### ISSUE TITLE
please use a mailing list for ng-grid

### ISSUE THREAD

**Issue by thkoch2001** [angular-ui/ng-grid#1264]
Hi,

I've some time again to do frontend stuff in our application and would like to catch up with ng-grid and test the current 3.0 state. But I've no place to look to see how things are going. Skimming through the last weeks of gitter chats is not really an option.

Gitter might be a useful tool for core developers, but it's not usable for people who can contribute only a few hours per month.

Please be so kind and consider using some kind of mailing list or google group.

Thank you!

**Comment by PaulL1** [comment]
Closing, as I think we're not going to do this.
