### ISSUE TITLE
Scrolling is a bit broken on Mac in Chrome and Safari

### ISSUE THREAD

**Issue by aptogo** [angular-ui/ng-grid#1426]
ngGrid doesn't handle scrolling well on the Mac - particularly in Chrome and Safari. Related issue https://github.com/angular-ui/ng-grid/issues/1425

ngGrid leaves blank space for horizontal and vertical scrollbars. But on the Mac, browser scrollbars should float over content:
![ui-grid info 2014-08-15 15-24-01 2014-08-15 15-24-08](https://cloud.githubusercontent.com/assets/442016/3934198/9d5a2d2a-2488-11e4-8a39-d7084e3bf823.jpg)

Funnily enough - ngGrid gets it right if RTL is set:
![ui grid 299 rtl support 2014-08-15 15-23-01 2014-08-15 15-23-25](https://cloud.githubusercontent.com/assets/442016/3934205/ae481c46-2488-11e4-8db9-18f561166049.jpg)

Also, horizontal scrolling while pinning columns is horribly broken:

![ui grid pinning 2014-08-15 15-26-47 2014-08-15 15-27-05](https://cloud.githubusercontent.com/assets/442016/3934211/c15e2834-2488-11e4-9a17-8ea34723a974.jpg)

**Comment by PaulL1** [comment]
I think this is fixed in the latest version of unstable, can someone look to see if it meets the original intent?

**Comment by c0bra** [comment]
Closing, no response in > 2 weeks.
