### ISSUE TITLE
Strange behaviour of editable cells, under some conditions afterCellEdit is called multiple times

### ISSUE THREAD

**Issue by lucassus** [angular-ui/ng-grid#1520]
The issue is pretty tricky to reproduce:

1. double click on a cell in order to invoke an input
2. hit ESC to close the input
3. double click again on the same cell
4. change value and submit
5. `gridApi.edit.on.afterCellEdit` will be invoked two times (or more if we close the input several times).

I'm trying to implement server side saving and in the outcome I have multiple ajax requests.

Take a look at this plunker http://plnkr.co/edit/pmQRweI5TnRpvImAHj5u?p=preview
![sc1](https://cloud.githubusercontent.com/assets/41239/4237063/d4d978ca-39cb-11e4-946e-6a0dd91f3c44.gif)

**Comment by swalters** [comment]
This was most likely fixed in 68a22aef65c67b9314855f852033da8c97a20476

**Comment by c0bra** [comment]
Closing, no response in > 2 weeks.
