### ISSUE TITLE
ng-grid does not allow 'controller as' syntax for options.data

### ISSUE THREAD

**Issue by ghost** [angular-ui/ng-grid#1525]
As mentioned in Issue #1040 , this is still broken.

**Comment by HeebaSteve** [comment]
I am thinking this was the same problem I had. I was using ui-grid RC 19. when i was setting up my grid, I set the data to what my view would call it as.

data: 'mainCtrl.gridData'

I am thinking this is the same problem I had getting my data to populate my grid using the controller as syntax and this worked for me.

**Comment by c0bra** [comment]
@HeebaSteve this issue is for versions falling under 2.x.  It should work in 3.0 but maybe not 2

**Comment by c0bra** [comment]
OK I'm going to go ahead and close this as 2.x will not be updated unless a PR is sent in.

Just a note: here's a plunker demonstrating how to do this with v3+: http://plnkr.co/edit/D48xcomnXdClccMnl5Jj?p=preview  It's just standard Angular code.
