### ISSUE TITLE
Compatibility issues on mobile devices

### ISSUE THREAD

**Issue by joemanfoo** [angular-ui/ng-grid#1551]
Reviewing the current site as well as the 2.0 site (http://ui-grid.info/docs/#/tutorial/) on an iOS device has some functionality of ng-grid not working.  Filtering doesn't work, sorting, scroll bars on the grid do not appear.  

Some grid examples on the existing site (http://angular-ui.github.io/ng-grid/) do not show up at all, just blank space where the code and table example would be.

**Comment by usn1485** [comment]
Thanks mathieu-ma, your suggestion worked. commenting lines 2424 and 2490 (event.preventDefault()) in the file ui-grid.js works.

**Comment by PaulL1** [comment]
This looks to be mostly working - I've just looked through the tutorials with my iPad.  

I'm going to close this issue down, and then suggest that people raise specific point issues for any remaining mobile device compatibility issues.

**Comment by omanyak** [comment]
Are you going to add the fix into the nearest release?
