### ISSUE TITLE
[3.0] Pinned container header viewport is calculated too wide

### ISSUE THREAD

**Issue by c0bra** [angular-ui/ng-grid#1590]
This doesn't present any rendering issues, but should probably be fixed.

To reproduce: look at the row selection tutorial and in your console, do: `$('.ui-grid-render-container-left .ui-grid-header-viewport').offsetWidth`

It will be like 600+ pixels rather than the 30px that it should be.  This is probably a simple fix in the render container calculation.

**Comment by PaulL1** [comment]
Doing this now returns 35px.  I believe that means it's fixed, closing.
