### ISSUE TITLE
UI Grid 3.0 paging example

### ISSUE THREAD

**Issue by mplayer** [angular-ui/ng-grid#1624]
is there an example of server and client side paging for ui-rid 3.0

**Comment by c0bra** [comment]
Paging is now in ui-grid.

**Comment by dipankarpaul** [comment]
I have also faced the UI-Grid Pagination Design issue in IE9. I have resolved this issue with the help of CSS. Follow the below link.... Hope this will help.

[http://dp1981.blogspot.com/2016/07/ui-grid-ie9-pagination-issue.html]
