### ISSUE TITLE
Directive Based Design

### ISSUE THREAD

**Issue by amcdnl** [angular-ui/ng-grid#1632]
Following a conversation on gitter, I'd like to propose directive based design.  This would be an alternative to the simple solution if a user described their layout using these child directives.

It would allow for removing templates and the 'external scope' variables.

I've actually started my own implementation: https://github.com/phxdatasec/ng-table that I'd be interested in merging if you would be interested.

**Comment by c0bra** [comment]
Going to close this as the dev team is not going to invest time into pursuing this. There's not enough man hours to even cover the bug fixes so this sort of thing is out of the question.
