### ISSUE TITLE
cell merge (create single row by merging all the cells)

### ISSUE THREAD

**Issue by yrojha4ever** [angular-ui/ng-grid#1663]
Its not duplicate question with other cell and row merge question.

![image](https://cloud.githubusercontent.com/assets/4167541/4478161/57ab3290-4983-11e4-8ecb-a822dde87f50.png)

Is this possible?

**Comment by PaulL1** [comment]
I believe that merging cells can be handled through custom rowTemplates, with a bit of fiddling around.  I have added a basic example of this to the 317 templates tutorial.
