### ISSUE TITLE
Extend grid menu

### ISSUE THREAD

**Issue by PaulL1** [angular-ui/ng-grid#1671]
The aim of the grid menu is to have a home for user actions that can be taken on the grid as a whole.

The most immediate need is to provide a way to show columns that have been hidden, similar to in 2.x.  But other features might also make use of it, including the exporter.  It might also be desirable to let an end user control some core gridOptions, for example to turn filtering on and off (as an example).

The general look and feel of the menu would be similar to 2.x - a menu button in the top right, which floats above the core grid.  The columns would scroll underneath it.  The main issue with this is that it would overlay the column menu for the rightmost column - which might be in the body renderContainer, or might be in the right renderContainer.  The header (or at least the columnMenuButton) for this column would need to be moved inward a little.

The menu itself should use the existing gridMenu, and should be switchable (so it can be turned off) and customisable (so the developer can add items to it if they wish).

**Comment by PaulL1** [comment]
I've fixed the last remaining planned item - making space in the rightmost column for the grid menu.  I've added a margin-right on the rightmost column's column-menu-button.  If the rightmost column isn't wide enough for the title this can overlay in an ugly way, but I think that's already a problem with column menu overlaying the title if the column isn't wide enough.

**Comment by lvostinar** [comment]
This last commit breaks the display of last column for us. We use no grid menu. See:
http://plnkr.co/edit/tM4e5Ng8dcJfKM6ZdKl7?p=preview The sort arrow of last column is displayed wrong. 

I think:
ng-class=\"{'ui-grid-column-menu-button-last-col': isLastCol}\"

should become

ng-class=\"{'ui-grid-column-menu-button-last-col': isLastCol && grid.options.enableGridMenu}\"

**Comment by JLLeitschuh** [comment]
Can you open this as a new issue?
