### ISSUE TITLE
[3.0][Column Resize] Column resize function works incorrectly after hiding columns

### ISSUE THREAD

**Issue by namminh2005** [angular-ui/ng-grid#1697]
After hiding some columns, i try to resize other visible columns but sometime it works incorrectly. 

You can reproduce it by following these steps:

Step 1: Go to tutorial "401 All Feature"  and refresh data
Step 2: Hide Address.Street column
Step 3: Try to resize Age column to right side few times

BUG: Sometime Address.City is resized instead of Age column. It happens to the other columns as well.

If you can't reproduce it or there is any point you dont understand, pls tell me.

Thank you. I'm looking forward to you response.

Write Preview Parsed as Markdown  Edit in fullscreen

**Comment by PaulL1** [comment]
I've fixed this, I did quite a big refactor on resize to achieve it.  The tutorial now includes column move to make it easier to see this working.
