### ISSUE TITLE
make filter types customizable

### ISSUE THREAD

**Issue by thkoch2001** [angular-ui/ng-grid#1703]
ui-grid provides only a text filter type. I need additional filter types for integer ranges, bool, date ranges, selectboxes and multi-selectboxes.

I think one approach could be if I could provide a 'template' for my filter that gets included instead of the default filter.

**Comment by PaulL1** [comment]
This has been provided in two ways:
1.  There are more standard types
2.  There is the capability to define custom filters using a filter directive.

Closing.
