### ISSUE TITLE
Additional pin menu items are added to column menu with column resizing

### ISSUE THREAD

**Issue by Hoakie** [angular-ui/ng-grid#1738]
Each time a column is resized, a  new set of pin menu items is added to the column menu (pin left, pin right).

<div id="grid1" ui-grid="gridOptions" style="width:auto; height:auto" ui-grid-pinning ui-grid-resize-columns></div>

![image](https://cloud.githubusercontent.com/assets/5766742/4545690/116e7d00-4e3d-11e4-9910-af24ca2a223a.png)

**Comment by PaulL1** [comment]
I believe this was resolved some time ago, and checking I don't see it happening on tutorials any more.  Closing.
