### ISSUE TITLE
How to insert a new row in grid?

### ISSUE THREAD

**Issue by balakrishnan051** [angular-ui/ng-grid#1739]
I just inserted a new row in grid but it always displayed as last row.
here is the http://plnkr.co/edit/geHyRzsAzSGruVzuCi29?p=preview

**Comment by PaulL1** [comment]
Closing as no response for some months, and believe this is now working.

**Comment by pmariduena** [comment]
I concur, it works for me now on 3.0.0-rc15

**Comment by nareshnraj** [comment]
PaulL1, I was goin through your plunker sample. If I am adding a new row and saving it to the grid. I want to apply an external save button. By which the newly added record is added to the DB. Then how about its refreshing the grid.
