### ISSUE TITLE
Infinite scrolling using the scroll bar

### ISSUE THREAD

**Issue by wattsbn** [angular-ui/ng-grid#1748]
Trying to scroll using the scroll bar while infinite scrolling is enabled is quite difficult at the moment. Once you load a new page of data the scroll bar jumps up the page a little while your mouse is still going down. I think the easiest way (maybe not the best but certainly better) to fix this is may be to force the dragging events to stop once you make a request for more rows.

**Comment by c0bra** [comment]
Since we've moved to using native scroll bars on the viewport we don't have any control over this behavior. I'm going to close this ticket as it's unavoidable.
