### ISSUE TITLE
Horizontal scrollbar screwiness with grid that's 100% of container

### ISSUE THREAD

**Issue by c0bra** [angular-ui/ng-grid#1758]
As of 3.0.0-rc.11-174f252.

For a demonstration check the index page of the site ( http://ui-grid.info/ ), then try to scroll the horizontal scrollbar. Initially the width of the bar is all the way across the bottom of the grid, then it becomes really small. like 10-15px wide... no idea why.

**Comment by PaulL1** [comment]
The scrolling has been substantially refactored - is this problem still occurring?

**Comment by PaulL1** [comment]
Believed to be fixed in recent changes, no updates from information request, assuming is resolved and closing.
