### ISSUE TITLE
Every example in Tutorial mis-references CSS

### ISSUE THREAD

**Issue by amac44** [angular-ui/ng-grid#1769]
Is it me or does every example in the tutorial contain:
&lt;script src="/release/ui-grid-unstable.css"&gt;&lt;/script&gt;

Shouldn't this be &lt;link rel="stylesheet" href="/release/ui-grid-unstable.css" /&gt; ?

For example, line 10 in http://ui-grid.info/docs/#/tutorial/102_sorting . But every example has it the same way.

Or am I missing something.

**Comment by PaulL1** [comment]
Closing on the basis that it doesn't break anything, and it's an upstream problem.
