### ISSUE TITLE
UI-Grid header height miscalculation leads to header growth

### ISSUE THREAD

**Issue by keeper3000** [angular-ui/ng-grid#1776]
The old ng-grid issue has returned in ui-grid.

When in a bootstrap tab ui-grid version rc12 will not render the grid.  Instead renders just a vertical scroll bar with no contents.  When pulled outside of a tab the grid renders normally.

Using an old trick does not work.: 
    $scope.fixGridInTab = function(){
        window.setTimeout(function(){
            $(window).resize();
            $(window).resize();
        }, 1000);
    };

Additional details:
- Bootstrap 3.2
- ui bootstrap 11.2
- angular 1.3-rc4

**Comment by PaulL1** [comment]
Checked and the header growth is still occurring on current code base.

**Comment by dzannotti** [comment]
yep still happens, 

temporary fix still valid
.ui-grid-header-cell{
height:27px;
max-height:27px;
}

**Comment by Siafu** [comment]
dzannotti that trick doesn't work for me. I tried adding the css to ui-grid.css and my custom styles.css to no avail.

**Comment by dzannotti** [comment]
@Siafu 
try to force a $('body').trigger('resize'); after the grid content is loaded, that should fix it. The previous post was regarding the zip on website, for master build credit to @giovannicalo for fixing it.

**Comment by PaulL1** [comment]
The key issue in here was that from @keeper3000 of the grid header growing whenever resize was called.  I've updated his plunker to use the latest angular, ui-grid etc, and that seems to have the issue go away: http://plnkr.co/edit/uM50PfGaxQIAR8dEwJTI?p=preview

On that basis, I'm closing the issue.

**Comment by chedched** [comment]
This is probably not the ideal place to post this, but as I don't know any better:

Thanks to this thread here I was able to put a grid inside a tab, and set tabs active with a button: http://plnkr.co/edit/EP3lFcsXqU8GfpRSYOxY. But when I use the exact same code in my local code (instead of the $http-request I simply hardcoded the data), the grid just shows up **exactly every second time** I click the button that makes the tab containing the grid active.

I've no clue why and can't even provide a proper plnkr, of course I'm aware that it's super likely some issue in my code. Has anyone every experience something similar and can give me a hint?

**Comment by PaulL1** [comment]
Yeah, I've had this before.  It's to do with the toggling of the active - you're toggling only on going to active, but not turning it off again when another tab comes active.  So you're toggling each time you enter the tab, not when you exit as well.  Hence it toggles off the first time you go there, toggles on the second time you go there, etc.

**Comment by chedched** [comment]
Thanks a lot for your (fast) help, I really appreciate it!

**Comment by tirams** [comment]
This problem is still happening using ui-grid v3.0.0-rc.20

**Comment by mihaitudor** [comment]
I struggled with the same problem for the better part of today (even though it's not related to a tab, my grid is inserted into a regular div, can't say exactly what's causing it to behave that way because I've been using it in other parts of the UI without coming across it). My solution is a variation of the css workaround proposed here (which didn't work for me):

.ui-grid-header {
	height: 25px;
	max-height: 25px;
}

**Comment by mliq** [comment]
mihaitudor's solution worked for me except that now the normal headings are too far from the top and hence cut off, and I can't seem to fix it, any ideas?

**Comment by nsupathy** [comment]
None of the solutions proposed here worked for me.  I am not even loading the grid in a tab.  The grid appears on pressing a button though.

When I created a plunker with the similar code, the plunker seems to work fine. So I cant really show the problem I am having.  I tried 3.0.1, 3.0.6 and unstable versions.  None worked so far.  
Chrome dev tools show the ui-grid-header-cell-wrapper and ui-grid-header-cell-row as 1123px*345px and the header cell seems to be filled up by padding-bottom.

**Comment by pavantambay** [comment]
I hit the same issue as mentioned by "nsupathy". We are using ui-grid - v3.0.0-rc.20-b41275e. Still searching for a solution, have not found anything so far.

**Comment by pavantambay** [comment]
overriding the default provided CSS ".ui-grid-header-cell-wrapper{position:relative;display:table;box-sizing:border-box;height:'100%'}" with this following one ".ui-grid-header-cell-wrapper{position:relative;display:table;box-sizing:border-box;height:initial}" worked out GOOD for me.

**Comment by lonepilgrim** [comment]
.ui-grid-header {
    height: 25px;
    max-height: 25px;
}

Worked for me.

**Comment by thezuck** [comment]
had the same problem, but only 
.ui-grid-header-canvas {
    height:27px;
    max-height:27px;
}
worked in my case.

**Comment by brianmriley** [comment]
The above fix worked for me as well:

```css
.ui-grid-header-canvas {
	height:     27px;
	max-height: 27px;
}
```

I also couldn't recreate the issue on plunker. I'll need to spend some more time recreating it as the culprit wasn't obvious.

**Comment by madfrog2047** [comment]
@pavantambay 's solution is worked for me.

**Comment by gornostal** [comment]
Issue still persists. I'm rendering grid in a tab.
Workaround mentioned above worked for me.
