### ISSUE TITLE
Scrolling with images is slow

### ISSUE THREAD

**Issue by chrisforgy** [angular-ui/ng-grid#1783]
Displaying images as column in the grid causes slow scrolling in Firefox and Safari on iPad.

I'm using this cell template:
```
"cellTemplate": "<img height=\"30px\" width=\"50px\" max-height=\"30px\" max-width=\"50px\" ng-src=\"{{row.getProperty('thumbnail')}}\" >"
```
Using Chrome or Safari on the desktop, scrolling is fast and smooth.  Definitely much better than the old ng-grid.  Trying FireFox or Safari on an iPad, scrolling is choppy and slow.

**Comment by PaulL1** [comment]
I think this will always be problematic given images and rendering them via cellTemplates.  Recent scrolling changes should make this better, and we still have pending open thoughts on improving scroll performance.  I see no value in leaving this specific issue open.  Closing.
