### ISSUE TITLE
grid RebuildGrid on data change

### ISSUE THREAD

**Issue by eranmit85** [angular-ui/ng-grid#1790]
Hello, 
I'm trying to create an ng-grid with re-sizable columns and dynamic data.
The issue is that every time I change the data collection the grid sets off the RebuildGrid function which sets my  columns width back to default.

is this a known bug ? will it be solved?

Thanks 

Eran

here is my test code: 

(function (angular) {
    'use strict';

    var controllerId = 'mainCtrl';

    function mainCtrl($scope) {

        function init() {

            $scope.name = 'Test';

            $scope.myData = [{ name: "Moroni", age: 50 },
                   { name: "Tiancum", age: 43 },
                   { name: "Jacob", age: 27 },
                   { name: "Nephi", age: 29 },
                   { name: "Enos", age: 34 }];

            $scope.addRow = function () {
                $scope.myData.unshift({ name: "aaaaaa", age: 1000 });
            }

            $scope.gridOptions = {
                data: 'myData',
                virtualizationThreshold: 1,
                rowHeight: 30,
                multiSelect: false,
                showGroupPanel: true,
                showFilter: true,
                showFooter: false,
                enableColumnResize: true,
                enableColumnReordering: true,
            };
        }

        init();
    }

    angular.module('app').controller(controllerId, ['$scope', mainCtrl]);

}(window.angular));

**Comment by PaulL1** [comment]
I believe I fixed this a while back - could you restest?

**Comment by PaulL1** [comment]
Believed to be fixed in recent changes, no updates from information request, assuming is resolved and closing.
