### ISSUE TITLE
infinite scroll doesn't work if the extra data comes without server call (hard coded data)

### ISSUE THREAD

**Issue by OrenHasbani** [angular-ui/ng-grid#1797]
scenario: 
go to http://plnkr.co/edit/macCJJN5rrDGzk18OMjM?p=preview
scroll down
after the first insertion of new data, there won't be more extra data. (will stop on 199 items)

why? after debug it for a while, i understand that the mechanism was developed to support server calls (or any deferred object that doesn't activate its success function straight - the common usage). 

for my workaround i wrapped the handler with $timeout(... ,1) to demonstrate server call.

FYI,
Oren.

**Comment by c0bra** [comment]
@OrenHasbani I'm not seeing the behavior you've described on that plunker any more. Can you confirm that it's fixed, please? Thanks.

**Comment by OrenHasbani** [comment]
Yeah @c0bra  it seems that the bug doesn't happen any more.
The bug is fixed.

**Comment by c0bra** [comment]
Great. Thank you.
