### ISSUE TITLE
3.0: Document the grid initialisation sequence for new contributors

### ISSUE THREAD

**Issue by PaulL1** [angular-ui/ng-grid#1818]
We need to document the sequence that the grid runs through to initialise, including when to use each of grid.refresh, grid.refreshCanvas, grid.refreshRows, and what some of the core methods like modifyRows and setVisibleRows need to do.

As the usage of the grid ramps up we'll both have more bugs and probably more contributors, having this in place would make it much easier for people to come up to speed with the project.

**Comment by PaulL1** [comment]
Completed - refer http://ui-grid.info/docs/#/api/design-rendering-cycle

**Comment by thatguyyoulove** [comment]
@PaulL1 This page shows up blank for me. Was it removed?

**Comment by PaulL1** [comment]
The document is still here: https://github.com/angular-ui/ui-grid/blob/master/design/RENDERING_CYCLE.md

Not sure why it's stopped showing in the design docs, presumably someone has changed something in the config.
