### ISSUE TITLE
[3.0][Scrolling] Working incorrectly in some conditions

### ISSUE THREAD

**Issue by namminh2005** [angular-ui/ng-grid#1824]
Hi,

Today, i got some errors when testing scroll functions. 
+ **Hortizontal scrolling**: When scrolling fast in grid with many columns, sometime when the scroll bar reach the left side of grid, the arrow < (move to left) is disabled but the columns aren't rendered completely.
  > I tested on tutorial page: 191 Hortizontal scrolling.

+ **Vertical scrolling**: When data rows total height is close to grid height, the scroll bar is disabled but i still can scroll the grid using mouse wheel.
  > I tested on my app with default grid options

+ **Images**:
    + **Horizontal**:
![image](https://cloud.githubusercontent.com/assets/9007173/4641575/d47eab88-5439-11e4-93ce-5d7434bc082c.png)

    + **Vertical**:
![image](https://cloud.githubusercontent.com/assets/9007173/4641603/41c3ce08-543a-11e4-9c1c-cb839a9b3c2e.png)

**Comment by PaulL1** [comment]
OK, a lot of further work has gone into scrolling in the last few weeks.  Could we test again, perhaps allowing us to close?

**Comment by c0bra** [comment]
No response in > 2 weeks. Closing.
