### ISSUE TITLE
sometimes css style height is directly set on the div of the grid (gridheight < rowheight)

### ISSUE THREAD

**Issue by jcompagner** [angular-ui/ng-grid#1829]
in ui-grid controller this code is there:

  // If the grid isn't tall enough to fit a single row, it's kind of useless. Resize it to fit a minimum number of rows
              if (grid.gridHeight < grid.options.rowHeight) {
                // Figure out the new height
                var newHeight = grid.options.minRowsToShow * grid.options.rowHeight;

                $elm.css('height', newHeight + 'px');

                grid.gridHeight = $scope.gridHeight = gridUtil.elementHeight($elm);
              }

so if that if is hit then height is directly set on the div element of the grid itself

But what ever i do then afterwards to make sure that the grid does have the right size like:

$timeout(function(){
         		 $scope.gridApi.grid.gridWidth = gridUtil.elementWidth($element);
         		 $scope.gridApi.grid.gridHeight = gridUtil.elementHeight($element);
         		 $scope.gridApi.grid.refreshCanvas(true);

that doesn't help because that elements height is never reset or set..

i really need to do:

 $element.children(".svyPortalGridStyle").height('');

where that child is the div where ui-grid is binded on.

Maybe the problem is a bit that in a specific situation the parent is not layout yet completely in the dom. it doesn't really have a height or width yet.
So ui-grids post controller code does get run a bit to soon and it works with the wrong sizes

In my timeout that i run when i get the callback from:
  $scope.gridOptions.onRegisterApi = function( gridApi ) {
     $timeout(xxxxxxx

then i just have to set the sizes correctly.
(and also really remove that height property)

**Comment by PaulL1** [comment]
Closing, no comments since last year.
