### ISSUE TITLE
Scroll bar covers the cell data as using 'text-align: right' by cellClass.

### ISSUE THREAD

**Issue by archerchiu** [angular-ui/ng-grid#1878]
Hi, I found the situation as title and the horizontal scroll bar does not appear. Whether the scroll bar should not occupy the space of grid content?
### cellClass css
`.pass.ui-grid-number-cell {
    text-align: right;
}`
### render result
![2014-10-21 09-59-27](https://cloud.githubusercontent.com/assets/2604264/4712295/fbfba3b4-58cb-11e4-9fdf-e5243e3157ba.png)

**Comment by PaulL1** [comment]
I think this issue is now resolved, @archerchiu could you perhaps review and confirm so that we can close?

**Comment by rupampatel2006** [comment]
@PaulL1 last week i was still facing this issue and had put workaround. I can look again and will get back.

**Comment by PaulL1** [comment]
Believed to be fixed in recent changes, no updates from information request, assuming is resolved and closing.
