### ISSUE TITLE
Sub-grid vert scroll erratic & scroll bar out of possition

### ISSUE THREAD

**Issue by jiggak** [angular-ui/ng-grid#1884]
![scroll_bug](https://cloud.githubusercontent.com/assets/301982/4724568/c5855d4e-5951-11e4-8b81-1fb360072188.png)

Plunker that reproduces the bug:
http://plnkr.co/edit/gICZRtxBrmFO2MOozhcV

ui-grid: v3.0.0-rc.12-55116d1
Chrome: 38.0.2125.104

This affects the sub-grid when using expanded grid module. The vertical scroll bar appears to be shifted down and to the left of where it should be.

The scrolling behavior of the sub table is also very erratic. The scrolling direction appears to be reversed and the rows "bounce" around when scrolling.

**Comment by c0bra** [comment]
I just checked this plunker and the behavior appears to be fixed. @jiggak please reopen if it's not fixed for you.
