### ISSUE TITLE
Q: Is it possible to add a class to the current sorted column?

### ISSUE THREAD

**Issue by samhenri** [angular-ui/ng-grid#1905]
Is there a way to add a css class to the current sorted column? I've been trying to do this but so far, no success.

**Comment by PaulL1** [comment]
Assuming issue raiser has resolved their issue, as no comments for nearly 3 weeks.

**Comment by mikeytag** [comment]
Ok, so I came across this old thing but I wanted to update with one small change to @PaulL1 's solution. His answer got me on the right track but the if condition needs to change slightly. My col.sort is always evaluated as true it's an object. Rather you want to do a conditional on whether or not priority is defined.

`gridoptions.columnDefs[0].headerCellClass = $scope.highlightHeader;

  $scope.highlightHeader: function( row, rowRenderIndex, col, colRenderIndex ) {
    if ( typeof(col.sort.priority) !== 'undefined'  ){
      return 'header-sorted';
    }
  };`
