### ISSUE TITLE
Header spacing where scroll bar used to be when data reduced

### ISSUE THREAD

**Issue by mschreibernaoual** [angular-ui/ng-grid#1919]
I am trying to find a solution to spacing on the right side of the header when the data in the grid is filtered and reduced in size.

How do I force a refresh of the headers when the scroll bar is removed? 

Or should I keep a scroll bar permanently on the grid?

**Comment by PaulL1** [comment]
I suspect that with all the changes in scrolling and filtering, this is long ago resolved.  Could you confirm?

**Comment by PaulL1** [comment]
Closing: solution proposed that should resolve the issue, no further comments for 2 weeks, assuming solution has resolved issue.
