### ISSUE TITLE
ng-grid examples don't work out of the box

### ISSUE THREAD

**Issue by rkpantangi** [angular-ui/ng-grid#1922]
I am trying this API first time and I am very disappointed the examples just don't work out of the box. THought the tutorial looks quite extensive, when I try to copy the code in the below and link and run it, it doesn't display any table. Basiclaly ng-controller etc. tags are not resolved. Help please? and please fix them to motivate more people to use it!
http://ui-grid.info/docs/#/tutorial/103_filtering

**Comment by c0bra** [comment]
You can download UI-Grid by using the "Download Zip" button on the bower-specific repo: https://github.com/angular-ui/bower-ui-grid/archive/v3.0.0-rc.20.zip

Closing this issue as it no longer seems to apply.
