### ISSUE TITLE
Horizontal scroll of of sync between scrollbar and viewport

### ISSUE THREAD

**Issue by SamarRizvi** [angular-ui/ng-grid#1938]
When you drag the horizontal scroller too fast, the scroller comes to starting point but the relevant column does not. As you see in the image, the horizontal scroller is at the starting point, but it is showing Col100 but instead it should show Col0. You can test in plunker here: http://plnkr.co/edit/IFjejWE0hlOXZhFa3WTk?p=preview
![screenshot](https://cloud.githubusercontent.com/assets/1614414/4804495/4032a194-5e6d-11e4-9bdd-520f0ae1bddb.jpg)

**Comment by PaulL1** [comment]
I believe this will now be resolved given the scrolling changes.  Could you retest?

**Comment by PaulL1** [comment]
Believed to be fixed in recent changes, no updates from information request, assuming is resolved and closing.
