### ISSUE TITLE
Overwrite columnDefs requires new UID to be handled

### ISSUE THREAD

**Issue by OrenHasbani** [angular-ui/ng-grid#1948]
i want to change columns position dynamically, so i changed the position of the first column to be the last, but noting happen.  i tried to use the api grid.refresh()  after the reordering (and also inside $timeout like in 'ui.grid.moveColumns' feature) without success either.  
i edit your "all features" plunker and made one that demonstrates my problem.
http://plnkr.co/edit/7qvlbMhL5b24ugeUf8j4?p=preview

To solve the problem i made a work-around:
instead of: 
$scope.moveFirstCellToBeTheLast = function () {
    var temp = $scope.cols[0];
    $scope.cols.splice(0,1);  
    $scope.cols.push(temp);
  }

i wrote: 
$scope.moveFirstCellToBeTheLastWorkArround = function () {
    var temp = $scope.col1[0];
    $scope.col1.splice(0,1);  
    $timeout(function () { $scope.col1.push(temp); });
  }
so the grid "think" that the columns was removed (so it refreshed itself once) and than i add another column so it refreshed itself again.

BUT, all the grid flickered twice, and this work around won't satisfied all the possible situations of programmatically columns reordering. 

I want to know if there is a better way to do it (by api for example) or right now this action is not supported?

Thanks a lot,
Oren.

**Comment by c0bra** [comment]
Update: this is going to be a more difficult solve than initially thought.

1. The grid fires the `uiGridConstants.dataChange.COLUMN` callbacks before the grid definition actually changes, so when I check the UIDs in the callback handler they haven't changed yet.
2. The grid only changes the column UIDs on the initial swap. On the 2nd-Nth swap the UIDs are no longer altered. A more robust rewrite of columnDef changing will be needed, most likely.
