### ISSUE TITLE
Footer template duplicating  ui-grid 3.0

### ISSUE THREAD

**Issue by mplayer** [angular-ui/ng-grid#1956]
When using a custom footer and using the ui-selection directive for ui-grid 3.0  the footer is being duplicated inside of the selection column.

**Comment by PaulL1** [comment]
I believe this is no longer occurring - could you confirm?  My plunker: http://plnkr.co/edit/yYLCBBmBB30ljOaxsdst?p=preview

**Comment by PaulL1** [comment]
Believed to be fixed in recent changes, no updates from information request, assuming is resolved and closing.
