### ISSUE TITLE
Add tutorial for retreiving data for subgrid via $http

### ISSUE THREAD

**Issue by russgove** [angular-ui/ng-grid#1960]
The tutorial for subgrids has the subgrid showing data that is in the scope of the parent grid. I think a more 'real-life' scenario is to get the subgrid data using an http call.

I started looking at this and realized the subgrid shares scope with the partent grid, while I kind of thought it would have its own scopy.

Anyway, I'm looking for a pattern for showing data on a subgrid, using info retrived via http.

The sample app has the subgrid created using a template with  ui-grid="row.entity.subGridOptions".

So I would assume that when the rowExpandedStateChanged event fires, I can call the $http method and stuff the returned data into row.entity.subGridOptions.data. Would that be a recommended approach?

Any examples of this anywhere?

**Comment by PaulL1** [comment]
PR is merged, assume this is resolved, closing.
