### ISSUE TITLE
Vertical scrollbar obscures part of last column

### ISSUE THREAD

**Issue by Dev63** [angular-ui/ng-grid#1993]
When you express col widths as a %, adding up to 100%, the last column is partially obscured by the vertical scrollbar.  This is fine, unless that column is right-justified, in which cast you end up not being able to see the last couple of digits.  

![image](https://cloud.githubusercontent.com/assets/9340860/4878934/4e4c7e94-631d-11e4-8681-26003c4ee56c.png)

It would be nice if the grid just drew the table cells into their reduced space.  But I wouldn't want to have this "fixed" by leaving a big white gap above the scrollbar (ugly), the way the horizontal scrollbar leaves a gap when row selectors are present.

I tried to work around this by having the col widths add up to 98%, but the current version seems to treat percentages as relative sizes, and always adds up to 100% (in proportion).  Even if my col widths only sum to 50%.

**Comment by PaulL1** [comment]
I think this should be fixed in master now - could you retest @Dev63?

**Comment by Dev63** [comment]
@PaulL1 No, this is still behaving the same.  Using a `cellClass:'text-right'` as the last column makes this obvious, but it happens to every column regardless of justification.

**Comment by PaulL1** [comment]
OK, I don't get scroll bars as I'm on OSX, but @swalters, do you want to look at this too?

**Comment by c0bra** [comment]
This was fixed by e099c5b5721afc
