### ISSUE TITLE
Fron page download link is non-sensical

### ISSUE THREAD

**Issue by c0bra** [angular-ui/ng-grid#2037]
Saw this on SO: http://stackoverflow.com/questions/26065099/how-do-i-download-the-angular-ui-grid/26805231

The download link doesn't actually let you *download* anything. It should probably either be removed (for now) or fixed to link to a real downloadable file. We would need to create them somehow, though...  We could download from the bower repo but the name would be weird (bower-ui-grid).

**Comment by PaulL1** [comment]
I think this is working adequately now - it takes you to an archive of built versions from which you can download.  Closing.
