### ISSUE TITLE
Slow row-by-row comparison when swapping data.

### ISSUE THREAD

**Issue by dshaver1** [angular-ui/ng-grid#2039]
I'm working with ui-grid v3.0.0-rc.12.

I have a grid which displays around 20,000 rows, and I occasionally need to swap out the data of this grid with a completely new set of 20,000 rows. It seems that ui-grid is doing a row-by-row comparison in order to modify each row to match the new dataset. This is less than ideal for a dataset of this size.

I was able to work around it by first setting the dataset to only 1 row of dummy data, then going ahead to load the actual data.

To illustrate slow workflow: (30 - 60 seconds to load)

1. Load original data. This is quick because there is nothing to compare to.
2. Load new data. This is slow because it's comparing old with new. 

vs. my hacky workaround: (2 - 5 seconds to load)

1. Load original data.
2. Load tiny dummy dataset.
3. Load new data.

Is there a better way to reset the data for a grid? 

Chrome's profiler says I spent 32 seconds on line 2902 of ui-grid.js:

```javascript
self.grid.modifyRows(n)
```

**Comment by PaulL1** [comment]
I think we now have a hashMap in this area, which should be improving this performance.  Closing.

**Comment by joshjung** [comment]
Awesome, thank you!
