### ISSUE TITLE
Horizontal virtualization + filtering with non-present value causes render bug

### ISSUE THREAD

**Issue by kavinnashi** [angular-ui/ng-grid#2047]
Hi can anyone please help me with a solution for this question
http://stackoverflow.com/questions/26763235/ng-grid-horizontal-scroll-issue

**Comment by PaulL1** [comment]
I think this has been resolved somewhere along the way, as it appears to not be happening any more.  Could you confirm so we can close @kavinnashi?

**Comment by kavinnashi** [comment]
yeah you can close @PaulL1
