### ISSUE TITLE
Trying to enable enableFiltering option dynamically

### ISSUE THREAD

**Issue by rubenjimenez** [angular-ui/ng-grid#2067]
Hi,

As the title says, I'm trying to activate the enableFiltering dinamically, but i can't and i don't know why. I can change the enableCellEdit behavior on the fly, but the same process doesn't work for enableFiltering.

I'm doing next:

```
var options = angular.copy($scope.gridOptions[$index]);

options.enableFiltering = true;

$scope.gridOptions[$index] = options;

for ( var i = 0, j = $scope.gridOptions[$index].columnDefs.length; i < j; i += 1 ) {
  $scope.gridOptions[$index].columnDefs[i].enableFiltering = true;
}

$scope.gridApi[$index].core.refresh();
```

$scope.gridOptions is an array because i'm showing a lot of grids.

What am i doing wrong?

Thanks.

**Comment by iooi** [comment]
+1. i'd love to have this feature, as there are many scenarios that we want to toggle the filter areas

**Comment by PaulL1** [comment]
I believe this is now implemented, I think I saw someone else push the request a couple of weeks back.  Can we confirm?

**Comment by ssonnenwald** [comment]
Has this been pushed out yet?  Doesn't seem to be.  I just pulled the latest a day ago.  I know you were waiting for a response on this, but just wondering.

**Comment by PaulL1** [comment]
Sorry, I appear to have failed to merge it.  Merging now.

**Comment by paambaati** [comment]
@PaulL1 Quick question. If my data is all dynamic and I've set `$scope.gridOptions.enableFiltering` to `true`, how do I set `enableFiltering` to `false` for a specific dynamic column after all the data is fetched? If I try to access `$scope.gridOptions.columnDefs`, it is just an empty array.

**Comment by PaulL1** [comment]
Hmm.  We don't really deal with that situation.  You can get the gridApi via onRegisterApi, and then modify grid.columns[x].colDef directly.  I'm not sure it's a great idea, but it'd probably work and I can't think of any downsides other than it not being a documented API.

**Comment by paambaati** [comment]
@PaulL1 Thanks for the quick response. Although, when I try to do `console.log(gridApi.grid);` I see all the items in `grid`, including `columns` and all their `colDefs`. However, when I try to do `console.log(gridApi.grid.columns);`, I see an empty array. What gives?

**Comment by PaulL1** [comment]
Most likely timing?  Has the data loaded at this point?  Or try gridApi.grid.columns[0]?

**Comment by paambaati** [comment]
@PaulL1 My guess is timing too. In the success callback of my remote data fetch, I set `$scope.gridOptions.data` to the data, and immediately afterwards, I try to look at `gridApi.grid.columns[0]` and it is undefined. Is there a callback for data-load complete for ui-grid?

**Comment by PaulL1** [comment]
Yes, you need a $timeout before you can look at the columns after you set the data, if you're relying on the grid to define the columns based on the data.

**Comment by W-prog** [comment]
Hi everybody,
I have the same prob and i'va resolve with defined a fake field in 1st gridOption
After, I defined the columnDef dynamically
If i don't first defined the fake field, the filter don't work. I don't know why.
