### ISSUE TITLE
Expandable grids freak out when resized

### ISSUE THREAD

**Issue by mburbea** [angular-ui/ng-grid#2074]
If a grid is configured to have expandable option and re-sizable when you resize the grid it will "freak out" and bounce out of its container when you reduce the amount of space for the grid. This issue happens in chrome 38, IE 11 and firefox 26.
I've captured a screenshot. 
![image](https://cloud.githubusercontent.com/assets/213233/5014145/60cad1a6-6a61-11e4-98a3-fe49233b67e4.png)

**Comment by PaulL1** [comment]
I fixed #1957, which was a similar issue to do with pinned columns.  I suspect it has also fixed this one, could you retest?

**Comment by mburbea** [comment]
I'll check it out I've not tried using the project from sources before.

**Comment by PaulL1** [comment]
Any progress with checking this out?

**Comment by mburbea** [comment]
Sorry, I'm no longer using ui grid so I haven't had a chance to try this
bug out.

**Comment by PaulL1** [comment]
OK, I'll assume that it's covered then, it will get re-raised if someone else sees it again.
