### ISSUE TITLE
Server side paging UI looks fractured

### ISSUE THREAD

**Issue by rupampatel2006** [angular-ui/ng-grid#2101]
Hello folks,

First of all thanks a lot @brianchance for contribution on server side paging. I just started with rc.16 and testing server side paging. It works well except UI looks fractured. When you increase width, it screws up horizontal scroll.  

![image](https://cloud.githubusercontent.com/assets/5253675/5046773/3347fc14-6bdc-11e4-990e-ccfb58a53b43.png)

![image](https://cloud.githubusercontent.com/assets/5253675/5046955/379cff38-6bde-11e4-9cdc-b97152a8697b.png)

**Comment by PaulL1** [comment]
Looking at it today, I think the pagination UI is a bit ugly/misaligned still, but I think the core issues are resolved.  Is that what you're seeing @rupampatel2006?

**Comment by rupampatel2006** [comment]
@PaulL1 It works perfectly and i don't find any issue as of now. Yes, UI is ugly but I have customized UI for my purpose. I have created paging in header and is sticky. I can share code if you are interested.

**Comment by PaulL1** [comment]
@rupampatel2006 : I think @brianchance would be interested in that code, it may offer options to improve what we have.
