### ISSUE TITLE
Rename or condense paging/pagination and tutorials 214 and 215 

### ISSUE THREAD

**Issue by c0bra** [angular-ui/ng-grid#2106]
So now there's two feature modules, "paging" and "pagination". That's going to be really confusing for our users.

Can these be combined into one? Or at least renamed if they accomplish two separate things?

**Comment by PaulL1** [comment]
Completed.

**Comment by PaulL1** [comment]
Potentially so, yes.

**Comment by derrabus** [comment]
Any chance, we can get a new release soon?

**Comment by PaulL1** [comment]
Refer #2545

**Comment by derrabus** [comment]
I see. Replace "release" with "release candidate" in my question. ;-)

**Comment by PaulL1** [comment]
The next release candidate we're aiming for having all the hi-pri bugs fixed.  We're close, but there are a few that still need doing: https://github.com/angular-ui/ng-grid/issues?q=is%3Aopen+is%3Aissue+label%3A%22Hi-Pri+Bug%22
