### ISSUE TITLE
Adding position: relative to grid adds extra footer space.

### ISSUE THREAD

**Issue by joshmackey** [angular-ui/ng-grid#2110]
Subject /\

Affects rc16.

**Comment by c0bra** [comment]
@joshmackey Very sorry that this issue hasn't been addressed. I can't reproduce this in current unstable as of this date. Please re-file if you're still having problems.

**Comment by hxlniada** [comment]
I faced this problem too.
when I load the template from remote server(not a inline template), the body hide occasionally

**Comment by hxlniada** [comment]
@c0bra
