### ISSUE TITLE
expandable grid with selection issue

### ISSUE THREAD

**Issue by novice3030** [angular-ui/ng-grid#2117]
When using expandable grid with selection and selecting rows on the parent grid sub grid rows are also getting the CSS for selected rows

![image](https://cloud.githubusercontent.com/assets/6697179/5061553/19c8012a-6da4-11e4-8dc8-3a2d0ee1a8d6.png)

**Comment by PaulL1** [comment]
Fix implemented, and no commentary for some time, assuming this is resolved.
