### ISSUE TITLE
Recent Grid Row Selector Rendering Issues

### ISSUE THREAD

**Issue by Dev63** [angular-ui/ng-grid#2119]
I've been seeing some recent degradation in table rendering, and it's so obvious I just assumed it would get fixed ASAP.  But just to be safe, here it is:

![image](https://cloud.githubusercontent.com/assets/9340860/5062726/4d10ab1a-6d7f-11e4-8eb3-2a2e586b83f4.png)

As you can see, the first row selector does not have the same height as the rest of the header row, and so everything is misaligned (this is particularly obvious in the image due to the row selection). 

The next image shows that if you resize the browser, causing the table to resize, it draws the row selectors correctly ... but if you select one, it highlights the whole column in blue, including empty sections of the table.

![image](https://cloud.githubusercontent.com/assets/9340860/5062739/df0e4298-6d7f-11e4-8109-2b7c56a0adfd.png)

As an aside, you can also see the bottom scrollbar is being drawn too high, occluding the footer row.  This started about a week ago, before the problems with the selectors.

I just imagined everyone was seeing these things, but who knows, perhaps there's something unique about my situation.  Let me know if you need more info.

**Comment by PaulL1** [comment]
OK, sounds like this one is sufficiently resolved, and checking again the plunker seems to be behaving well now.  Closing.
