### ISSUE TITLE
UI-Grid CSS misbehaves 

### ISSUE THREAD

**Issue by calvinKG** [angular-ui/ng-grid#2124]
Hi guys 

Please help, I have been trying to add CSS to the ui-grid but no luck. I have applied the default css 
{ .grid { width: 700px; height: 450px;}} but still no luck. I have created my own css but I am having a problem with the vertical and horizontal scroll bar if I add more data to the grid. 

Please see screen shots for more details. 

![css](https://cloud.githubusercontent.com/assets/1926014/5071568/b05e85e2-6e7a-11e4-8729-4327431ccec6.png)

![error](https://cloud.githubusercontent.com/assets/1926014/5071516/2200862e-6e7a-11e4-948e-bb6f7ba027e5.png)

**Comment by PaulL1** [comment]
Is this still occurring?  I have seen problems when people override the core grid css, and it's not clear to me what use case people have that needs that override.

**Comment by calvinKG** [comment]
Yes and I am using the same CSS  that's on the mockups.

**Comment by PaulL1** [comment]
It's not clear to me what is different, but when I put that same content into a standard plunker: http://plnkr.co/edit/tB85JVwXqr6sMcb8BaQb?p=preview it seems to work fine.  Could you please retest?

**Comment by PaulL1** [comment]
Solution suggested, no further comment for 2 weeks, assuming solution has resolved the problem.

**Comment by stoplion** [comment]
Having the same prob.
