### ISSUE TITLE
Grid with pinned columns width is incorrect

### ISSUE THREAD

**Issue by dshybeka** [angular-ui/ng-grid#2140]
I was simply playing with pinning functionality on http://ui-grid.info/docs/#/tutorial/203_pinning. 

1. { name:'friends[2].name', displayName:'3rd friend', width:150 } - this row is not displayed on UI at all;
2. almost the same issue as the first one - if even one column is pinned width of viewport calculated incorrectly. See plunker: http://plnkr.co/edit/3I3OCeHj9hLLcI8CZBSz?p=preview.

**Comment by PaulL1** [comment]
I think this is now resolved - could you retest?

**Comment by darkthread** [comment]
@PaulL1 Yes, the bug is fixed! Confrirmed in JSBin and my own project.  Thanks for your wonderful support.
