### ISSUE TITLE
Vertical scroll bar in wrong location in IE9

### ISSUE THREAD

**Issue by mdsauer** [angular-ui/ng-grid#2145]
The vertical scroll bar is not positioned properly in IE9.  This can be seen by displaying the ui-grid.info page:

![image](https://cloud.githubusercontent.com/assets/8696368/5092589/1043a228-6f1e-11e4-8ff8-c44ea292ec51.png)

I also am seeing this in my own app...the grid at the bottom of the page is initially empty and the scroll bar is in the upper right.
![image](https://cloud.githubusercontent.com/assets/8696368/5092596/32e10834-6f1e-11e4-88f7-bf4d89712873.png)

My app is using v 3 rc 16 release.  I also tried the latest unstable css and js files.

**Comment by PaulL1** [comment]
I think with the latest changes to scrollbars, we've perhaps got logic that will work more natively.  Could someone retest the latest unstable on IE9?

**Comment by mdsauer** [comment]
I removed css fixes provided by alexandery and tested with the unstable versions of the .js and .css files and the scroll bars looked fine!  The only issue that I noticed was that when I would resize the columns by dragging the border all of the entries in the table were highlighted as if you clicked and dragged the mouse through them.  This does not happen in Chrome.

**Comment by PaulL1** [comment]
OK, could I suggest we raise a new issue for that last item, and perhaps close this issue as being resolved?

**Comment by mdsauer** [comment]
That sounds fine to me.  Should I create the new issue?  Do you want me to close this one?

**Comment by PaulL1** [comment]
Yes, fine for you to close and raise the new issue, that would be great.
