### ISSUE TITLE
No way to override/hide the text "Expandable Buttons"

### ISSUE THREAD

**Issue by eirenik** [angular-ui/ng-grid#2149]
With expandable rows, the row header column header says "Expandable Buttons".  I have glanced at the code and guess that the name "expandableButtons" gets converted to that text by some auto-formatting logic.

Either way, I'd like to be able to replace/remove it -- it's a little awkward and will never really be visible since the width of the column won't ever show it all.  Being able to provide a custom header would be nice, but simply providing text for the column title would be fine.

**Comment by motaro** [comment]
Also when i am exporting to PDF then there is blank columns in front of it for expandableButtons. How can i hide that

**Comment by PaulL1** [comment]
The exporting I can fix - there is a property to set on the expandable column def, which was added in #2453.  I can probably do something with the header text if I try too.

**Comment by PaulL1** [comment]
Header text was already set to `''`, I've suppressed the expandable column in exports.
