### ISSUE TITLE
Fast key navigation causes column header misalignment

### ISSUE THREAD

**Issue by PatrickWright2** [angular-ui/ng-grid#2152]
Using latest RC when you have many columns and horizontally scroll backwards and forwards rapidly using the keys to move between cells (ie. not scrollbar) then the column headers become misaligned. Tested on Chrome with grid of 40 columns. So to elaborate further I am holding down the left and right arrow keys to scroll the grid. In my screenshot below the column headers are not related to the columns underneath them.

![image](https://cloud.githubusercontent.com/assets/7928904/5101025/2f319108-7005-11e4-8b2a-ccad61d81b3a.png)

**Comment by PaulL1** [comment]
Fixed in latest scrolling changes (removing throttling seems to have fixed header misalignment).
