### ISSUE TITLE
ui.grid data row rendering vulnerable to .ui-grid-cell height change.

### ISSUE THREAD

**Issue by singhparmjit** [angular-ui/ng-grid#2160]
When I change the height of each row to be more than the default it confuses the rendering of the data.  see the Plunker for example.
http://plnkr.co/edit/bT9MxF?p=preview

When a user hold the scroll-bar or scrolls down with mouse wheel the height of the data row container starts shrinking. It keeps on shrinking until it disappears from screen.

**Comment by PaulL1** [comment]
OK, I think the problem here is the overrides on the css - when I remove all those the residual issues go away. Closing.
