### ISSUE TITLE
resizing column with pinned column broke table

### ISSUE THREAD

**Issue by brainsbucket** [angular-ui/ng-grid#2163]
(First thanks for your great work !)
When you pin a column (to the left) and then increase the size of it, then the not pinned columns go under the pinned columns.
you can try it on the tutoriel : http://ui-grid.info/docs/#/tutorial/401_AllFeatures

**Comment by PaulL1** [comment]
I've applied the fix as suggested.  This does refresh twice, but only for people using resize, and only when the user manually resizes (i.e. not that frequently).  I don't think the performance overhead will be material.
