### ISSUE TITLE
Column disappears after sorting

### ISSUE THREAD

**Issue by turbosasa** [angular-ui/ng-grid#2165]
Reproduce issue you can here in this demo http://ui-grid.info/docs/#/tutorial/191_horizontal_scrolling scroll to end and sort grid by last column (Col499) this column lost, if a little bit scroll backward forward this column appears again. 
Google Chrome v38.0

**Comment by PaulL1** [comment]
This appears to no longer be occurring.  @turbosasa: could you also confirm whether this is resolved for you?

**Comment by sunz7** [comment]
I was having the same issue. Then I updated ui-grid from rc-16 to the latest which is now rc-18 and it was fixed. Thanks

**Comment by jibinkv** [comment]
after editing a cell and pressing on tab going to next cell, but at the same time that column is sorted, so that next cell getting on the wrong row.

please help me to disable that horizondal nav if column edited and sorted or any way to move to correct row cell?

thanks
