### ISSUE TITLE
Removal of selected rows does not trigger rowSelectionChanged

### ISSUE THREAD

**Issue by eirenik** [angular-ui/ng-grid#2171]
If a selected row in gridOptions.data is slice()'d out, the grid properly removes it, but does not fire rowSelectionChanged, which seems reasonable, even if there are other events that do fire.

**Comment by PaulL1** [comment]
Misreferenced this from the above commit.

**Comment by PaulL1** [comment]
I don't think we can reasonably implement this.  The responsibility falls on the caller who manipulates the data to do any tidyup that is appropriate in their use case before manipulating the data.

**Comment by settergren** [comment]
Poor form? Responsibility fails on the caller? How about, lazy?

**Comment by PaulL1** [comment]
Or you could call in the order suggested - remove the selection before removing the row.

Feel free to submit a PR if you'd like this to be different, but calling someone lazy for not doing something that you want when you're not prepared to do it yourself seems somewhat hypocritical.
