### ISSUE TITLE
In contrast to #2170 , how to enable/disable(show hide) Selection column dynamically 

### ISSUE THREAD

**Issue by anandvihar** [angular-ui/ng-grid#2181]
How should i show or hide the selection column dynamically ie on a button click? I cant set the $scope.gridOption.enableRowHeaderSelection= false on the button click. I can hide the coloumn by hiding it or setting the visibilty to false by the api. Is there any way to hide/show the selection column through api not through grid option?

**Comment by PaulL1** [comment]
I believe this has now been addressed, selection can be turned on and off.

**Comment by PeterRangelov** [comment]
Having the same issue and can confirm this has not been addressed yet, at least as far as I can tell.
Initially:
$scope.gridOptions.enableRowHeaderSelection = false;
Then on button click:
$scope.gridOptions.enableRowHeaderSelection = true;

However the UI doesn't update even after grid.refresh(); and notifyDataChange.

**Comment by kannach** [comment]
I have exactly the same issue. Any workaround ?

**Comment by tomyam1** [comment]
It seems there is still not an option to show/hide the row headers columns.

The work around we use it to show/hide the checkboxes by adding/removing a `disable-row-selection` class to the `ui-grid`:

```less
.ui-grid.disable-row-selection {
  .ui-grid-selection-row-header-buttons {
    display: none;
  }
}
```

**Comment by cscuser** [comment]
> I'm not clear on your question. When you say you can't set `$scope.gridOption.enableRowHeaderSelection= false` on a button click, does that mean you need advice on how to set it, or does it mean you're setting it and then it's not doing what you'd expect?
> 
> There is no api other than the gridOption (which is itself an API), but it may be that we need to make that option dynamic, so this would be another variant of #1819

Thanks its working fine
