### ISSUE TITLE
[3.0][Scroll] I can't scroll down by scrollbar down-button in case of I hide horizontal scroll 

### ISSUE THREAD

**Issue by MariMax** [angular-ui/ng-grid#2185]
Please see the [plunker example](http://plnkr.co/edit/tPER4Qwckk9AwO3sqBG3?p=preview) for hiding horizontal scrollbar I use options.enableHorizontalScrollbar = 2;

**Comment by PaulL1** [comment]
I'm on OSX, so I don't get scrollbars anyway, so the plunker is working fine for me.  But it seems to me like you're saying that when you turn the scrollbars off, then you don't have a scrollbar down button.  That  would be expected behaviour, wouldn't it?

**Comment by MariMax** [comment]
Horizontal scrollbar is placed upon vertical scrollbar's down button, even if it hided and it is also upon last row of the table, so I can't select it when I need to

**Comment by MariMax** [comment]
I can't select last row and I can't press a down button on vertical scrollbar

**Comment by PaulL1** [comment]
Could you maybe provide a screenshot?  Your issue is still not clear to me.  Also, what version and build?

**Comment by MariMax** [comment]
if both scrollbars should be shown horizontal scrollbar lays upon the vertical scrollbar [screenshot](https://yadi.sk/i/S463GPQ7dypiT) and makes impossible to press down button, even if horizontal scroll hided. It also lays upon last row and user cannot press any link in last row when scrollbar hided for example I cannot press sn1 on [this screenshot](https://yadi.sk/i/jvBEJb0BdypiF)

**Comment by PaulL1** [comment]
And what version is that on?  Is it happening on the tutorials?

**Comment by MariMax** [comment]
My version is v3.0.0-rc.16
My example on plunker seems go to me now, except I cannot hide horizontal scrollbar at all
