### ISSUE TITLE
ui-grid selection loses row selection when switching ui-router states

### ISSUE THREAD

**Issue by mmild** [angular-ui/ng-grid#2187]
Two ui-grid's coupled to two ui-router states does not keep row selection when switching the views. Don't know if this is by design, but it causes problems to create navigational views (with ui-grid selection) ruled by states. It seems that switching states recreates the DOM, which could be an explaination as to why. Is there a way to solve this?

Minimalistic example: http://plnkr.co/edit/4BlFx0SZNn78i29fofSx

**Comment by PaulL1** [comment]
Save State is now implemented, assuming that resolves this issue.

**Comment by prashantkoshta** [comment]
I am facing same issue if i include ui.router and ui.grid together grid is not working.
GET http://localhost:8080/ui-grid/ui-grid 404 (Not Found)
Error: [$compile:tpload] Failed to load template: ui-grid/ui-grid (HTTP status: 404 Not Found)

Any help on it. I checked in http://plnkr.co/edit/4BlFx0SZNn78i29fofSx too. This is not working as well.
