### ISSUE TITLE
Grid columns headers have no width on refresh

### ISSUE THREAD

**Issue by severin2** [angular-ui/ng-grid#2193]
We have an app where we change the columns of the grid often, we do this by building a list of columns from the data property keys.

1) click the 'data set 3' button, observe that data set 3 is displayed and its columns are correctly drawn
2) click the 'data set 2' button, observe that data set 2 is displayed and its columns are correct
3) click the 'data set 1' button, observe that data set 1 is displayed but its column headers have no width and overlap
4) notice that now switching between 'data set 1' and 'data set 2' will not fix the headers, but switching to 'data set 3' will (presumably because the significant change between the columnDefs?)

plunker example: http://plnkr.co/edit/RDEC8e?p=preview

I've noticed that in our app, the column headers get classes dynamically added to them like `.grid1416592787863 .ui-grid-coluiGrid-082` and on the columns that are correctly drawn these classes are what gives the headers their width and on the columns that are drawn incorrectly they do not.

I am experimenting with using a custom headerTemplate to enforce the header width but I am still working on getting the header to play nice with the rest of the grid's concept of the column width.

**Comment by alexandery** [comment]
@PaulL1 - I'm glad I found this thread with a work-around for the problem as I was dire to have it working. I would highly suggest to make this piece of knowledge available on the Tutorial pages until it gets fixed. I have actually used $timeout instead of $interval to achieve the same result:

```javascript
$timeout(function() {
	$scope.grid.config.columnDefs = columnDefs; // update grid columns
	$scope.grid.config.data = results; // update grid data
});
```

**Comment by PaulL1** [comment]
I think this will (hopefully) get resolved when @c0bra deals with generating/using new UIDs for columns #2364 #1948

**Comment by abhishekam** [comment]
This is so way too cool - I was completely lost the whole of Sunday night trying to get this to work... This thread definitely needs to be made popular!!!

**Comment by c0bra** [comment]
Looks like this is working properly so I'm going to close. If there's any further issues please file a new ticket, thanks!

**Comment by settysreekanth** [comment]
My apologies to comment on closed issue, however  I am facing this issue still. Any suggestion ?

**Comment by settysreekanth** [comment]
Ignore my previous comment. 

Resolution: Changing ColumnDefs to have "name" instead of "field" solved the issue. Not sure of root cause though.

**Comment by firstpin** [comment]
how to give array data into 
New issue
Grid columns headers have no width on refresh

**Comment by allanelder** [comment]
Yup. I'm getting the same issue as firstpin; tried the resolution on here to no avail.
