### ISSUE TITLE
::one-time-binding on {{row.entity.field}} with custom cellTemplate for columnDef not working correctly

### ISSUE THREAD

**Issue by cristobal** [angular-ui/ng-grid#2198]
Using: `angular#1.3.3` + `angular-uI-grid#3.0.0-rc.16`

When having more than the `>=` 10 elements the cellTemplate does not display the correct values for the item it is supposed to be bound to @see this [plunker](http://embed.plnkr.co/ukLQ8mnWA0NLFeAWpmEt/preview)

If not using the one time binding it works fine, however it would be nice if `ui-grid` also supported the [`::one-time-binding` expression](https://docs.angularjs.org/guide/expression#-event-) to reduce the amount of watchers used by Angular.

**Comment by PaulL1** [comment]
OK, so 1.3 support is merged - is this still a problem?

**Comment by Arkh1** [comment]
We ended up moving to ui-grid due to a variety of issues we were experiencing with ng-grid.  Definitely appreciate seeing continuing support for ng-grid though.  And on that note...  I don't believe that I have tested the :: operator in ui-grid yet.

**Comment by PaulL1** [comment]
Ah, I don't think I'd even noticed this was a 2.x issue, I was treating it as 3.0.  :-)  I'd be interested to know whether it works.

**Comment by cristobal** [comment]
No this is still an issue tried with `Angular 1.3.8` and `ui-grid rc18`. There still seems to be an issue when having more than 10 elements http://embed.plnkr.co/xazvX3YQZVfyJ1IMOkB5/, seems that when doing the rendering manually it's done in a batch job and then next batch of 10 elements are referring to the first batch of 10 elements not sure where in the code this happens… :/

**Comment by PaulL1** [comment]
Thinking about this some more, I don't think the one-time binding will work with virtualisation.  One-time binding would work if we rendered all the DOM elements at the start and then never changed them.  But what we actually do as you scroll is that we change which row/col a particular DOM element points to - we reuse the existing DOM element but repoint it.  I believe that this process relies on the angular digest cycle to update the value in the cell - with one-time binding the scrolling would break.

**Comment by c0bra** [comment]
@PaulL1  is correct; performance would actually be **worse** with one-time bindings as you'd have to create and destroy DOM elements with wild abandon, which is browser-intensive. Bindings let us swap data out on the back-end while re-using the same DOM elements. That's the whole point of virtualization.

**Comment by sudhanshu258** [comment]
hello..i m new to this..can u tell me how to use one time bindings for ui-grid?
