### ISSUE TITLE
Filtering not working properly with paging.

### ISSUE THREAD

**Issue by conanak99** [angular-ui/ng-grid#2211]
I use the lastest ui-grid unstable version.
For example, I have a table of 500 tries, each page contains 50 entries.

When I try to filter a property, I excepted it to filter all 500 entries, and paging the filtered result.
But it only filter the 50 entries of the current page.
Is this a bug? Can I configure somewhere to make it works as I excepted?

**Comment by furier** [comment]
Got the same problem, have 10k+ items in the data source, and i would like the filter to filter on the datasource and not care about paging. the paging plugin should just page the filtered results which might be 200 rows out of the 10k, where each page is 50 items would make 4 total pages.

**Comment by brianchance** [comment]
The PR was merged, you might need to use the latest unstable release. I know it is in there.

**Comment by furier** [comment]
@brianchance cool! :)

**Comment by PaulL1** [comment]
Can you confirm that this is now working so that we can close?

**Comment by furier** [comment]
This seems to work now thank you :)

**Comment by PaulL1** [comment]
Excellent, thanks.

**Comment by christrude** [comment]
Not sure if I'm missing something, but I'm doing filtering using the registerRowsProcessor, and even in 4.0.2, the filtering only takes into account existing page. Here's my code snippets:

 $scope.sourceGridOptions = {
          enableSorting: true,
          paginationPageSizes: [2,50,75],
          paginationPageSize: $scope.sourceListing.size,
          useExternalPagination: true,
          columnDefs: [
            { field: 'sourceTitle', name: 'Source Title', enableColumnMenu: false},
            { field: 'sourceUrl', name: 'Source Url', enableColumnMenu: false, minWidth: 300},
            { field: 'sourceType', name: 'Source Type', enableColumnMenu: false},
            { field: 'entityCount', name: 'Entity Count', enableColumnMenu: false, cellTemplate: entityCountCellTemplate},
            { field: 'lastSyncedOn', name: 'Last Sync Date', enableColumnMenu: false, minWidth: 200},
            { field: '', name: 'Action', cellTemplate: attrActionTemplate, enableColumnMenu: false, enableSorting: false, maxWidth: 150}
          ],
          onRegisterApi: function (gridApi) {
            $scope.sourceListGridApi = gridApi;
            $scope.sourceListGridApi.grid.registerRowsProcessor($scope.configSLFilter, 200);
            $scope.sourceListGridApi.pagination.on.paginationChanged($scope, function (newPage, pageSize) {
              $scope.sourceListing.from = newPage;
              $scope.sourceListing.size = pageSize;
              $scope.buildSourceListing();
            });
          }
      };

    //Grid filter business logic
    //We checking for a match using sourceTitle & sourceType
    $scope.configSLFilter = function (visibleRows) {
        var matcher = new RegExp($scope.source.searchStr.toLowerCase());
        renderableRows.forEach(function (row) {
          var match = false;
          ['sourceTitle', 'sourceType'].forEach(function (field) {
            if (row.entity[field] !== null) {
              if (row.entity[field].toLowerCase().match(matcher)) {
                  match = true;
              }
            }
          });
          if (!match) {
              row.visible = false;
          }
        });
        return renderableRows;
    };


In my defense, I didn't write this code, just debugging it. Tried swapping renderableRows with visibleRows, but that had no effect.
