### ISSUE TITLE
Cell template using ng-click on rowSelectionEnabled grid

### ISSUE THREAD

**Issue by Fabryprog** [angular-ui/ng-grid#2214]
Hello everyone,

i have a grid with:

  enableRowSelection: true
  enableRowHeaderSelection: false

In the last cell i am using a button with ng-click event handler. 

My grid fired  2 events:
 - selection
 - ng-click

How to avoid cell selection ? I need only ng-click event!!!

NOTE: if i use enableRowHeaderSelection: true attribute, it is all ok!

CODE: http://plnkr.co/edit/oAm3Zm

**Comment by PaulL1** [comment]
Solution provided that sounds like it would resolve the issue, no response for a few months, assuming issue is resolved.
