### ISSUE TITLE
Propagate vertical scrolling events when pagination is used

### ISSUE THREAD

**Issue by avaliani** [angular-ui/ng-grid#2242]
I wanted to know if there was a away to enable vertical scrolling events to propagate when I'm using pagination with ui-grid. Meaning, if I scroll with my mouse over the ui-grid I want the entire page to scroll. If I didn't use pagination then vertically scrolling through the results of course makes sense (and in this case the page should not scroll).

Thanks for all your great work on this library!

**Comment by PaulL1** [comment]
I think this is now working - could you confirm?  We've done work on the scroll propagating to parent page and end of the grid.

**Comment by rysilva** [comment]
Based on the demo on the home page of ui-grid.info, it seems to work as expected.

**Comment by PaulL1** [comment]
Thanks,
