### ISSUE TITLE
filter and horizontal scroll position bug

### ISSUE THREAD

**Issue by trokohl** [angular-ui/ng-grid#2251]
the bug appears for example in http://ui-grid.info/docs/#/tutorial/401_AllFeatures

1. scroll horziontal the Address.City column in the middle of the grid
2. filter for some city that doesn't exist ( 222 )
=> the grid remove the horizontal scroll position( Bug or Feature?)
3. scroll horziontal Address.City again in the middle of the grid
4. clear the filter

=> 

![scrollbug](https://cloud.githubusercontent.com/assets/7289810/5229298/c8c94be6-7715-11e4-9fa4-7bd8bd3af88b.png)

**Comment by girishla** [comment]
I've had the same issue and have a dodgy workaround - I add a dummy row to the data. The dummy row seems to get around the issue. I will undo this once a fix is available.

For example:

         if(!$scope.gridOptions.data.length>0){

                $scope.gridOptions.data=[{
                        "firstName": "No",
                        "lastName": "Results"
                 }]

            }

**Comment by PaulL1** [comment]
There are some substantial changes going in on scrolling that look like they'll resolve this issue. We'll look again once those are complete and merged.

**Comment by PaulL1** [comment]
I think this is now resolved.  Can you confirm?

**Comment by trokohl** [comment]
the horizontal scrolling is looks good.
Is anyone working on the vertical scolling at the moment?
it doen't work correct at the moment.

**Comment by PaulL1** [comment]
Could you be a little clearer about what portion of vertical scrolling doesn't work?  It is working quite well for me.

**Comment by trokohl** [comment]
If i just replace the ui-grid js and css in my project, the scrollbar range seam to be to big.
There no more lines available but i can scroll further.

In my environment the scroll range is always to huge

**Comment by trokohl** [comment]
never mind. i think it was only a caching problem somewhere .

thank you.
