### ISSUE TITLE
Clicking on tablet

### ISSUE THREAD

**Issue by cookednoodles** [angular-ui/ng-grid#2252]
If you put a clickable item in a grid (ng-click etc...) won't fire the action, with ngTouch I can see the ng-click-active class changing; but no event happening.

**Comment by PaulL1** [comment]
The cell edit feature is now working on iOS devices (and I assume therefore on other touch devices).  Could you retest this click handler issue?

**Comment by PaulL1** [comment]
You can now see a click event on the app scope tutorial: http://ui-grid.info/docs/#/tutorial/305_appScope.  This seems to be working on touch devices (on my iPad), on that basis I'm closing.
