### ISSUE TITLE
UI-GRID both row header selection and row selection

### ISSUE THREAD

**Issue by netsalman** [angular-ui/ng-grid#2254]
Hi i when i set the rowheaderselection to false, the row selection works perfectly fine with the new UI grid, but i need to have both , header selection option and row selection option, how can i achieve this

**Comment by vamsikrishnamannem** [comment]
Brian Hann c0bra solved it find this in
http://stackoverflow.com/questions/29469778/angular-ui-grid-row-selection/29479910#29479910

**Comment by iyel** [comment]
Will solution be merged in upcoming releases?
