### ISSUE TITLE
Unable to sort on toggled column

### ISSUE THREAD

**Issue by msheiny** [angular-ui/ng-grid#2260]
After adding a column to the table by appending to the ColumnDefs, sorting doesn't work properly on that column. 

I followed documentation from the [Docs](http://ui-grid.info/docs/#/tutorial/113_adding_and_removing_columns) and was able to reproduce [here](http://plnkr.co/edit/eygIi6OOqPhvQA0o3lyA?p=preview). Specifically, push the 'Add' button and then click on 'Company' to try and sort that column. 

For clarification, this was reproduced on version v3.0.0-rc.16-cc7841b

**Comment by PaulL1** [comment]
This now appears to be working - could you review and confirm?

**Comment by msheiny** [comment]
Yep that fixed things! Thanks guys!
