### ISSUE TITLE
Scrolling with dynamic data

### ISSUE THREAD

**Issue by surabhi-batra** [angular-ui/ng-grid#2270]
Hi, I am using the editable ui-grid, and I'm facing an issue with scrolling upon adding data. As you can see, I'm using the 'add trade' button on top to dynamically add new rows. Once they get added, they go beyond the height of the viewport. The CSS messes up.Moreover, the vertical scrollbar doesn't work upon adding extra rows.

Could you please look into this?

Thanks

FYI - my issue is similar to this: https://github.com/angular-ui/ng-grid/issues/2124 

![scrolling issue](https://cloud.githubusercontent.com/assets/10069538/5293282/b7f44800-7ba9-11e4-892d-d166395a2aca.PNG)

**Comment by PaulL1** [comment]
I think the changes to scrollbars may have resolved this - could you retest on current unstable?

**Comment by PaulL1** [comment]
Believed to be fixed in recent changes, no updates from information request, assuming is resolved and closing.
