### ISSUE TITLE
Expandable Row and Column Resize don't play nice together, can't get ColDef for ExpandableColumn

### ISSUE THREAD

**Issue by devakone** [angular-ui/ng-grid#2277]
I was using both Expandable Row and the Column Resizing feature and it seems they don't play nice out of the box. If you try and resize the expandable buttons column, all hell breaks loose. So i decided to keep the expandable buttons column non resizable. First it would be great to be able to provide your own coldef for the expandable row, but given that,I wanted to set {enableResize:false} on the coldef for the expandable row.If you try to get the vanilla coldef by using grid.getColumnDef('expandableButtons'), you get a null back even though grid.getColumn('expandableButtons') will indeed return the proper column. The reason after looking at the source code is that getColumnDef() looks through grid.options.columnDefs and of course expandableGrid being a plugin, that columndef is added after the fact. I am looking for a good workaround to it and will post it when I do

**Comment by PaulL1** [comment]
I think I fixed this earlier today/yesterday, when I tidied up the colDef for expandable - I made it both non-exportable, but also non-resizeable.  Could you check and confirm?

**Comment by PaulL1** [comment]
Assuming this is resolved, given no comment for 3 weeks.  Closed.
