### ISSUE TITLE
Possible regression: horizontal scroll with pinning doesn't show last column(s)

### ISSUE THREAD

**Issue by c0bra** [angular-ui/ng-grid#2288]
Depending on the width of left-pinned columns, you cannot scroll to a certain number of the last columns in the main viewport. They are either cut off or completely hidden. This is probably because the scroll width is not being calculated properly, and was possibly introduced as a regression.

The horizontal scrollbar also now covers the totality of the grid width and not just the viewport to which it belongs. This may or may not be related but it's possible that the grid thinks it has more space to scroll horizontally than it really does, and the horizontal scrollbar would be a symptom of that.

Bisecting will probably be required to find the source.

**Comment by PaulL1** [comment]
@c0bra: is this still happening for you with @swalters' latest changes?

**Comment by c0bra** [comment]
I'm not able to make this happen any more, I don't think. Going to close and I'm sure if it's still a problem it will be opened as a new issue.
