### ISSUE TITLE
Improper use of non-existent "clearfix" class

### ISSUE THREAD

**Issue by c0bra** [angular-ui/ng-grid#2297]
Both the `ui-grid-footer` and `ui-grid-header` templates have a `clearfix` class on them. The grid defines no "clearfix" class nor can we rely on it being there.

These references should probably be updated to `ui-grid-clearfix` which DOES exist, but who knows what effect that could have. Someone will need to test this out to make sure there's no problems with the rendered elements.

**Comment by PaulL1** [comment]
I'll give this a go and a test through the tutorials to see what happens.  I don't have all browsers to test on, but I figure if we are going to do this it should be before 3.0 releases.
