### ISSUE TITLE
Rows disappear on cell select and/or edit at the bottom of the current data set

### ISSUE THREAD

**Issue by jdscolam** [angular-ui/ng-grid#2299]
Please see the way the last few rows disappear in the Plunker when scrolling and editing the last cell.

http://plnkr.co/edit/MIl2xRmjKEXcJdumCDER?p=preview

**Comment by c0bra** [comment]
This is no longer happening for me.  @jdscolam @PaulL1  can you verify please?

**Comment by PaulL1** [comment]
This is now working for me, closing.
