### ISSUE TITLE
Cell navigation package (cell.Nav) and Selection packages  (ui.grid.selection)  are not working in co ordination.

### ISSUE THREAD

**Issue by manoj84** [angular-ui/ng-grid#2308]
I did a bower install of latest ui.grid on 12/9/2014 and I have the following code in my controller 

      gridApi.selection.on.rowSelectionChanged($scope, function(row) {
        //Update the Layout to set our row, so that toolbar can pick it up.
        nwfGridService.setSelectedData(row.entity);

      });

      gridApi.cellNav.on.navigate($scope,function(newRowCol){
        $scope.gridApi.selection.selectRow(newRowCol.row.entity);

Essentially row selection change on key board nav and mouse select ( which is the above) stopped working in coordination and there are errors on ui-header-cell in console.

**Comment by Flown** [comment]
http://plnkr.co/edit/p88PJE8J1UJGoKjs8WCw?p=preview

It looks like the selection is only triggered when the viewport/canvas scrolls.
E.g. select ID 0, then use the down-key to scroll to ID 11/12 .... As soon it is reached, the canvas scrolls down a bit and the selection is triggered.

**Comment by steverA** [comment]
If you inject uiGridConstants into your controller it seems to work. Otherwise, your code gets an exception in the $scope.gridApi.core.notifyDataChange() call...

**Comment by Flown** [comment]
Looks like it is working now, thx a lot

**Comment by ferrao** [comment]
I am on RC-18, am injecting uiGridConstants into my controller, tried scrolling after selection, but i still have this issue. 

Here is a plunkger :

http://plnkr.co/edit/sZpG81?p=preview

**Comment by PaulL1** [comment]
It works well with headerRowSelection, which is also what we do in the 401 all features tutorial.  http://ui-grid.info/docs/#/tutorial/401_AllFeatures

Without headerRowSelection, it looks like it works with a $timeout, and doesn't work without.  I can't work out why that is, but it is.  http://plnkr.co/edit/QcZy9TaeLkIV4WrWK77y?p=preview

**Comment by ferrao** [comment]
At least there is a workaround, i might have to play a bit with the styles to get what i want and not to have the nav cell darker than the selected row,and if i scroll real fast the highlighted cell actually goes in front of the selected row, but for my purposes it's more than ok.

**Comment by c0bra** [comment]
@PaulL1 looks like it's outside of $digest inside the `navigate` handler. Do we need to force a $scope.$apply() in our keydown/click handlers in cellNav?
