### ISSUE TITLE
Old versions of jquery cause edit not to work

### ISSUE THREAD

**Issue by AgDude** [angular-ui/ng-grid#2311]
If jquery version <= 1.8.3 is present, "type property can't be changed" is thrown on beginning to edit a cell. I realize this jquery version is a couple years old, but 1.7 and 1.8 are still in very wide use (and 1.7 happens to be in the large project where I want to use ui-grid) 

I believe this was introduced in the resolution to #1432.

This can easily be seen by adding this line this to the beginning of the "edit" demo:
```
<script data-require="jquery@1.8.3" data-semver="1.8.3" src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.8.3/jquery.js"></script>
```

**Comment by PaulL1** [comment]
It looks like @jpuri fixed this a month or so ago.  @AgDude: can you confirm it's fixed?

**Comment by AgDude** [comment]
I haven't tried this with different data types, but the basic edit functionality is working with the latest unstable.  @jpuri, thanks for the fix.
