### ISSUE TITLE
auto resizing configuration option

### ISSUE THREAD

**Issue by vsertti** [angular-ui/ng-grid#2315]
I use auto resizing in angular ui-grid as described in
http://ui-grid.info/docs/#/tutorial/213_auto_resizing

I want to enable/disable auto resizing, but I cannot find any configuration option for it.
   So I want to define:
    GridOptions = {                              
                enableAutoResizing: false
Is there a configuration option for auto resizing. I would need it.

**Comment by PaulL1** [comment]
I doubt that notifyDataChange would help with this.

The auto-resize code base doesn't include any options to turn auto-resize on and off - I think you can only achieve that by including or not including the directive.

**Comment by PaulL1** [comment]
No further comment for some time, resolution offered.  Closing.
