### ISSUE TITLE
Date Filters

### ISSUE THREAD

**Issue by MaxMem** [angular-ui/ng-grid#2321]
Is there a way for column filters to filter Javascript date objects?
```
columnDefs: {
    field: 'dateField',
    cellFilter: 'date:\'MM/dd/yyyy\'',
    filters: [
      { placeholder: 'from...',
        condition: uiGridConstants.filter.GREATER_THAN_OR_EQUAL },
      { placeholder: 'to...',
        condition: uiGridConstants.filter.LESS_THAN_OR_EQUAL }
 ]}
```

**Comment by thomas-koch-comsolit** [comment]
this could be solved if we have the possibility to define custom filters: #2796

**Comment by PaulL1** [comment]
Custom filters are now possible, which would allow a date chooser or other similar widget to be used, and thereby get date objects as the term.  Closing.

**Comment by marcosicp** [comment]
@PaulL1 hello, I need to use something like uiGridGroupingConstants.aggregation.MAX but with dates, so I need to filter the MAX (bigger) date

**Comment by MUNNASALLA** [comment]
i have done it with javascrip method  http://plnkr.co/edit/0MIf9QE3LsPFWCWPyDMZ?p=preview

**Comment by mzmousa** [comment]
Thank you @MUNNASALLA that works for me, even when I use `type='date'` and `cellFilter` for a date format.
