### ISSUE TITLE
scrollbar up and down arrows do not work in IE 9.

### ISSUE THREAD

**Issue by hmendezm** [angular-ui/ng-grid#2322]
Hi guys,

I have a ui-grid and I need to enable the scroll bars. The problem is when I click the up and down arrows. These are not working and I do not get any error.

Does someone have any idea how to fix this or where should I start looking ?

Best regards
Henry

**Comment by PaulL1** [comment]
With the recent change to using native browser scrollbars as part of our container, rather than scrollbars in their own container, I'd expect this to be solved.  @alexandery, could you confirm?

**Comment by alexandery** [comment]
@PaulL1  I will be able to try the new version out in the next few day, possibly early next week as it is not very simple for me to migrate from RC-16 to the latest with the changes in paging/pagination + CSS issues on IE9 in the latest release seem to affect my code again. I should be able to migrate soon enough and then I will test this feature.

**Comment by alexandery** [comment]
This works in IE9 now.

**Comment by PaulL1** [comment]
OK, thanks, closing.

**Comment by acostaf** [comment]
@PaulL1 

Hi Paul I am on version 3.0.0-RC.18 and cannot see that change, Am I using the right version?

**Comment by PaulL1** [comment]
Try using the unstable, or looking at the tutorials.
