### ISSUE TITLE
When too many columns are pinned the viewport wraps around to multiple lines

### ISSUE THREAD

**Issue by loongdefect** [angular-ui/ng-grid#2328]
view demo:
http://plnkr.co/edit/ALZWKqiqOPsiJ428hhYO?p=preview

**Comment by PaulL1** [comment]
Is this still happening @c0bra, @swalters?  I think that we've been playing with pinning and the new scrolling, and this might still be happening in some circumstances?

**Comment by PaulL1** [comment]
Still happening.  Current answer is to put a scrollbar on the pinned container, so that it doesn't break rendering.  Future enhancement is to resize the pinned v's body container.

**Comment by PaulL1** [comment]
Is this now solved with the latest sizing updates?  I can't recreate the issue in the plunker, but I'm not sure I ever could.

**Comment by PaulL1** [comment]
Closing: solution proposed that should resolve the issue, no further comments for 2 weeks, assuming solution has resolved issue.
