### ISSUE TITLE
ui-grid: tabbing into and out of the grid?

### ISSUE THREAD

**Issue by alexandery** [angular-ui/ng-grid#2339]
Hi guys,

I have a ui-grid on the page which displays search results. I need to be able to tab into it after hitting Search button and navigate the rows. Once a row is selected, I need to be able to tab out to an 'Open' button (which is outside the grid). Is this possible?

Thanks!

**Comment by cks333** [comment]
I have a number of fields (textboxes, checkboxes, selectfields etc) along with a number of grids (implemented using ui-grid) in a single page. Tabbing works fine in the page through various fields until i encounter the grid. The tabbing skips the grid and goes straight to next field ! I hope this fix will help me too ! Thanks to Paul and Swalters on this !
