### ISSUE TITLE
dynamic pagination?

### ISSUE THREAD

**Issue by DaveSysomos** [angular-ui/ng-grid#2340]
Very straightforward: if there are fewer records listed than the page size, there is no reason to show the pagination controls.

I've tried several ways to implement this, none of which seems to work.

directly, in the config:

```javascript
$scope.gridOptions = {
    totalServerItems:'totalServerItems',
    enablePaging: totalServerItems > $scope.pagingOptions.pageSize
}
```

indirectly, via the setPagingData function

```javascript
$scope.setPagingData = function(data, page, pageSize){
    ...
    $scope.gridOptions.enablePaging = $scope.pagingOptions.totalServerItems > $scope.pagingOptions.pageSize;
    if (!$scope.$$phase) {
        $scope.$apply();
    }
}
```

Not sure if there is already functionality for this that I'm missing, or if I've got to hack it.
I think my hacks are not working either because of variable scoping or because of a timing issue.

**Comment by PaulL1** [comment]
OK, sounds like there's a reasonable workaround, and given how light support is for pagination at all, I don't think this enhancement will get added any time soon.  Closing.
