### ISSUE TITLE
Modal window example is broken

### ISSUE THREAD

**Issue by mmuruev** [angular-ui/ng-grid#2359]
Modal window grid just doesn't work on example page in the right way and nothing at all for fiddle page.

**Comment by PaulL1** [comment]
This looks to no longer be broken?  At least, the behaviour I get in plunker for 1.3.0 and 1.2.26 is the same.  @c0bra: does this look fixed to you?

**Comment by PaulL1** [comment]
Believed to be fixed in recent changes, no updates from information request, assuming is resolved and closing.
