### ISSUE TITLE
cellNav does not always bring selected cell into viewport

### ISSUE THREAD

**Issue by alexandery** [angular-ui/ng-grid#2365]
When navigating cells with up/down keys, ui.grid.cellNav does not always make selected cell visible:

![ui-grid - cellnav 01](https://cloud.githubusercontent.com/assets/3676316/5462484/79da9ad8-8531-11e4-9bb1-f6047af04fac.png)

**Comment by PaulL1** [comment]
Assuming that this issue is resolved - a lot of work has gone into scrolling recently, and no reply from issue raiser for 3 weeks.
