### ISSUE TITLE
I am not able to call refresh() on grid.

### ISSUE THREAD

**Issue by rkrishnadudyala** [angular-ui/ng-grid#2384]
Can some on provide me some pointers on how we call refresh() method. Any examples?

Thanks.

**Comment by PaulL1** [comment]
Assuming that original issue is resolved, no comments for 3 weeks.

**Comment by Vinodang** [comment]
yes, it works! @PaulL1 thank u!

**Comment by Ankita10** [comment]
Hi, I am using the ui-grid and th eupdate of model does not update the grid (view).
When I perform a sort it updates the data.
How can I perform refresh in this case?
Thanks in advance!

**Comment by Ankita10** [comment]
got it to work using gridApi.core.refresh() but is there a better way to achieve it?
