### ISSUE TITLE
Exporter: download to clipboard

### ISSUE THREAD

**Issue by PaulL1** [angular-ui/ng-grid#2406]
Extend exporter to support download to clipboard.  The aim would be that the data goes onto the clipboard in an html table format, which most applications seem to be happy to then paste.

**Comment by PaulL1** [comment]
Should be substantially addressed through #2464 and #2186

**Comment by PaulL1** [comment]
I don't have a viable way to do more on this without included a flash control, which we won't do.  So closing.

**Comment by hxlniada** [comment]
oh, nooooo....
