### ISSUE TITLE
expandable grid with horizontal scrolling

### ISSUE THREAD

**Issue by novice3030** [angular-ui/ng-grid#2415]
We need to also add in the tutorials a demo for expandable grid that supports horizontal scrolling
Right now there are some known issues that needs to be fixed like recalcing the expanded row width when scrolling event is triggered.

I'm not sure I have time to do this chore so anyone else that might have some time can take it

**Comment by PaulL1** [comment]
This appears to be working: http://plnkr.co/edit/pqxMilIRwbBTRsGMxOe9?p=preview.  Is there any reason we wouldn't close?

**Comment by PaulL1** [comment]
Closing: solution proposed that should resolve the issue, no further comments for 2 weeks, assuming solution has resolved issue.
