### ISSUE TITLE
Can you export a subgrid to PDF/CSV?

### ISSUE THREAD

**Issue by countrdd** [angular-ui/ng-grid#2419]
Is it possible to export the subgridRow to PDF/Csv?

**Comment by bleuscyther** [comment]
+1

**Comment by PaulL1** [comment]
I believe that if you change your subgrid to have exporter as one of it's options, then there's no reason you couldn't export from the subgrid.  You'd need to provide some sort of UI to make it work, but it's very plausible.  Closing, as I don't think this is something we'd provide in the core group, and it's possible to extend the grid to do it.
