### ISSUE TITLE
ui-grid Paging stopped working

### ISSUE THREAD

**Issue by longshot5112** [angular-ui/ng-grid#2420]
I noticed that the grid for the app I'm working on started displaying the paging buttons and the horizontal scroll bar on top of each other. I checked out a few plunkers to see if it was something that was getting pulled from the unstable release.

http://plnkr.co/edit/eNszV91DnH7Uf2aBqlVF?p=preview

![capture](https://cloud.githubusercontent.com/assets/10211493/5526788/07fe6468-89bd-11e4-86a2-c04351d71fe5.PNG)

**Comment by PaulL1** [comment]
Is this still happening, or have recent changes sorted it out?

**Comment by longshot5112** [comment]
I have since moved to an older more stable release for development.
However, I switched to the latest unstable build, briefly, and switched from ui.grid.paging to ui.grid.pagination and it appears that the obvious issue has been resolved.

**Comment by PaulL1** [comment]
OK, sounds like we can close.
