### ISSUE TITLE
Starting with empty gridOptions and ui.grid.selection in app forces header to be 46 px tall!

### ISSUE THREAD

**Issue by steverA** [angular-ui/ng-grid#2421]
If I start with an empty gridOptions to load later, just the grid outline shows correctly. If I add ui.grid.selection into module definition, a box appears in the header row that is 46 px high and its height won't be reset when I later load the gridOptions. [Plnkr here](http://plnkr.co/edit/4DlpTEay1EYJKVOGAKeS). 
Comment out the ui.grid.selection in the module definition and see that the grid rectangle is empty!

**Comment by steverA** [comment]
I found a solution! In a directive in which I have a template that includes ui-grid="gridOptions", I use a value on the directive/attribute name myGrid="multiple" and in the prelink function, check to see if myGrid is "multiple". If so, I add enableRowHeaderSelection, multiSelect, enableSelectAll as true to the gridOptions; otherwise I add them as false.  That way, the checkbox column only appears if multiselect! I'm testing with v3.0.0-RC.18-f8a68cc - 2015-01-02.

**Comment by PaulL1** [comment]
Closing, as issue raiser appears to have a resolution.
