### ISSUE TITLE
CSV export failing with data larger than 2MB (Chrome)

### ISSUE THREAD

**Issue by smiller393** [angular-ui/ng-grid#2424]
I noticed that Chrome crashes any time I try to export data to a CSV that is larger than 2MB. This seems to be because the Chrome size limitation for Data URIs ( See this related link: https://code.google.com/p/chromium/issues/detail?id=44820 ). Does anyone know of a workaround for this?

Thanks

**Comment by PaulL1** [comment]
Closing this, browser limitation.
