### ISSUE TITLE
no (documented) gridMenuItemTemplate?

### ISSUE THREAD

**Issue by juliusakula** [angular-ui/ng-grid#2428]
I don't know if this is something configurable via gridOptions, but I'm trying to apply a directive to a menu item, and have no way to do so. It would be useful for many use cases to be able to change attributes or give directives to the menu items. Specifically I want to include the clip-copy directive from ng-clipboard.

Enhancement or Existing feature that isn't documented?

**Comment by PaulL1** [comment]
Closing, as #2816 is in progress.
