### ISSUE TITLE
Missing watch on options.enableFiltering

### ISSUE THREAD

**Issue by TheHalcyonSavant** [angular-ui/ng-grid#2433]
I see many grid options are not watched, including enableFiltering on both the grid and columns. Any plans for implementing watchers on most options for dynamic change ? (I'm reading the latest source codes)

**Comment by paambaati** [comment]
@TheHalcyonSavant I'm in the same pickle. Can you show me how you managed to modify `enableFiltering` after loading remote data?

**Comment by PaulL1** [comment]
EnableFiltering should now update with notifyDataChange, and in fact I think the tutorial has an example of this.

**Comment by TheHalcyonSavant** [comment]
My `enableFiltering` is always true and in my `uiGridToolbar` directive I have `filter` button with onclick event that executes this:
```javascript
$elem.closest('.ui-grid').toggleClass('filterable');
```
@paambaati you can toggle this class onload instead, in case you need only to show/hide the filters. This way it's much simpler as you don't depend on the internal watchers/events of the ui-grid.
