### ISSUE TITLE
Horizontal scroll problem

### ISSUE THREAD

**Issue by pgopkalo** [angular-ui/ng-grid#2438]
Grid is scrolling horizontally on touchpad scroll (reproduced on macbook) even if rows width fits grid width.

**Comment by PaulL1** [comment]
No reply for over 2 weeks, assuming problem is resolved.

**Comment by Jazz777** [comment]
Hi, I can see this on the example you mentioned above (using chrome on windows):

![image](https://cloud.githubusercontent.com/assets/1511867/5719671/d80b6778-9b1a-11e4-8b8a-f7975fd6adb3.png)

**Comment by Jazz777** [comment]
Furthermore, scrolling horizontally miss-aligns header field with row fields:

![image](https://cloud.githubusercontent.com/assets/1511867/5719747/88a2c856-9b1b-11e4-8fd2-7f3fc3b71821.png)

![image](https://cloud.githubusercontent.com/assets/1511867/5719751/934b2b5e-9b1b-11e4-89ac-2cfb6da114f1.png)

**Comment by mozaffar** [comment]
I have this problem too in chrome. in Firefox everything works well but on chrome NO. I am using version 4.6.6

**Comment by mozaffar** [comment]
I have this problem too in chrome. in Firefox everything works well but on chrome NO. I am using version 4.6.6
