### ISSUE TITLE
Nested ui-grid problem 

### ISSUE THREAD

**Issue by oussanovsi** [angular-ui/ng-grid#2440]
Hi,
I'm preparing a grid which have a column that contain another grid, i tried it with ngGrid it works according to this plunkr link : http://plnkr.co/edit/wSd880e7cm2BlOkfdrAW?p=preview
The previous link was done with ngGrid But when i tried to prepare the equivalent of this using ui-grid,
i got a problem (a.uiGrid is undefined).

Please help me for this issue
thanks

**Comment by PaulL1** [comment]
Could you perhaps provide a plunker with your ui-grid example, which we could then look at to see if we can help.  

I'm not sure that placing a grid within a cell is a common use case, and no doubt that's why this issue hasn't received any response.

**Comment by PaulL1** [comment]
No plunker provided, and no further comments.  Assuming problem is resolved and closing.
