### ISSUE TITLE
Modify features to allow grouping rows

### ISSUE THREAD

**Issue by PaulL1** [angular-ui/ng-grid#2453]
The grouping functionality is underway, thanks to @jpdesigndev.  Grouping will introduce grouping rows, which are not part of the core data set, but are visible in the grid and appear in `grid.rows`.

It is desirable to exclude these rows from some actions, particularly actions that some of the features implement, for example we might not want these rows to be editable, to be selectable, or to be exportable.

In order to implement this in a generic way it would be nice to allow each of these features to be suppressed for individual rows - so set a flag on a given row that says "don't do xyz".  The proposition is that we have a flag for each feature - so a flag on the row that says "enableSelection", another that says "enableFocus", another that says "enableEditing".  These are sort of like options on the columnDefs, but they're on rows instead.

At this stage the intention is for these to have internal use only - other features can set the flags, so in a sense they're part of the API set of a given feature, and able to be consumed by other features.  At a later date these flags might also be user settable - so if your data entity had an attribute of `enableFocus: false` then that row wouldn't be focusable.  That's for future discussion.

Also, a given feature that creates rows (such as grouping) might have gridOptions that control this behaviour.  So maybe by default grouping doesn't export the group rows.  But maybe you can set "groupingExportGroupRows: true" and it then allows export on those rows.  Again perhaps a future extension.

This issue is an umbrella to track that work as I implement it.  My current list of items to implement is:

- cellNav.  @jpdesigndev has implemented the core logic, I need to extend with unit tests and some documentation: COMPLETE
- edit.  An enableEditing flag, true by default.  You can't edit any cells in a row with this flag set to false. COMPLETE, but didn't work out a way to unit test as the flag is only settable in code, and that is hard with the current unit testing structure for this module (it assumes it can compile the grid element and then it works)
- expandable.  Ignoring for now, don't think we need this at this stage
- exporter.  exporterEnableExport, true by default.  When set to false we ignore that row in the export.  COMPLETE
- importer.  Nothing needed
- infinite-scroll.  Nothing needed
- move-columns.  Nothing needed.
- pagination/paging.  Nothing needed.
- pinning.  Nothing needed
- resize-columns.  Nothing needed.
- row-edit.  Should work off edit - if you can't edit the row then row-edit will never kick in
- saveState.  Nothing needed, however grouping options might need to be added to saveState
- selection.  enableSelection, true by default.  When set to false you cannot select the row, needs to deal with rowHeader as well.  COMPLETE, but no special handling on rowHeader - the header is still there, clicking it does nothing.

**Comment by PaulL1** [comment]
Closing this, as I think the core bits are done.

**Comment by jpdesigndev** [comment]
Woah, just saw this. Where can I test this functionality? Sorry, I haven't been more responsive.

**Comment by PaulL1** [comment]
I merged them into master Jarod, so should be all available when you're ready to use them.

**Comment by jpdesigndev** [comment]
Awesome. I'll follow up tomorrow. Thank you!
