### ISSUE TITLE
ui-grid does not respond when css height is given in %

### ISSUE THREAD

**Issue by AdityaJitu** [angular-ui/ng-grid#2466]
When I implement ui-grid in a responsive page & try to change the height then I am unable to do so. My approach is to apply height in % instead of px.  Please let me know if my approach is wrong or anything I am missing.

**Comment by PaulL1** [comment]
You may want to look at the hidden grid tutorial, it provides quite a bit of information on sizing the grid: http://ui-grid.info/docs/#/tutorial/108_hidden_grids

**Comment by PaulL1** [comment]
No commentary for some time, and solution offered.  Assuming issue has been resolved.
