### ISSUE TITLE
Is it possible to show group of columns headers with common column header and also group of rows under common row header using ngGrid

### ISSUE THREAD

**Issue by madasuk** [angular-ui/ng-grid#2468]
Please see the plunker http://plnkr.co/edit/DMH6eJ1wQaV750B6jNDj?p=preview. For '01-14',  Is it possible to represent spend, shpts, perc under a common column header Q1-14 in ngGrid? The same columns  I want to repeat under Q2-14, etc. I have attached sample image for reference. 
![requirednggrid](https://cloud.githubusercontent.com/assets/7821113/5585651/cd9916fc-90aa-11e4-94d8-a5bc0db38f2b.png)

**Comment by PaulL1** [comment]
Solution provided, and no new comments for over 4 weeks.  Assuming issue is resolved, closing.

**Comment by send4sbk** [comment]
i too facing the same issue? is it implemented or is there any alternative for grouping? please help.

**Comment by raghu185** [comment]
Its 2017, any updates on this ? has this feature been implemented ?
