### ISSUE TITLE
ScrollTop and filter weir behavior.

### ISSUE THREAD

**Issue by hmendezm** [angular-ui/ng-grid#2472]
Hi Guys, I have a ng-grid that can be filtered by department. The grid has events, meetings and announcements for each department. All info is together and I just filter the info according to the selection of the department(dropdown). The filter is working but the problem is the page has a button that takes the user to the first event of Today which can be any row in the nggrid. If I have all information without filtered, the scrolltop is working correctly but when I filter the data the scrolltop is not moving the first event of Today. The scrolltop is moving many rows forward.

How can I make the scrolltop to show the first event in the first row if the grid data is filtered?

```
  angular.forEach( $scope.gridData , function(data, rowIndex){
			            if(!foundRow)
			            {
			               if(data.EventDate == HelperService.getToday()){
				            	var grid = $scope.gridOptions.ngGrid;
				            	$scope.recordCount = grid.filteredRows.length;
   			            	        $scope.todayRow=rowIndex;				            	
				            	grid.$viewport.scrollTop((rowIndex) * grid.config.rowHeight);
				            	//grid.$viewport.scrollTop(grid.rowMap[rowIndex] * grid.config.rowHeight) 				        
				             foundRow=true;    
				            }
			            }
```

Best regards
Hmendezm

**Comment by PaulL1** [comment]
Closing on the basis of no further comment for 3 weeks, assuming raiser has resolved their issue.
