### ISSUE TITLE
unable to show data for some ng grids when their columnsDef in Grid Options is different during multi ng grids display

### ISSUE THREAD

**Issue by madasuk** [angular-ui/ng-grid#2480]
With  multiple ngGrids display I am facing problem when the columnDef option in the Grid options are differ for the different Grids. Please find my plunker http://plnkr.co/edit/y878sCsl3PJ04MhcAKYI?p=preview. Here when we click 'create multiple ng grids', Grid 2 and Grid 3 data is appearing fine, for these two columnsDef in Grid options is same. However Grid1 data is not appearing, its columnDef in Grid Options is different from Grid2 and Grid3. For reference I have separated them individually through 'Create ng Grid1' and 'Create ng Grid2', which are working fine. The same grids I am trying to create together using 'Create Multple ng Grids' button. But the first grid data is not appearing. Is there any fix for this?

**Comment by PaulL1** [comment]
It's a bit easier to help if your code is tidily formatted in the plunker.  Try this one: http://plnkr.co/edit/zPORLxUnvYA1CeyPdUgu?p=preview

I can't scroll to read the content of the gridOptions variables, any idea what it is that stops it from scrolling?

**Comment by PaulL1** [comment]
No response to information request for some time, and appears that a solution exists.  Closing.
