### ISSUE TITLE
Single search field for filtering

### ISSUE THREAD

**Issue by motiejuss** [angular-ui/ng-grid#2481]
Since `filterOptions` was dropped, does anybody know how to bind single input to filter table's rows?

Like here: http://plnkr.co/edit/PHdBhF?p=preview

**Comment by PaulL1** [comment]
Filtering is now per-column.  So implementing a single filter field isn't something that is easily handled in ui-grid.

**Comment by PaulL1** [comment]
Refer the new singleFilter tutorial: http://ui-grid.info/docs/#/tutorial/321_singleFilter

**Comment by koinca** [comment]
In the SingleFilter tutorial, how do I filter against cellFilter 'mapGender' column?
