### ISSUE TITLE
Disable individual selection checkmarks

### ISSUE THREAD

**Issue by teterovic** [angular-ui/ng-grid#2482]
Is it possible to disable some selection boxes(checkmarks) like when you want to prevent the user to select already imported files from the gridview.

i am using also infinitive scroll so i cant use a simple CSS hack

**Comment by PaulL1** [comment]
There isn't an immediately easy way to do it, but you could perhaps use:
- a cellClass function to grey out or otherwise visually indicate rows that shouldn't be selected (when I build #2448 this would be easier)
- the `rowSelectionChanged` callback to unselect rows again if the user selects them and you don't want them selected

**Comment by teterovic** [comment]
Thank you for your reply. A simple workaround to disable the checking of specific fields, the CSS also needs to be changed. The can be selected is inside the model:

in selection.js

toggleRowSelection: function (grid, row, multiSelect, noUnselect) {
          /// Add this
          var selected = row.isSelected;
          if (row.entity.canBeChecked == false) return;

/////////////////////////////////////////////////////////////////////

scope.gridOptions = {
				columnDefs: [
					{ name: 'Firstname', field: 'Firstname'},
					{name: 'Lastname', field: 'Lastname'},
					{name: 'canBeChecked', field: 'canBeChecked',
						cellClass: function(grid, row, col, rowRenderIndex, colRenderIndex) {
						  var value =grid.getCellValue(row,col);
						  return value ? 'grid-label-chacked' :  'grid-label-notchecked';
						}
					},
			]
			};

**Comment by PaulL1** [comment]
I think #2660 added this feature.  Could you confirm that it meets your needs?

**Comment by c0bra** [comment]
No response after 2 weeks. Closing.
