### ISSUE TITLE
Create a Grid Footer similar to the 2.x grid footer

### ISSUE THREAD

**Issue by swalters** [angular-ui/ng-grid#2483]
2.x had the ability to enable a grid Footer that would show:
Total Rows
Selected Rows
Filtered Rows

Create a GridFooter in core that append to the grid and does not scroll horizontally with the column scroll.

**Comment by camacazze** [comment]
Does this mean that the Grid Footer is not working correctly??

I am asking bcoz the Tutorial documentation says that it does.

I am facing a problem where the footer is not working.

Pls. reply.

**Comment by PaulL1** [comment]
It is working for me.  What problem exactly are you having?  The functionality that you see in the tutorial should be working, so long as you've grabbed the unstable version.

**Comment by PaulL1** [comment]
I think this is now implemented.  Closing.
