### ISSUE TITLE
RC.18-f8a68cc messes up styles for IE9 again

### ISSUE THREAD

**Issue by alexandery** [angular-ui/ng-grid#2485]
I've added quite a few fixes for CSS to support IE9 in version RC.16-9c495da. Tried to update to RC.18-f8a68cc only to see that the styling is all messed up and even my previous fixes do not really do their job anymore. Scrollbars are out of place in random spots on a page, headers are not visible, etc.

Do you guys incorporate or take into account fixes posted here or do you only accept fixes done on the actual codebase?

I've reverted for the time being, but once I get back to this (or later) version I will post my CSS fixes here for others to use.

**Comment by mdsauer** [comment]
Alexandery, I migrated to RC 18 and your changes are still working for me.

**Comment by PaulL1** [comment]
@alexandry: unless you submit a PR and we merge it, then it isn't in the code base, unless someone else picks up your changes and makes them into a PR.  We do pick things up and make PRs out of them, but for me I don't have IE to be able to test, so I can't easily do that.

**Comment by alexandery** [comment]
@PaulL1 Got it. Never done PRs. I'll see if I can help with the fixes there sooner rather than later. For now, I guess, we'll have to deal with CSS overrides.

**Comment by alexandery** [comment]
@mdsauer Interesting. Wasn't working for me. But I am also using a pagination, which is messing up styles in RC-18. Maybe that was the reason. I just didn't have any free time to figure it out and fix it.

**Comment by PaulL1** [comment]
There's a reasonable guide on PRs in https://github.com/angular-ui/ng-grid/blob/master/FIRST_TIMER.md

**Comment by c0bra** [comment]
Can we get a screenshot of the styling issues and a short write-up of what's expected?

**Comment by alexandery** [comment]
@c0bra At this point I think it'd be fare to say that this item should be closed. I've done a lot of code and style changes to make sure the grid works and gets displayed properly on my screens, so I cannot really provide you with screenshots of it's incorrect behavior.

**Comment by c0bra** [comment]
Understood. I'll go ahead and close.
