### ISSUE TITLE
What are thoughts on making ng-grid declarative?   

### ISSUE THREAD

**Issue by bkbonner** [angular-ui/ng-grid#2487]
Had any thought had been given to having ng-grid let the table be created in regular HTML and use directives to augment the functionality.   Something similar to:

https://www.pointblankdevelopment.com.au/blog/angularjs-fixed-header-scrollable-table-directive

It seems that ng-grid is very functional, but it would be nice to augment existing HTML tables vs having to  do everything in javascript scope configurations.

**Comment by c0bra** [comment]
It would be a huge amount of work, and it's very unlikely that someone will
take the time to write it when the grid functions as is. On top of that
there's the ongoing cost of supporting divergent ways of setting up the
grid. Additional complexity and duplication are things we are trying very
hard to avoid.

**Comment by PaulL1** [comment]
I don't think this is a direction the grid will be going in, it would really require a new project or a fork.  So closing this (mostly to keep our issue tracker tidy).

**Comment by bkbonner** [comment]
Thanks for responding.
