### ISSUE TITLE
Column moving not working well with horizontal scrolling

### ISSUE THREAD

**Issue by edmondpr** [angular-ui/ng-grid#2489]
If the table has horizontal scrolling and the columns are movable they will get into positions that are different from the ones intended when dragged to the right or left with the scroll as can be seen in the following plunker:
http://plnkr.co/edit/pBotvpDTiUdXn2U1uIW8?p=preview
Furthermore in Chrome any text over which the mouse cursor passes inside and outside of the table gets selected when moving the columns.

**Comment by PaulL1** [comment]
Right, so I think what you're saying is that as soon as you scroll the grid the column moving basically stops working - whether the grid scrolls as part of dragging the column, or just if you scroll the grid to the right a bit and then try moving columns around.@jpuri, have you seen this?

**Comment by jpuri** [comment]
HI @PaulL1 ,

I have not noticed it, but I will check this out and also review PR #2490

**Comment by jpuri** [comment]
Hey @PaulL1 ,

I checked it out column moving actually had issue with scrolling. But PR #2490 submitted by @edmondpr  has fix for it.

**Comment by tuannh99** [comment]
@edmondpr , @jpuri  : This issue is back in ui-grid's latest release.

I checked ddc8a16e6037b02c62e43f71431a7f55a1c1f315, it fixed the original issue. But it is NOT with latest code now master.
Can you please help?

**Comment by pavankumarpg** [comment]
I ran into the same issue.
Is there a workaround. I am using ui-grid 3.0.0 rc21 and tried upgrading to 3.0.1. It did not help much though downgrading might pull the fix but that may not be in option.

**Comment by vhosamath1** [comment]
I'm running into the same issue. please let me know, how to fix this issue?. 
I'm using ui-grid v3.0.7. 

Thanks in advance.

**Comment by swalters** [comment]
try 3.1

**Comment by vhosamath1** [comment]
Thanks.  is there a work around in version v3.0.7 ? our production release date coming near..so we don't want to migrate to new version at this point of time.  

Thanks again.

**Comment by swalters** [comment]
no workaround that I know about.  The fixes where made in 3.1 code.  3.1 isn't much of a major upgrade.  We only did a 3.1 because of a change to the sorting feature that made the sort counters 0 based.  If you don't do anything custom with sorts, then for you 3.1 is like a 3.0.8 release.

**Comment by shaileshayer** [comment]
HI i am using Angular UI Grid 3.2.1 Movable columns with horizontal scroll dosent work, scrolling is done only to visible columns in the viewport. Columns beyond scroll does not moves, scroll get freeze.
