### ISSUE TITLE
[BUG] Vertical scrolling does not reach fully to the top or bottom when pagination is enabled

### ISSUE THREAD

**Issue by drixta** [angular-ui/ng-grid#2491]
http://ui-grid.info/docs/#/tutorial/214_pagination

When scrolling, you can see that the vertical scrollbar does not fully reach the bottom or top. I only see this when pagination is enabled so far. 

Console says: "Uncaught TypeError: Cannot read property 'percentage' of undefined"

**Comment by PaulL1** [comment]
Is this still happening since the scrolling changes that were recently implemented?

**Comment by PaulL1** [comment]
This is scrolling all the way to the top and bottom for me.  Closing on the basis that there's no response for some time, and it appears resolved.
