### ISSUE TITLE
enableRowHeaderSelection disables enableRowSelection

### ISSUE THREAD

**Issue by popraducj** [angular-ui/ng-grid#2493]
If I set enableRowHeaderSelection to true it set to false enableRowSelection.
I need to be able to select a row by clicking it if enableRowHeaderSelection is set. I even tried to set selectWithCheckboxOnly but is not working.

How can I do that?

**Comment by PaulL1** [comment]
The feature currently cannot do that.  I had a quick look, and it appears that the row click handler interferes with the checkbox click handler, so it isn't as simple as just having both of them at the same time.

**Comment by PaulL1** [comment]
This has been implemented today, should meet the needs, refer the selection tutorial.

**Comment by thisismanish** [comment]
Looks good to me.

**Comment by gzinger** [comment]
Is this part of an official release? I still have this issue with ui-grid - v3.2.9 - 2016-09-21
