### ISSUE TITLE
[ui-grid 3.0.0-rc15] Get error whenever I scroll in the grid

### ISSUE THREAD

**Issue by pmariduena** [angular-ui/ng-grid#2495]
Hi Guys I get the following error whenever I scroll in a ui-grid:
TypeError: Unable to get property 'get Focused Cell' of undefined or null reference

I'll post a jsfiddle soon.

**Comment by PaulL1** [comment]
Suggest updating to the latest, it's likely resolved already.

**Comment by pmariduena** [comment]
I'll give upgrading a shot soon.

**Comment by pmariduena** [comment]
Upgrding to rc18 worked for me....I will close.
