### ISSUE TITLE
Incorrect width calculated until resize

### ISSUE THREAD

**Issue by alexmccabe** [angular-ui/ng-grid#2497]
I am having a strange issue on some of my grids where the incorrect width will be calculated (too wide) until the window is resized. The instantiation options are the same between all the grids, and there are roughly the same amount of columns.

**Comment by PaulL1** [comment]
I think we'd need a plunker or similar that allows us to reliably replicate the problem in order to do anything with this. Are you able to provide a plunker?

**Comment by rokugou** [comment]
http://plnkr.co/edit/7X7s6dJsXZ8GMQVk9mFK?p=preview
![screen shot 2015-01-12 at 6 02 32 pm](https://cloud.githubusercontent.com/assets/6297235/5701461/9645d95c-9a86-11e4-8b62-d9c63a7937f3.png)
(using chrome)
i have a similar problem.
click resize button, everything fine.

any idea?

**Comment by alexmccabe** [comment]
Unfortunately I can't provide a stripped down version of our app, which is entirely frustrating, and I realise that this is not much help at all. 

I have also noticed that the height of the `.ui-grid-cell` get's increased by 1px for every resize event fired by the browser.

**Comment by PaulL1** [comment]
What version are you on?  We had in the past some issues that looked like this - perhaps upgrading to unstable would resolve this issue?

**Comment by kmittal** [comment]
I too have similar type of setup as @alexmccabe mentioned, and I do see the same rendering problem happening one in 10 times maybe. Clicking browser refresh fixes it. I am using Grid 3.0.0-RC.18 with Angular 1.3.11

**Comment by alexmccabe** [comment]
We have narrowed it down to this; the grid is being calculated before the page / parent elements dimensions have been calculated. If you can, try delaying the instantiation of the ui-grid until page load is complete.

**Comment by tony0918** [comment]
I got the same issue on v3.0.0-rc.16. #2700

**Comment by httpete** [comment]
Do this as a workaround:

window.dispatchEvent(new Event('resize'));

After setting data.

**Comment by aikrez** [comment]
Same problem with v3.0.0-RC.18-7774d30

The workarround from httpete works for me.

**Comment by alexmccabe** [comment]
The workaround works for me too, from what I can tell so far. Will post again when we have tested on more of our grids. Thanks @httpete.

**Comment by httpete** [comment]
If you have issues with IE11, try this:

            setTimeout(function(){
                var evt = document.createEvent('UIEvents');
                evt.initUIEvent('resize', true, false,window,0);
                window.dispatchEvent(evt);
            }, 100);

**Comment by httpete** [comment]
I think I have a better fix, that isn't a hack.

What I found was, if the page does not have scrollbars and something on the page initiates this, the grid dies. To prevent this, I just do:

html {
  overflow-y: scroll; /* we always want to show scrollbars to prevent bouncing, and resizing issues with the grid */
}

so we always show scrollbars whether or not the content forces it. Overall, I wish the authors of this grid would have used standard <table> html which is more solid than floats which never work.Either that, or use the divs and use display: table for the css mechanism.

**Comment by c0bra** [comment]
I'm not seeing the problem with latest unstable on @rokugou's plunker. Can anyone confirm?

**Comment by rokugou** [comment]
@c0bra
latest unstable version work for me. 
Thank you.

**Comment by c0bra** [comment]
Great! Thanks.

**Comment by Odravison** [comment]
I have a issue that the scenario is:
has two grids, one has only one column with custom cell template with all necessary classes to ui-grid work.

When access the page that has this two grids, wait 5 sec, and click on tab that have this grid that I have mentioned, data isn't showed util I resize the window (browser). Curiously, if I click on the tab before this 5 sec, the data is showed properly. 

I have tried all kind of solution and nothing works.
