### ISSUE TITLE
ui-selection check boxes missing?

### ISSUE THREAD

**Issue by brianchance** [angular-ui/ng-grid#2502]
Latest unstable release does not have check boxes showing. See the tutorial... http://ui-grid.info/docs/#/tutorial/210_selection

![image](https://cloud.githubusercontent.com/assets/1154287/5654503/6d5a3ca0-9689-11e4-85dd-606cd56b2e80.png)

**Comment by extdevelopment** [comment]
+1 
and select all function (click in a left top corner) missing, not work, 
but  I do have enableSelectAll set to true, 
I tested in https://github.com/angular-ui/ng-grid/commit/d9b2314fca4d34e4a276d44bbc2d00e9a76d558a

**Comment by extdevelopment** [comment]
@AnneLaureF thx
with minified, http://ui-grid.info/release/ui-grid-unstable.min.css working properly select all and check boxes also

**Comment by brianchance** [comment]
Using the .min file does work. thank you.

**Comment by PaulL1** [comment]
Duplicate of #2511

**Comment by PaulL1** [comment]
I merged some other things, which also causes a rebuild, and I think the problem has gone away.  Can others also check?

**Comment by brianchance** [comment]
Using the latest unstable out on release works. Thanks.

**Comment by extdevelopment** [comment]
yes, rebuild ok http://ui-grid.info/release/ui-grid-unstable.css  does it work for me also thx

**Comment by bayy** [comment]
Using the latest unstable out on release works. Thanks a lot!

**Comment by PaulL1** [comment]
Excellent, thanks.  Closing.
