### ISSUE TITLE
An expandable grid with deep nesting of grids with unknown record length is unusable

### ISSUE THREAD

**Issue by majgis** [angular-ui/ng-grid#2503]
When using the expandable grid option with deep nesting of grids where the number of rows is unknown, the grid quickly becomes unusable.

Potential solution:
The expandableRowHeight setting is optional, with the height being set to the full height of the rows by default.

**Comment by majgis** [comment]
Can anyone suggest a work around for this issue?  Because expandableRowHeight is set at the grid level, it can't be used to control subgrid height on a per row basis.

**Comment by PaulL1** [comment]
It's not clear to me what exactly you mean by 'unusable', and I don't typically work on expandable (@jpuri or @novice3030 worked in that area).  But I think for this to be actionable for them you'd need to articulate which version you're using, what the behaviour is that you get (including perhaps screenshots or a plunker), and then be clear on what the behaviour is that you'd prefer to have.  Then they can potentially help you.

**Comment by majgis** [comment]
To better describe "unusable", the sub-grids get confined to smaller and smaller space and the scroll bars can't be operated with clicks and the scroll wheel doesn't solve the problem.  A plunker will be best, and I will work on that, but here is a screen shot in the interim:

![image](https://cloud.githubusercontent.com/assets/546259/5672009/e9c300e0-9749-11e4-8c27-07f8f2a9c22e.png)

**Comment by jpuri** [comment]
@majgis what you can try doing is set expandableRowHeight to a bigger value. Its not possible to make height expandable row flexible because of the way scrolling is implemented. Grid does not uses browser scrolling but rather has its own logic of scrolling (for performance reasons), scrolling logic can not work with variable row heights.

**Comment by swalters** [comment]
There is some remaining work we need to do no row heights and canvas height calculation.  Variable row heights can be allowed, but we must encapsulate all the logic that computes the canvas height.

Also, with more than 1 subgrid, the upper grids probably have not way of knowing that they need to increase the canvas height. 

We need to provide row.setRowHeight() methods that bubble up to all parent rows.

**Comment by jpuri** [comment]
@swalters, I am still not very sure if we can allow variable height for expandable rows. That is because while scrolling we need to take into consideration all expandable rows even those that are not visible. How can we determine height of non-visible rows if its variable. Rows need to have some fixed height.

**Comment by majgis** [comment]
@jpuri Even with the current setting for expandableRowHeight, the expandable rows with a single child have a lot of white space, and for my use case, there is no predicting the maximum number of children, so increasing expandableRowHeight isn't a practical solution.

**Comment by jpuri** [comment]
I agree thats issue for you, what I can suggest you is changing Expandable Template to use all available space of expandable row. You can check this comment: https://github.com/angular-ui/ng-grid/issues/2300#issuecomment-70043518

**Comment by majgis** [comment]
FYI, I'm making good progress using a custom cell template, along with useExternalSorting

![image](https://cloud.githubusercontent.com/assets/546259/5829065/d3d0f9b6-a0c9-11e4-8149-722567a41109.png)

As food for thought, I would back peddle a bit and say that support for nested data would be a great feature.  I'm unsure if expandable grid is the best solution to meet that requirement, at least in its current form.  In the interim, a custom cell template combined with useExternalSorting appears to be a workable solution.

**Comment by PaulL1** [comment]
Are you also using externalFiltering to give effect to the expand/collapse?  It looks very slick - well done.

**Comment by majgis** [comment]
Thanks.  You are right, I'll need to use externalFiltering as well, when I'm done tuning the sort. It was suggested I included all the children in the filtering, so my initial guess is that the indent and expander will be removed when the filter is in effect.

**Comment by majgis** [comment]
Sorry, I misunderstood.  I'm not currently using externalFiltering for the expand/collapse, just passing the data through a filter before setting the data, I'll look at how to best integrate externalFiltering.

**Comment by c0bra** [comment]
... so what are we left with here? Do we need to re-create this issue with what exactly needs to be changed with expandable grids? Or does the workaround suffice for this problem?

**Comment by PaulL1** [comment]
I think it would be nice to turn what @majgis has done into a tutorial - or potentially even into a feature.  It is quite similar to grouping in concept - and I think is more useful than expandable in situations where you don't actually need different columns in the expanded section than were in the original grid

**Comment by PaulL1** [comment]
I've pushed today, PR #2935.  This is alpha only, so the API is be no means stable, refer the new tutorial for known limitations.

This is along the lines of the custom template you were working on above, but with more functions.

**Comment by PaulL1** [comment]
Resolved I think with the new grouping feature, no comments for 3 weeks, closing.

**Comment by gizbo** [comment]
Hi guys,
   Where can  I find a example with more than 2 levels? 
Thanks so much,

**Comment by dineshnagarit** [comment]
[Expandable UI Grid ] , Does any one have success till now to implement Expandable UI Grid with more then 2 or 3 levels. If yes please share plunker or fiddle or detailed explanation would be great!
