### ISSUE TITLE
How to get the visible row index?

### ISSUE THREAD

**Issue by arjan123** [angular-ui/ng-grid#2505]
Suppose I want to persist the current selection based on the row index.
How can I get the visible rowindex of the currently selected row?

**Comment by steverA** [comment]
My current solution (given a row in hand) is to march through the gridOptions.data and compare $$hashKey. This assumes you do not prohibit their use:

    $scope.findIndex = function(row) {
        // find real row by comparing $$hashKey with entity in row
        var rowIndex = -1;
        var hash = row.entity.$$hashKey;
        var data = $scope.gridOptions.data;     // original rows of data
        for (var ndx = 0; ndx < data.length; ndx++) {
            if (data[ndx].$$hashKey == hash) {
                rowIndex = ndx;
                break;
            }
        }
        return rowIndex;
    };

**Comment by arjan123** [comment]
thx. Seems to do the trick...
It would be convenient though to have a build in function for that...

**Comment by steverA** [comment]
I resent the fact that the ordering both original and sorted require similar functions and it isn't inherent in the grid someplace...

**Comment by PaulL1** [comment]
Hmm.  I'll assume that you didn't really mean that you "resent" someone providing you software for free.  :-)  The normal usage is to persist by calling `row.entity.save()` - if you're using the built in angular resource service you can just call save on your entity, there should be no reason to have to search the whole array to find the visible index.

**Comment by steverA** [comment]
I was simply comparing ui.grid with ngGrid that had built in row numbering in the grid and row selection events that were very easy to work with. When a row is selected, I have to pass along to the "caller" the row number in the original data array and I didn't see an easy way to find it! I consider it a feature that was removed!

**Comment by PaulL1** [comment]
Closing, I think the original raiser has a solution.
