### ISSUE TITLE
303 tutorial broken

### ISSUE THREAD

**Issue by juliusakula** [angular-ui/ng-grid#2506]
http://ui-grid.info/docs/#/tutorial/303_customizing_column_menu

It says click the third column to test the custom menu items. No menus anywhere, no menu items "Outer Scope Alert", etc, as intended.

**Comment by PaulL1** [comment]
It's working for me at the moment.  Is it perhaps driven by $2511 mentioned above?  Could you perhaps check again?

**Comment by juliusakula** [comment]
- Appears to be working again

**Comment by PaulL1** [comment]
OK thanks, closed.
