### ISSUE TITLE
ng-grid binding issue on Tomcat server

### ISSUE THREAD

**Issue by Bhimisetty** [angular-ui/ng-grid#2507]
I deployed my application on Tomcat server (both the services and the angular templates files). I am seeing an awful behavior in grid binding.
I created a directive with ng-grid and binding of that grid. At first on loading of the page the gird has bind perfectly. But when i rebind the grid based on the conditions the data is not binding. But i am able to see the no of rows that are of from restcall.
Is the ng-grid has any impact with Tomcat server (i hope no)?
It is critical problem, waiting for the earliest response.

**Comment by PaulL1** [comment]
There is no reason that Tomcat in particular could cause an issue - ui-grid has no awareness of what type of server you're deploying on.  I suspect there's a different problem in your code, probably to do with the way you're going about rebinding, or the timing of waiting for the rest call to complete then doing the rebinding.  Are you able to provide a plunker or a code snippet of that portion?

**Comment by Bhimisetty** [comment]
Probably i can't provide the plunker. Because when i execute the same through the WebStorm, it works greatly but the problem is with the Tomcat execution. I don't know how i can provide a proof to you to reproduce the issue

**Comment by PaulL1** [comment]
Closing, as no way to recreate.
