### ISSUE TITLE
checkbox column height issue

### ISSUE THREAD

**Issue by rokugou** [angular-ui/ng-grid#2508]
Plnkr:
http://plnkr.co/edit/wZC9NisYhXRVeJmyDGdc?p=preview

![screen shot 2015-01-08 at 1 35 02 pm](https://cloud.githubusercontent.com/assets/6297235/5658416/6e74890c-973c-11e4-805e-a65e79e50d7e.png)
id. 7 row, i hardcoded height 100% for it in my browser

id.7 row is my expected result.
Am i missing something or designed for it or just a bug?

**Comment by PaulL1** [comment]
OK, so the checkbox in the rowHeader isn't growing/centring when the overall row height is altered.  I can look at that.
