### ISSUE TITLE
Firefox25 Pinning

### ISSUE THREAD

**Issue by cookednoodles** [angular-ui/ng-grid#2510]
I know this is going to sound like an odd request, but I need to support Firefox 25; Pretty much everything works so far apart from the pinning where pinned cols appear under the rest.

I've attached a screenshot from the demo.
![ff25](https://cloud.githubusercontent.com/assets/226331/5660621/b1e3d144-9722-11e4-808f-083517f2fcae.png)

**Comment by PaulL1** [comment]
We're hopefully merging some changes this morning that change some of this behaviour.  It may fix this for you.  Failing that, the likely problem is a calculation error.  Usually that particular issue arises when the column is 1 or 2 pixels wider than we expect, so basically the right container is getting shifted down below the body controller.  Sometimes the different browsers calculate widths differently (particularly older browsers), so this can turn up.  Do you get any sort of developer tools that could tell us where the width is wrong, and how much it's wrong by?

**Comment by PaulL1** [comment]
Potentially issue is resolved, and no comments on this issue for 3 weeks after request for information.  Assuming issue is resolved and closing.
