### ISSUE TITLE
Release CSS (not-minified) missing glyph codes

### ISSUE THREAD

**Issue by AnneLaureF** [angular-ui/ng-grid#2511]
It seems the glyphs are missing from the CSS in the latest release. They are present in the minified file, though.

In consequence:
* icons do not show up (of course), see for example issue #2502 
* some features are impossible to use because you can't click on the icon, for example column menus (see issue #2506)

**Comment by klode** [comment]
The glyphs are missing also in the css generated by the [Customizer]( http://ui-grid.info/customizer/)

**Comment by PaulL1** [comment]
They look to be present in the tutorial.  So that suggests to me that you're having this issue with the bower install?  If so, can you confirm:

- that you have looked at http://localhost:9003/docs/#/tutorial/116_fonts_and_installation, and that isn't the issue
- what exact version bower has installed, and that it is the latest available

Thanks,

**Comment by brianchance** [comment]
For #2502, the public tutorial does not have the icons - http://ui-grid.info/docs/#/tutorial/210_selection

Locally, the ui-grid-unstable.min.css works, the ui-grid-unstable.css does not.

**Comment by PaulL1** [comment]
OK, seeing that now.  I'll look shortly.

**Comment by PaulL1** [comment]
I think this is now resolved, I suspect it was just a build error, as I merged some other things (which also causes a rebuild) and it went away.  Can others check it is also fixed for them?

**Comment by bayy** [comment]
Using the latest unstable out on release works. Thanks.

**Comment by PaulL1** [comment]
Excellent, thanks.  Closing.

**Comment by jrodrigoav** [comment]
The NuGet package seems to have this problem too, thanks to the comment I grabbed the css from the release in the linked tutorial and fixed the url routes in the css.
