### ISSUE TITLE
Scrolling with the mouse wheel doesn't fully reach the top or bottom

### ISSUE THREAD

**Issue by AnneLaureF** [angular-ui/ng-grid#2512]
Scrolling with the mouse wheel doesn't fully reach the top or bottom, when the number of rows left outside of the viewport is inferior to `scrollThreshold` and the console show this error:
> Uncaught TypeError: Cannot read property 'percentage' of undefined

You can see this in any tutorial page.

I think this is due to line 2427 in not-minified js:
```javascript
// Let the parent container scroll if the grid is already at the top/bottom
if (args.y.percentage !== 0 && args.y.percentage !== 1) || (args.x.percentage !== 0 && args.x.percentage !== 1)) {
    evt.preventDefault();
}
```
In this case `args.y.percentage` is either `0` (top) or `1` (bottom) and `args.x` is undefined because `newEvent.deltaX === 0`, hence the error when checking the condition on the `if`
I solved it in my local copy by adding `angular.isDefined(args.x)`:
```javascript
// Let the parent container scroll if the grid is already at the top/bottom
if (args.y.percentage !== 0 && args.y.percentage !== 1) || (angular.isDefined(args.x) && args.x.percentage !== 0 && args.x.percentage !== 1)) {
    evt.preventDefault();
}
```

related issues (I think): #2491 and #2492

**Comment by bayy** [comment]
Missing one (

                                if ((args.y.percentage !== 0 && args.y.percentage !== 1) || (angular.isDefined(args.x) && args.x.percentage !== 0 && args.x.percentage !== 1)) {
                                    evt.preventDefault();
                                }

**Comment by PaulL1** [comment]
There is some work going into an alternative approach to scrollbars.  That might perhaps fix many of the various issues that we currently have (or potentially, some might still remain).  We'd probably look at this once that approach is resolved.

**Comment by AnneLaureF** [comment]
This issue seems to be fixed with commit a6d00a77271451fc7ff09301408fa229847a1293
The only remaining issue is that when the number of rows is too small to fill the viewport height, the calculated `y.percentage` is neither `0` nor `1` so it still prevents the whole page to be scrolled.

**Comment by mikehuebner** [comment]
I also noticed I'm having this issue with a grid that maxes out data, I get this error from this line.
![image](https://cloud.githubusercontent.com/assets/6125123/5688568/a5c25688-980d-11e4-94d1-2bb9a416f8db.png)

```
// Let the parent container scroll if the grid is already at the top/bottom
              if ((args.y.percentage !== 0 && args.y.percentage !== 1) || (args.x.percentage !== 0 && args.x.percentage !== 1)) {
                evt.preventDefault();
              }
```

This happens every time I scroll.

**Comment by PaulL1** [comment]
A major change went in this morning on master that related to scrolling.  It might address this issue.  There's unlikely to be any diagnosis unless you can replicate on master.

**Comment by mikehuebner** [comment]
I just updated the versions, that issue went away but multiple more appeared. I noticed there are scroll bars on the grid now!

The only issue I'm finding is scrolling to the bottom of a rid may not happen sometimes.

**Comment by PaulL1** [comment]
What does "scrolling to the bottom of a grid may not happen sometimes" mean?  Is it something that happens on the tutorials, are there steps to replicate it?

**Comment by mikehuebner** [comment]
Sure thing, sorry for the short response.
I have the row height set to 30, and there are occasions where the grid height doesn't match the row heights combined. But with no grid height set it gets to the bottom fine. It could be some extra stuff I'm doing, I haven't done too much Testing yet I just wanted to bring it to your attention at least.

**Comment by PaulL1** [comment]
Believed to be fixed in recent changes, assuming is resolved and closing.

**Comment by MishaTornes** [comment]
Issues is still present Please see bellow.
Happens as reported when you scroll up and the grid is at the top of the collection.
![ui-grid bug-version](https://cloud.githubusercontent.com/assets/2124154/7642428/e961f2d2-fa5e-11e4-9b9f-83c96088ba9a.PNG)
![ui-grid bug](https://cloud.githubusercontent.com/assets/2124154/7642433/ed13b4e2-fa5e-11e4-9ba0-7fc1907e1298.PNG)
