### ISSUE TITLE
cellClass row index not changing on sort

### ISSUE THREAD

**Issue by furier** [angular-ui/ng-grid#2525]
cellClass row index does not changing on sort.

By that I mean that whenever I sort a column on its value the cellClass sticks to the original cell and does not follow the value.

[Youtube video of the bug](https://www.youtube.com/watch?v=cQyc9qXYUQM)

    var utils = {
        colorizeNumbers: function (grid, row, col, rowRenderIndex, colRenderIndex) {
            var value = grid.getCellValue(row, col);
            if (value < 0) {
                return 'red selectable';
            }
            else if (value > 0) {
                return 'green selectable'
            }
        }
    };

    $scope.playerBalanceGridOptions = {
        enableSorting: true,
        enableFiltering: true,
        pagingPageSizes: [10, 20, 30],
        pagingPageSize: 20,
        columnDefs: [
            {field: 'name', cellClass: 'selectable'},
            {field: 'hassium', cellClass: utils.colorizeNumbers, cellFilter: 'numeral'},
            {field: 'indium', cellClass: utils.colorizeNumbers, cellFilter: 'numeral'},
            {field: 'strontium', cellClass: utils.colorizeNumbers, cellFilter: 'numeral'},
            {field: 'neodymium', cellClass: utils.colorizeNumbers, cellFilter: 'numeral'},
            {field: 'total', cellClass: utils.colorizeNumbers, cellFilter: 'numeral'}
        ],
        data: ad2460.allianceData.playerBalance
    };

**Comment by PaulL1** [comment]
What version are you on?  I think this defect was fixed a wee while back, and should be working now.  Check the tutorials.

**Comment by furier** [comment]
my bowser.json has this line in it `"angular-ui-grid": "~3.0.0-RC.18"`, I used the code from the tutorial just now.

**Comment by PaulL1** [comment]
OK, does it work for you on the tutorials?  Are you able to provide a plunker (probably based off the tutorial is the easiest way) that illustrates the problem?  http://ui-grid.info/docs/#/tutorial/111_cellClass

**Comment by furier** [comment]
Hmmmm. strangly im not able to reproduce it with this plunker http://plnkr.co/edit/RGxTqwbeDf4zALMdiOvk?p=preview

Im using it in a Chrome Application where compatibility mode needs to be enabled for angular to work, could that cause the problems im having?

**Comment by PaulL1** [comment]
I'm suspicious of versions.  The plunker always uses the latest version (i.e. that build from source).  Perhaps the fixes aren't in RC18 yet, either that or something else in your configuration.

**Comment by furier** [comment]
I installed the version with bower: `bower install angular-ui-grid#~3.0.0-RC.18 --save` the AngularJS version used is `1.3.7`. The header in `ui-grid.js` sais `ui-grid - v3.0.0-RC.18 - 2014-12-09`.

**Comment by furier** [comment]
I copy pasted the js code from the cdn file and it worked so seem like the bower version is bad. :-1:

**Comment by PaulL1** [comment]
OK, closing as now resolved.  Thanks.
