### ISSUE TITLE
Is that possible to change a specific column's html ?

### ISSUE THREAD

**Issue by itgoujie2** [angular-ui/ng-grid#2526]
For some columns, I need some custom behaviors, so I need to customize its html, can I do that ?

**Comment by PaulL1** [comment]
There are a number of specific ways to customise:

- cellTemplate
- headerCellTemplate
- headerFilter
- cellFilter
- cellClass

If none of those meet your needs, then you can write a custom directive to extend it.

**Comment by itgoujie2** [comment]
Thanks for the response, in my case, for a column, for each row of that column, I need a different html. But using cellTemplate, that is for the whole column. I am wondering if I can define cellTemplate when I define the data ?

**Comment by PaulL1** [comment]
There is no way to have a per-cell html.  Usually you'd do that by setting your cell template to a directive, and then burying your optionality inside that directive, or if your logic isn't too complex, just using an ng-if in the cell template.

**Comment by PaulL1** [comment]
Solution provided, and no new comments for over 3 weeks.  Assuming issue is resolved, closing.
