### ISSUE TITLE
Extra characters in first column header when exporting to CSV

### ISSUE THREAD

**Issue by bayy** [angular-ui/ng-grid#2527]
On http://ui-grid.info/docs/#/tutorial/312_exporting_data_complex, after selecting "All", "All", "CSV" and clicking on "Export" button, in the generated csv file, there are extra characters on the first column header as  ` ï»¿"Person Name"`

Here is a screen shot for this problem:

![image](https://cloud.githubusercontent.com/assets/2373656/5687696/b04f403a-980c-11e4-9a01-039db8849fc9.png)

**Comment by PaulL1** [comment]
The \ufeff appears to be causing it.  I've removed it for all but Navigator, I don't have Navigator to know whether I'm better to take it out or leave it in.

**Comment by markens** [comment]
I'm not pretty sure if this is the correct place to ask this but here I go anyway...
@bayy how did you manage to get every value separated by column? I get all the row in just one column per row... like this
![image](https://cloud.githubusercontent.com/assets/3089441/16984507/b4fb01f2-4e7a-11e6-930d-d922900396f7.png)

Thanks in advance!

**Comment by matt2mi** [comment]
@markens you just need to put ; instead of this , to separate your columns ;)
