### ISSUE TITLE
External Scopes documentation is missing.

### ISSUE THREAD

**Issue by AdityaJitu** [angular-ui/ng-grid#2533]
I was following [this] (http://ui-grid.info/docs/#/tutorial/301_custom_row_template) link & I found out that **External Scopes** documentation is missing. 
I feel it would be nice to have the documentation .

**Comment by PaulL1** [comment]
It is 305, it must have moved.  I'll update the link.

**Comment by edenchen123** [comment]
why you guys remove external-scopes....
