### ISSUE TITLE
Infinite scroll 'blank block'

### ISSUE THREAD

**Issue by cookednoodles** [angular-ui/ng-grid#2535]
When using the infinite scroll at http://ui-grid.info/docs/#/tutorial/212_infinite_scroll

If you scroll down, content will load but not be shown until the 'up' scrollbar is pressed.

**Comment by Arkh1** [comment]
+1 to this.  I am seeing the same problem with infinite scroll.  I also see a similar problem without infinite scroll on a grid with a large data set.

**Comment by rkilarski** [comment]
I just noticed this as well, and looks like this was broken between 1/2 and 1/15.

**Comment by c0bra** [comment]
@Arkh1 is it still breaking for you on the large data set without infinite scrolling? I couldn't get it to happen.

**Comment by Arkh1** [comment]
Actually after switching over to the unstable version of ui-grid I no longer experience the issues I was having with large datasets.

**Comment by PaulL1** [comment]
OK, excellent, closing.

**Comment by cookednoodles** [comment]
This issue is still reproducable, I can see it on the demos and when moving over to unstable on my project. I have reproduced it on both chrome and firefox, all you need to do is go to http://ui-grid.info/docs/#/tutorial/212_infinite_scroll and scroll down via scrollbar or the mouse.

![bug](https://cloud.githubusercontent.com/assets/226331/5973799/c833273c-a86c-11e4-9515-0b5c13c9aa8a.png)

When this happens, the canvas has a height of 6000px, the first element has a margin-top of 4350px in the style. If I remove the margin on both, the scroll bar is very jumpy and initially at the wrong postion, but I can see content 'normally' for a while until it loads more content and the height changes again.

**Comment by rkilarski** [comment]
My group actually has a fix for this issue, we are working through it and will post a fix asap.  

We're also working on code to enable infinite scroll in the UP direction.  Just FYI.

**Comment by chussenet** [comment]
Cool  Ryszard !

Yes ,currently the infinite scrolling is not working . Should be taking out of the feature implemented until a basic sample works such as the sample from the tutorial !

Not working or missing features .
1-blank block after scrolling until a request is triggered to the backend to load more records.
2-keeping in memory only a subset of the records loaded to minimize footprint  
3-scrolling up and down should trigger a call to the backend if the records previously loaded were reclaimed for memory management.
4-currently ,the implementation is pushing records to the end of the array . May need more sophisticated to push ,insert in specific positions. (see slickgrid for example)

Thank you
Claude Hussenet

**Comment by cookednoodles** [comment]
The blank lines issue seems better but before (totally subjective), but is still there.

Considering this is also in the 'vanilla' add rows demo, I presume that there are some other related core issues.
