### ISSUE TITLE
Move sort arrow in columns to the right. Currently it is in the center

### ISSUE THREAD

**Issue by mschreibernaoual** [angular-ui/ng-grid#2541]
What is the best way to move the sort arrow in the column headers from the center to the right?

**Comment by PaulL1** [comment]
At the moment it goes immediately after the column title, in order to visually separate it from the column menu.  To change that I'd use a customHeaderCellTemplate.

**Comment by PaulL1** [comment]
Solution provided, and no new comments for over 2 weeks.  Assuming issue is resolved, closing.
