### ISSUE TITLE
Bug - Grid is showing as two separated parts  

### ISSUE THREAD

**Issue by elpd** [angular-ui/ng-grid#2542]
Just trying out today ui-grid. Version 3.0.0-rc.16 on Chrome and Firefox with expandable plugin.
This is what I get:
![angualr-grid](https://cloud.githubusercontent.com/assets/3258587/5728682/bbdb0270-9b74-11e4-8e59-81259d3d66e3.jpg)

When I resize manually the browser window, it returns to normal.

**Comment by PaulL1** [comment]
There is a known issue with this on http://ui-grid.info/docs/#/tutorial/401_AllFeatures.  I'm not sure it's logged, so I'll make this issue that master for that problem.

**Comment by PaulL1** [comment]
On initial rendering of this tutorial, the width of the header viewport is set to `NaNpx`, which then doesn't seem to render well.  Once data is populated, or resize is called, or anything else that triggers a grid refresh, the width is set to 470px, and the grid isn't 'broken'.

Tracked this down to the width calculations in ui-grid-render-container.js, and in particular the adjustors once the selection column is present.  Sometimes the drawnwidth isn't present (column not drawn yet), in this case use width instead.  Sometimes the calls aren't sequenced as we expect, so if there isn't a calculated width, call updateWidth first.
