### ISSUE TITLE
No way to toggle enableRowSelection

### ISSUE THREAD

**Issue by flea19** [angular-ui/ng-grid#2543]
Need ability to toggle enableRowSelection similar to setMultiSelect(true/false).

**Comment by PaulL1** [comment]
Have you tried directly changing gridOptions.enableRowSelection?

**Comment by flea19** [comment]
Yes. I see the value update when using the debugger but it doesn't seem to actually stop the event from going out.

**Comment by PaulL1** [comment]
I believe this is now handled dynamically, and demonstrated in the tutorial.
