### ISSUE TITLE
When will the 3.0 be finally released? What is the current version & status?

### ISSUE THREAD

**Issue by camacazze** [angular-ui/ng-grid#2545]
I wanted to know - when will the 3.0 be released. The ng-grid page says that ui-grid is in "beta"? The ui-grid download button, on the home page takes me to a "release" directory on github. The current version nos. are marked with "RC"?

Is it true that the the current version is an "RC" - "Release Candidate"? Do we have some idea when the module will be released. I know RC is almost as good as released, but still, when is the plan to release the first "Release" version?

Many thanks in advance. & kudos on a great piece of code. Great programability. Wonderful!!

Thanks from India,

Mayank.

**Comment by PaulL1** [comment]
In one sense the code base is quite close - we've issued a number of release candidates and our last major issue was improving scroll performance and alignment, some major fixes went in last week towards this end.  The API is reasonably stable, and there are people using the grid as-is.

In another sense, this is the classic open source question, and the answer is that it will release when there are no more hi-pri bugs outstanding, and all planned features are included.  The main outstanding feature that would be good to include in 3.0 is grouping, and there is some work underway on that, but it is reasonably complex.  In terms of hi-pri bugs, there aren't so many really at the moment, but there are a few niggles still out there.  

We still have quite a small contributor base, none of whom have the luxury of spending much time on the grid, so even though the work remaining probably isn't huge, that could still mean months or more away.

**Comment by rkilarski** [comment]
My org is also quite interested in this question, thanks for giving some direction in the answer!

**Comment by PaulL1** [comment]
OK, I think we're getting close to 3.0 release.  I've created a new 3.1 milestone, and I'm working through all the issues to either leave them in 3.0 (implying we're not releasing until they're closed), put them in 3.1 (implying I think they're needed reasonably soon after 3.0), or putting them in future, implying that they're a good idea but really dependent on someone to decide to do a PR.

This should mean that you can tell how close 3.0 is just by watching the 3.0 milestone.  https://github.com/angular-ui/ng-grid/milestones

**Comment by PaulL1** [comment]
We're getting close to 3.0 - in the sense that there are now 13 open issues.  This one being open is a contributor to that 13!!  I'm closing it in favour of #727.
