### ISSUE TITLE
virtualizationThreshold  max limit

### ISSUE THREAD

**Issue by kavinnashi** [angular-ui/ng-grid#2546]
Hi ,
I just want to know is there any limit on manually setting  the virtualizationThreshold, if so on what factors it depends.
Thank you

**Comment by PaulL1** [comment]
I'm not aware of a limit in terms of it physically not working.  If you are setting it to a very high value, then potentially you'd be better just using an HTML table, as you'd be not using a lot of the grid functionality.  As you increase the virtualisation threshold I'd expect your performance to decrease as your browser will need to keep track of a lot of DOM elements.

**Comment by kavinnashi** [comment]
say what would be the maximum limit for a gb ram and ie 11

**Comment by PaulL1** [comment]
I think it is very machine dependent, and remember that you need to consider all your potential users (e.g. some may have mobile phones).  You'd need to test it in your application and your usage.

**Comment by c0bra** [comment]
I'm going to close as I don't think we can provide more direction.
