### ISSUE TITLE
ng-grid 2x version 

### ISSUE THREAD

**Issue by kavinnashi** [angular-ui/ng-grid#2548]
how to achieve $scope.gridApi.core.refresh();
actually my aim is to refresh the column heared once the new header is populated.
in ng-grid 2x version

**Comment by PaulL1** [comment]
I'm not sure that it's necessary to call refresh in 2.x.  What specifically are you trying to achieve?

**Comment by kavinnashi** [comment]
Actually I want to push data from server into the already existing columndef,I am able to push some dummy  local (defined locally) objects into it but the server objects are also pushed in to it but the grid column is not rendered again. I follow https://github.com/angular-ui/ng-grid/issues/128 issue but it holds good for local data I am unable to work it out for server data.
