### ISSUE TITLE
Toggle grid footer doesn't fill remaining space

### ISSUE THREAD

**Issue by PaulL1** [angular-ui/ng-grid#2554]
On the footer tutorial: http://ui-grid.info/docs/#/tutorial/105_footer, when clicking the toggle footer button, or the toggle column footer button, the footer disappears, but the grid doesn't fill the space now freed up.

**Comment by rupampatel2006** [comment]
@PaulL1 footer has still many issues. I display 5-6 line of calculations in footer and column separator doesn't expand beyond one row if particular footer cell is empty. Ideally all cell separator should expand  if footer is multi-line

**Comment by PaulL1** [comment]
Closing as duplicate.
