### ISSUE TITLE
Bad state of ui-grid stability!

### ISSUE THREAD

**Issue by camacazze** [angular-ui/ng-grid#2562]
Is it true that the ui-grid is very unstable right now?

I think it's not fit for professional/commercial use? Is that actually true or it's just me who has had a bad experience. My standpoint?

We were evaluating ui-grid for adoption in our app, maturing in 5-6 months. Want to have a good idea about this. Should we use ng-grid instead, until then?

I really haven't seen such an unstable & not ready RC version. Am I getting the right feel about this gentlemen, or am I mistaking something.

The ng-grid homepage says that ui-grid is in beta. Is it actually in beta, or is it in RC?

Below is a depiction of it in action (picture). Filters are working, editing is working, selections are working half, but nothing else seem to be working fine. Footer is not visible, pinning is not ok, selection check-marks are not fine, ascending/descending/pinning menu is not displaying at the right place, etc.

Regards.

![image](https://cloud.githubusercontent.com/assets/10526998/5756921/35585dca-9cdb-11e4-8568-788450365eb0.png)

**Comment by alexandery** [comment]
Sorry, but your post here is very confusing and not constructive. You are not really reporting any bugs with a good set of steps to reproduce and screenshots to match. All you have here is a screenshot of the grid with row header selection marks missing. You have not provided your configurations and code. You have mixed multiple issues into a single, not precise post. If I was a developer of ui-grid I would simply ignore your post.

I believe you should first figure out which exact issues you are having. Then create posts here for each one of them, adding as much details, screenshots, configs as necessary. That way the developers will have much better details of what is wrong.

**Comment by PaulL1** [comment]
I'd be focusing on what version you're using, and pulling the latest unstable version which has fixes for many of the issues you mention.
