### ISSUE TITLE
Issue when tabbing between filters results on horizontal scroll

### ISSUE THREAD

**Issue by mortjo** [angular-ui/ng-grid#2573]
When using tab to navigate between the filters and there is a horizontal scrollbar the header row will get out of sync with the other rows.

Can be reproduced in this [grid](http://ui-grid.info/docs/#/tutorial/401_AllFeatures)

Focus on the first filter's input field and press tab you reach a field that is currently hidden. The header row will move but the scrollbar and the data rows will remain in the same position .

![image](https://cloud.githubusercontent.com/assets/10530381/5774184/8491a4a6-9d6b-11e4-8f0d-05e11cc1aaf7.png)

**Comment by PaulL1** [comment]
OK, looking at your plunker, it looks like when tabbing between the filters leads to a horizontal scroll being triggered, that scroll is only occurring on the header, and not on the body of the grid.

@swalters, any tips on where in the code I'd look for this?

**Comment by swalters** [comment]
normal tabbing now works exception for one situation that we see on 401 Tutorial
- holding down shift tab on the last filter column can result in header getting out of sync

**Comment by PaulL1** [comment]
Looks like this is resolved, closing.

**Comment by hoonto** [comment]
I have this issue in 3.0.6, is this resolved in that version?
