### ISSUE TITLE
filter only specific columns

### ISSUE THREAD

**Issue by alascaboy** [angular-ui/ng-grid#2575]
Is there any way to filter only specific columns of the data and not the whole model? for example the model has an ID , a name and a code. I want only the search box to filter the name and code columns and not the id.

**Comment by PaulL1** [comment]
I'm assuming this relates to the 2.x code base?  I think there's a syntax where you put the column name at the start of the filter - something like `name:fred`.

**Comment by alascaboy** [comment]
Thank you for your response. My problem is not for one column but for multiple columns. The <code>name:fred</code> works perfectly when I want to filter for names. But I want to filter for column name OR column code. The <code>name:fred;code:fred</code> is working only if in both columns the word fred exists. I want to use the logical or expression not the end expression in order to search in both columns.
Thank you

**Comment by PaulL1** [comment]
I don't believe that ng-grid supports OR syntax.

**Comment by PaulL1** [comment]
Closing, as this is really an enhancement request on 2.x, but we're not doing enhancements on 2.x any more.
