### ISSUE TITLE
borders for last column and last row

### ISSUE THREAD

**Issue by swalters** [angular-ui/ng-grid#2579]
Can we get some CSS magic to add the seperator line on the right side of the last column and one on the bottom of the last row?  The grid doesn't look finished when the canvas is partially filled.

![1-16-2015 12-35-05 pm](https://cloud.githubusercontent.com/assets/195646/5781925/49c6a194-9d7c-11e4-8d18-62fcda7c59c5.png)

**Comment by whisperofdoom** [comment]
Here ya go

// last row
.ui-grid-row:last-child > div > div > div {
    border-bottom: 1px solid black !important;
}

//last col
.ui-grid-row > div > div > div:last-child {
    border-right: 1px solid black;
}
