### ISSUE TITLE
can not edit a cell in modal

### ISSUE THREAD

**Issue by blsr** [angular-ui/ng-grid#2583]
I am not able to edit a cell in a modal
Please check the example in plunker and let me know if I missed something

http://plnkr.co/edit/dGf2kEnPSU2uJKwfyldX?p=preview

**Comment by PaulL1** [comment]
This one works.  I can't quite see what's different though: http://plnkr.co/edit/gYvz5JIhUXfdy4cbLweF?p=preview

**Comment by blsr** [comment]
Thanks ... I know the issue

**Comment by PaulL1** [comment]
OK, closing.
