### ISSUE TITLE
RTL vertical scroll bar is missing when using pinned columns

### ISSUE THREAD

**Issue by novice3030** [angular-ui/ng-grid#2585]
@swalters your fix causes the vertical scroll bar to disapear when using pinned columns
here is a plunker to show the problem

http://plnkr.co/edit/ifSixWAqz63XJmPxcb93?p=preview

**Comment by PaulL1** [comment]
I also note that on my Mac, the horizontal scrolling on that plunker is a bit crazy - it's jumping around a lot in what appear to be unpredicatable ways.  Am I the only one seeing that?  Taking a quick look at the RTL tutorial, it's also doing it there.  It's sort of like there's one set of code scrolling left, and another set scrolling right.  I move my trackpad in only one direction, but the grid is flicking backwards and forwards.
