### ISSUE TITLE
using ui-grid with bower and angular 1.3.9

### ISSUE THREAD

**Issue by ef7475** [angular-ui/ng-grid#2587]
Hello,

I'm using AngularJS 1.3.9 and ui-grid as well, and using bower to install my project dependencies.
However, the ui-grid bower package is using angular ~1.2.16 which gives me hell lot of problems with the project deployment.
Is there a way to use latest ui-grid bower package with angular >=1.3.9?

Thanks,
Eyal.

**Comment by mtraynham** [comment]
In you're bower.json, add a `resolutions` section:

```
    "dependencies": {
        "angular": "~1.3.9",
        "angular-ui-grid": "~3.0.0-rc.16"
    },
    "resolutions": {
        "angular": "~1.3.9"
    },
```
https://github.com/bower/bower.json-spec#resolutions

**Comment by ef7475** [comment]
Thanks. I have this in my bower.json and it doesn't work so good (actually, sometime it does and sometime it doesn't). from some reason, when I run "bower install angular", bower doesn't use the resolution and keep asking me about the angular version to use.

  "dependencies": {
    "angular": ">=1.3.9",
    "angular-ui-grid": "3.0.0-RC.18"
  },

  "resolutions": {
    "angular-ui-grid": "3.0.0-RC.18",
    "angular": ">=1.3.9"
  }

Isn't RC-18 better version to use? I encountered some issues with RC-16?

**Comment by mtraynham** [comment]
The `resolutions` is for when you call `bower install` (with no package specified).  When you have `angular` listed in your bower's `dependencies` section, there is no need to call `bower install angular` as that will try and re-download a particular version, prompting you for which version.

RC.18 is the latest, so sure that should be fine.

**Comment by PaulL1** [comment]
You may also want to be careful with capitalisation, refer #2324

**Comment by PaulL1** [comment]
@c0bra: is there something we need to change here to indicate that we're now compatible with 1.3?

**Comment by c0bra** [comment]
Yea, we need to update bower.json here: https://github.com/angular-ui/bower-ui-grid/blob/master/bower.json

I think `angular: 1.2.16 - 1.3.x` should do it?

**Comment by c0bra** [comment]
This should take effect with the next RC.

**Comment by gaving** [comment]
It appears this 1.3 compatibility fix got reverted in angular-ui/bower-ui-grid@4615685f3f7a4a4a15b1a4ee80b82da31d41d5ee

Same conflict issue here:-

    % cat bower.json
    {
      "name": "idap",
      "dependencies": {
        "angular": "~1.3.15"
      }
    }

    % bower install angular-ui-grid --save
    bower angular-ui-grid#*         cached https://github.com/angular-ui/bower-ui-grid.git#3.0.0-rc.21
    bower angular-ui-grid#*       validate 3.0.0-rc.21 against https://github.com/angular-ui/bower-ui-grid.git#*
    bower angular#~1.2.16           cached https://github.com/angular/bower-angular.git#1.2.28
    bower angular#~1.2.16         validate 1.2.28 against https://github.com/angular/bower-angular.git#~1.2.16
    bower angular#1.3.15            cached https://github.com/angular/bower-angular.git#1.3.15
    bower angular#1.3.15          validate 1.3.15 against https://github.com/angular/bower-angular.git#1.3.15
    bower angular#>= 1.0.8          cached https://github.com/angular/bower-angular.git#1.3.15
    bower angular#>= 1.0.8        validate 1.3.15 against https://github.com/angular/bower-angular.git#>= 1.0.8
    bower angular#^1.2.9            cached https://github.com/angular/bower-angular.git#1.3.15
    bower angular#^1.2.9          validate 1.3.15 against https://github.com/angular/bower-angular.git#^1.2.9
    bower angular#>=1.0.8           cached https://github.com/angular/bower-angular.git#1.3.15
    bower angular#>=1.0.8         validate 1.3.15 against https://github.com/angular/bower-angular.git#>=1.0.8
    bower angular#>=1.3.0           cached https://github.com/angular/bower-angular.git#1.3.15
    bower angular#>=1.3.0         validate 1.3.15 against https://github.com/angular/bower-angular.git#>=1.3.0
    bower angular#*                 cached https://github.com/angular/bower-angular.git#1.3.15
    bower angular#*               validate 1.3.15 against https://github.com/angular/bower-angular.git#*
    bcower                        ECONFLICT Unable to find suitable version for angular

Any breakage reasons? Having issues with the resolutions block too.

**Comment by danielstankiewicz** [comment]
Since it's closed and the problem is still present, here's the link to the "reopened" issue #3925
