### ISSUE TITLE
External scope for cellEditableCondition 

### ISSUE THREAD

**Issue by smithscripts** [angular-ui/ng-grid#2589]
I need a way to disable/enable a cells edit function based on an external scope.

            cellEditableCondition: function ($someExternalScope) {
                return $someExternalScope.view.isEditing;
            },

Is this possible?

**Comment by PaulL1** [comment]
Can you handle this with a standard javascript closure?

**Comment by smithscripts** [comment]
I solved this issue by using:
cellEditableCondition: function ($scope) {return $scope.col.grid.appScope.view.isEditing;},
