### ISSUE TITLE
ng grid edit field loosing data 

### ISSUE THREAD

**Issue by kavinnashi** [angular-ui/ng-grid#2590]
The issue is the data in edit template is auto rendered when the particular column is rendered ie(the column is scrolled to such position that it is not displayed then on scrolling back the data edited is lost and old data is populated.

**Comment by PaulL1** [comment]
Are you able to provide a plunker, and some recreation instructions?

Is this the same as #2115?  I think there is another out there on cellFocus and scrolling, if you're using cellNav.

**Comment by kavinnashi** [comment]
yeah the same issue

**Comment by PaulL1** [comment]
OK, closing as a duplicate then.
