### ISSUE TITLE
Resizing columns causes cells to be highlighted in IE9

### ISSUE THREAD

**Issue by mdsauer** [angular-ui/ng-grid#2594]
When columns are resized by dragging the header border in IE 9 the data in the cells is highlighted.
This is using the latest unstable version of RC 18 as of 1/16/2015

![image](https://cloud.githubusercontent.com/assets/8696368/5818047/ddecb3bc-a07f-11e4-833c-588bbffad698.png)

**Comment by c0bra** [comment]
Setting `.user-select(none);` on the resizer less class may fix it.

**Comment by sunz7** [comment]
I'm having the same issue here. @c0bra It looks like "user-select" is supported by IE9. Any other suggestions? Thank you!
