### ISSUE TITLE
Type='Date' not working in IE 

### ISSUE THREAD

**Issue by AdiCam** [angular-ui/ng-grid#2595]
We're currently using an editable date field in our project. The date picker pops up properly on Chrome and Firefox but noticed it doesn't work in IE (which is necessary for us). When editing the field, it acts as a regular text field in IE instead of displaying the date picker tab.

This is the field: 
{ field: 'ApprovalDate',          displayName: 'Approval Date', type: 'date', cellFilter: 'date:"yyyy-MM-dd"',      width: 144 }

I searched and noticed the ones in this tutorial don't work in IE as well:
http://ui-grid.info/docs/#/tutorial/201_editable

Also, is there any way to disable the "X" and the up/down icons when editing the date field. I've attached a screenshot showing what I'm talking about.

![screen shot](https://cloud.githubusercontent.com/assets/10619185/5823506/5d234cf6-a0ab-11e4-98ad-321cfef1e8d1.jpg)

**Comment by longshot5112** [comment]
I don't believe this is an issue with ui-grid.
The "date" type of html input tag is a new part of html5 and is not supported in IE or Firefox, currently.

If you want a consistent experience across browsers, you should consider implementing your datepicker with jQuery or Angular-ui (ui-bootstrap).

Sources:
http://www.w3schools.com/html/html_form_input_types.asp
https://stackoverflow.com/questions/12455506/html5-input-type-date-color-range-support-in-firefox-and-internet-explorer

**Comment by AdiCam** [comment]
Gotcha. I'm still fairly new to angular so I assumed when defining type="date", it was using some pre-defined cell template that was set by ui-grid. I looked into using jQuery, but the grid is in a modal, so I had some challenges. I'll look into Angular-ui datepicker. 

Thanks for the reply.

**Comment by PaulL1** [comment]
Be careful here - there are a number of issues open related to this - #2279, #2321, #2196, #1785, #2290.

They all come down to that ui-grid uses native html5 editors and widgets, and not all browsers support these as yet.  What would be nice would be to implement bootstrap widgets instead (as a feature), but that is actually kinda hard, and is why people haven't done it.  Any new editor directive needs to honour the EDIT_START and other EDIT events - refer the edit tutorial that briefly mentions this, and look in the edit feature itself to see the directives that have been created for each of the edit widgets.
