### ISSUE TITLE
Column name adds extra space

### ISSUE THREAD

**Issue by regoarrarr** [angular-ui/ng-grid#2596]
I want to have a column name called "UA.Y", with all caps. 

UI-Grid is adding a space between the U and A.  

http://plnkr.co/edit/EqO4R3LNrWVSUwqYRFNA?p=preview

I think that it is in the readableColumnNames function

                        // Put a space in between words that have partial capilizations (i.e. 'firstName' becomes 'First Name')
                        // .replace(/([A-Z]|[A-Z]\w+)([A-Z])/g, "$1 $2");
                        // .replace(/(\w+?|\w)([A-Z])/g, "$1 $2");
                        .replace(/(\w+?(?=[A-Z]))/g, '$1 ');

I'm not sure what the best thoughts are as far as changing column names, or is there a way to bypass the smart column name replacing?

**Comment by PaulL1** [comment]
You can use the displayName property on each column to override the automatically calculated name.

**Comment by regoarrarr** [comment]
Thanks - that solves what I was looking to do

**Comment by redfox05** [comment]
Can the team add a flag for this to turn this feature off. All our SQL column names are in caps, so this would cause chaos for us.

**Comment by PaulL1** [comment]
Again, you can override this behaviour by setting a displayName on the column.

**Comment by redfox05** [comment]
PaulL1, that was already stated above. The reason we cant use that is that ALL our column names are in caps. The data can sometimes be variable, and the nice thing about ui-grid, especially during development, is that it can dynamically style the columns without needing to specify them first.

So just to be clear, in our use case, we cannot specify the columns beforehand, so we cannot use displayName.

Hence my request is to add a config flag to allow a developer to switch off this feature. I'm hoping it should be possible, as the feature itself is adding to the functionality, so the flag prevents it from executing the extra code that processes the column names into CamelCase.

**Comment by codeofsumit** [comment]
I'm also +1 that this can be deactivated. We have hundreds of dynamic columns and can't write a column definition for each.

We have all caps abbreviations like "PLZ" or "VLM ID" <-- there is obviously no point in making that "V L M I D".

**Comment by rogercloud** [comment]
Any updates on this issue? I'm in the same situation as @codeofsumit and @redfox05.

**Comment by potatopeelings** [comment]
Here'e a quick example of overriding `displayName` (as mentioned in PaulL1's comment) for dynamic columns (where you don't specify the `columnDefs` but allow it to be driven by data)

```
$scope.gridOptions.data = data;
$scope.gridOptions.columnDefs = Object.keys(data[0]).map(function (key) {
    // set displayName to the property name itself
    return {
        field: key,
        displayName: key
    }
});
```
