### ISSUE TITLE
Re-compile cellClass?

### ISSUE THREAD

**Issue by juliusakula** [angular-ui/ng-grid#2598]
I have a cellClass function, it returns a class 'group0' - 'group20'. 

I have a service which stores a JSON object which determines which columns have the cellClass applied.

I have a menuItem which toggles the value in that service. The cell class function checks the service before returning a group:

if(coloredColService[this.name]){
  return 'group' + num; // When the menuItem changes coloredColService[this.name] to false, the cellClass should return nothing, so no special styling would be applied. 
}

I'm fairly certain my code is working and the cellClass just needs to recompute itself. If I directly change the service to return false or true, the styling goes away or appears. If I alert the value of the service, I confirm I'm changing the service, as well.

Is there a *gridApi.grid.method()* to re-render the grid or column after clicking a column menu item?
http://plnkr.co/edit/AzyY6zfB39jFdWl0XhiZ?p=preview (<-- click column menu for "Name"). I brought this up near the end of #1773, where it was suggested I use a directive/ row template -- I am completely unfamiliar with directives and would prefer just to tell cellClass() to render itself again.

**Comment by PaulL1** [comment]
Notifydatachange should recalculate classes.

**Comment by juliusakula** [comment]
So from within my MenuItems:

menuItems: [
        {
            icon: 'ui-grid-icon-ok',
            title: "Toggle Color",
            action: function(){ 
              alert(this.context.col.colDef.name + " is " + $scope.coloredCols[this.context.col.colDef.name]);
              $scope.coloredCols[this.context.col.colDef.name] = false; // = !$scope.coloredCols[this.context.col.colDef.name];
              this.cellClass.notifyDataChange();
            }
        }],

**Comment by juliusakula** [comment]
I got it -- http://ui-grid.info/docs/#/api/ui.grid.core.api:PublicApi ...$scope.gridApi.core.notifyDataChange($scope.gridApi.grid, uiGridConstants.dataChange.COLUMN);

http://plnkr.co/edit/AzyY6zfB39jFdWl0XhiZ?p=preview

Thanks!!

**Comment by aloha** [comment]
This should be in the documentation somewhere.  Very helpful when you are using a custom cellClass to highlight table cells.  notifyDataChange is key to get the cell to update when your threshold for cell highlighting (or class naming) is dynamic.
