### ISSUE TITLE
sortChanged event lunched twice when ui.grid.moveColumns is used.

### ISSUE THREAD

**Issue by romcode** [angular-ui/ng-grid#2601]
Hi.
When i want to sort a column the sort event "sortChanged" for the external sorting is lunched twice with moveColumns dependency on.
This is the punker for the issue.
http://plnkr.co/edit/o7Yi17bNyLF8QaJW6poY?p=preview
Thanks

**Comment by jpuri** [comment]
Hi @romcode....I am looking into this issue, will update you soon about it.

**Comment by jpuri** [comment]
which browser/ device are you using ?

**Comment by romcode** [comment]
Hi @jpuri , i'm using chrome / windows os. Thanks

**Comment by jpuri** [comment]
Hi @romcode ,

I could find the issue and will soon fix this.

**Comment by c0bra** [comment]
Looks like this is working correctly now. @romcode if you still have any problems please open a new issue. Thanks!
