### ISSUE TITLE
Dynamic external filtering

### ISSUE THREAD

**Issue by paambaati** [angular-ui/ng-grid#2602]
The tutorial for UI Grid on [external filtering](http://ui-grid.info/docs/#/tutorial/308_external_filtering) shows how to do server-side filtering using the `filterChanged` event. Is there a way to find which column's filter changed? I would like to build a search query on the fly and send an AJAX request to fetch the data.

**Comment by paambaati** [comment]
Currently, I am able to get what I want with this.

```
gridApi.core.on.filterChanged($scope, function() {
    var grid = this.grid;
    angular.forEach(grid.columns, function(value, key) {
        if(value.filters[0].term) {
            console.log('FILTER TERM FOR ' + value.colDef.name + ' = ' + value.filters[0].term);
        }
    });
});
```
This feels a bit hacky though, with the iterating and whatnot. Is there some variable that holds the columns that just got filter terms?

**Comment by PaulL1** [comment]
No, as noted in the documentation, the watch that we're using doesn't easily let us work out which column changed (and for the internal filtering, isn't an issue as we just reapply the full filter).  So what you're doing is the right approach.

**Comment by paambaati** [comment]
Well, alright then. I'll go ahead with just doing this. Will keep an eye out for changes in the filtering API though. Thanks!

**Comment by PaulL1** [comment]
OK, sounds like this is resolved, closing.
