### ISSUE TITLE
Restoring state with external filtering.

### ISSUE THREAD

**Issue by cookednoodles** [angular-ui/ng-grid#2603]
When restoring a grid from a saved state with external filtering from something like (http://ui-grid.info/docs/#/tutorial/308_external_filtering). The event isn't emitted, so the sort isn't run.

Is there a non hacky way around this ?

**Comment by PaulL1** [comment]
Updated today - I'm now triggering events for sortChanged, visibilityChanged and filterChanged.

**Comment by cookednoodles** [comment]
Shouldn't the events be something like 
grid.api.core.raise.sortChanged(grid, grid.columns[currentIndex]);

To know what col was changed ?

**Comment by PaulL1** [comment]
The sort event doesn't tell you which sort changed - in a number of instances it's not possible to work it out (I think this is documented in the API documentation).
