### ISSUE TITLE
Trying to load gridoptions from server

### ISSUE THREAD

**Issue by nrso** [angular-ui/ng-grid#2604]
I want to build the gridOptions on server side to be able to serve columns dynamically according to user configuration.
The issue is that when i try to load gridOptions, the gridOptions is broken and not taken into account (randomly the header is not shown correctyl, on plnkr)

http://plnkr.co/edit/WflBPm4Jkf9Gquekq25j?p=preview

I init the gridOptions
`$scope.gridOptions1 = { };`

then i do a fake delay load
```
   $timeout(function() {
     $scope.gridOptions1 = {
        enableSorting: false,
        columnDefs: [
          { field: 'name' },
          { field: 'gender' },
          { field: 'company', enableSorting: false }
        ],
        onRegisterApi: function( gridApi ) {
          $scope.grid1Api = gridApi;
        }
      }
  });
```

**Comment by PaulL1** [comment]
I think  your problem relates to pointers and overwriting objects.  You set gridOptions1 to point to a particular object (an empty object).  You then tell the grid to use that object by giving it a pointer to it.  Later, you change gridOptions1 to point to a different (new) object, but I suspect that the grid is still pointing to the old object.

I think the intermittent behaviour is due to timing - sometimes the grid has already used the object, sometimes it hasn't.  I also suspect it's actually gridOptions1.columnDefs that is causing the problem.

If I rewrite your code to extend the existing object instead of overwriting it, it seems to work reliably: http://plnkr.co/edit/sJxgyO957Y8zsZXl6vzi?p=preview

**Comment by nrso** [comment]
I'll try to look deeper on whats going on. I tried your solution but its still not working

As you can see on that example:
http://plnkr.co/edit/gYIYMzD4LfKvZRs7qmVM?p=preview
I show 2 columns and disable the sort on the Company column
gridOptions1 which is filled in the timeout prints all the fields without taking into account the columnDefs
gridOptions2 does the job

**Comment by PaulL1** [comment]
In that second example, you're again repointing the columnDefs at a different array, which is breaking the pointers - I don't think this is ui-grid stuff so much as javascript stuff.

http://plnkr.co/edit/zCEcb77ecSeuPU9dOHDF?p=preview

**Comment by nrso** [comment]
I shouldnt have put that button "switch"

What i wanted to point out is that i have those 2 grids
One is loaded directly in the controller and the other one at some time after (timeout)

In the timeout i set
     $scope.gridOptions1.enableSorting = true; // This says all columns must have sort enabled
     // use of concat to not override columnDefs pointer (columnDefs object is supposed to have been created by ui-grid)
     $scope.gridOptions1.columnDefs.concat([
          { field: 'gender' },
          { field: 'company', enableSorting: false } // this overrides gridOptions config for company column to disable sort options
        ]);

like you proposed with the concat to keep the same pointer, so i'm expecting to not have sorting on company column, but i still have the "Sort descending" "Sort ascending"

Here is the plnkr without any noise and some comments: http://plnkr.co/edit/mYFHH8rq542ow7mUxd15?p=preview

**Comment by PaulL1** [comment]
OK, in this case, you've never set columnDefs, so concat-ing doesn't make sense.  If you run without the concat, I think it works:
http://plnkr.co/edit/mYFHH8rq542ow7mUxd15?p=preview

**Comment by PaulL1** [comment]
Solution offered, no comments for 2 weeks, assuming this is resolved and closing.
