### ISSUE TITLE
a <span style="float:right">Foo</span> inside cellTemplate not correctly rendered on firefox

### ISSUE THREAD

**Issue by steeeveb** [angular-ui/ng-grid#2605]
I'm tryng to modifing a cell template in this way:
```javascript
'<div class="ngCellText" ng-class="col.colIndex()"><span ng-cell-text>{{row.getProperty(col.field)}}</span><span style="float:right">Foo</span></div>'
```
and other combinations of tags with float:right. The result is always the same, on chrome, I have the correct behaviour, but in firefox the rendering of the cell is broken.
I have tryed with nggrid 2.0.14 and beta18 of uigrid

**Comment by PaulL1** [comment]
OK, the obvious answer would be to not use float:right?  

I've build a plunker of something that I think would approximate what you're asking for: http://plnkr.co/edit/8bd3H7QFYoJD8ol77Vje?p=preview.  As you note it's working fine on Chrome, and it's also working on safari.

**Comment by steeeveb** [comment]
thank you very much!
