### ISSUE TITLE
grid in a ui.bootstrap tab draws column header too far

### ISSUE THREAD

**Issue by steverA** [angular-ui/ng-grid#2606]
using latest 3.0rc18. When I switch tabs, there is a momentary display with the column header extending off the screen.
![2015-01-21-162810-centricity business - internet explorer](https://cloud.githubusercontent.com/assets/9431902/5845593/45437f8a-a18b-11e4-94f4-a7f9904d2b0a.png)
Shortly thereafter, It pops back to the correct size.
![2015-01-21-163403-centricity business - internet explorer](https://cloud.githubusercontent.com/assets/9431902/5845611/6bf2807c-a18b-11e4-88ee-84d18a3625c6.png)
Debugging, you can see the width of the grid.
![2015-01-21-163555-clipboard](https://cloud.githubusercontent.com/assets/9431902/5845657/d1b7695e-a18b-11e4-9039-4b903da0895c.png)
I don't think I could easily create a plunkr for this one!

**Comment by PaulL1** [comment]
Hmm.  I'm not sure that it'll be possible to do much with without a plunker!! There is a feature request for a bootstrap compatibility overall #2586, which might give us the opportunity to deal with some of these things.

**Comment by steverA** [comment]
In looking into this, if I run tutorial 101 in Chrome, the grid is 500 px wide. If I run the same tutorial 101 in IE11, the grid is 625 px wide! The ui-grid-viewport says in the debugger that it is only 500 px wide but it is larger! I can't explain the discrepancy but it might be related. To double check, I copied the plunkr to my box. Here is the over/under of the two browsers on the same code! (same main.css for both!)
![2015-01-25_16-00-20_index html](https://cloud.githubusercontent.com/assets/9431902/5893273/6f7c5f42-a4ab-11e4-83a9-9c36b1e3de96.png)

**Comment by c0bra** [comment]
@steverA Could you try this again please? I checked a Tutorial 101 plunker in IE11, both on the site and downloaded to my machine and they all rendered the grid as 500px wide.

**Comment by steverA** [comment]
I thought I posted my mea culpa some time ago. My IE was set with a 125% zoom... oops!

**Comment by c0bra** [comment]
Ah-ha! That's one I hadn't heard before :). We should probably put that somewhere in a debugging FAQ.
