### ISSUE TITLE
How to refresh grid after height changed?

### ISSUE THREAD

**Issue by mani95lisa** [angular-ui/ng-grid#2608]
The default height is 350px for display 10 rows data.
When I want to display 20 rows data I changed grid's height to 700px, then I want the grid refresh and fill all data.
Is there any method to refresh? Thanks!

**Comment by rogrdat** [comment]
$scope.gridApi.grid.refresh();

**Comment by mani95lisa** [comment]
@rogrdat Thanks, but where is $scope.gridApi ? There is only gridOptions I can get.

**Comment by PaulL1** [comment]
Check through the tutorials.  You get $scope.gridApi from the onRegisterApi callback.

**Comment by mani95lisa** [comment]
@PaulL1 Thanks, I'll have a check.
