### ISSUE TITLE
Grid alignment and rendering issue.

### ISSUE THREAD

**Issue by rogrdat** [angular-ui/ng-grid#2609]
Am having a strange issue.  The grid is being defined by the following html:

<div id="mainGrid" ng-controller="MainCtrl" style="display:none;">
   <div id="grid1" ui-grid="gridOptions" ui-grid-edit ui-grid-selection ui-grid-pinning ui-grid-pagination ui-grid-move-columns class="grid" external-scopes="$scope"></div>
</div>
   
Then I try to init the grid the following way:
app.controller('MainCtrl', ['$scope', '$http', function ($scope, $http) {
    $scope.gridOptions = {
        enablePaginationControls: true,
        paginationPageSizes     : [50, 100],
        paginationPageSize      : 50,
        enableSorting           : true,
  };

   $scope.loadData = function(data)  {
           var colDefs = [];
            angular.forEach(data[0], function(value, key) {
                     var colDef = {
                         minWidth : 45, 
                         ......
                     };
                    colDefs.push(colDef);
               });
           $scope.gridOptions.columnDefs = colDefs;
            $scope.gridApi.grid.refresh();
     }    
}]);

function loadGrid(data)   {
      $('#mainGrid).attr('style', 'display:block;');
     var scope = angular.element(document.getElementById('grid1')).scope();
     scope.loadData(data);
}

However, the grid gets rendered incorrectly
![image](https://cloud.githubusercontent.com/assets/10156078/5850367/345744ea-a1c2-11e4-9f1c-ec4be4720803.png)

**Comment by rogrdat** [comment]
Upon some investigation changing a couple of styles restores the alignment., the ones I changed (manually):

1.  Remove the width specification for the element identified by the following classes
.grid1421939520063 .ui-grid-render-container-body .ui-grid-viewport {
    /* width: 1655.4375px; */
    height: 339.1875px;
}

2.  Remove the float:left specification for the element "grid-container-body"
.ui-grid-render-container-body {
     /* float: left; */
}

Hope this helps to identify the issue..,

**Comment by rogrdat** [comment]
The basic issue boils down to this:

1.  When the div defining the grid is hidden by "style='display:none;'" and the grid options and data assigned later, the viewPortWidth and container-body position get "improperly" set.  Commenting out the following lines from the CSS and the javascript seems to fix the issue for me, but would like someone with more knowledge to confirm:

  -- from the css file comment out the line:: 
.ui-grid-render-container-body {
  /*float: left;*/
}

 --- from the javascript file comment out the portion related to the width..,
 ret += '\n .grid' + uiGridCtrl.grid.id + ' .ui-grid-render-container-' + $scope.containerId + ' .ui-grid-viewport {/* width: ' + viewportWidth + 'px; */height: ' + viewportHeight + 'px; }';

**Comment by PaulL1** [comment]
Have you looked at the hidden grid tutorial?  http://ui-grid.info/docs/#/tutorial/108_hidden_grids

**Comment by PaulL1** [comment]
Also, version of ui-grid would be important - we had an issue with selection and bad rendering quite a few RCs back - so being on the latest (RC18) or even building from source would make sense.

**Comment by rogrdat** [comment]
I'm working off the latest unstable release.  Despite using the technique described by "hidden grid" tutorial, I see that I still need the "hack-fix" to get the alignment proper.  That said, when I try to create plunkr, the same exact code with static data seems to work fine as you would expect but with different data it doesn't.  For now you could probably close this issue.

**Comment by PaulL1** [comment]
OK, I'll close for now.  Thanks,
