### ISSUE TITLE
Infinite $digest Loop

### ISSUE THREAD

**Issue by ByKraB** [angular-ui/ng-grid#2610]
I have a large Angularjs app, where I want to use ui-grid. 

I started from the test example - http://ui-grid.info/docs/#/tutorial/101_intro. Added data to controller and added row to view. The grid works, but I have a lot of error about Infinite loop in my console. 

New errors are generating when I try to scroll grid or when invoked $apply. 
You can see error details  [here](https://docs.angularjs.org/error/$rootScope/infdig?p0=10&p1=%5B%5B%22fn:%20function%20()%7Bvar%20a%3Dl(e);a!%3D%3DJ%5Bc%5D%26%26(a!%3D%3Dm%3Fm%3DJ%5Bc%5D%3Da:n(e,a%3Dm%3DJ%5Bc%5D));return%20a%7D;%20newVal:%20%7B%5C%22data%5C%22:%5B%7B%5C%22firstName%5C%22:%5C%22Cox%5C%22,%5C%22lastName%5C%22:%5C%22Carney%5C%22,%5C%22company%5C%22:%5C%22Enormo%5C%22,%5C%22employed%5C%22:true%7D,%7B%5C%22firstName%5C%22:%5C%22Lorraine%5C%22,%5C%22lastName%5C%22:%5C%22Wise%5C%22,%5C%22company%5C%22:%5C%22Comveyer%5C%22,%5C%22employed%5C%22:false%7D,%7B%5C%22firstName%5C%22:%5C%22Nancy%5C%22,%5C%22lastName%5C%22:%5C%22Waters%5C%22,%5C%22company%5C%22:%5C%22Fuelton%5C%22,%5C%22employed%5C%22:false%7D%5D%7D;%20oldVal:%20%7B%5C%22data%5C%22:%5B%7B%5C%22firstName%5C%22:%5C%22Cox%5C%22,%5C%22lastName%5C%22:%5C%22Carney%5C%22,%5C%22company%5C%22:%5C%22Enormo%5C%22,%5C%22employed%5C%22:true%7D,%7B%5C%22firstName%5C%22:%5C%22Lorraine%5C%22,%5C%22lastName%5C%22:%5C%22Wise%5C%22,%5C%22company%5C%22:%5C%22Comveyer%5C%22,%5C%22employed%5C%22:false%7D,%7B%5C%22firstName%5C%22:%5C%22Nancy%5C%22,%5C%22lastName%5C%22:%5C%22Waters%5C%22,%5C%22company%5C%22:%5C%22Fuelton%5C%22,%5C%22employed%5C%22:false%7D%5D%7D%22%5D,%5B%22fn:%20function%20()%7Bvar%20a%3Dl(e);a!%3D%3DJ%5Bc%5D%26%26(a!%3D%3Dm%3Fm%3DJ%5Bc%5D%3Da:n(e,a%3Dm%3DJ%5Bc%5D));return%20a%7D;%20newVal:%20%7B%5C%22data%5C%22:%5B%7B%5C%22firstName%5C%22:%5C%22Cox%5C%22,%5C%22lastName%5C%22:%5C%22Carney%5C%22,%5C%22company%5C%22:%5C%22Enormo%5C%22,%5C%22employed%5C%22:true%7D,%7B%5C%22firstName%5C%22:%5C%22Lorraine%5C%22,%5C%22lastName%5C%22:%5C%22Wise%5C%22,%5C%22company%5C%22:%5C%22Comveyer%5C%22,%5C%22employed%5C%22:false%7D,%7B%5C%22firstName%5C%22:%5C%22Nancy%5C%22,%5C%22lastName%5C%22:%5C%22Waters%5C%22,%5C%22company%5C%22:%5C%22Fuelton%5C%22,%5C%22employed%5C%22:false%7D%5D%7D;%20oldVal:%20%7B%5C%22data%5C%22:%5B%7B%5C%22firstName%5C%22:%5C%22Cox%5C%22,%5C%22lastName%5C%22:%5C%22Carney%5C%22,%5C%22company%5C%22:%5C%22Enormo%5C%22,%5C%22employed%5C%22:true%7D,%7B%5C%22firstName%5C%22:%5C%22Lorraine%5C%22,%5C%22lastName%5C%22:%5C%22Wise%5C%22,%5C%22company%5C%22:%5C%22Comveyer%5C%22,%5C%22employed%5C%22:false%7D,%7B%5C%22firstName%5C%22:%5C%22Nancy%5C%22,%5C%22lastName%5C%22:%5C%22Waters%5C%22,%5C%22company%5C%22:%5C%22Fuelton%5C%22,%5C%22employed%5C%22:false%7D%5D%7D%22%5D,%5B%22fn:%20function%20()%7Bvar%20a%3Dl(e);a!%3D%3DJ%5Bc%5D%26%26(a!%3D%3Dm%3Fm%3DJ%5Bc%5D%3Da:n(e,a%3Dm%3DJ%5Bc%5D));return%20a%7D;%20newVal:%20%7B%5C%22data%5C%22:%5B%7B%5C%22firstName%5C%22:%5C%22Cox%5C%22,%5C%22lastName%5C%22:%5C%22Carney%5C%22,%5C%22company%5C%22:%5C%22Enormo%5C%22,%5C%22employed%5C%22:true%7D,%7B%5C%22firstName%5C%22:%5C%22Lorraine%5C%22,%5C%22lastName%5C%22:%5C%22Wise%5C%22,%5C%22company%5C%22:%5C%22Comveyer%5C%22,%5C%22employed%5C%22:false%7D,%7B%5C%22firstName%5C%22:%5C%22Nancy%5C%22,%5C%22lastName%5C%22:%5C%22Waters%5C%22,%5C%22company%5C%22:%5C%22Fuelton%5C%22,%5C%22employed%5C%22:false%7D%5D%7D;%20oldVal:%20%7B%5C%22data%5C%22:%5B%7B%5C%22firstName%5C%22:%5C%22Cox%5C%22,%5C%22lastName%5C%22:%5C%22Carney%5C%22,%5C%22company%5C%22:%5C%22Enormo%5C%22,%5C%22employed%5C%22:true%7D,%7B%5C%22firstName%5C%22:%5C%22Lorraine%5C%22,%5C%22lastName%5C%22:%5C%22Wise%5C%22,%5C%22company%5C%22:%5C%22Comveyer%5C%22,%5C%22employed%5C%22:false%7D,%7B%5C%22firstName%5C%22:%5C%22Nancy%5C%22,%5C%22lastName%5C%22:%5C%22Waters%5C%22,%5C%22company%5C%22:%5C%22Fuelton%5C%22,%5C%22employed%5C%22:false%7D%5D%7D%22%5D,%5B%22fn:%20function%20()%7Bvar%20a%3Dl(e);a!%3D%3DJ%5Bc%5D%26%26(a!%3D%3Dm%3Fm%3DJ%5Bc%5D%3Da:n(e,a%3Dm%3DJ%5Bc%5D));return%20a%7D;%20newVal:%20%7B%5C%22data%5C%22:%5B%7B%5C%22firstName%5C%22:%5C%22Cox%5C%22,%5C%22lastName%5C%22:%5C%22Carney%5C%22,%5C%22company%5C%22:%5C%22Enormo%5C%22,%5C%22employed%5C%22:true%7D,%7B%5C%22firstName%5C%22:%5C%22Lorraine%5C%22,%5C%22lastName%5C%22:%5C%22Wise%5C%22,%5C%22company%5C%22:%5C%22Comveyer%5C%22,%5C%22employed%5C%22:false%7D,%7B%5C%22firstName%5C%22:%5C%22Nancy%5C%22,%5C%22lastName%5C%22:%5C%22Waters%5C%22,%5C%22company%5C%22:%5C%22Fuelton%5C%22,%5C%22employed%5C%22:false%7D%5D%7D;%20oldVal:%20%7B%5C%22data%5C%22:%5B%7B%5C%22firstName%5C%22:%5C%22Cox%5C%22,%5C%22lastName%5C%22:%5C%22Carney%5C%22,%5C%22company%5C%22:%5C%22Enormo%5C%22,%5C%22employed%5C%22:true%7D,%7B%5C%22firstName%5C%22:%5C%22Lorraine%5C%22,%5C%22lastName%5C%22:%5C%22Wise%5C%22,%5C%22company%5C%22:%5C%22Comveyer%5C%22,%5C%22employed%5C%22:false%7D,%7B%5C%22firstName%5C%22:%5C%22Nancy%5C%22,%5C%22lastName%5C%22:%5C%22Waters%5C%22,%5C%22company%5C%22:%5C%22Fuelton%5C%22,%5C%22employed%5C%22:false%7D%5D%7D%22%5D,%5B%22fn:%20function%20()%7Bvar%20a%3Dl(e);a!%3D%3DJ%5Bc%5D%26%26(a!%3D%3Dm%3Fm%3DJ%5Bc%5D%3Da:n(e,a%3Dm%3DJ%5Bc%5D));return%20a%7D;%20newVal:%20%7B%5C%22data%5C%22:%5B%7B%5C%22firstName%5C%22:%5C%22Cox%5C%22,%5C%22lastName%5C%22:%5C%22Carney%5C%22,%5C%22company%5C%22:%5C%22Enormo%5C%22,%5C%22employed%5C%22:true%7D,%7B%5C%22firstName%5C%22:%5C%22Lorraine%5C%22,%5C%22lastName%5C%22:%5C%22Wise%5C%22,%5C%22company%5C%22:%5C%22Comveyer%5C%22,%5C%22employed%5C%22:false%7D,%7B%5C%22firstName%5C%22:%5C%22Nancy%5C%22,%5C%22lastName%5C%22:%5C%22Waters%5C%22,%5C%22company%5C%22:%5C%22Fuelton%5C%22,%5C%22employed%5C%22:false%7D%5D%7D;%20oldVal:%20%7B%5C%22data%5C%22:%5B%7B%5C%22firstName%5C%22:%5C%22Cox%5C%22,%5C%22lastName%5C%22:%5C%22Carney%5C%22,%5C%22company%5C%22:%5C%22Enormo%5C%22,%5C%22employed%5C%22:true%7D,%7B%5C%22firstName%5C%22:%5C%22Lorraine%5C%22,%5C%22lastName%5C%22:%5C%22Wise%5C%22,%5C%22company%5C%22:%5C%22Comveyer%5C%22,%5C%22employed%5C%22:false%7D,%7B%5C%22firstName%5C%22:%5C%22Nancy%5C%22,%5C%22lastName%5C%22:%5C%22Waters%5C%22,%5C%22company%5C%22:%5C%22Fuelton%5C%22,%5C%22employed%5C%22:false%7D%5D%7D%22%5D%5D)

Thanks.

**Comment by ByKraB** [comment]
I tried to use trick for grid in modal ( http://ui-grid.info/docs/#/tutorial/110_grid_in_modal), but I still get Infinite loop errors while scroll table.

**Comment by PaulL1** [comment]
I'd suggest starting at 101 (or one of the slightly more complex tutorials), and then clicking 'edit in plunkr'.  Add your logic there, and see if you still get the problem.  If not, then work out what's different between the plunker and your real code.  If you do, then you could post the plunker here for us to look at.

What angular does with the binding/digest loop stuff is that it just iterates over all your bindings re-evaluating them until they become stable.  As a general rule, an infinite digest will occur when you have some data that angular thinks changes every time it runs the digest loop.  When it's happened to me before the usual cause is that I've modified some of my data in a way that means it changes every time it is evaluated, by for example creating a new object in a function, rather than returning a pointer to an existing object if it's already correct.  I see that your data has a function buried within each row, so that's probably the most likely cause.

**Comment by PaulL1** [comment]
Possible solution offered, no response for some time, assuming raiser has resolved their issue and closing.
