### ISSUE TITLE
getExternalScopes missing

### ISSUE THREAD

**Issue by smithscripts** [angular-ui/ng-grid#2613]
getExternalScopes is missing from the latest unstable build.

**Comment by c0bra** [comment]
It's been refactored: https://github.com/angular-ui/ng-grid/commit/7f336d4907d5f85c82d33538cfed160e3b3f5df8

**Comment by smithscripts** [comment]
That worked. Thanks!

**Comment by btelintelo** [comment]
The stable tutorial is broken now.

**Comment by swalters** [comment]
You must use the unstable version of the grid on the tutorial.  AFAIK, there is no way to have a tutorial work for both stable and unstable when unstable has a breaking change.
