### ISSUE TITLE
Grid focus

### ISSUE THREAD

**Issue by smithscripts** [angular-ui/ng-grid#2619]
When clicking on a Cell, Row or Column Header.  Is there an overall way to get if the grids has focus?

**Comment by PaulL1** [comment]
There's not a grid-specific way to check if the grid has focus that I'm aware of, although someone else may have seen a way.  But I presume there's a native javascript way to work out what element has focus, and then determine if the grid is a parent of that element.

**Comment by smithscripts** [comment]
I used a directive + some native javascript as you suggested and it worked well. Is this something you guys would consider including if I submitted a pull request?

**Comment by PaulL1** [comment]
Yes, that would probably be useful.  I'm thinking as an addition to the cellNav feature, rather than in core.  Not sure why, other than we're trying to avoid bloat in the core.

**Comment by c0bra** [comment]
@PaulL1 So do we want to rename this issue or close it and open a new one for this feature?

**Comment by PaulL1** [comment]
It's been three weeks, and @smithscripts can submit the PR without needing this issue open.  Closing.
