### ISSUE TITLE
column moving plugin doesn't work properly with the selection plugin

### ISSUE THREAD

**Issue by talavivi03** [angular-ui/ng-grid#2632]
Hi,

I have ui-grid with column moving and selection plugins.
I noticed that the column moving plugin doesn't work properly with the selection plugin.
When I disabled the selection plugin, column moving plugin back to normal behavior.
Is this a known issue? What should I do if I want to work with them both?

Best,

**Comment by PaulL1** [comment]
I don't think this is known, @jpuri, do you know?

**Comment by jpuri** [comment]
Hi @PaulL1 ,

I do not know of this issue, I will check this out.

**Comment by jpuri** [comment]
Hi @talavivi03,
I checked column moving with row selection plugin and it looks fin to me. If you are still facing the issue, can you please share a plunkr for it.

**Comment by talavivi03** [comment]
I didn't managed to reproduce this issue with plunkr, I'm not sure why.
Moreover I noticed that I have a lot of exceptions in my console log:
    TypeError: Cannot read property 'colDef' of undefined
    at service.redrawColumnAtPosition.findPositionForRenderIndex (ui-grid.js:14769)
    at Object.service.redrawColumnAtPosition (ui-grid.js:14777)
    at ui-grid.js:15005
    at angular.js:13170
    at l.$get.l.$eval (angular.js:14383)
    at l.$get.l.$digest (angular.js:14199)
    at l.$get.l.$apply (angular.js:14488)
    at uiGridMenu.link.applyHideMenu (ui-grid.js:1796)
    at l.$get.l.$broadcast (angular.js:14702)
    at self.fireScrollingEvent.gridUtil.throttle.trailing (ui-grid.js:2959)
Maybe this message related to the issue?

**Comment by jpuri** [comment]
Hi @talavivi03 ,

I am also not able to replicate the issue, tell me one thing does your grid has a huge scroll ?

**Comment by PaulL1** [comment]
The function `findPositionForRenderIndex` is:
```
      var findPositionForRenderIndex = function (index) {
                  var position = index;
                  for (var i = 0; i <= position; i++) {
                    if (angular.isDefined(columns[i]) && ((angular.isDefined(columns[i].colDef.visible) && columns[i].colDef.visible === false) || columns[i].isRowHeader === true)) {
                      position++;
                    }
                  }
                  return position;
                };
```

The error is `cannot read property colDef of undefined`.  The code has a specific `isDefined` check before it tries to use the colDef.  So it makes little sense that you could get that error.

First question: what version are you using, and does the `findPositionForRenderIndex` in your code base look the same as the above?  If not, then perhaps an upgrade is in order.  If so, then I'd be putting a breakpoint in that function and having a look to see which variable it is that is undefined, and then we can probably track back why it is.  It's possible that it's attempting to get at the colDef of the selection column, but I think we changed it a while back to have a colDef.

**Comment by jpuri** [comment]
The error will not occur for selection column even, from error it looks like columns[i] itself is undefined. Also I do not think an upgrade is in order since this file (http://ui-grid.info/release/ui-grid-unstable.js) has same function as above.

A possibility is that @talavivi03 has some older version.

**Comment by PaulL1** [comment]
Good points @jpuri.  Following that logic path:

1. columns = grid.columns.  Let's assume that is defined
2. a possibility is that columns[i] doesn't exist though, if we're attempting to access beyond the end of the array
3. the for loop doesn't go to columns.length, it codes to position (which is equal to index)

So, this error could occur if we're attempting to findPositionForRenderIndex with an index that is beyond the end of the columns array.

Looking at the code, what it is trying to do is find the position in the visible columns of a given column.  It doesn't appear to have much logic that deals with render containers.  Perhaps a better way to do this would be to instead to use the grid.renderContainers.body.visibleColumnCache?  That already excludes any invisible columns, and it is aware of render containers?  

Alternatively, we could implement a check such that:
```
if ( i >= columns.length ) {
  console.log('You have attempted to move a column that is beyond the end of the columns array');
  return;
}
```

**Comment by jpuri** [comment]
Hi @PaulL1 ,

Thanks for bringing up that mistake from docs, its type I will correct it.

I would not prefer to use visibleColumnCache, for moving the column I take into consideration all the columns and not just visible columns. This is required to make sure that hidden columns do not create an issue. But yes the if condition you mentioned above is definitely something that should be there. Let me added this and submit a PR.

**Comment by PaulL1** [comment]
Actually, I tried it on 401, but scrolling is also in the way.  I also forgot to mention that moving columns seems to not work at all once you scroll - so if you scroll 401 to the right a bit, then try moving columns it seems to just do nothing.

**Comment by PaulL1** [comment]
Sounds good.  How does column moving work with render containers - if I pin left then drag the columns around I think it will break if you don't use visibleColumnCache - because the renderIndex will be the index within a particular render container, and there might be a column that is within visibleColumns but has been pinned left.

Consider if I have 5 columns:
0 -> Name
1 -> Gender
2 -> Company
3 -> Address
4 -> E-mail

If I only have one renderContainer, then I can drag column 1 (gender) to position 3. When I look through the columns, the column at position 3 is going to be Address.

If I now pin column 2 (company) to the left render container, it will still stay in the same position in columns.  So my renderContainer has:
0 -> Name
1 -> Gender
2 -> Address
3 -> E-mail

but my columns has:
0 -> Name
1 -> Gender
2 -> Company
3 -> Address
4 -> E-mail

So when I drag my columns around, surely they'll end up in the wrong place?  Plunker's all broken for me at the moment or else I'd just try it and tell you.  :-)

**Comment by jpuri** [comment]
Plunkers are actually all broken, even I tried that.

I actually do not use renderIndex, I use index of column in the list of all columns of grid. Let me also try how move column works with pinning.

**Comment by jpuri** [comment]
Hey @PaulL1 ,

This PR #2490 has fix for move column issue when grid has scroll.

**Comment by jpuri** [comment]
I checked for the pinning. In case of pinning, all columns except the pinned columns can be moved correctly.

Pinned columns does not moves. Small bug I see is that dark moving column header appears for pinned column for few seconds (although its not moved). I can probably create a separate issue and fix this.

**Comment by PaulL1** [comment]
OK, looks like we can close this one.
