### ISSUE TITLE
Grid doesn't respect height of enclosing div

### ISSUE THREAD

**Issue by steverA** [angular-ui/ng-grid#2633]
http://plnkr.co/edit/LODMLRbGBU0buOLM2KYV?p=preview
The plunkr shows a grid enclosed in a div with width/height styles but without access to a .grid style in a css file. This is a simple modification to the tutorial 101 sample.

`<div ng-controller="MainCtrl">`
 ` <div style="width:400px; height:150px">`
`  <div id="grid1" ui-grid="{ data: myData }" class="grid"></div>`
`  </div>`
`</div>`

The width can be changed and the grid size changes but not the height - seems stuck at about 352 px in this case. Is there a minimum height that needs to be overridden?  This is 30.rc18 of 1/21
True in both IE11 and Chrome.

**Comment by PaulL1** [comment]
It's not clear to me whether we expect the grid to respect a height that's given in that way. I can't see why we wouldn't, but I also can't see why the grid would even know that the height was given in that way instead of via a css, and css really isn't my thing.  Is there a reason you can't just give a height on a css style as per normal?

**Comment by steverA** [comment]
Paul: We have hundred of pages written by different people and their layout tool allows them to define the height of their grid at whatever makes them happy. I don't see how we could fill up a styles with all kinds of individual styles for each grid height. The only other thing I can think of is maybe to set the height on the grid directly in a directive. Is that reasonable?

**Comment by PaulL1** [comment]
Is it possible to set the height/width on the grid div directly, rather than on the enclosing div?

**Comment by steverA** [comment]
It appears that if I add to the grid div style="width:100%; height:100%" that is enough to size the grid directly - that leaves the outer grid to set sizes!  You can try that by adding this to the plunkr above.  Seems like a reasonable workaround.

**Comment by steverA** [comment]
I will add that it doesn't seem to help the column header on a tabbed page..

**Comment by c0bra** [comment]
Divs by default fill 100% of their container's width, but height friends on content, and since the grid's content is virtual there's no way for it to guess the height. Setting height to 100% of the right thing to do.

There's a page on this on the tutorials named "A Hidden Grid Manifesto".

**Comment by c0bra** [comment]
Closing as the original issue seems resolved.
