### ISSUE TITLE
Select all rows after paging

### ISSUE THREAD

**Issue by talavivi03** [angular-ui/ng-grid#2634]
Hi,
Is it possible to select all rows, and to keep the selection while paging changes.
I mean, I want to select all rows and until the box of the 'select all' is checked I want all my rows to be highlight(to be selected). 
I tried to following code and it's not working:
                        scope.gridApi.selection.setMultiSelect(true);
                        scope.gridApi.grid.selection.selectAll = true;
                        scope.gridApi.selection.selectAllVisibleRows();
I also tried to select each row in the paging manually by using toggleRowSelection and it's not working either.
Is there any idea how should I do this?

Looking forward to you answer,
Best!

**Comment by novice3030** [comment]
I don't see why it shouldn't be possible. just keep the selected rows in your scope and reselect them on paging events
You can use the gridApi.selection.on.rowSelectionChanged to keep track of the selected rows (you can save the UID/index)
And then when you have a paging event just reset the selected rows using row.isSelected = true for each row you have in the array.

Hope that helps

**Comment by talavivi03** [comment]
Unfortunately. it still not working. 
I tried to debug it and I saw that the event rowSelectionChanged  is never occurs.
Any ideas?

**Comment by talavivi03** [comment]
I noticed that the selectAllVisibleRows event occurs before the new data loaded so I added a timeout and it solved the issue.
Thanks.
