### ISSUE TITLE
[3.0][Scroll] table column are not under header column, when I use horizontal scrollbar

### ISSUE THREAD

**Issue by MariMax** [angular-ui/ng-grid#2636]
[example](http://plnkr.co/edit/tPER4Qwckk9AwO3sqBG3?p=preview), [screenshoot](https://yadi.sk/i/trLlxVyeeEzzK)

**Comment by c0bra** [comment]
Thanks for the report but this appears to be a duplicate of #2592; closing.

**Comment by kenaths** [comment]
Set enableVerticalScrollbar to true, It'll fix the issue.

        $scope.gridOptions = {
            enableVerticalScrollbar: 1,
            ..............
        }
