### ISSUE TITLE
Dynamic Row Height

### ISSUE THREAD

**Issue by mikehuebner** [angular-ui/ng-grid#2641]
Is there a way to do dynamic row heights for different sets of data.

This is what it does currently if data goes over the max row height
![image](https://cloud.githubusercontent.com/assets/6125123/5910868/cd3c11fe-a573-11e4-91ff-2f17a9b036a8.png)

And here is what it does when you set the row height to 100%
![image](https://cloud.githubusercontent.com/assets/6125123/5910876/e510f4c0-a573-11e4-8109-1b86ac1ecb7a.png)

So you lose that fill and it won't center the text vertically. Is there a CSS trick I could try, I've tried a few but maybe I'm missing something. (This is with the default CSS running as well)

**Comment by PaulL1** [comment]
The grid doesn't do dynamic row heights, and isn't likely to in the near future.  It substantially complicates scrolling.

**Comment by PaulL1** [comment]
Closing, the grid isn't likely to support this in the near future.
