### ISSUE TITLE
regression setSavePromise - parameter mismatch.

### ISSUE THREAD

**Issue by aschyiel** [angular-ui/ng-grid#2642]
v3.0.0-RC.18-d5229e6 - 2015-01-26

                 saveRow: function (rowEntity) {
@@ -17520,9 +17520,9 @@ module.filter('px', function() {
                  * been initiated
                  * @param {promise} savePromise the promise that will be resolved when the
                  * save is successful, or rejected if the save fails
                  */
-                setSavePromise: function ( rowEntity, savePromise) {
+                setSavePromise: function (grid, rowEntity, savePromise) {
                   service.setSavePromise(grid, rowEntity, savePromise);
                 },

**Comment by PaulL1** [comment]
I updated the publicApi last week to not take the grid.  But I doubt that's made it into the RC yet, so you need to either build from source or provide the grid as first parameter.

**Comment by aschyiel** [comment]
mb
