### ISSUE TITLE
Breaking Changes

### ISSUE THREAD

**Issue by Dev63** [angular-ui/ng-grid#2643]
Is there someplace I can watch that lists breaking changes?  For example, the moves from getExternalScopes() to grid.appscope, or showFooter to showColumnFooter, etc.?

**Comment by PaulL1** [comment]
https://github.com/angular-ui/ng-grid/blob/master/CHANGELOG.md should list them, so long as those making the changes explicitly put `BREAKING` in the commit.  I think all the ones you mention would appear there when an RC is next built.

If you're building from source, then you'd need to look at the commits, but my driving of github isn't quite up to filtering the commit log by breaking changes.

**Comment by Dev63** [comment]
OK, thanks.  I'm just test driving the unstable build, and a number of things aren't working for me, due to these kinds of changes.  I was wondering if there was a published list that grows with each such breaking commit, but that's fine.
