### ISSUE TITLE
Missing  Header Column Dividers (commented out)

### ISSUE THREAD

**Issue by Dev63** [angular-ui/ng-grid#2644]
In the unstable build, I no longer see header column dividers in my tables, and in looking at the constructed DOM, I see that they are commented out.  Is this on purpose?  Is there some setting I need to make to have them reappear?  The demos still look fine...

    <div ng-class="{ 'sortable': sortable }" class="ng-scope sortable">

**Comment by PaulL1** [comment]
@c0bra: was this part of the changes you did to borders - and is it intentional?

**Comment by PaulL1** [comment]
I still don't have these, but visually I do have borders.  I presume we've moved away from dividers and now use borders.  I think this is intentional.

**Comment by Dev63** [comment]
@PaulL1 I haven't retested the latest unstable build, but the point I was making was that although the tutorial demos purport to be using the latest unstable build, and DO show dividers, my use of the latest unstable build did not ... and in examining the constructed HTML, it had the border HTML stuff commented out (in the constructed page!).  This doesn't seem right.  The commented-out HTML seems problematic and wasteful, and I personally think the dividing lines are necessary (think about column resizing!).

**Comment by PaulL1** [comment]
Resize works fine without them.

The tutorial builds do use the latest unstable build, although there is a lag between a merge happening and the site updating which may explain any difference you saw.

**Comment by Dev63** [comment]
@PaulL1 My initial comment was from 2 months ago ... what tutorial demos show no dividers in the header?  I would have thought my experience was a temporary aberration (and I haven't retested), but you seem to say you don't see dividers either?

**Comment by PaulL1** [comment]
They all have dividers visually, they all also have the same commented out html you mentioned.
