### ISSUE TITLE
How to improve performance of large datasets with pagination.

### ISSUE THREAD

**Issue by poeticninja** [angular-ui/ng-grid#2647]
First of all.... Thanks for this awesome library! :smile: 

I am working with a large dataset of 100k+ items and the scrolling is really choppy. I changed my dataset to 10k and it still is not that smooth. I started looking into ways to improve the performance. After looking at different options the easiest method would be to use pagination. Because with pagination set to 1k per page it should only use the virtualization process on the 1k items. It seems to still be just as slow as if it was the virtualization on the 10k items.

It looks like the virtualization process with pagination is on the full data set. It should only be on the items shown that page.

**Comment by PaulL1** [comment]
I'd be focusing more on the large dataset scrolling properly.  That should work irrespective of pagination.  I did some work on filtering with a large data set (130K rows), and the scrolling seemed to be working fine (#2574).  Could you provide a bit more detail on what about it was not working well for you?

**Comment by poeticninja** [comment]
Thanks @PaulL1, the issue is the lag when scrolling. When I have 100-2000 items the scrolling seems to be normal. It scrolls like you would be scrolling on a website. There is flickering but no lag at that point.

Once I load 10k or more items the scrolling is not smooth and its lagg/choppyy. At 100k it just seems to jump around when scrolling, not smooth, and not natural. The scrolling is no longer functional from a user experience standpoint.

I am using the latest unstable version (18).

**Comment by PaulL1** [comment]
Vertical scrolling or horizontal?  Have you tried the latest unstable - there were some changes that went in that might address some scrolling issues.

**Comment by poeticninja** [comment]
I am using rc 18. Not sure if that is the latest. I will try and see if there is newer. My grid uses vertical and horizontal scrolling. Because I can. :) I can test out what it would be like with out the horizontal just to see if that changes improves anything.

**Comment by PaulL1** [comment]
rc18 is actually getting a bit old, we're due to cut a new RC, but waiting on a few defects.  Building from unstable might make sense - you can probably just copy the versions that the tutorials are using (http://ui-grid.info/release/ui-grid-unstable.js, http://ui-grid.info/release/ui-grid-unstable.css)

**Comment by poeticninja** [comment]
I just tested out the newest ui-grid from the links you gave. The scrolling on the 1k items I can tell have improved with less flickering! That is great!

I am still having issues with 10k though. I removed horizontal scrolling and removed pagination and the only thing left is the grid and the data. As I add more items it still slows down more and more.

Here is an animated gif of 1k items. You can see it is very responsive and fast.
![gif of 1k items](https://cldup.com/QYywbZfusE.gif)

And here is an animated gif of 10k items. Really choppy. 
![gif of 10k items](https://cldup.com/O9GkaILAYU.gif)

My first time doing images on github so I hope they turn out okay. They are a couple mb's each so wait for them to fully load to see the scrolling

**Comment by PaulL1** [comment]
What browser and OS combination do you have?  For me, when I visit the large dataset tutorial (http://ui-grid.info/docs/#/tutorial/190_large_dataset) the scrolling is very smooth.  It is also smooth for me on the horizontal scrolling tutorial (http://ui-grid.info/docs/#/tutorial/191_horizontal_scrolling).  Finally, on the plunker for the 320K rows above (http://plnkr.co/edit/Mp7I2yMQADMTPAETL0KD?p=preview), I find that to also be smooth.  

Are those also good for you (indicating it's perhaps something with your specific grid configuration), or are you having issues with those samples as well?

**Comment by poeticninja** [comment]
Wow, those are fast with lots of data! ........   I am going to start a blank project and see if I can recreate a fast version with lots of data. From there I will start adding things and see what is causing the issue.

**Comment by poeticninja** [comment]
I fixed it.

I changed this line:
```
<div class="grid" ui-grid="{gridOptions.paginationPageSizes: [100, 250, 500], gridOptions.paginationPageSize: 100, data: gridOptions.data, columnDefs: gridOptions.columnDefs}" style="height: 500px;"></div>
```

To:
```
<div class="grid" ui-grid="gridOptions" style="height: 500px;"></div>
```

The only difference is passing in the object of grid options directly. :smile:

**Comment by poeticninja** [comment]
I updated my comment above with proper syntax. It has been a long day. ;)

**Comment by c0bra** [comment]
I guess there was some sort of extra $digest processing going on.

**Comment by c0bra** [comment]
Closing as the issue appears to be fixed. Though we may want to append this to a FAQ.
