### ISSUE TITLE
Last column can't be edited if parent width is a percentage

### ISSUE THREAD

**Issue by axelstudios** [angular-ui/ng-grid#2649]
http://plnkr.co/edit/wKVrbMx663uBe6OxZzNy?p=preview

If I try to show an editable grid in a div where the parent width is a percentage less than 100% (like a Bootstrap column < col-md-12), cells in the last column aren't editable:

Workarounds:
- Scroll the horizontal scrollbar to the right before clicking the cell (not ideal)
- Set an explicit `px` width on the grid (not ideal for fluid layouts)
- Add the ui-grid-selection directive to the grid.  For some reason, if the row header is there this works fine (close enough, even though I don't want the user to select anything)

Details:
If you don't have the row header, this particular `fireScrollingEvent` is raised because it decided that the x scroll change was 1%: https://github.com/angular-ui/ui-grid.info/blob/4496502fefce8110ff329f7a8e34033f7fade1ea/release/ui-grid-unstable.js#L11799

#### Edit
I think there are two bugs here:
1. `grid.gridWidth` can be a float when the parent is percentage based, and [this line](https://github.com/angular-ui/ui-grid.info/blob/4496502fefce8110ff329f7a8e34033f7fade1ea/release/ui-grid-unstable.js#L11695) should really be using `Math.ceil(grid.gridWidth)` instead.  Implementing that fixes this issue.
2. Row header width isn't taken into account inside of the `scrollToIfNecessary` function.

**Comment by PaulL1** [comment]
I've added the first line as you suggest, thanks for that fix.

On row header width, I think that it maybe isn't taken into account because it's not in the body render container, and the scroll only applies to the body, not the left (or right) pinned container.  Does that make sense?
