### ISSUE TITLE
Grid (in unstable release) breaks when updating gridOptions

### ISSUE THREAD

**Issue by choketsu** [angular-ui/ng-grid#2650]
Please see http://plnkr.co/edit/eQeIJ5VZkV83dHU6FvLy?p=preview

When you click on "Click me", the grid becomes distorted.

**Comment by PaulL1** [comment]
The most likely problem is that you're overwriting both gridOptions and the columnDefs.  You shouldn't just replace them with a brand new object, as the grid is holding a pointer to them.  In general it breaks things to do so (that's general javascript practice, not just a grid thing).

Having said that, plunker is severely broken for me today - even before clicking your button the format was way off, and it's doing it from all the tutorials too. So it's a bit hard to provide an alternative example that is working.

**Comment by choketsu** [comment]
Yes you're right - I'll close the issue. Thanks.
