### ISSUE TITLE
Pagination and Expandable together when 100% cause weird styling

### ISSUE THREAD

**Issue by jrgleason** [angular-ui/ng-grid#2654]
I have an example here...

http://plnkr.co/edit/Mcu1bmxRIAfBtFkMMGi3?p=preview

basically I have pagination and expanding and when I scroll all the way down if I open and close the bottom it leaves white space until I scroll or some other movement.

**Comment by jpuri** [comment]
The problem is not with Expandable or Pagination, but its a rather known bug that scrolling at times gives this weird behavior with expandable grids. Check #2488.

**Comment by PaulL1** [comment]
This appears resolved - could you confirm?

**Comment by PaulL1** [comment]
Looks fixed, no further comment after 2 weeks, closing.
