### ISSUE TITLE
Is it possible to disable the selection of Row in UI-grid?

### ISSUE THREAD

**Issue by doshimehul** [angular-ui/ng-grid#2665]
Please let me know if its possible to disable the selection of Row in UI-grid on certain conditions.

Within ng-grid, I was using 

gridOptions['checkboxCellTemplate'] 

to hide the checkboxes , something similar is possible in UI-grid?

Thanks for the amazing work you guys are doing!

**Comment by PaulL1** [comment]
There was a similar issue raised, the answer is that we can't do it currently, although I'd like to add it.  But you can get a similar effect by using a cellTemplate to mark the row as not being editable (for example, making the text grey), and hook onto the row selection event to unselect the row again whenever anyone selects it.  Not quite the same thing, but it works.  Refer #2482

**Comment by doshimehul** [comment]
Hi Paul,

Thanks for prompt reply. 

In stead of cellTemplate I am using rowTemplate.

///////////////////

function rowTemplate() {
            return $timeout(function() {
                return '<div ng-class="{strike: getExternalScopes().checkStatus(row)}"  ng-repeat="col in colContainer.renderedColumns track by col.colDef.name" class="ui-grid-cell" ui-grid-cell></div>';
            }, 1000);
        }
///////////////////

$scope.gridOptions['rowTemplate'] = rowTemplate();

//////////////////////////

.strike {
    background-color: lightgrey !important;
}

Let me know your thoughts on the same.

**Comment by PaulL1** [comment]
Yes, that should also work.

**Comment by PaulL1** [comment]
There is now a enableRowSelection property on each row that grouping uses to disable rowSelection.  Closing.
