### ISSUE TITLE
Is it possible to change the visibility of the column conditionally

### ISSUE THREAD

**Issue by gnehapk** [angular-ui/ng-grid#2668]
I want one of the column of my grid to be invisible at the load of the page. But after some condition that column should be visible. So while defining the columns for my grid I am setting the visible property of the grid to false. But when it matches some condition I am changing the visible property to true. But still that column is not visible in that grid.

**Comment by PaulL1** [comment]
Refer to the associated tutorial: http://ui-grid.info/docs/#/tutorial/113_adding_and_removing_columns

**Comment by gnehapk** [comment]
Solved. Thanks :+1:

**Comment by shaikh23wahid** [comment]
instead of column index, can we hide column using column(field) name?

**Comment by rafiquemshaikh** [comment]
Hi Paul,

I wanted to hide columns dynamically, here we have option to hide column using `$scope.gridOptions.columnDefs[0].visible = true`. its working, but the problem is we are loosing the column index. if i hide column [0], then column 1 is becoming [0]. can you please help me on this?
