### ISSUE TITLE
[3.0.0-rc.18] - Select All checkbox is intially missing whenever filtering is enabled

### ISSUE THREAD

**Issue by pmariduena** [angular-ui/ng-grid#2669]
Easy to reproduce. 

Whenever I initially load the page, the "Select All" checkbox is missing, so the other row selection checkboxes appear out of line with the row they control (they are above the row the control). 

However, if I Restore-down, then maximize the window, or, if I simply scroll the grid, the "Select all" checkbox magically re-appears, and all the row selection checkboxes are suddenly lined up properly.

Create a ui-grid like the following in your html partial:

```
<!-- the spinner I added here is irrelevant to the issue, so is the ng-class that allows the spinner to appear or disappear -->
<div ng-class="{true: 'loading', false: 'empty'}[dataLoading]" class="gridStyle {min-height: 300px}" ui-grid="gridOptions" ui-grid-edit ui-grid-resize-columns ui-grid-row-edit ui-grid-cellnav ui-grid-selection>
    <span us-spinner="{radius:6, width:2, length: 5}" spinner-key="spinner-configuration"/>
</div>
```
In your controller, define following gridOptions:
```
...
            $scope.gridOptions = {
                columnDefs: [
                    {field: 'name', displayName: 'Name*', enableCellEdit: true},
...
                    {field: 'updatedAt', displayName: 'Updated At', type: 'date', enableCellEdit: false, cellFilter: 'jsonDateTime | date:"yyyy/MM/dd HH:mm:ss"'}
                ],
                data: "myData.data.posts",  // just the way I send data back to the client
                enableFiltering: true,
                enableGridMenu: true,
                minRowsToShow: 25,
                rowHeight: 20,
                rowEditWaitInterval: -1,
                showFooterRow: false
            };
```

**Comment by pmariduena** [comment]
Before:
![before](https://cloud.githubusercontent.com/assets/9665570/5960610/b9507f6c-a7a4-11e4-8573-782569b19f24.jpg)

After:
![after](https://cloud.githubusercontent.com/assets/9665570/5960611/bebe5d8e-a7a4-11e4-9e1c-eb8d9138d869.jpg)

**Comment by PaulL1** [comment]
Could you try with the latest unstable?  I'm not seeing this happening on the tutorials, so if you can recreate on unstable, then could we have a plunker?

**Comment by pmariduena** [comment]
I'll try with a plunker. I wonder if it has to do with all the divs in my application? The way I have it, I have a main html page, and that loads several "partials". This is done to keep a consistent look-and-feel (the tab bar you see at the top) across the entire application.

**Comment by PaulL1** [comment]
Try the unstable first I'd say.  If that fixes it, then upgrade to the unstable.  If not, then yes it would seem you have some sort of timing issue, a few divs shouldn't cause that though.

**Comment by pmariduena** [comment]
See this plunkr (modified by me): http://plnkr.co/edit/liRYMcAnh2RjddRWPlGB

I was sort of able to reproduce it with "unstable". You need to stop the plunkr and restart it to see it. In this plunkr on the browser I mention above, I see the entire data portion of the grid detached from the column of select row checkboxes and the column headers.

I was able to do this by taking the div tag for the ui-grid, and wrapping it around multiple layers of divs (which is how my real-life needs to be).

![brokengrid](https://cloud.githubusercontent.com/assets/9665570/6004935/89ef792a-aad4-11e4-8b03-49c166b36d41.jpg)


Though slightly different from what I reported, it's probably the same root cause.

**Comment by pmariduena** [comment]
Did not save it properly :/ just one sec.

**Comment by pmariduena** [comment]
Ok, try this plunkr: http://plnkr.co/edit/94S2GsxDaAq1zNQQgMDT

**Comment by pmariduena** [comment]
I tried rc18-0fa8c48 level. I don't seem to have the issue anymore, but let me keep testing, especially on IE10 (haven't tested there yet). I'm thinking #2542 may have fixed this.

**Comment by c0bra** [comment]
It's been 18 days; I'm going to go ahead and close this.

@pmariduena if you're still having a problem please paste your original issue text into a new one.
