### ISSUE TITLE
Cannot scroll subgrid with mousewheel without scrolling parent grid

### ISSUE THREAD

**Issue by c0bra** [angular-ui/ng-grid#2672]
If you attempt to scroll in a sub-grid with the mouse wheel it will also (improperly) scroll the parent grid.

You can see the behavior in this plunker: http://plnkr.co/edit/YGlX5XltCzMgZ1fOAO33?p=preview

**Comment by PaulL1** [comment]
I'm downgrading this from hi-pri on the basis that I think we're going to release ui-grid with expandable still being beta.  There are a lot of issues still outstanding in expandable and I think we want to focus on getting the core stable first.

**Comment by jpuri** [comment]
This looks like duplicate of #2162.

**Comment by c0bra** [comment]
@jpuri doh, you're right. Closing as a dupe.
