### ISSUE TITLE
Performance issue getWidthOrHeight  

### ISSUE THREAD

**Issue by smithscripts** [angular-ui/ng-grid#2675]
line: 8725 getWidthOrHeight  is continually being called after grid render.

**Comment by PaulL1** [comment]
Is that perhaps because you've given a variable height or set it to an auto height?  Have you given the grid both a height and a width in the css?

**Comment by smithscripts** [comment]
Yes, both height and width. I verified that this is also happening in the auto-size tutorial page also.

**Comment by axelstudios** [comment]
I've seen this also with ui-grid-auto-resize, but only when the grid is not visible.  Here's an example with 6 grids in an accordion, and the more accordions that are collapsed, the higher the processor usage will be with memory usage climbing.  `getWidthOrHeight` makes up more than 50% of the calls

http://plnkr.co/edit/osposWKkUNmSEGcKWY9c?p=preview

**Comment by PaulL1** [comment]
Have you set auto-size?  If so, then that tutorial explicitly says that there is a performance impact associated with that.
