### ISSUE TITLE
Dropdown showing Id and not Label

### ISSUE THREAD

**Issue by sanjayjaras** [angular-ui/ng-grid#2676]
Hi, I am new to ui-grid, I tried to implement editable grid, however when focus is not the column it's show Id instead of label. Please tell me what I am doing wrong. Thanks in advance.
![screenshot from 2015-01-31 04 02 58](https://cloud.githubusercontent.com/assets/10779622/5984660/48497bec-a8fe-11e4-9c50-44995659bbd3.png)
![2](https://cloud.githubusercontent.com/assets/10779622/5984765/72eb09c8-a8ff-11e4-9cef-b7446f71fb18.png)

**Comment by PaulL1** [comment]
Check the tutorial more closely.  It looks to me like you're missing the cellFilter.

**Comment by sanjayjaras** [comment]
Yes Paul you right I am missing cellFilter. Thanks for reply. 
Is it possible to provide cellFilterProvider dynamically as follows?
displayController.filter('map' + property.name,
 function() {
	var genderHash = {															1 :'India',																		2 :'Pakistan'
};
return function(input) {
if (!input) {
return '';
} else {
return genderHash[input];
}
};
});

**Comment by sanjayjaras** [comment]
Got the solution by writing service method for the same. Thanks.
