### ISSUE TITLE
angular-UI / UIGrid

### ISSUE THREAD

**Issue by mail2gopinath** [angular-ui/ng-grid#2677]
The filtering is not getting enabled in the expandable UIGrid

**Comment by PaulL1** [comment]
Could you please provide a plunker and a clearer description of what your problem is, what version you're using, and what OS/Browser combination?

**Comment by mail2gopinath** [comment]
http://plnkr.co/edit/rizLNiRRAwOmRqliRW2g?p=preview , the plunked link.
 The version is 3.0 UI grid, the browser is IE 11 and trying to enable to filter in  the column definition of the parent and nested grid as well.

**Comment by PaulL1** [comment]
You need to enableFiltering on the gridOptions.  http://plnkr.co/edit/kRne2DrQTwXUklw4qf62?p=preview

Refer http://ui-grid.info/docs/#/tutorial/103_filtering

**Comment by mail2gopinath** [comment]
Thanks..
