### ISSUE TITLE
Scrolling in Safari browser on Windows

### ISSUE THREAD

**Issue by flex123** [angular-ui/ng-grid#2680]
Hello,

Has anyone experience the following issue with Safari?  After doing horizontal scrolling, the table turned black.

![image](https://cloud.githubusercontent.com/assets/10717743/5990020/3cb4994c-a96c-11e4-8cc6-aebde2e07be8.png)

**Comment by PaulL1** [comment]
No, it's not doing it for me at all (Safari on OSX).  Is it doing it repeatably for you, or was it a one-time thing?

**Comment by flex123** [comment]
I see.. I guess it's because I'm using safari on windows version (5.1.7).

**Comment by c0bra** [comment]
Man. I've tried using the profiler while horizontal scrolling in windows safari 5.1.7 and it crashes.

**Comment by mikila85** [comment]
not much :+1:

**Comment by c0bra** [comment]
I don't know if this is fixable but I'll leave open for little while to see if it gets any interest.  Without help from someone familiar with Safari 5 perf it's unlikely that we'll find a solution.

**Comment by c0bra** [comment]
I'm going to go ahead and close; if anyone has any updates please file a PR or open a new issue.

**Comment by mikila85** [comment]
Lol waste of time open bugs for you guys good luck.,
