### ISSUE TITLE
[3.0.0-rc.18] appScope and appScopeProvider not available.

### ISSUE THREAD

**Issue by jjstrat3** [angular-ui/ng-grid#2684]
After spending a couple hours trying to figure out why I couldn't make use of your documented feature of appScope and appScopeProvider, I started digging through the source and realized it isn't there.  Instead the external-scope directive and getExternalScopes() are still there.  Now we use Bower for our dependencies at my job so I pulled your latest *tagged* release down. Your latest tagged release was done on Dec. 9th.  The refactor to appScope was done on January 21st as seen [here](https://github.com/angular-ui/ng-grid/commit/7f336d4907d5f85c82d33538cfed160e3b3f5df8).  That's all fine, except in your docs you have a dropdown with 'unstable', or 'stable' and selecting either still shows the appScope property in Grid or appScopeProvider in GridOptions.  According to [this](https://github.com/angular-ui/ui-grid.info/tree/gh-pages/release) page, you seem to signify that v3.0.0-rc3 is your 'stable' release, and it obviously doesn't have the previously mentioned features as your docs suggested.  The 'unstable' seems to be v.3.0.0-RC18-f82f554, which is not tagged as a release(so not something I'm going to be able to pull in with Bower unless I'm willing to just accept any version or point to master).

Point being, it's a little frustrating to not be able to count on your documentation being accurate in order to utilize this module.  Might I suggest changing your docs from saying 'stable' or 'unstable' to the actual release the docs are for?  Pretty much like what the official angular docs do?

**Comment by c0bra** [comment]
3.0 has not be released yet, there is no stable. It says so in the readme: `Note: 3.0 is NOT ready for production. It is still in a pre-beta state.`

Sorry for the confusion with the -stable suffixed file names. Those were created as part of release-process testing and need to be removed.

We are working on clarifying the site and making sure the docs/tutorials line up with the current "release", whether stable or not, and not with the current commit in master, but it all depends on time availability.

**Comment by jjstrat3** [comment]
Understandable.  We all have only so much time in the day :).  Just hoping others will not fall into the same 'trap' that I did with using a property or feature that's documented but not on the version they are using. ;)

**Comment by c0bra** [comment]
I hear where you're coming from. We definitely hope to avoid this in the future and save you and others  time spent uselessly floundering in mismatched documentation!

**Comment by sivakarthikgade** [comment]
Thanks much jjstrat3 !!!
Stuck with this issue for quite some time.. Google should increase relevance of this page in search results 🎯
