### ISSUE TITLE
Cannot filter on non-visible columns

### ISSUE THREAD

**Issue by parliament718** [angular-ui/ng-grid#2687]
I'm having an issue with settings visible: false on one of my columnDefs.

I use external filters, however I really on filterChanged event

```
this.gridApi.core.on.filterChanged($scope, () => {
      this.queryGridData();
});
```

This event only triggers when I bind the "filter" property to a filter model:

```
      columnDefs: [
            { field: 'Gender', filter: this.gridFilters.gender },
       ]
```

This all works but I don't want the Gender column to be visible. However, if I set visible:false on that column, then it also ignores the filter property and filterChanged does not fire.

**Comment by jpuri** [comment]
Hi,

The reason I think is filtering is implemented inside the directive 'uiGridHeaderCell', and since it does not exists for invisible columns filtering can not be done for them.

Removing filtering into separate feature will be a bigger change. @PaulL1 what do you suggest.

**Comment by PaulL1** [comment]
I don't think this is accurate.  If I edit the filtering tutorial to make the gender column invisible you can still filter on it: http://plnkr.co/edit/uaM2dPtTxOKsSX5FRmsC?p=preview.

Of course, you can't enter filter conditions in via the UI, because without the column header there's no filter box.  But you can enter filter conditions through code/a custom UI - and if you want to filter on hidden columns then you obviously want a different UI than the one we have by default.

**Comment by jpuri** [comment]
But @PaulL1 check following code in ui-grid-header-cell.js. I do not think filtering event will be raised for invisible columns:

            if ($scope.filterable) {
              var filterDeregisters = [];
              angular.forEach($scope.col.filters, function(filter, i) {
                filterDeregisters.push($scope.$watch('col.filters[' + i + '].term', function(n, o) {
                  if (n !== o) {
                    uiGridCtrl.grid.api.core.raise.filterChanged();
                    uiGridCtrl.grid.refresh()
                      .then(function () {
                        if (uiGridCtrl.prevScrollArgs && uiGridCtrl.prevScrollArgs.y && uiGridCtrl.prevScrollArgs.y.percentage) {
                          var scrollEvent = new ScrollEvent(uiGridCtrl.grid,null,null,'uiGridHeaderCell.toggleMenu');
                          scrollEvent.y.percentage = uiGridCtrl.prevScrollArgs.y.percentage;
                          scrollEvent.fireScrollingEvent();
                        }
                      });
                  }
                }));  
              });
              $scope.$on('$destroy', function() {
                angular.forEach(filterDeregisters, function(filterDeregister) {
                  filterDeregister();
                });
              });
            }

**Comment by PaulL1** [comment]
Possibly not, but I also don't know how you'd change the filter on invisible columns - logically you can only do it from code, in which case you already know it changed, because you did it.

**Comment by parliament718** [comment]
@PaulL1 , I use 2-way binding to bind the filter object to an input's ng-model, therefore I don't modify is in code manually. When user types in the input, I expect filterChanged to fire (which it does for all but invisible columns).

**Comment by PaulL1** [comment]
The change event is fired from the filter box itself, it uses a watch.  If you implement a custom input, then you'll also need to handle firing the filterChanged event.

**Comment by c0bra** [comment]
@parliament718 I'm going to go ahead and close this as there's been no response for 2 weeks. If using `filterChanged` didn't work for you please open a new issue.

**Comment by parliament718** [comment]
this IS the issue regarding filterChanged not working. @PaulL1 suggests handling this myself so yes i CAN set an extra watch.. But it's not a real solution, but a hack; because it would be redundant for any non invisible column. I Imagine when if I had more columns and had them dynamically hide/show this would result in a lot of redundant code. IMO, ng-grid should handle invisible columns the same way as normal ones.

**Comment by PaulL1** [comment]
@parliament718 : the problem is that it can't.  The way it handles visible columns is that it has a watch on the input field itself, and triggers the event when the field changes.  We absolutely should do the same on invisible columns - but on invisible columns we don't have an input field.  Presumably you're building your own input field in order for users to be changing the filter, if we want to behave the same as the other columns that means you should put a watch in that input field.

**Comment by parliament718** [comment]
@PaulL1  Yes, but the user shouldnt be forced to use the inputs provided under the column header. In many cases, it's ideal to put the inputs outside the table entirely (as is in my case), in which case 2-way data-binding to the filter object is ideal, regardless how the user selects the filter term. For example I might a dropdown instead of a text input, so it shouldn't be coupled to the default text inputs provided in table header. Even from a design perspective, placing them in the column header is just ONE way to do it, but the user shouldn't be forced to do so at the expense of breaking filter functionality. 

Anyways I won't rant anymore. I have teh hack working in place for a while now and it doesn't matter anymore. But I don't think filtering should be tightly-coupled to the default template; not everyone wants the filters in the column header, so it should $watch on the filter object instead of on the inputs.

**Comment by pegiejot1** [comment]
Hi, I have similar problem, I'm not using external filters but that build in and I'm trying to update filter on hidden column from code. It works only on app start when I set filter for column:

```javascript
columnDefs: [
            { field: 'myColumn', filter: { term: 'blabla' } },
       ]
```

That works correctly, data is filtered, but when I'm trying to set that filter later, for example:

```javascript
columnDefs[0].filter.term = 'asd';
```

then grid is not refreshing, filters are not applied.

**Comment by r0m4n** [comment]
@bartekx If you perform a grid refresh when the term has changed, the filter updates even when the column isn't visible.

http://plnkr.co/edit/JAfT6CNy6nCt8X3I0ekb?p=preview
