### ISSUE TITLE
selectRow is not selecting a particaular row

### ISSUE THREAD

**Issue by gnehapk** [angular-ui/ng-grid#2688]
I want to select the ith row of my grid, so passing $scope.gridOptions.data[i] entity as a parameter to selectRow function. But still that row is not selected. Is there any other configuration requires to set for the grid in order to enable row selection?

**Comment by PaulL1** [comment]
You need to include the selection module, and you need to wait until after the grid has rendered before you call the function.

**Comment by gnehapk** [comment]
I have include the "ui-grid-selection" module.  Still its not working. Below is the code - 

//grid configurations
$scope.gridOptions = {
            enableHorizontalScrollbar: 2,
            enableVerticalScrollbar: 2,
            gridHeight: 300,
            minRowsToShow: 5,
            enableRowSelection: true,
            multiSelect: false,
            enableGridMenu: true
        };

$scope.gridOptions.data.splice(j, 1, data.server_groups[0]);  
$scope.gridApi.selection.toggleRowSelection($scope.gridOptions.data[j]);

I want to replace a grid's row with the new entity. Once its done, I want to select that particular row.

**Comment by PaulL1** [comment]
Could you perhaps provide a plunker, which would then make it much easier to diagnose.  Perhaps base off the selection tutorial (click the "edit in plunker" button).

**Comment by gnehapk** [comment]
Plunker for the same - http://plnkr.co/edit/UiAuyBaChgkXkHj2XW2N?p=preview

**Comment by PaulL1** [comment]
OK, there are some things in your code that I don't quite understand, so I deleted an if condition....but the main problem is that you've loaded the data, but haven't given the grid time to actually process it.  So you're trying to select a row before the grid knows about it.

You can deal with this by using another interval, I've set it to zero ms, so it runs immediately after the digest cycle finishes.

http://plnkr.co/edit/W5ZLHEW02SIX4PNyVHw8?p=preview

**Comment by gnehapk** [comment]
Thanks alot :+1:
