### ISSUE TITLE
When the first row is opened in an expandable grid the third row loses it's + sign 

### ISSUE THREAD

**Issue by ivankr91** [angular-ui/ng-grid#2689]
As such it's impossible to expand the third row after the first one has been expanded.

http://plnkr.co/edit/CuM0zURR3eNJkrXmjLWA?p=preview

![screenshot1](https://cloud.githubusercontent.com/assets/10808036/5998681/ba972a3e-aad2-11e4-9af3-3ae62d67c64c.png)

**Comment by PaulL1** [comment]
@jpuri, any thoughts?

**Comment by jpuri** [comment]
I am not able to replicate it on the plnkr. I guess some commit has already fixed the issue.

**Comment by PaulL1** [comment]
It was doing it for me on the plunker.  OSX/Chrome.  Open the plunker, click on expand on row 0.  Row 2 loses it's button, and cannot be clicked on.

**Comment by jpuri** [comment]
Oh...even I could replicate that now, might be its random. Let me check this issue.

**Comment by jpuri** [comment]
Hey @PaulL1 ,

I do not have much idea about it. Row headers use left container. Might be @swalters / @novice3030 will be able to help.

**Comment by jessertaylor** [comment]
Everything seems to be floated, and the fact that the +'s are in their own seperate container means it knows nothing about the expanding row (HTML/CSS) wise. 

My workaround was like this:


1) Add a column for the new +

        columnDefs: [
            {
                field: 'expand',
                enableColumnMenu:false,
                enableSorting:false,
                displayName:'',
                width:'*',
                cellTemplate: 'mytemplate.html'
            }
]

2) in mytemplate.html (for example):

<div class="ngCellText" ng-class="col.colIndex()">
    <a toggle-class="row-expanded" ng-click="grid.api.expandable.toggleRowExpansion(row.entity)">
        <div toggle-class="open" class="icon menu2">
            <span></span>
            <span></span>
        </div>
    </a>
</div>

3) Use css to hide the old +s completely, and unfloat everything. Whoever wrote the css for this needs to stop the float love.

**Comment by PaulL1** [comment]
This looks to be resolved - could people verify?

**Comment by PaulL1** [comment]
Looks fixed, no further comment for 2 weeks, assuming can close.
