### ISSUE TITLE
Add public getRow() method to gridTestUtils.spec.js

### ISSUE THREAD

**Issue by mscharp** [angular-ui/ng-grid#2693]
Sometimes it's necessary to get a row from the grid without doing an expectation on it.  Add method:

```javascript
getRow: function( expectedRow, gridId ) {
        return this.getGrid( gridId ).element( by.repeater('(rowRenderIndex, row) in rowContainer.renderedRows track by $index').row( expectedRow )  );
    }
```

And refactor utils to use getRow method instead of manually retrieving the row.

**Comment by PaulL1** [comment]
Happy to accept a pull request with this - or I'll do it next time I'm doing e2e testing (I need to write some methods to test edit).

**Comment by PaulL1** [comment]
This is merged, closing
