### ISSUE TITLE
Getting undefined exception for .custom-csv-link-location

### ISSUE THREAD

**Issue by yugansh20** [angular-ui/ng-grid#2698]
Hi
I am getting undefined exception for class .custom-csv-link-location .
I have looked in all the files and could not find this class.
Please help me in debugging it

exporterCsvLinkElement: angular.element(document.querySelectorAll(".custom-csv-link-location")),

**Comment by PaulL1** [comment]
What version are you using?  Have you tried using the unstable: http://ui-grid.info/release/ui-grid-unstable.js

**Comment by mltroutt** [comment]
Same issue on Bower-installed RC 18. Is there a quick fix to get this working on the Bower installed version? Or any idea when the next RC with this fixed will be in the Bower release?

**Comment by PaulL1** [comment]
The easiest fix is to copy the unstable over top.  The timing for the next RC is indeterminate, as these things always are.  But it is rather close - the dependency is fixing all the hi-pri defects.  There are currently 11 open: https://github.com/angular-ui/ng-grid/issues?q=is%3Aopen+is%3Aissue+label%3A%22Hi-Pri+Bug%22

**Comment by asmath21** [comment]
I had the same issue, Updated to the latest RC and it works. Thanks Paul

**Comment by PaulL1** [comment]
Excellent, closing.

**Comment by yugansh20** [comment]
Hi Paul,


Sorry for the late reply.
I updated the js file and I am still facing this issue.
I am not able to understanf where is this class ".custom-csv-link-location"
