### ISSUE TITLE
cannot apply two match filters to one column

### ISSUE THREAD

**Issue by sunz7** [angular-ui/ng-grid#2701]
Is there a way to apply an "or" filters?
For example, this plunker, http://plnkr.co/edit/LIQCrxwgoKvSr5vaVJwy?p=preview I want to show people with age 20 and 30
Any ideas? Thank you!

**Comment by PaulL1** [comment]
In general the feature is build to work as an AND.  Having said that, the filter does take a regEx, so you could write an OR regEx: http://plnkr.co/edit/6aIq4YfaLxyNlvvCJVLe?p=preview

Having said that, it would be better if you could put that regEx in the term, so I may have a play with that.

**Comment by sunz7** [comment]
Thank you. The solution is good enough for me
