### ISSUE TITLE
afterSelectionChange called numerous times when scrolling.

### ISSUE THREAD

**Issue by Arkh1** [angular-ui/ng-grid#2702]
I would like to use afterSelectionChange to call my save method, but afterSelectionChange is called numerous times when scrolling through the grid contents.  This is apparent when standard editing is enabled, but it is magnified by enabling editOnFocus.  It would seem that the code to reselect the selected cell when scrolling is firing afterSelectionChange over and over again.

Is it possible to prevent afterSelectionChange from being fired when scrolling?

**Comment by PaulL1** [comment]
The latest change to not reselect on scroll should fix this. Try unstable.

**Comment by Arkh1** [comment]
Thanks for the quick response.  The latest version of unstable does appear to fix it.  Thank you!
