### ISSUE TITLE
Complete Example of Import using Button (external picker)

### ISSUE THREAD

**Issue by countrdd** [angular-ui/ng-grid#2705]
Does anyone have a complete example of how to import using an input type=file?

**Comment by PaulL1** [comment]
I've updated the 311 tutorial to show this: http://ui-grid.info/docs/#/tutorial/311_importing_data_with_rowedit

**Comment by countrdd** [comment]
Thank you!....

**Comment by dreadeddev** [comment]
But the plunker doesn't work!! Save a file with the example csv and nothing happens when you import it?
