### ISSUE TITLE
CellNav with EditableOnFocus Enabled is Broken in IE 

### ISSUE THREAD

**Issue by smithscripts** [angular-ui/ng-grid#2707]
I've only noticed this in IE. If you navigate using left or right arrow keys a number of times the cells will not retain focus. This can be seen in this tutorial: http://ui-grid.info/docs/#/tutorial/301_editableOnFocus

**Comment by PaulL1** [comment]
I think it has been broken everywhere.  I've pushed a fix today that I hope fixes this, at the expense of the focused cell being a bit funny when you manually scroll.

**Comment by PaulL1** [comment]
No response for 2 weeks after solution provided, assuming issue is resolved.
