### ISSUE TITLE
Source Missing License Header 

### ISSUE THREAD

**Issue by KelseyBlodgett** [angular-ui/ng-grid#2708]
I noticed that the JavaScript file doesn't have a license header. This seems to be a common practice amongst JavaScript libraries.
Would it be possible to add the information to the file so users can easily adhere to the project's license?
Something like:
Licensed under the MIT License
Thanks.

**Comment by PaulL1** [comment]
I think the unstable now has it: http://ui-grid.info/release/ui-grid-unstable.js  #1316 

It will be in the next RC.

**Comment by PaulL1** [comment]
@KelseyBlodgett : are you expecting the full text of the license, or (as it has now) just the "License: MIT"?

**Comment by KelseyBlodgett** [comment]
Hi Paul, 

We don't expect the entire license text. Just want to make sure the license is clear. 
Thank you!

**Comment by c0bra** [comment]
It will go out in the next release. Thanks for prompting this!

**Comment by KelseyBlodgett** [comment]
thanks!
