### ISSUE TITLE
CSV Import - Columns not accessible if the first row contains a space in the column header 

### ISSUE THREAD

**Issue by countrdd** [angular-ui/ng-grid#2710]
The file I am importing, has a "First Name", "Last Name" in the header column. if I use the ColumnDefs option It does not display the data. Is this a bug?

columnDefs: [

                {name:"ID",type:"number"},
                {name: "First Name"},
                {name:"First_Name"}

            ],

any field that DOES not contain a space in the column header name displays fine...

**Comment by countrdd** [comment]
It is ok...This is the format I had to use.

    { field: 'First Name' },
                { name: 'Last Name'},
                {name: 'address'},
                {name: 'city'},
                {name: 'state'},
                {name: 'zip'},
                {name: 'email'},
                {name: 'type'},
                {name: 'Phone'},
                {name: 'Entry Date'}

**Comment by PaulL1** [comment]
It should strip out spaces, and it should be case insensitive.  The field that is created is:
```
  value.replace( /[^0-9a-zA-Z\-_]/g, '_'
```
So basically anything that isn't 0-9, _ or -, or a letter gets replaced with an _.  Which, now I look at it, might be annoying for non-English speakers.

**Comment by countrdd** [comment]
Thanks! Awesome Work on this...Live this Mod!
