### ISSUE TITLE
rowRenderIndex in cellTemplate prevents grid from showing all data

### ISSUE THREAD

**Issue by ferrao** [angular-ui/ng-grid#2711]
Using uigrid RC18 created a grid with 20 elements, which has a column with the following cellTemplate: 

````
<div class="ui-grid-cell-contents">	
{{ rowRenderIndex + 1 }}
</div>
````

Only the first 14 rows were rendered properly on screen, the others seem to be there during scroll, but some how disappear after.

**Comment by PaulL1** [comment]
The renderIndex relates to how many rows are actually rendered, not the physical rows themselves.  The point of the grid is that we only render the rows that are visible, the rest we don't render - which is the row virtualisation we talk about.  If your page has only about 10 rows visible, then I'd expect the render index to never go above about 14, when you scroll it would probably renumber the existing rows - so it would probably show all the rows, but they'll always be numbers 1-14.  Try adding an id column to your data instead.

**Comment by ferrao** [comment]
Thanks Paul, you are spot on with what occurred, it's just that due to the nature of the data i did not realised i was actually seeing all the data. I have since already added an extra id column to the data.

But just out of curiosity, if i did wanted to understand which row i was and render that on a cellTemplate somehow, is there any mechanism for that currently?

**Comment by PaulL1** [comment]
The cellTemplate can directly get at the current row by just using `row.xxxx`, for example, `row.entity.name`.  This is sort of illustrated in the rowTemplate example: http://ui-grid.info/docs/#/tutorial/301_custom_row_template

**Comment by ferrao** [comment]
you are correct.. I had gone through a few of the examples but failed to notice that. Thanks for pointing it out, might come useful in the future. Ui-grid is looking really nice!
