### ISSUE TITLE
Latest unstable lost ability to click on clickable elements in cells.

### ISSUE THREAD

**Issue by Arkh1** [angular-ui/ng-grid#2718]
Somewhere between the 01/15 and 02/03 in the unstable build the ability to click on anchors or other clickable elements in grid cells has been lost.  When I try to click on links in cells now it it just selects the cell.

Was there a change to settings that we have to work with in order to make the elements within a cell clickable?

**Comment by Arkh1** [comment]
Just glanced at the diff.  Looks like getExternalScopes has been dropped in favor of checking for parent scope.  Based on this I take it I have to remove all of the instances of getExternalScope that I am currently using.

**Comment by Arkh1** [comment]
Replaced getExternalScope() with grid.appScope and we're back on track.

**Comment by bleuscyther** [comment]
+1
