### ISSUE TITLE
Does lazy loading load entire data set?

### ISSUE THREAD

**Issue by pmariduena** [angular-ui/ng-grid#2719]
I've tried reading the tutorial, but it's not clear for me at this point. The question is on infinte scroll feature....based on this tutorial: http://ui-grid.info/docs/#/tutorial/212_infinite_scroll

From what I read here, it seems we are loading the entire data set (say 10,000 rows).

```
  $scope.gridOptions.onRegisterApi = function(gridApi){
    gridApi.infiniteScroll.on.needLoadMoreData($scope,function(){
      $http.get('/data/10000_complex.json')
        .success(function(data) {
          $scope.gridOptions.data = getData(data, page);
          ++page;
          gridApi.infiniteScroll.dataLoaded();
        })
        .error(function() {
          gridApi.infiniteScroll.dataLoaded();
        });
    });
  };
...
  var getData = function(data, page) {
    var res = [];
    for (var i = 0; i < page * 100 && i < data.length; ++i) {
      res.push(data[i]);
    }
    return res;
  };
```

To me, it simply looks like we add to the rendered grid on each scroll that triggers a new chunk of data to be rendered, but we already have the entire data set, which implies we will still incur the big hit of fetching the entire data.

It seems to me what I really want is a server-side paging, where I set up a REST API with parameters for a starting row index and a number of rows in a page (to fetch). This would allow me to fetch the data in chucks-at-a-time, preventing me from incurring the longer query of the entire data set.

1) Am I correct that ui-grid lazy loading actually fetches the entire data set (such that I have to wait for it)?

2) If so, I am correct in my mentioned approach of server-side paging API to prevent that hit in time?

3) If 1 is Yes, can you please clarifying the article above to mention that if you want to avoid loading the entire data set, you need to implement a server-side paging API?

Thanks.

**Comment by PaulL1** [comment]
As I understand it the infinite scroll works with the data that you give it, and when you scroll to the end (top or bottom I think) it raises an event "needMoreData".  You respond to that event with more data, and where you get the data from is your business - it can be local or from the server.  I would usually expect it to come from the server, but since our tutorial site doesn't have a server as such, it probably "fakes" a server by getting the data locally.

Pagination I believe similarly can get data locally or from a server.

**Comment by pmariduena** [comment]
Thanks for your answer. I was able to implemet server-side pagination (which is what I wanted all along) using the latest unstable code with the "externalPagination" feature. It's nice because I can query chunks of the full data at a time as the user choose different pages. And since I always the size of the full data set, we get an accurate calculation of the # of pages that should be rendered.

**Comment by kegster** [comment]
How did you implement the server side pagination? The example doesn't show it actually in use--- it shows 100 rows with a 100row data set. I attempted to use it with a 20,000 row set, and totalItems = 20000 caused page 1 to be 20000 rows. Any ideas on how you implemented this @pmariduena ?
