### ISSUE TITLE
[Doc error] Tutorial 314 External pagination doc makes no sense

### ISSUE THREAD

**Issue by pmariduena** [angular-ui/ng-grid#2720]
http://ui-grid.info/docs/#/tutorial/314_external_pagination

The first paragraph of this doc is (verbatim):
```
When pagination is enabled, the data is displayed in pages that can be browsed using using the built in pagination selector.

For external pagination, handle the paginationChanged' to load the page. Set thegridOptions.totalItems' in the callback.
```

Can you fix this? Or at least tell me what it means?

**Comment by PaulL1** [comment]
What would you like it changed to?  Would you submit a pull request for it?  It seems reasonably clear to me, but I didn't write it.

**Comment by pmariduena** [comment]
Given my understating of what that last sentence is trying to say, it should say something like: "For external pagination, implement the ```gridApi.pagination.on.paginationChanged``` callback function. The callback should update any pagination state variables your application may have, e.g. variables containing the ```pageNumber``` and ```pageSize```. The xhr call used to fetch the data from the server should be called from this callback. The URL of the call should contain parameters that will allow the server-side code to have sufficient information to be able to retrieve the specific subset of data that the client requires. It should also update the  ```$scope.gridOptions.totalItems``` variable with the total count of rows that exist (but were not all fetched since they exist in other pages of data). This will allow ui-grid to calculate the correct number of pages on the client-side.
