### ISSUE TITLE
move column to the end of grid causes the grid header to offset from body..

### ISSUE THREAD

**Issue by lohsu** [angular-ui/ng-grid#2721]
![screen shot 2015-02-06 at 4 24 47 pm](https://cloud.githubusercontent.com/assets/1861271/6089746/b48ffc04-ae1c-11e4-8ff1-b8c501b6cef8.png)
We've encountered an issue where if I drag the column header to the far right, the header becomes decoupled from the body and offset by about the width of the vertical scrollbar.

This doesn't seem to happen on the demo page, and so am wondering if someone has encountered this before and could get some advice on how to fix this. 

Note: I'm using angular 1.3 in my project.

**Comment by PaulL1** [comment]
First I'd try upgrading to unstable (or to the new rc19 that might go out today), that's the most obvious difference with the tutorial pages.

**Comment by PaulL1** [comment]
No response for 2 weeks, assuming issue is resolved by upgrade.

**Comment by lohsu** [comment]
Thanks! Yes, the bug was fixed, but ui-grid's vertical and horizontal scrollbars must be enabled for the table for the fixes to be applied.  Otherwise, the default browser scrollbars creates the misalignment between the header viewport and the grid-body viewport depending on the OS and the timing of the native scrollbars rendering by the browser.

The fix seems to work by making ui-grid's scrollbar override the native scrollbars and recalculate the spaces properly.
