### ISSUE TITLE
[3.0.0-rc.18] saveState

### ISSUE THREAD

**Issue by Chyzwar** [angular-ui/ng-grid#2722]
Hi

In docs http://ui-grid.info/docs/#/tutorial/208_save_state this fature should be in 3.x version but when I try to load ui.grid.saveState module I get injection error. 

I tried on 3.0.0-rc.16 and 3.0.0-rc.18 and It seems that saveState is not in source code. 

Marcin

**Comment by PaulL1** [comment]
It is currently in unstable, and will be in the next rc.

**Comment by Chyzwar** [comment]
Sorry It was my fault. I didn't include directive in grid div. 

Maybe it would be possible to mention about when you need to add directive.
