### ISSUE TITLE
Vertical Scrolling - scrollbar and end of list issue

### ISSUE THREAD

**Issue by jaskaye17** [angular-ui/ng-grid#2723]
I am having an issue with the vertical scroll bar changing size as I scroll down the list. It never actually reaches the bottom of the viewport, but, gets smaller as it gets further down the list of rows.

Additionally, it reaches the end of the list and the scroll bar is only halfway down the viewport height. This leaves a lot of extra blank space at the bottom of the grid. 

The below images are from the same grid at the start of a downward scroll and at the end of the list after a downward scroll. Key features: scroll bar height has dynamically changed; scroll bar position at the END is halfway down the viewport; blank space at the end of the list (user can manually drag scroll bar to bottom, but, it is just a lot of empty space).

TOP (beginning of scroll):
![grid-vertical-scroll-top1](https://cloud.githubusercontent.com/assets/7294623/6095781/7ddf0a2c-af22-11e4-8f88-b14b5528241b.PNG)

BOTTOM (end of scroll):
![grid-vertical-scroll-bottom1](https://cloud.githubusercontent.com/assets/7294623/6095782/88babd9c-af22-11e4-8b44-f3c94771143f.PNG)

I am using UI.Grid: v3.0.0-RC.18-d5229e6 - 2015-01-26

Also, my data is being loaded via http. This may or may not affect grid rendering. ui-grid-canvas also appears to calculate the correct height, 5310 px (177 rows @ 30px height each).

**Comment by PaulL1** [comment]
I'd suggest trying with unstable, there have been a lot of recent changes on scrolling, and we probably wouldn't try to fix/diagnose this unless it's still occurring on the latest code base.

**Comment by jaskaye17** [comment]
@PaulL1 I had a look at the latest unstable release files and updated them, things seem to be working beautifully in regards to this issue. Thanks and keep up the awesome work!
