### ISSUE TITLE
Cannot set property 'grid' of undefined

### ISSUE THREAD

**Issue by Rolando-Barbella** [angular-ui/ng-grid#2724]
Hi, I'm new to angular and ng-grid, I am calling a simple static json file but the grid is not showing at all, the massage I'm getting is **Cannot set property 'grid' of undefined**, anyone can help??

My controlers looks like this

'use strict';
```javascript
angular.module('healthyLivingApp')
  .controller('SubscribersCtrl', function ($scope,$http) {
  	$http.get('http://localhost:9000/subscribers.json').success(function(data){
  		$scope.subscribers = data;
  	});
  	 $scope.gridOptions = {
  		data:'subscribers'
  	}

  });
```
app.js
```
.module('healthyLivingApp', [
'ngAnimate',
    'ngResource',
    'ngRoute',
    'ngSanitize',
    'ngTouch',
    'ngGrid',
    'ui.bootstrap'
  ])
```
My HTML

```
<h1>Subscribers</h1>
<div class="gridStyles" ng-grid="gridOptions">
</div>

```

I'm using bower, 
Angular  "1.3.12", 
ng-grid " "2.0.14""
j-qurey " 2.1.3"

**Comment by c0bra** [comment]
V2 probably won't work right with angular 1.3. Ng-grid is being deprecated in favor of ui-grid.

**Comment by Rolando-Barbella** [comment]
Not sure, I have a plunker here where it works http://plnkr.co/edit/ersNjlKz4xjlmoIGgUli?p=preview, but some reason is not working on my app

**Comment by Rolando-Barbella** [comment]
The css file was missing  <link rel="stylesheet" href="bower_components/ng-grid/ng-grid.min.css" />
sorry about that

**Comment by Rolando-Barbella** [comment]
The css file was missing ```ng-grid.min.css``` sorry about that, when you have an app running with yo, sometimes there is to much going on, I miss that

**Comment by c0bra** [comment]
No worries!
