### ISSUE TITLE
ng-show doesnt work well with angular ui grid

### ISSUE THREAD

**Issue by mikila85** [angular-ui/ng-grid#2725]
Dont mind the "ng-class" it works well only the ng-show doesnt work well with angular ui grid,

watch:
http://plnkr.co/edit/kGq54FH4Wv1ZYpIllL0d?p=preview

at first each row that has "Previous Readmission" is also lightened with a yellow stripe..

after you scroll down things start to be messy :(

**Comment by mikila85** [comment]
And if ng-class do work in chrome, it doesnt in safari. bit diff problem, when scrolling the added class doesnt apply right away so it looks flickering on and off untill you stop scrolling (here when stop scrolling the right line gets the right class).

**Comment by cookednoodles** [comment]
This is very much to do with the cell reuse, if you use a cellClass function, it works fine.

**Comment by mikila85** [comment]
cook that comment for me or for paul?
i dont know how to use cellClass

**Comment by PaulL1** [comment]
This is another example of a problem we've seen a few times.  It's an angular usage error, it needs to be:
`ng-show="row.entity.employed==true"`
not
`ng-show="{{row.entity.employed==true}}"`
http://plnkr.co/edit/LGXrtAYhZinamnBfH0gt?p=preview

**Comment by c0bra** [comment]
Looks like the solution's been given. Closing.

**Comment by DiHuang1986** [comment]
add ui-grid-auto-resize to your ui-grid directive will solve the ng-show problem...
