### ISSUE TITLE
Table with more than 10 columns, it is not showing properly

### ISSUE THREAD

**Issue by vsatishkumar91** [angular-ui/ng-grid#2726]
my data is student data and I have 20 columns in my table,
It is showing properly for 10 or less columns but when I add the 11th columns data is not showing properly,
Am I doing anythinng wrong or its limitation of UI grid?

**Comment by cookednoodles** [comment]
Could you paste a plunker to reproduce it ?

**Comment by vsatishkumar91** [comment]
<div class="list-page-search-div" data-ng-show="!composedApp.showDetailPage" data-ng-class="{'paged-table' : (model.properties.tableType == 'paged')}">
            <div class="list-page-search" data-ng-show="(section.properties.showSearch == true || section.properties.showSearch == 'yes')" data-ng-class="(section.properties.showCreateIcon != true || detailFormAction == 'View') && 'only-search-box'">
                <input type="search" data-appcrest-paged-search ng-model="searchTableData" placeholder="Search List..." />
            </div>
            <div class="paged-table-actions">
                <div class="list-page-create-icon paging-options" data-ng-show="model.properties.tableType == 'paged' && pagedTableDataLoaded && gridOptions.totalItems > 10">
                    <select data-ng-model="gridOptions.pagingPageSize" ng-options="o as o for o in gridOptions.pagingPageSizes"></select>
                    <span>per page</span>
                </div>
                <div class="list-page-create-icon" data-ng-show="(section.properties.showCreateIcon == true || section.properties.showCreateIcon == 'yes')&&  detailFormAction != 'View' && !isEditMode" data-ng-click="createNew();" style="margin-left:15px;">
                    <a class="add-image" title="Add Record"></a>
                </div>
                
                <div class="list-page-create-icon" data-ng-show="isEditMode" data-ng-click="updateRecords();" style="margin-left:15px;">
                    <a class="add-image update-records" title="Update Records"></a>
                </div>
                <div class="list-page-export-to-excel table-edit-excel" data-ng-show="(model.properties.tableType == 'paged' && section.properties.showEditIcon)" data-ng-click="toggleEditMode();" data-ng-class="{'edit-mode':isEditMode}">
                    <a class="edit-image" title="Edit Records"></a>
                </div>
                <div class="list-page-export-to-excel" data-ng-show="section.properties.showExportIcon">
                    <a class="export-excel" data-ng-click="saveToExcel();" title="Export Records to Excel"></a>
                </div>
            </div> 
        </div>

**Comment by PaulL1** [comment]
That's not a plunker.  You need to go to one of the tutorials, click "edit in plunker", then add in your specific code so that it demonstrates the problem.

**Comment by PaulL1** [comment]
No provision of additional information for > 2 weeks, assuming issue is resolved.

**Comment by ngaheer** [comment]
I am able to reproduce this issue. will post code on plunkr soon and post a link.

- Narinder.

**Comment by ngaheer** [comment]
Here is the link to the plunker. Interestingly I had to copy paste the ng table's content rather than importing the library using plunker to reproduce the problem. 

http://plnkr.co/edit/Kxo4zGnwz0mYshbd2SET?p=preview
