### ISSUE TITLE
rowsRendered shows nothing

### ISSUE THREAD

**Issue by narzul1** [angular-ui/ng-grid#2727]
Hi,
I try to use ng-grid, my table is created, the columns headers are there but I don't have anything inside. When checking the DOM, the ng-repeat is only a comment and there is no row rendered.
Do you have an idea of what is happening ?

Thanks

**Comment by PaulL1** [comment]
Have you checked the tutorials? It sounds like you either forgot to put the gridOptions on your html where you defined your grid, or that you forgot to include the ng-grid module in your code, so the directive isn't evaluating at all.

**Comment by mikila85** [comment]
narzul i crossed that issue my self, if your gridOptions has a problem like a bad rowTemplate there is no error in the console but it would show just blank rows.. (will still show the length of the data with the scrollbar) .. maybe thats the case for you, try removing some options sticking with only the data until it shows to eliminate and find the problematic one.

**Comment by narzul1** [comment]
Hi, It is exactly what is happening, I have the columns title and number of rows but nothing displayed.
When you talk about removing option, you mean from the gridOption in the initialization of the grid ?

**Comment by narzul1** [comment]
Even with just the data binding, I get no rows rendered 

driversVm.gridOptions = {
        data: vm.data
}

**Comment by mikila85** [comment]
try reproducing it on plunker so we can help you find your mistake.

**Comment by c0bra** [comment]
Removing from the 3.0 milestone; sounds like a user issue.

**Comment by PaulL1** [comment]
Suggestions provided for assistance, no further communication.  Assuming issue has been resolved.
