### ISSUE TITLE
gridApi.core.notifyDataChange() signature changed

### ISSUE THREAD

**Issue by magiccrafter** [angular-ui/ng-grid#2728]
The function gridApi.core.notifyDataChange(type) has been changed without updating the API and Tutorial section. The right way to call it now is:  gridApi.core.notifyDataChange(grid, type), where grid is the gridApi.grid object. (ui-grid version 3.0.0-rc.16)

**Comment by PaulL1** [comment]
Actually, the other way around.  It used to require grid, but that was redundant since we could derive it from the gridApi.  So it was removed in current unstable, and the documentation reflects current unstable.
