### ISSUE TITLE
Bring back hidden columns

### ISSUE THREAD

**Issue by wendeldw** [angular-ui/ng-grid#2732]
Feature request: 

If you hide a column via the context menu then it is not possible to bring back the column, unless you refresh the page.

**Comment by PaulL1** [comment]
The grid menu, which you can enable but isn't enabled by default, can restore columns.  If you don't like the grid menu, then you can build a custom column picker.

**Comment by wendeldw** [comment]
I suggest to add it as default to the column context menu, only visible when the user has hide a column.

**Comment by PaulL1** [comment]
If the column is hidden, then there won't be a menu to put it in.

**Comment by wendeldw** [comment]
If you hide one column then you can add the restore item to the menu of the remaining columns.

Sit next to a user and see how they interact with your UI. It may surprise you.

**Comment by c0bra** [comment]
Why would you add a menu item to one column  to interact with another? If you have 10 hidden columns do you have 10 extra items whenever you open another column's menu? Or do you have to make an extra level of context menus? Seems nonsensical.

**Comment by PaulL1** [comment]
Closing, I think the grid has a method for doing this, and the proposed enhancement doesn't really fit with our design direction.

**Comment by wendeldw** [comment]
Problem:

By default you can hide a column.
By default you cannot unhide a column.

Solution:

Part 1) If the user hides one column then in the remaining column context menu, a single item appears to restore the grid back to default. 

Part 2) Ensure that the user cannot hide the last column. There is no purpose in hidding all columns. This ensures that you always have one menu to restore the grid.

**Comment by PaulL1** [comment]
Easier and better solution: change the default to be for the grid menu to be visible.  But since users can easily turn that on for themselves with a single setting, I'm not sure why that would be needed.

**Comment by wendeldw** [comment]
In that case, I would also disable the hide feature by default.

Verstuurd vanaf mijn iPad
