### ISSUE TITLE
How to make drop-downs for editable cells seen at all times or by single click

### ISSUE THREAD

**Issue by onkami** [angular-ui/ng-grid#2735]
Hei, I have configured my drop-down edit cells as described here: http://ui-grid.info/docs/#/tutorial/201_editable (Gender column part).

But my cell is meant to be edit field at all times and I do not need a switch between edit and "view" look at all.  So I would like edit field with drop-down to be either: a) shown always (preferable) or b) appear by single-click.

How I can achieve that? If that is not possible now, can you please consider add options for "permanent editing mode" or "single-click edit mode"? 

Double-clicking may result in  selection happening to the cell contents in parallel with starting editing mode.

**Comment by swalters** [comment]
you need to create your own cellTemplate for that columns

**Comment by PaulL1** [comment]
I would expect some performance impact from making all your cells permanently editable.  Depending on browser, maybe not huge.

Single click edit is available, it's called editOnFocus.  Check the tutorials.

**Comment by PaulL1** [comment]
No response for 2 weeks after solution provided, assuming issue is resolved.
