### ISSUE TITLE
Seting enableColumnMenus=false disables column reordering/moving feature

### ISSUE THREAD

**Issue by magiccrafter** [angular-ui/ng-grid#2736]
If grid option enableColumnMenus = false and enableSorting = false, the column moving/reordering feature seems to be disabled also. Here is the plunkr: http://plnkr.co/edit/V0y8Tcld2HaOhJyuvLVQ?p=preview

**Comment by PaulL1** [comment]
EnableSorting:false seems to be the problem.  @jpuri, have you seen this issue before?

**Comment by PaulL1** [comment]
This should be fixed with the touch move changes I did yesterday, they aren't merged yet but can be tested at #3142

**Comment by PaulL1** [comment]
I have merged these changes, closing the issue.
