### ISSUE TITLE
Bug with IE <style> includes limit

### ISSUE THREAD

**Issue by Aynolor** [angular-ui/ng-grid#2738]
Hello !

I'm developing an Angular app with lots of ui-grids on a single page. With each instance of ui-grid, the lib generate a <style> include, due to the template "ui-grid.html". After a certain number grid, I reach the limit of 31 combined stylesheets and <style></style> includes per page imposed by IE (see [Internet Explorer's selector limit on WTF, HTML and CSS?](http://wtfhtmlcss.com/#ie-selector-limit)). So each new grid doesn't display properly.

Have you any ideas or tips to fix this bug? I think that adding style attribut to each HTML element separately will be ok, but the fact that styles are dynamics and use pseudo-class (:last-child in this case) makes the fix harder...

**Comment by PaulL1** [comment]
Do you need all the grids visible at the same time?  (Presumably they can't all be on-screen at the same time?).  Could you wrap the grids in an ng-if when they're not visible?  That would also help your browser performance, and I'm aware that our IE browser performance isn't as great as it might be.

This would be easiest if using a tab or something, but even if it's just a big long list you could write the code to determine which are visible.

**Comment by Aynolor** [comment]
Of course, i don't need all the grids to be visible at the same time ! But i use ng-show instead of ng-if to keep the state of each grid (filter etc.) even if they are hidden. Anyway, I'm aware that this is not an optimal way regarding the performance of my application.

**Comment by PaulL1** [comment]
OK, I think it's unlikely we'd be changing the core styling functionality to avoid a limitation in older IE versions that only occurs in a use case that has a relatively easy workaround.

You could consider using savestate to maintain state, instead of using ng-show.

**Comment by Aynolor** [comment]
I understand this answer, thank you !
