### ISSUE TITLE
Column re-size enhancement.

### ISSUE THREAD

**Issue by smithscripts** [angular-ui/ng-grid#2739]
Can an option be added to re-size the columns dynamically like ng-grid instead of only on mouse-up?

**Comment by PaulL1** [comment]
I'm not entirely clear what you mean - do you mean dynamically to the data at all times, or do you mean that it drags the column width as you resize it?  If the latter, then probably it could be added, but we don't really have anyone who specialises in that kind of css stuff, so it'd be quite low priority unless someone submitted a pull request.

**Comment by PaulL1** [comment]
No further information provided, and resize has quite patchy support at the moment.  I don't believe this is a clear enough request to be implemented by anyone other than the original requestor, whom doesn't appear inclined to submit a PR.
