### ISSUE TITLE
Possible to reference another column value?

### ISSUE THREAD

**Issue by mltroutt** [angular-ui/ng-grid#2740]
I'm attempting to have a column that references another column(s) in the same row, preferably in the normal angular templating fashion of `{{ var }}`. So I'd have something along the lines of

First Header | Second Header | Combined Columns
------------ | ------------- | -------------
Content from cell 1 | Content from cell 2 | {{ first_column }} - {{ second_column }}
Content in the first column | Content in the second column | {{ first_column }} - {{ second_column }}

Where the last column would output the actual values of the first and second columns. But, of course, if I set the value of the cell to `{{ first_column }} - {{ second_column }}` it literally prints out `{{ first_column }} - {{ second_column }}`. I've messed with the `cellTemplate`, tried adding in a `$compile`, moving things around, but I'm always either getting the literal string or nothing.

Is it possible to do this in the current ui-grid? If not, is there any plan for this to be implemented? This is something I could do on the server side, but it would be much cleaner to be able to do it client side, especially if it's bound.

**Comment by PaulL1** [comment]
You should be able to do it, but I think your format would be:
```
  {{ row.entity.column_1 - row.entity.column_2 }}
```

**Comment by mltroutt** [comment]
Thanks for the quick reply, Paul.

I was actually looking to do this in the column data itself, but your reply made me realize that I can do it at the column settings level instead and achieve the results I'm looking for so I'm probably going to go with that.

But, out of curiosity, is it possible to do this with the cell data? I jsut tested it within the cellTemplate and it worked, but in the cell itself it's just printing out the literal value of `{{ row.entity.column_1 - row.entity.column_2 }}`.

**Comment by PaulL1** [comment]
With ui-grid, you can bind a column to a function, and that function could add the two items together.  But you need to insert the function into the row itself.  So you could in theory do:

```
  angular.forEach(myData, function(dataRow) {
    dataRow.calculatedValue = dataRow.value1 + dataRow.value2;
  });
```
and then declare your column field as `name: 'calculatedValue'`.

I think one of the tutorials does something like this, I don't recall the exact syntax.

**Comment by mltroutt** [comment]
Awesome, thanks for the info.
