### ISSUE TITLE
Approach for sorting cellTemplate

### ISSUE THREAD

**Issue by AdityaJitu** [angular-ui/ng-grid#2741]
Hi,
Using cellTemplate I am able to display multiple row entities.  However,  I would like to know the approach to sort the cellTemplates.  As in [this plunker]
(http://plnkr.co/edit/tpl:Yzd3y2goKsO4aILqRfNU?p=preview)

I just did a little modification to your plunker code to display Name in Show Scope column.  After that I would like to sort the *Show Scope* column.

With Regards,
Aditya Padhi

**Comment by PaulL1** [comment]
To have the sort working, you need to give a field.  Try this: http://plnkr.co/edit/wiKtqNlcxgWSGNkALsHZ?p=preview

**Comment by AdityaJitu** [comment]
Thank you Paul for the quick response.  :)
