### ISSUE TITLE
Edit: on scroll event after the end of edit

### ISSUE THREAD

**Issue by sirjasiu** [angular-ui/ng-grid#2742]
In beginEdit function 3 events are registered on scope: OnGridScroll, OnEndCellEdit and OnCancelCellEdit. When edit is finished (OnEndCellEdit is called) still OnGridScroll is remained registered (when you scroll on the grid next call of afterCellEdit callback is performed). I think in every of mentioned listeners the other two should be also deregistered.

I also noticed strange behaviour of this scroll event in mac (chrome). It looks like deregistering was not performed correctly, during scrolling more than one event was raised and afterCellEdit callback was executed few times (in windows this callback is called only once, then it is deregistered). 

I'm working with rc-18 and angular 1.3.9

**Comment by PaulL1** [comment]
This should be fixed in unstable - or rc19 if it went out.

**Comment by sirjasiu** [comment]
Do you have any plans when can you release rc19?

**Comment by PaulL1** [comment]
We were planning to release once all the hi-pri bugs were knocked off.  There are only a handful left.  Help would be appreciated :-)
