### ISSUE TITLE
Publish to bower more often (unstable bower package?)

### ISSUE THREAD

**Issue by kelkes** [angular-ui/ng-grid#2744]
I do not want to be cheeky but would it be possible to publish your progress to bower more often? Maybe a dedicated bower package for the unstable versions? It would simplify my build process :)

**Comment by PaulL1** [comment]
We have been consciously holding off with a target to fix the outstanding hi-pri bugs.  This was to avoid spending our limited time pushing RCs instead of fixing things.  But we've gone a bit slower than we'd like in fixing those bugs.

**Comment by kelkes** [comment]
I totally get the point and appreciate your effort. Can i provide any help? My Angular Skills may not be good enough to help fixing stuff but i could provide some CI/CD skills&infrastructure to automate bower package builds etc.

**Comment by PaulL1** [comment]
Absolutely that would be useful.  One big outstanding is the protractor (e2e) tests running with Travis, that would be really great to get going.

**Comment by PaulL1** [comment]
I think we're now pushing more frequently, so closing.
