### ISSUE TITLE
unselect seleceted row in nggrid by clicking outside of the grid

### ISSUE THREAD

**Issue by swathi1029** [angular-ui/ng-grid#2747]
I have a ng-grid in my page when i select a row in the ng-grid still i leave the page the selection of a row is maintained but i need, once i select the row in ng-grid if i do some(any) other action in my page it should be deselected.

This is my plunker: http://plnkr.co/edit/cZLP2A3W6bKI1bzllj1C

**Comment by PaulL1** [comment]
You don't seem to have any code other than standard grid stuff in there.

To achieve this you need to set an event handler on the page that captures the click, and calls the grid API to deselect the row.  I'm not overly familiar with 2.x, I can't recall the exact method you call.

**Comment by swathi1029** [comment]
I have used a directive to capture the click event outside the div but the problem with the directive is of there are two divs in a page then the the directive is not working. The directive is

app.directive('clickAnywhereButHere', function($document){
  return {
    restrict: 'A',
    link: function(scope, elem, attr, ctrl) {
      elem.bind('click', function(e) {
        // this part keeps it from firing the click on the document.
        e.stopPropagation();
      });
      $document.bind('click', function() {
        // magic here.
        scope.$apply(attr.clickAnywhereButHere);
      })
    }
  }
})

so can you please tell me any alternative method so that I can apply the functionality to all the grids whereever I have used in my project.


Thanks.

**Comment by c0bra** [comment]
It's because your gridOptions.$gridScope is being overwritten by each grid in turn, finally settling with the final grid. You need to call `toggleSelectAll` on each grid in turn. Here's plunker: http://plnkr.co/edit/FWnrT0MARM9SGwQf05WC?p=preview

**Comment by swathi1029** [comment]
But in the above plunker if we select a row in first grid and if we click a row in the second grid the grid selection in the first grid remains, It should be unseleceted how to do this

**Comment by c0bra** [comment]
@swathi1029 You need to bind to the afterSelectionChange event and de-select rows in the other grid if the changed row is selected.

I've updated the plunker to demonstrate this: http://plnkr.co/edit/FWnrT0MARM9SGwQf05WC?p=preview

**Comment by PaulL1** [comment]
Solution provided, no comment for 3 weeks.  Assuming issue is resolved, closing.

**Comment by aderchox** [comment]
This is how I did it in React for future visitors:
```js
  const gridRef = useRef(null);

  useEffect(() => {
    document.addEventListener("mousedown", outsideAgClickHandler);

    const gridArea = gridRef.current.querySelector(".ag-center-cols-container");

    function outsideAgClickHandler(e) {
      if (gridArea && !gridArea.contains(e.target)) {
        gridApi.deselectAll();
      }
    }

    return () =>
      document.removeEventListener("mousedown", outsideAgClickHandler);
  }, [gridRef]);
```
Also if you're here for "Being able to deselect a row when it was selected already" read this: https://stackoverflow.com/a/71105532/9868445
