### ISSUE TITLE
Restore grid saved state on load of page

### ISSUE THREAD

**Issue by aneeshwp** [angular-ui/ng-grid#2748]
I have an app wherein i wish to save the state of users grid and restore it back when the user returns.

For this purpose i am saving the state of users grid whenever the user navigates to different page.

When the users revisits the page, the previous state of grid should be restored automatically (without any explicit action from user).

So for it i am listening for the 'renderingComplete' event, and call my restore function in it.

I have kept my restore function in $interval .

Is it the right way to do it, and don't you think putting the restore function in $interval is not a good way of doing it.

                //restore  grid state , function listens for rendering complete event and then tries to restore user state grid
                $scope.gridApi.core.on.renderingComplete($scope, function() {
                    $interval(function () {
                        var state_name = $state.$current.self.name;    //grid preferences saved for each page
                        $scope.restore(state_name);  //call my restore function 
                    }, 100,5);
                });

**Comment by cookednoodles** [comment]
Why are you doing $interval on a repeat with a time ?
You should be using $timeout();

**Comment by aneeshwp** [comment]
I just wanted to  run it, a few times and then give up.

Initially i had kept a timeout of 200, it worked fine but on slower connection , the grid state was not being restored.

**Comment by PaulL1** [comment]
I wouldn't repeat it, but I would use $interval, with a repeat of 1.  $interval works better with protractor than $timeout does.

The way you're doing it is the accepted way, the only extension I'd make is that I'd wait for all your http requests to resolve before I think called the interval.  (I'm assuming here that some of your grid setup is dependent on the $http, given that you say your render time is impacted by network speed).

**Comment by aneeshwp** [comment]
But why couldn't we have a event when the grid is ready and we can apply setting, we could have done away with timeout or interval then.

**Comment by c0bra** [comment]
What does "ready" mean? It's very difficult to know when rendering is complete because:

1. It's based on many factors, some out of our control, and
2. It happens between angular and the browser. There are no callbacks from the browser available so we can't be triggered passively, we can only actively check.

**Comment by mchurichi** [comment]
I was able to accomplish the same thing on v3.0.7 by restoring the saved state after the promise of my http request is resolved. No timeout required.

Has this been fixed or that's a workaround?

**Comment by PaulL1** [comment]
I don't believe it will be "fixed" as it's by design that it works this way.  The only change we may make at some point is to add a $timeout to the renderingComplete call - so that people don't need to do it themselves.
