### ISSUE TITLE
can i fiter column with comparison operators ?

### ISSUE THREAD

**Issue by jagadiz61** [angular-ui/ng-grid#2753]
I have 3 columns Name,id,age..
i want to see whose age is less than 20 in filtertext..
Pls help me

**Comment by PaulL1** [comment]
What version of the grid are you using - 2.x or 3.x?

**Comment by jagadiz61** [comment]
ng-grid 2.x

**Comment by c0bra** [comment]
No, you cannot with 2.x, AFAIK. The best you could do is a custom external filter.

**Comment by c0bra** [comment]
No response in 2 weeks. Closing.
