### ISSUE TITLE
Cell navigation in combination with cell Edit is broken

### ISSUE THREAD

**Issue by pedroclayman** [angular-ui/ng-grid#2755]
see http://ui-grid.info/docs/#/tutorial/205_row_editable

If you navigate to a cell that lies somewhere outside of the first page (scrolling occurs) and hit F2 then the cell does not become editable. Some weird scrolling happens instead.

**Comment by PaulL1** [comment]
This looks to have been fixed in #2790, could you retest?

**Comment by pedroclayman** [comment]
Fix works. Problem solved.

**Comment by PaulL1** [comment]
Thanks,
