### ISSUE TITLE
ngAnimate makes the grid behave and look wierd.

### ISSUE THREAD

**Issue by mikila85** [angular-ui/ng-grid#2757]
im having hard time reproducing it outside my app :(
but whenever i add 'ngAnimate' the grid start having bad behavior.

i'll work on a plunker hope i can get it to flicker.

**Comment by PaulL1** [comment]
Which version are you using?  This will be much easier to diagnose with a plunker.

**Comment by mikila85** [comment]
im using v1.3.11
i cant reproduce it on plunker :(

**Comment by c0bra** [comment]
Which version of the grid are you using?

The grid should have animations disabled if $animate is available.

**Comment by mikila85** [comment]
ui-grid - v3.0.0-rc.19

how do i disable animate on grid?

**Comment by c0bra** [comment]
It should be disabled automatically. I will look into it.

**Comment by c0bra** [comment]
OK by default the header and footer has animations disabled.

**Comment by c0bra** [comment]
Strange, `$animate.enabled()` is a `noop` in latest angular versions...

**Comment by c0bra** [comment]
I think you're going to need to give us some direction as to how to reproduce. Otherwise we're kind of stuck, unable to track it down :(

**Comment by mikila85** [comment]
not able to reproduce it, just removed ng-animate for now :(
thanks, close please.
