### ISSUE TITLE
There is a way to know that a row is rendered?

### ISSUE THREAD

**Issue by OrenHasbani** [angular-ui/ng-grid#2758]
Hey, i have grid with complex data to show. 
For optimization, I want to make server calls (to get the data for each row) only if the row is rendered.
So, there is a way to get event when the row is rendered for the first time? or any time?
There is a callback like: gridApi.on.rowRendered?

Should i use **rowsRendered** Event? I read that it is raised when the viewport (cached rows) is changed - It's not specific (about which rows entered the cached rows array) ... but if there is no other way i'll use it.

Thanks,
Oren.

**Comment by PaulL1** [comment]
There is no other way via the API that I'm aware of.  You can in theory look in grid.renderContainers.body.renderedRows, but you'd still need an event to notify you that something had changed in the rendering.  I guess if you really wanted you could watch on the renderedRows.

**Comment by c0bra** [comment]
Closing; no response in 2 weeks.
