### ISSUE TITLE
[3.0.0-rc.19] Momentum / kinetic scrolling on touch devices fails

### ISSUE THREAD

**Issue by krix** [angular-ui/ng-grid#2760]
Hi guys,

I'm sorry to say this, but the issue that was already fixed in RC 18 reappeared in 3.0.0 RC 19.
Orginal issue: https://github.com/angular-ui/ng-grid/issues/2671

I'm also pretty sure, that the following commit is causing it: https://github.com/angular-ui/ng-grid/commit/a1082afc88c9063ed51bf4937253410ba136a408

When I remove this part of the touchmove function, momentum scrolling is working again:
```javascript
// Let the parent container scroll if the grid is already at the top/bottom
if ((scrollEvent.y && scrollEvent.y.percentage !== 0 && scrollEvent.y.percentage !== 1) ||
    (scrollEvent.x && scrollEvent.x.percentage !== 0 && scrollEvent.x.percentage !== 1)) {
  event.preventDefault();
}
```

**Comment by krix** [comment]
Update:

If you change this...
```javascript
 // Let the parent container scroll if the grid is already at the top/bottom
if ((scrollEvent.y && scrollEvent.y.percentage !== 0 && scrollEvent.y.percentage !== 1) ||
(scrollEvent.x && scrollEvent.x.percentage !== 0 && scrollEvent.x.percentage !== 1)) {
event.preventDefault();
}
scrollEvent.fireScrollingEvent();
```

...into this:
```javascript
 // Let the parent container scroll if the grid is already at the top/bottom
if ((scrollEvent.y && scrollEvent.y.percentage !== 0 && scrollEvent.y.percentage !== 1) ||
(scrollEvent.x && scrollEvent.x.percentage !== 0 && scrollEvent.x.percentage !== 1)) {
event.preventDefault();
scrollEvent.fireScrollingEvent();
}
```

...then it works like a charm again.

**Comment by PaulL1** [comment]
@c0bra, @swalters, I saw some commentary on gitter about a change like this today - there was some suggestion that making this change was in turn breaking scrolling on some render containers?

**Comment by c0bra** [comment]
Should be fixed with my latest commit, hopefully

**Comment by c0bra** [comment]
@krix please test on the demo site. This looks fixed for me in emulation and on my Android device.

**Comment by krix** [comment]
@c0bra looks very good to me. Thank you for your help! Keep up the good work, you all do an amazing job! <3
