### ISSUE TITLE
Selection Checkboxes not working.

### ISSUE THREAD

**Issue by sachinny21** [angular-ui/ng-grid#2761]
Hi UI-Grid team.

I am having a weird issue where all the symbols are working fine except for the selection checkboxes...  I tried having just the selection module by itself and that didn't help either.  Any ideas of what might be happening?

I am on v3.0.0-RC.18-e4b2293 .js/.css

![checkboxselectionerror](https://cloud.githubusercontent.com/assets/9724198/6171436/b498bbc4-b2a8-11e4-9d7b-7adc0954b6c6.png)

**Comment by PaulL1** [comment]
It sounds like a font problem, perhaps your fontello hasn't built properly?  Does it work when you grab the unstable .js/.css and fonts?

**Comment by sachinny21** [comment]
No, I tried with the latest builds, and still having the same issue...  The only symbols missing are the checkboxes...

![alignmentnewerror](https://cloud.githubusercontent.com/assets/9724198/6235552/45aeaa04-b6b1-11e4-8bf5-8152a1a13a66.png)

**Comment by sachinny21** [comment]
This has now been fixed with a later build.  Thanks for looking into this Paul!

**Comment by PaulL1** [comment]
Excellent, thanks.

**Comment by passivereferral** [comment]
This problem is coming again when selecting . I guess this is started with latest upgrade which was introduced .

angular.js:14996 TypeError: row.setSelected is not a function
    at ui-grid.js:247668
    at Array.forEach (<anonymous>)
    at Grid.selectAllVisibleRows (ui-grid.js:247665)
    at Object.selectAllVisibleRows (ui-grid.js:288012)
    at ChildScope.$scope.headerButtonClick (ui-grid.js:248225)
    at fn (eval at compile (angular.js:15847), <anonymous>:4:249)
    at callback (angular.js:28064)
    at ChildScope.$eval (angular.js:18816)
    at ChildScope.$apply (angular.js:18915)
    at HTMLDivElement.<anonymous> (angular.js:28069)

**Comment by mportuga** [comment]
@passivereferral The issue is resolved, it was due to a mistake with the concat task for the grid after I reorganized the repository.
