### ISSUE TITLE
Rows removed while user is scrolling aren't always removed.

### ISSUE THREAD

**Issue by roguezedd** [angular-ui/ng-grid#2765]
A user submits an ajax request to remove row data to the backend. Once the row data removal is confirmed in the response, a new data source is constructed with the relevant rows removed/omitted. If the user is scrolling while the grid data source is changed, not all of the rows from the previous data source are removed from the screen.

**Comment by PaulL1** [comment]
That sounds somewhat complex to replicate.

Firstly, what version are you using - 2.x or 3.x?  Secondly, is it possible to create a plunker that demonstrates the issue?

**Comment by c0bra** [comment]
No response in 2 weeks. @roguezedd if this is still a problem with rc.20 please file a new issue with some steps to reproduce.  I think it should be possible to check by using a $timeout that removes rows from the data set and just manually scrolling during it.
