### ISSUE TITLE
Angular JS ng-grid rendering issue

### ISSUE THREAD

**Issue by vigneshkumarj7** [angular-ui/ng-grid#2769]
Hi All,

I am new to Angular JS, I tried an client side app using angular js. I have used the ng-grid for forming table structure which is an effective one. But still I face some problems in ng-grid. 

I am using the ng-grid version ng-grid-1.3.2.js and  AngularJS v1.2.19. 

I face some problem while the grid rendering. The data gets retrieved from the server, but it doesn't bind to the grid. It shows empty grid or displays the hidden fields in the grid with the hash key. Please make a solution. 

Thanks in advance.

![render 1](https://cloud.githubusercontent.com/assets/9857766/6182917/f47b0c2c-b372-11e4-842e-62c978b4d136.jpg)

![render 2](https://cloud.githubusercontent.com/assets/9857766/6182919/ffc7e780-b372-11e4-91f2-c4f8d73447e9.jpg)

**Comment by PaulL1** [comment]
It sounds like you haven't correctly set the data in the gridoptions.  Some suggestions:
1. ng-grid is less well supported, the new 3.0 version (ui-grid) is better supported.  If you're doing this for the purposes of learning, then you may find better support with ui-grid
2. have you followed the tutorials closely?  Perhaps one of the learning tutorials like https://technpol.wordpress.com/category/technology-2/tutorials/rails-4-and-angular/ might help you?
3. failing all that, could you provide a plunker so we can see your code and assist.

**Comment by vigneshkumarj7** [comment]
Thanks PaulL....

But the issues in ng-grid is fixed when the Grid is refreshed. I don't know, how it was fixed.. But I have to refresh the whole page where the grid is sited..

**Comment by c0bra** [comment]
@vigneshkumarj7 ng-grid 1.3.2 is 3 years old. I would at LEAST try to update to the latest in the 2.x series and see what that gets you.

**Comment by c0bra** [comment]
No response in 2 weeks. Closing.
