### ISSUE TITLE
Request: Include src files in Bower repo

### ISSUE THREAD

**Issue by joshuahiggins** [angular-ui/ng-grid#2778]
Currently, the Bower repo includes only the distribution files from this repository. This means that a user must always store fonts in the same directory as the CSS, since there is no way to override the font-face URLs. 

Adding in the src folder would allow users to import the main LESS file and change the font path as well as any other variables they wish prior to compiling. 

I thought that I'd be able to get around this by including this repo directly, instead of the bower distribution repo. Unfortunately fonts aren't built in this repo. I'd need both in order to get the LESS and the fonts together, or I'd need to pull down the full repo and do builds myself. Not an ideal solution.

**Comment by PaulL1** [comment]
I seem to recall we did a PR that someone submitted that was to enable fonts to be stored in another directory.  I think the trick was to override a variable somewhere.  Let me look for it.

**Comment by joshuahiggins** [comment]
Yes, his pull request allows the overriding of the LESS via variables. Am I missing where the fonts are located in this master repository though? Unless I'm mistaken, I believe the font files are not stored in this repository and are built during the Grunt Fontello process. 

Ideally, one of the 2 repos (master or bower) would include both the built font files and the src LESS files, so that a user has more solutions to the problem custom font folder location. Currently there are 2 solutions: 1) store font files within same directory, as determined via the distributed UI-Grid build or 2) integrate your own Fontello build process for UI-Grid into your project's grunt workflow.

**Comment by c0bra** [comment]
This is something that bootstrap does with bower, correct? There's not a "stripped-down" version of the  repo that users can install if they only want compiled files, is there?

**Comment by joshuahiggins** [comment]
Correct, Bootstrap includes their source CSS. In my experience, it's more common for Bower repos to include source files than not. Angular does not, but Angular is also purely JS.

**Comment by iyel** [comment]
+1

**Comment by bierdok** [comment]
+1
