### ISSUE TITLE
custom headerTemplate size does not stay constant

### ISSUE THREAD

**Issue by rinckd** [angular-ui/ng-grid#2781]
I would like to create two header rows by using a custom headerTemplate. This is how it was done in ng-grid 2.0: http://plnkr.co/edit/i261iOpP2PdfGgg3C6ng?p=preview

Migrating to ui-grid, it appears to work at first, but if you click on any of the sorting columns the header size increases. Is there a work around for this? Or is my headerTemplate wrong?
Here's my plunker, click on any column header and the header changes size: 
http://plnkr.co/edit/27PuMj?p=info

**Comment by c0bra** [comment]
This happens because header cell heights are calculated based off the header height and the calculation expects the only thing in the header to be the cells, which is probably the wrong thing to do.

I am looking into a fix.

**Comment by rinckd** [comment]
Thanks. I did learn that if I add this .css it fixes my issue. Not sure if that helps you with an overall fix.

ui-grid-header-cell {
    height: 30px !important;
}
