### ISSUE TITLE
To show a line in the grid header

### ISSUE THREAD

**Issue by swathi1029** [angular-ui/ng-grid#2782]
I had a requirement of showing a line in the grid header starting from some column to till end. I dont know how to do that. I have tried in css using text overline and it is not the correct process can you please help me out how to do that. To be clear i have added an image.

![grid](https://cloud.githubusercontent.com/assets/10825275/6212010/71031cd6-b606-11e4-8c4e-6c07a4856396.png)

**Comment by c0bra** [comment]
How do you determine which columns the line will be over?  Can the columns be reordered?

**Comment by swathi1029** [comment]
The columns can't be reordered. The columns belong some category should be overlined. We will not specify any special properties for those columns. Just to know for the viewers that those columns belong to a category we are placing a line over them. Is there any way to show this. Please help me out.

**Comment by swathi1029** [comment]
Can anybody please give me a reply for this.

**Comment by c0bra** [comment]
Would using `headerCellClass` work?

Here's a demonstration plunker: http://plnkr.co/edit/NT55Ak?p=preview

**Comment by swathi1029** [comment]
I am using ng-grid not ui-grid. Is it applicable for ng-grid. I have used it and it is not showing the line. I am adding the plunker to make you clear. Can you please check it out Is there any mistake in my plunker.

http://plnkr.co/edit/gHSYo5n3G9EgfRYfnoqr?p=preview

**Comment by c0bra** [comment]
Ah, the property for ng-grid is `headerClass`. You can find the (incomplete) docs here: http://angular-ui.github.io/ng-grid/
