### ISSUE TITLE
IE 9 Performance on auto resize

### ISSUE THREAD

**Issue by anandvihar** [angular-ui/ng-grid#2783]
Any alternative of ui-grid-autoResize.Its performance is pretty bad in IE9.

**Comment by PaulL1** [comment]
All it's doing is calling the resize api from a timer I think.  If you have some way to notice the event that is triggering the resize, then you could call handleResize yourself from that event.

**Comment by c0bra** [comment]
This tutorial works alright for me in IE9: http://ui-grid.info/docs/#/tutorial/213_auto_resizing  Is this what's not performing well, or something else?

**Comment by PaulL1** [comment]
Workaround suggested, no further comment for some time.  Assuming issue has been resolved, closing.
