### ISSUE TITLE
ui-grid-render-container element is larger then grid element

### ISSUE THREAD

**Issue by gvlekke** [angular-ui/ng-grid#2786]
I have a webapplication based on bootstrap with the modules data-ui-grid-auto-resize, data-ui-grid-selection, data-ui-grid-cellnav

When i add the grid and set the following

```
.passage-grid {
  height: 300px;
}
```

I expect that the grid is fixed and the content can be scrolled.
The output was that the ui-grid-render-container element is larger then grid element and shows all items.

Is this a bug or can I fix this myself?

**Comment by c0bra** [comment]
Are you able to reproduce in a plunker, or provide a screenshot with the render container element highlighted in development tools so we can see exactly how it looks?

Thanks

**Comment by gvlekke** [comment]
Update from version 18 to version 19 fixes the problem
