### ISSUE TITLE
adding ui-grid-cellnav disables row selection and forcely enables cell selection.

### ISSUE THREAD

**Issue by mikila85** [angular-ui/ng-grid#2788]
adding ui-grid-cellnav disables row selection and forcely enables Cell selection. even if 
enableRowSelection: true

im using ui-grid-cellnav for  $scope.gridApi.cellNav.scrollTo(row)

http://plnkr.co/edit/yukJlcdVVxte4ZV5jK6h?p=preview

*Only if click the line between columns it will select row

**Comment by swalters** [comment]
Add the row selection checkbox. That's the only way you can select rows with cellNav on.

**Comment by mikila85** [comment]
really?
just bad design? :-1: 

how do i use scrollTo row if i need to scroll to row not to cell.
the grid is select row.
any way to access the scrollTo without adding the cellNav?

**Comment by mikila85** [comment]
@c0bra have any idea how i can do it? its not a good design to have a general feature like scrollTo attached to a specific type like cellNav.

**Comment by c0bra** [comment]
How is it bad design? With cellnav you need to be able to select cells by clicking on them. What would you want to happen with row selection enabled? You select both the cell and the row? That, in my opinion, would be bad design.

**Comment by mikila85** [comment]
scrollTo accepts:
grid, $scope, rowEntity, colDef

checks if any specifics has been requested and if not sends the row/col to:

which sends to scrollToInternal:
grid, gridRow, gridCol

so it is pretty general, can go to row or cell... meaning that it can be in a higher scope that everyone can use it as ScrollTo(row) .. and cellNav can use it too with the extra params for cell.. its already build in it.

scrollTo is a base function for a grid. shouldent be limited to cells only OMHO :)

**Comment by PaulL1** [comment]
Arguably scrollTo could be a grid function, since it doesn't select anything.  ScrollToFocus clearly has to be cellNav, as only cellNav uses focus.  I can't recall whether scrollTo uses any logic specific to cellNav though, I feel that it might.

**Comment by mikila85** [comment]
@PaulL1 thank you for your help, is it in your intention to convert scrollTo to a grid function or is there a way i can do it manually? i really need to scrollTo line (without activating cellNav coz need row selection - without checkbox for select row)

i tried changing the code my self to add it as a grid function but scrollTo uses scrollToInternal which uses scrollEvent which uses scrollThrottle and thats where i got confused :(

please help.

**Comment by mikila85** [comment]
@PaulL1 ?

**Comment by lecoleco** [comment]
cell nav and put cellTemplate with a checkbox
get this error when navigation 

TypeError: Cannot read property 'focus' of undefined
    at ui-grid-unstable.js:12549
    at l.$get.l.$broadcast (angular.js:14720)
    at Object.module.directive.compile.pre.uiGridCtrl.cellNav.broadcastCellNav.grid.cellNav.broadcastCellNav [as broadcastCellNav] (ui-grid-unstable.js:12280)
    at Object.module.directive.compile.pre.uiGridCtrl.cellNav.handleKeyDown (ui-grid-unstable.js:12355)
    at HTMLDivElement.<anonymous> (ui-grid-unstable.js:12403)
    at HTMLDivElement.n.event.dispatch (jquery.js:4430)
    at HTMLDivElement.n.event.add.r.handle (jquery.js:4116)

**Comment by PaulL1** [comment]
@mikila85 : no, I don't currently have any plans to do this - I don't need it personally, and it doesn't cause me any issues to include cellNav.  It's a reasonably large refactor by the looks of it, since the scrollTo methods are linked all that code would need to move into core, and care would need to be taken that it didn't impact other things.

**Comment by mikila85** [comment]
Yes i understand, as a company we were investigating ng ui-grid for a new product we developing but we now decided to go with kendo ui grid as its more stable and has many more features, thank you for the help guys.

**Comment by ivangitgild** [comment]
No updates about this? Enabling Cell navigation disables the Cell Selection tool, on previous version the ng-grid it works well, the navigation and cell selection interacts nicely. hope thers an update for this. thank you

**Comment by sennz** [comment]
I have the same problem, when enable key navigation I can't select a row by clicking on a cell.

**Comment by tapresle** [comment]
Is there any opposition to changing cellNav's function to also raise a row selection event? This seems like something that would help with accessibility.

**Comment by madhansekar** [comment]
Hi im facing issue like my data is there in grid but its not displaying while scrolling its diplaying can any one please help me

**Comment by kodecraft** [comment]
The following works for me:

```javascript
vm.gridOptions.onRegisterApi = function(gridApi)
{
    vm.gridApi = gridApi;
    gridApi.cellNav.on.navigate(null, function(newRowCol, oldRowCol){
         vm.gridApi.selection.selectRow(newRowCol.row.entity);
         vm.gridApi.core.notifyDataChange( vm.gridApi.grid,  uiGridConstants.dataChange.COLUMN );
    });
};
```

**Comment by kalihos** [comment]
I have found this page looking for the same problem. Although I think the design is correct, it's evident that there's a lack of functionality about this topic. But I believe it's possible to solve it making the markup attribute dependant on a logical expression. So, for example, we could say something like this:
<div ui-grid="gridOptions" ui-grid-selection ui-grid-cellnav**="logicalcontrol==value"**></div>

Using this way, the structure wouldn't be affected, but it would be possible to decide when we can navigate, and when not.
