### ISSUE TITLE
adding and removing columns toggle visible ruins the grid.

### ISSUE THREAD

**Issue by mikila85** [angular-ui/ng-grid#2789]
reproduce:
1) go here: http://ui-grid.info/docs/#/tutorial/113_adding_and_removing_columns
2) press 4 times "Add"
3) press 1 time "Toggle Visible"
4) scroll down.

**Comment by c0bra** [comment]
Note to self: the problem is here: https://github.com/angular-ui/ng-grid/blob/fee00cdfa5aeaeb5a10db8ea71e64035eb39bba0/src/js/core/factories/Grid.js#L796

a & b here are GridColumn objects. This probably needs to be `a.name.match` and `b.name.match`.
