### ISSUE TITLE
Add class to expandableScrollFiller

### ISSUE THREAD

**Issue by mimopo** [angular-ui/ng-grid#2793]
Hi! 

A css class in the "expandableScrollFiller" template would be very usefull for designers. This would open the possibility of changing the background color , add inset box-shadow , etc ...

Thanks!

**Comment by PaulL1** [comment]
@jpuri: is this something you'd consider adding?

**Comment by jpuri** [comment]
Sure @PaulL1 , thats good suggestion. I will implement it.

**Comment by mimopo** [comment]
:+1:

**Comment by jpuri** [comment]
Hi,
This one got much delayed. I am taking it up now.

**Comment by jpuri** [comment]
This should be working now.

**Comment by mimopo** [comment]
cool!
