### ISSUE TITLE
Documentation files differing only in case cause problems on Windows, OS X

### ISSUE THREAD

**Issue by robertbcalhoun** [angular-ui/ng-grid#2794]
This issue pertains to the release repo at https://github.com/angular-ui/ui-grid.info, which directs users to submit bug reports here.

Several files in ui-grid.info/docs/partials/api/ differ only in case. These are:
* ui.grid.cellNav.directive.uiCellNav.html and ui.grid.cellnav.directive.uiCellNav.html
* ui.grid.cellNav.directive.uiGridCell.html and ui.grid.cellnav.directive.uiGridCell.htm
* ui.grid.cellNav.service.uiGridNavService.html and ui.grid.cellnav.service.uiGridNavService.html
* ui.grid.cellNav.constant.uiGridEditConstants.html and ui.grid.cellnav.constant.uiGridEditConstants.html

If the resulting github zip archive or git clone is done on a case-preserving, case-insensitive filesystem (Windows NTFS, default OS X HFS+), failure occurs. Unzipping fails with an error and git claims working copy changes when no changes have been made.

These ambiguous filenames are present since the oldest tag (gh-pages v3.0.0-rc.2-gec2e962) and are present as of gh-pages v3.0.0-RC.18-232a0a0.

To me, it looks like ui.grid.cellnav.service.* are obsolete and should be deleted.

**Comment by PaulL1** [comment]
Hmm.  I looked, but these files in compiled format aren't present in the ng-grid repo, nor are they in the ui-grid.info repo.  So I am presuming that at some point in the past these got built onto the website, and haven't been deleted by the build process.  I'm not sure I know where to look to fix it - @c0bra?

**Comment by c0bra** [comment]
Yep I ran into this myself recently. I will try to clean it up. Thanks for reporting, @robertbcalhoun.

**Comment by robertbcalhoun** [comment]
Thank you!

**Comment by c0bra** [comment]
This should be fixed now. @robertbcalhoun  Can you let me know if it's working for you?

**Comment by robertbcalhoun** [comment]
Starting from https://github.com/angular-ui/ui-grid.info/tree/gh-pages and clicking the "Download ZIP" (
https://github.com/angular-ui/ui-grid.info/archive/gh-pages.zip) now generates a zip archive that can be successfully unzipped on Windows, and the offending files are gone. Likewise git no longer claims there are changes in fresh checkouts. Victory.

It might be worth mentioning on the ui-grid.info page that branch "master" doesn't have anything in it, so you need to follow `git clone https://github.com/angular-ui/ui-grid.info.git` with `git checkout gh-pages`. (Maybe the big red download button on http://ui-grid.info/ should link to the zip archive instead of the github page https://github.com/angular-ui/ui-grid.info/tree/gh-pages/release.)

But, now that I can actually switch branches, I'm good. Thanks for the fix. I will close the ticket.
