### ISSUE TITLE
ui-grid-cellNav fails for rows not rendered in initial grid view

### ISSUE THREAD

**Issue by brummell** [angular-ui/ng-grid#2795]
Inclusion of cellNav seems to prevent all rows beyond those ~rendered(?) in the initial view of the grid from being edited. 

No amount of tinkering with virtualization thresholds had any impact... for whatever that's worth for debugging purposes (I don't expect that it should, in the bug-free case?).

This is visible in the tutorial:
http://ui-grid.info/docs/#/tutorial/309_editable_with_cellnav
for me using a ~2009 macbook pro running Chrome Version 38.0.2125.104

(Also, sorry if I'm just missing something stupid, I'm WAY out of my wheelhouse on the front-end.)

Thanks,
D

**Comment by PaulL1** [comment]
I think we fixed this recently - could you try RC20?

**Comment by brummell** [comment]
Yep, when I get a bit of free time I'll give it a shot. Thanks!

**Comment by c0bra** [comment]
No response in > 2 weeks. I'm going to close; if it's still a problem, please open a new issue.
