### ISSUE TITLE
Custom filter ui

### ISSUE THREAD

**Issue by yccteam** [angular-ui/ng-grid#2796]
I could not find how to implement custom filter ui (i.e. a multiselect, a drop down or a time/date/datetime ui).
I was thinking of something in the form of:
'''filter: {
          condition: function myLogic(searchTerm, cellValue){
                    // logic comes here
          },
          placeholder: 'ends with',
          ui: uiGridMultiSelect
}'''
The example above would create a multi select comprised of the values available in this column to filter with.
Any way to this right now?

**Comment by PaulL1** [comment]
This is a feature that we don't currently have, but I think it would be useful, so I'll mark it for future implementation.

**Comment by PaulL1** [comment]
I've added a dropdown.  I didn't find an easy way to add a multi-select dropdown to the core, because we're using native controls and don't want to introduce dependencies on external libraries.  I'm still thinking on a way to generalise this to allow other controls to be injected.

**Comment by shrihari1857** [comment]
has the issue of displaying Angularjs bootstrap datepicker on headerCellTemplate on ng-Grid been resolved?

**Comment by PaulL1** [comment]
I've provided the ability to have custom filter templates.

**Comment by shrihari1857** [comment]
I wanted to have a bootstrap datepicker on headerCellTemplate, got it resolved a few days back by adding overflow: visible to the ngHeaderContainer class, as shown below.
.ngHeaderContainer {
  position: relative;
  overflow: visible !important;
  font-weight: bold;
  background-color: inherit;
}
