### ISSUE TITLE
"OR" filter

### ISSUE THREAD

**Issue by yccteam** [angular-ui/ng-grid#2797]
I've read the documentation and could not find any way to create an "OR" filter (when dealing with multiple filter fields). The examples only show an "AND" filter. Can this be done using the current API?

**Comment by PaulL1** [comment]
Only through a regEx

**Comment by PaulL1** [comment]
I don't think this is something we're intending to add, and products like Excel also don't allow this, so I'm closing as something that's not included in our product direction.

**Comment by yccteam** [comment]
Excel might not, but kendoUI does... which is very helpful.
