### ISSUE TITLE
suppressRemoveSort breaks sorting for other columns.

### ISSUE THREAD

**Issue by KingKahuna** [angular-ui/ng-grid#2799]
If you set suppressRemoveSort = true for any column, once that column has been sorted then no other column can be used for sorting.

Example here:
http://plnkr.co/edit/y9PlnTx1idB9zs5VYacr?p=preview

This used to work in RC18.

**Comment by PaulL1** [comment]
Is that not the expected behaviour - if you cannot remove the sort, then that column must stay sorted.

**Comment by KingKahuna** [comment]
I did wonder whether this was the expected behaviour and that we were relying on a bug to achieve what we're after.

When clicking the heading the sort goes - 'Ascending' - 'Descending' - 'No Sort'. We just want it to alternate between Ascending and Descending, but not prevent sorting on other columns. Setting suppressRemoveSort to true got this to work on previous versions. There doesn't appear to be a way to achieve this now :-(

**Comment by PaulL1** [comment]
So if I understand you correctly, you want the sort not to be removed from the column, but if a new sort is added you're OK for it to become a higher priority sort (with the name sort remaining as a lower priority sort)?

I think you could achieve this by listening to the sortChanged event, and then shuffling the sort priorities appropriately, and calling queueGridRefresh.  Would that meet your needs?

**Comment by winktechnologies** [comment]
I had the same problem and I was able to solve it with setting `suppressRemoveSort: true` on each column and I've added in `onRegisterApi`
```javascript
$scope.gridApi.core.on.sortChanged($scope, function(grid, sortColumns) {
  if(sortColumns.length > 1) {
    angular.forEach(sortColumns, function(col){
      if(col.sort.priority === 1) {
        col.sort.priority = 0;
        col.sort.direction = null;
      } else {
        col.sort.priority = 1;
      }
    });
  } else {
    sortColumns[0].sort.priority = 1;
  }
});
```

**Comment by PaulL1** [comment]
that would work if you only ever had two sort columns - what does it do if you have three?

**Comment by winktechnologies** [comment]
The result is that only one column from any number of columns is sorted.
I'm setting the `col.sort.priority = 1` only for the column that will be sorted and by setting `col.sort.direction = null` I'm removing sort from the rest of the columns.

With that I will have 1 or 2 elements in `sortColumns` array (not more).
1 element - when you're toggle sorting on one column.
2 - when you're switching to an other column.

Maybe I'm missing a case but it looks like it's working in my app :)

**Comment by PaulL1** [comment]
Oh, OK.  So your intention is that you always have at least one column sorted, but you don't care which column.  Understand.

**Comment by winktechnologies** [comment]
yes :) Thanks @PaulL1 for looking at it.

**Comment by KingKahuna** [comment]
Thanks @winktechnologies  that's fixed it for me.

**Comment by nitrium** [comment]
Yup, thanks. Keeping an eye for any developments on this feature/issue.
