### ISSUE TITLE
Controller 'uiGrid', required by directive 'uiGrid', can't be found!

### ISSUE THREAD

**Issue by yahavger** [angular-ui/ng-grid#2804]
i updated the ui-grid from  

! ui-grid - v3.0.0-RC.18 - 2014-12-09  to  * ui-grid - v3.0.0-rc.19 - 2015-02-11

and i got the error

Error: [$compile:ctreq] Controller 'uiGrid', required by directive 'uiGrid', can't be found!

what am i missing ?

**Comment by c0bra** [comment]
How are you referencing ui-grid? Did you install it with bower?

Check your Network tab, is ui-grid.js being loaded? Can you run `angular.module('ui.grid');` successfully?

**Comment by yahavger** [comment]
1.) yes i am refering to ui-grid.
2.) yes i install it with bower.
3.) i can see the ui-grid in the current version in the dev tools
4.) angular.module('ui.grid') run successfully

the only change i did in my project is updating ui-grid version from .18 to .19

i did some tests , and it seems that in fresh project it's work with no problem... i guess i have some conflicts between plugins.

**Comment by cosenmarco** [comment]
+1

I experience this problem as well. I have a nested grid and I believe this is generated by the directive "uiGrid" in the ui.grid.expandable module.

If I comment the following line (line 13724 in ui-grid.js) the error is gone, the nested grid is shown but I get many other errors along the way.
```
require: '^uiGrid'
```

**Comment by c0bra** [comment]
Yea that should probably be `?^uiGrid` and it should bails if no parent grid is found. This may be a breaking change from 1.2.x to 1.3.x, possibly.

**Comment by drmoose** [comment]
Try Firefox. The plunker you linked works fine in IE but dies in FF.

**Comment by drmoose** [comment]
I've found setting the `priority:` of the `ui.grid.expandable` "uiGrid" directive to a negative number [on line 284 of expandable.js](https://github.com/angular-ui/ng-grid/blob/3292e3fefd83f2236c8349823dae2264ad203c12/src/features/expandable/js/expandable.js#L284) is a viable workaround.

The idea being to force angular to run that directive it *after* the "uiGrid" directive from `ui.grid`, it seems to solve the problem for Firefox, IE, and Chrome.

**Comment by devakone** [comment]
Any updates on this, it happens if i used a ng-if tag on a div containing the ui-grid directive.

**Comment by c0bra** [comment]
@devakone Strange, the plunker forks fine for me in FF as well. I'm using v36.0.4. Can you check on your version?

**Comment by devakone** [comment]
I fixed it by setting the ng-if directive on a parent div!

**Comment by c0bra** [comment]
OK, but I guess what I'm saying is that I'm not finding it necessary to do that to get that plunker to work...

**Comment by drmoose** [comment]
I concur that I can no longer reproduce it on the original plunkr, but @devakone  is right about ng-if breaking it.

Here's a fork of your plunkr with no change other than an ng-if on the div: http://plnkr.co/edit/Xy9o9tXqwu2dQKwIFmCF?p=preview

Breaks on FF 36.0.4 for me; will recheck with addons off and update this post.

**Comment by devakone** [comment]
Thanks @drmoose, @c0bra that's indeed the behavior I am experiencing.

**Comment by c0bra** [comment]
OK I found it. ngIf runs with priority 600 and the expandable features stacks uiGrid with a directive that runs at 1000: https://github.com/angular-ui/ng-grid/blob/master/src/features/expandable/js/expandable.js#L284
