### ISSUE TITLE
Using right/down arrow keys to navigate with editOnFocus fails to emit END_CELL_EDIT

### ISSUE THREAD

**Issue by axelstudios** [angular-ui/ng-grid#2807]
If you navigate using the right or down arrow keys, `END_CELL_EDIT` won't get emitted, and thus `afterCellEdit` won't get called.  Watch the Last Cell Edited output on [309](http://ui-grid.info/docs/#/tutorial/309_editable_with_cellnav) after hitting right/down.

Pressing right/down only works successfully if the grid has to scroll to show the cell.  Up/left/tab/enter all work as expected.

[The problem is here](https://github.com/angular-ui/ng-grid/blob/0fc6b21ceff002226697e5d3520b6d4f8374b678/src/features/edit/js/gridEdit.js#L768): the blur event isn't happening for these keys, so `stopEdit` isn't getting called.  And it's apparently been broken [since November](https://github.com/angular-ui/ng-grid/pull/2084).

![issue](https://cloud.githubusercontent.com/assets/411466/6270559/11227082-b818-11e4-9857-cc941ae1757b.gif)

**Comment by PaulL1** [comment]
I also see that edit on focus isn't working if we have to scroll to show the cell - it works fine if no scroll event happens.

**Comment by swalters** [comment]
should be fixed by #3120

**Comment by c0bra** [comment]
This appears to be working. @axelstudios please file a new issue if you're still having problems

**Comment by axelstudios** [comment]
Sorry for the delay, this looks good.
