### ISSUE TITLE
Raw data and displayed data

### ISSUE THREAD

**Issue by joncortez** [angular-ui/ng-grid#2809]
I'm pretty new to ui-grid and I've been using it to render a table of numerical values. These values would have up to 6 decimal places (ex 0.123456) but they should be displayed as a percentage with up to 2 decimal values (ex. 12.34%).

How can I display the percentage format and still let the user export the data in a .csv file in its raw format?

**Comment by c0bra** [comment]
I would use a custom cellFilter to format the display value.

**Comment by c0bra** [comment]
No response in > 2 weeks. Closing.
