### ISSUE TITLE
ipad scrolling shows empty unrendered lines untill scroll stops (alot of time)

### ISSUE THREAD

**Issue by mikila85** [angular-ui/ng-grid#2810]
when scrolling in ipad up and down and giving it a momentum of scroll it takes a lot of time for it to stop and meanwhile (can be 5+ sec of slowing down animation) you only see an empty white grid :(
tested on ipad air1, ios 7.1.2, with browsers: chrome\safari\webview.(phonegap)

also tested it here too: http://ui-grid.info/docs/#/tutorial/202_cellnav

*tried upping the virtualizationThreshold to 100-500  O.o  did not help either.

**Comment by c0bra** [comment]
Take a look at the starting "Id" of the row you're at before the scroll, and then after the scroll.

When I use emulation in Chrome and do a flick I go from row 1 to 108. That's effectively 3240px of scroll distance with one flick, in a couple seconds, in a viewport that is 400px high.

If you convert that to feet it's like looking through a 5 foot window and watching something 40 feet long fall past at 11 miles per hour. Once a feature on that 40 foot object appears into view it will be gone in 3/10ths of a second. Can your brain really register that information? In this case, could it register any of the data in those 100+ rows in 2.5 seconds?

That being said, 5+ seconds does seem kind of long, especially for the last second or two you would think that something should be renderable, but I don't have an iOS device to test on. In emulation is there is a bit of flicker but it does indeed render while scrolling. It may be down to just hardware performance.

**Comment by mikila85** [comment]
chrome emulation works perfecrt!
just in ios device, row 20-30 are blank already.

**Comment by c0bra** [comment]
So nice of you to assume that we have friends. I'll try to get my hands on an iPhone or iPad.

Telerik is completely different other than our names ended up similar.

**Comment by mikila85** [comment]
Hehe an iphone is always arround :)

Thx for the info looked really alike thought they took it and extended it (some companies leech of open-source project, who knows.)

**Comment by PaulL1** [comment]
I have a pretty old iPad (iPad 2 I think), for me on the 202 tutorial it's now OK (meaning that it's half a second or so of blank, but not many seconds).  Is that also your experience?  If so, I think that's about as good as it'll get.

**Comment by PaulL1** [comment]
Closing, no further response and appears fixed.

**Comment by ekiran** [comment]
What is solution for this issue on iOS?

**Comment by mikila85** [comment]
Nope.. No one ever fixed it. And if you scroll fast the anercia can take 5+ seconds of blank screen untill fully stopped
