### ISSUE TITLE
infinite scroll doesn't work well with rowIdentity

### ISSUE THREAD

**Issue by lvostinar** [angular-ui/ng-grid#2811]
the commit from https://github.com/angular-ui/ng-grid/issues/2535 should use rowIdentity instead of $$hashKey

**Comment by c0bra** [comment]
What does "doesn't work well" mean?

**Comment by c0bra** [comment]
You'll want to squash these 3 commits into one.

**Comment by lvostinar** [comment]
Is only one commit on different branches but we can close this one, I created a pull request.
