### ISSUE TITLE
How to set a specific width for the grid?

### ISSUE THREAD

**Issue by tarunbatta** [angular-ui/ng-grid#2817]
I have a use case where I am not setting column width, and rather setting column width by css classes.
The problem is that the grid displays fine but there is white space after the last column ends, so the grid is not able to end its width on last column.

Is there a property by which we could set the grid width as a whole or may be make it automatically have a width depending on its column widths?

**Comment by c0bra** [comment]
Give the grid a class and set its width with CSS, or use ng-style if you're doing it at runtime. You may have to resize the grid. There aren't methods exposed for this so we may want to do that.

**Comment by tarunbatta** [comment]
thanks, ng-style idea works for my case.
