### ISSUE TITLE
Header cell borders can be too short after the dynamic header height change

### ISSUE THREAD

**Issue by axelstudios** [angular-ui/ng-grid#2819]
Before:
![image](https://cloud.githubusercontent.com/assets/411466/6277153/7e17826e-b849-11e4-8d03-813c4604d557.png)

After:
![image](https://cloud.githubusercontent.com/assets/411466/6277161/849f388e-b849-11e4-8e71-78392c8d8bc1.png)

**Comment by c0bra** [comment]
Fix incoming for this today once I can get around IE9 being a pig.

**Comment by c0bra** [comment]
OK should be fixed in the latest unstable.

**Comment by axelstudios** [comment]
Looks good!
