### ISSUE TITLE
Performance with custom directive on cell

### ISSUE THREAD

**Issue by cp2587** [angular-ui/ng-grid#2820]
It is not a bug per say but i did not find anywhere else to post this, so i hope you can help me. 
I have moderate ui-grid to render (around 200 lines) but each line contains a D3js/SVG drawing encapsulated inside an angular directive that affects greatly the perfomance. If i don't set the 'virtualizationThreshold' option to a high number, i get laggy scrolling and when I do use 'virtualizationThreshold' it takes severals seconds to sort the data.
My understanding is that the directive takes too much time redrawing its element each time an user sort the grid, would you see a possible workaround ? Can the svg's be put in a cache ? (I just began using angular so i am not sure if that is a common pattern)

In any case let me thank you for your amazing job on this library

**Comment by cp2587** [comment]
Moreover when using a plain and simple ng-repeat to recreate the table, the sort is instantaneous (using orderBy). Where does the overhead comes from ? Why is ui-grid so much slower ?

**Comment by c0bra** [comment]
Define "laggy" scrolling. Do you see the same sort of lag here: http://plnkr.co/edit/jjYqORiN6yeqB94sXfIB?p=preview ? That's a grid with 10k rows and a sparkline chart on each one.

The sort on 200 lines should not be slow. Sorting on the plunker above takes maybe 500ms for me, which is a lot faster than an ng-repeat with 10k elements: http://plnkr.co/edit/kf9Tinp3YxuIBbvk7ozf?p=preview

**Comment by cp2587** [comment]
Yes I see the same flicker as the one in my application. Maybe it can be mitigated by rendering a spinner when the grid is not fully refreshed ? Your example works well in favor of ng-grid because of the size of the set but in my case, it's not obvious that i should use virtualization. The best solution for me would be to compute the html elements of every line in the grid at the beginning and only reorder these element on a sorting event. Is that possible using ui-grid ?

**Comment by c0bra** [comment]
I'm seeing very little flicker on my end, when I mouse-wheel around. What sort of device are you using? Would it be possible to get a gif or something that shows exactly the flicker you're getting?  If it's the same as mine then it's probably going to be unavoidable but imo it's not awful.

**Comment by cp2587** [comment]
Yes i agree it's not a big problem, i can live with it. But still if i could get rid of the white flash (they are particularly visible on my end when i am using the scroll bar to do a 'big' jump far ahead) by rendering a spiner instead, that would be great. 
However it is weird that the sort takes 4-5 secs when used on a set of 200 lines without virtualization. Why do you need to redraw every item when sorting ? Can you not reorder the html element in place ?
Anyway, if you don't see an obvious solution, i guess you can close this thread, you are already been very helpful

Thank you

**Comment by c0bra** [comment]
No the browser cannot reorder DOM elements in place. Re-ordering them requires re-painting and re-painting 200 elements is going to take longer than 15, or 20. Have you tried using normal virtualization and checking the speed of sorting there?

Unfortunately there's no easy way to put a spinner over the grid during "large" scrolls. We have a property that will tell you when the grid is scrolling but it would happen during ALL scroll events. To do what you're wanting you'd need to somehow measure the scroll distance, apply a threshold filter, and display a spinner if the scroll was above a certain pixel amount or number of rows, then remove it onc the scroll was done.

**Comment by cp2587** [comment]
Here is a plunker of my issue: http://plnkr.co/edit/cbND3qHtzcSqrfG24nJS?p=preview (test the sort in the ng-repeat against the one in ng-repeat)
You can see clearly the performance difference between ng-grid and plain ng-repeat when there are no virtualization activated. And it only grow worth as the number of watches / redrawing increase.

**Comment by c0bra** [comment]
It's not really a fair comparison, since the grid is vastly more complex than a simple table. If you absolutely cannot have any sort of flicker then you're probably going to want to look at going in another direction. Right now ui-grid and angular just can't do what you're wanting.

**Comment by cp2587** [comment]
Ok. Thank you for your time. One last thought, ng-repeat does not trigger any watch event when reordering while ng-grid does. Could it be possible possible to use the orderBy directive of ng-repeat with ng-grid (i really dont need any complex reordering)?

**Comment by c0bra** [comment]
Re-ordering **has** to trigger $watches, the only way your list changes order is by angular noticing that the orderBy predicate has changed during a $digest cycle.  How are you measuring whether "watch events" are being triggered?

Also, I don't know if it would work for your use case but pagination would prevent you from having to deal with flicker.

**Comment by cp2587** [comment]
I meant that a change of the orderBy does not trigger a $watch event on the directive i use to draw the svg (i have set a watch for the input-data in this directive) while in ng-repeat it does.

**Comment by cp2587** [comment]
You can close this topic. Maybe ng-gid was an overkill for my problem, anyway, i am now using http://mattiash.github.io/angular-tablesort/, maybe you can take a look and implement their sorting on your project ? The author do a in-place sort that is very efficient in combination with ng-repeat 'track by' feature.

Thanks again for all the help !
