### ISSUE TITLE
Pinned cols with virtualization having left margin

### ISSUE THREAD

**Issue by cookednoodles** [angular-ui/ng-grid#2821]
After e7bd6f26afb4dc6bc2e1ce4e9fa56d801e54fd96

It appears that restyle is adding a left margin on pins cols because the  !renderContainer.disableColumnOffset condition is no longer being checked, this is leading to the pinned col disappearing when virtualized.

This is reproducible when scrolling to the far right on http://ui-grid.info/docs/#/tutorial/203_pinning

**Comment by c0bra** [comment]
I'm not seeing any bad behavior on that tutorial. The pinned columns stay right where they are.

**Comment by cookednoodles** [comment]
This is interesting, its only appearing to happen when not at full width
![screenshot - 02202015 - 10 40 30 pm](https://cloud.githubusercontent.com/assets/226331/6309852/83cb98e0-b951-11e4-9296-1bbf05366894.png)
