### ISSUE TITLE
listening for grid events such as expandableRow.shouldRenderExpand

### ISSUE THREAD

**Issue by DaveC426913** [angular-ui/ng-grid#2823]
I am upgrading to ui-grid so that I can take advantage of the expandable rows. 

(It's better but not quite there yet. eg. expandable rows are fixed height, which does not allow for a subGrid with unknown number of rows. I've cobbled a solution that allows the height to be set on-the-fly.)

Anyway, I need to listen for the expand/collapse event in the outer grid so I can do some further processing. I cannot seem to capture this event without adding an emit in the ui-grid core code.

This is what I'm experimenting with:
ui-grid.js:
$scope.expandableRow.shouldRenderExpand = function () {
    var ret = //etc etc;
    $scope.$emit('expandMe', ret);
    return ret;
};

myController.js
$rootScope.$on('expandMe', function(e) {
    console.log(e.targetScope);
});

Unfortunately, what is happening is that shouldRenderExpand() is called on every single row each time any expand/collapse button is clicked.

Do you have a way to listen for expand/collapse row click?

**Comment by DaveC426913** [comment]
Is there at least an API documented somewhere that will allow me access to the properties of the grid so I can write my own methods?

**Comment by PaulL1** [comment]
The API is documented on the grid site: http://ui-grid.info/docs/#/api

**Comment by jpuri** [comment]
@DaveC426913 did you checked this event: rowExpandedStateChanged

**Comment by PaulL1** [comment]
Solution provided, no further comment for 3 weeks.  Assuming issue is resolved.
