### ISSUE TITLE
inputbox and filter 

### ISSUE THREAD

**Issue by lecoleco** [angular-ui/ng-grid#2824]
Hi, i'm trying to use the inputbox for generic filter, but work only at the first time!  Thanks

                    $scope.state = {};
                    $scope.setFiltro = function() {
                        $scope.state = $scope.gridApi.saveState.save();
                        angular.forEach( $scope.state.columns, function ( value, key ) {
                            if ( value.name === $scope.filtroSelecionado.name ) {
                                $scope.state.columns[key].filters.push( { term: $scope.filtro } );
                            }
                          });
                        $scope.gridApi.saveState.restore($scope, $scope.state);
                    };

**Comment by juliusakula** [comment]
It's not exactly clear what is wrong or what you're trying to achieve. could you provide a plunkr or jsfiddle maybe? Here's a plunkr to get started, from the 103 tutorial http://plnkr.co/edit/KWKtkD0XKaJcXiYbZu68?p=preview

**Comment by lecoleco** [comment]
Hello,

I changed to find another way, but still have some problems 

When use the 'option one' the selection not working good.
            - If select a row and put text that not exist the row not is any more selected.
            - If select a row and put text that exist and clear the input and put text that not exist and clear again, the row is not selected. But if put the same text with the first time, the row comes selected again.

 When use the 'option two' the height never back the same if insert a column with filter and remove the column again.

 Function reSize not doing nothing - the only away to refresh is get data again??  


http://plnkr.co/edit/1ZRXhI60RWJHUd9ZXzSZ?p=preview

**Comment by PaulL1** [comment]
Option one looks like it works OK, if you were going to use option 2 I don't know why you wouldn't just use normal filters.  Are there any problems remaining that require an issue to remain open?

**Comment by c0bra** [comment]
No response in > 2 weeks. Closing.
