### ISSUE TITLE
Your demo/grid is not working

### ISSUE THREAD

**Issue by TomZilla1** [angular-ui/ng-grid#2825]
http://puu.sh/g7rJq/7e5ed14ae3.png

And I tried your demo code, it's not working either. Please help?

**Comment by c0bra** [comment]
Please check your developer console and see if you're getting any errors. It's working here.

**Comment by TomZilla1** [comment]
Getting this error:
http://puu.sh/gbDCh/751a2a48fb.png

I'm running this code:
http://ui-grid.info/docs/#/tutorial/101_intro

**Comment by PaulL1** [comment]
The page you show in your image doesn't appear to be the tutorial code.  It's reporting a syntax error in ui-grid-unstable.css on line 5.  What code exactly are you running, and can you provide a plunker?

**Comment by TomZilla1** [comment]
http://plnkr.co/edit/wXx7tVA5zMzD1POBqxQX

**Comment by PaulL1** [comment]
You need to include the css file as a stylesheet.  The tutorials (and the ngdoc code) have an issue where it shows as a script, but if you click edit in plunker you can see it is converted to a stylesheet:

http://plnkr.co/edit/7eSPjaGTlMUQaVaf8WFT?p=preview

**Comment by TomZilla1** [comment]
Oh cool. Also, any idea why it's showing up as Korean characters? This is a pure English OS.

http://puu.sh/gd5ej/28b117541f.png

**Comment by PaulL1** [comment]
Check the font tutorial: http://ui-grid.info/docs/#/tutorial/116_fonts_and_installation

**Comment by TomZilla1** [comment]
So I do show that the ui-grid-unstable.css is referencing the font files. Where else do I need to reference it to show proper, non Korean looking symbols? Do I need to install the ui-grid font onto my Windows font folder? If that's the case then, all my users would need to install the font prior to viewing the site?

**Comment by PaulL1** [comment]
No, you need to install the font in the expected place on your web server.  If you look at your web console you'll see a load error when it tries to load the font, the place that it's looking is where you need to put the font.  It should be automatic if you installed with bower.

**Comment by TomZilla1** [comment]
Thanks for being patient with me. Here's a screen. http://puu.sh/geyby/a9f511f748.png

Anyway I can resolve this issue without installing bower? I'm not sure how to tell where my webserver is looking.

**Comment by PaulL1** [comment]
Yeah, the alternative is to download all the files - ui-grid.info/release/* - then put them onto your web server in a directory.  The standard way to do that (or at least the way my grunt setup does it) is to put all the files into your root directory /assets/*

You then change your index.html to expect these files to be in assets/* rather than in ui-grid.info/release/*.

The issue here is that the browser is blocking the fonts because they're not on the same domain as the index.html.  You don't want all your users to have to change their browser settings, so you need to move the files onto your domain instead.

**Comment by TomZilla1** [comment]
Worked. Thank you so much. Love the grid so far. Are you guys going to license it in the near future or stay on the MIT license?

**Comment by PaulL1** [comment]
I expect it will stay on the MIT license - it'd be quite hard to move off it once contributions are already licensed under it, and the intention is for it to be and remain open source.  Glad it worked for you, closing.
