### ISSUE TITLE
Footer works only with unstable version.

### ISSUE THREAD

**Issue by mmuruev** [angular-ui/ng-grid#2826]
I've been trying to get footer with agregation in my grid. Footer just not appearing. Without any errors. I've checked for rc18 version. But if I use grid-unstable from examples then footer works. But in that case it broke event fiering in other places there grid in use. Which stable version is actually supporting footer?

**Comment by mmuruev** [comment]
I've found that with lattest version ng-click="getExternalScopes().details(row.entity)" just  never invoke the controller method.

**Comment by PaulL1** [comment]
It has changed instead to appScope, refer the tutorial: http://ui-grid.info/docs/#/tutorial/305_appScope

**Comment by mmuruev** [comment]
Yep.. this change really help. But this sudden change scope invocation make an issue for find the places.. probably make sense leave this old as deprecated.

**Comment by PaulL1** [comment]
I think the issue here is resolved, closing.
