### ISSUE TITLE
hideColumn, what should be changing ?

### ISSUE THREAD

**Issue by cookednoodles** [angular-ui/ng-grid#2829]
I'm trying to persist the visibility change of cols, so when a columnVisibilityChanged event happens, I save it to the database.
After some debugging, I noticed that it was always saving visible as true.

After doing some digging, I noticed that when a column changes from the menu `$scope.hideColumn` is setting :
`$scope.col.colDef.visible = false; `

However the actual saved value is col.visible, I'm not 100% sure what the fix should be, should hideColumn be affecting just colDef, or both ?
or are changes to colDef reflected back to the visible at a later time ? (So I'd be saving too early)

I'm not 100% sure as I can't really reproduce this on the website demos.

**Comment by PaulL1** [comment]
It seems to work here: http://plnkr.co/edit/3CHTMu0SbHbq1NsHEKDj?p=preview

I just added the grid menu into the tutorial, so you can hide a column, save state, then show it again, then restore state.  It appears to hide correctly, so it must be working?

**Comment by sandeepbhasy** [comment]
Hi Paul

I am trying to save the state automatically on any user action on the ui-grid. Hence in the below event I am calling the saveState.save method.

$scope.$on('hide-menu', function (event) {
$scope.state = $scope.gridApi.saveState.save();
alert($scope.state.columns[1].visible);
});

In this case the visible value is always true.

With Regards
Sandeep B

**Comment by PaulL1** [comment]
Could you provide a plunker that demonstrates that?  Then I can look at it.

**Comment by c0bra** [comment]
No update in > 2 weeks. Closing.
