### ISSUE TITLE
Unable to get column visibility status

### ISSUE THREAD

**Issue by sandeepbhasy** [angular-ui/ng-grid#2830]
Hi

I am trying to implement saving the ui-grid state. I am using the Save State feature to get the grid state and trying to the save as user preference.

$scope.state = $scope.gridApi1.saveState.save();

The method currently does not return the correct visibility status.

Can you suggest a solution to get the visibility state of a column in UI-grid.

Thanks,

**Comment by cookednoodles** [comment]
I actually opened a ticket about this just before you did !
https://github.com/angular-ui/ng-grid/issues/2829

**Comment by sandeepbhasy** [comment]
Hi Paul

I am trying to save the state automatically on any user action on the ui-grid. Hence in the below event I am calling the savestate method.

$scope.$on('hide-menu', function (event, newColumns) {
  $scope.state = $scope.gridApi.saveState.save();
  alert($scope.state.columns[0].visible);
});

In this case the visible value is always true.

With Regards
Sandeep B
