### ISSUE TITLE
ui-Grid header Height extended

### ISSUE THREAD

**Issue by HeebaSteve** [angular-ui/ng-grid#2831]
I hope i don't copy up on another issue. I have been looking and didn't find one.

I set up a grid and my header is also pulling it's height from my grid in my css.
I am using RC19 with Angular 1.3.8

html:
div class="container"
    div ui-grid="gridOptions" class="gridStyle" /div
/div

css:
.gridStyle {
    height: 500px;
}

controller:
s.gridOptions = {
    data: 'myData',
    columnDefs: [
        { field: 'FirstName', displayName: 'First Name' },
        { field: 'LastName', displayName: 'Last Name' },
        { field: 'Phone', displayName: 'Phone' },
        { field: 'Email', displayName: 'Email' }
    ],
    enableSorting: false
};

Picture of issue:
![ui-grid issues](https://cloud.githubusercontent.com/assets/11096459/6330095/250a3898-bb3b-11e4-9df6-eac6add517a8.PNG)

any help would be appreciated.

**Comment by vedtopkar** [comment]
@HeebaSteve, did you find a solution to this problem? I am encountering it as well. Any help would be appreciated!

**Comment by HeebaSteve** [comment]
Whoever created the project I am redoing in angular did not have the !DOCTYPE html tag on the layout page.

**Comment by vedtopkar** [comment]
To anyone else that has this issue: switching to RC20 or higher seems to have fixed this problem!
