### ISSUE TITLE
Header template not working as advertised

### ISSUE THREAD

**Issue by tedhohio** [angular-ui/ng-grid#2833]
I used the cellTemplate referencing an external HTML file and everything worked fine.  When I attempted to use the headerCellTemplatereferencing an external HTML file, I got a console error that the template.replace function failed.  

However, when I cut and pasted the HTML from the external file and entered it into a javascript variable, then referenced the variable for the headerCellTemplate, it worked.

**Comment by c0bra** [comment]
What version of ui-grid as you using? Also, can you reproduce in a plunker?

I checked using this plunker and it appears to work fine: http://plnkr.co/edit/7GcnaR?p=preview

**Comment by tedhohio** [comment]
I'm using ui-grid - v3.0.0-rc.19 - 2015-02-11.  Haven't tried to reproduce
in plunker, but will try that later.  I double-checked my code and still
the reference to the external HTML still produces the template.replace
error, while the reference to a variable that contains the exact copy of
the HTML works.

  Ted

**Comment by c0bra** [comment]
Can you paste the value of your headerCellTemplate?

**Comment by tedhohio** [comment]
Here is the HTML string used for the variable:  The only difference between
it and the separate HTML file is I removed any extraneous whitespace.

var myHeader = "<a data-toggle='tooltip' data-placement='center'
title='Add New'  ng-click='grid.appScope.create()'
class='gridCellWidth glyphicon glyphicon-plus green'> </a>"

**Comment by PaulL1** [comment]
I think a plunker is probably the right way to diagnose this - could you modify Brian's plunker to illustrate the problem?

**Comment by c0bra** [comment]
@PaulL1 @tedhohio I've made a plunker here doing what ted's trying to do: http://plnkr.co/edit/aFmOtw?p=preview  Seems fine to me.

**Comment by c0bra** [comment]
No response in 2 weeks. Closing.

**Comment by ShaneF67** [comment]
I am having this issue too. It seems to effect v3 and upwards. If you check those plunkers they no longer work.
