### ISSUE TITLE
Cannot access font file

### ISSUE THREAD

**Issue by virus-warnning** [angular-ui/ng-grid#2835]
Install release 3.0.0-rc19 on localhost, then a lot of icons are broken.
There is an error message in Chrome console.

```
Font from origin 'http://ui-grid.info' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost' is therefore not allowed access.
```

I try to fix that.
Just replace index.html:15
```html
  <link rel="stylesheet" href="//ui-grid.info/release/ui-grid-unstable.min.css" />
```
as
```html
  <link rel="stylesheet" href="./release/ui-grid-unstable.min.css" />
```
then it's fixed.

Need to load font from localhost instead of remote.

**Comment by PaulL1** [comment]
I think this is a configuration problem at your end - I don't think that index.html comes from the ui-grid code.  Did you install using bower?

**Comment by c0bra** [comment]
No response in > 2 weeks. Closing.
