### ISSUE TITLE
cell nav with cellTemplate

### ISSUE THREAD

**Issue by lecoleco** [angular-ui/ng-grid#2836]
cell nav and put cellTemplate with a checkbox
get this error when navigation

TypeError: Cannot read property 'focus' of undefined
at ui-grid-unstable.js:12549
at l.$get.l.$broadcast (angular.js:14720)
at Object.module.directive.compile.pre.uiGridCtrl.cellNav.broadcastCellNav.grid.cellNav.broadcastCellNav as broadcastCellNav
at Object.module.directive.compile.pre.uiGridCtrl.cellNav.handleKeyDown (ui-grid-unstable.js:12355)
at HTMLDivElement. (ui-grid-unstable.js:12403)
at HTMLDivElement.n.event.dispatch (jquery.js:4430)
at HTMLDivElement.n.event.add.r.handle (jquery.js:4116)

**Comment by c0bra** [comment]
@lecoleco Can you paste your custom cellTemplate?

**Comment by lecoleco** [comment]
Yes, 

<div><input tabindex="-1" class="ngSelectionCheckbox" type="checkbox" ng-checked="row.selected" /></div>'

Thank you

Em 24/02/2015, à(s) 11:49, Brian Hann <notifications@github.com> escreveu:

**Comment by PaulL1** [comment]
I suspect you need to start with the default cell template - my guess would be that cellNav is trying to set focus on the element, and is looking for a cell class or similar that it can't find.

**Comment by lecoleco** [comment]
I try thank you

Em 26/02/2015, à(s) 03:51, Paul <notifications@github.com> escreveu:

**Comment by c0bra** [comment]
No response in 2 weeks. Closing.
