### ISSUE TITLE
Scrollbars disappeared 

### ISSUE THREAD

**Issue by pioneer903** [angular-ui/ng-grid#2841]
I had scrollbars before, but something happened and they are gone. 
I did not have  ```$scope.gridOptions.enableHorizontalScrollbar``` set up.
But even if i set it up to 
```
$scope.gridOptions.enableHorizontalScrollbar = uiGridConstants.scrollbars.ALWAYS;
```
, scrollbars still are not displayed.

My angular version 1.3.13
ui-grid version 3.0.0-rc.16
The reason why I use this version is that it works with angular-ui modal;
I open a modal from within ui-grid 
```
<a ng-click="getExternalScopes().open(row.entity.domain, row.entity.table_name)" >Open</a>
```
Newer versions do not work like that.

Do you have any ideas why doesn't it work or any suggestions of how to troubleshoot it?

Thanks

**Comment by PaulL1** [comment]
I would suggest using the latest rc.  When you upgrade to the latest you need to replace getExternalScopes with appScope.

**Comment by c0bra** [comment]
No response in > 2 weeks. Closing.
