### ISSUE TITLE
click event on angular UI grid cell

### ISSUE THREAD

**Issue by ctysingh** [angular-ui/ng-grid#2843]
i would like my grid cell to handle the click event & display a pop up.
for e.g if if I click empId in an employee details grid the popup modal dialog should come up.

**Comment by PaulL1** [comment]
What version are you using?  Check the tutorials, ui-grid has examples of exactly this.

**Comment by ctysingh** [comment]
UI-Grid V 3.0 with Angular ver 1.2.26 I. The closed example that i came across was handling of click event on new column cell & not the existing one.

**Comment by PaulL1** [comment]
This tutorial should cover it: http://ui-grid.info/docs/#/tutorial/305_appScope

**Comment by ctysingh** [comment]
I was referring to that sample earlier. There the click event is added to new column cell. How do i add the event to the Name column cell.
I tried add the event in first column as see in 
http://plnkr.co/edit/INecSNb3agsBhs5hMV5q?p=preview

**Comment by PaulL1** [comment]
You need to look at the default cell template, and copy all of that into your new template, plus add the ng-click.  The default template is at: https://github.com/angular-ui/ng-grid/blob/master/src/templates/ui-grid/uiGridCell.html

The amended version in your plunker is: http://plnkr.co/edit/cnWfgpHwpNmwt6Jh1LKr?p=preview

**Comment by ctysingh** [comment]
Thanks for the help & your Patience Paul. wouldn't have possible without your support.

**Comment by mnaouali** [comment]
@PaulL1 is it possible to display the btn only for the last line?
