### ISSUE TITLE
gridApi.edit.on.afterCellEdit fires a second time after initial row edit.

### ISSUE THREAD

**Issue by ddelapaz** [angular-ui/ng-grid#2844]
After the first row edit, if i wait nothing happens (as it should) if i click on the grid then scroll down (scroll wheel up) in OSX, then the `afterCellEdit` fires.

**First Edit - I'm editing Name on first Row (from `Alex` to `Dayan`)** 

![screenshot 2015-02-25 11 59 45](https://cloud.githubusercontent.com/assets/10531886/6375803/86c459d0-bce7-11e4-94d7-5adae5cc32ec.png)

**All should be done but if I scroll down, it fires again.**

![screenshot 2015-02-25 12 01 00](https://cloud.githubusercontent.com/assets/10531886/6375811/92f91808-bce7-11e4-99b0-3ea7ee3fa39e.png)

**Comment by PaulL1** [comment]
Most likely what is happening is that you have a particular cell focused, you scroll down, which triggers a lose focus (endCellEdit) on that cell.  It also selects another cell, which if you have edit on focus, will start  editing that cell.  When you scroll again, it loses focus on the second cell, and selects another cell.

The `if (newValue !== oldValue) {` check should avoid any logic running in this situation, so it shouldn't break anything.

The best fix for this would be for us to discard the focused cell upon scroll (and not select another cell).  Unfortunately we haven't been successful in doing this without having bad side effects in the code - we got problems when you selected a cell and then a scroll was triggered (perhaps by the cell being partly off the page, and then typing into it, although there were other scenarios).

What problem does this cause for you?

**Comment by ddelapaz** [comment]
Paul,

The biggest issue for me is the fact that my `newValue` still remains as `Dayan` so the `if` statement I have in place is allowing another Postback via the `saveFieldEdit`  in the screenshot examples. 

Right now I just made this hack to get around the problem:

`if (newValue !== oldValue && $scope.recentEditedValue !== newValue)`

In the above, `$scope.recentEditiedValue` is updated after every successful Edit with the new value, so when the `afterCellEdit` kicks in, it checks and sees that `recentEditedValue` is equal to `newValue`  then just returns false. 

Thanks,
Dayan

**Comment by PaulL1** [comment]
Could you provide a plunker for that?  It sounds like you're saying that the second time it fires it is showing a different newValue and oldValue, and so it runs even though it shouldn't?

We did have a problem like that in earlier versions, but if you're on rc18 or rc19 you shouldn't be getting that issue.

**Comment by ddelapaz** [comment]
No, the second time it fires shows the same as the first time it fires, which is why it gets through. If the `newValue` that was previously entered is indeed equal to the old value (the current value in the grid) then yes, the `if` statement would stop that from calling the `afterCellEdit` function. But what happens is the following.

**EmployeeName: Dayan**
 I change this to Jenny

**oldValue: Dayan**
**newValue Jenny**

Data gets Posted back, all is good.. Now I scroll and look what happens to the old and new values.

**EmployeeName: Jenny**
Since it was recently changed from Dayan...

**oldValue: Dayan**
**newValue: Jenny**

They don't change.

**Comment by c0bra** [comment]
@PaulL1 do you want to try to reproduce this one?

**Comment by PaulL1** [comment]
I believe @swalters recent changes have fixed this.  Refer this plunker: http://plnkr.co/edit/XdRX2aLEHSRMgiONRDpj?p=preview - I put a console.log in the after cell edit, and tried various flavours of editing and scrolling.  It only ever wrote the row id once.

**Comment by PaulL1** [comment]
Closing, believe this is fixed.
