### ISSUE TITLE
addRowHeaderColumn does not use a correct column id when adding a new column

### ISSUE THREAD

**Issue by yurigenin** [angular-ui/ng-grid#2847]
addRowHeaderColumn uses the following code to create a new header:

var rowHeaderCol = new GridColumn(colDef, self.rowHeaderColumns.length, self);

self.rowHeaderColumns.length is used to assign a new column id. But the self.rowHeaderColumns arrays is only updated when the column builder's promise returns result (after the $digest cycle):

self.columnBuilders[0](colDef, rowHeaderCol, self.options)
      .then(function(){
        ........
        self.rowHeaderColumns.push(rowHeaderCol);
        ........
      });

It means that calling addRowHeaderColumn more than once to create several headers will result in all of them assigned the same id which screws up the styling (at least) since css styles for columns like width are based on column ids (.ui-grid-col0, .ui-grid-col1, etc.)

**Comment by PaulL1** [comment]
Any chance you'd submit a PR with a fix?  Or alternatively provide a plunker providing an example we could work with?

**Comment by yurigenin** [comment]
Here's the fix for the `Grid.prototype.addRowHeaderColumn`:

`var rowHeaderCol = new GridColumn(colDef,` **gridUtil.nextUid()**`, self);`

instead of:

`var rowHeaderCol = new GridColumn(colDef, `**self.rowHeaderColumns.length**`, self);`

[Here is a link to a plunker](http://plnkr.co/edit/Nk8Xl4jP2JnuGLyiLB4h?p=preview)

Notice how I set the widths to 100 and 200 but it always takes the width of the first header.
