### ISSUE TITLE
Refresh after delete

### ISSUE THREAD

**Issue by jayeshanandani** [angular-ui/ng-grid#2849]
Using latest unstable version of ui grid. I have following code in my file:

```php
var index = $scope.gridOptions.data.indexOf(row.entity);
          $scope.gridOptions.data.splice(index,1);
          $scope.gridApi.core.refresh();
```

The code is fired on success from server.When I splice the content from grid it always removes the first record irrespective of which row I deleted. So in total it removes 2 row, but when you refresh it the 1st row is back.

So I was wondering , why:

1.) Refresh the grid after delete is not working.
2.) Dont know what is causing 1st row to be removed.

**Comment by PaulL1** [comment]
Are you able to provide a plunker so I can look at the code running?  It doesn't sound correct, and the tutorial that adds and removes data appears to work correctly: http://ui-grid.info/docs/#/tutorial/112_swapping_data

**Comment by jayeshanandani** [comment]
It seemed to be a code error. It is working fine on all tables.Closing this issue.

**Comment by jayeshanandani** [comment]
It seemed to be a code error. It is working fine on all tables.Closing this issue.
