### ISSUE TITLE
I have a question about how to use ajax to pagination for this grid?

### ISSUE THREAD

**Issue by az8321550** [angular-ui/ng-grid#2850]
I don't want once load all the data,but still want the panigation is normal?how to do ? please tell me

**Comment by PaulL1** [comment]
The pagination allows server requests to be triggered when the paging is activated.  Refer: http://ui-grid.info/docs/#/api/ui.grid.pagination.api:GridOptions

**Comment by az8321550** [comment]
I have a question now,how to use a method in grid,like getColumn(name)

where I should use in code?

**Comment by PaulL1** [comment]
I think you should spend some time looking through the tutorials.  I think the questions you are asking are answered there.

**Comment by az8321550** [comment]
I'm sorry,but I already read all fo the tutorials,and I not find the answer,so now I still want ask you.

**Comment by PaulL1** [comment]
Ok, can you provide a more comprehensive question.  I don't think getColumn is a method we provide in the api - where did you learn that the method should be available?

**Comment by az8321550** [comment]
Here:
ui.grid.class:Grid
http://ui-grid.info/docs/#/api/ui.grid.class:Grid

getColumn(name)

returns a grid column for the column name

Parameters
name – {string} – column name

**Comment by PaulL1** [comment]
Only the methods marked as publicApi are designed to be used outside the grid code.

http://ui-grid.info/docs/#/tutorial/311_importing_data_with_rowedit provides information on obtaining a gridApi.  Api methods can be called using that.

**Comment by az8321550** [comment]
Tks,I know! soga!!!
