### ISSUE TITLE
ui.grid.selection: add public api to enableRowHeaderSelection

### ISSUE THREAD

**Issue by scottmcdonnell** [angular-ui/ng-grid#2855]
I can toggle multiselect using the api:
`$scope.gridApi.selection.setMultiSelect(!$scope.gridApi.grid.options.multiSelect);`

but there is no way to toggle the RowHeaderSelection:
`$scope.gridApi.selection.setRowHeaderSelection(!$scope.gridApi.grid.options.enableRowHeaderSelection);`

changing the gridOptions does not work either. 
`$scope.gridApi.grid.options.enableRowHeaderSelection = false;`

**Comment by PaulL1** [comment]
At present the rowHeader isn't dynamic.  Another instance of #1819

**Comment by PaulL1** [comment]
I don't think we're planning on allowing the rowHeader for selection to come and go - you set it up front or you don't.  If you're not using the rowHeader, you can turn selection on and off dynamically, as demonstrated in the selection tutorial.

**Comment by tzhang318** [comment]
Wonder if you can allow the rowHeader to be toggleable, we are struggling to find a way to make this to work.

**Comment by Bodmoor** [comment]
You can also toggle the enableRowHeaderSelection by saving the on / off value using angular localstorage.

```
localStorageService.set('selectionState', true/false);
```

now, reload the page the grid is on and load the setting:

```
    var selectionState = localStorageService.get('selectionState');
    if (selectionState != null || selectionState != undefined) {
        gridOptions.enableRowHeaderSelection = selectionState;
    }
```

the disadvantage is of course having to reload the grid, but being able to toggle this column is great. I use it combined with the save state call, inspired by: [http://plnkr.co/edit/LAMZvOkpx6jsD4CWSz04?p=preview](url)

Also, the code samples need to be interpreted to fit your method of loading the gridOptions initially.
