### ISSUE TITLE
scrolling through repeats error

### ISSUE THREAD

**Issue by bwinchester** [angular-ui/ng-grid#2857]
I have a ui-grid that has an empty [array] when the page partial loads. The data object is updated after a service call. It has anywhere from 0 - 100s of results. When I start scrolling through the data vertically and see the scroll bar progress from 0% -100% the same data keeps being displayed. So ui-grid may start with 16 items to ng-repeat over out of the total 100 items. As I scroll, the ui-grid should be replacing the visible rows with incremental objects in the array, such as 16-32, 17-33, etc as it moves through the array. Instead, the scroll bar progresses correctly, but the data is always the first 16 items in the array. you scoll up 4 or so rows and it jumps back 4 rows of data. so its always the same 16 items, when I know there are maybe 85. Randomly, the last row item visible will display it's index (I implemented a column to visually track whats going on) and be at 50 or 85. But mostly it stays around the first 16 rows. I added watchers to the data object to report if something jenky was happening to my data object given to ui-grid options, but it's not changing. Seems internal to ui-grid's scope. 

I have even put in code breaks in the ui-grid get rows functions that calculate the next set of visible rows, and they report the correct data, such as: I should be displaying 25-42's rows.

**Comment by c0bra** [comment]
What version are you on?

**Comment by bwinchester** [comment]
I'm trying ui-grid 3.18, .19 and the very new 20 release candidate. They all seem to do it. Some other factors: its a grid with 4 columns and 100% width of the container. Im using grid-auto-resize, cellNav, both scrollbars always. There's another grid on the page, but it's using a different option object with it's own data (it displays fine but only has up to 5 rows.) 

I use ui-grid on another page, with the same configuration, different dataset with 5-200 rows just fine, and it has 30-40 columns.

    <div id="lookups" ui-grid="lookupOptions" class="grid" ui-grid-auto-resize style="width:100%;height:300px"></div>
   
    $scope.lookupOptions = {
      columnDefs: [],
      data: 'lookupData',
      enableHorizontalScrollbar: 'always',
      enableVerticalScrollbar: 'always'
    };

Since the data on all of my tables can have different columns, the tables have empty arrays [] for their columnDefs. And then when the data is loaded, the array is replaced with an on the fly array of objects with name, and optionally with cellTemplate, visible and width, depending on the dataset.

**Comment by c0bra** [comment]
'always' isn't a valid value for the enable scrollbar options, though it probably SHOULD be. The values are essentially an enum, so `uiGridConstants.scrollbars.ALWAYS` == 1 and `uiGridConstants.scrollbars.NEVER` == 0.

Trying changing 'always' to 1 and see if anything changes.

**Comment by bwinchester** [comment]
@c0bra , Thanks for the catch. However my lists/tables are still duplicate repeating

**Comment by PaulL1** [comment]
I think a plunker is probably the best bet - it isn't a behaviour I've seen before so probably hard to recreate without your specific context.

**Comment by c0bra** [comment]
@bwinchester if you manage to get a plunker going then please open another issue, as it's been almost a month since the last update.

You can just copy and paste your text from here into the new one. In the meantime I'm going to close this.
