### ISSUE TITLE
Cannot parse column width 'auto' 

### ISSUE THREAD

**Issue by masterkidan** [angular-ui/ng-grid#2858]
Hi, 
I've been using RC 20 for the last few days, and I seem to enter the following error when I set width to auto in columnDefs
Cannot parse column width 'auto' for column named A.
This is how I am setting my columndefs:
<code>
$scope.wizardOptions = {
        enablePagination:false,
        rowHeight:'auto',
        columnDefs: [
            { field: 'b', title: 'b'},
            { field: 'A', title: 'A', celltemplate: '<div ng-repeat="item in row.entity[col.field]"><div class="ui-grid-cell-contents">{{item}}<a ng-click="copy(item)" class="btn">Copy</a></div>', width: 'auto' },
        ]
    };
</code>
Here is my markup:
<code>
<div id="wizardTable" ui-grid="wizardOptions" class="table" ui-grid-auto-resize></div>
</code>

Not entirely sure if this is a bug or not.

**Comment by PaulL1** [comment]
For what reason do you think "auto" is a valid value for width?  I think we accept "*" and "**", but I haven't seen "auto" before.

**Comment by masterkidan** [comment]
https://github.com/angular-ui/ng-grid/wiki/Defining-columns

The above documentation seems to suggest that auto is allowed as an option for width.

**Comment by PaulL1** [comment]
That documentation I think is for 2.x.  It's not part of the 3.0 set.

**Comment by masterkidan** [comment]
Ah, I see, is there anything similar to auto in the newer 3.0 set?

**Comment by PaulL1** [comment]
Only "*" and "**".  There has been talk of auto-resizing columns, but I don't believe it is implemented.

**Comment by masterkidan** [comment]
Oh ok. Thanks for the info.

**Comment by parisjackson** [comment]
I'd like to chime in and say that I need this feature too. Auto sizing of long columns is a big deal.
