### ISSUE TITLE
Any tutorial in doing external filtering.

### ISSUE THREAD

**Issue by andrewvmail** [angular-ui/ng-grid#2860]
I have like 100k records and it's very slow to do it on the client.
Just wondering if there is any guide to implement external filtering.

Thanks in advance.

A

**Comment by PaulL1** [comment]
We did some work on filtering performance under #2574, and at that time I built a plunker with 320K records, which filtered acceptably.  http://plnkr.co/edit/Mp7I2yMQADMTPAETL0KD?p=preview, which still performs OK for me.

Is the performance you are getting materially different than that?

There is a tutorial on external filtering, called external filtering.  :-)  http://ui-grid.info/docs/#/tutorial/308_external_filtering

**Comment by andrewvmail** [comment]
Its pretty similar performance. Actually mine is 85K only. 
Is there something I can do to speed it up?
I think im using a version that was like 3 months ago. Did it get faster since then?

A

**Comment by PaulL1** [comment]
Short answer: yes.  The fix was done 17th Jan, so you probably need RC18 or later, I'd go with RC20 since it's most stable.

**Comment by andrewvmail** [comment]
Okay cool ill try that THanks!



—

**Comment by PaulL1** [comment]
No change for 28 days, assuming that @andrewvmail has upgraded and issue is resolved.
