### ISSUE TITLE
Templates do not support Angular directives (ng-click)

### ISSUE THREAD

**Issue by choketsu** [angular-ui/ng-grid#2864]
The solution (and corresponding plunker) mentioned at the bottom of https://github.com/angular-ui/ng-grid/issues/2141 no longer works: http://plnkr.co/edit/z0t2hdX9uSezW8gRKQOS?p=preview.

Clicking either the alert button or the checkboxes is supposed to trigger an alert() but it doesn't.

**Comment by PaulL1** [comment]
Check the appScope tutorial, the syntax has changed.

**Comment by choketsu** [comment]
Got it, thank you.
