### ISSUE TITLE
CSS height percent doesn't work

### ISSUE THREAD

**Issue by blakemcbride** [angular-ui/ng-grid#2866]
Greetings,

I am using ui-grid - v3.0.0-RC.18-7774d30

CSS:

height 500px;      works

width: 50%;         works

height: 75%;       does not work 

(Note the two height styles were not done at the same time.)

Thanks.

Blake McBride

**Comment by c0bra** [comment]
Please read this: http://ui-grid.info/docs/#/tutorial/108_hidden_grids

**Comment by PaulL1** [comment]
Response provided, no further comments, assuming issue is resolved.
