### ISSUE TITLE
Font issue

### ISSUE THREAD

**Issue by TomZilla1** [angular-ui/ng-grid#2868]
This is what yours look like:
http://puu.sh/gg16j/01dc90e113.png

However, on my machine, it looks like this:
http://puu.sh/gg1eR/20b72a8583.png

And no errors in inspection:
http://puu.sh/gg1bt/4e05aad550.png

What am I doing wrong? I don't use Bower. I'm on a Windows machine.

**Comment by PaulL1** [comment]
I don't believe that font is set by the grid - it uses your default font.  If you don't like the font on your web page then you need to change it to something else.  I presume if you put something else on that same page (e.g. a simple div) then it would use that same font?  

I think the tutorial pages are simply using the default sans-serif font.

**Comment by TomZilla1** [comment]
I thought the CSS is setting the default font is "grid-ui"?

**Comment by PaulL1** [comment]
There isn't a font called grid-ui in our distribution package.  I don't think we're using a special font, we're just using the font that is set in your application.  If we were setting to a special font then you'd have an error when your browser didn't find it?

I'm assuming you're using ui-grid, and not 2.x of ng-grid?

**Comment by TomZilla1** [comment]
Correct, UI-Grid. I see. Let me try and I will update you. PS. Why not use Glyphicons for icons?

**Comment by c0bra** [comment]
@TomZilla1 we just wanted to use the smallest subset we could so people didn't have to include a huge font in their app for icons that we weren't using.

There are plans to add shims for bootstrap, font-awesome, etc.

**Comment by PaulL1** [comment]
Resolution provided, no update for 3 weeks, assuming problem is resolved.
