### ISSUE TITLE
Column name is not capitalizing?

### ISSUE THREAD

**Issue by TomZilla1** [angular-ui/ng-grid#2872]
So I have a grid called BIN:
http://puu.sh/gg4Bk/08a69cb540.png

However, when displayed, it shows "Bin"
http://puu.sh/gg4AE/73edc5856e.png

Any thoughts on this?

**Comment by PaulL1** [comment]
You need to use displayName if you want to force a particular formatting.  Otherwise we automatically generate a displayName using default formatting (capitalise first letter of each word I think).
