### ISSUE TITLE
is multiple column sorting set in column definition supported?

### ISSUE THREAD

**Issue by mlassi** [angular-ui/ng-grid#2875]
Hi, I really like ui-grid. My understanding from looking at examples in the tutorial is that you should be able to sort by multiple columns that you define in your column definition based on the priority order you set for each column but I can only get the ui grid to sort one single column this way.

Is there a bug or is it not supported at the moment? 

I have a plnkr here: http://plnkr.co/edit/BhDUMqXXfaKcY9kwAI9v?p=preview

Thank you,
Magnus

**Comment by PaulL1** [comment]
ID is unique, if you sort by that first, then none of the other column sorts will have any effect.  Sort by age, then name, then id, you can see it works: http://plnkr.co/edit/UBmTmSQRBz1uhWYojj9o?p=preview
