### ISSUE TITLE
Issue registering multiple grids onRegisterApi

### ISSUE THREAD

**Issue by PhilBroadbent** [angular-ui/ng-grid#2879]
Hi,

I have 3 grids on a screen, with different gridOptions. I want to have access to the gridApi, so have set up the onRegisterApi callback, however, only 1 of the callbacks ever triggers.

Has anyone come across this and know how to solve it please?

**Comment by sebilozano** [comment]
How did you resolve this?

**Comment by PhilBroadbent** [comment]
I think I had made a mistake in the HTML - having the wrong gridOptions name in the ui-grid directive. Either that or wrong gridOption name elsewhere . 

If you post a code snippet I can try see what's up with yours.

**Comment by sebilozano** [comment]
I might have a different problem than you, then. I have multiple grids on a page that each have different dynamically generated columns. My problem might be how I'm manipulating gridOptions to make it dynamic. I'll post back if I think it has to do with this -- thanks.

**Comment by Sushsusmitha** [comment]
I am not able to register 2 different gridOptions(gridCustOptions,gridOptions) on the RegisterApi. 

<div  ui-grid="gridCustOptions"  class="grid ui-grid-selectable" ui-grid-pinning ui.grid.resizeColumns ui-grid-selection ui-grid-exporter ui-grid-grouping>

<div ui-grid="gridOptions" class="grid ui-grid-selectable" ui-grid-pinning ui.grid.resizeColumns ui-grid-selection  ></div>
