### ISSUE TITLE
uiGrid column sorting

### ISSUE THREAD

**Issue by mathewbeno** [angular-ui/ng-grid#2881]
I am persisting the column sort information and I am trying to set the grid sorted using the function  $scope.gridApi.grid.sortColumn($scope.gridApi.grid.columns[5], uiGridConstants.DESC, true).

But this is apparently not working. First of all I wanted to see if I am calling this function right. Is there any other way to get this sort working?

Highly appreciate your response on this matter.

Thank you,

BM

**Comment by PaulL1** [comment]
Take a look at saveState, which does exactly what you're seeking - it persists some or all of the grid state, and then reloads it on request.  You may find it easier to use that feature than roll your own, or alternatively you could look through how it persists sort.

**Comment by mathewbeno** [comment]
Finally got that working with adding the sort to the column definition.

Thank you for your response.
