### ISSUE TITLE
UI Grid remote pagination not working with data swap

### ISSUE THREAD

**Issue by boltondr** [angular-ui/ng-grid#2882]
I was successful in getting client side pagination to work with swapping data; however, I've not been able to get remote pagination to work with swapping data.  I believe this is a bug in the code, else more documentation needs to be provided to clarify how it should work.

As an example, I've combined the code examples on the Angular UI Grid page "314 Remote Pagination" and "112 Add/Delete/Swap".  When doing so you'll find that when you go to swap data it does not refresh the pagination controls on the grid.

main.css
```.grid {
  width: 600px;
}```

index.html
```
<!doctype html>
<html ng-app="app">
  <head>
    <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.2.26/angular.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.2.26/angular-touch.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.2.26/angular-animate.js"></script>
    <script src="http://ui-grid.info/docs/grunt-scripts/csv.js"></script>
    <script src="http://ui-grid.info/docs/grunt-scripts/pdfmake.js"></script>
    <script src="http://ui-grid.info/docs/grunt-scripts/vfs_fonts.js"></script>
    <script src="http://ui-grid.info/release/ui-grid-unstable.js"></script>
    <link rel="stylesheet" href="http://ui-grid.info/release/ui-grid-unstable.css" type="text/css">
    <link rel="stylesheet" href="main.css" type="text/css">
  </head>
  <body>
<div ng-controller="MainCtrl">
  <button type="button" id="swapData" class="btn btn-success" ng-click="swapData()">Swap Data</button>
  <div ui-grid="gridOptions" ui-grid-pagination class="grid"></div>
</div>
    <script src="app.js"></script>
  </body>
</html>
```


app.js
```
var app = angular.module('app', ['ngTouch', 'ui.grid', 'ui.grid.pagination']);

app.controller('MainCtrl', [
'$scope', '$http', 'uiGridConstants', function($scope, $http, uiGridConstants) {

  var paginationOptions = {
    pageNumber: 1,
    pageSize: 25,
    sort: null
  };
  
    var data2 = [
    {
      "name": "name1",
      "company": "company1",
      "gender": "male"
    },
    {
      "name": "name2",
      "company": "company2",
      "gender": "male"
    },
    {
      "name": "name3",
      "company": "company3",
      "gender": "male"
    },
    {
      "name": "name4",
      "company": "company4",
      "gender": "male"
    },
    {
      "name": "name5",
      "company": "company5",
      "gender": "male"
    },
    {
      "name": "name6",
      "company": "company6",
      "gender": "male"
    }
  ];
  
  $scope.swapData = function() {
    $scope.gridOptions.data = data2;
  };

  $scope.gridOptions = {
    paginationPageSizes: [25, 50, 75],
    paginationPageSize: 25,
    useExternalPagination: true,
    useExternalSorting: true,
    columnDefs: [
      { name: 'name' },
      { name: 'gender', enableSorting: false },
      { name: 'company', enableSorting: false }
    ],
    onRegisterApi: function(gridApi) {
      $scope.gridApi = gridApi;
      $scope.gridApi.core.on.sortChanged($scope, function(grid, sortColumns) {
        if (sortColumns.length == 0) {
          paginationOptions.sort = null;
        } else {
          paginationOptions.sort = sortColumns[0].sort.direction;
        }
        getPage();
      });
      gridApi.pagination.on.paginationChanged($scope, function (newPage, pageSize) {
        paginationOptions.pageNumber = newPage;
        paginationOptions.pageSize = pageSize;
        getPage();
      });
    }
  };

  var getPage = function() {
    var url;
    switch(paginationOptions.sort) {
      case uiGridConstants.ASC:
        url = 'https://cdn.rawgit.com/angular-ui/ui-grid.info/gh-pages/data/100_ASC.json';
        break;
      case uiGridConstants.DESC:
        url = 'https://cdn.rawgit.com/angular-ui/ui-grid.info/gh-pages/data/100_DESC.json';
        break;
      default:
        url = 'https://cdn.rawgit.com/angular-ui/ui-grid.info/gh-pages/data/100.json';
        break;
    }

    $http.get(url)
    .success(function (data) {
      $scope.gridOptions.totalItems = 100;
      var firstRow = (paginationOptions.pageNumber - 1) * paginationOptions.pageSize;
      $scope.gridOptions.data = data.slice(firstRow, firstRow + paginationOptions.pageSize);
    });
  };

  getPage();
}
]);
```

**Comment by boltondr** [comment]
As a test, I tried adding a button that when clicked it set's the grid's current page to 1.  Setting the paginationCurrentPage property doesn't do anything.

        function testSetToPage1() {
            $scope.resultsGrid.paginationCurrentPage = 1;
            safeApply($scope, null);
        }

**Comment by boltondr** [comment]
I was able to get this to work by forcing a refresh on the grid.  Doing $scope.$apply() doesn't do it.  You have to do the following...
$scope.gridOptions.totalItems = totalItems;
ui.grid.core.refresh();

**Comment by ctthang** [comment]
Maybe the totalItems of gridoptions is set after the grid's initialization so you can use:
$scope.gridApi.grid.options.totalItems = 100;
