### ISSUE TITLE
Sorting on data of Cell Template

### ISSUE THREAD

**Issue by jayeshanandani** [angular-ui/ng-grid#2883]
I have an Id field in my ui grid. The data for that comes from a custom template that prints number 1,2,3 in order. But due to some reasons I am not able to perform search or sorting on that field. Is that normal behavior?

**Comment by PaulL1** [comment]
You'd be better to insert the id field into the data than to use a custom template.  ui-grid searches and sorts on the underlying field, it doesn't know that you've changed the template to render a value in there that wasn't in the data.

**Comment by jayeshanandani** [comment]
Id can be random nos. They dont follow a particular order. So directly showing id will not be useful in some cases. From a user perspective I was thinking to have a sequential nos in first column independent of id and have a sorting on that.

**Comment by PaulL1** [comment]
So add an extra field to the data called `seq`, define it as a column `{ name: 'seq', displayName: 'ID' }`, and then they can sort/filter on it.  There is no need to include the real id in your columns at all.

**Comment by PaulL1** [comment]
For example: http://plnkr.co/edit/Qdn5oYmfPbxB1hCVLcJe?p=preview

**Comment by jayeshanandani** [comment]
Thanks Paul for suggestion. It works as expected. Closing issue.
