### ISSUE TITLE
CSV export not working

### ISSUE THREAD

**Issue by jayeshanandani** [angular-ui/ng-grid#2884]
Hi,
  I am not able to download / export data to csv. It is same on live site tutorial:
http://ui-grid.info/docs/#/tutorial/206_exporting_data
http://ui-grid.info/docs/#/tutorial/312_exporting_data_complex

PDF works fine though.

**Comment by PaulL1** [comment]
I thought I'd merged #2878, but apparently not.  I've merged it now, it fixes this issue.
