### ISSUE TITLE
Shift key start cell edit.Shift + letter lock uppercase for next letters. Looks like any key start edit mode.

### ISSUE THREAD

**Issue by Ignikot** [angular-ui/ng-grid#2885]
Version 3.0 rc20 when cell navigation and edit enabled press SHIFT start cell editing. Press shift + letter lock uppercase (looks like shift onKeyUp missing)
More over pressing any key (ctrl alt esc capslock) start edit mode.
look at http://ui-grid.info/docs/#/tutorial/205_row_editable

**Comment by PaulL1** [comment]
1.  Yes, it looks like any key including shift starts edit.  It's not clear to me that's a bug v's expected behaviour.  What problem does it create?

2.  When I press shift+a it puts in an upper case A, but subsequent letters were all lower case.  Is there another way to reproduce the problem?

**Comment by Ignikot** [comment]
Problem with uppercase reproduced in Firefox only. Firefox 36.0.1 Windows 64
To reproduce:
go http://ui-grid.info/docs/#/tutorial/205_row_editable - click table second column cell. Press esc to cancel edit. Press "shift-A" and all next letters will be uppercase.

**Comment by swalters** [comment]
It's a bug.  I'm trying to fix it today

**Comment by swalters** [comment]
https://github.com/angular-ui/ng-grid/commit/025c89397184ba44d65b7ad457546538e0cb3f22
