### ISSUE TITLE
Bug:  Grid.prototype.redrawInPlace

### ISSUE THREAD

**Issue by jmmartinez84** [angular-ui/ng-grid#2889]
This issue hide first column when I add - remove an item.
This code:
    <pre>if (rowsAdded) {
        container.adjustRows(container.prevScrollTop, null);
        container.adjustColumns(<strong>container.prevScrollTop</strong>, null);
      }</pre>
Should be:
     <pre>if (rowsAdded) {
        container.adjustRows(container.prevScrollTop, null);
        container.adjustColumns(<strong>container.prevScrollLeft</strong>, null);
      }</pre>

**Comment by PaulL1** [comment]
Any chance you could do a PR for this - perhaps referring to the first timers guide if you need to?  Changes are much more likely to get merged if submitted as a PR.

**Comment by PaulL1** [comment]
I've merged the suggested code, thanks and closing.
