### ISSUE TITLE
Bug GridRenderContainer.prototype.adjustScrollVertical

### ISSUE THREAD

**Issue by jmmartinez84** [angular-ui/ng-grid#2890]
This code:
    <pre>if (typeof(scrollTop) === 'undefined' || scrollTop === undefined || scrollTop === null) {
      scrollTop = (this.getCanvasHeight() - <strong>this.getCanvasWidth())</strong> * scrollPercentage;
    }</pre>
Should be:
     <pre> if (typeof(scrollTop) === 'undefined' || scrollTop === undefined || scrollTop === null) {
      scrollTop = (this.getCanvasHeight() - <strong>this.getViewportHeight())</strong> * scrollPercentage;
    }</pre>

**Comment by PaulL1** [comment]
Any chance you could do a PR for this - perhaps referring to the first timers guide if you need to?  Changes are much more likely to get merged if submitted as a PR.

**Comment by PaulL1** [comment]
Closing - the changes were merged.
