### ISSUE TITLE
Moving col incorrectly positioned on IE

### ISSUE THREAD

**Issue by cookednoodles** [angular-ui/ng-grid#2894]
Using the [column_moving demo](http://ui-grid.info/docs/#/tutorial/310_column_moving) on IE, 
A col header being dragged gets positioned below everything else.

![movecol](https://cloud.githubusercontent.com/assets/226331/6464457/958e2d24-c1ba-11e4-91bf-bcf7a45515ee.png)

**Comment by PaulL1** [comment]
@jpuri, have you seen this behaviour before?

**Comment by jpuri** [comment]
Hey @PaulL1 ,

I will check this soon.
