### ISSUE TITLE
RC20 Cell nav- Tab no longer working when combined with ui.grid.edit and editOnFocus

### ISSUE THREAD

**Issue by bringking** [angular-ui/ng-grid#2898]
Using the RC20 release, the cell nav feature seems to no longer work with ui.grid.edit and editOnFocus. The enter keys works to go to the next row, but tab doesn't take you to the next column. Plunkr here- 

http://plnkr.co/edit/nLeSBvb9IF9y0Hixn8SD?p=preview

**Comment by rplotkin** [comment]
I am experiencing this as well. Tab appears to end the edit.
301_editableOnFocus (in the tutorial) says "See api docs for default navigation keys and how you can override," but the api docs don't seem to have anything on default navigation keys.
I believe it must be broken around here
(near line 13372, $elm.on('keydown', function (evt), in module.directive('uiGridEditor')
at line 13402, it has a comment saying "Pass the keydown event off to the cellNav service, if it exists."
Either it is not passed off to cellNav, or cellNav is doing things wrong.

**Comment by rplotkin** [comment]
found the bug (not sure how to fix), but hope this helps whoever picks up the ticket:
in
uiGridCtrl.cellNav.handleKeyDown
at line 12343
rowCol.row === lastRowCol.row
is evaluation to true, even though it is not in fact the lastRowCol.row in the grid.

**Comment by nitescuc** [comment]
I also experience this but on numeric fields. Text fields behave normally.

**Comment by PaulL1** [comment]
I can also recreate this on http://ui-grid.info/docs/#/tutorial/301_editableOnFocus.

**Comment by PaulL1** [comment]
This appears to have been introduced in aabcd4da564391296d182d78415ab51f9853df64 by @c0bra.  To be fair, whilst tabbing was working before this, it wasn't allowing editOnFocus, which seems to have been broken in or around 232a0a004299a5d4b5cbb37aa7fad456cd93957a by @swalters.  

I'm marking as hi-pri, but don't have time to fix this today.
