### ISSUE TITLE
Transfer data from 1 grid to another grid

### ISSUE THREAD

**Issue by aksharak** [angular-ui/ng-grid#2903]
Hi,
I have a grid with 3 columns. On click of any row in that grid the entire row data should be transferred to the 2nd grid below as columns. For example if i have columns as "Name , City , Country" in the 1st grid on click of the row the below grid will have only 2 columns as "Data, value". The 2nd Grid consists of 3 rows with 1st row Name, 2nd row City, 3rd row Country. 

Am able to achieve the above, however have 2 issues.
Issue #1: The data transferred to the grid 2 is not visible in the grid. how ever on click of the row of 2nd grid if i put an alert am able to see the data in the alert but not in the grid.

Issue #2: When i click on the grid 1 row the entire row data is transferred to grid 2 however data is not visible. Now i click on another row in grid 1 the data of that row gets appended to the Grid 2. I want it to  show only the data of the row selected and not append it.

How to achieve this? have shared the plunkr link am using below 

plunkr: http://plnkr.co/edit/qiUwrzylXOV4pRqNyUq5?p=preview

**Comment by PaulL1** [comment]
The problem is the code that you're using to create the key-value pairs - it's creating an array not an object.  Try this instead: http://plnkr.co/edit/eehYJIB5A3eiuVutbl1c?p=preview

**Comment by aksharak** [comment]
Bingo.. That solved the problem. Thanks Paul.

**Comment by DLN-India** [comment]
@PaulL1 the plunk seems broken. The grid is empty, can you take a look?
