### ISSUE TITLE
issue in using ui grid in custom directive

### ISSUE THREAD

**Issue by smart987** [angular-ui/ng-grid#2904]
Hi, I am trying to use ui grid in custom directive. Please find my plunker http://plnkr.co/edit/YV5GrvTWKwwQKbIZuxRB?p=preview. The layout is appearing but the actual data is missing off.

**Comment by c0bra** [comment]
Check your console; your columnDefs are being created incorrectly. They look like this:

```javascript
columnDefs: {
    month6: "07-14",
    month7: "08-14",
    month8: "09-14",
    month9: "10-14",
    month10: "11-14",
    month11: "12-14"
}
```

**Comment by smart987** [comment]
Hi c0bra, I am in the process of migrating the ng grid to ui grid. I am using the same example suggested by PaulL1. I have taken the example from https://github.com/angular-ui/ng-grid/issues/2458 and the plunker given by PaulL1 at http://plnkr.co/edit/2UouUZuChllyYcQchoBK?p=preview. In Ng Grid it is perfectly working fine only when in Ui grid I am facing the problem.

**Comment by nailaandleeb** [comment]
m totally new to ui-grid n included grid libraries to my index.html file but it isn't working offline despite of i have downloaded libraries from links given in example of github.i just want to know is it necessary to be online while working with ui-grid?

**Comment by PaulL1** [comment]
No, you don't need to be online.

Normally you would install using bower.  If you don't want to do that for whatever reason, then you would download the release files from ui-grid.info/release/*, and put them into an appropriate directory on your web server, and then change your code to reference them (perhaps in index.html).

The most likely problem is that somewhere in your application you're still referring to ui-grid.info, notwithstanding that you've copied the files locally.

**Comment by smart987** [comment]
PaulL1, is it possible to represent the dynamic model values using ui grid similar to the one https://github.com/angular-ui/ng-grid/issues/2458? If yes, could you please provide some working example code using ui grid ?

**Comment by PaulL1** [comment]
The syntax is very similar to ng-grid, and a lot of what you need is in the tutorials.  I'd suggest you have a go, and then if you have problems that the tutorials don't provide answers to, create a plunker for that specific issue.

**Comment by smart987** [comment]
Thanks PaulL1, please see the plunker http://plnkr.co/edit/JFzTKeXl49gjAV5gNNFl?p=preview. Even though for the first time it is displaying  but when I shift from ui grid 1 to ui grid 2 , ui grid is not refreshing with latest data and vice versa. Any fix for this please ...

**Comment by PaulL1** [comment]
I have no idea what it is that you want it to do that it's not doing - I think you're assuming that we have some idea what your application is supposed to do!  When I click create grid 1 it creates it, when I click create grid 2 it creates it (although it's way down the page and I have to scroll to see it).

**Comment by smart987** [comment]
Sorry PaulL1, for my lack of clarification in expressing the issue. When I click ui grid2, I am expecting ui grid1 to be totally unloaded (clearoff ) from the screen and only grid 2 should be compiled. When I click grid2, you can see my template ("<div class= \"chartsDiv\"> <div class=\"gridStyle\" ui-grid=\"gridOptions2\" ui-grid-grouping ui-grid-pinning ></div> </div>"), the template contains only gridOption2 but still the first grid remaining as it is. So when I click grid2, the grid1 should be replaced with grid2. There should not be any grid1 on the screen. How can I clear off that existing grid1?

**Comment by PaulL1** [comment]
The problem is your custom directive.  You are appending your new template, but not removing the old element, so now you have both elements.  That's not really a grid thing, that's an angular/jquery thing.

**Comment by smart987** [comment]
The following solved the issue, thanks.
  parent.html('').append(content);
