### ISSUE TITLE
Sorting ISO dates is not supported

### ISSUE THREAD

**Issue by novice3030** [angular-ui/ng-grid#2905]
RowSorter.SortDate does not support ISO format
This is a major issue if you system is using ISO date format and not JS date

**Comment by cookednoodles** [comment]
ISO dates aren't really dates, they are just strings.
You could parse them into dates before giving them to ui-grid, or do a custom sorter that parses them.

**Comment by PaulL1** [comment]
@novice3030: what is it that you'd want here?  I think the suggestion of a custom sorter makes sense - the sorters that are provided in the grid are reasonably basic.

**Comment by PaulL1** [comment]
Closing: solution proposed that should resolve the issue, no further comments for 2 weeks, assuming solution has resolved issue.
