### ISSUE TITLE
filtering outside of grid

### ISSUE THREAD

**Issue by bradrice** [angular-ui/ng-grid#2908]
I finally figured out how to pass in filters to filter the grid. In most cases it is just passing an object with the field values to filter by. I couldn't figure out how to do regex so I had to manipulate the data outside of the gridOptions and pass in the data when I needed to do that.

http://www.uakron.edu/academics_majors/class-search/index.dot#/class-search/

**Comment by PaulL1** [comment]
It's not clear to me what the issue is here.  Is there something in particular you wanted us to do?

**Comment by thomas-koch-comsolit** [comment]
@PaulL1 I think the question becomes clear if you look at the page (and wait half a minute for the json data to load).

We also need to filter our grids on data that is not shown in any column. Example:

Gender: Male | Female | All

Name   |   Prename |   Phone | Class |
------ | ---------| -------| ------
Pop    | Anna     | 234    | 3a   |
Meyer  | Klaus    | 5432   | 1b   |

In the above case 'Gender' is not a column in the grid but one can filter the grid on gender. I think this use case should be supported and documented.

**Comment by bradrice** [comment]
I was just mentioning that it is possible to filter using internal filtering from outside form fields. However, I don't find much in documentation to show how to do it. The reason I had to filter the json itself instead of an internal filter for the Career field was I couldn't figure out regex filtering. Undergraduate and Graduate would return all records when you select Undergraduate. I was just suggesting some better explanation in the manual. This is a very helpful angular library and I'm glad for the project.

**Comment by PaulL1** [comment]
Does the tutorial not provide sufficient information?  http://ui-grid.info/docs/#/tutorial/103_filtering

Or are you using 2.x?

**Comment by PaulL1** [comment]
OK, I've seen the request before for filtering or sorting on hidden columns, I can take a look at that.

**Comment by PaulL1** [comment]
I believe that we now support filtering and sorting on hidden columns, although of course you must set the filters/sort criteria programatically.  Can someone confirm whether there is any remaining issue here?

**Comment by c0bra** [comment]
No response in > 2 weeks. Closing.
