### ISSUE TITLE
Sort Icons Not Displaying Correctly

### ISSUE THREAD

**Issue by Emadof** [angular-ui/ng-grid#2910]
I've added the ui-grid-unstable.js/css and the font files ui-grid.svg/ttf/woff/eot from the RC 20 release, when I enabled sorting the acs/desc sorting icons appear as symbols and not the up/down  chevrons as in the examples.  What am I doing wrong?
![image](https://cloud.githubusercontent.com/assets/11318739/6490465/c190ec1e-c263-11e4-92d9-63f9b89b758c.png)
Thanks.

**Comment by PaulL1** [comment]
It's almost certainly something wrong in the way you've set up your fonts.  http://ui-grid.info/docs/#/tutorial/116_fonts_and_installation

Usually you'll get an error in your javascript console or http requests saying that the browser failed to retrieve the fonts.  That'll tell you where your application is expecting them to be stored.

**Comment by Emadof** [comment]
Yes it was my setup, thanks for pointing that out.

This is a Visual Studio project and somehow (possibly through NuGet) the font files ended up in a different directory the css couldn't access.

**Comment by c0bra** [comment]
Glad you got it solved!

**Comment by Kusk01** [comment]
I have some different use case for this issue.
I am using angular ui grid 3.1.1 version.

These font are perfectly working fine in chrome and firefox but in IE first time when page loads, It's showing the sort icon perfectly but when i refresh the page then its again start showing me the the japani character. please help 


Thanks
Kusum

**Comment by dannymockaitis** [comment]
I don't believe webpack is supported yet. Has anyone figured out how to make these fonts show up in webpack?
