### ISSUE TITLE
footerTemplate not working

### ISSUE THREAD

**Issue by carbunash** [angular-ui/ng-grid#2916]
This is regarding the ui-grid footerTemplate. I tried entering html content (a div with some text) in a string, I've also tried adding a .html file name in the string and even the ID of a rendered div, but none of them seem to work. 
It also wasn't clear for me if I need to enable showGridFooter for this or not, so I tried both, but the footerTemplate is either not shown at all, or if I set showGridFooter to true, it  shows the default footer (total lines in the grid). 
Am I doing something wrong? 

Thanks :)

**Comment by Chyzwar** [comment]
You can change template for footerTemplate. I have:

```javascript
 $scope.gridOptions.footerTemplate = myGridOptions.footerCreate('profile.campaign.create', 'Create Campaign');
```

I have service that return footer collumn template:
```javascript
        this.footerCreate = function (createLink, linkLabel) {
            return '<div class = "ui-grid-bottom-panel"' +
                'style = "text-align: right" >' +
                '<a ui-sref="' + createLink + '">' +
                '<button type="button" class="btn btn-success btn-tarzan">' + linkLabel + '</button>' +
                '</a>' +
                '</div>';
        };
```
In grid options I have    
showColumnFooter: true

**Comment by rupampatel2006** [comment]
@PaulL1 Hi Paul, It has stopped working for sure. I see many bugs created on footer cell template.

I have a custom template as:


   

    var footerCellDescTempelate = '<div class="ui-grid-cell-contents" >Total</div>' +
            '<div class="ui-grid-cell-contents" ng-if="grid.appScope.searchResults.postDatedAmountTotal "> Post Dated Total </div>' +
            '<div class="ui-grid-cell-contents" ng-if="grid.appScope.searchResults.eftAmountTotal" > Eft Total </div>' +
            '<div class="ui-grid-cell-contents" ng-if="grid.appScope.searchResults.manualAmountTotal" > Manual Total </div>' +
            '<div class="ui-grid-cell-contents" ng-if="grid.appScope.searchResults.voidAmountTotal" > Void Total </div>' +
            '<div class="ui-grid-cell-contents" ng-if="grid.appScope.searchResults.outstandingAmountTotal" > Outstanding Total </div>';


Above code was working earlier and now it doesn't. It shows only one cell and is not expanding.

**Comment by rupampatel2006** [comment]
Expected result:

![image](https://cloud.githubusercontent.com/assets/5253675/6559962/d5ac259a-c65c-11e4-943e-e9608ac332b3.png)

**Comment by PaulL1** [comment]
I'm not sure that "I see many bugs created on footer cell template" means that it's stopped working.  Could you perhaps provide a plunker, and explain when it was that it worked, and what it was that changed that made it stop working?

**Comment by carbunash** [comment]
Ok, so if I understand this right, the footerTemplate is actually a custom column footer, rather than a grid footer, right? If someone could confirm that, this could be closed.

**Comment by rupampatel2006** [comment]
yes it is custom column footer which gets hidden due to some css changes happened recently. Hight remains fixed and doesn't expand any-more. @PaulL1: Fix is very small in css if you can add it.    

.ui-grid-footer-panel {
height: auto !important;
}

**Comment by PaulL1** [comment]
I'm not sure if we expected the footer to auto-size, and I'm not a big fan of using !important to force things.  But I see the use case, so I'll leave this open.

**Comment by rupampatel2006** [comment]
@PaulL1 : Yeaterday i was trying footerTemplate and is not working at all instead gridFooterTemplate works!

**Comment by rupampatel2006** [comment]
@PaulL1  gridFooterTemplate property  is completely misses out from documentation/GridOptions  API.
