### ISSUE TITLE
Excel Type Filtering

### ISSUE THREAD

**Issue by sachinny21** [angular-ui/ng-grid#2919]
This is not an issue, but rather an enhancement.  I wasn't sure if something like this is in the works but I am wondering if it is possible to create a feature where we can do filtering on columns based on a dropdown selection of what values are available in that column, rather than the user having to type it out. Basically how Excel Table Filtering works. 

I wasn't able to find anything by doing some searches on Git so I figured I would ask before I try to implement on my own rather than help contribute to something that might already be started.

**Comment by PaulL1** [comment]
I think #2918 would enable you to add this function.

**Comment by PaulL1** [comment]
Implemented http://ui-grid.info/docs/#/tutorial/306_custom_filters, via #3262

**Comment by tggagne** [comment]
This is precisely the feature I'm looking for--having Excel-like drop-downs on a column with just the values in it.  I checked-out the documentation referenced above but didn't read anything about the drop-downs.  Is it something that must be enabled via a setting, or is it a hook for developers to implement their own dropdowns?

**Comment by PaulL1** [comment]
You enable it by changing the filter template (from memory), and you have to actually populate the dropdown yourself.

**Comment by johncja** [comment]
@sachinny21 Just to clarify, does you mean something like this?

![1ag-grid](https://cloud.githubusercontent.com/assets/18004961/13969654/47721c62-f095-11e5-80b6-d5727b6dbb15.png)
