### ISSUE TITLE
Select first row

### ISSUE THREAD

**Issue by lecoleco** [angular-ui/ng-grid#2920]
How select the first row after controller read.
ui grid

**Comment by PaulL1** [comment]
You need to get the gridApi object (refer the tutorials), put in a timer to wait for rendering complete, then call the selection API to select the first row.

**Comment by lecoleco** [comment]
I tried everything, the only way that works is. 
          
$scope.$watchCollection('gridOptions.data[0]', function() {
                    if ( angular.isDefined($scope.gridApi) ) {
                        $scope.gridApi.selection.selectRow($scope.gridOptions.data[0]);
                    }
                });

It's a good idea?

**Comment by PaulL1** [comment]
That can't be the only way that works because I've seen it done before.  In general we avoid watches if possible, and watching the data seems a bad idea.  The data is being set by your code - surely you know when it's been set?  Is it coming from an http request?  In which case, you should wait on the promise from the http request and then do it.

**Comment by lecoleco** [comment]
Is it coming from an http request?  Yes

//this is a request to populate a grid

                    return reembolsoServico
                        .getDataBD( $scope.formulario )
                        .then(
                            function onResult( response ) {
                                $scope.gridOptions.data = response.data.result;
                                if ( $scope.gridOptions.data === null ) {
                                    $scope.gridOptions.data = [];
                                }

                                //put here?

                            }
                    );
if not, could send me an example?

**Comment by PaulL1** [comment]
Yes, that should work.  It's basically the same as what you're doing, but instead of watching for you to change the data, you're doing it when you change the data.  I'd put it inside the if condition though.

**Comment by lecoleco** [comment]
I tried this and not work.

                    .then(
                            function onResult( response ) {
                                $scope.gridOptions.data = response.data.result;
                                if ( $scope.gridOptions.data === null ) {
                                    $scope.gridOptions.data = [];
                                }
                                $scope.gridApi.selection.selectRow($scope.gridOptions.data[0]);
                            },

**Comment by PaulL1** [comment]
Add a timeout: http://plnkr.co/edit/zMiTJk4khzSjEBKmreCh?p=preview

**Comment by PaulL1** [comment]
I've added to the selection tutorial under #2938
