### ISSUE TITLE
Default Sorting direction should be customizable

### ISSUE THREAD

**Issue by sarbjeet65** [angular-ui/ng-grid#2923]
Hi,

There are number of columns in Grid. I have requirement to sort columns in different order. For Example :when user click on any column first time. But right now it seems that when user click on any UI-Grid  column then by default the uiGridConstants.ASC icon displayed. I need uiGridConstants.DESC icon. Please advice is this possible in current release. Can i change dynamically the sorting icon based on user action for particular column.

Thanks

**Comment by c0bra** [comment]
@sarbjeet65 do you need to sort by descending first, when the user clicks, rather than ascending first?  Or do you need to show the DESC icon when the user is sorting ascending, and vice-versa?

**Comment by PaulL1** [comment]
Information sought and no response for nearly a month.  Assuming another solution has been found.
