### ISSUE TITLE
Unable to send emails

### ISSUE THREAD

**Issue by deusprimus** [angular-ui/ng-grid#2925]
Error on trying to send an email to the Pods Santa Barbara list. 

![image](https://cloud.githubusercontent.com/assets/6808346/6517160/965c90da-c398-11e4-816b-3d8db90f9781.png)

Browser: Chrome 40
OS: Windows 7

**Comment by PaulL1** [comment]
Could you re-read your issue, then think about what it is that you want us to do?

**Comment by deusprimus** [comment]
This is what happens when you have two github tabs open at the same time. I posted this issue to the wrong repository. Sorry about that!

**Comment by PaulL1** [comment]
Ah, that explains it.  I thought it looked unusual.  :-)
