### ISSUE TITLE
Dropdown Menu in addRowHeaderColumn

### ISSUE THREAD

**Issue by rhllor** [angular-ui/ng-grid#2931]
Hi, 
Is possibile add Row Header Column with dropdown menu o contex-menu?
I need to group several features

**Comment by PaulL1** [comment]
I'm not sure exactly what it is that you're asking for here.  Where would the dropdown menu appear?

**Comment by rhllor** [comment]
Hi, 
I need the dropdown menu in row header as check for select row.

**Comment by PaulL1** [comment]
I think you could do this with a combination of `addRowHeader` and using a custom cellTemplate on that column.

**Comment by PaulL1** [comment]
No further comment for over a month, solution provided that probably resolves the issue.  Closing, please re-raise if there is a reliable recreate or more information.
