### ISSUE TITLE
Need a download column

### ISSUE THREAD

**Issue by blakemcbride** [angular-ui/ng-grid#2933]
Greetings,

I have a grid where each row uses several columns to describes a unique file.  What I would like is to have a first column that had a "download" icon.  When the user presses that icon, an application specific function (of my creation) will execute causing the file to download.  Of course that function will need to know which row they clicked.  

I am familiar with ui-grid-selection but don't know how to make that do what I want.  I need to be able to change the icon used and attach a function to it.  

I don't want to use a grid-menu because it is a little less clear from the users perspective.

Any help would sure be appreciated.

Thanks.

Blake McBride

**Comment by swalters** [comment]
You need a custom cell template for your download column. See http://ui-grid.info/docs/#/tutorial/305_appScope

**Comment by thomas-koch-comsolit** [comment]
We use directives for this use case, e.g.:

```JavaScript
  cellTemplate: '<my-download-button />'
```

We still use ng-grid 2.x, but it should work the same in 3.x I believe.

**Comment by PaulL1** [comment]
Solution provided, no response for some time, assuming issue is resolved.
