### ISSUE TITLE
My Grid design is not not looks proper

### ISSUE THREAD

**Issue by dilip-borad** [angular-ui/ng-grid#2942]
![grid-looks-bad](https://cloud.githubusercontent.com/assets/3114028/6548510/66eeca26-c621-11e4-97eb-e9543f4923bc.png)

Check the above image first.

All things looks proper, but first time when it's loads it's looks like above image and when i'm resize the screen then it's looks is automatically looks good

**Comment by PaulL1** [comment]
That looks to me like a grid in a modal.  You might want to refer to http://ui-grid.info/docs/#/tutorial/110_grid_in_modal.  More importantly, it looks like a bootstrap modal, and with the bootstrap modal it does an animation as it draws - so at the point the grid initialises the available space is less than once the animation finishes.  You can address this by calling `handleWindowResize` (refer the api documentation).

**Comment by dilip-borad** [comment]
Thanks for information but this is not my solution because when i was used it outside the modal that time this same issue is occurs.

Is there any way to re-create/re-size grid after load it successfully, I think it's works for me.

**Comment by dilip-borad** [comment]
Issue is solved out by using ng-if as like 
    <div ui-grid="gridOptions" ui-grid-selection class="grid" ng-if="gridOptions.data.length>0"></div>

Use reference of this issue https://github.com/angular-ui/ng-grid/issues/855

Thanks.
