### ISSUE TITLE
Moveable: 3 unit tests are commented out

### ISSUE THREAD

**Issue by PaulL1** [angular-ui/ng-grid#2945]
There are 3 unit tests in moveable that are marked `xit`, and therefore aren't running.  When uncommented they fail.  These should be fixed.

@jpuri, do you know why these were commented out?

**Comment by jpuri** [comment]
Hey @paul,

We got these commented as they were failing for strange reasons. I will see if I can fix some of them, or else if they do not make sense I will remove them.

**Comment by jpuri** [comment]
Hi @PaulL1 ,

This can be closed now.
