### ISSUE TITLE
Focusing to an individual cell for editing

### ISSUE THREAD

**Issue by feralanPaladin** [angular-ui/ng-grid#2955]
Hi,

Using grid.$viewport.scrollTop() I can manage to scroll to any row item but I also need to focus on an individual cell (ex. row number 25, column number 3) to start editing (each column has its own cell templates for editing) 
Will u please suggest me a method to handle this situation.

Thanks in advance.

**Comment by PaulL1** [comment]
Use cellNav, and use the scrollToFocus method.

**Comment by feralanPaladin** [comment]
Here is a plunker for this situation : http://plnkr.co/edit/xImo5U
I am using ng-grid and i do not know how i can manage to use cellNav.
Will you please show this with an example

**Comment by PaulL1** [comment]
You also need the edit feature and to set the editOnFocus property.  Look at http://ui-grid.info/docs/#/tutorial/309_editable_with_cellnav

If you're stuck with 2.x, then you can't use cellNav, and I'm not familiar enough with 2.x to give you alternative suggestions.

**Comment by feralanPaladin** [comment]
Thank you,
I am currently upgrading to 3.x
