### ISSUE TITLE
row index

### ISSUE THREAD

**Issue by pjlasl** [angular-ui/ng-grid#2958]
I am trying to display the row index in a column and I found an example that works using ng-grid, but it produces the same number "1" for every row it adds to the grid.

Using the ng-grid, I could write the following:
{name: 'ID', field: '', displayName: 'Row Number', cellTemplate: '<div>{{row.rowIndex + 1}}</div>'}

The ui-grid does not produce the same result. How can I get the same behaviour with the ui-grid?

**Comment by PaulL1** [comment]
When you say you are trying to display the row index, do you mean you want the actual row index, or that you want to display a sequential id in all your rows?

If the latter, then you can do it by just adding a counter column to your data:
```
  angular.forEach($scope.myData, function( row, index){
    row.sequence = index;
  });
```

If you want to show the index of the row within the grid internals, then it depends on which internal you want.  You can get the index of the row within grid.rows, which would show the row as it stands in the original rows list (not filtered nor sorted), or the index of the row within grid.renderContainers.body.visibleRowCache (filtered and sorted), or the render index of the row within the currently displayed rows (given virtualisation, this is generally a particularly useless number).

If you're OK that whenever someone sorts or filters then the numbers will change, then you could do it with a cellTemplate, which would be something like:
```
  cellTemplate: '<div>{{row.grid.renderContainers.body.visibleRowsCache.indexOf(row)}}</div>
```

**Comment by pjlasl** [comment]
Thank you for the reply. I am looking to add a sequential number (1,2,3...) to a column in the grid. 
I am very new to this control so any detail you could provide would be great. I tried to use the following (in my columnDefs) but all i get is an empty cell

```javascript
{name: 'lineNbr', displayName: '',width: 30, cellTemplate: '<div>{{row.grid.renderContainers.body.visibleRowsCache.indexOf(row)}}</div>' },
```

**Comment by pjlasl** [comment]
This was not meant to be closed....

**Comment by PaulL1** [comment]
Try this: http://plnkr.co/edit/9QbQCqTSz8aluh9n62Hl?p=preview

**Comment by pjlasl** [comment]
Thanks Paul. That worked better! Appreciate the quick responses. I really like this grid and it has been fun learning how it works!

**Comment by Awakening-j** [comment]
@PaulL1 The row index working for me at cellTemplate, but I wonder will it cause performance issue? It is so complex to get index  
>  {cellTemplate: '&lt;div&gt;{{row.grid.renderContainers.body.visibleRowsCache.indexOf(row)}}&lt;/div&gt;' },

**Comment by PaulL1** [comment]
Personally I wouldn't do that.  I'd create an attribute on my data that I called id, and I'd put a number in it.  But that may be because I don't have a use case where the number changes if people sort (and actually, since my data is all persisted to the server, I have my server give me a unique id that persists across visits to the application, which I think is much more useful).

But it will work, and it shouldn't impose any significant overhead beyond that we already have by having a binding.  It's only doing it for the number of rows visible - so perhaps 10-15 calls to indexOf.

**Comment by Awakening-j** [comment]
@PaulL1 ok, thanks, Maybe I will server side unique id too

**Comment by vaimeo** [comment]
use {{rowRenderIndex}}
