### ISSUE TITLE
Expandable Grid causes issues with pinning

### ISSUE THREAD

**Issue by jayeshanandani** [angular-ui/ng-grid#2964]
Following is link to plunkr:

http://plnkr.co/edit/6DeFYsCpMswwskXfV99P?p=preview

When you show/hide column Id which in pinned by default you will observer that table layout changes entirely and table shifts down. This is happning due to use of module ui.grid.expandable in it. 

If you take out expandable module out of app.js it will just work fine.

**Comment by c0bra** [comment]
I believe this is the same issue as #2930.
