### ISSUE TITLE
TAB key does not work properly within a editableCellTemplate

### ISSUE THREAD

**Issue by feralanPaladin** [angular-ui/ng-grid#2966]
Hi,

With default editing functionality, TAB key is working great while cellNav service is injected to the grid. But as you can see from the below plunk, TAB key is not working as expected while using editableCellTemplates.

Plunk: http://plnkr.co/edit/Ld5xOX41km03zaIqd2nc?p=preview

Yours sincerely.

**Comment by swalters** [comment]
This is also in 401 tutorial

**Comment by PaulL1** [comment]
Duplicate of #2898
