### ISSUE TITLE
native ui-grid "Export All" feature and external/server-side pagination?

### ISSUE THREAD

**Issue by Shanna7463** [angular-ui/ng-grid#2967]
Is it possible to use native ui-grid "Export All" feature with external/server-side pagination?  I know I need to implement a customized $http.get call, but I'm just not sure where to add it within the native export implementation.  Has this been done before?

**Comment by PaulL1** [comment]
I think I'd be tempted to use a server-side export in this situation - there are some reasonable pdf generation packages on the server.

If you really want to export client side, then fundamentally you'll have to shift all the data to the client (which takes the point out of pagination somewhat).  I don't think exporter has a hook to say "get all the data", so you perhaps would have to use a custom UI/menu item, and wrap it in a method that first gets all the data into the grid, then calls export.

**Comment by Shanna7463** [comment]
I'm trying to use your advice and implement a custom menu Item, however it doesn't seem to be working correctly.  I update my grid with all data and then I call csvExport:

gridMenuCustomItems: [
                          {
                            title: 'Export All Data',
                            action: function ($event) {

                            	$http.get(url).success(function(data) {
                            		$scope.gridOptions.totalItems = data.totalFeatures;
                            		$scope.gridOptions.data = data.features;
                            		
                              	    var myElement = angular.element(document.querySelectorAll(".custom-csv-link-location"));
                              	    $scope.gridApi.exporter.csvExport( uiGridExporterConstants.ALL, uiGridExporterConstants.ALL, myElement );
                          	  	});
                            }
                          }
                        ],

However, the file only contains the data that was previously displayed in the grid (i.e. I was initially displaying 25 rows, then selected Export All Data, the grid updates with all available data, but the file created only has 25 entries.)  Any idea what I'm doing wrong?

**Comment by PaulL1** [comment]
You may need a timeout or $interval to allow the grid to ingest the data before triggering the export.

**Comment by AlphaHinex** [comment]
Hi @PaulL1 , I did some works on my fork's `export-all` branch to fulfill the same requirement as @Shanna7463 needed. If you think it would do some help, please let me know.

**Comment by PaulL1** [comment]
I'd be happy to take a look at it.  I can only imagine that it'd have a callback for "get the rest of the data", and then it'd wait on that promise before calling export?

**Comment by AlphaHinex** [comment]
yes, user need to supply a callback to "get the rest of the data" if using external pagination, exporter plugin will call it automatically when it found the length of grid data is not equal to total item of grid.

**Comment by PaulL1** [comment]
Yeah, sounds useful.  A PR would be appreciated.

**Comment by PaulL1** [comment]
This is now merged, closing.
