### ISSUE TITLE
PageDn/PageUp in grid with cellNav doesn't always end up visible

### ISSUE THREAD

**Issue by steverA** [angular-ui/ng-grid#2970]
I tried the cellNav example (tutorial 202) and a PageDn shows only a partial row (at best). I don't think it takes into account a horizontal scrollbar when determining if the row is visible.
1. put focus on row 0 (on top) and hit page down. You can just see the highlighted row
    Then do PageDn again and focus disappears entirely
2. With row 0 on top, click on row 4. Do a PageDn. Focus disappears. Use the vertical scrollbar slowly and when row 19 comes into view it will be in focus. Continue with the vertical scrollbar slowly and the focus disappears.
I would think that the PageXX would move focus a certain number of rows and then that row would be scrolled into view if necessary.

In my code, I tried a scrollToIfNecessary() inside cellNav but it wasn't very useful.

**Comment by PaulL1** [comment]
@swalters: do your scrolling changes address this by any chance?

**Comment by swalters** [comment]
Page down causes wrong cell selection

**Comment by swalters** [comment]
this seems to work well enough on master.  It doesn't do exactly one page of data when you are focused on row 0 and hit page down, but imho it's good enough until someone has time to really dig into it.
