### ISSUE TITLE
Modifying value before displaying in grid

### ISSUE THREAD

**Issue by weagle08** [angular-ui/ng-grid#2973]
I have a value I would like to modify before displaying in the grid... is there a way to make the field accept a function without having to modify the original data to contain a function which can be passed as a string? Does this make sense? I just would rather not modify the data source.

Thanks

**Comment by PaulL1** [comment]
A filter would be the normal way to do that - look at the cellFilter doco.

**Comment by weagle08** [comment]
I found the cellFilter documentation http://ui-grid.info/docs/#/api/ui.grid.class:GridOptions.columnDef but the documentation doesn't really help me understand how to use it and what it does... would you know of an example of it's use? I did not find an example in the tutorials.

**Comment by PaulL1** [comment]
http://ui-grid.info/docs/#/tutorial/201_editable has a cellFilter in it.

It's the same as any other angular filter - it formats values.  In the example above it converts the codes (1, 2) to (male, female).

**Comment by weagle08** [comment]
Now that clicks!!! thank you!!!!
