### ISSUE TITLE
csv export formatting

### ISSUE THREAD

**Issue by kitensei** [angular-ui/ng-grid#2978]
Hello,
is it possible to export as csv using the exact same formatting used for display ? see the example:

```
{
    enableColumnMenu: false,
    name: 'unitPrice',
    width: 150,
    enableCellEdit: false,
    displayName: $translate('APP.UI.catalog.grid.price'),
    cellClass: 'ui-grid-cell-contents unselectable',
    cellTemplate: '<div title="{{ row.entity.unitPrice | currency }} \/ {{row.entity.detail_qty | number:0}}{{row.entity.unit}}">{{row.entity.unitPrice | currency}}</div>'
}
```

This get displayed as **CHF 15.00** in the grid, but exported as **15** without using the `exporterFieldCallback()` function, is it possible to do this without export callback ?

**Comment by PaulL1** [comment]
Not currently, no.  I looked into using the filters that the field uses, but they're not formatted in the same way that filters are used when called directly, and when called directly they need to be synchronous, whereas some cell filters are async.  It wasn't clear to me that I could reliably deal with all the different filters.  So exporterFieldCallback is currently the only way.

**Comment by kitensei** [comment]
works as expected, I wanted just to know if there was another method as I thought it would generate too much overheat

**Comment by ghiscoding** [comment]
I actually need to do this as well, I have for example "translate" applied on headerCellFilter and cellFilter. Is there any ways of doing it? 

I know the issue is closed but it really is an issue.

**Comment by PaulL1** [comment]
Yes, the way to do it is to use the exporterFieldCallback.  I think the handling of angular filters has improved over time, so potentially it is possible to create a pull request that added the capability to do this automatically, but that's really a feature request (that would come with a pull request), not a defect.

**Comment by ghiscoding** [comment]
Thanks for the super fast reply. So if I follow correctly, correct me if I'm wrong, I would need to use the `exporterFieldCallback` as shown on this [UI Grid Tutorial: 312 Exporting Data With Custom UI](http://ui-grid.info/docs/#/tutorial/312_exporting_data_complex) and do a mapping for all the necessary columns. 

Seems fairly simple, I'll give it a try. Thanks again

**Comment by sachetgupta** [comment]
If you have applied filter to columnDefs, then you just have to write a callback method which will execute that same filter while exporting the data. You do not have to write the same logic (filter logic) twice.

Below is my proposed solution. This method would work for multiple filter with multiple parameters.

Column defination:

```
var rptColumnDefs = [ {
        field: 'field1',
        cellFilter: "filter1:'param1' | filter2 | filter3 : 4 | filter4 : 4 : 'param2'",
        displayName: "Field 1"  
    }, field: 'field2',
        cellFilter: "filter1:'param1' | filter2 | filter3 : 4 | filter4 : 4 : 'param2'",
        displayName: "Field 2"  
    }]
```
Exporter Callback function:

```
$scope.reportGridOptions = {
    enableFiltering: true,
    enableHorizontalScrollbar: uiGridConstants.scrollbars.NEVER,
    enableVerticalScrollbar: uiGridConstants.scrollbars.WHEN_NEEDED,
    exporterCsvFilename: '',
    columnDefs: rptColumnDefs,    
    exporterFieldCallback: function (grid, row, col, input) {
            if (col.cellFilter) { // check if any filter is applied on the column
                var filters = col.cellFilter.split('|'); // get all the filters applied
                angular.forEach(filters, function (filter) {
                    var filterName = filter.split(':')[0]; // fetch filter name
                    var filterParams = filter.split(':').splice(1); //fetch all the filter parameters
                    filterParams.unshift(input); // insert the input element to the filter parameters list
                    var filterFn = $filter(filterName); // filter function
                    // call the filter, with multiple filter parameters. 
                    //'Apply' will call the function and pass the array elements as individual parameters to that function.
                    input = filterFn.apply(this, filterParams); 
                })
                return input;
            }
            else
                return input;
        }
```
This generic function will help export the data as it is displayed in UI Grid (after applying the filters.)
Hope this helps someone.

**Comment by vikobg** [comment]
I have the same problem as @ghiscoding.  The exporterFieldCallback works perfect for cellFilters, but I'm also using exporterHeaderFilter for the headers and currently they are displayed without any filter applied. Is there a way to change the headers also, because we are using a translation filter for them ?
