### ISSUE TITLE
empty col when exporting csv

### ISSUE THREAD

**Issue by kitensei** [angular-ui/ng-grid#2979]
When trying to export a csv with the following command:

```
api.exporter.csvExport(uiGridExporterConstants.ALL, uiGridExporterConstants.ALL);
```

The following column get always exported as an empty value (value is *undefined*) can you help me ?

```
{
    enableColumnMenu: false,
    enableCellEdit: false,
    enableSorting: false,
    name: 'packing',
    width: 150,
    displayName: $translate('APP.UI.catalog.grid.packing'),
    cellClass: 'ui-grid-cell-contents unselectable',
    cellTemplate: '<div>{{ (row.entity.quantity || 1) | number:0 }} {{ row.entity.unit }}</div>'
},
```

**Comment by PaulL1** [comment]
It doesn't have a field, it has a custom template that is rendering values from other columns.  Exporter cannot get at that value, it doesn't read the content off the screen, it gets it from the underlying data.

If you bound your column to a function instead, then that would likely work.  To do that you have to iterate through your data array adding a function to each row - the function would be something like:
```
  data[i].packing = function() {
    return packing = (data[i].quantity || 1) + ' ' + data[i].unit;
  ];
```

And then use packing as your column field.  See the binding tutorial for examples.

**Comment by kitensei** [comment]
works great, thank you :)
