### ISSUE TITLE
Error thrown when running "npm install" for ng-grid project.

### ISSUE THREAD

**Issue by mscharp** [angular-ui/ng-grid#2984]
Following the steps in the FIRST_TIMER.md file, when attempting to run "npm install" the following error was thrown:

npm ERR! notarget No compatible version found: glob@'>=4.4.2-0 <5.0.0-0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["1.1.0","2.0.9","2.0.8","2.0.7","2.1.0","3.0.0","3.0.1","3.1.0","3.1.1","3.1.2","3.1.3","3.1.4","3.1.5","3.1.6","3.1.7","3.1.9","3.1.10","3.1.11","3.1.12","3.1.13","3.1.14","3.1.15","3.1.16","3.1.17","3.1.18","3.1.19","3.1.20","3.1.21","3.2.0","3.2.1","3.2.3","3.2.4","3.2.5","3.2.6","3.2.7","3.2.8","3.2.9","3.2.10","3.2.11","4.0.0","4.0.1","4.0.2","4.0.3","4.0.4","4.0.5","4.0.6","4.1.2-beta","4.1.2","4.1.3","4.1.4","4.1.5","4.1.6","4.2.0","4.2.1","4.2.2","4.3.0","4.3.1","4.3.2","4.3.3","4.3.4","4.3.5","4.4.0","4.4.1"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

**Comment by c0bra** [comment]
When you do `npm info glob` do you see versions that fall within that range?  5.0.2 is the latest for glob and I see v4.4.2 out there.

**Comment by mscharp** [comment]
Nope, max version is 4.4.1 when I do ```npm info glob```

**Comment by c0bra** [comment]
Maybe try cleaning your npm cache?

**Comment by mscharp** [comment]
OK, that got me closer.  Ran npm install, bower install and then grunt, but got an error:

Loading "Gruntfile.js" tasks...ERROR
>> TypeError: Cannot call method 'match' of null
Warning: Task "default" not found. Use --force to continue.

Aborted due to warnings.


Ran npm update and got this error:

npm ERR! fetch failed https://registry.npmjs.org/vow/-/vow-0.4.8.tgz

**Comment by c0bra** [comment]
Are you posting to github from the same machine that you're trying to setup the project on?

Seems like network problems, perhaps?

**Comment by c0bra** [comment]
No response in > 2 weeks. Closing.
