### ISSUE TITLE
Edit: nested timeout on cellNav editOnFocus

### ISSUE THREAD

**Issue by PaulL1** [angular-ui/ng-grid#2986]
We had a defect where a cellNav that required a scroll would:
1. Fire scroll
2. Set focus to the new cell
3. Edit would start editing (editOnFocus)
4. Scroll event handler would fire
5. Editing would end again

This can be (and has been) fixed by a nested timeout - timeout then timeout, then start editing.  The fact this is necessary means that something is wrong, but it's not clear what that something is.  We need to find that something and fix it.

**Comment by PaulL1** [comment]
May be fixed with @swalters latest scrolling changes.

**Comment by PaulL1** [comment]
I've reviewed now that this code is merged.  The ugly double timeout is gone, and this whole area of code is also gone.  Closing.

**Comment by Aatish810** [comment]
This issue still persists in IE. when one navigates from last visible cell to the next one(which is invisible or partially visible) with tab it gets focus and then goes to edit mode and the comes out of edit mode with focus still there.

**Comment by kolekaramol** [comment]
This issues still persits I am facing when height of grid is fixed

**Comment by kolekaramol** [comment]
> I've reviewed now that this code is merged. The ugly double timeout is gone, and this whole area of code is also gone. Closing.

Still facing this when grid heigh is less than no of rows
