### ISSUE TITLE
Grouping API does not work as expected

### ISSUE THREAD

**Issue by SSAbraham** [angular-ui/ng-grid#2996]
Hello

I know this is still in alpha but I couldn't find an issue report on this.  According to the grouping API tutorial:
Grouping can be set programmatically by using the columnDef option grouping: { groupPriority: 0 }, or for aggregations on a column by setting grouping: {aggregation: uiGridGroupingConstants.aggregation.COUNT}.

Then I call notifyDataChange(uiGridConstants.dataChange.ALL) or notifyDataChange(uiGridConstants.dataChange.COLUMN)

However nothing happens when I do that.  I can instead inject uiGridGroupingService to call groupColumn and that works fine.  However like similar to the user interactive grouping when grouping is removed the columns are reordered but this only seems to happen with over 10 columns on the grid.

Code example:
```javascript
onRegisterApi: function (gridApi){
   $scope.gridApi = gridApi;
}

$scope.groupBy = function(columnName){
   var columnDef = $scope.gridApi.options.columnDefs.filter(function(columnDef) {return columnDef.name === columnName})[0];
   columnDef.groupPriority = 0;
   $scope.gridApi.core.notifyDataChange(uiGridConstants.dataChange.ALL);
}
```

I'm using the unstable js file from Commits on Mar 12, 2015.

Thanks
Sam

**Comment by PaulL1** [comment]
The notifyDataChange isn't implemented yet, this is included in the outstanding items listed in the tutorial. But it should work if you set the grouping settings on initial render, as in the tutorial.

**Comment by SSAbraham** [comment]
I may have misunderstood the tutorial.  I thought that it was just saying it needed to be called manually for the time being.  It sounds like the hook isn't there at all yet.  Thanks for clarifying this.

Unfortunately, my goal is to allow the users to group the grid after the initial render via the API so that part won't work.  Thanks for your prompt reply.

**Comment by PaulL1** [comment]
OK, the notify data change part probably isn't too far away - I need mostly to do some testing to check how it works, but I had started to wonder whether it would work automatically with no changes at all.  Perhaps I should just expose groupColumn and aggregateColumn on the API instead - perhaps the rest of it will take care of itself.

**Comment by SSAbraham** [comment]
It worked injected the uiGridGroupingService and called uiGridGroupingService.groupColumn($scope.gridApi.grid, column) and did do grouping.  The problem was after uiGridGroupingService.groupColumn($scope.gridApi.grid, column), the column order seems to get messed up.  Also performance was kind of slow with the ungroup call.  I'm happy test in our scenario either way when you're ready.

**Comment by PaulL1** [comment]
Thinking about it, the trick may be that the columnBuilders have to run.  The code uses the grouping settings on the columns themselves, and the settings are copied down from the colDef to the columns when the columnBuilders run (unless the user has made changes to the column settings directly via the UI).

So perhaps if you set the grouping on the column directly (same settings as you put on the colDef) then it would "just work".  You may also need to call grid.refresh(), or at least grid.refreshRows().

**Comment by SSAbraham** [comment]
Just a quick update.  We tried the ColDef followed by the refresh.  Worked and the column order was preserved.  Thanks!

**Comment by SSAbraham** [comment]
I misspoke above... it was done on columns[i].grouping not on colDef.  I edited the post to reflect the correct info.  

Two things of note while I'm in here:
1) We had to do a sort before grouping to get the desired results
2) Most grid groupings I've used in the past the column being grouped on moves to the left so you can see the group headers all in one place.  Doing it this way does not result in that.  Interactive grouping does this properly however.

**Comment by PaulL1** [comment]
Hmm.  It should, the move column is in the column processor, so if the column processor runs again (which it does in a refresh()) it should move.

Do you have the latest unstable?  It's something I changed in the last few days.

**Comment by SSAbraham** [comment]
The problem was with v3.0.0-rc.20-b98fa0f - 2015-03-10.  We just tried it with the latest unstable build.  The column ordering seems to be fixed.  The sorting still needs to be applied first however.

**Comment by SSAbraham** [comment]
Just a few more suggestions.  It would good if the grouped column appears on the header of the grouping rather than repeated as a column in every row, as it that seems redundant.  Also grouping and pinning don't seem to play nice.  When pinning is enabled the grouping seems to push rows below.

**Comment by PaulL1** [comment]
On the repeating of the data in rows, I'm not overly thrilled with teh current look and feel but I'm somewhat constrained by a desire to not modify the row templates (doing so impacts scroll performance), and to not change the underlying data entities (can impact on people's $http requests).

So at the moment the data rows are exactly as they were before they were grouped, only the groupHeader rows are new.  I'm open to ideas as to how to do it differently within those constraints, I haven't really come up with any ideas I like a lot that would resolve it.

On pinning, we're looking at that in a few different places, it's not pinning itself, rather it's having more than 1 column in the left render container I think.

**Comment by PaulL1** [comment]
Relating to the repeating of data, the tutorial should be updated later today with an example of a cellTemplate that will avoid the data repeating in each row.  

I think the right approach to doing this programmatically is to expose the groupColumn, ungroupColumn and aggregateColumn methods.  I'll do a PR with that today.  I'll include the default sort logic inside that.

**Comment by SSAbraham** [comment]
Great thanks!
