### ISSUE TITLE
reduce flicker when resizing horizontally

### ISSUE THREAD

**Issue by Tim-Erwin** [angular-ui/ng-grid#2997]
I have grids on a page that have *width: 100%*. When I then decrease the browser width, the grid content repeatedly jumps down for a moment before it jumps back. That looks really unclean and annoying. By adding an *overflow-x: hidden* to *.ui-grid* I was able to reduce that quite a bit. It's still there, but not as much and also it does not push down the content which is below the grid any more. Don't know if this has any negative side effects, though. None noticed so far.

**Comment by kelchm** [comment]
I've noticed this as well.  Would be great to see ui-grid-auto-resize improved.

**Comment by c0bra** [comment]
I haven't been able to find a solution that doesn't require altering how containers are rendered. It looks like we'll need to move away from floated elements and either absolutely position or use margins.
