### ISSUE TITLE
"Export all visible data as csv" and "Export all data as csv" in the grid menu return the same data

### ISSUE THREAD

**Issue by bringking** [angular-ui/ng-grid#2998]
I am seeing this locally in RC20 and here on the docs site-

http://ui-grid.info/docs/#/tutorial/206_exporting_data

**Comment by PaulL1** [comment]
I just checked the tutorial, and for me the all data includes the gender column and the visible data does not.  Are you getting a different result?

**Comment by bringking** [comment]
@PaulL1 actually you are right, I was thinking it would export the data "visible" in the grid window, not the  visible columns. Sorry about that. To prevent confusion possibly consider renaming the label to say "Export all visible columns" or something similar.
