### ISSUE TITLE
editDropdownFilter does not work

### ISSUE THREAD

**Issue by tanak** [angular-ui/ng-grid#3000]
editDropdownFilter does not work because the position of filter expression is not correct.

src/features/edit/templates/dropdownEditor.html
```html
<div>
  <form name="inputForm">
    <select ng-class="'colt' + col.uid" ui-grid-edit-dropdown ng-model="MODEL_COL_FIELD" ng-options="field[editDropdownIdLabel] as field[editDropdownValueLabel] CUSTOM_FILTERS for field in editDropdownOptionsArray"></select>
  </form>
</div>
```
should be
```html
<div>
  <form name="inputForm">
    <select ng-class="'colt' + col.uid" ui-grid-edit-dropdown ng-model="MODEL_COL_FIELD" ng-options="field[editDropdownIdLabel] as field[editDropdownValueLabel] for field in editDropdownOptionsArray CUSTOM_FILTERS"></select>
  </form>
</div>
```

**Comment by tanak** [comment]
Here is a plunker to check editDropdownFilter.
http://plnkr.co/edit/L1jeq87mOHAPsLISIHr7?p=preview

**Comment by c0bra** [comment]
@tanak did you forget to save the plunker?

**Comment by tanak** [comment]
@c0bra this is correct version.
This plunker is to check if the function works correctly or not.
I mean, this plunker uses the latest version of ui-grid, so editDropdownFilter does not work correctly now.
I hope it will work correctly after my PR merged.
sorry for my poor explanation.
