### ISSUE TITLE
Scrolling call back responsiveness

### ISSUE THREAD

**Issue by feralanPaladin** [angular-ui/ng-grid#3002]
At 402_GridIsScrolling tutorial gridApi.grid.isScrollingVertically and gridApi.grid.isScrollingHorizonally models are not likely to be responsive. Are there any other (and more efficient) way of observing scroll end event.

**Comment by c0bra** [comment]
What do you mean by "responsive"?

**Comment by feralanPaladin** [comment]
I mean the visual feedback is done instantly but the model values are not
that fast.
13 Mar 2015 16:50 tarihinde "Brian Hann" <notifications@github.com> yazdı:

**Comment by c0bra** [comment]
Yea it looks like there is a timeout on determing when scrolling is complete. @PaulL1 @swalters can either of you comment?

**Comment by feralanPaladin** [comment]
I will be glad if you can suggest me an alternative way to observe the
scroll event's ending.
13 Mar 2015 19:29 tarihinde "Brian Hann" <notifications@github.com> yazdı:

**Comment by PaulL1** [comment]
@swalters is working on some better scroll event notifications at the moment.  This probably should get tipped into that pile.  The short answer is that some of it is native browser stuff and we don't get told by the browser when it's finished.  But the longer answer is that we might be able to do a bit better than we're doing today.

**Comment by feralanPaladin** [comment]
Thank u guys. Wish u good luck.
13 Mar 2015 20:30 tarihinde "Paul" <notifications@github.com> yazdı:

**Comment by PaulL1** [comment]
Shane, I think you're doing a scroll end notification in your scroll changes, so we could close this when you're done?

**Comment by swalters** [comment]
try setting gridOptions.scrollDebounce to a smaller number.  it defaults to 300ms. Try 
gridOptions.scrollDebounce = 50 and see if it's better.

**Comment by PaulL1** [comment]
@swalters: is there also a new SCROLL END event or something, which might get to the root of what @feralanPaladin was after?

**Comment by PaulL1** [comment]
No further comment for over a month, solution provided that probably resolves the issue.  Closing, please re-raise if there is a reliable recreate or more information.
