### ISSUE TITLE
Grid menu filter

### ISSUE THREAD

**Issue by cookednoodles** [angular-ui/ng-grid#3004]
At the moment you can add a translate filter  to the headerCellFilter, but there is no way to apply a translate filter to the menu items.

**Comment by c0bra** [comment]
Does i18n not work for you for altering menu item text? http://ui-grid.info/docs/#/tutorial/104_i18n

**Comment by cookednoodles** [comment]
Sorry; I meant the col names in http://ui-grid.info/docs/#/tutorial/304_grid_menu menu

**Comment by PaulL1** [comment]
This is working for me in my application.

The setting I think you need is gridMenuTitleFilter, which is documented in http://ui-grid.info/docs/#/api/ui.grid.class:GridOptions
