### ISSUE TITLE
Infinite Scroll not working in rc-20 - blank grid

### ISSUE THREAD

**Issue by PhilBroadbent** [angular-ui/ng-grid#3007]
RC-20 seems to have broken Infinite Scroll - if I revert to RC-19 it works as expected.

Call to database to retrieve data shows data fine, however, when scrolling down and infinite scroll is fired, when the data comes back it renders the grid as blank:

![image](https://cloud.githubusercontent.com/assets/7779879/6640375/b79e520a-c98e-11e4-9d56-3cb6335fdbc9.png)

You can get the data back by scrolling horizontally only!

Anyone else seen this?

**Comment by cookednoodles** [comment]
This is fixed in unstable.

**Comment by PaulL1** [comment]
Looks to be fixed, no response for some time, closing.
