### ISSUE TITLE
Row selection does not appear with custom row template

### ISSUE THREAD

**Issue by yashgt** [angular-ui/ng-grid#3013]
When a row is clicked in the grid, it gets selected and appears in a different color. I would like to create a custome row template that shows all grid data in a different color. However, I would like to retain the functionality where the row appears in a different color when selected.
At this plunker http://plnkr.co/edit/Y3mvxtzlS55RjXjllVZE?p=preview
When I select the row, the color does not change. This happens after I have applied my new rowTemplate.
If I remove the rowTemplate, the row selection appears correctly.

How can I retain the row selection appearance with a custom row template?

Regards,
Yash

**Comment by PaulL1** [comment]
You can't change the level of nesting of the divs by the look.  If you extend the default ng-class it works:
http://plnkr.co/edit/qLT78EZg3yyPDlMdwPH3?p=preview

**Comment by yashgt** [comment]
That works. Thanks a ton.
