### ISSUE TITLE
Html passing as a value is not rendered

### ISSUE THREAD

**Issue by deezaster** [angular-ui/ng-grid#3021]
i send html code as a value, but it is not rendered in the browser. what i am doing wrong?

http://plnkr.co/edit/TwMfw5LpGS2Dpqqwn5Ix?p=preview

**Comment by PaulL1** [comment]
You can't render html in that way within the grid - you're putting the string into a div, it's just rendering the string.  To render the actual html I think you'd need to make a directive, then set the cellTemplate to that directive.  Inside the directive you'd need to grab the cell value and then compile it and append it to the DOM.  

Do you really want the ability to execute arbitrary html code in your cells, or do you have a limited set of different renderings that you want?  If the latter, then you can get most of what you want by using an ng-if, in some cases a filter or a cellClass may give you all you need.

**Comment by deezaster** [comment]
depending on the user permission the backend service sends a view, edit and/or delete-button. 
using ng-if is not really beautifull ;-)
do you have an example using a filter or a cellClass? i have no idea how to use...

**Comment by PaulL1** [comment]
It depended on what the html was trying to do.  

If it's a button, then ng-if or ng-show is the best answer.  

If it's more css stuff (making it bold or flashing or something) then cellClass would be the right answer.  

If your html was just trying to format the value in the cell, then a filter can do that.

So, at the moment the best answer is an ng-if.  Is the button different at the row level, or will all rows displayed to a given user have the same button?  If so, then I'd do the configuration at the grid level using a cellTemplate.

**Comment by deezaster** [comment]
i wrote a directive. i dont compile the html in the directive and it works as well. why?

i updated the plunk: http://plnkr.co/edit/TwMfw5LpGS2Dpqqwn5Ix?p=preview

**Comment by deezaster** [comment]
I made a directive:
```javascript
angular
   .module('theApp')
   .directive('x3mCompileHtml', x3mCompileHtml);

x3mCompileHtml.$inject = ['$compile'];

function x3mCompileHtml($compile) {

   var directive = {
      restrict: 'A',
      replace: true,
      link:     link
   };
   return directive;

   function link(scope, element, attrs) {
      attrs.$observe('x3mCompileHtml', function (val) {
         element.html(val);
         $compile(element.contents())(scope);
      });
   }
};
```

The directive in action:  
```javascript
:
columnDefs:          [{
   :
   cellTemplate:     '<div class="ui-grid-cell-contents"><span x3m-compile-html="{{COL_FIELD}}"></span></div>'
},
:
```
