### ISSUE TITLE
How do i show the nested JSON data in ng-grid?

### ISSUE THREAD

**Issue by aksharak** [angular-ui/ng-grid#3023]
I have a JSON data as {"data1":"val1","data2":val2,"data3":[{"data4":"val3","data5":"val4"},{"data6":"val5","data7":"val6"}],"data8":[{"data9":"val7","data10":"val8","data11":"val9"},{"data12":"val10","data14":"val11","data14":"val12"},{"data15":"val13","data16":"val14","data17":"val15"}],"id":1}

I want to keep the inner JSON as multiple select check-boxes or multiple select drop-down in a cell. For ex: for data3 column a single cell will have a multiple select check-boxes or multiple select drop-down with values of data4 and data6 in 1 set and in another set data5 and data7. How do i represent the data here? Any better solution also in appreciated. Thanks in advance

**Comment by totszwai** [comment]
Dude, you should ask this in stackoverflow... this isn't a bug/issue. 

To answer your question, you could probably build the columnDefs dynamically. 

I had similar situation dealing with JSON data, however my work involve using EMF, and i end up altering my EMF model to match the ui-grid columnDefs options. That allows me to dump my columnDefs directly. $scope.myGrid = myEMFColumnDefs;

**Comment by PaulL1** [comment]
If you're doing a multi-select type arrangement, I'd usually represent as an array:

```
  {
    data1: "val1",
    data2: "val2",
    data3: ["val3", "val5", "val7"],
    etc
  }

I generally wouldn't try to put two widgets in the same cell, particularly if the height of that widget is variable, because it will give you issues with row height.  ui-grid doesn't support variable row heights.  So I'd be focusing on widget types and arrangements that allow a standard row height.

Are you suggesting that each row would have different widgets - so for row1 you might have a dropdown in column2, and in row2 there might be a dropdown in column4?  ui-grid isn't great at dealing with data that isn't genuinely in columns - where all the rows for a given column have the same data type.  If you don't mean this, but just mean that you want to build the column definitions on the fly once you see the data, then ui-grid is quite good at this.

**Comment by aksharak** [comment]
I have the JSON data like below:
{
data1: "val1",
data2: "val2",
data3: [ {data31: "val31",
              data32: "val32" },
            {data33: "val33",
             data34: "val34" }]
data4: [ {data41: "val41",
              data42: "val42" },
            {data43: "val43",
             data44: "val44" }]
}

So i thought it would be better to put a grid with checkboxes inside the cells. What is the other best way to represent the data if you do not suggest nested grids? any suggestions would be great.
Thanks,

**Comment by PaulL1** [comment]
Expandable is the normal way to nest data, refer http://ui-grid.info/docs/#/tutorial/306_expandable_grid

**Comment by PaulL1** [comment]
Closing: solution proposed that should resolve the issue, no further comments for 2 weeks, assuming solution has resolved issue.
