### ISSUE TITLE
Circular Reference Failure with BreezeJS

### ISSUE THREAD

**Issue by mikethibault** [angular-ui/ng-grid#3025]
It looks like ui-grid cannot handle the circular references that are inherent in Breeze.JS.  The Breeze folks write a bit about it on their site, and even though they reference Knockout the concept is still valid: http://www.getbreezenow.com/documentation/knockout-circular-references

Here's the Todos Sample Plunker with a UI Grid added with the same data: http://plnkr.co/edit/JoHYIeSUmbV113kAUwMv

This results in infinite "Maximum call stack size exceeded" and "[$rootScope:infdig] 10 $digest() iterations reached. Aborting!" errors.

Breeze and UI-Grid would be a formidable combination, especially if editing were possible.  I hope this can be fixed!

**Comment by novice3030** [comment]
We also use breeze and you can use .noTracking() method to get a plain js
object. Also note that if you dont use inline editing thats probably what
you should have done in the first place just project the the properties you
want using .select(). One more note angular 1.3+ does support circular ref
what ver of angular do you use?
בתאריך 16 במרץ 2015 21:24, ‏"Mike Thibault" <notifications@github.com> כתב:

**Comment by mikethibault** [comment]
I've used projections and similar errors occur.  I'll try noTracking() but the ideal would be to inline edit using Breeze and UI Grid.  I'm using Angular 1.3.12.

**Comment by novice3030** [comment]
Let me try to see what i can do about it
I dont have much time these days but i will try to help if i can
בתאריך 16 במרץ 2015 22:06, ‏"Mike Thibault" <notifications@github.com> כתב:

**Comment by mikethibault** [comment]
Fantastic, thank you!

**Comment by novice3030** [comment]
I was able to fix this issue and everything works as expected
It didn't have anything to do with circular references
Please check out this plunker http://plnkr.co/edit/JoHYIeSUmbV113kAUwMv

**Comment by mikethibault** [comment]
Thanks so much!  This worked great and I'm able to edit with UI Grid and Breeze.

**Comment by BartVDACodeware** [comment]
I had this issue with formly and breeze.
The solution was to rename the 'entityAspect' property to '$entityAspect'
This will prevent angular.equal function from comparing this property.
I also posted a suggestion here:

https://breezejs.uservoice.com/forums/173093-1-breezejs-feature-suggestions/suggestions/9073255-change-entityaspect-name-to-entityaspect-to-preve
