### ISSUE TITLE
Programatically select the row in ng-grid

### ISSUE THREAD

**Issue by aksharak** [angular-ui/ng-grid#3032]
Hi,
Am refreshing an ng-grid on every 5 seconds. I am getting the data from the server on an interval of every 5 seconds.
setInterval(function () {
    $scope.$apply(function (){
$http.get('http://www.w3schools.com/website/Customers_JSON.php').success(function(thisdata) {
    //Convert data to array.
    $scope.myData = angular.fromJson(thisdata);
}
    });
}, 5000);

Suppose i select a row, after 5 seconds the grid is reloaded, i want to keep the selection as is. Or make it select the same row again programatically. on select of row am performing other actions. Am trying to get the row index on select of a row and storing it in a variable. After refresh am using $scope.ngGrid.selectRow(selectedRowIndex, true) to make it select. But it seems to be selecting the row but not visible in UI. how make it look selected in UI as well.

**Comment by PaulL1** [comment]
Without seeing the plunker of the whole it's hard to say, but the most common issue people have is selecting the row before the grid has had a chance to ingest the data - so if you are setting the data then setting the selection, you need to put one or two (can't remember which) timeouts before the selection.  The selection tutorial I think does exactly this, so check there.

**Comment by aksharak** [comment]
Hi Paul,
Adding the delay worked fine for me.. We can close this. Thanks
