### ISSUE TITLE
Pinned columns not rendering properly

### ISSUE THREAD

**Issue by njosh** [angular-ui/ng-grid#3037]
data in pinned column is overlapping into each other on pinning                   

I am facing this issue when i set minWidth property on pinned columns
Also i have noticed this issue happens only if i am using subgrid feature.

Here is the plunkr
http://plnkr.co/edit/Q8ZMrHGM15vOgQXB4Eib?p=preview

Please let me know on this

![image](https://cloud.githubusercontent.com/assets/11484810/6695366/bb1eea2c-cd06-11e4-89a1-e5ddc2edeff6.png)

**Comment by PaulL1** [comment]
I suspect this is related to #3050

**Comment by PaulL1** [comment]
The plunker now seems to be working - could you confirm if this is resolved with the latest column width calculation fixes?

**Comment by njosh** [comment]
Thanks Paul. This is working now.But there is some issue with expandable feature its not working now in the plunker same is replicable on tutorial pages also

http://ui-grid.info/docs/#/tutorial/306_expandable_grid

![image](https://cloud.githubusercontent.com/assets/11484810/6885556/e3fd6118-d642-11e4-8d8c-9521c0399f3b.png)

**Comment by PaulL1** [comment]
Yeah, that's weird.  It wasn't like that last night, and no code seems to have gone up in the meantime.  When I pull master and build it it works fine locally.  It looks like a font problem - maybe the build just went wrong.  If so, it'll fix next time someone merges something.

**Comment by PaulL1** [comment]
Fonts now also fixed.  Original issue is resolved, the subsidiary issue was a build gremlin. Closing.
