### ISSUE TITLE
IRC webhook

### ISSUE THREAD

**Issue by Foxandxss** [angular-ui/ng-grid#3041]
Hello dear @angular-ui/ng-grid guys, could you please remove the IRC webhook? It is not interesting anymore I think. There is no core team on the IRC anymore so I don't think anyone wants it.

I also removed the ui-bootstrap ones, weren't needed as well.

**Comment by Foxandxss** [comment]
@PaulL1 This is something you can do in 10 seconds, not sure why the milestone is "Future".

**Comment by c0bra** [comment]
I'll remove it

**Comment by Foxandxss** [comment]
Thanks @c0bra, people were complaining and I didn't ban them :P

PS: We don't see you anymore ;(

**Comment by c0bra** [comment]
@Foxandxss I know :(

My work has blocked most ports and I'm too lazy to run a reverse proxy or find a webchat client that isn't terrible.
