### ISSUE TITLE
Refresh row.isSelectable

### ISSUE THREAD

**Issue by masterkidan** [angular-ui/ng-grid#3054]
A question on how row.isSelectable is evaluated. 
In the following plunkr
http://plnkr.co/edit/rrT6G2VxC6EKyQzsYkYF?p=preview
I have set selection to only allow selection on rows with age > 30. 
However when I update a particular row entry to an age > 31 it doesn't allow me to select that row. I have tried calling $scope.gridApi.core.notifyDataChange(uiGridConstants.dataChange.ROW) after setting the age,but doesn't seem to re-evaluate isRowSelectable. 

Is there something I am missing here?

**Comment by PaulL1** [comment]
I updated to try notifyDataChange.DATA, which would be the one we'd probably use.  http://plnkr.co/edit/SUC3DEMm3QnFBALeKdjq?p=preview  But looking in the code we only evaluate selectable on row creation, we haven't got any hooks to re-evaluate with data change.

**Comment by PaulL1** [comment]
I've done an update on this that I'll push at the end of today, which should update the selection tutorial with this example (and code changes to make the isRowSelectable dynamic).

**Comment by masterkidan** [comment]
That was quick!,Thanks for the fix.

**Comment by TJSoftware** [comment]
I am still seeing this issue with the latest version of Angular.  Please see the [plunker](http://plnkr.co/edit/UKMM2kNaTpxUzsdn6RDB?p=preview) that I created from the [selection](http://ui-grid.info/docs/#/tutorial/210_selection) example.  I change the first row age value then call $scope.gridApi.core.notifyDataChange(uiGridConstants.dataChange.ROW);, however I am still not allowed to select the row.

**Comment by masterkidan** [comment]
notifyDataChange.DATA . Try using that instead :)
-Mukund
