### ISSUE TITLE
how to differentiate ng-grid event with two grids in single page

### ISSUE THREAD

**Issue by kandarpbhesaniya** [angular-ui/ng-grid#3055]
I have two ng-grid in page, and I want to use two corresponding ngGridEventEndCellEdit event:

function HomeCtrl($scope, $http) {
 $scope.columns = [{ field: 'name', displayName: 'Name', enableCellEdit: false }, { field: 'age', displayName: 'Age', enableCellEdit: false }];        

 $scope.gridOptions1 = {
    data: 'myData', enablePinning: true, enableCellEdit: true, enableRowSelection: false,
    columnDefs: 'columns'
 };

 $scope.columns2 = [{ field: 'name1', displayName: 'Name', enableCellEdit: false }, { field: 'Age1', displayName: 'Age', enableCellEdit: false }];        

 $scope.gridOptions2 = {
    data: 'myData2', enablePinning: true, enableCellEdit: true, enableRowSelection: false,
    columnDefs: 'columns2'
 };
 $scope.myData = [{name: "Moroni", age: 50},
                     {name: "Tiancum", age: 43},
                     {name: "Jacob", age: 27},
                     {name: "Nephi", age: 29},
                     {name: "Enos", age: 34}];

$scope.myData2 = [{name1: "Moroni", age1: 50},
                         {name1: "Tiancum", age1: 43},
                         {name1: "Jacob", age1: 27},
                         {name1: "Nephi", age1: 29},
                         {name1: "Enos", age1: 34}];
}

There are two grids, and I want two different event of ngGridEventEndCellEdit on cell edit based on grid id. How can i do that ?

//for  grid1
$scope.$on('ngGridEventEndCellEdit', function (data) {

};

//for  grid2
$scope.$on('ngGridEventEndCellEdit', function (data) {

};

**Comment by jjkovacs** [comment]
The grid event has scope information on it, which you can use to determine where it came from. From that, you can handle it as many ways as you'd like. 

For this particular event, one way you could do it is:

```javascript
$scope.gridOptions1 = {
   //options for grid 1
}

$scope.gridOptions2 = {
   //options for grid 2
}

$scope.$on('ngGridEventEndCellEdit', function(event) {
   switch(event.targetScope.gridId) {
      case $scope.gridOptions1.$gridScope.gridId:
         //handle the event for grid 1
         break;
      case $scope.gridOptions2.$gridScope.gridId:
         //handle the event for grid 2
         break;
   }
});
```

**Comment by kandarpbhesaniya** [comment]
thanks....i also did with angular ui-grid
