### ISSUE TITLE
Column sorting changed to default automatically after row added

### ISSUE THREAD

**Issue by mrodrig** [angular-ui/ng-grid#3058]
I've been using ui-grid RC.18 without any issues, but just noticed that when I change the grid's sorting to something other than the default that I specify via the grid options and then add a row to the ui-grid, the default sort is applied and my customized sorting is removed. This can be confusing to users as it's not their expected behavior.

Here's an example: http://jsfiddle.net/7ony74h5/1/
I apologize for copying and pasting the RC.18 minified release into the example... I couldn't find a CDN that hosted it, so I just copied and pasted it in.  Basically, just click on 'Gender' or 'Company' to change the sorting to something other than the default, and then click on 'Add Row' to see the behavior that I am referencing.

I did notice that the unstable release which is used on ui-grid.info does not have the same issue, but I cannot change to an unstable release.  Is there a known work around for this unexpected column sorting behavior?

Thanks in advance,
Mike

**Comment by PaulL1** [comment]
Would upgrading to RC.20 resolve the issue?

**Comment by mrodrig** [comment]
Thanks, Paul! Upgrading to RC.20 did the trick.  I hadn't upgraded because I didn't see ui.grid.paging which we are also using, but just noticed that it has since changed to ui.grid.pagination.  Thanks again!
