### ISSUE TITLE
Edit Date Control does not display for IE 11 or FF latest in RC 20

### ISSUE THREAD

**Issue by TJSoftware** [angular-ui/ng-grid#3062]
I can replicate this using http://ui-grid.info/docs/#/tutorial/201_editable as well as the RC 20 download from git.  When I try to edit a date using IE 11 or FF I only see a text field.  

Instead of a date field I would expect the date picker to display.  The date is still stored, but I know users would prefer to use a date picker.

Chrome works as expected.
![capture](https://cloud.githubusercontent.com/assets/4823412/6739315/76036b2e-ce3d-11e4-8caa-dad6067a1054.JPG)

P.S. I am also seeing the foreign characters due to the ISO issue with IE only.  Please let me know if you want a new issue created for this (since it is a known item), you can see the Chinese/Korean characters in the screenshot.

**Comment by PaulL1** [comment]
I think the issue is that we use native html5 controls, and some browsers don't provide them.  I think IE is one of those, and therefore there's little we can do unless we chose to include a control library and shims (which we haven't chosen to do).

On the foreign characters, those look like the usual font installation issue (http://ui-grid.info/docs/#/tutorial/116_fonts_and_installation).  Are you saying that there is something special about IE that causes this?

**Comment by TJSoftware** [comment]
DatePicker:
I know that IE is behind on some of HTML5, but it does support some, just probably not this control or the number control, etc.  Anyways... are there any plans in the future to provide backwards compatibility?

Foreign Chars:
I do not know what is causing the issue and I do not have any ideas as to why this happens.  I just remember reading another post that there is an issue with font installation when seeing foreign chars.  This is a screenshot from your site (http://ui-grid.info/docs/#/tutorial/201_editable).  I thought it was strange that I only see the issue in IE 11.

**Comment by PaulL1** [comment]
Yes, that is strange with fonts.  I hadn't realised / hadn't had reported that IE didn't display the fonts on the tutorial site.  Is it giving you any retrieve errors or javascript errors when it does that?

On datepicker, probably the only tentative plan is to have a ui.grid.bootstrap feature which would replace all our widgets with angular-bootstrap ones, and respect some of the bootstrap styles (which I'm not sure yet).  That would give cross platform widgets.

**Comment by TJSoftware** [comment]
I do not see any messages in the Developer Tools console log except that Nav occurred.

![capture](https://cloud.githubusercontent.com/assets/4823412/6741438/049395bc-ce4d-11e4-8583-55b760c8819e.JPG)
.

Datepicker, I will start taking bets on you guys and MS to release HTML5 support vs backwards compatibilty ;).

P.S. A++ on quick response.

**Comment by PaulL1** [comment]
Is there anything in the network tab?  Usually the fonts not working is a security exception (some sort of cross-domain policy, but in this case they shouldn't be cross-domain), or trying to retrieve the fonts from the wrong place.  Unfortunately (or fortunately) I don't have IE, so can't test myself.

**Comment by TJSoftware** [comment]
Nothing in the network tab either.
![capture](https://cloud.githubusercontent.com/assets/4823412/6741661/14722cda-ce4f-11e4-954b-ae2e5e94d6c1.JPG)

**Comment by PaulL1** [comment]
Do you need to refresh the page with the network tab open?  There should be something there, even if only successful requests?  Not all that familiar with IE's tools.

**Comment by TJSoftware** [comment]
On the datepicker topic...
I ran into the same issue while using http://vitalets.github.io/angular-xeditable/#html5-inputs (now I know it is due to HTML5 and browser support).  With the vitalets, there is an option to use the twitter bootstrap date picker.  I was able to get that to work, unfortunately, it only supports an older version of AngularUI Bootstrap (6 I think).  Is it possible to support twitter bootstrap datepicker?

**Comment by TJSoftware** [comment]
I refreshed with the network tab open.  Still no results.  Checking with Fiddler ...

**Comment by TJSoftware** [comment]
![capture](https://cloud.githubusercontent.com/assets/4823412/6741879/db9bf84e-ce50-11e4-9963-333c31f537e2.JPG)

**Comment by TJSoftware** [comment]
Looks like the fonts are half way down with a 200.  Sorry, should not have spam posted.

**Comment by PaulL1** [comment]
It should be retrieving ui-grid.info/release/ui-grid.woff or similar.  Perhaps IE likes it's own sort of font files - we appear to have ui-grid.eot, ui-grid.svg, ui-grid.ttf and ui-grid.woff.  I guess they're different font formats for different browsers - so maybe the one IE likes is missing or corrupt?

**Comment by TJSoftware** [comment]
I personally have never made font files, I only modify the css to point to them when I move a third party css to a sub folder of the content directory.  It is usually the .woff file sometimes .woff2 and 3 others.  I updated my email to my main email so I will see responses to this thread.  Please feel free to ask me if you would like a test done.

**Comment by aikrez** [comment]
You need to press the green arrow to start capturing network resources in IE.
Works different than FF/Chrome (surprise)

**Comment by rirapha** [comment]
Datepicker topic : I confirm IE and FF doesn't support this usefull functionalities. Unfortunately people continue to use IE. Thank you. I hope a new release will solve this problem.

**Comment by TJSoftware** [comment]
@aikrez Thanks for the green arrow tip.  I am more of a Chrome user that must support x-browser.  Here are the results of the network tab.  Still no .woff files.

![capture](https://cloud.githubusercontent.com/assets/4823412/6752988/6e4f02a8-ced8-11e4-97f9-51070689c020.JPG)

**Comment by PaulL1** [comment]
OK, I don't have IE to work on it, but the problem seems to be that it's not trying to, or not succeeding in, downloading the fonts.  Therefore they show incorrectly.  I presume that's either because it's not trying to download the right font file, or because the code that determines which font file to download isn't right for IE.  We'd need a breakpoint and some debugging to work out which.

**Comment by TJSoftware** [comment]
Thank you for the help with the date picker topic.  I was able to confirm using http://html5test.com/ that neither IE or FF support the date HTML5 field.

I just realized that I have the ability to close it here.  I am not able to debug your site directly, but I will see how much time I have after taking care of the kids this weekend to try this on my own machine.

**Comment by TJSoftware** [comment]
Update on Fonts.  The only way that I could ever get the incorrect fonts to display was if I was not pointing to the correct fonts in the css.  However, this caused issues on all three IE, Chrome, and FF.  I was not able to get a similar example to your site.
