### ISSUE TITLE
ui.grid.grouping Missing

### ISSUE THREAD

**Issue by MagicIndustries** [angular-ui/ng-grid#3065]
It's difficult to tell from the tutorial documentation, but is ui.grid.grouping supposed to be included in 3.0-rc.20 ?  The Tutorial docs say to include the ui.grid.grouping module and I can't find reference to it anywhere in the code, and I'm probably overlooking something obvious but I can't see it in master either.

Is the documentation ahead of the codebase, or am I pulling the wrong thing?

**Comment by PaulL1** [comment]
The documentation reflects unstable for now, and grouping is very new so you probably want to be using unstable. It's not in rc20
