### ISSUE TITLE
How to add new togle button in ui-grid

### ISSUE THREAD

**Issue by Gajendrasinh** [angular-ui/ng-grid#3066]
I want to add new toggle button in table how to i add this in row

**Comment by PaulL1** [comment]
Check the scope tutorial, it has a button in it.  http://ui-grid.info/docs/#/tutorial/305_appScope

**Comment by Gajendrasinh** [comment]
hi i am already show this tutorial. i want to add new botton in every row
<button> Edit </button> like this

-
Best Regards,
Gajendrasinh Zala

**Comment by PaulL1** [comment]
That's what the tutorial does, right?

**Comment by chanakaDe** [comment]
WOW.... I;m working on this now. I searched a lot about how to add a button at the end of a row. Finally I got and now i'm working. 
Thanks a lot.

**Comment by chanakaDe** [comment]
Have a problem. In that example, there's Name column. I want to pass name in the showMe() function as a parameter.  A follows : 

ng-click="grid.appScope.showMe(name)"

How can I do this ? Then I can access it from the controller. Imagine if I want to update or remove a row, I have to send the ID. Like that.

**Comment by chanakaDe** [comment]
@PaulL1  Please help me on this.
