### ISSUE TITLE
spanish translation

### ISSUE THREAD

**Issue by elifio** [angular-ui/ng-grid#3070]
Hi:

I think it is more correct to use "registros" instead of "Articulos" 
I think that "Articulos" are for "things" and the grid can be clients, horses, apple, or other type, "registros" is more "neutral"

http://plnkr.co/edit/8adsQt1EgQqFYdDogFbj?p=preview

also missing the definition of pagination an other minor texts...

I do not see the text "1 - 10 of 2327 items" but in spanish is "1 - 10 de 2327 registros"

Thanks for this great job.

$delegate.add('es', {
        aggregate: {
          label: 'Registros'
        },
        groupPanel: {
          description: 'Arrastre un encabezado de columna aquí y suéltelo para agrupar por esa columna.'
        },
        search: {
          placeholder: 'Buscar...',
          showingItems: 'Registros Mostrados:',
          selectedItems: 'Registros Seleccionados:',
          totalItems: 'Registros Totales:',
          size: 'Tamaño de Página:',
          first: 'Primera Página',
          next: 'Página Siguiente',
          previous: 'Página Anterior',
          last: 'Última Página'
        },
        menu: {
          text: 'Elegir columnas:'
        },
        sort: {
          ascending: 'Orden Ascendente',
          descending: 'Orden Descendente',
          remove: 'Sin Ordenar'
        },
        column: {
          hide: 'Ocultar la columna'
        },
        aggregation: {
          count: 'filas totales: ',
          sum: 'total: ',
          avg: 'media: ',
          min: 'min: ',
          max: 'max: '
        },
        pinning: {
          pinLeft: 'Fijar a la Izquierda',
          pinRight: 'Fijar a la Derecha',
          unpin: 'Quitar Fijación'
        },
        gridMenu: {
          columns: 'Columnas:',
          importerTitle: 'Importar archivo',
          exporterAllAsCsv: 'Exportar todo como csv',
          exporterVisibleAsCsv: 'Exportar visibles como csv',
          exporterSelectedAsCsv: 'Exportar selección como csv',
          exporterAllAsPdf: 'Exportar todo como pdf',
          exporterVisibleAsPdf: 'Exportar visibles como pdf',
          exporterSelectedAsPdf: 'Exportar selección como pdf'
        },
        importer: {
          noHeaders: 'No fue posible derivar los nombres de las columnas, ¿tiene encabezados el archivo?',
          noObjects: 'No fue posible obtener registros, ¿contiene datos el archivo, aparte de los encabezados?',
          invalidCsv: 'No fue posible procesar el archivo, ¿es un CSV válido?',
          invalidJson: 'No fue posible procesar el archivo, ¿es un Json válido?',
          jsonNotArray: 'El archivo json importado debe contener un array, abortando.'
        },
        pagination: {
          sizes: 'Registros por página',
          totalItems: 'Registros'
        }
      });

**Comment by PaulL1** [comment]
Looks good.  Any chance of getting that in a PR?  There is a first time contributors guide that might help.

**Comment by analista64** [comment]
Please add grouping translation:

 grouping: {
                  group: 'Agrupar',
                  ungroup: 'Desagrupar',
                  aggregate_count: 'Calcular: Cuenta',
                  aggregate_sum: 'Calcular: Suma',
                  aggregate_max: 'Calcular: Máximo',
                  aggregate_min: 'Calcular: Mínimo',
                  aggregate_avg: 'Calcular: Promedio',
                  aggregate_remove: 'Quitar cálculo'
              }
