### ISSUE TITLE
ngGridEventScroll doesnot work for multiple grids

### ISSUE THREAD

**Issue by subsabgolu** [angular-ui/ng-grid#3073]
I have two ng-grids in the same controller. But when i scroll down till the buttom of view port of any of the grid, ngGridEventScroll  is emiited. But i want for the specific grid only? Is there any way to achieve that in ng-grid???

**Comment by jjkovacs** [comment]
Only the grid that you scrolled to the bottom of will emit the event. If you're unsure which grid emitted the event, or if you want to only handle the event for one of the grids, you could do something like:

```javascript
$scope.gridOptions1 = {
   //options for grid 1
}

$scope.gridOptions2 = {
   //options for grid 2
}

$scope.$on('ngGridEventScroll', function(event) {
   if(event.targetScope == $scope.gridOptions2.$gridScope) {
      //do something when scrolling to the bottom of grid 2
   }
});
```

**Comment by subsabgolu** [comment]
Hi
I tried but it does not work.$scope.gridOptions2.$gridScope is undefined.
Any idea why is it giving "undefined"?

Regards
Sabina

On Wed, Apr 1, 2015 at 3:26 AM, jjkovacs <notifications@github.com> wrote:

> Only the grid that you scrolled to the bottom of will emit the event. If
> you're unsure which grid emitted the event, or if you want to only handle
> the event for one of the grids, you could do something like:
>
> $scope.gridOptions1 = {
>    //options for grid 1
> }
>
> $scope.gridOptions2 = {
>    //options for grid 2
> }
>
> $scope.$on('ngGridEventScroll', function(event) {
>    if(event.targetScope == $scope.gridOptions2.$gridScope) {
>       //do something when scrolling to the bottom of grid 2
>    }
> });
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/angular-ui/ng-grid/issues/3073#issuecomment-88264111>.
>



-- 
Best Regards
Sabina Maharjan

**Comment by jjkovacs** [comment]
ngGrid sets $gridScope on your bound gridOptions object during the initialization process of the grid, so once the grid has finished initializing, it should be there. The following is a plunker with it working:

http://plnkr.co/edit/u1BVKGKl9pVom05240Si?p=preview

**Comment by subsabgolu** [comment]
Hi,
Thank you so much.
It is working.


Regards
Sabina

On Wed, Apr 1, 2015 at 10:28 PM, jjkovacs <notifications@github.com> wrote:

> ngGrid sets $gridScope on your bound gridOptions object during the
> initialization process of the grid, so once the grid has finished
> initializing, it should be there. The following is a plunker with it
> working:
>
> http://plnkr.co/edit/u1BVKGKl9pVom05240Si?p=preview
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/angular-ui/ng-grid/issues/3073#issuecomment-88542359>.
>



-- 
Best Regards
Sabina Maharjan
