### ISSUE TITLE
$uiGridIndex should be $$uiGridIndex 

### ISSUE THREAD

**Issue by bringking** [angular-ui/ng-grid#3074]
On the RC20 release, the [rowSorter]( https://github.com/angular-ui/ng-grid/blob/3b4d2ec154f7c3aad9a3eb98e98d45a97d99a2e1/src/js/core/services/rowSorter.js ) code  should not use $uiGridIndex, but instead should use $$uiGridIndex. Added properties onto people's entities can have unintended consequences. For example, in my case I had a dirty watcher using ng.toJson on the entity, to save changes. Simply sorting that column caused the row to be marked as "dirty". Using $$ is the common Angular use case for properties that need to be ignored by the serializer. 
Relevant snippet below.

var setIndex = function( row, idx ){
      row.entity.$uiGridIndex = idx;
    };

**Comment by PaulL1** [comment]
Sure, that's easy enough to change, and since we're immediately deleting the value again it really doesn't matter what it's called.
