### ISSUE TITLE
IE9 Columns don't line up correctly

### ISSUE THREAD

**Issue by msosa** [angular-ui/ng-grid#3075]
I've noticed that sometimes the columns on the grid aren't lining up correctly in IE9.  It seems to work fine in IE11(haven't tested in IE10) and all other browsers.  Below is a screenshot from the tutorial http://ui-grid.info/docs/#/tutorial/214_pagination it's a lot more noticable where I am using it though.
![columns](https://cloud.githubusercontent.com/assets/1843410/6760017/3d16e41a-cf1b-11e4-9d57-55cdabbae375.png)

I think it has something to do with the scroller in ie9 but I'm not sure. Does anyone have any ideas?

**Comment by PaulL1** [comment]
Unfortunately I don't have IE9 to test or diagnose.  There are some scrolling changes coming in the next few days that might fix things, we'll see.

**Comment by msosa** [comment]
Ok thanks, I'll check when the update comes

**Comment by c0bra** [comment]
@PaulL1 well the columns look right but the paging controls don't show up...

**Comment by c0bra** [comment]
I'm going to close this as the original issue seems fixed. I will open a new issue for the paging control positioning.
