### ISSUE TITLE
Setting ngGrid column definition dynamically 

### ISSUE THREAD

**Issue by masoom** [angular-ui/ng-grid#3080]
I have a table whose headers(columns) get populated depending on the click of an object. So every time a user clicks on a tree object, there is a different header and cell contents in the table. The data on the grid is populated from a JSON file and is passed to the property of scope as $scope.data = data.

After I integrated UI Grid in my project, The columns headers don't change. How can you set the column headers dynamically based on the user selection?

Here is my fiddle
https://jsfiddle.net/svcxh6hu/8/

**Comment by paambaati** [comment]
Have you tried the `$scope.gridApi.core.notifyDataChange()` API? I suppose you'd call that to ask ui-grid to redraw.

**Comment by PaulL1** [comment]
The column headings are changing for me in the jsfiddle.  Are you sure they aren't changing for you?

**Comment by PaulL1** [comment]
Further information sought and not provided for 2 weeks, assuming problem has been resolved.
