### ISSUE TITLE
 ui-grid 'ui.grid.selection' messing up grid display in Chrome browser

### ISSUE THREAD

**Issue by dlukianenko** [angular-ui/ng-grid#3081]
As soon as I included  'ui.grid.selection' the table became broken in chrome in another browsers it works fine. I'm using windows 8 Chrome Version 41.0.2272.89 m. 
Please advice.

Thank you

**Comment by PaulL1** [comment]
Do the tutorials work for you, in particular the selection tutorial?  If so, then could you provide a plunker, as it's most likely something that you're specifically doing that is causing the issue.

**Comment by dlukianenko** [comment]
I download code from tutorial and lunched it on my station what how it looks for me http://i.imgur.com/96nDsbF.png

**Comment by dlukianenko** [comment]
Here is my plunker http://plnkr.co/edit/w516VYbVxaTYUMCdMX1O?p=preview

**Comment by masoom** [comment]
@dlukianenko Did you include jQuery?

**Comment by dlukianenko** [comment]
no, I did not. If you go to http://ui-grid.info/ it says "Native AngularJS implementation, no jQuery" the very first header line. So I'm sure that is not about missing jQuery

**Comment by PaulL1** [comment]
Your plunker is running fine for me.  Are you getting any javascript console errors?  Is there something in particular you're doing that gets to that rendering issue - some sequence of actions, or just when you open it?  Does it do it on the tutorial page itself, or only when you download/put it into a plunker/edit it?  The rendering issue you have can be triggered when people are using pinned columns or adding row headers, refer #3050, but it doesn't normally manifest just opening the page.  It can sometimes be resolved by calling handleWindowResize(), but you shouldn't have to do that.

**Comment by dlukianenko** [comment]
I have just opened my plunker and I see issue http://i.imgur.com/VBuF3c2.png and as I can tell I don't have any script errors http://i.imgur.com/tKlYcOL.png. I did not do anything special, I just trying to run code from tutorial.

**Comment by dlukianenko** [comment]
Please also make sure that you have your cache disabled or clean

**Comment by PaulL1** [comment]
@dlukianenko : does it do this when you visit the tutorial page or only on the plunker?

**Comment by dlukianenko** [comment]
no it doesn't

**Comment by PaulL1** [comment]
OK, so it is something different between the plunker and the tutorial?  Are there differences?

**Comment by dlukianenko** [comment]
the difference only that I did not include main.css file and the font files, but it should not reflect on the ui-grid behavior

**Comment by PaulL1** [comment]
The main.css may impact.  Have you tried including it?

**Comment by dlukianenko** [comment]
As soon as I included main.css with these two properties, the grid started acting normal, as soon as I remove the main.css the grid starts acting up. 
Please see http://plnkr.co/edit/w516VYbVxaTYUMCdMX1O?p=preview and try to include and exclude main.css file. The problem is that in my project I don't have main.css file I have other css files and the grid should not depend on such crazy stuff. Could you please assist how I can fix this issue or to find some work around.

**Comment by PaulL1** [comment]
The grid does depend on the height and width being defined.  You don't have to have a main.css, you do have to have set the height and width on the div that contains the grid.  This is known and well documented (e.g. http://ui-grid.info/docs/#/tutorial/108_hidden_grids).

**Comment by dlukianenko** [comment]
It is truly works when you set the width and height properties to the grid or to the container which holds the grid. I read the grid-ui documentation very carefully, but this important piece of information is located in the section of the documentation where in my case the user can just miss. My suggestion maybe it would be better to emphasis such moment somewhere here http://ui-grid.info/docs/#/tutorial/101_intro. Thank you very much for your assistants, quick responses to solve my kinda dummy problem. I do really appreciate your help. Thank you very much.
