### ISSUE TITLE
RTL(right to left) option in UI-GRID is not working properly.

### ISSUE THREAD

**Issue by ntio7** [angular-ui/ng-grid#3082]
I tried to work with RTL in ui-grid but there are some problems with it. 
minimizing/maximizing columns, is working on the opposite way,
and the column sub menu (ui-grid-menu), go left.
Which variables I need to change in order to fix this problem?

**Comment by novice3030** [comment]
Make sure you use dir="rtl" on the ui-grid directive
בתאריך 22 במרץ 2015 05:54, ‏"Netanel" <notifications@github.com> כתב:

**Comment by c0bra** [comment]
@novice3030 Actually the grid should inherit the `dir` property from its parents.

**Comment by PaulL1** [comment]
Closing: solution proposed that should resolve the issue, no further comments for 2 weeks, assuming solution has resolved issue.

**Comment by KasMA1990** [comment]
I'm having trouble getting this to work, but I can't find any official documentation on how this should work. It would be nice with an example :)

**Comment by blowsie** [comment]
I am using dir='RTL' on my html element and found that the grid headers are working in RTL but the content is not.
![image](https://cloud.githubusercontent.com/assets/308572/18084680/02997958-6ea0-11e6-8ede-847df1eca6aa.png)

**Comment by TheFrohlich** [comment]
+1

**Comment by mmoman1993** [comment]
I am currently facing the same issue... did any body solve it ??

**Comment by rashel3014** [comment]
This worked for me (on chrome; I used jquery to address the grid):

After page load:
$scope.$timeout(function () {
	$(".gridClassName").attr("dir", "rtl");
});

After manual API core refresh:
$(".gridClassName").attr("dir", "rtl");
