### ISSUE TITLE
Groupheadertext doesnt show up on deeper fields 

### ISSUE THREAD

**Issue by GEdelmann** [angular-ui/ng-grid#3086]
If i define a column like

<code>{name: 'Author', field: 'author.name'}</code>

and group by that column, the row-group-headertext is empty. 
Reason: field is not on the root level of the datasctructure (like author.name)

**Comment by PaulL1** [comment]
This is known and documented in the grouping tutorial.

**Comment by PaulL1** [comment]
Grouping will still be beta in 3.0, moving to 3.1

**Comment by PaulL1** [comment]
Fixed a wee while back in the grouping refactor.
