### ISSUE TITLE
How do i change particular column value on runtime in angularjs ui grid

### ISSUE THREAD

**Issue by Nisha-Sharma** [angular-ui/ng-grid#3087]
How do i change particular column value on runtime in angularjs ui grid? I have to perform following scenario ?
When there is ACTIVE in Grid then the column should disable.
When there is DRAFT in grid and user click on this option then only two option of selectbox should visible i.e DRAFT and RELEASE?
When there is Release in grid and user click on this option then only three option of selectbox should visible i.e DRAFT, ACTIVE, RELEASE.

http://plnkr.co/edit/O57gmOAYgybEcXM1Uxu7?p=info

**Comment by GEdelmann** [comment]
The selection stores a copy of the list provided with <code>editDropdownOptionsArray: $scope.genderTypes</code> and there is no binding between that copy and the original list. I don't think there is a way to update the copy using the api currently (v20).

**Comment by PaulL1** [comment]
I think using the row-based dropdown will allow what you're seeking. `editDropdownRowEntityOptionsArrayPath`

**Comment by PaulL1** [comment]
@GEdelmann: I don't think that's correct.  I don't recall writing a copy anywhere in there, and the code appears to refer directly to columnDef.editDropDownOptionsArray.

For what reason do you say it's a copy and not a binding?

**Comment by mohitgupta2209** [comment]
Hi, you can achieve it by maintaining different dropdownOptionsArrays for each state DRAFT, RELEASE, ACTIVE.

$scope.gridOptions.columnDefs : 
{ name: 'state', displayName: 'State', width: '20%', editableCellTemplate: 'ui-grid/dropdownEditor',
      cellFilter: 'mapState', editDropdownValueLabel: 'state', editDropdownRowEntityOptionsArrayPath: 'stateOptions' }
  ]


 $scope.draftStateDropdownOptions = [
    { id: 1, state: 'DRAFT' },
    { id: 2, state: 'RELEASE' },
    { id: 3, state: 'ACTIVE' },
    
  ];

 $scope.activeStateDropdownOptions = [
      { id: 2, state: 'RELEASE' },
    { id: 3, state: 'ACTIVE' },
    
  ];



 gridApi.edit.on.afterCellEdit($scope,function(rowEntity, colDef, newValue, oldValue){
      if( colDef.name === 'state' ){
        if( newValue === 1 ){
          rowEntity.stateOptions = $scope.draftStateDropdownOptions;
        } else {
          rowEntity.stateOptions = $scope.activeStateDropdownOptions;
        }
      }

**Comment by PaulL1** [comment]
Solution provided 3 weeks ago, no comments since.  Assuming issue has been resolved.
