### ISSUE TITLE
access selected row data

### ISSUE THREAD

**Issue by Shanna7463** [angular-ui/ng-grid#3088]
I am trying to access the data in a particular column of a row that has been selected.  I'm using the rowSelectionChanged event and trying to access the data via entity, but it isn't working.  Here is what I have: 

    $scope.gridOptions = {
    paginationPageSizes: [10, 25, 50],
    paginationPageSize: 25,   
    useExternalPagination: true,
    useExternalSorting: true,
    multiSelect: false,
    enableSelectAll: false,
    columnDefs: [
      { name: 'Name', field: 'properties.Name'},
      { name: 'Address', field: 'properties.Address'},
      { name: 'PhoneNumber', field: 'properties.PhoneNumber'}
    ],

    onRegisterApi: function(gridApi) {
        $scope.gridApi = gridApi;
        $scope.mySelectedRows = $scope.gridApi.selection.getSelectedRows();
        gridApi.selection.on.rowSelectionChanged($scope, function(row) {
            var msg = row.entity.Name;
            alert("Row Selected! " + msg);
        });
    ...

row.entity.Name (also tried row.entity.name) is returning nothing.  What am I doing wrong?

**Comment by PaulL1** [comment]
Does it return a single row or an array?  Try logging out `row` and see what's in it, or put a breakpoint and look at the variable directly.

**Comment by Shanna7463** [comment]
Added a breakpoint...that totally cleared it up...it was returning a single row (presumably because I have multiSelect set to false).  I just needed to change it to "row.entity.properties.Name", and now it works just fine.  Thank you! :)

**Comment by c0bra** [comment]
@Shanna7463 Great! Glad you got it working.

**Comment by sinaisix** [comment]
Hi. I've a similar issue. 

Here is my code 
```
 $http.get("./resources/departments").success(function (data) {
            vm.gridOptions.data = data;
            $log.log("Successfully retrieved data: " + data)
        }).error(function (error, headers) {
          vm.gridOptions.data = [];
            $log.log(headers);
            $log.log(error)
        });

  vm.gridOptions = {
            autoResize: true,
            enableRowSelection: true,
            enableSelectAll: true,
            selectionRowHeaderWidth: 35,
            rowHeight: 35,
            enableGridMenu: true,
            enableFiltering: true,
            enableSorting: true,
            enableSelectionBatchEvent: false,
            enableRowHeaderSelection: false,
            noUnselect: true,
            columnDefs: columnNames,
            onRegisterApi: function (gridApi) {
                vm.gridApi = gridApi;
                //gridApi.selection.selectRow(vm.gridOptions.data[0]);
                gridApi.selection.on.rowSelectionChanged($scope, function (row) {
                    console.log(row.entity.id);



                });
            }

        };
```
Now let's say I've 5 rows of data, each representing a department. When the page renders fresh, selecting (first click on the grid) a row logs the department id just fine. But any other selection, I have the id of the previous row and the newly selected row both logged to the console. 

Essentially, apart from the very first click on the on the grid when it renders, all subsequent clicks give me both two ids. All I want is the id of the entity of the currently selected row.


![grid](https://cloud.githubusercontent.com/assets/3254773/7644318/c98c930c-fa92-11e4-8a47-fa9ed07ef568.png)

**Comment by PaulL1** [comment]
Two row selections have changed.  One row changed from selected to unselected, one row changed from unselected to selected.  If you want only the newly selected row then you need to check the selected property on the row (maybe it's isSelected?)

**Comment by sinaisix** [comment]
Thanks a lot. Modifying the code thus 

```
if(row.isSelected){
                        console.log(row.entity.id);

                    }``` 

now I get only the id of the entity in the currently selected rows. Thanks. 

I think somehow I misunderstood this part of the documentation

is raised after the row.isSelected state is changed

```
Parameters
row – {GridRow} – the row that was selected/deselected
event – {Event} – object if raised from an event```


Thanks again for your time. Very much appreciate it.

**Comment by vikasmadineni** [comment]
how to get data all selected rows in ui-grid
