### ISSUE TITLE
highlight column

### ISSUE THREAD

**Issue by aaronloe** [angular-ui/ng-grid#3091]
how do you apply column-level css ? As in, if a mouse hovers over a cell, then that cell's entire column is highlighted ?

**Comment by c0bra** [comment]
You would need to do it with javascript. The DOM is built row first, then column, so there's no container object for just the column set you want.

Each column does have a specific class, though. You could have a mouseover event callback that will check the column's unique class and add a special dynamic stylesheet with a highlight class, which is then is removed on mouseout.

**Comment by aaronloe** [comment]
Yup. This is what I ended up doing since posting the question. After my controller's row-data update event handler finishes, I just set up the jQuery .hover event on all elements with that column's specific class name:

function applyColumnStyles(colClass) {
            $("." + colClass).hover(function() {
                $("." + colClass).addClass("ColHover");
            }, function() {
                $("." + colClass).removeClass("ColHover");
            });
        }

Thanks for the help anyways.
