### ISSUE TITLE
Grid Menu only should "Columns:" as an item

### ISSUE THREAD

**Issue by tarunbatta** [angular-ui/ng-grid#3092]
The Grid Menu implementation only should "Columns:" as an item, and nothing else.

The following are the options,
gridOptions: {
	exporterMenuCsv: false,
    	enableGridMenu: true
}

<div ui-grid="vm.gridOptions" class="grid" ng-style="vm.gridwidth" ui-grid-pagination ui-grid-auto-resize ui-grid-exporter></div>

![weirdgridmenu](https://cloud.githubusercontent.com/assets/1251794/6791924/2a626c84-d170-11e4-8a6d-9bf945bcca48.png)

I am using ui-grid - v3.0.0-rc.20 - 2015-02-24.

**Comment by PaulL1** [comment]
The only menu items you get by default are exporter and enabling/disabling columns.  But it looks to me like the menu is compressed and would scroll if you tried scrolling it, and that there would be a list of columns there.  So the real question is why it's decided to use such a small height.

**Comment by PaulL1** [comment]
Closing: further information sought and not provided, and looks like the problem had a reasonably easy resolution, assuming it was resolved.
