### ISSUE TITLE
How to resize ui-grid cells height depending on it's content?

### ISSUE THREAD

**Issue by dlukianenko** [angular-ui/ng-grid#3094]
There is need to let the ui-grid cell to be adjustable depend on it's content. It is possible to do?

**Comment by PaulL1** [comment]
Not really.  The grid relies on all rows having the same height to calculate scrolling.

**Comment by dlukianenko** [comment]
If I'm going to use whole page scroll and pagination for ui-grid, can I make it work somehow in this case? Any ideas? Advice?

**Comment by PaulL1** [comment]
It's been asked before a few times, so you could search the issues.  But I think the general answer is that it doesn't work well.

**Comment by dlukianenko** [comment]
I have one more question. I have for each row cell custom template when I get data from the server to fill up my grid I can see only header but then after refreshing the page a few times with f5 the content appears in the table then when I refresh the page it could stay or could be again shown only header of the grid. To get data from the server I'm using service which returns promise and when I resolve this promise I apply data to gridOption.data of the grid.

positionService.search(self.eventId, allPositionQuery).success(function (result) {
       self.gridOptions.data = result.reference;
}).error(function (error) {
});

What could be problem over here?

**Comment by PaulL1** [comment]
You probably need to show a plunker.  Plenty of the tutorials get data from the server, there's probably something with your timing.

**Comment by dlukianenko** [comment]
my code looks like this http://plnkr.co/edit/09aAnz0Cou1MowtrmlEa?p=preview it works here, but in my ASP.Net project it acts like I described it above http://i.imgur.com/jdcEzKJ.png. When I look at console I see requests to get templates for the grid and between these request the promise returns http://i.imgur.com/r1URtvR.png.

**Comment by c0bra** [comment]
Sounds like we can try to reproduce by having the cellTemplate and headerTemplate return AFTER the data promise, or one after the other with the data in-between.

**Comment by dlukianenko** [comment]
Yep sounds like good idea

**Comment by PaulL1** [comment]
Any chance you could try to get a recreate in the plunker - if we had a reliable recreate it'd be much easier to fix.  You could just put the template retrieves inside a timeout to get the right ordering perhaps.

**Comment by dlukianenko** [comment]
ok, let me try to recreate it

**Comment by dlukianenko** [comment]
I can't really do anything with plunker, but for example if I give the gridOptions.data the static set of data in the controller the grid contents loads without problems but as soon as I change it to get JSON from the server the grid starts acting up. I think the best way to reproduce it is place the templates and JSON data to the server and try to access it from it

**Comment by dlukianenko** [comment]
I resolved this problem by loading all cellTemplates before loading data from the server.
