### ISSUE TITLE
Slecting a row after data insertion

### ISSUE THREAD

**Issue by feralanPaladin** [angular-ui/ng-grid#3097]
Hi,

Is there any equivalent of "ngGridEventData" event on ui-grid version 3.x. I am trying to select the newly incoming data row.

**Comment by PaulL1** [comment]
There is no event triggered when data is added.  The assumption is that your code added the data, therefore knows what it added.  You can select a row based on the entity it is based on, presumably that's the last row in your data array?

**Comment by feralanPaladin** [comment]
Actually I have added the empty data to the top of the grid data, so after
addition operation, first daha row became empty as I expected. But when I
select the first row after insertion operation, just the second row became
selected ( second row contains the first row element before insertion).
Thats why ng-grid has an event mechanism which i was using for this puspose.
24 Mar 2015 11:46 tarihinde "Paul" <notifications@github.com> yazdı:

**Comment by c0bra** [comment]
@feralanPaladin You have to select the row in a timeout. The data won't be updated in the grid until after the digest cycle, once it notices you've changed the data. Before that happens your element is not in the grid's rows and it won't have anything to select.

The selection tutorial shows this in its code: http://ui-grid.info/docs/#/tutorial/210_selection

And I've created a plunker for your use case: http://plnkr.co/edit/h1xVQeohSv9O4TeMaqdT?p=preview

**Comment by feralanPaladin** [comment]
Thank you Brian,

Timeout is the silver bullet for the angular problems.
That will solve my problem.
24 Mar 2015 18:16 tarihinde "Brian Hann" <notifications@github.com> yazdı:

**Comment by c0bra** [comment]
Glad it worked for you!
