### ISSUE TITLE
Browser window resize causes the vertical scroll bar to disapear

### ISSUE THREAD

**Issue by feintus** [angular-ui/ng-grid#3098]
Hi,
I have my grid set on gridOptions.enableVerticalScrollbar = 2; // When Needed.
When my browser window is in full size I see the vertical scroll bar in "disable" mode since I have only a few rows (3) and it is not required.

If I in that state resize the browser window and then full size it again the scroll bar disappears completely and I still haven't managed to figure out why.

**Comment by c0bra** [comment]
I believe `WHEN_NEEDED` is no longer a valid option: https://github.com/angular-ui/ng-grid/blob/master/CHANGELOG.md#breaking-changes

**Comment by feintus** [comment]
Yep!
I removed it from my code and it worked! thanks. :+1:

**Comment by c0bra** [comment]
I'm having trouble reproducing this issue. Can you answer a few questions?

1. What version of UI-Grid are you using?
2. What browsers does this occur in?
3. Can you set up a plunker that demonstrates this problem?
4. If not, can you walk me through creating a grid that has this problem? i.e. what is the exact CSS you're using on the grid and its parent container(s), what options you have turned on, etc.

**Comment by c0bra** [comment]
No response in > 2 weeks. Closing.
