### ISSUE TITLE
angularjs ui-grid doesn't update the scope in jquery ui-popup

### ISSUE THREAD

**Issue by neran27** [angular-ui/ng-grid#3101]
Am new to the angularjs-ui grid thing, excuse me if am wrong.  My scenario is got two grids, master grid rendered on the page - and on click event of the cell template of the master grid need to show a jquery ui-popup which is again going to render the 2nd Grid. 
Master Grid :
 <div class="panel-body" data-ng-hide="!viewMode">  
<div id="grid1" ui-grid="gridOptions" ui-grid-selection class="grid"></div>
</div> 
2nd Grid :
<div id="div2" class="panel-body"> 
<div id="grid2" ui-grid="gridHistoryOptions" ui-grid-selection class="grid"></div>
</div>

$("#div2").dialog("open")  { will render the pop-up with second grid, }

But the opened dialog is not rendering the gridHistoryOptions

Same time, getting the initial error like "Unable to get property 'data' of undefined or null reference" - "Type Error" - Error Number : -2146823281

on debugging able to trace to the uiGridController is throwing the above error.

**Comment by neran27** [comment]
Am not building on bootstrap UI, so ther is no need for me to go with the modalService, or anything else, just on the jquery ui-pop need to render the ajs ui-grid. Please, help me in resolving this. (Am new here, sorry if am went wrong anywhere)

**Comment by c0bra** [comment]
@neran27 How are you passing data into your dialog? Angular does scope inheritance by element ancestry, so if the dialog element is being appended to the `<body>` then your 2nd grid won't be able to access any properties from the original controller's scope.

**Comment by neran27** [comment]
@c0bra  For the second grid, the data binding is from the service, which is written on the first grid's cell template function defined.

**Comment by c0bra** [comment]
@neran27 Can you unpack what you mean by the service being written on the first grid's cell template function?

**Comment by neran27** [comment]
ya GET Service Call from WebAPI.. $http.get{ url: 'url' on success assigning to $scope.grid2Options=data; }

**Comment by neran27** [comment]
@c0bra  Am able to get the data flowing to the 2nd popup ui-grid wrong handling of '$scope' variable. But am getting the Total Items : followed by multiple line spaces and then followed by the grid. Y that so... Can you please, help me in fixing that.
![popup_ui_grid](https://cloud.githubusercontent.com/assets/8090439/6821218/d6b7cf60-d2ab-11e4-86f0-daae74bdc4f2.png)

**Comment by c0bra** [comment]
@neran27 Could it be something with the CSS of the modal. Looks like your one row (do you only have one row) is wrapping around the bottom of the viewport, but "Total items" is somehow at the top.

Are you able to create a plunker that reproduces this? That would make helping you much, MUCH easier.

**Comment by PaulL1** [comment]
Have been waiting for a plunker for 2 weeks, assuming that raiser has resolved their issue.
