### ISSUE TITLE
UI Grid CSV Exporter opens new tab in Safari instead of downloading file

### ISSUE THREAD

**Issue by mrodrig** [angular-ui/ng-grid#3102]
Hi,

I was just testing my new ui-grid in Safari (v8.0.4) and noticed that the ui.grid.exporter is currently causing a new tab to be opened with the CSV data inside it instead of downloading the CSV file.

Here's an example plnkr: http://plnkr.co/edit/JwDo7Bdwa3pkwETfYrxX?p=preview

I'm currently using RC.20, but was wondering if there is a known fix or if a newer release fixes this?

Thanks,
Mike

**Comment by PaulL1** [comment]
The tutorials have the latest.  The csv file should always download, and I don't think it changed rc20 v's the latest, but check the tutorial on safari to be sure.

**Comment by PaulL1** [comment]
OK, I get the same behaviour.  I'll take a look.

**Comment by mrodrig** [comment]
Thanks, Paul!

**Comment by PaulL1** [comment]
OK, short answer here as it turns out.  Safari doesn't support the html5 download attribute, therefore there is no way to make it download instead of opening in a new tab.  So the fallback behaviour is exactly what it's doing.  I think this one would therefore be a can't fix?

**Comment by mrodrig** [comment]
Ok, that makes sense.  Based on what I found (http://caniuse.com/#feat=download), IE 11 also doesn't support the download attribute, but the CSV Export is working and initiates a download when I just tested it.  I haven't looked through the source, but is it possible that IE is being handled a different way? If so, I wonder if that approach might also work for Safari?

**Comment by PaulL1** [comment]
It is being handled differently, but it's a classic ugly IE hack.  I suspect it won't work in Safari, and I didn't see a suggestion of how safari might work.  I didn't actually write that - the code was provided by someone else, and I don't have IE to even test it.  I seem to recall that it adds an iFrame and then does something tricky with that frame.

**Comment by mrodrig** [comment]
Thanks for looking into it, Paul.  Safari not working isn't a huge issue for the app I'm working on.  Hopefully Apple will implement the download attribute in Safari at some point in the near future

**Comment by PaulL1** [comment]
OK, looks like we can't do anything with the current state of browser support....closing.

**Comment by gordol** [comment]
What about support to use a web service of some kind to accept the blob content and a filename, and then it reflects it back to the client with proper headers? Should be easy to put together a few examples... That sort of client-side functionality could be useful anyway, for example if anyone wanted to ever export the data to a server.

**Comment by cyclemycity** [comment]
Actually, I found that by changing "var strMimeType" to 'data:attachment/csv' Safari will automatically download the file, but it is named 'unknown' and you need to add the .csv extension to open it. Perhaps someone can work out how to set the filename with this approach?
