### ISSUE TITLE
Expandable ui-grid, action column don't working. Help me!

### ISSUE THREAD

**Issue by lungkuteo** [angular-ui/ng-grid#3104]
Angular ui grid 3.x
How to use action button in expandable grid? Funtion getExternalScope() don't working. Thanks!
This is my code http://plnkr.co/edit/VHuE151KUFx0ImVPuHy2?p=preview

**Comment by PaulL1** [comment]
http://ui-grid.info/docs/#/tutorial/306_expandable_grid

Expandable scope.

**Comment by PaulL1** [comment]
Closing: solution proposed that should resolve the issue, no further comments for 2 weeks, assuming solution has resolved issue.
