### ISSUE TITLE
How can I add more languages fonts to export pdf option in ui-grid? 

### ISSUE THREAD

**Issue by ntio7** [angular-ui/ng-grid#3105]

**Comment by PaulL1** [comment]
Sorry, it's not clear what you're asking.  If you mean more languages to the i18n, then you would submit a PR for additional languages, the files are in the src/js/i18n folder.  If you mean controlling the font selected by the pdf, then you need to use the font configuration options of pdfMake.

**Comment by PaulL1** [comment]
Closing: solution proposed that should resolve the issue, no further comments for 2 weeks, assuming solution has resolved issue.
