### ISSUE TITLE
Grid columns don't respect percentage widths that add up to less than 100%

### ISSUE THREAD

**Issue by c0bra** [angular-ui/ng-grid#3111]
Check this plunker to see the behavior: http://plnkr.co/edit/4YZbaJJvjZE85Bj0VciQ?p=preview

If I have 4 columns and set them all to `width: '4%'` then they appear to ignore it and divide up the viewport evenly. If I instead give 3 columns 4% width and leave one unset, then the first 3 columns will work as expected and the final column will fill the rest of the space.

**Comment by PaulL1** [comment]
Hmm.  I think after I recoded the updateColumnWidths I kept exactly this behaviour. 

The question is what we do with 'leftover' width.  At the moment the grid works pretty hard to fill that width, and that makes things behave nicely when you use resize.  Basically any column that doesn't have a fixed pixel width we're treating as something we can adjust.

It'd be pretty easy to change that logic to only adjust columns that have '*' (or nothing) for their width.  Is that the behaviour you think we should have?

**Comment by c0bra** [comment]
Yes, that's what it should do. I should be able to split up less than the total viewport width among my columns however I want.

**Comment by mscelina** [comment]
I see other issue related with this, too.
How about when columns '*' have maxWidth set to it? This is not respected, too. See plunker: http://plnkr.co/edit/nlXKsjjmlUsYKQylT3g9?p=preview
If there is free space on viewport the columns get additional pixels.
Other issue which is partially related with this one is when you use minWidth for '*' columns. When first columns has low minWidth and others have greater minWidth we can get scroll even if the column with small minWidth could be smaller. See plunker: http://plnkr.co/edit/N9P7zsJr2AsKCOvlStO7?p=preview
