### ISSUE TITLE
bootstrap-typeahead is not working in ui-grid

### ISSUE THREAD

**Issue by DavidV1** [angular-ui/ng-grid#3115]
Thank you for the great UI-Grid !

It works very well for me except for one thing : Autocomplete does not seem to work in **ui**-grid (it works in **ng**-grid).

Working example in ng-grid
http://plnkr.co/edit/w4EBcKBsN3X814Hyr7h9?p=preview

Not working example in ui-grid
http://plnkr.co/edit/hK9MLRX3VxZA1HWlWNg0?p=preview

I don't think this problem is related to issue [435 - bootstrap-typeahead is not working in **ng**-grid ] (https://github.com/angular-ui/ng-grid/issues/435)

Could you help please ?

**Comment by PaulL1** [comment]
his looks to be an appScope issue - it works if you use `grid.appScope.states`, not with simply `states`.

http://plnkr.co/edit/ai91kJMiApXktc4vM4mt?p=preview

**Comment by DavidV1** [comment]
Paul thanks a lot for taking some time to look into this.
It works for me now !

Should we consider this a bug ?

**Comment by PaulL1** [comment]
No, expected behaviour - this is how we access things on the controller scope.  So I'll close.

**Comment by syedrehman** [comment]
Hi Everyone.

I would  like to thank for helping in angular UI grid queries. I am developing one application where In my UI grid. I am using autocomplete view in one cell. I need to use ng-change in that cell. but ng-change is not invoking in it. Please help me out.below is the code.

     $scope.cellProductUsageEditableTemplate = '<div class="typeaheadcontainer"><input type="text" ' +
    'class="typeaheadcontrol"' +
    'ng-model="grid.appScope.productsExcelExport.data[rowRenderIndex].ProductUsage" ' +
    'uib-typeahead="ProductUsage as PU.ProductUsage for PU in  grid.appScope.ProductUsage | filter:$viewValue | limitTo:8" ' +
    'ng-required="true" ' +
    'typeahead-editable ="false"' + 'ng-change="ProductUsageValueChange()"' +
    'typeahead-on-select="grid.appScope.typeaheadPUSelected(row.entity, $item)" ' +
    '/></div>';

 $scope.ProductUsageValueChange = function ()
    {
        alert('Hi');
    }

**Comment by Gerodork** [comment]
When trying to access functions in your scope, you must use "grid.appScope.yourfunction()"

In your case ` ng-change="grid.appScope.ProductUsageValueChange() "` if your function is in the same scope as your grid
