### ISSUE TITLE
Sort by headerCell click?

### ISSUE THREAD

**Issue by dlukianenko** [angular-ui/ng-grid#3116]
How can I trigger built in ui-grid sort by clicking on the header cell?
Thank you for your answers in advance.

**Comment by PaulL1** [comment]
You mean trigger it programatically, not by clicking on the cell?  You set the sort object on the columnDef, refer the sorting tutorial.

**Comment by dlukianenko** [comment]
I was thinking of using the function which is used by ui-grid when you click on the drop down menu to sort in my custom headerCellTemplate

**Comment by PaulL1** [comment]
In that case you'd just need to replicate the same logic/template as that in the default header cell template, since that also sorts when you click on it?

**Comment by dlukianenko** [comment]
that is what I was trying to do but for some reason the sortColumn($event, asc) function is not triggered by click. 

my headerCellTemplate looks the next 

<div ng-class="{ 'sortable': sortable }">
    
    <div class="ui-grid-cell-contents" col-index="renderIndex">
        <span>
            Pos {{ CUSTOM_FILTERS }}
         
            <span class="th-sort">
                <span ng-click="sortColumn($event, asc)">
                    <i class="fa fa-caret-up" ng-class="{ 'fa-caret-up': col.sort.direction == asc, 'fa-caret-up': col.sort.direction == desc, 'hello': !col.sort.direction }"></i>
                </span>
            </span>
        </span>

        <span ui-grid-visible="col.sort.direction" ng-class="{ 'ui-grid-icon-up-dir': col.sort.direction == asc, 'ui-grid-icon-down-dir': col.sort.direction == desc, 'ui-grid-icon-blank': !col.sort.direction }">
            &nbsp;
        </span>

    </div>

    <div class="ui-grid-column-menu-button" ng-if="grid.options.enableColumnMenus && !col.isRowHeader  && col.colDef.enableColumnMenu !== false" ng-click="toggleMenu($event)" ng-class="{'ui-grid-column-menu-button-last-col': isLastCol}">
        <i class="ui-grid-icon-angle-down">&nbsp;</i>
    </div>

    <div ng-if="filterable" class="ui-grid-filter-container" ng-repeat="colFilter in col.filters">
        <div ng-if="colFilter.type !== 'select'">
            <input type="text" class="ui-grid-filter-input" ng-model="colFilter.term" ng-attr-placeholder="{{colFilter.placeholder || ''}}" />

            <div class="ui-grid-filter-button" ng-click="colFilter.term = null">
                <i class="ui-grid-icon-cancel" ng-show="!!colFilter.term">&nbsp;</i> 
            </div>
        </div>

        <div ng-if="colFilter.type === 'select'">
            <select class="ui-grid-filter-select" ng-model="colFilter.term" ng-attr-placeholder="{{colFilter.placeholder || ''}}" ng-options="option.value as option.label for option in colFilter.selectOptions"></select>

            <div class="ui-grid-filter-button-select" ng-click="colFilter.term = null">
                <i class="ui-grid-icon-cancel" ng-show="!!colFilter.term">&nbsp;</i> 
            </div>
        </div>

    </div>
</div>

**Comment by PaulL1** [comment]
http://plnkr.co/edit/aVqs1mRIstqVNOAvLvhy?p=preview works for me.

I suspect you've left something out of your template that's important.

**Comment by dlukianenko** [comment]
In your plnkr you have standard sort from dropdown menu. I need to trigger sort by clicking on table header name. I saw that ui-grid is using sortColumn function to sort but I can't trigger it from my headerCellTemplate

**Comment by PaulL1** [comment]
The plunker also allows sort by clicking on the column heading.  You can remove the column menu either by removing the html for it, or by setting enableColumnMenu to false.

**Comment by dlukianenko** [comment]
Could you please specify on which one? I'm clicking on all header sections and it is not sorting. I'm using windows 8 chrome Version 41.0.2272.101 m

**Comment by PaulL1** [comment]
Ah.  On a touch-enabled computer?  We have a bug where touch enabled computers that also have a mouse only respond to touch events.  We're part-way through a fix for that.

**Comment by dlukianenko** [comment]
yep, I have touch one. Now I can see. Yep it is working thanks.
