### ISSUE TITLE
Support for tooltips on column headers

### ISSUE THREAD

**Issue by AgDude** [angular-ui/ng-grid#3118]
It appears that currently in order to put a tooltip on a column header, I would need to use a custom template. Consider this a feature request for a columnDef option ```headerCellTooltip```. 

In this case I would like to use a static string, but I could see the use case for a function or the displayName, similar to the cellTooltip.

**Comment by akashdeepg12** [comment]
please provide support for tooltips on column headers as like ui-grid.

as per above disscussion,i have tried headerCellTooltip in column defintion of PrimeNg table but still it is not working . 
Please provide me alternative of this issue.

Thanks
