### ISSUE TITLE
Sorting of data on server

### ISSUE THREAD

**Issue by davidkaminsky** [angular-ui/ng-grid#3119]
Hello,

I've been working with ui-grid for about a week and it's been working great. There's one feature I haven't been able to find and am wondering if I'm missing it or if I need to look into developing it myself and submitting a pull request.

I'm using the infinite scroll directive on the grid to continually get more data. We're expecting the dataset to realistically be up to ~50,000 rows and don't want to load that all at once. However, we do want to allow sorting on the columns and we want the sort to occur on all of the rows, not just the ones that have been loaded. Thus, we'd need to call the server to get new data when sorting by a column. I'm not seeing how to hook into the grid API to do this. I see there's a sort function but that appears to be to change how the sort works on the data that's loaded instead of replacing the entirety of what sort should be doing (i.e. calling the server, getting new data, etc. as opposed to ordering the data that already exists in the grid).

Am I missing something or is this not something that can be done? I took a look at ng-grid 2.0 as well and unless I'm missing something there too I don't see this functionality either. Can anyone offer me some guidance?

Thanks!

**Comment by PaulL1** [comment]
I think this is what the externalSorting option is for.

The grid can only sort the data it can see, so obviously can't sort rows that are on the server.  But what it can do is to tell you whenever the sort changes, and you can then bake the sort criteria into your server call, and refresh all the pages.

I don't recall all the ins and outs of external sorting, but I do recall building it. :-)  I think that it keeps the UI actions the same as if we'd done the sorting internally, but it actually bypasses all sorting, and you hook onto the sort changed event to know that you need to refetch the data.  I seem to recall there's a tutorial on it.  I've never connected it to infinite scroll, but there's no reason it shouldn't work.

**Comment by cookednoodles** [comment]
We are currently doing this in production. When we get a sort event we do a first api call to get back a list of sorted ids, we then do subsequent api calls to get the rows related to those ids.

**Comment by PaulL1** [comment]
@cookednoodles: ugh.  Why would you get the ids then later the data?  Surely that'll create a lot of round trips?  Wouldn't it make more sense to just get the list of data back when you got the ids?

**Comment by davidkaminsky** [comment]
So I've implemented this right now and I think I'm maybe seeing the problem you're referring to here. I set gridOptions.data = [] and then call the function to get more data. When the data returns it sets gridOptions.data to the data that comes back. This all works but when I think scroll down it doesn't get more any more users. Is there any workaround for this at the moment? Thanks!

**Comment by PaulL1** [comment]
Not sure that's quite the same thing, but it could be related.  Which version are you using - are you on unstable?  (the behaviour will be different with unstable v's rc20)

**Comment by davidkaminsky** [comment]
I was on an unstable version but maybe not one of the most recent versions with the different behavior. I just got it and tried it now and it appears that issue is now gone. However, it's not scrolling back up to the top of the viewport. It seems like that's what you were talking about previously.

**Comment by PaulL1** [comment]
Yep, that's it exactly.  I'm working on that now.

**Comment by davidkaminsky** [comment]
Thank you!

**Comment by PaulL1** [comment]
OK, there's a much more elaborate infiniteScroll there now, including a change to trigger getting more data based on # of rows from the end, not %.  I've also added a method that lets you grab the scroll position right before you update the data, rather than us using the scroll position before you started fetching the data from the server - this should take some of the lumps of the scroll smoothness.

It's still not as good as it could be, and I'm hoping that @swalters new changes to scrolling will give some new options that might smooth it out some.

**Comment by davidkaminsky** [comment]
This is great! Thank you!

**Comment by davidkaminsky** [comment]
I'm seeing a problem that I'm assuming is related to this change. When I've reached the end of my results the scrollbar is still in the middle of the viewport and I see a lot of empty space below the entries.

I am telling dataLoaded that it should no longer be able to scroll and that seems to be working as I'm not seeing anymore calls to get more data.

vm.gridApi.infiniteScroll.dataLoaded(false, (page * numResultsPerPage) < result.numTotalUsers);

![screen shot 2015-03-30 at 2 38 56 pm](https://cloud.githubusercontent.com/assets/1380808/6907378/8f1b5364-d6ea-11e4-88f8-d952dccf174c.png)
