### ISSUE TITLE
when is a row not equal to itself?

### ISSUE THREAD

**Issue by steverA** [angular-ui/ng-grid#3121]
A colleague is developing part of our LARGE application and has a grid the is initially invisible and then at the click of a button, it is drawn. I have something similar in concept with tabs. Mine works - his fails for a reason that makes no sense. We have a function in scope that calls gridApi.cellNav.scrollToFocus. The entity we pass in is from $scope.gridOptions.data[].

When his grid is hidden, he calls scrollToFocus for the first row in the grid and it works. When he clicks the button, the grid appears. If he clicks on a row, his code calls the scrollToFocus. This is where it gets weird. Best shown by a picture. Debugging in IE-11, I see:
![2015-03-26-113620-jabberwindow desktopshare borderwindow](https://cloud.githubusercontent.com/assets/9431902/6851980/835f6928-d3b8-11e4-82c9-a7773ceb88b7.png)

How can $scope.gridApi.grid.rows[1].entity **be different** from $scope.gridOptions.data[1]? Is there some circumstance where a copy is made under the covers as his grid is being rendered? I looked at the two items in the debugger and they appear to be the same. 11 properties and the same $$hashKey in both.

I'm using v3.0.0-rc.20-746a476 - 2015-03-19.

I am unable to create a plunker as this comes from a project with almost 70 mb of unminified javascript!

**Comment by PaulL1** [comment]
I think the last line says that `$scope.gridApi.grid.rows[1].entity` is equal to `$scope.gridOptions.data[1]`.  It's a not equal, and it's false, which is a double negative....so it's true and the two are equal.

**Comment by steverA** [comment]
Paul, grid.getRow does NOT find a row when I pass in $scope.gridOptions.data[1] but does when I pass in $scope.gridApi.rows[1].entity! I'll put the code back and try again!  :-)

**Comment by steverA** [comment]
Okay, here's some code:
var row = $scope.gridOptions.data[rowIndex];        // the entity
var row1 = $scope.gridApi.grid.rows[rowIndex].entity;        // the entity
var same = (row == row1);
This **broke** with same **false** and here's a picture!
![2015-03-26-150801-f12](https://cloud.githubusercontent.com/assets/9431902/6854836/0aae20c0-d3ca-11e4-930d-1137d41a7713.png)
Note same has a value of false! This is also the case if I use === which is what the default rowEquality() uses!

**Comment by PaulL1** [comment]
Hmm.  It doesn't copy the entity, it should be a reference.  Is it possible that you've replaced the data with a new array, and the grid is still pointing to the entities in the old array?  I think if you do that it doesn't repoint to the new entities, but it works out that they're the same and puts the same hashkey on them perhaps?  I'm stretching a bit, but it's possible.

**Comment by steverA** [comment]
I make NO copies of the entities – the gridOptions.data is my “model.”

/steve

Stephen R. Alpert, PhD
Principal Technical Architect
GE Healthcare
Clinical Business Solutions

T +1 617 519 2216
F +1 617 519 2625
E steve.alpert@ge.com<blocked::mailto:steve.alpert@ge.com>
www.gehealthcare.com<http://www.gehealthcare.com>

         GE imagination at work

**Comment by PaulL1** [comment]
It is possible for them to get out of synch, but it looks to me like they would resynch:
http://plnkr.co/edit/Ih5s7DrDytOPe3i3yPw2?p=preview

(click the "swapData" button, and look at the javascript console).

**Comment by steverA** [comment]
I would expect that but I don’t believe the dataset is refreshed. I’ll instrument it and check.

--

/steve

Stephen R. Alpert, PhD
Principal Technical Architect
GE Healthcare
Clinical Business Solutions

T +1 617 519 2216
F +1 617 519 2625
E steve.alpert@ge.com<blocked::mailto:steve.alpert@ge.com>
www.gehealthcare.com<http://www.gehealthcare.com>

         GE imagination at work

**Comment by PaulL1** [comment]
Closing: solution proposed that should resolve the issue, no further comments for 2 weeks, assuming solution has resolved issue.
