### ISSUE TITLE
Add pinning to saveState

### ISSUE THREAD

**Issue by jonathanchris** [angular-ui/ng-grid#3123]
I think the saveState feature should be able to include pinning. This way the grid can restore your pinned columns. Currently the saveState doesn't remember you pinned columns, this feels like a missed opportunity.

**Comment by PaulL1** [comment]
It can easily be added, it's very extensible, it's just that nobody has added it as yet.  A PR would be welcomed.

**Comment by jonathanchris** [comment]
Awesome, coming soon!

**Comment by PaulL1** [comment]
I think the most elegant way to do this (after doing something similar on grouping) is for the pinning feature to offer a "get pinning state" and a "set pinning state", which save state then just calls.  Much tidier than having saveState knowing about the pinning internals.

**Comment by jonathanchris** [comment]
@PaulL1 Take a look and let me know if you have any suggestions/recommendations on this PR. I used the publicApi and created an event and method in the pinning feature. Then utilized this in the saveState feature. I attempted to add testing and documentation as I went along.

**Comment by PaulL1** [comment]
This merged some time ago and seems to be working well.
