### ISSUE TITLE
Grid footer tutorial: remove footer, grid height doesn't adjust

### ISSUE THREAD

**Issue by PaulL1** [angular-ui/ng-grid#3126]
Refer http://ui-grid.info/docs/#/tutorial/105_footer.  Click the provided toggle buttons, the content disappears but the footer height doesn't recalculate.

**Comment by PaulL1** [comment]
Duplicate of #2554

**Comment by c0bra** [comment]
If the footer is adding a viewport adjustment, it might not be de-registering the adjuster when the element is destroyed.
