### ISSUE TITLE
Edit: using cursor keys off end of edited text loses focus

### ISSUE THREAD

**Issue by PaulL1** [angular-ui/ng-grid#3128]
On the edit tutorial with no cellNav: http://ui-grid.info/docs/#/tutorial/201_editable, if you start editing a cell then use the arrow keys to go to the end of the data, it will navigate off the end of the cell and lose focus (OSX and Chrome, in case this is OS/Browser dependent).

I think this is a duplicate, and will later look for the matching item.

**Comment by swalters** [comment]
@PaulL1 after several iterations, my solution was to turn off grid scrolling while in edit mode. You can't ignore scroll events and Chrome is firing a scroll event for the parent container when you are at the end of the text.  I think this is bad behavior from Chrome, but we probably have to live with it.

What I did was change the rendercontainer overflow style to hidden when editing.  This has the effect of turning off scroll bars when in edit mode.  What do you think?

You can see the fix here: https://github.com/angular-ui/ng-grid/tree/Fix-3128

**Comment by PaulL1** [comment]
It sounds reasonable to me, if perhaps prone to giving us some sort of artefacts when the scrollbars come and go.  I'm on a Mac so I don't see scrollbars anyway, so for me it works fine.  When I turn scrollbars on it also works fine.  I'd go ahead and merge it, one more defect off our list.

**Comment by swalters** [comment]
Scrollbars are removed from viewport if in deep edit to prevent any browser trigger scrolling
