### ISSUE TITLE
Add date flag to filters to be allow columns to be filtered by dates. #2772

### ISSUE THREAD

**Issue by SSchaaf** [angular-ui/ng-grid#3147]
Hi, I posted a comment in this PR : 

https://github.com/angular-ui/ng-grid/pull/2772#discussion_r26733569

Could be implemented ?

**Comment by PaulL1** [comment]
We're not likely to include new dependencies.  Otherwise, yes functionality like this could be included, but only if someone did a PR to provide it.

**Comment by SSchaaf** [comment]
Tks Paul. Shortly I will submit a PR. I have this code in my project and runs perfectly.
