### ISSUE TITLE
Make grid menu less ugly

### ISSUE THREAD

**Issue by PaulL1** [angular-ui/ng-grid#3150]
Every time I look at the grid menu I think it's ugly.  I can say that because I built it.  It needs to be less ugly, it's not clear that I have the talent to do that.

**Comment by deepu105** [comment]
how about removing the inner shadow and making it flat :smile:

**Comment by PaulL1** [comment]
I've set the button to match the header height, which makes it tidier.  And I've added content to the tutorial to explain how to adjust that height if it doesn't suit in your particular grid.

It'd be better if it took the height of the header that it's in, but whenever I try to do that I run into issues with the menu clipping to the header height - which are currently avoided by having the button outside the header but overlaying the header.

I could make it more like the column menu, with the menu and the button being disassociated, but that'd be some rework on what I did with the menu - at the moment the menu itself is in the same directive as the button and relies on this for some communication stuff.

Moving this out to 3.1.

**Comment by Zorkling** [comment]
How about something like this?

![uigrid_columnmenu_clean](https://cloud.githubusercontent.com/assets/5298416/7359291/9159dc8c-ecf1-11e4-9c9c-0f5f4125d41e.png)

All i did was change the following css
.ui-grid-menu .ui-grid-menu-inner {
   box-shadow: 0 **1px 5px** rgba(0, 0, 0, 0.2), inset 0 12px 12px -14px rgba(0, 0, 0, 0.2);
}
.ui-grid-menu .ui-grid-menu-inner ul li:hover {
   /* remove box shadow */
     background: #ddd;
}

**Comment by PaulL1** [comment]
I think there's adequate work on this, it's less ugly than it was, although still not pretty.  Closing.

**Comment by aurbano** [comment]
I've done a lot of CSS on top of the defaults to change the appearance to suit our design, if you're interested I can publish it.

Here's a screenshot of the result:

![capture](https://cloud.githubusercontent.com/assets/2827818/13500028/9dd57f82-e158-11e5-846a-9f56ed0dc356.PNG)

**Comment by vbasem** [comment]
@aurbano I know this is a little older, but I was wondering if you could still publish the CSS for your UI-GRID. The default just doesn't look well with modern bootstrap.

**Comment by xycloud** [comment]
@aurbano could you share your css?

**Comment by aurbano** [comment]
@vbasem @xycloud I've put together a quick repository for it.
UI Grid must have updated some of their CSS because it now looks slightly different, but it should be easy to improve/extend.

https://github.com/aurbano/ui-grid-css

The source is in Sass with variables for the colors, and there is a dist folder with built css files for convenience.

**Comment by xycloud** [comment]
@aurbano thx!
