### ISSUE TITLE
Scrolling - column headers misaligned with data

### ISSUE THREAD

**Issue by apurvajos** [angular-ui/ng-grid#3155]
I am facing an issue where my column headers are getting misaligned when I do horizontal scrolling on the angular UI grid.I am using ui-grid - v3.0.0-rc.20 .I have gone through the earlier post on this issue which says that the issue is fixed in version ui-grid - v3.0.0-rc.18.

![image](https://cloud.githubusercontent.com/assets/11720509/6897358/cef8d38c-d710-11e4-914e-66d32c980302.png)

**Comment by c0bra** [comment]
@apurvajos Does it happen for you on any of the tutorials?

**Comment by apurvajos** [comment]
No ..I have implemented custom UI grid control.I have implemented the custom header template for it.

**Comment by c0bra** [comment]
A lot of the scrolling requires that the header elements be correctly identified. I would make sure that your directives and classes line up, maybe by using the original header template and then slowly changing it one step at a time to make sure your changes didn't break anything.

**Comment by apurvajos** [comment]
Thank for quick response.I have tried moving back to default  header template but still the same issue is occurring.

**Comment by c0bra** [comment]
@apurvajos  You'll need to reformat your paste. It's so long that it can't all be seen. Look at the github docs on markdown formatting, specifically the parts on code blocks

**Comment by apurvajos** [comment]
Sorry for confusion ..I have added the code block now

**Comment by c0bra** [comment]
@apurvajos Can you actually read your cell and row templates and tell what's going on? I would highly suggest storing the templates as HTML and loading them into $templateCache (either with ng2html or script template tags or whatever).

Are you able to reproduce this in a plunker at all?

**Comment by apurvajos** [comment]
I have tried creating plunkr at "http://plnkr.co/edit/vYkaRyuoSl7yBswzB2aK?p=preview".I have removed  used the default row and cell template in the plunkr.Still the issue is occurring.

**Comment by c0bra** [comment]
@apurvajos "2" is no longer a valid value for the `enableScrollbar` options. If you remove that the grid renders properly.

**Comment by apurvajos** [comment]
Hi,

Thank you your inputs.So basically we should not have horizontal scrolling in the grid.We should use default browser horizontal scroll bar as it was coming in plunkr once I have removed "enableScrollbar" option.

**Comment by PaulL1** [comment]
Sounds like this issue is resolved - plunker now working.  Closing.
