### ISSUE TITLE
enableRowSelection together with enableRowHeaderSelection

### ISSUE THREAD

**Issue by zvovk1** [angular-ui/ng-grid#3156]
Hi guys, 
first of all I want say that we all are very appreciate for all you doing !

But I stuck with situation when in one grid in same time I need to have checkmark column with checkAll and I need to have possibility to check row by 'click' event.
We had such opportunity in ui-grid v.2 . 

So I debug source code. And on the row 21445 I find necessary fix-place for my case, but ask you to tell me a better solution.

Here context of this row 
```
 function registerRowSelectionEvents() {
              if ($scope.grid.options.enableRowSelection &&    !$scope.grid.options.enableRowHeaderSelection) {
                $elm.addClass('ui-grid-disable-selection');
                $elm.on('touchstart', touchStart);
                $elm.on('touchend', touchEnd);
                $elm.on('click', selectCells);

                $scope.registered = true;
              }
            }
```

So as we can see enableRowSelection and enableRowHeaderSelection do not work together, but I need them both.

If I remove this condition term everithing work fine for me, but this is "dirty workaround"

Please help with my issue.
Many thanks.

**Comment by PaulL1** [comment]
I think this has been asked for a few times, and probably makes sense.  I'll put it on the list for future enhancement, I'm not sure it's as simple as removing that one line (although it may be).

**Comment by PaulL1** [comment]
I've added this feature.
