### ISSUE TITLE
column IE and FireFox

### ISSUE THREAD

**Issue by lecoleco** [angular-ui/ng-grid#3160]
Hi,

I put one option on grid to show or not the filter on column, i set on start all columns enableFiltering: false, and after selection of a column which i what to show the filter, I remove the column set enableFiltering =  true and put column again. this work but only in safari and chrome not working IE 10.

If i click another option of menu and click again on the same page, the column show perfect. 

What i have to do for this work like safari and chrome?

http://plnkr.co/edit/S0ymCr9S5mQ6UVqBSK7A?p=preview

Thanks

**Comment by PaulL1** [comment]
Unfortunately I don't have IE to test on, but I think the issue with this is fixed and related to header sizing.   Are you able to check again to see if this is still occurring?

**Comment by PaulL1** [comment]
Solution provided that may resolve it, no comment for 3 weeks, closing, please re-raise or reopen if this is still occurring.
