### ISSUE TITLE
reopening #3138

### ISSUE THREAD

**Issue by yurigenin** [angular-ui/ng-grid#3162]
After last commit it is totally screwed up. Look at this plunker: http://plnkr.co/edit/3rY4J0GjVCuouuwFske0?p=preview

The headers are half sized and selection header is not even shown (no checkboxes)

**Comment by PaulL1** [comment]
Duplicate of #3165.  The issue is that the fonts are broken.  This looks to be a build process issue, the same code built locally works fine.
