### ISSUE TITLE
How do I use the same model field on multiple columns in the same columnDefs?

### ISSUE THREAD

**Issue by icfantv** [angular-ui/ng-grid#3163]
It appears that if I specify the same model field for two different columns (in the columnDefs array), the last one wins and the first isn't even rendered.  Short of duplicating the data to another field, is there a way to use a model data field for two different columns?  Thanks.

**Comment by PaulL1** [comment]
You can use the same field so long as you give the columns different names.

**Comment by icfantv** [comment]
Do you mean different columnDef displayName values?  The columnDef name field value is the same.

**Comment by icfantv** [comment]
I should also say that this is for columns in a nested grid.

**Comment by PaulL1** [comment]
There are three properties relevant on the columnDef:  name, field, displayName. 

You can have the same field but different names, and you can put whatever you like in displayName.

**Comment by PaulL1** [comment]
Resolution provided, no further comments for over 1 month, assuming original issue is resolved.

**Comment by icfantv** [comment]
Whoops, sorry about that.  Should have closed it.
