### ISSUE TITLE
Header size problem in IE and FireFox when put body css

### ISSUE THREAD

**Issue by lecoleco** [angular-ui/ng-grid#3164]
Hi,

I found the problem.

If you put bootstrap and in the custom css put  'font-family, font-size' the header not work good.

body {
    font-family: "open sans", "Helvetica Neue", Helvetica, Arial, sans-serif;
    font-size: 13px;

    background-color: #f3f3f4;
    color: #676a6c;
    overflow-x: hidden;
}

The plnkr show the problem only in firefox and ie. 
In this plnkr select Option Name and after Gender to show the filter. Again select the Name and Gender and see that header not return to the same size.

I guess have another problem in IE because if take off the css below the problem to be continued. (only in IE)
    font-family: "open sans", "Helvetica Neue", Helvetica, Arial, sans-serif;
    font-size: 13px;

http://plnkr.co/edit/S0ymCr9S5mQ6UVqBSK7A?p=preview

Please could you help with this? 

Thanks

**Comment by lecoleco** [comment]
Hi, if i comment the line below working perfect on safari, chrome, firefox and IE.
 
              //if (renderContainer.explicitHeaderCanvasHeight) {
                //ret += '\n .grid' + uiGridCtrl.grid.id + ' .ui-grid-render-container-' + $scope.containerId + ' .ui-grid-header-canvas { height: ' + renderContainer.explicitHeaderCanvasHeight + 'px; }';
              //}

**Comment by c0bra** [comment]
This should be fixed with 98ed01049015b22caddb651. 

Here's an updated plunker that shows how to do it. It should be easier since you don't have to iterate over your column defs or use $timeout: http://plnkr.co/edit/VYe5xly20xmYLEcgq0TB?p=preview

**Comment by lecoleco** [comment]
thank you

**Comment by lecoleco** [comment]
Work perfect! 
thank you
