### ISSUE TITLE
How to render html fomatted content in ng-grid?

### ISSUE THREAD

**Issue by Mayurdoshi** [angular-ui/ng-grid#3171]
I have jsonData which consist of html content in it. and i want to render that html in ng-grid but html content not rendered as its only shows in normal string format.

Below Is the plnkr which shows all the code:

http://plnkr.co/edit/RlWyDqCUUR15dmLM7ePV?p=preview

**Comment by griessbreilp** [comment]
It's not that hard, i had the same problem in my own project.
You can define a columntemplate:
gridOptions.columnDefs.cellTemplate = '<div ng-bind-html="row.entity[col.field]"></div>';

with the row.enity[col.field] you get the value of the field, and bind it to "ng-bind-html".
To make this work you just have to add "ngSanitize" in your App as module/dependencie:
angular.module('app', ['ui.grid', 'ngSanitize']);

And now it should render the html als html

**Comment by Mayurdoshi** [comment]
Thanks for your reply. Can i have a sort of example for it . I have tried it but not working.

**Comment by griessbreilp** [comment]
I just added a plunker which works, or at least i hope so. :)

**Comment by Mayurdoshi** [comment]
@griessbreilp: Html is working with it but ng-click is not working as in my data i have '<a ng-click=''show(''F:/cox/main.html'')'>Cox</a>', but when i inspecting the element it only shows me <a>Cox</a>

**Comment by c0bra** [comment]
@Mayurdoshi I answered your SO post; you can find a working plunker there.

**Comment by Mayurdoshi** [comment]
Thanks @c0bra. Its solved my issue also thanks so much to illustrate my errors

**Comment by c0bra** [comment]
@Mayurdoshi  no problem, glad it's working for you!

**Comment by griessbreilp** [comment]
http://stackoverflow.com/questions/29365355/how-to-render-html-fomatted-content-in-ng-grid
For everyone else who searched for the answer and didn't know what "SO Post" meant

**Comment by PraveenGuda** [comment]
But Grouping is messing up if we apply this method.
