### ISSUE TITLE
How to bind subgrid events in expandable ui-grid

### ISSUE THREAD

**Issue by LazyCod** [angular-ui/ng-grid#3174]
ng-click event for the sub grid in ui-grid(expandable ui grid) is not working. But the same ( ng-click) is working for the outer grid with ‘grid.appScope’ scope. But I don’t know how to bind the subgrid events in expandable grid. I have kept my code in the below plnkr. ‘Click me’ is not working in the inner grid.
                   http://plnkr.co/edit/0OyR35YeRfLRHr5DA6tC?p=preview

TIA

**Comment by PaulL1** [comment]
There is an expandableScope property you use instead of appScope on expandable.

**Comment by LazyCod** [comment]
I have added below snippet in gridOptions 
expandableRowScope: {
      message:"Hello",
      clickMe: function(){alert('hi');}
    }

I tried to call clickMe method from expandableRowScope like below.
<button class="btn primary" ng-click="grid.expandableRowScope.clickMe()">Click Me</button>
Still no luck.

**Comment by LazyCod** [comment]
<button class="btn primary" ng-click="grid.expandableRowScope.clickMe()">Click Me</button>

**Comment by LazyCod** [comment]
Hi PaulL1,
In subGrid i tried invoking the method as ```grid.options.expandableRowScope.clickMeSub()``` and ```grid.expandableRowScope.clickMeSub()``` .

```expandableRowScope: { clickMeSub: function(){alert('hi');} }```

Plz check the plnkr below
http://plnkr.co/edit/nJLcMLBwdgPzOQUvgjQT?p=preview

**Comment by PaulL1** [comment]
Yeah, turns out I have no idea how expandable actually works.  Looks to me like it's setting on the grid $scope, not on the row $scope.  I don't know how you get at it from a row/cell template.

Anyway, I think what you are doing is really appScope on the subgrid.  Try this: http://plnkr.co/edit/FY13fnTWBw329TOEZ7Q5?p=preview

**Comment by LazyCod** [comment]
thank you Paul.............

**Comment by asafliv** [comment]
This saved my life!!!!! :)

**Comment by hadestt** [comment]
**grid.options.expandableRowScope.get(id)** and add the following fields on subGridOptions is worked on me.

expandableRowScope: {
getResponseDetail: function(id) {
alert("get	 "+id);
}
}
Thanks!

**Comment by fatifleu** [comment]
what if i am not using subgrid and just an expanded template with this buttons how can i access the data here is my plnk : http://plnkr.co/edit/4BgT1Z75PD9DDixx5QFa?p=preview
i really need your help
