### ISSUE TITLE
after sorting, celltemplate button's action not match 

### ISSUE THREAD

**Issue by fwdpwl** [angular-ui/ng-grid#3177]
added a button which alerts the cell content.
after sorting, the button action alerts  incorrect cell content

http://plnkr.co/edit/YyBZ4Qu2jEOHJkc8N9mL?p=preview

![ui-grid_celltemplate_sorted](https://cloud.githubusercontent.com/assets/11750697/6936921/dfc38a8e-d889-11e4-911f-050c1103ead7.png)

**Comment by c0bra** [comment]
Change your ng-click to: `grid.appScope.showMe(row.entity[col.field])`.  You're interpolating the contents of your field into a string, which only happens once, so when you sort the value isn't re-interpreted.
