### ISSUE TITLE
Paint of the Grid with Tabsets

### ISSUE THREAD

**Issue by griessbreilp** [angular-ui/ng-grid#3178]
Hellow everyone,

i try to display a site in tabs and tabsets.
I have one or more grids on every tab and the grids simply show nothing.

Know, when i move the window (resize it), or open the developertools (Chrome), the content of the grid appears. When i change the tab, the game starts again:
nothing is there -> resize -> data appears -> tab change -> nothing is there ...

I made a little plunker to show the problem:
http://plnkr.co/edit/nlyA9z?p=preview

I hope I am just to dump to do it properly.
That is a minimalistic version, the cellTemplate and the structure of the html is because of the project I am working on.

**Comment by aikrez** [comment]
You need to set a width/height on the grids
Working plunker: http://plnkr.co/edit/0Nljj5zbKjUQPv80uKcj

More info on the issue http://ui-grid.info/docs/#/tutorial/108_hidden_grids

**Comment by griessbreilp** [comment]
That solved my problem, thank you really much!
