### ISSUE TITLE
Customize Viewport template

### ISSUE THREAD

**Issue by muhmud** [angular-ui/ng-grid#3180]
Is this possible? Can't see where this would be done in the API docs.

Thanks

**Comment by c0bra** [comment]
What result are you wanting?

**Comment by c0bra** [comment]
What result are you wanting?

**Comment by muhmud** [comment]
I'm trying to put a border around a specific row in the grid. Testing it out in Chrome, it only seems to work when I add my ng-class to the bit that's in the ViewPort template

**Comment by PaulL1** [comment]
There's an existing item open for providing a row class capability #3186, so I'm closing this one.
