### ISSUE TITLE
custom Editable Cell Template with ng-model-options

### ISSUE THREAD

**Issue by dardino** [angular-ui/ng-grid#3181]
hi,
I have a problem with my custom Cell Template:
```html
<div>
   <form name="inputForm">
      <input ng-model-options="{ updateOn: 'blur' }" type="INPUT_TYPE" ui-grid-editor ng-class="'colt' + col.uid" ng-model="MODEL_COL_FIELD" />
   </form>
</div>
```
this template differ with default only for ng-model-options but when I leave from filed (blur) the model is not updated.

is it a bug or the binding on blur not supported?

Thanks a lot!
Gabriele

**Comment by dardino** [comment]
Hi, anyone has this problem?

**Comment by bencameron** [comment]
Yes, I've run into this problem too.  Before finding the issue you created, I tried the same approach (custom cell template) and ran into the same problem.  I got rid of the custom template and am just allowing the model to be updated from the view after each keystroke for now.  That's definitely not ideal for my application, but I've got other priorities for now and was hoping this might get resolved by the time I circle back to it.

Have you had any luck?

**Comment by dardino** [comment]
Hi! Thanks for the reply.
For now I have placed the event raise instruction into a $timeout callback with a delay of 10 msec.
Doing this, angular can commit the value before the end cell edit destroys the DOM element and its directive.
This is not a good choice but for now is the fastest way to get around the problem.

**Comment by PaulL1** [comment]
The recommended way to handle update on every keypress is to do a debounce, rather than trying to change things so that there isn't an update on every keypress.  I'm not familiar with the option that you're setting to cause it to update only on blur, but I do recall discussion of a problem where angular by default doesn't have a blur event, perhaps that is the problem.

**Comment by PaulL1** [comment]
Looks like original raiser has found a solution, no further updates for some time, closing.

**Comment by dardino** [comment]
Good! thanks!
I'll try it as soon as possibile

**Comment by aiguofer** [comment]
I was having this issue. Unfortunately the linked solution didn't work for me. I have submitted a PR #4698 with a solution that's working for me.
