### ISSUE TITLE
sortChanged called multiple times with external sorting on

### ISSUE THREAD

**Issue by davidkaminsky** [angular-ui/ng-grid#3182]
I have external sorting turned on and listen for the sortChanged event and I see it usually get called twice. When I click on a single column it seems to call it each time with a different sort direction on the column. When I start using the grid menu to add/remove columns I often see it get into a state where it seems to call it 3 times and since the sort is a tri-state it gives the appearance that nothing about the sort direction has changed. Refreshing the page brings it back to just calling it twice.

**Comment by PaulL1** [comment]
Is this still occurring?  I seem to recall a fix to the listeners in the sorting that may have fixed it.  If not, is it possible to get a plunker that demonstrates this, that would make it much easier to fix.

**Comment by davidkaminsky** [comment]
No, this does appear to be fixed. Thanks!

**Comment by tonybrasunas-greenlots** [comment]
I'm still seeing this issue in v18 here in 2025.  Was this ever fixed? 

With external sorting on, `nzSortOrderChange` is called twice when the user chooses a new column to sort on. It is only called once if the user repeatedly sorts on the same column, but once the user tries a different column, it's called twice, and this breaks everything on the sort.
