### ISSUE TITLE
Lots of blank space past last row when infinitely scrolling

### ISSUE THREAD

**Issue by davidkaminsky** [angular-ui/ng-grid#3184]
I'm seeing a problem that I'm assuming is related to the fix for this issue (https://github.com/angular-ui/ng-grid/issues/3119). When I've reached the end of my results when infinitely scrolling the scrollbar is still in the middle of the viewport and I see a lot of empty space below the entries.

I am telling dataLoaded that it should no longer be able to scroll and that seems to be working as I'm not seeing anymore calls to get more data.

vm.gridApi.infiniteScroll.dataLoaded(false, (page * numResultsPerPage) < result.numTotalUsers);

![screen shot 2015-03-30 at 2 38 56 pm](https://cloud.githubusercontent.com/assets/1380808/6945045/e9ef02f6-d84b-11e4-9800-30c413030d9f.png)

**Comment by luciformed** [comment]
I  have the same issue, and based on my investigation it's because of the way viewport offsets the rows from the top

**Comment by davidkaminsky** [comment]
I'm still seeing this issue on the stable version rc.21. Is this supposed to be fixed?

**Comment by PaulL1** [comment]
This looks to have been fixed on 18th April.  Are people still experiencing it?  If so, could someone please provide a plunker so that it can be diagnosed?

**Comment by c0bra** [comment]
No response in > 2 weeks. Closing.

**Comment by valtersboze** [comment]
i got the same problem when i was trying to remove the weird 1px padding-top on ui-grid-canvas. so after i added "padding: 0"  i got same empty block after the content making the scrollable content 2x longer.. if anyone experiencing the same, remove anything in custom css related to ui-grid-canvas and that should fix the problem.
