### ISSUE TITLE
Select filter does not work with boolean values

### ISSUE THREAD

**Issue by pedroclayman** [angular-ui/ng-grid#3194]
If you define a filter like this:
```
filter: {
  type: uiGridConstants.filter.SELECT, 
  selectOptions: [ {value: true, label: 'true'}, {value: false, label: 'false'} ]
}
```
Then selecting the *false* option from the select filter does not work as expected. All results are returned and the "x" (clear filter button) disappears, too.

http://plnkr.co/edit/rz0wA7wbw50Gh6ncN0GK?p=preview

**Comment by pedroclayman** [comment]
I have fixed this in the pull request #3197

**Comment by PaulL1** [comment]
The PR is merged, closing.  Thanks.

**Comment by BribeFromTheHive** [comment]
I had just encountered this issue myself, however the solution required using 'true' and 'false' as strings, rather than as their normal booleans, and then using the condition function to compare the strings to their boolean counterparts.
