### ISSUE TITLE
Demos don't work on ui-grid.info / stable / tutorial

### ISSUE THREAD

**Issue by blandine** [angular-ui/ng-grid#3196]
Hi,
If you go on http://ui-grid.info/docs/#/tutorial/ and select "stable" (and change again to tutorial since it brings you back to the api). 

There's many errors and all the demos grids are not working :
`
Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: page in module.directives track by page.url, Duplicate key: #/api/ui.grid.directive:uiGridColumnMenu, Duplicate value: {"section":"api","id":"ui.grid.directive:uiGridColumnMenu","shortName":"uiGridColumnMenu","type":"directive","keywords":"api column directive framework grid leverages menu provides the ui uigridmenu underneath","partialUrl":"partials/api/ui.grid.directive.uiGridColumnMenu.html","url":"#/api/ui.grid.directive:uiGridColumnMenu"}
`

Same behaviour in Chrome, Firefox, IE.

Thank you for your help.

**Comment by c0bra** [comment]
There is no stable release yet, UI-Grid is still in beta. The "stable" links will work once a stable release is complete.

Sorry for the confusion!
