### ISSUE TITLE
editableCellTemplate for custom Template for gridApi.edit.on.afterCellEdit

### ISSUE THREAD

**Issue by manomohanty** [angular-ui/ng-grid#3206]
I use the sample present in section 201 of tutorial. But I made a change for editableCellTemplate. Here I use my own custom template. While changing dropdown for the gender column, the thread is not entering to public api  gridApi.edit.on.afterCellEdit($scope,function(rowEntity, colDef, newValue, oldValue).

this afterCellEdit is not working.

**Comment by PaulL1** [comment]
If you use a custom editableCellTemplate, you also have to provide the afterCellEdit event as part of your directive, this is described in the 201 tutorial.

**Comment by PaulL1** [comment]
No further comment for over a month, solution provided that probably resolves the issue.  Closing, please re-raise if there is a reliable recreate or more information.

**Comment by karthiksubbu** [comment]
am also facing the same problem could you please guide me where i need to add the after cell edit in custom template

**Comment by cramroop** [comment]
The afterCellEdit does not fire when using a custom editableCellTemplate.  As soon as I remove the custom editableCellTemplate, thereby using the built-in editableCellTemplate, the event fires.

**Comment by sumeetsonawane11** [comment]
Facing the same issue 👍 
 Here I use my own custom template. While changing dropdown for the gender column, the thread is not entering to public api gridApi.edit.on.afterCellEdit($scope,function(rowEntity, colDef, newValue, oldValue).

this afterCellEdit is not working.???
@PaulL1 : Please can you provide a small code snippet for the same. That would be great.
Thanks in advance!
