### ISSUE TITLE
PreventDefault for cellEditEvents

### ISSUE THREAD

**Issue by genu** [angular-ui/ng-grid#3208]
The `beginCellEdit` is great because we can introduce some logic before a user edits a cell, but is there a way to prevent a cell from being edited in this event?

Generally calling preventDefault would work, but it needs the event passed as well.

-Eugen

**Comment by swalters** [comment]
Maybe cellEditableCondition is what you want: http://ui-grid.info/docs/#/api/ui.grid.edit.api:ColumnDef

**Comment by genu** [comment]
The use case that I'm trying to accommodate is:

1. User Edits a cell
2. Editing cell focus is lost
3. Row is dirty, but the changes are not yet saved to BE
4. User tries to edit another cell in another row
5. Alert user that their are currently have unsaved changes before allowing them to edit another cell in another row.

What is being editing can be tracked by placing different items on the scope, and then access them through the appScope in the cellEditableCondition, but seems kind of awkward to do that. Ideally, the grid should have an easily accessibly state properties through its API, correct?

**Comment by PaulL1** [comment]
Would perhaps the rowEdit feature give you what you want?

Failing that, we would probably accept a PR that added the event to beginCellEdit, that wouldn't impact anyone that didn't want to use it.

**Comment by genu** [comment]
> Alternatively, wouldn't it make sense to trap the loss of focus on the cell and save it or force the user back into it if they haven't saved it / it has errors?

Setting `rowEditWaitInterval: -1` enables the user to have a button outside of the grid to initiate a save. That means a row could remain in an unsaved state after losing focus.

I'm honestly not sure, how to go about implementing event propagation though. I'll have to study rowGrid feature some more.

-Eugen

**Comment by PaulL1** [comment]
No further comment for over a month, solution provided that probably resolves the issue.  Closing, please re-raise if there is a reliable recreate or more information.
