### ISSUE TITLE
[FEAT] Selecting a row doesn't unselect the rest

### ISSUE THREAD

**Issue by yccteam** [angular-ui/ng-grid#3215]
I don't know if you meant this as a feature but currently, selecting a row in "multiselect" mode just adds another selection.
The standart is usually - ctrl+click to multiselect and click to select one and unselect the rest.
I see that ```evt``` is being sent to the listener, so it should be as easy as:
```if (evt.ctrlKey)```, but shouldn't default be as the standart? (by standart I mean kendoUI, excel etc.)

**Comment by PaulL1** [comment]
This is a design choice to support tablets.  Multi-select explicitly works by allowing you to toggle each row.

There is an option `modifierKeysToMultiSelect` that may give the behaviour you want.

**Comment by yccteam** [comment]
Sorry - it's in the tutorial. I've missed that.
This leaves the following issue unresolved though: #3214

**Comment by c0bra** [comment]
As that issue is separate from this one, can this be closed?
