### ISSUE TITLE
Each time its calling new json data from server

### ISSUE THREAD

**Issue by rmyemul** [angular-ui/ng-grid#3217]
Hi Team,
    When I am calling data from json using ng-grid each time its calling the json from the server it means each request fetching data from server. May i know how to stop it to gtet from local variable i mean cache and its not gettong updated when I pick dropdown 5 to 10 pagesize . please let me know how to reslove.
 Script is 
     <script>
     var app = angular.module('myApp', ['ngGrid']);
     app.controller('MyCtrl', function($scope, $http) {
         $scope.filterOptions = {
             filterText: "",
             useExternalFilter: true
         };
         $scope.totalServerItems = 0;
          $scope.pagingOptions = {
             pageSizes: [5,10],
             pageSize: 5,
             currentPage: 1
         };   
         $scope.setPagingData = function(data, page, pageSize){	
             var pagedData = data.slice((page - 1) * pageSize, page * pageSize);
             $scope.myData = pagedData;
             $scope.totalServerItems = data.length;
             if (!$scope.$$phase) {
                 $scope.$apply();
             }
         };
         $scope.getPagedDataAsync = function (pageSize, page, searchText) {
             setTimeout(function () {
                 var data;
                 if (searchText) {
                     var ft = searchText.toLowerCase();
                     $http.get('fileQueueDepthPublisher').success(function (largeLoad) {		
                         data = largeLoad.filter(function(item) {
                             return JSON.stringify(item).toLowerCase().indexOf(ft) != -1;
                         });
                         $scope.setPagingData(data,page,pageSize);
                     });            
                 } else {
                     $http.get('fileQueueDepthPublisher').success(function (largeLoad) {
                         $scope.setPagingData(largeLoad,page,pageSize);
                     });
                 }
             }, 100);
         };
     	
         $scope.getPagedDataAsync($scope.pagingOptions.pageSize, $scope.pagingOptions.currentPage);
     	
         $scope.$watch('pagingOptions', function (newVal, oldVal) {
             if (newVal !== oldVal && newVal.currentPage !== oldVal.currentPage) {
               $scope.getPagedDataAsync($scope.pagingOptions.pageSize, $scope.pagingOptions.currentPage, $scope.filterOptions.filterText);
             }
         }, true);
         $scope.$watch('filterOptions', function (newVal, oldVal) {
             if (newVal !== oldVal) {
               $scope.getPagedDataAsync($scope.pagingOptions.pageSize, $scope.pagingOptions.currentPage, $scope.filterOptions.filterText);
             }
         }, true);
 /* To filter the search these code is imp*/        
         $scope.filterOptions = {
        	        filterText: "",
        	        useExternalFilter: true
        	    };
  ///////////////////////////////       
         $scope.gridOptions = {
             data: 'myData',
             enablePinning:true,
             enablePaging: true,
             showFooter: true,
             totalServerItems:'totalServerItems',
             pagingOptions: $scope.pagingOptions,
             filterOptions: $scope.filterOptions,
             columnDefs:[
                         
                  	   {field:'fileName', displayName:'FileName',width:520,pinned:true},
                         {field:'fileDropTime', displayName:'fileDropTime',cellFilter: "date:'yyyy-MM-dd HH:mm:ss'",width:140 },
                         { field: 'fileProcessedTime', displayName: 'fileProcessedTime',cellFilter: "date:'yyyy-MM-dd HH:mm:ss'",width:140 },
                         { field: 'fileProcessingLag', displayName: 'fileProcessingLag',cellFilter: "date:'yyyy-MM-dd HH:mm:ss'",width:130}
                     ],
                     typeaheads:[]
         };
     });
           
</script>
and html is 
<div class="container" >
<div class="row" >
  Search:<input type="text" placeholder="Enter file name" ng-model="filterOptions.filterText"/><br><br>
  <div style="font-size: x-small;" class="gridStyle" ng-grid="gridOptions" ></div>
    
</div>
</div>

**Comment by c0bra** [comment]
Looks like you're missing the script and html and whatever else you meant to include.

If you're wanting to cache data in your app after it's been fetched once that's more of a general Angular question than a UI-Grid-specific question.

**Comment by PaulL1** [comment]
Further information sought and no response for over a month.  Assuming issue is resolved, closing.
