### ISSUE TITLE
Data Security

### ISSUE THREAD

**Issue by Kishor-Parmar123** [angular-ui/ng-grid#3218]
When load page of ng-grid then ajax reponse getting all json data in console of browser.so data are not secure

**Comment by c0bra** [comment]
Anyone with 10 free seconds and a javascript debugger can access the contents of an ajax response... or maybe I'm misunderstanding?

**Comment by PaulL1** [comment]
I think the point is perhaps that there's a log statement in there somewhere that's putting the data in the console.  But I'm not sure that log statement would be in the grid code (ng-grid or ui-grid?  Version?), rather than in @Kishor-Parmar123's code.

**Comment by PaulL1** [comment]
No further comment for over a month, insufficient information to diagnose or correct.  Closing, please re-raise if there is a reliable recreate or more information.
