### ISSUE TITLE
Accessing GridRow after Row is added 

### ISSUE THREAD

**Issue by mikefedak** [angular-ui/ng-grid#3220]
Hello,

I am having some issues with gridApi and getting the GridRow. 

The workflow is as follows:
1. The grid is defined and gridApi initialized 
2. A  new row is added, within the gridApi callback ($scope.addRow is triggered from an onClick event).
3. I try to retrieve the contents of the new row using gridApi. If the grid was empty and a new row was added, the rows array is empty, however if there are multiple rows added then the rows object contains all of the rows. 

This looks to me as an issue with the gridApi object being refreshed, is there any way to force it to refresh as soon as one row is added? 

```javascript

   $scope.modalData.Replays.onRegisterApi = function (gridApi) {
            $scope.gridApi = gridApi;
            console.info("grid api registered", $scope.gridApi);
            //Add Row Function 
            $scope.addRow = function () {
                $scope.modalData.Replays.data.push({
                    CreatedBy2: $scope.roles.UserId,
                    DateCreated: $scope.curDate
                });
                var rows= $scope.gridApi.grid.rows;
            };


        }
```

**Comment by PaulL1** [comment]
It looks to me like a timing issue.  When you change the data the grid notices via a watcher.  That watcher doesn't get evaluated until a digest runs.  

So, if you add data then you need to do things with that data after the digest has run - typically we do that by a $timeout of zero length.

So your code would be something like:
```
  $scope.modalData.Replays.onRegisterApi = function (gridApi) {
            $scope.gridApi = gridApi;

            //Add Row Function 
            $scope.addRow = function () {
                $scope.modalData.Replays.data.push({
                    CreatedBy2: $scope.roles.UserId,
                    DateCreated: $scope.curDate
                });
                $timeout(function() {
                  var rows= $scope.gridApi.grid.rows;
                  // do something with the rows
                });
            };
        }
```

**Comment by PaulL1** [comment]
No further comment for over a month, solution provided that probably resolves the issue.  Closing, please re-raise if there is a reliable recreate or more information.
