### ISSUE TITLE
Rendering is missing columns or missplacing sub-grid

### ISSUE THREAD

**Issue by Luftzig** [angular-ui/ng-grid#3223]
I see bad rendering of the ui-grid usually when the page is first being loaded. One example of bad rendering is in the attached image, another variation is that only part of the columns are rendered. When I resize the browser window it usually re-renders correctly. There are no errors in the javascript console.
We're using ui-grid-3.0.0-rc.20 with angular-1.3.14 on chrome, chrome canary and firefox.
![ui-grid bad rendering bug](https://cloud.githubusercontent.com/assets/3384761/7019409/3cf81d86-dd18-11e4-95f3-ee5a851665b5.png)

**Comment by PaulL1** [comment]
Some of this is fixed in unstable.  Suggest trying that before we try to diagnose/fix.

**Comment by PaulL1** [comment]
No further comment on this, and I haven't seen problems of this nature for some time.  Assuming it is fixed in current unstable, and closing.  Please reopen if you have a reliable recreate for it.
