### ISSUE TITLE
[BUG] Wrong/confusing documentation in performance tutorial

### ISSUE THREAD

**Issue by yccteam** [angular-ui/ng-grid#3225]
In the performance tutorial there are 2 things in the tutorial that I believe need fixing:
1) When going to plnkr, the ajax call failes because the URL is wrong. I believe it should be: ```https://cdn.rawgit.com/angular-ui/ui-grid.info/gh-pages/data/10000_complex.json``` and not ```https://cdn.rawgit.com/angular-ui/ui-grid.info/gh-pageshttps://cdn.rawgit.com/angular-ui/ui-grid.info/gh-pages/data/10000_complex.json```.
2) You mention ```flatEntityAccess``` in the tutorial. In the example you treat it like a simple variable, while in the documentation it is a function. Which is true? On the same topic - could you create a performance test between the two states?

**Comment by PaulL1** [comment]
I've fixed the plunker.

flatEntityAccess is a boolean, as it shows in the tutorial.  ngdoc had it marked as a method, changed to a property.

The tutorial allows flatEntityAccess to be toggled, so people can see the performance difference on their own computer and environment.
