### ISSUE TITLE
Checkbox in a cell template does not trigger ng-change.

### ISSUE THREAD

**Issue by rogood** [angular-ui/ng-grid#3226]
In an implementation of ui-grid the cell template for a column of cells require a checkbox. However, the ng-change event is never fired. I don't want to switch between read/edit modes, I would like the checkboxes to be always selectable.

Any ideas?

Thanks.

**Comment by c0bra** [comment]
How are you binding to the ng-change? Are you sure you sure you're using `appScope` properly?

**Comment by PaulL1** [comment]
Request for information, no further information for over a month.  Assuming issue is resolved, please re-raise if there is further information.

**Comment by evirca** [comment]
I had the same problem. As i am using checkbox on multiple grids, i came out using this:`.directive('uiGridCheckbox', [function() {
        function link($scope, $element, $attrs, uiGridCtrl) {
            $element.on('change', function() {
                uiGridCtrl.grid.api.edit.raise.afterCellEdit($scope.row.entity, $scope.col.colDef, $element[0].checked, !$element[0].checked);
            });
        }

        return {
            restrict: 'A',
            scope: false,
            require: '?^uiGrid',
            link: link
        };
    }]);`
and i declare my column as below ` columnDefs: [ { name: 'isActive', type: 'boolean', cellTemplate: '<div class="checkbox"><label><input ui-grid-checkbox type="checkbox" ng-model="row.entity.isActive"></label></div>' }]`

**Comment by evirca** [comment]
Actually the code mentioned before it's not about ng-change not being fired but more like an optimization so that you won't have to write ng-change on every checkbox.
