### ISSUE TITLE
Expandable row with HTML content as opposed to a sub-grid

### ISSUE THREAD

**Issue by neiz** [angular-ui/ng-grid#3228]
More of a feature proposal instead of an issue, but for my application I've got my expandable row rendering a ui-bootstrap tab control, each tab with different HTML (ng-bind-html) content (and sometimes a true sub-grid).

I've had few issues so far, aside from the expandableRowHeight calculation - there is currently a workaround, but it is based off of a calculated given the row count to derive the expandableRowHeight - in the case of HTML content, this will not work.

Any immediate red-flags or major problems with this? (Aside from the height issue which will need to be addressed - I am looking into options)

**Comment by PaulL1** [comment]
I believe the expandable feature is intended to be able to be used with things other than grids in the expanded space, so I think this is a reasonable usage.  @jpuri, do you agree?

**Comment by jpuri** [comment]
Very true @PaulL1 Expandable grid is can support any sub-grid, just one point to mention sub-grid template will be same for all the rows.

**Comment by PaulL1** [comment]
Resolution provided, no further comments for 4 weeks, assuming is resolved.
