### ISSUE TITLE
angular animate used for ui grid causing problem in IE9

### ISSUE THREAD

**Issue by smart987** [angular-ui/ng-grid#3232]
Using angular-animate.js for ui grid plugin (for grouping and export functionality) in ie9 giving  error "Function expected" in function fireDoneCallbackAsync(). Please see the attached screenshot. How can I handle this error and also I am not clear from which part of the code this error is being thrown. Other than for ui grid, I have not used anular animate any where else in my project. 
![animateerror](https://cloud.githubusercontent.com/assets/11309381/7039935/ccf9b03e-dde5-11e4-8db0-91fcac883268.png)

**Comment by c0bra** [comment]
And if you remove ui-grid the error goes away? Can you paste the call stack?

UI-Grid disables animations on the header and footer; not sure if that could have anything to do with it.

**Comment by smart987** [comment]
Hi c0bra, Recently I have updated my angular.js to 1.3.15 however my animate.js 1.2.26 only. That  caused the issue. I have updated both animate and touch also to 1.3.15 and it has fixed the reported issue on ie9. Now ui grid is working fine even on ie9. But please see the attached screen shot. Some other type of errors being shown on ie9 browser console for ui grid, even though ui grid is fully functional on ie9. I want to get rid of even these errors from my console on ie9 so what are the fixes I need to make.
![uigriderror](https://cloud.githubusercontent.com/assets/11309381/7082532/78c26e18-df73-11e4-80b1-d5c2a73cb30a.png)

**Comment by PaulL1** [comment]
That's an error I'm not seeing on other browsers.  Any chance of a plunker that demonstrates the issue, we can then track it down.

It appears to be saying that the renderContainer isn't there, but I don't see how you could have a headerCell without a renderContainer - they are defined in the renderContainer template.

**Comment by smart987** [comment]
PaulL1, I am facing problem to replicate it in plunker and will update you the soon I have error replication plunker. But please find the following details, if they can be of any help to track the issue.

Complete Error Stack -

Error: [$compile:ctreq] Controller 'uiGridRenderContainer', required by directive 'uiGridHeaderCell', can't be found!
http://errors.angularjs.org/1.3.15/$compile/ctreq?p0=uiGridRenderContainer&p1=uiGridHeaderCell
minErr/<@https://localhost/dashboard3/js/d3angular/angular.js:63:12
getControllers@https://localhost/dashboard3/js/d3angular/angular.js:7583:1
getControllers/<@https://localhost/dashboard3/js/d3angular/angular.js:7591:24
forEach@https://localhost/dashboard3/js/d3angular/angular.js:323:11
getControllers@https://localhost/dashboard3/js/d3angular/angular.js:7590:11
nodeLinkFn@https://localhost/dashboard3/js/d3angular/angular.js:7751:1
compositeLinkFn@https://localhost/dashboard3/js/d3angular/angular.js:7117:13
publicLinkFn@https://localhost/dashboard3/js/d3angular/angular.js:6996:30
createBoundTranscludeFn/boundTranscludeFn@https://localhost/dashboard3/js/d3angular/angular.js:7135:1
controllersBoundTransclude@https://localhost/dashboard3/js/d3angular/angular.js:7795:18
ngRepeatAction@https://localhost/dashboard3/js/d3angular/angular.js:24681:15
$watchCollectionAction@https://localhost/dashboard3/js/d3angular/angular.js:14175:13
$RootScopeProvider/this.$get</Scope.prototype.$digest@https://localhost/dashboard3/js/d3angular/angular.js:14308:23
$RootScopeProvider/this.$get</Scope.prototype.$apply@https://localhost/dashboard3/js/d3angular/angular.js:14571:13
@https://localhost/dashboard3/js/d3angular/uigrid/angular-touch.js:471:7
jQuery.event.dispatch@https://localhost/js/jquery-1.9.1.js:3073:15
jQuery.event.add/elemData.handle@https://localhost/js/jquery-1.9.1.js:2750:6

and from Windows 7 IE9 machine 

Error: [$compile:ctreq] Controller 'uiGridRenderContainer', required by directive 'uiGridHeaderCell', can't be found!
http://errors.angularjs.org/1.3.15/$compile/ctreq?p0=uiGridRenderContainer&p1=uiGridHeaderCell 
Error: [$compile:ctreq] Controller 'uiGrid', required by directive 'uiGridFooterCell', can't be found!
http://errors.angularjs.org/1.3.15/$compile/ctreq?p0=uiGrid&p1=uiGridFooterCell

**Comment by PaulL1** [comment]
Have you changed some of the templates perhaps, or overridden them?  Basically it's saying it can't find the render container controller as a parent of the header directive - perhaps you've changed the one or more of the grid templates?

**Comment by smart987** [comment]
I will try to provide you the plunker the soon it is ready with the error replication, mean while I am writing my code below, please let me know if it helps you identify the cause my problem.  Thanks 

My grid Options:

$scope.serverResponse = {
	    columns: data.tabDetails[dashVar].columns,
	    data: data.tabDetails[dashVar].data
	};

	$scope[config[uniqueIdInWithinTheTab].gridOptions] = {
	    showGridFooter: true,
	    showColumnFooter: true,
	    enableFiltering: true,
	    data: $scope.serverResponse.data,
	    columnDefs: $scope.getColumnDefsForUiGridComplex($scope.serverResponse.columns),
	    enableGridMenu: true,
	    enableSelectAll: true,
	    exporterCsvFilename: 'dataFile.csv',
	    exporterPdfDefaultStyle: {
	        fontSize: 9
	    },
	    exporterPdfTableStyle: {
	        margin: [30, 30, 30, 30]
	    },
	    exporterPdfTableHeaderStyle: {
	        fontSize: 10,
	        bold: true,
	        italics: true,
	        color: 'red'
	    },
	    exporterPdfHeader: {
	        text: "My Header",
	        style: 'headerStyle'
	    },
	    exporterPdfFooter: function(currentPage, pageCount) {
	        return {
	            text: currentPage.toString() + ' of ' + pageCount.toString(),
	            style: 'footerStyle'
	        };
	    },
	    exporterPdfCustomFormatter: function(docDefinition) {
	        docDefinition.styles.headerStyle = {
	            fontSize: 22,
	            bold: true
	        };
	        docDefinition.styles.footerStyle = {
	            fontSize: 10,
	            bold: true
	        };
	        return docDefinition;
	    },
	    exporterPdfOrientation: 'portrait',
	    exporterPdfPageSize: 'LETTER',
	    exporterPdfMaxGridWidth: 500,
	    exporterCsvLinkElement: angular.element(document.querySelectorAll(".custom-csv-link-location"))

	};	

and 

    $scope.getColumnDefsForUiGridComplex = function(columns) {
        var columnDefs = [];
        angular.forEach(columns, function(col) {
            if (col.field == "mode") {
                columnDefs.push({
                    field: 'mode',
                    grouping: {
                        groupPriority: 0
                    },
                    displayName: 'Mode',
                    enableCellEdit: false,
                    width: '10%'
                });
            } else {
                if ((col.displayName.indexOf("Spend") > -1) || (col.displayName.indexOf("Shp") > -1)) {
                    col.aggregationType = uiGridConstants.aggregationTypes.sum;
                    col.width = '10%';
                    //  col.cellFilter = 'currency';
                } else {
                    if (((col.displayName.indexOf("Quarter") > -1))) {
                        col.width = '5%';
                    } else {
                        col.width = '10%';
                    }
                }

                if ((col.displayName.indexOf("Mode") > -1) || (col.displayName.indexOf("Service") > -1) || (col.displayName.indexOf("Quarter") > -1)) {
                    col.enablePinning = false;
                }
                columnDefs.push(col);
            }

        });
        return columnDefs;
    };

Then I just compile my template 

var template = ' <div class="col"> <p class="graphtitle">' + dashletterName + ' </p> <div class="gridStyle" ui-grid="' + config[uniqueIdInWithinTheTab].gridOptions + '"  ui-grid-grouping ui-grid-pinning ui-grid-selection ui-grid-exporter ></div>'

**Comment by PaulL1** [comment]
No further comment for over a month, further information required to reliably diagnose.  Closing on assumption issue has probably been resolved in another way, please re-raise if there is a reliable recreate or more information.

**Comment by fabolo** [comment]
I'm trying to use example "306 custom filter" from the doc and I'm getting the *Controller 'uiGridRenderContainer', required by directive 'uiGridHeaderCell', can't be found!* error
both on IE11 and Chrome
filter is working as expected but the second time the modal grid is opened, and any subsequent opening,the error is thrown, doubling its occurrence every time, if it has already been resolved, could you please point me to the issue? Thanks
![uigriderror](https://cloud.githubusercontent.com/assets/6189594/7902409/4981b6cc-07b9-11e5-9b52-b8274b4361e2.png)
