### ISSUE TITLE
Grid width extends surrounding div

### ISSUE THREAD

**Issue by dannythemaster** [angular-ui/ng-grid#3233]
I use UI grid within a UI Bootstrap accordion tab. I want to have it 100% width, but initially it always extends the width of the accordion area. It fixes automatically doing any browser resizing.

**Comment by yccteam** [comment]
Have you tried ui-grid-autoresize?

**Comment by dannythemaster** [comment]
I just tried, but no difference. Is there any other way to force the grid being 100% then putting a css width: 100% in the .grid class?
I think the grid initially calculates a wrong px width this way. As I said it recalculated correctly on resizing the window.

![sample1](https://cloud.githubusercontent.com/assets/2980841/7041168/5bc29286-ddd7-11e4-8df7-76d2550ebd31.PNG)

**Comment by yccteam** [comment]
Could you put a sample code on plnkr/jsbin/jsfiddle?

**Comment by dannythemaster** [comment]
http://plnkr.co/edit/vKVZY05B01yZ9cTn0fJz?p=preview

So far I could not reproduce the width problem on plnkr, but could have something to do with the ui-grid-selection component, since the grid doesn't display correctly once enabled, at least in ie and firefox.

**Comment by yccteam** [comment]
Check this please: http://plnkr.co/edit/hmuVy6pZE10oBmsGs3iD?p=preview
I've used the auto-resize to solve your width issue. Is that you wanted?

**Comment by dannythemaster** [comment]
Jonathan, perfect, thanks. Now it even scales up to full width without the additional css information.

**Comment by yccteam** [comment]
:+1: 
I believe this issue can be closed then

**Comment by dannythemaster** [comment]
well, there should not be a display or width problem initially, but anyway, the autoresize option fixes it. :-)

**Comment by c0bra** [comment]
This is the same issue as #2700. I'll close as a duplicate.
