### ISSUE TITLE
Get Aggregation value in Tree Grid.

### ISSUE THREAD

**Issue by debayan31** [angular-ui/ng-grid#3234]
Using below logic I can iterate my present visible grid. 

```javascript
$scope.gridApi.grid.renderContainers.body.visibleRowCache.forEach(function (row) {
  console.log($scope.gridApi.grid.renderContainers.body.visibleRowCache);
  // my logic
});
```

But from the above logic I can find no for "groupPriority =  0". How can I able to iterate higher grouping level to lower grouping level .

For better understand see attached screenshot.

![mapping screenshot](https://cloud.githubusercontent.com/assets/11749797/7040969/73843328-ddf2-11e4-8a0c-335afe7e95e4.jpg)

**Comment by PaulL1** [comment]
The row has a `groupLevel` on it, that should tell you which grouping you're currently looking at.

**Comment by debayan31** [comment]
Hi Paul.

Kindly refer above attached screenshot for proper understanding.
Current size of $scope.gridApi.grid.renderContainers.body.visibleRowCache is 1 and groupLevel is 0 which is holding data for State INDIA.

Logically in groupLevel is 1 it will hold data corresponding to female(2) and male(4). So how can I iterate $scope.gridApi.grid.renderContainers.body.visibleRowCache for getting data when groupLevel = 1?

**Comment by PaulL1** [comment]
What have you already tried - example code perhaps or a plunker?

**Comment by PaulL1** [comment]
Request for further information, no further comment for over 3 weeks.  Closing.
