### ISSUE TITLE
block  UI-Grid when saving data

### ISSUE THREAD

**Issue by kandarpbhesaniya** [angular-ui/ng-grid#3235]
i want to block ui-grid cell when saving data. it should not focus next cell when enter...it seems big problem to me. because it again going in afterCellEdit event and saving. how can i do like that...

**Comment by PaulL1** [comment]
If you're looking to save data from the edit feature, you could consider using rowEdit, which is intended fro this purpose.

I'm not sure that it's good UI design to block a user from leaving the current cell until it's saved.  If that's what you want to do, then I think you'd need to hook onto the cellNav events and move the user back to the previous cell when they try to leave it.

**Comment by kandarpbhesaniya** [comment]
ok i solved using cell navigation..thanks PaulL1
