### ISSUE TITLE
guessSortFn throws error, getSortFn expects null return

### ISSUE THREAD

**Issue by gentleman-turk** [angular-ui/ng-grid#3236]
Within the rowSorter, the getSortFn expects the guessSortFn to return null if it couldn't guess the correct sort function. Instead it throws an exception. Either guessSortFn should return a default function or the call should be wrapped in a try catch. 

Without this, one can't specify a custom colDef.type without breaking sorting.

**Comment by PaulL1** [comment]
colDef.type is a value that the grid uses, I'm not sure you can just invent new types and expect things to work.  Is there a reason you cannot use a different field for type - perhaps colDef.myType or something?

**Comment by gentleman-turk** [comment]
Perhaps I'm confused...

"type

the type of the column, used in sorting. If not provided then the grid will guess the type. Add this only if the grid guessing is not to your satisfaction. Refer to gridUtil.guessType for a list of values the grid knows about"

Reading it again, I can interpret it to say type may be provided as long as it is one of the supported types. A list of the supported types would be of great help. I'll change my implementation to add a new property type for what I was doing and key off of that instead. 

I was setting the type to be "select" for use when performing an edit.
