### ISSUE TITLE
ng-grid inside a cell template

### ISSUE THREAD

**Issue by aksharak** [angular-ui/ng-grid#3242]
Hi,
I have 3 grids where i need to display them inside a cell of an ng-grid based on a some condition. Can i display an ng-grid inside a cell with if, else if, else conditions on a variable? If yes please let me know how.
Thanks in advance.

**Comment by PaulL1** [comment]
Yes, you can, although generally it looks rather ugly when you do so.

Is what you're doing perhaps a candidate for the expandable or treeview features?

**Comment by PaulL1** [comment]
No further comment for over a month, solution provided that probably resolves the issue.  Closing, please re-raise if there is a reliable recreate or more information.
