### ISSUE TITLE
 cellTemplate does not trigger ng-paste when pasting data in cell

### ISSUE THREAD

**Issue by kandarpbhesaniya** [angular-ui/ng-grid#3243]
can we call function when user paste data in cell? 

here is a plunkr  http://plnkr.co/edit/Llewp381weVWqLYbGrhs?p=preview

i can call function on ng-click..but ng-paste didn't work..

**Comment by PaulL1** [comment]
Two problems with your plunker:
1. You need to use grid.appScope to call functions from within a template
2. When the cell goes into edit mode it uses the editableCellTemplate, not the cellTemplate, so you need your ng-paste in there.  http://ui-grid.info/docs/#/api/ui.grid.edit.api:ColumnDef

I haven't dealt with the editableCellTemplate, as that's quite tricky.  But I've changed your plunker to make the column not editable, and you can see the cellTemplate then is giving a response from the ng-paste.

http://plnkr.co/edit/kLUqD15403buEnbfXeUV?p=preview

**Comment by kandarpbhesaniya** [comment]
see this plunkr...
http://plnkr.co/edit/nC3pxpjNWKxMhgsxRvic

i applied editableCellTemplate but..as it was...also i cant edit the cell. is there any colDef properties i forgot to mention?

**Comment by PaulL1** [comment]
The editableCellTemplate would be similar to the base editableCellTemplate - so something like:

```
<div>
    <form name="inputForm">
        <input type="INPUT_TYPE" ng-paste="demoevent(row)" ng-class="'colt' + col.uid" ui-grid-editor ng-model="MODEL_COL_FIELD" />
    </form>
</div>
```

Updated plunker:  http://plnkr.co/edit/xvPpCzR4cQUIJKXdwLRj?p=preview

**Comment by kandarpbhesaniya** [comment]
thanks its working...thank u vary much sir

**Comment by kandarpbhesaniya** [comment]
actually i also want to paste excel data in N no of cell...can i do with ui-grid?

**Comment by PaulL1** [comment]
Not currently.  You can however export as CSV, then import using importer feature.

**Comment by kandarpbhesaniya** [comment]
ok thanks

**Comment by aricang** [comment]
could you please have a look again at this plunker? 
http://plnkr.co/edit/kLUqD15403buEnbfXeUV?p=preview
ng-paste does not work for celltemplate like you mentioned

Thank you very much
