### ISSUE TITLE
Change editableCellTemplate per column value?

### ISSUE THREAD

**Issue by awn70** [angular-ui/ng-grid#3245]
Hi,
I've to create a editable grid with 3 columns:
1) attribute (dropdown, no problem)
2) attribute type (display only, based on column 1)
3) attribute value
The dropdown selection in column 1 defines the input type (col 2: alphanum, num, boolean, dropdown) for column 3. I'm looking for an example or some hints to build this. AFAIK I have to switch the editableCellTemplate before editing of column 3 starts, am I right or is there a better solution?
Thanks
Andreas

**Comment by PaulL1** [comment]
Editable cell template would probably do it, but I'm not sure that you can just change the template and have it immediately apply - there's some steps with compiling the template that I suspect won't get re-executed.

You may find you can change column3.type, and then when they start editing it'll just pick the right sort of editor, without playing with the editable cell template.  Basically we create the editor each time we start editing - we're adding a new element - so it may just work.

**Comment by awn70** [comment]
Changing the type of column 3 at the right moment sounds good. Where is the right place to do it, are there events like "enter row" or "begin row edit"? 
It would be cool if I can pass a function to the type property of the column and the grid evaluates the function before the editor is created.

**Comment by PaulL1** [comment]
I don't think you can pass a function to the type property.

I think the after cell edit event would be the place to do this, although you could also do it with a watcher on the value itself I guess.  The event would be better.  Refer the edit api documentation, and I think the edit tutorial uses the after cell edit event.

You may get timing issues, you'll have to check to see (I don't know if the after cell edit will fire before we create the new editor on the new cell).

**Comment by awn70** [comment]
Changing the type of column 3 isn't working, I've tried it from the cellNav.navigate event.
When I assign the editableCellTemplate from this event it works for number and string type. The last thing I need is the dropdown option. The dropdown editor opens but the list is always empty. I have used the editDropdownRowEntityOptionsArrayPath property to define the data source of the dropdown.  Are there any special initializations for the dropdown editor?

**Comment by awn70** [comment]
I've found a workaround for my problem.
When the initial configuration of column 3 is a dropdown: 
    editableCellTemplate: 'ui-grid/dropdownEditor',
    editDropdownRowEntityOptionsArrayPath: "...",
    editDropdownIdLabel: "...",
    editDropdownValueLabel: "..."

Now I can switch between the edit modes for string, number, and dropdown by changing the column properties above from the cellNav.navigate event.

**Comment by PaulL1** [comment]
Looks like this is resolved, closing.

**Comment by navateja424** [comment]
Hi awn, I am looking exactly the same one. Can you please provide me the code in plunker.

Thanks in advance
