### ISSUE TITLE
[FEAT] - tree-view grid

### ISSUE THREAD

**Issue by yccteam** [angular-ui/ng-grid#3246]
This feature would be a combination of grouping and expandable row. Each row could be expanded, but the expansion would be considered as a part of the main grid, so their virtualization be calculated together.
So the look and feel would be like a grouped grid, but the rows would look like an expandable grid (the "group headers" would have their own data sources).

Some thoughts:

@PaulL1 :
1) ```
potentially treeview could be added to grouping rather than duplicating. Probably the main change is to use the existing row as a groupHeader rather than inserting a new row. But not quite sure how we'd decide which row is the "parent" row
since at the moment we sort then look for breaks in value. Would the first row with a given value always be the "parent". Or would we have some other way to tell the code which rows are nodes and which rows are leaves?```

2) ```Thinking on the treeview @yccteam, perhaps it could be a lot like grouping, but you could have an optional property on each row ($$treeLevel), and then it could use a rowsProcessor similar to the group rowsProcessor to work out which are nodes and which are leaves (perhaps it could set a property on the row like row.treeLevel, and row.treeNode = true)
Further, we could store the number of child nodes for any given node in row.numChildren, and then use a custom cell template to add the number of children in brackets if the user wanted
You could reuse the header column logic and the indenting of the + from grouping
it'd be nice to have a combined code base, but perhaps it's easier to just copy the bits that are useful.
Since treeview would (I presume) be more of a programatically set thing - I'm assuming you can't just sort by any arbitrary column then turn that into a treeview - so it would probably be a much smaller code base```

**Comment by PaulL1** [comment]
Would you see the expanded sections having their own data sources, or all the data returned as part of one server call?  The latter would be much more efficient, if we did the former we'd need a "get children of this node" type method, and we'd need to original data to tell us which nodes had children under them.  Seems like you'd be making your server a lot more complicated with not much benefit?

**Comment by PaulL1** [comment]
I've started on this: https://github.com/PaulL1/ng-grid/tree/treeView

It doesn't run yet, but the basics are there.  I haven't done any work on dynamic loading.  I need to add a tutorial.  But just so we don't double up, I'm posting.

**Comment by PaulL1** [comment]
I've completed the base implementation of this.  It runs, has unit tests, has a tutorial and supports dynamic loading.  It has some outstandings that we might want to implement as noted in the tutorial: http://ui-grid.info/docs/#/tutorial/215_treeView

**Comment by PaulL1** [comment]
Refer discussion on the commit for potential extensions and fixes.

**Comment by PaulL1** [comment]
I think this is now resolved, closing.

**Comment by vijender1256** [comment]
Hi, I cannot build a tree using UI-Grid , please help me to fix this below is the code what i got:

I also have a json which i need to build the treeview

var app = angular.module('app', ['ngAnimate', 'ngTouch', 'ui.grid', 'ui.grid.treeView' ]);

app.controller('MainCtrl', ['$scope', '$http', '$interval', 'uiGridTreeViewConstants', function ($scope, $http, $interval, uiGridTreeViewConstants ) {
  $scope.gridOptions = {
    enableSorting: true,
    enableFiltering: true,
    showTreeExpandNoChildren: true,
    columnDefs: [
    
      { name: 'id', width: '20%' },
      { name: 'parentId', width: '20%' },
      { name: 'name', width: '30%' }
    ],
  };

var data = [
        {
            "id": 1,
            "parentId": 1,
            "name": "TopLoc1",
            "children": [
              {
                  "id": 2,
                  "parentId": 1,
                  "name": "Loc1 child",
                  "children": [
                    {
                        "id": 4,
                        "parentId": 2,
                        "name": "Loc2 child",
                        "children": []
                    }
                  ]
              },
              {
                  "id": 3,
                  "parentId": 1,
                  "name": "Loc1 child",
                  "children": []
              }
            ]
        },
        {
            "id": 5,
            "parentId": 5,
            "name": "Top Loc 2",
            "children": [
              {
                  "id": 6,
                  "parentId": 5,
                  "name": "Loc5 child",
                  "children": [
                    {
                        "id": 8,
                        "parentId": 6,
                        "name": "Loc6 child",
                        "children": []
                    },
                    {
                        "id": 9,
                        "parentId": 6,
                        "name": "Loc5 child",
                        "children": []
                    },
                    {
                        "id": 10,
                        "parentId": 6,
                        "name": "Loc5 child",
                        "children": [
                          {
                              "id": 11,
                              "parentId": 10,
                              "name": "Loc10 child",
                              "children": [
                                {
                                    "id": 12,
                                    "parentId": 11,
                                    "name": "Loc11 child",
                                    "children": []
                                }
                              ]
                          }
                        ]
                    }
                  ]
              },
              {
                  "id": 7,
                  "parentId": 5,
                  "name": "Loc5 child",
                  "children": []
              }
            ]
        }
        ];

 
    $scope.gridOptions.data = data;
 

  $scope.expandAll = function(){
    $scope.gridApi.treeBase.expandAllRows();
  };

  $scope.toggleRow = function( rowNum ){
    $scope.gridApi.treeBase.toggleRowTreeState($scope.gridApi.grid.renderContainers.body.visibleRowCache[rowNum]);
  };

  $scope.toggleExpandNoChildren = function(){
    $scope.gridOptions.showTreeExpandNoChildren = !$scope.gridOptions.showTreeExpandNoChildren;
    $scope.gridApi.grid.refresh();
  };
}]);


Please reply as early as you could :)
