### ISSUE TITLE
cellEditableCondition Not Working

### ISSUE THREAD

**Issue by goodies4uall** [angular-ui/ng-grid#3248]
I cannot get the cellEditableCondition to work at all when it is based on a property from the row.
 [Here](http://plnkr.co/edit/azJ71IWsHk5iFRbRFYba?p=preview) is a plunker of it working with the classic ng-grid. 
[Here](http://plnkr.co/edit/YZq8z6myxKcLk5ZdMMoc?p=preview) is a plunker of it not working with the new ui-grid.

**Comment by PaulL1** [comment]
1. Cell editable condition is a property of the columnDef: http://ui-grid.info/docs/#/api/ui.grid.edit.api:ColumnDef
2. I think it's better represented as a function, I'm not sure that you can just pass in a variable name like that

http://plnkr.co/edit/ex0kgg0ip8nB7wUaAwUd?p=preview

**Comment by goodies4uall** [comment]
Thank you that worked smoothly. I don't know how I overlooked the example in the API documentation.

**Comment by martinnv6** [comment]
Excelente paúl es así como me funciono, muchas gracias.
//////////////////////////////////////////////////////////////
Excelent, paul is functional, thanks.

**Comment by BillKrat** [comment]
To make the following work:
     cellEditableCondition: "row.entity.IsCustomProp===true"

I had to add an **eval** statement to shouldEdit(col,row).  If the string was not a function it was always evaluating to true from beginEditAfterScroll(triggerEvent) resulting in edits always working.

     function shouldEdit(col, row) {
       return !row.isSaving &&
         ( angular.isFunction(col.colDef.cellEditableCondition) ?
             col.colDef.cellEditableCondition($scope) :
             eval(col.colDef.cellEditableCondition)); // BillKrat.2018.06.31 - added eval
     
     function beginEditAfterScroll(triggerEvent) {
       // If we are already editing, then just skip this so we don't try editing twice...
       if (inEdit) {
         return;
       }
       if (!shouldEdit($scope.col, $scope.row)) {
         return;  // Always returned here if cellEditableCondition was not a function
       }
       ... code to edit cell contents ...
