### ISSUE TITLE
registerColumnsProcessor() not registered on the api

### ISSUE THREAD

**Issue by genu** [angular-ui/ng-grid#3251]
I notice that this function isn't exposed to the grid api. Is there a reason for this?

The implementation is there, but not registered, It just a matter adding 

`self.api.registerMethod('core', 'registerColumnsProcessor', this.registerColumnsProcessor);`

Any thoughts?

**Comment by PaulL1** [comment]
No real reason.  I added rowsProcessors to the api the other day, and I didn't add columnsProcessors at the same time.  For rowsProcessors I also added a priority, which I think we might also want on columnsProcessors if we're going to expose them - that would give people some more control over exactly when their processor runs.

**Comment by PaulL1** [comment]
Closing - now merged.
