### ISSUE TITLE
Fixed left hand side columns that don't horizontally scroll

### ISSUE THREAD

**Issue by muhmud** [angular-ui/ng-grid#3255]
Is it is possible to have a number of columns in the left side of the grid that don't scroll when the grid is horizontally scrolled, like the way Excel does?

Thanks!

**Comment by PaulL1** [comment]
Are you looking at ui-grid or ng-grid?  In ui-grid this is what the pinning feature does: http://ui-grid.info/docs/#/tutorial/203_pinning

**Comment by muhmud** [comment]
ui-grid and fantastic!!
