### ISSUE TITLE
Trackpad scrolling over left pinned container is intermittent

### ISSUE THREAD

**Issue by PaulL1** [angular-ui/ng-grid#3260]
If I go to the pinning tutorial (http://ui-grid.info/docs/#/tutorial/203_pinning) and use my trackpad to scroll over any but the rightmost container, I get jitter in my scrolling.  Sometimes it scrolls normally, sometimes the whole page scrolls without the grid scrolling at all, sometimes it's in between.

It behaves similarly over the rowHeader on selection, and over the groupHeader in grouping, I suspect that it's all pinned containers that exhibit this behaviour.

**Comment by PaulL1** [comment]
Looks like this applies to scrolling over the header as well - scrolling doesn't really work well.

**Comment by jercoh** [comment]
This commit 89461bcbcfdfc527655c398df19555738fa9bd63 broke the ability to disable vertical scrolling. 

Last unstable version:
http://plnkr.co/edit/k46LqpiBc1cesOP8xdIM?p=preview

Unstable version `v3.0.0-rc.20-d4a784f - 2015-04-21`:
http://plnkr.co/edit/35szFnzVSPGinvzJgR8y?p=preview
