### ISSUE TITLE
Radio buttons unchecked after vertical scroll

### ISSUE THREAD

**Issue by XiaoweiJia** [angular-ui/ng-grid#3265]
I have a column  with Input Radios which are checked. But when I scroll the grid some of the radios become unchecked. It seems it happens to random number of radios.
Please help.

Thanks

**Comment by PaulL1** [comment]
I think we'd need a plunker to help you with this.  This doesn't sound like editable, so I'm assuming it's a custom cellTemplate you're using.  The most common error I've seen with custom cellTemplates is using {{}} inside an angular directive when you don't need them, which causes issues with scrolling.

**Comment by PaulL1** [comment]
No further comment for over a month, solution provided that probably resolves the issue.  Closing, please re-raise if there is a reliable recreate or more information.
