### ISSUE TITLE
Double Ajax request when I want to see next pagination files

### ISSUE THREAD

**Issue by rmyemul** [angular-ui/ng-grid#3268]
Dropdown menu is not working when I want to see 10 files it will affect on next click pagination. And each time it will call ajax request for data

**Comment by PaulL1** [comment]
I think you'll need to provide more information.  What exactly are you doing, what version are you using, and what is the dropdown that you are clicking?

**Comment by rmyemul** [comment]
I am changing the page size from 5 to 10 its not getting reflected.

**Comment by totszwai** [comment]
@rmyemul Please create a reduced test case, this is not helping anybody, especially not for Paul to troubleshoot.

**Comment by PaulL1** [comment]
Request for further information, nothing forthcoming for nearly 1 month. Assuming issue has been resolved, closing.
