### ISSUE TITLE
Sorting on grouped colum with null values

### ISSUE THREAD

**Issue by valepu** [angular-ui/ng-grid#3271]
Hi,
If i try to sort a grouped colum that contains null values i receive this error:

"Error: groupingProcessingState[i].currentGroupHeader is null
service.setVisibility@http://localhost/resources/angularjs/grid-3.0.0-rc.20/ui-grid-unstable.js:17249:1
service.groupRows@http://localhost/resources/angularjs/grid-3.0.0-rc.20/ui-grid-unstable.js:16998:13
startProcessor@http://localhost/resources/angularjs/grid-3.0.0-rc.20/ui-grid-unstable.js:4163:23
handleProcessedRows@http://localhost/resources/angularjs/grid-3.0.0-rc.20/ui-grid-unstable.js:4179:20
Ae/e/l.promise.then/F@http://localhost/resources/angularjs/v1.2.26/angular.min.js:100:178
Ae/e/l.promise.then/F@http://localhost/resources/angularjs/v1.2.26/angular.min.js:100:178
Ae/f/<.then/<@http://localhost/resources/angularjs/v1.2.26/angular.min.js:101:350
Zd/this.$get</k.prototype.$eval@http://localhost/resources/angularjs/v1.2.26/angular.min.js:112:64
Zd/this.$get</k.prototype.$digest@http://localhost/resources/angularjs/v1.2.26/angular.min.js:109:160
Zd/this.$get</k.prototype.$evalAsync/<@http://localhost/resources/angularjs/v1.2.26/angular.min.js:112:177
e@http://localhost/resources/angularjs/v1.2.26/angular.min.js:37:495
te/k.defer/c<@http://localhost/resources/angularjs/v1.2.26/angular.min.js:41:235
"

on Chrome the error is (which is the same error, in the end, just with a different wording)

TypeError: Cannot read property 'expandedState' of null
    at Object.service.setVisibility (ui-grid-unstable.js:17249)
    at Grid.service.groupRows (ui-grid-unstable.js:16998)
    at startProcessor (ui-grid-unstable.js:4163)
    at handleProcessedRows (ui-grid-unstable.js:4179)
    at l.promise.then.F (angular.js:11573)
    at l.promise.then.F (angular.js:11573)
    at angular.js:11659
    at k.$get.k.$eval (angular.js:12702)
    at k.$get.k.$digest (angular.js:12514)
    at angular.js:12740

This happens either by clicking on the column header or by chosing the sorting from the column menu.

The same error happens if i try to group a column which the first row has a null value. In this case the grouping happens but the grid doesn't change unless i do some action (like adding another grouping or sorting or filtering)

**Comment by valepu** [comment]
As a temporary solution i did this, which shows an underscore for blank values. Maybe it'd be useful to be able to specify a default value for each column when a cell value is blank

  Grid.prototype.getCellValue = function getCellValue(row, col){
    if (this.options.flatEntityAccess && col.field){
	  //XXX: EDITED
	  if(row.entity[col.field]==null){
	    row.entity[col.field]="_";
	  }
      return row.entity[col.field];      
    } else {
      if (!col.cellValueGetterCache) {
        col.cellValueGetterCache = $parse(row.getEntityQualifiedColField(col));
      }
	  //XXX: EDITED
	  if(col.cellValueGetterCache(row)==null){
	    return "_";
	  }
  
      return col.cellValueGetterCache(row);
    }
  };

**Comment by AgDude** [comment]
I have generated a plunk to look at null values in grouping: http://plnkr.co/edit/UhJTvq?p=preview

I have found that setting a "state" value to null or omitting it, is causing the grid to completely fail to generate (with the error stated by the OP).
