### ISSUE TITLE
'!important' in cell.less & selection.less

### ISSUE THREAD

**Issue by Zorkling** [angular-ui/ng-grid#3281]
The !important in cell.less for the checkbox column seems unnecessary and is causing some difficulty for me while trying to create style overrides. 

Changing the selector for 'ui-grid-row-header-cell' to '.ui-grid-row .ui-grid-cell.ui-grid-row-header-cell' should allow it to take precedence over the stripped row colors without the need for the !important.

Additionally in selection/less/selection.less the selector for a selected row could be modified from '.ui-grid-row-selected > [ui-grid-row] > .ui-grid-cell' to '.ui-grid-row.ui-grid-row-selected > [ui-grid-row] > .ui-grid-cell' to accomplish the same goal.

Please let me know if theres any considerations i missed that would make this change problematic and i will look into it for a more complete solution. If possible I would like to use the default css so that I am able to keep up to date with the latest version and not have compatibility issues, rather than using the customizer or compiling the less myself.

Fantastic job with the 3.0 update, and im looking forward to the release!

(using v3.0.0-rc.20-b0dc47d)

**Comment by c0bra** [comment]
Thanks for the report. I'll look at updating this. If you were wanting to have a go at a PR it would be most welcome.

**Comment by Zorkling** [comment]
Ill give it a shot, and let you know if im able to make progress on it. Thanks for the response!

**Comment by Zorkling** [comment]
@c0bra Completed the changes and made a pull request. Let me know if it looks good and if theres something I can improve upon with my PR process!

**Comment by Zorkling** [comment]
Thanks @c0bra !
