### ISSUE TITLE
How redraw the grid view after modifying grid options from the controller.

### ISSUE THREAD

**Issue by sagar-mindstix** [angular-ui/ng-grid#3283]
Hi  
Just wanted to ask you how redraw the grid view after modifying grid options from the controller.

Example .
  After clicking  on  the grid view, row wanted to show and hide the external panel which has edit and delete button, row details as well. I have added my external template HTML in $templateCache and I have also added extra grid options for it.

**Comment by PaulL1** [comment]
Sorry, what you're trying to do is not entirely clear.  

1.  What version of the grid is this on?
2.  What external panel are you talking about that has edit and delete buttons?  Is this a column that you want to hide?

**Comment by PaulL1** [comment]
Additional information sought, no comment for 3 weeks, closing, please re-raise or reopen if this is still an issue.
