### ISSUE TITLE
[Grouping] blank row headers from fields not on first level

### ISSUE THREAD

**Issue by valepu** [angular-ui/ng-grid#3288]
Hello,
I have noticed that if i add grouping on a colum which field is not a first level element then the group header cell will have a blank value.

For example if my column defs looks like this:

          columnDefs: [
            {field: 'archive.name', displayName: "Archive Name", width: 70, minWidth: 50}
            //more...
          ]

and data looks like this:

        [
          {
            identifier: "00AA",
            archive: {
              name: "Archive",
              description: "My Archive"
            }
          }
          //more...
        ]
Then i group for Archive Name, the groups will have a blank cell instead of the archive name.
This happens because of the way the header row is created:

          // TODO: can't just use entity like this, have to use get cell value, need col for that
          var newValue = grid.getCellValue(renderableRows[rowIndex], col);
          headerRow.entity[fieldName] = newValue;
          headerRow.groupLevel = stateIndex;
          headerRow.groupHeader = true;
          headerRow.internalRow = true;

headerRow.entity[fieldName] = newValue will create a value named "archive.name" and not an object "archive" with a parameter called "name". Your TODO makes me think you have already realized this, so i'm writing this issue just to post a temporary fix for those who need it. 

Edit the last part of Grid.prototype.getCellValue function to look like this:

    if (!col.cellValueGetterCache) {
      col.cellValueGetterCache = $parse(row.getEntityQualifiedColField(col));
    }
    //Added to get header value in grouping when value is nested
    if(col.cellValueGetterCache(row)==null){
      return row.entity[col.field];
    }
    return col.cellValueGetterCache(row);

**Comment by PaulL1** [comment]
Yes, that will work.

The right answer here is to write a function that:
1.  Looks to see if the name has `.` in it, and breaks that down to create a cascading series of objects
2.  Looks to see if the binding is a function, and if it does, then creates a function that just returns our specified value.

It's doable, and we have some similar code in gridUtil that's used by getCellValue (but the other way - as an accessor not a creator).  But it's sort of on the todo list.

**Comment by AgDude** [comment]
@valepu I think this is fixed in the current unstable. Will you please confirm?

**Comment by valepu** [comment]
Yes i can confirm it works, see this Plunker: http://plnkr.co/edit/NPazbil7fCU39SgHviDf?p=preview (company name and company mail are 2nd level fields. Sorry for being lazy with sample data)
