### ISSUE TITLE
Chrome - grid menu items position issue 

### ISSUE THREAD

**Issue by rquiroz6** [angular-ui/ng-grid#3291]
In Chrome, it seems as though whenever the UI Grid contains exactly 8 columns, the menu item in the grid menu that corresponds to the first column is positioned above the "Columns:" item in the grid menu. In a grid with 7 or 9 columns, all column items appear below "Columns:", as expected. The issue does not occur in IE 11.

Plunker with 8 columns and grid menu enabled: http://plnkr.co/edit/eefIVsjOCae2odgz9Xda?p=preview

**Comment by c0bra** [comment]
Pinging @PaulL1

**Comment by PaulL1** [comment]
Hmm.  The new grid menu sorting should have avoided that.  :-)  Looks like I set the `columns` item to 300, then each column menu item to `300 + index * 2` or `300 + index * 2 + 1` (there are two menu items for each column - one show, one hide).  The array is zero based, so the first menu item also has a priority of 300, and Chrome has unstable sorting, so it's random which one is on top.

I'll push a fix later today.
