### ISSUE TITLE
Header Rows for grouped records

### ISSUE THREAD

**Issue by MagicIndustries** [angular-ui/ng-grid#3294]
I can't seem to find an answer so I thought I'd ask here - how can I create a row template that lets me put a header in above grouped records?  For example, for a list of documents in different folders I'd like to display them like this:

    Name                    |   Type          |  Owner
    ------------------------------------------------------------------------
    Folder: /invoices
    invoice1.doc          |  Word          | Bob Jones
    ------------------------------------------------------------------------
    invoice2.doc          |  Word          | Jim Bloggs
    ------------------------------------------------------------------------
    Folder: /Designs
    Design1.doc          |  Word          | Bob Jones
    ------------------------------------------------------------------------
    Design2.doc          |  Word          | James Smith
    ------------------------------------------------------------------------
    Design3.doc          |  Word          | Jim Bloggs

So the above record set is grouped on folder.  Is there any way to achieve this currently?

**Comment by PaulL1** [comment]
Your markup is a bit hard to read.  So it looks like the first row is your headers, and then you have 5 documents, and you want to insert the two header rows?

You could maybe use treeView for this - add the group rows into the data, and set them to be $$treeLevel=0.  http://ui-grid.info/docs/#/tutorial/215_treeView

Is that what you had in mind?

**Comment by MagicIndustries** [comment]
Yeah sorry, no idea why it's marking up like that. You're correct, the top line is the actual column headers, then the rest are document rows.

The rows with "Folder: whatever" I want to use like a row header for each group of rows under a folder. I don't want an actual row header in a column on the left hand side, I want it to sit in there like a normal row.  If I were to do it in html it would look like this:

    Yeah sorry, no idea why it's marking up like that. You're correct, the top line is the actual column headers, then the rest are document rows.
    
    The rows with "Folder: whatever" I want to use like a row header for each group of rows under a folder. I don't want an actual row header in a column on the left hand side, I want it to sit in there like a normal row.  If I were to do it in html it would look like this:
    
    <table>
        <tr>
            <th>Name</th>
            <th>Type</th>
            <th>Owner</th>
        </tr>
        <tr>
            <td colspan="3">Folder:  Invoices</td>
        </tr>
        <tr>
            <td>Invoice1.doc</td>
            <td>Word</td>
            <td>Bob Jones</td>
        </tr>
        <tr>
            <td>Invoice2.doc</td>
            <td>Word</td>
            <td>Jim Bloggs</td>
        </tr>
        <tr>
            <td colspan="3">Folder:  Designs</td>
        </tr>
        <tr>
            <td>Design1.doc</td>
            <td>Word</td>
            <td>Bob Jones</td>
        </tr>
        <tr>
            <td>Design2.doc</td>
            <td>Word</td>
            <td>James Smith</td>
        </tr>
        <tr>
            <td>Design3.doc</td>
            <td>Word</td>
            <td>Jim Bloggs</td>
        </tr>
    </table>
        
Does that make more sense?  I can try the tree view, but I still want the user to be able to click the column headers and re-order the rows *within* the folders.

**Comment by PaulL1** [comment]
There isn't currently any logic that would let you re-order within a group - that's not what grouping does.  When you re-order with grouping, you're actually reordering all the rows, then grouping that new sort order.  

What you're describing is much more akin to treeView, the problem is that we haven't written the sorting for treeView yet.  At the moment it just renders the rows it's given in the order it's given.  Doing a recursive sort within each of the nodes of the tree is somewhat more complex, and we haven't written that - it'd have to be an extension of the treeView feature.

What you could do, in order to get that effect (if you really need sorting) is to turn on external sorting, and then listen for the sort events.  Whenever anyone sorts by anything you could then resort your data based on your knowledge of what that should mean, the nodes etc.

Or, submit a PR to extend the sorting for treeView.  :-)

**Comment by MagicIndustries** [comment]
Ok that makes sense. I'll give the tree view a try, and if I get sorting working I'll organise a PR. Thanks very much for the help.

**Comment by MagicIndustries** [comment]
Sorry another question - I'm almost there with the tree view. I can't seem to get rid of the row header column that it adds though. I want to ensure the rows are always expanded and to get rid of that extra column on the left that holds the expansion symbols. Is there any way to do this?

**Comment by PaulL1** [comment]
Not in the base code, although it'd be quite easy to add (grouping has a suppressHeader I think, or something similar).

With what's there you could set the header width to 0 and the indent width to 0.  But I think there's a min column width that will catch you out.

Probably easier if I write a new option for you.

**Comment by MagicIndustries** [comment]
I'd agree that the option should be there long term, but embarrassingly I just realised how I can achieve the same thing without all that.

1) order data set by the item I want to "group" on.
2) loop over the set and every time that field changes (IE we've reached the beginning of a new group) splice in an extra row with only the properties: bFolderRow:true, desiredGroupingProperty: currentGroup
3) Have a row template with a conditional display - if the row has bFolderRow then just output a simple line with the property value I want, otherwise use the standard row template stuff to output all the columns.

This actually achieves everything I need without grouping or tree view :)  Here's an example:

    var rowTemplate = '<div ng-if="row.entity.hasOwnProperty(\'bFolderRow\')">{{row.entity.documentLocationPath}}</div>' +
                        '<div ng-if="!row.entity.hasOwnProperty(\'bFolderRow\')"><div ng-repeat="(colRenderIndex, col) in colContainer.renderedColumns track by col.colDef.name" class="ui-grid-cell" ng-class="{ \'ui-grid-row-header-cell\': col.isRowHeader }"  ui-grid-cell></div></div>';

    function convertDataToTree ( aDocs ) {
        var _aDocs = lodash.sortBy( aDocs, 'documentLocationPath' );
        var prevLocation;
        lodash.each( _aDocs, function ( doc, key ) {
            if ( doc.documentLocationPath !== prevLocation ) {
                // insert a folder row
                _aDocs.splice( key, 0, {
                    documentLocationPath: doc.documentLocationPath,
                    bFolderRow:           true
                } );
            }
            prevLocation = doc.documentLocationPath;
        });
        return _aDocs;
    }

Thanks muchly for the quick responses, apologies for the waste of time :)

**Comment by PaulL1** [comment]
Sounds excellent then.
