### ISSUE TITLE
variable height rows + small virtualizationThreshold = jerky scrolling

### ISSUE THREAD

**Issue by ssteffl** [angular-ui/ng-grid#3296]
I have grid rows that have user input in them, so i have to wrap text. This leads to some rows being taller than other rows. if i set virtualizationThreshold < # rows in grid, when I scroll, it will jump around when the row added is not the same height as the row that was removed from the gridbody.

My current fix to avoid jumping while scrolling with variable height rows is to set virtualizationThreshold to 10000000 or something very large. Unfortunately this is bad for large datasets....

I was looking at the ng-grid code and was not sure how this could be fixed.

The modifications i added are below if it helps:

    .ui-grid-row, 
    .ui-grid-cell { height:initial !important; }
    .ui-grid-row > div {
	    display:flex !important;
	    align-items:stretch !important; }
    .ui-grid-cell,
    .ui-grid-cell * { white-space: normal !important; }

heres a plunkr that demonstrates the issue: http://plnkr.co/edit/RC6WvGB2VTHk5egP4E9e?p=preview

**Comment by PaulL1** [comment]
The grid doesn't currently support variable height rows.  This is on the roadmap, but as you have noted, it doesn't work at the moment, for exactly the reason you noted - the scroll calculations assume all rows are the same height.

**Comment by PaulL1** [comment]
Closing, there is an existing open item for variable row height.
