### ISSUE TITLE
Horizontal Scroll bar appears in browser when grid menu displayed.

### ISSUE THREAD

**Issue by dimetrym** [angular-ui/ng-grid#3299]
To reproduce open your main http://ui-grid.info/ page.
Try to open menu for Gender column in Basic example grid. Horizontal scroll bar appears in Web browser (latest IE, Chrome) and page layout is broken. 
 
![image](https://cloud.githubusercontent.com/assets/7129551/7200224/81c1f926-e503-11e4-9313-98bcc409433a.png)

Seems this problem appears in one of the latest build. 
Thank you!

**Comment by PaulL1** [comment]
I don't get this scrollbar.

What do you mean by "page layout is broken"?

**Comment by dimetrym** [comment]
It is 100% reproducible on Chrome, IE, Firefox (Windows). Browser window must be maximized so grid right border is near browser right border.
I mean that page has horizontal scrollbar at the bottom. Please take a look at the attached screenshot and how site is looking after opening grid menu.

![image](https://cloud.githubusercontent.com/assets/7129551/7215926/5c2bfb20-e5f4-11e4-9201-911b0c5f6f3f.png)

**Comment by dimetrym** [comment]
This bug appears in 
 * ui-grid - v3.0.0-rc.20-8199eb5 - 2015-04-13

**Comment by dimetrym** [comment]
@PaulL1 , is there any chance that this bug will be fixed in one of the nearest builds? it is easy to reproduce.
Step 1: open http://ui-grid.info/docs/#/tutorial/216_expandable_grid
Step 2: Open menu for "Address.City" column.
![image](https://cloud.githubusercontent.com/assets/7129551/7296682/64d4a36a-e9ca-11e4-938f-24729d0d53e9.png)
Strange horizontal scroll bar appears at the page bottom (marked in red color).

Step3 : scroll page horizontally

![image](https://cloud.githubusercontent.com/assets/7129551/7296711/bdd17fc4-e9ca-11e4-9eea-e85c1e834242.png)

It is reproducible on all major browsers on Windows (Chrome, IE, Firefox, Opera).
Thank you!

**Comment by dimetrym** [comment]
This code is from <b>ui-grid - v3.0.0-rc.20-8199eb5 - 2015-04-13</b>
.ui-grid-column-menu {
  position: relative;
}

Restoring it  to <b>ui-grid - v3.0.0-rc.20-b0dc47d - 2015-04-12</b>
.ui-grid-column-menu {
  position: relative;
}
and bug disappears

Thank you for awesome grid..

**Comment by dimetrym** [comment]
it's fixed in  <b> ui-grid - v3.0.0-rc.21-43f63ac - 2015-04-28.</b>
Thank you!

**Comment by shaileshayer** [comment]
Hi, when you show hide columns in UI Grid. There is shift in the menu items. It is only replicated in IE browser
