### ISSUE TITLE
ui grid export does not work

### ISSUE THREAD

**Issue by alexdav89** [angular-ui/ng-grid#3303]
examples on website export does not work,  
http://ui-grid.info/docs/#/tutorial/312_exporting_data_complex

I can export in CSV with my previous version but pdf does not work on there too
any ideas how to make it working or where can I get old working version?

**Comment by c0bra** [comment]
What browser/OS are you using? It's working for me on Chrome / Win7.

I believe there's a known issue with IE and the PDF library we're using.

**Comment by PaulL1** [comment]
It was broken - I broke it when I merged #3027 exportAll for pagination.  I fixed it yesterday, but was waiting for the fonts to come right before I marked as fixed.

**Comment by c0bra** [comment]
I'll close then.
