### ISSUE TITLE
Exporting to CSV/PDF TypeError: Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by sameershenai** [angular-ui/ng-grid#3306]
Getting this error for csv and pdfExport -> Cannot read property 'then' of undefined
at Object.service.csvExport (ui-grid-unstable.js:15396)

This error is also seen in the tutorial section ->http://ui-grid.info/docs/#/tutorial/206_exporting_data

**Comment by PaulL1** [comment]
I believe this is fixed, closing.
