### ISSUE TITLE
Number Sorting not working when applied cellFilter

### ISSUE THREAD

**Issue by aimeehwang** [angular-ui/ng-grid#3308]
I wanna display a US dollar sign before the numbers (eg: $400,890). With cellFilter(eg: {name:'12 mo ending Sept2014', field:'12moendingSept2014', cellFilter: 'currency'}), I am able to do that but after using the filter, the sorting for numbers doesn't work anymore, every number is being treated as a String.

Is there any way that I can make the sorting work without defining a sortAlgorithm myself?

**Comment by PaulL1** [comment]
The sorting doesn't reflect the cellFilter at all, so cellFilter shouldn't impact.  I'd suspect the sorting wasn't working before the cellFilter change.

You can set a colDef.type, and if you have numbers inside a string, the type you want I think is 'numberStr'.

**Comment by aimeehwang** [comment]
You are right, the sorting doesn't work in the first place. What do you mean by set a colDef.type, so I do have to define a sorting algorithm?

**Comment by PaulL1** [comment]
The sorting determines which sorting algorithm to use based on the column.type.  It can either guess the type, or it can be set manually in the colDef, by setting the type.  The valid values are documented in the colDef api information: http://ui-grid.info/docs/#/api/ui.grid.class:GridOptions.columnDef

**Comment by aimeehwang** [comment]
it works right now, thanks a lot!

**Comment by PaulL1** [comment]
Looks resolved, closing.
