### ISSUE TITLE
Not able to get the selected rows in the UI-Grid.

### ISSUE THREAD

**Issue by siddhsuper** [angular-ui/ng-grid#3314]
Hi,

I am new to the ui-grid, trying to get the selected item from the ui-grid, but not able to get the selected item.
```
$scope.gridRolesList.onRegisterApi = function(gridApi){
                  //set gridApi on scope
                  $scope.gridApi = gridApi;
                  $scope.mySelectedRows = $scope.gridApi.selection.getSelectedRows();
                  gridApi.selection.on.rowSelectionChanged($scope,function(row){
                    console.log('row selected ' + row.isSelected);
                  });
                  
                  //var g = $scope.gridApi.selection.getSelectedRows();   
                  gridApi.selection.on.rowSelectionChangedBatch($scope,function(rows){
                    console.log('rows changed ' + rows.length);
                  });
                };  
```

gridApi is showing undefined, and that's the reason the $scope.gridApi = gridApi;
                  $scope.mySelectedRows = $scope.gridApi.selection.getSelectedRows(); is not getting set.

**Comment by PaulL1** [comment]
What other errors do you have on your javascript console?  Is the grid rendering at all?  Where in your code is this function - is it part of grid initialisation before the grid initially renders?

**Comment by siddhsuper** [comment]
There are no other errors.
Yeah Grid is rendering properly. And I am able to select the rows but not able to get the selected rows.
Below are the piece of code which I am calling before the  onRegisterApi.

```
                $scope.gridRolesList.rowHeight = 50;
                $scope.gridRolesList.enableSorting = false;
                $scope.gridRolesList.enableFiltering = false;
                $scope.gridRolesList.data = rolesCollection;
                $scope.gridRolesList.multiSelect = true;
                $scope.gridRolesList.enableRowSelection = true,
                $scope.gridRolesList.enableSelectAll = true,                
                //$scope.gridRolesList.showGridFooter = true,
                $scope.gridRolesList.columnDefs = [                    
                    { name: 'roleName', displayName: 'Name' },
                    { name: 'Actions',
                    cellTemplate: '<button class="btn btn-primary" ng-click="grid.appScope.EditRole(row.entity.roleName)">Edit</button><button class="btn btn-primary" ng-click="grid.appScope.DisableRoles(row.entity.roleName)">Disable</button>'
                }];
```

**Comment by PaulL1** [comment]
It's working for me here: http://plnkr.co/edit/JNID2STlF0QELj2dpqzZ?p=preview

Just to be clear - are you getting the selected rows as soon as the grid has rendered (in the onRegisterApi)?  Surely there won't be any rows selected at that point?  Don't you have to wait until the user selects some rows before getting them?

**Comment by siddhsuper** [comment]
A big thank you @PaulL1 .

As I said onRegisterApi was not getting initialized, reason was I had written it inside  $http.get() call.
Hence, gridApi was not getting initialized.

Now, it's working great.

**Comment by Basel78** [comment]
HI PaulL,
I am facing the same issue with UIGrid in SharePoint 2013, I am using UI-Grid to select few Items in the grid to have certain action on it, but couldn't get the selected rows by using the function mentioned in your sample above, even though I've downloaded the same "ui-grid-unstable.js", "ui-grid-unstable.css" from the sample and almost copied the same steps of configuring the grid and how populate it with data, in addition to the note of initilizing gridAPi by siddhusper, all that and I am still unable to get selected rows by:
$scope.mySelectedRows = $scope.gridApi.selection.getSelectedRows();

so I used another method: gridApi.selection.on.rowSelectionChanged($scope, function (row) { ..}
to get each row and add it to my selectedrows = [];

its working fine with an issue that I couldn't handle  when "Select All/Deselect All" the ticker button of the Grid clicked, so I can reset my SelectedRows[] Array.
any help or advice is really appreciated.

**Comment by lpand** [comment]
@Basel78 you should read the [documentation](http://ui-grid.info/docs/#/api/ui.grid.selection.api:PublicApi) of ui.grid.selection. The secret is `rowSelectionChangedBatch()`

```Javascript
gridApi.selection.on.rowSelectionChanged(scope, singleSelect)
gridApi.selection.on.rowSelectionChangedBatch(scope, function (rows) {
    rows.forEach(singleSelect)
})
```

**Comment by Basel78** [comment]
Thanks iPand for the reply,
Actually, the rowSelectionChangedBatch() is not fired in my case,
so is there a property needs to be enabled except , enableSelectionBatchEvent : true.
and where the event handler should comes in the code, as you mentioned its falling inside "gridApi.selection.on.rowSelectionChanged() {}" , but as for the documentations it's coming after it, and inside "$scope.gridOptions.onRegisterApi= " exactly like  rowSelectionChanged().

it seems that I have problem to fire rowSelectionChangedBatch function in my code, can you please describe how to do it in code.

I will put part of the code can explain to me what I did wrong?

$scope.gridOptions = {
        enableRowSelection: true,
        enableSelectAll: true,
        selectionRowHeaderWidth: 35,
        rowHeight: 35,
        showGridFooter: true,
        enableSelectionBatchEvent: true
    };
$scope.gridOptions.columnDefs = [
      { field: 'ProductID', displayName: 'Product ID' },
      { field: 'ProductName', displayName: 'Product Name' },
      { field: 'SupplierID', displayName: 'Supplier ID' },
      { field: 'CategoryID', displayName: 'Category ID' },
      { field: 'QuantityPerUnit', displayName: 'Quantity Per Unit' },
      { field: 'UnitsOnOrder', displayName: 'Units On Order' }
    ];
    $scope.info = {};

 $scope.getSelectedRows = function () {
        $scope.mySelectedRows = $scope.gridApi.selection.getSelectedRows();
    };

    $scope.gridOptions.onRegisterApi = function (gridApi) {
        $scope.gridApi = gridApi;
       
        gridApi.selection.on.rowSelectionChanged($scope, function (row) {
            $scope.SelectedProduct = row.entity; 
      });

        gridApi.selection.on.rowSelectionChangedBatch($scope, function (rows) {

            rows.forEach($scope.SelectedProduct);
        });
    };

**Comment by Basel78** [comment]
After deep checking on my case, I found out that I am two UI grid in my page, with same 
<pre><code> $scope.gridApi = gridApi;</code></pre>
so what is happening is a conflict BTW the gridApi on both grids, and when I checked the items on the first gird , the gridApi is working on the second one that is having mo items yet :)

anyway I Listen here is we should use different "$scope.gridApi" for different grids on the same page!

Thanks lpand for your help.

**Comment by PaulL1** [comment]
You should really do $scope.gridApi1 and $scope.gridApi2 if you have two grids in the same controller.

**Comment by piyush-dholariya** [comment]
how can I highlight ui-grid row on selection/click, which has 6 pinned columns?
