### ISSUE TITLE
Expandable example

### ISSUE THREAD

**Issue by soundar84** [angular-ui/ng-grid#3318]
HI,
        If anybody having sample code for expandable gridview. Please share simple code.

Thanks,
Soundar

**Comment by PaulL1** [comment]
Is the tutorial not sufficient?  http://ui-grid.info/docs/#/tutorial/216_expandable_grid

**Comment by tanak** [comment]
And have a look at this plunker
http://plnkr.co/edit/8phKFI0hzfmN7lWK9zMe?p=preview

**Comment by PaulL1** [comment]
Looks like issue is resolved, closing.
