### ISSUE TITLE
Pagination Display Problem.

### ISSUE THREAD

**Issue by debayan31** [angular-ui/ng-grid#3327]
If I compare pagination looks of Angular Grid with Kendo Grid then Kendo looks much professional in that case. So can we able to change Angular Grid display property? 

![pagination](https://cloud.githubusercontent.com/assets/11749797/7246372/e243a330-e819-11e4-8feb-da5e50992a0d.jpg)

**Comment by PaulL1** [comment]
No, the grid does what it does, unless someone wants to submit a pull request with different look and feel.  You can replace the pagination directive and/or template, which may give you what you're looking for, but it would be complex to do so.

**Comment by debayan31** [comment]
If I make changes inside $templateCache.put('ui-grid/pagination',...) , it will also serve my purpose.Right Paul.

**Comment by debayan31** [comment]
I have written below code for pagination : 
 
$templateCache.put('ui-grid/pagination',
    "<div class=\"ui-grid-pager-panel\" ui-grid-pager ng-show=\"grid.options.enablePaginationControls\">\n\
    <ul class=\"pagination\" ng-if=\"1 < paginationApi.getTotalPages()\">\n\
    <li ng-class=\"{ disabled : grid.options.paginationCurrentPage == 1 }\">\n\
        <a href=\"\" ng-click=\"paginationApi.seek(1)\"  ng-disabled=\"cantPageBackward()\">&laquo;</a>\n\
    </li>\n\
    <li ng-class=\"{ disabled : grid.options.paginationCurrentPage == 1 }\">\n\
        <a href=\"\" ng-click=\"paginationApi.previousPage()\"  ng-disabled=\"cantPageBackward()\">‹</a>\n\
    </li>\n\
    <li ng-repeat=\"pageNumber in paginationApi.getTotalPagesArray(paginationApi.getTotalPages()) track by $index\" ng-class=\"{ active : grid.options.paginationCurrentPage == pageNumber.id, disabled : pageNumber == \'...\' }\">\n\
        <a href=\"\" ng-click=\"paginationApi.seek(pageNumber.id)\"   ng-disabled=\"cantPageBackward()\">{{ pageNumber.id }}</a>\n\
    </li>\n\
    <li ng-class=\"{ disabled : grid.options.paginationCurrentPage == paginationApi.getTotalPages() }\">\n\
        <a href=\"\" ng-click=\"paginationApi.nextPage()\"  ng-disabled=\"cantPageForward()\">›</a>\n\
    </li>\n\
    <li ng-class=\"{ disabled : grid.options.paginationCurrentPage == paginationApi.getTotalPages() }\">\n\
        <a href=\"\" ng-click=\"paginationApi.seek(paginationApi.getTotalPages())\"  ng-disabled=\"cantPageToLast()\">&raquo;</a>\n\
    </li>\n\
    </ul>\n\
    <div class=\"ui-grid-pager-count-container\">\n\
        <div class=\"ui-grid-pager-count\">\n\
            <span ng-show=\"grid.options.totalItems > 0\">{{showingLow}} - {{showingHigh}} of {{grid.options.totalItems}} {{totalItemsLabel}}</span>\n\
        </div>\n\
    </div>\n\</div>");

Function ::

getTotalPagesArray: function (pageSize) {
                    
                  var arrayPage = new Array();
                  for(var i=0 ; i < pageSize; i++){
                      var newElement = {};
                      newElement['id'] = i+1;
                      arrayPage.push(newElement); 
                  }
                  return arrayPage;
                };

But whenever I am going to a page through pagination the page content is loading for a while and then coming to 1st page.

I think some scope issue is happening here.Kindly have a look and help.

![pagination](https://cloud.githubusercontent.com/assets/11749797/7252424/7cebab8e-e852-11e4-8910-749ee6a211e4.jpg)

**Comment by debayan31** [comment]
Hi PauL,

It is now working fine .So I am cosing this issue.
