### ISSUE TITLE
ui-grid does not take 100% width on page load and grid looks squeeze

### ISSUE THREAD

**Issue by mukundkmr** [angular-ui/ng-grid#3330]
I am using ui-grid to showing data in table. when i load the page and leave for few second and then click on the tab (which containing ui-grid), the ui-grid css break. it does not show width of ui-grid 100% of container.but when i load page and just click on tab (containg ui-grid). ui-grid is showing perfect, i mean width of that is 100% of container. I don't know what is the problem.this is the code, i am working on .

complete code which i written is here:
http://stackoverflow.com/questions/29763842/ui-grid-does-not-take-100-width-on-page-load

![capture](https://cloud.githubusercontent.com/assets/6688406/7253081/c97d0d62-e7ee-11e4-8ad7-98f82bbc7d56.PNG)

**Comment by PaulL1** [comment]
I've answered on the stackOverflow question.  My best guess is animations, meaning that the workaround we use on modals would perhaps work: http://ui-grid.info/docs/#/tutorial/110_grid_in_modal

**Comment by mukundkmr** [comment]
@PaulL1 , you are right. i resolved this issue using the following chunk of code:


    onRegisterApi: function (gridApi) {
        $scope.gridApi = gridApi;
        // below mentioned code resolve my issue(window resizer issue) 
        $interval( function() {
            $scope.gridApi.core.handleWindowResize();
        }, 10, 500);
     }

**Comment by cathydomini** [comment]
I have the same problem. Can you put the workaround in Plunker. Thanks
