### ISSUE TITLE
Support for number input restrictions

### ISSUE THREAD

**Issue by sleiber** [angular-ui/ng-grid#3331]
I couldn't find an easy way to implement input restrictions (min/max/step) on number input types without creating a custom template.  Am I missing an obvious way to get this done?  If not, would you take a pull request so that a columnDef could be defined like this:
{ type: 'number', min: 0, max: 100, step: 10}

**Comment by PaulL1** [comment]
We'd take a PR for that, but you need to be careful about browser limitations.

**Comment by PaulL1** [comment]
Closing, as no progress for over a month.  Reopen or submit a pull request if/when you get time.
