### ISSUE TITLE
[moveColumn] Sorting by clicking column header broken - triggering move instead

### ISSUE THREAD

**Issue by brockj** [angular-ui/ng-grid#3333]
I think this was introduced in the last few days, but clicking on the header to sort a column no longer works
you can see this in http://ui-grid.info/docs/#/tutorial/102_sorting
Clicking on the name/gender columns has no effect, but using the menu works

I will try to isolate the change that caused this.  I am currently on 7df7234

**Comment by brockj** [comment]
This is super strange.  It only appears on Chrome and restarting the browser a few times made the issue go away.  Chrome version is 42.0311.90.m

please close if you can't reproduce

**Comment by PaulL1** [comment]
It's working for me, but I'll leave it open and see if anyone else has issues.

**Comment by StanislavPrusac** [comment]
Sorting by click with mouse at header still is not working.
I tested at link : http://ui-grid.info/docs/#/tutorial/102_sorting  and in my application 
Sometime when start fresh Google Chrome, working but after refresh this same page stopped.
Working  normal in Firefox 37.0.2
Google Chrome: Version 42.0.2311.135 m (64-bit)
Windows 7
Angular-ui-grid,version: 3.0.0-rc.21

**Comment by sandeeppbajaj** [comment]
Yes...its acting weird. It needs to be clicked 2-4 times and it goes through stages asc, desc and no-sorting.

**Comment by enigmak** [comment]
It looks like chrome calls the move function when the mouse has not moved much and the other browsers do not.

Changing the downFn to track the event.pageX and then checking it in the moveFn will correct this.

So in the downFn add the $scope.previousMouseX = event.pageX;
```
              $scope.mousedownStartTime = (new Date()).getTime();
              $scope.mousedownTimeout = $timeout(function() { }, mousedownTimeout);
              $scope.previousMouseX = event.pageX;
```

Then in the move function check for movement.
```
            $scope.moveFn = function( event ){
              var xMove = $scope.previousMouseX - event.pageX;

              // If we haven't moved let mouse up call fire.
              if (xMove !== 0) {
                // we're a move, so do nothing and leave for column move (if enabled) to take over
                $timeout.cancel($scope.mousedownTimeout);
                $scope.offAllEvents();
                $scope.onDownEvents(event.type);
              }
            };
```

**Comment by PaulL1** [comment]
OK, I did the work on the downFn and move stuff, so I guess I get to fix this.

**Comment by Zorkling** [comment]
@enigmak You can also acomplish this by just varing up a previousMoveX and setting it during the down event handling. Since the drag activation only needs to happen once, and the previous move can be reset on any down event, theres no need for timers.

@PaulL1  Would you like me to make a PR for this? I had messed with it previously but hadnt gotten around to commiting the fix

**Comment by PaulL1** [comment]
@Zorkling : that would be useful.

**Comment by Zorkling** [comment]
@PaulL1 Pull request ready, my bad for the double commit, got too hasty with the push

In case anyone is curious, the issue has existed for almost a couple of years, heres a chromium issue that describes alot of the behavior around it
https://code.google.com/p/chromium/issues/detail?id=327114
