### ISSUE TITLE
How to select multiple cell (excel style) in 3.0.0-rc.20

### ISSUE THREAD

**Issue by dksfcb** [angular-ui/ng-grid#3334]
We need to make cell selection (excel) style and also copy&paste to and fro from excel to ui-grid.
Is this supported?
Any pointers?

Will appreciate help
Regards

**Comment by PaulL1** [comment]
We don't support selecting multiple cells at the moment, and we don't support pasting into the grid other than cell by cell. We'd welcome a PR that did this, but I think it'd be more complex than you might think - I looked at copying to the clipboard at one point and it wasn't easy.

You could take a look at the combination of importer and exporter, they provide similar capability, just not in quite the same way.

**Comment by PaulL1** [comment]
Solution provided that may resolve it, no comment for 3 weeks, closing, please re-raise or reopen if this is still occurring.
