### ISSUE TITLE
Takes lot of time to render large json data

### ISSUE THREAD

**Issue by 1karthik** [angular-ui/ng-grid#3335]
$http.get('resturl').success(function (data) { //makes a rest call here
        $scope.myData = data;
    }); 
The data loads in grid only after request completes. I have very large data so this makes user to wait for 2 min - 3 min to load grid. Is there a way to render large data quickly ?

**Comment by PaulL1** [comment]
Only if you receive the data from your server in chunks.  You could consider infinite scroll or similar, or if you have some sort of streaming protocol with your server that lets you get subsets of the data, you could write logic that gets the data in pieces, and then concatenates them into $scope.gridOptions.data.

**Comment by 1karthik** [comment]
Does pagination of ng-grid can help ? I tried and did not succeed
When i change a page it makes request every time and fetches data.
I tried setting offset to fetch data limitedly but cassandra doesn't support offset(which is supported in mysql).

**Comment by PaulL1** [comment]
Pagination could help, but fundamentally ui-grid can't do anything about your data retrieve time, it only gets the data after you've retrieved it.  The question is whether you can modify your server to get smaller chunks of data, and if doing so would actually make it faster.  ui-grid has a few ways to deal with smaller chunks of data - you can:

1. Use pagination
2. Use infinite scroll
3. Just load the first 200 rows into the grid, then append the rest onto the data when they become available

As a matter of interest - why is your server query so slow?  Is it just a matter of indexing your database better?  2-3m is a very long time - how many rows are we talking?  Is it database time that's the problem, server processing time, or network transmission time?

**Comment by PaulL1** [comment]
Potential resolution provided - no further comment for some time, presuming problem has been resolved.
