### ISSUE TITLE
cellFilter applied for cellTooltip

### ISSUE THREAD

**Issue by iorzetic** [angular-ui/ng-grid#3336]
For the cellTooltip, if the function returns true than the tooltip value would be the cell value.
I think that instead of returning the actual cell value we should return the cell value with the cellFilter applied to it.

Or if this is not the desired behaviour for the default tooltip, please indicate how we could simply achieve this without compromising performance.

**Comment by PaulL1** [comment]
Oversight on my part.  I only use tooltips for long description fields, so I hadn't considered the need for filters.

**Comment by iorzetic** [comment]
That was fast! Thanks guys!
