### ISSUE TITLE
Virtualised columns not rendering on resizing to larger size

### ISSUE THREAD

**Issue by acheshire-scottlogic** [angular-ui/ng-grid#3338]
If the window is resized to be made smaller so that some of the columns are not rendered due to virtualization. When maximizing the window the non-rendered columns will not appear even if they should now be visible.

Triggering a grid refresh fixes the issue and the columns appear as they should.

**Comment by PaulL1** [comment]
This is currently expected behaviour unless you're using the auto-resize feature.

**Comment by acheshire-scottlogic** [comment]
@PaulL1 Thanks for the answer. We would rather not use this feature due to performance issues so we will look for our own way around it.

**Comment by PaulL1** [comment]
This looks resolved through other means, closing.
