### ISSUE TITLE
How can I change the GridMenu icon to a Font Awesome icon?

### ISSUE THREAD

**Issue by double3** [angular-ui/ng-grid#3339]
I definitely don't want to change that icon in the original .js from UI Grid. So how can I change it via my own .js file?

Same with other icons like the plus and minus in expandable rows? Those seem to be coming from a font. ???

Thanks!

**Comment by SayusiAndo** [comment]
I assume you can overwrite the style included there by your own CSS class if your CSS file is included later. However, I don't know on how many places this css class is used.

**Comment by double3** [comment]
figured it out. i targeted the "i" inside the parent div ...

$('[ui-grid-menu-button]').find('i').removeClass('ui-grid-icon-menu').addClass('fa fa-columns');

**Comment by prasad414** [comment]
Just add override below class in your css file :
```
.ui-grid-icon-angle-down:before {
        font-family: FontAwesome;
        content: "\f013";
    }
```

**Comment by specter01wj** [comment]
The GridMenu icon, it should be:
.ui-grid-icon-menu-down:before {
    font-family: FontAwesome;
    content: "\f013";
}
