### ISSUE TITLE
setting $scope.gridOptions.columnDefs[0].visible = false doesn't hide column

### ISSUE THREAD

**Issue by dereklin** [angular-ui/ng-grid#3341]
Instead, I have to do something like:

$scope.gridOptions.columnDefs[0] = { field: $scope.gridOptions.columnDefs[0].name, visible: false };

I took what Paul has created and put a plunker here: http://plnkr.co/edit/AjnQEzizYbDodYcyABVR?p=preview

Hide Name 2 works while Hide Name doesn't.

Is it because there is a watch on the object?  But changing the visible field should affect the object as well, right?

**Comment by PaulL1** [comment]
http://plnkr.co/edit/4aoMCmyEGnmmLTGvcAkj?p=preview.  You usually need to call notifyDataChange when you dynamically change columnDefs, this is to avoid a watch on every single property on every columnDef, which would be expensive.

refer: http://ui-grid.info/docs/#/tutorial/113_adding_and_removing_columns

**Comment by dereklin** [comment]
Hi Paul,  You are great!

In this case, I am not removing the column, I am just hiding it.  So I still need to use notifyDataChange, right?

**Comment by PaulL1** [comment]
Thanks for the feedback.  :-)

Yes, most changes to columnDef properties need notifyDataChange.  However, some aren't (yet) dynamic at all, and some get used directly from the columnDefs and so don't need notifying.  It's not obvious which are which to an end user unfortunately.

**Comment by dereklin** [comment]
Does the notifyDataChange work with multiple grids on the page?

**Comment by dereklin** [comment]
OK. Figured it out.  It works.  The key is one gridAPI per grid.

**Comment by PaulL1** [comment]
Looks resolved, closing.

**Comment by Jyotsna008** [comment]
@PaulL1 Hi Paul,Can u tell me how to hide columns in angular 4
