### ISSUE TITLE
Get Selected Rows With ControllerAs Syntax (no $scope)

### ISSUE THREAD

**Issue by jarzuaga** [angular-ui/ng-grid#3345]
I'm trying to get the grid's selections using the the api (gridApi.selection.on.rowSelectionChanged) on a controller that doesn't inject the $scope. Is this supported? Is there a workaround I can apply?

**Comment by PaulL1** [comment]
The workaround would be to pass rootscope, or to create a new scope and pass that.  The impact is that your listener won't get destroyed, so you need to be careful on garbage collection.

**Comment by jarzuaga** [comment]
Gotcha. I'll give that a try. Thanks.

**Comment by jarzuaga** [comment]
This approach worked. Closing.
