### ISSUE TITLE
ng-grid grid load complete event

### ISSUE THREAD

**Issue by sunil123-github** [angular-ui/ng-grid#3350]
How to attach an event for ng-grid which fires after grid load complete. I did not find any event with respect to that.

**Comment by PaulL1** [comment]
Is this ng-grid or ui-grid?  I think ng-grid has such an event.  ui-grid does not, and the usual approach is to load your data, and if you want to wait for it to be rendered, to do $timeout(0).

**Comment by sunil123-github** [comment]
I am still using 2.x. Could you please show me some sample

**Comment by c0bra** [comment]
That event probably doesn't exist in 2.x

**Comment by PaulL1** [comment]
Response provided that should resolve issue, no reply for a month, assuming raiser has resolved.  Closing.

**Comment by Krolock1** [comment]
I have a similar problem. I have to restore the sort order after the new ui-router state is loaded.
After serveral tries I put mit restore logic in the callback onRegisterApi.

onRegisterApi: function (gridApi) {
            console.error("registerApi");

}

**Comment by bhantol** [comment]
scrollToFocus worked in the current version

http://plnkr.co/edit/sxeoeNbmAf09op5P2eJU?p=preview

**Comment by sirigariabhishek** [comment]
add this ng-if="gridOptions.data && gridOptions.data.length>0"
