### ISSUE TITLE
Refreshing data after api call with notifyDataChange("all") 

### ISSUE THREAD

**Issue by equilerex** [angular-ui/ng-grid#3358]
Hi,   
i am trying to replace "data" in the ui-grid with user initated api calls... the data changes fine but im unable to rebuild / refresh the table, as i understand notifyDataChange("all") should do the trick but no luck... either im doing something wrong or i am looking in the wrong place... spent half a day trying to find an answer in the tutorials and api page but no luck so maybe someone can help me out?

heres a simplified example of the issue:
http://plnkr.co/edit/56EdrUR5YYONn7p2f2oX?p=preview

**Comment by PaulL1** [comment]
The grid derives the columnDefs when it gets data if there aren't any.  But once there are some, it never re-derives them.  You need to modify your code to also append additional columnDefs (or, better still, to explicitly set the columnDefs from the start).

**Comment by equilerex** [comment]
so theres no way to re-derive the whole table? defining the column def's in advance is not an option since the data is very dynamic so i completely replace it since in many cases, the selected columns/rows are completely different. 

so far, the only solution ive come across is is wrapping the table in <script type="text/ng-template" id="table.html"> and then toggling it with ng-if"show" which seems to destroy the table and rebuild it but that is really hacky and not really the angular way of doing things....

**Comment by PaulL1** [comment]
You can re-derive the whole table by using an ng-if to destroy/create it, or removing and re-adding the element.

But you shouldn't need to do that.  You just need to set columnDefs when you set the data.  The columnDefs are derivable from your data if you wanted to - you just need to set a columnDef with a name = to the attribute name for each field in your data entity.

**Comment by equilerex** [comment]
Fair enough, not as simple as gridApi.rebuild() but  i can manually define the columns on every load by iterating through the first row (ive managed to avoid dom manipulation ever since i started working with angular so i'l avoid that route here as well)

however, the header columns and content columns end up having different widths after i do that a few times... looks like this:
![header width](https://cloud.githubusercontent.com/assets/5556216/7344869/fe5ad4e8-eccf-11e4-91e4-952033a72524.jpg)

can also be re-produced here: http://plnkr.co/edit/jSi80f?p=preview
do i need to pass in some specific parameters to table options/columnDefs to avoid that?

**Comment by PaulL1** [comment]
Closing, raiser has found other alternatives.
