### ISSUE TITLE
cellFilter cannot be changed dynamically

### ISSUE THREAD

**Issue by AgDude** [angular-ui/ng-grid#3359]
When I change the cellFilter in the columnDef, then call ```gridApi.core.notifyDataChange(uiGridConstants.dataChange.ALL)``` the grid does not update to reflect the new cellFilter. In this case I am I changing the second arg the ```date``` filter.

Here is a plunk: http://plnkr.co/edit/EqTSgR?p=preview

**Comment by PaulL1** [comment]
Changing the filter in the columnDef doesn't get reflected in the columns other than on initialisation - otherwise every time we refreshed the grid we'd overwrite the user's filter options.  You need to change column.filters[0] directly if you want to programatically change filters.

**Comment by AgDude** [comment]
@PaulL1, thanks for the response. I apologize for no being more clear. I am talking about the ```cellFilter```, as in the Angular "filter" used for formatting. I think your response is referring to the ```filter``` property as in rowSearcher. I suspect this problem has to do with how the row templates are cached.

**Comment by c0bra** [comment]
@AgDude the cellFilter is joined in with the cell template when the cell template is fetched/used. It doesn't get updated live.

You could write your own custom filter that uses a user-input variable plus the $filter service to do what you're wanting, I think.

**Comment by AgDude** [comment]
@c0bra, thanks for the suggestion. Using a filter arg from the scope worked great. I am closing this ticket.

Here is how I accomplished this, for anyone who comes across this in the future.

```
colDef.cellFilter = 'date:col.filterFormat'

uiGridApi.core.registerColumnsProcessor(function(columns, rows){
  angular.forEach(columns, function(col){
    var filterFormat = col.colDef.filterFormat; 
    if ( filterFormat ){ col.filterFormat = filterFormat; }
});
return rows;
}, 40);
```

You can then dynamically change the filterFormat property on any column.

**Comment by spaghettiguru** [comment]
Thanks for the solution guys, I've been debugging ui-grid for 2 days until I found out that the problem is that cell filter is constructed during the cell template compilation phase and therefore is not updated until the cell gets rerendered by ng-repeat.

@AgDude , your solution can be simplified: filter parameter can be taken directly from colDef object, like this: colDef.cellFilter = 'date:col.colDef.filterFormat' so there is no need for registering column processor. At least it worked for me :)

**Comment by mcrib96** [comment]
Another way around this is to setup the cellTemplate within the columnDefs:
$scope.myFilter = "currency:$:0"
...
cellTemplate: "<div class='ui-grid-cell-contents'>{{COL_FIELD |grid.appScope.myFilter}}</div>"
...

Then, if you change $scope.myFilter to be something else, the change is automatically reflected in the cellTemplate.
