### ISSUE TITLE
Canvas getting NaN on width

### ISSUE THREAD

**Issue by bradrice** [angular-ui/ng-grid#3364]
I'm getting this on my grid with the newest update:

.grid1429899594830 .ui-grid-render-container-body .ui-grid-canvas {
  width: NaNpx;
  height: 529860px;
}

I want my grid to be 100% width of the container it is in.

**Comment by c0bra** [comment]
@bradrice Can you reproduce it in a plunker?

**Comment by PaulL1** [comment]
Request for information, no reply for a month, assuming raiser has resolved through other means.  Closing.
