### ISSUE TITLE
resize columns behavior changed between RC18 and RC20. rendering issue

### ISSUE THREAD

**Issue by streamnsight** [angular-ui/ng-grid#3366]
My use case:
- display a # of columns. Update the columnDef to add/remove columns programatically. using ResizeColumns feature.

on RC18, I could resize a column and the grid would EXPAND so that it may be necessary to scroll horizontally. However using "*" column width on init usually lead to very small columns on init 
So I was trying to use fixed width to start but had rendering issues with the footer that didn't render the totals.

Switching to RC20, the footer worked, but everything else gets worse: adding / removing a column in the columnDef causes the table to render headers and columns completely differently, and the table seems to render with 'auto' width, causing empty cells to be squeezed to almost nothing.
I reverted to RC18 and used "*" but set minWidth to work around my problem...
Still no footer on RC18 though.

**Comment by PaulL1** [comment]
The behaviour you should see with columns is that we respect minWidth, maxWidth, width and *.  

If you set minWidth or maxWidth, we won't violate those. 

If you set width, you get exactly that value.

If you set width to * then we will attempt to fill the available space within the constraints of minWidth, maxWidth and leaving any columns with a fixed width fixed.

I think your problem is probably resolved if you were to set widths on those columns you want fixed, and set a minWidth on columns that you do not want to get too small.  

Could you advise whether this resolves your issue?  I'd also suggest rc21, I think we had some defects in rc20 with header height.

**Comment by streamnsight** [comment]
I did check RC21 recently and had the same problem: The bhavior you describe indeed works as you say (set * and minWidth and it tries to fit all with a minimum minWidth)HOWEVER, what I see is that if the columns expand beyond the size of the table, and even though horizontal scroll setup, the columns get all messed up (as if there was no minWidth)the columns also don't match the header size (the header seems rendered properly, but the columns are not)
If i scroll DOWN far enough, the columns get rendered 'better' in the sense that indeed they fit the minWidth or more... but they do not match the Header width, so the columns are miss-aligned.
I do not see this problem on RC18, and reverted to it.In RC 18 however the FOOTER does not work, which is why I originally had tried to upgrade to RC20/21.
Cheers

Date: Fri, 15 May 2015 16:51:15 -0700

**Comment by PaulL1** [comment]
Is there one of the tutorials that this happens on, or could you provide a plunker?  I haven't seen it do that, but since I did the changes on the column width logic no doubt it's my fault it's busted.  If I have a recreate then I can probably debug it.

**Comment by streamnsight** [comment]
will try to get you an example ASAP... right now it's pretty deeply integrated with much logic for filtering and selecting columns etc... so I need to extract it and plug in sample data.

Date: Fri, 15 May 2015 17:19:01 -0700

**Comment by tmarkley** [comment]
I ran into this issue as well with rc21: http://plnkr.co/edit/Qbi0qQMwj1F7DzN4rIqi?p=preview

However, it seems like the issue was resolved in the unstable release: http://plnkr.co/edit/93vSt01C8GKan2Tt91Di?p=preview

**Comment by streamnsight** [comment]
I upgraded to the latest unstable version and it does seem to work fine now.

**Comment by PaulL1** [comment]
OK, closing then.  Thanks,
