### ISSUE TITLE
Cascade dropdowns not working

### ISSUE THREAD

**Issue by ComeOutToPlay** [angular-ui/ng-grid#3367]
Hello,

The example at http://ui-grid.info/docs/#/tutorial/315_editable_cascading_dropdown did'nt work for me, so I tried to build an example to include in my grid a cascade dropdown at filter.

Basically, I defined two columns gender and clothe

      { field: 'gender', width:'20%', filter: { 
          type: uiGridConstants.filter.SELECT, 
          selectOptions: [ { value: '1', label: 'male' }, { value: '2', label: 'female' } ]
        }, 
        cellFilter: 'mapGender' },                               
      { field: 'clothe', width:'20%', filter: { 
          type: uiGridConstants.filter.SELECT, 
          selectOptions: getSelectedOptions()
        }, 
        cellFilter: 'mapClothe' },  

I have a clothe dropdown including: "dress" and "pants".
And I tried to use clothe as a dependent dropdown from gender, for example, if female is selected, I want "dress" to appear in the dependent dropdown.

In a previous version this worked for me, but with current version, calling getSelectedOptions() is called once, so I don't know what I'm doing wrong.

Here is my Plunkr http://plnkr.co/edit/ALGgjBQ1Kkft2ljuLeX2?p=preview

Best regards,

Fernando

**Comment by c0bra** [comment]
@ComeOutToPlay 

1. You need to bind to the filterChanged even so you can set your filter options. The example you looked at is for editing row values, not for chaining filter drop-downs.
2. You need to make sure that you set your `selectOptions` value by directly assigning to it. Angular won't notice you've changed the value if you just re-reference the property. You'd need to alter the existing variable by splicing the array up or something, but I find direct assignment easier.

Here's an updated plunker: http://plnkr.co/edit/ReRl4Ej5vGoSqAl2HWeL?p=preview

**Comment by ComeOutToPlay** [comment]
Thank you!!! It worked!!! 

I appreciate your collaboration!
