### ISSUE TITLE
RC 21

### ISSUE THREAD

**Issue by stoykostanchev** [angular-ui/ng-grid#3372]
Hi.
The latest RC to the date of writing this is v3.0.0-rc.20 - 2015-02-24. It's been more than a month and a lot of things have been improved ( I am interested in the cell tooltips for example ). Any chance of a new RC ( are those done regularly or after certain problems have been solved )? billyaraujo asked the same question a while ago ( currently - that's the last comment ) in https://github.com/angular-ui/ng-grid/issues/727.

**Comment by c0bra** [comment]
Absolutely, it's overdue. I've just pushed the release to Travis. It should go out shortly.

**Comment by stoykostanchev** [comment]
Good stuff :) Thank you all, your work is much appreciated.
