### ISSUE TITLE
encountered several issues with ui-grid rc20

### ISSUE THREAD

**Issue by rroy2** [angular-ui/ng-grid#3373]
I created a grid contains an editable dropdown and another column that contains a checkbox. I use ui-grid-pagination ui-grid-cellNav ui-grid-pinning ui-grid-edit. I also set enableCellEditOnFocus: true.

Issue 1: after tabbing into the dropdown column, the dropdown appears and has focus. The problem is that I can't tab out. I have to hit escape to close the dropdown first. Shift+tab does work however.

Issue 2: I use cellTemplate in order to display a checkbox instead of the words "true" or "false". The problem with using a cellTemplate is that when tabbing into (or clicking) the cell in that  column, the checkbox gets focus but the cell does not change it's background color. I just used a cellTemplate I found in a lot of places on the internet and that is:  cellTemplate: '<input type="checkbox" ng-model="row.entity.isretired"/>'
Do I need to do something different for the cellTemplate to get cell highlighting to work?

**Comment by rroy2** [comment]
Never mind about issue 1. The problem was caused by this code
        onRegisterApi: function(gridApi) {
            $scope.gridApi = gridApi;
            gridApi.edit.on.afterCellEdit($scope, function(rowEntity, colDef, newValue, oldValue) {
               $scope.lastCellEdited = 'edited row id:' + rowEntity.id + ' Column:' + colDef.name + ' newValue:' + newValue + ' oldValue:' + oldValue ;
                $scope.$apply();
            });

**Comment by rroy2** [comment]
Issue 2 has been resolved in RC21 but a new issue has arose.
When navigating into a checkbox cell, the cell background hightlights but pressing spacebar no longer checks/unchecks the checkbox.

Another issue I've seen is that for a dropdown, changes made with the keyboard does not take effect. Tabbing out of the cell reverts any changes made.

**Comment by PaulL1** [comment]
@swalters: assigning to you to have an opinion on.  I think this is really telling us that we've still got gremlins in edit, which I think we know, setting this to hi-pri so that we don't lose that.

**Comment by swalters** [comment]
dropdown tab fixed with https://github.com/angular-ui/ng-grid/commit/2edc4d66193b37734733b2a8a1999921426424b2
