### ISSUE TITLE
$rootScope:infdig Infinite $digest Loop with angular 1.2.0

### ISSUE THREAD

**Issue by medigvijay** [angular-ui/ng-grid#3390]
I am getting this error with the angular 1.2.0 varsion but with the latest 1.2.26 it works fine.

http://errors.angularjs.org/undefined/$rootScope/infdig?p0=10&p1=%5B%5B%22fn%3A%20function%20()%7Bvar%20a%3Dg(d)%3Ba!%3D%3DK%5Bb%5D%26%26(a!%3D%3Dh%3Fh%3DK%5Bb%5D%3Da%3Ak(d%2Ca%3Dh%3DK%5Bb%5D))%3Breturn%20a%7D%3B%20newVal%3A%20%7B%5C%22data%5C%22%3A%5B%7B%5C%22firstName%5C%22%3A%5C%22Cox%5C%22%2C%5C%22lastName%5C%22%3A%5C%22Carney%5C%22%2C%5C%22company%5C%22%3A%5C%22Enormo%5C%22%2C%5C%22employed%5C%22%3Atrue%7D%2C%7B%5C%22firstName%5C%22%3A%5C%22Lorraine%5C%22%2C%5C%22lastName%5C%22%3A%5C%22Wise%5C%22%2C%5C%22company%5C%22%3A%5C%22Comveyer%5C%22%2C%5C%22employed%5C%22%3Afalse%7D%2C%7B%5C%22firstName%5C%22%3A%5C%22Nancy%5C%22%2C%5C%22lastName%5C%22%3A%5C%22Waters%5C%22%2C%5C%22company%5C%22%3A%5C%22Fuelton%5C%22%2C%5C%22employed%5C%22%3Afalse%7D%5D%7D%3B%20oldVal%3A%20%7B%5C%22data%5C%22%3A%5B%7B%5C%22firstName%5C%22%3A%5C%22Cox%5C%22%2C%5C%22lastName%5C%22%3A%5C%22Carney%5C%22%2C%5C%22company%5C%22%3A%5C%22Enormo%5C%22%2C%5C%22employed%5C%22%3Atrue%7D%2C%7B%5C%22firstName%5C%22%3A%5C%22Lorraine%5C%22%2C%5C%22lastName%5C%22%3A%5C%22Wise%5C%22%2C%5C%22company%5C%22%3A%5C%22Comveyer%5C%22%2C%5C%22employed%5C%22%3Afalse%7D%2C%7B%5C%22firstName%5C%22%3A%5C%22Nancy%5C%22%2C%5C%22lastName%5C%22%3A%5C%22Waters%5C%22%2C%5C%22company%5C%22%3A%5C%22Fuelton%5C%22%2C%5C%22employed%5C%22%3Afalse%7D%5D%7D%22%5D%2C%5B%22fn%3A%20function%20()%7Bvar%20a%3Dg(d)%3Ba!%3D%3DK%5Bb%5D%26%26(a!%3D%3Dh%3Fh%3DK%5Bb%5D%3Da%3Ak(d%2Ca%3Dh%3DK%5Bb%5D))%3Breturn%20a%7D%3B%20newVal%3A%20%7B%5C%22data%5C%22%3A%5B%7B%5C%22firstName%5C%22%3A%5C%22Cox%5C%22%2C%5C%22lastName%5C%22%3A%5C%22Carney%5C%22%2C%5C%22company%5C%22%3A%5C%22Enormo%5C%22%2C%5C%22employed%5C%22%3Atrue%7D%2C%7B%5C%22firstName%5C%22%3A%5C%22Lorraine%5C%22%2C%5C%22lastName%5C%22%3A%5C%22Wise%5C%22%2C%5C%22company%5C%22%3A%5C%22Comveyer%5C%22%2C%5C%22employed%5C%22%3Afalse%7D%2C%7B%5C%22firstName%5C%22%3A%5C%22Nancy%5C%22%2C%5C%22lastName%5C%22%3A%5C%22Waters%5C%22%2C%5C%22company%5C%22%3A%5C%22Fuelton%5C%22%2C%5C%22employed%5C%22%3Afalse%7D%5D%7D%3B%20oldVal%3A%20%7B%5C%22data%5C%22%3A%5B%7B%5C%22firstName%5C%22%3A%5C%22Cox%5C%22%2C%5C%22lastName%5C%22%3A%5C%22Carney%5C%22%2C%5C%22company%5C%22%3A%5C%22Enormo%5C%22%2C%5C%22employed%5C%22%3Atrue%7D%2C%7B%5C%22firstName%5C%22%3A%5C%22Lorraine%5C%22%2C%5C%22lastName%5C%22%3A%5C%22Wise%5C%22%2C%5C%22company%5C%22%3A%5C%22Comveyer%5C%22%2C%5C%22employed%5C%22%3Afalse%7D%2C%7B%5C%22firstName%5C%22%3A%5C%22Nancy%5C%22%2C%5C%22lastName%5C%22%3A%5C%22Waters%5C%22%2C%5C%22company%5C%22%3A%5C%22Fuelton%5C%22%2C%5C%22employed%5C%22%3Afalse%7D%5D%7D%22%5D%2C%5B%22fn%3A%20function%20()%7Bvar%20a%3Dg(d)%3Ba!%3D%3DK%5Bb%5D%26%26(a!%3D%3Dh%3Fh%3DK%5Bb%5D%3Da%3Ak(d%2Ca%3Dh%3DK%5Bb%5D))%3Breturn%20a%7D%3B%20newVal%3A%20%7B%5C%22data%5C%22%3A%5B%7B%5C%22firstName%5C%22%3A%5C%22Cox%5C%22%2C%5C%22lastName%5C%22%3A%5C%22Carney%5C%22%2C%5C%22company%5C%22%3A%5C%22Enormo%5C%22%2C%5C%22employed%5C%22%3Atrue%7D%2C%7B%5C%22firstName%5C%22%3A%5C%22Lorraine%5C%22%2C%5C%22lastName%5C%22%3A%5C%22Wise%5C%22%2C%5C%22company%5C%22%3A%5C%22Comveyer%5C%22%2C%5C%22employed%5C%22%3Afalse%7D%2C%7B%5C%22firstName%5C%22%3A%5C%22Nancy%5C%22%2C%5C%22lastName%5C%22%3A%5C%22Waters%5C%22%2C%5C%22company%5C%22%3A%5C%22Fuelton%5C%22%2C%5C%22employed%5C%22%3Afalse%7D%5D%7D%3B%20oldVal%3A%20%7B%5C%22data%5C%22%3A%5B%7B%5C%22firstName%5C%22%3A%5C%22Cox%5C%22%2C%5C%22lastName%5C%22%3A%5C%22Carney%5C%22%2C%5C%22company%5C%22%3A%5C%22Enormo%5C%22%2C%5C%22employed%5C%22%3Atrue%7D%2C%7B%5C%22firstName%5C%22%3A%5C%22Lorraine%5C%22%2C%5C%22lastName%5C%22%3A%5C%22Wise%5C%22%2C%5C%22company%5C%22%3A%5C%22Comveyer%5C%22%2C%5C%22employed%5C%22%3Afalse%7D%2C%7B%5C%22firstName%5C%22%3A%5C%22Nancy%5C%22%2C%5C%22lastName%5C%22%3A%5C%22Waters%5C%22%2C%5C%22company%5C%22%3A%5C%22Fuelton%5C%22%2C%5C%22employed%5C%22%3Afalse%7D%5D%7D%22%5D%2C%5B%22fn%3A%20function%20()%7Bvar%20a%3Dg(d)%3Ba!%3D%3DK%5Bb%5D%26%26(a!%3D%3Dh%3Fh%3DK%5Bb%5D%3Da%3Ak(d%2Ca%3Dh%3DK%5Bb%5D))%3Breturn%20a%7D%3B%20newVal%3A%20%7B%5C%22data%5C%22%3A%5B%7B%5C%22firstName%5C%22%3A%5C%22Cox%5C%22%2C%5C%22lastName%5C%22%3A%5C%22Carney%5C%22%2C%5C%22company%5C%22%3A%5C%22Enormo%5C%22%2C%5C%22employed%5C%22%3Atrue%7D%2C%7B%5C%22firstName%5C%22%3A%5C%22Lorraine%5C%22%2C%5C%22lastName%5C%22%3A%5C%22Wise%5C%22%2C%5C%22company%5C%22%3A%5C%22Comveyer%5C%22%2C%5C%22employed%5C%22%3Afalse%7D%2C%7B%5C%22firstName%5C%22%3A%5C%22Nancy%5C%22%2C%5C%22lastName%5C%22%3A%5C%22Waters%5C%22%2C%5C%22company%5C%22%3A%5C%22Fuelton%5C%22%2C%5C%22employed%5C%22%3Afalse%7D%5D%7D%3B%20oldVal%3A%20%7B%5C%22data%5C%22%3A%5B%7B%5C%22firstName%5C%22%3A%5C%22Cox%5C%22%2C%5C%22lastName%5C%22%3A%5C%22Carney%5C%22%2C%5C%22company%5C%22%3A%5C%22Enormo%5C%22%2C%5C%22employed%5C%22%3Atrue%7D%2C%7B%5C%22firstName%5C%22%3A%5C%22Lorraine%5C%22%2C%5C%22lastName%5C%22%3A%5C%22Wise%5C%22%2C%5C%22company%5C%22%3A%5C%22Comveyer%5C%22%2C%5C%22employed%5C%22%3Afalse%7D%2C%7B%5C%22firstName%5C%22%3A%5C%22Nancy%5C%22%2C%5C%22lastName%5C%22%3A%5C%22Waters%5C%22%2C%5C%22company%5C%22%3A%5C%22Fuelton%5C%22%2C%5C%22employed%5C%22%3Afalse%7D%5D%7D%22%5D%2C%5B%22fn%3A%20function%20()%7Bvar%20a%3Dg(d)%3Ba!%3D%3DK%5Bb%5D%26%26(a!%3D%3Dh%3Fh%3DK%5Bb%5D%3Da%3Ak(d%2Ca%3Dh%3DK%5Bb%5D))%3Breturn%20a%7D%3B%20newVal%3A%20%7B%5C%22data%5C%22%3A%5B%7B%5C%22firstName%5C%22%3A%5C%22Cox%5C%22%2C%5C%22lastName%5C%22%3A%5C%22Carney%5C%22%2C%5C%22company%5C%22%3A%5C%22Enormo%5C%22%2C%5C%22employed%5C%22%3Atrue%7D%2C%7B%5C%22firstName%5C%22%3A%5C%22Lorraine%5C%22%2C%5C%22lastName%5C%22%3A%5C%22Wise%5C%22%2C%5C%22company%5C%22%3A%5C%22Comveyer%5C%22%2C%5C%22employed%5C%22%3Afalse%7D%2C%7B%5C%22firstName%5C%22%3A%5C%22Nancy%5C%22%2C%5C%22lastName%5C%22%3A%5C%22Waters%5C%22%2C%5C%22company%5C%22%3A%5C%22Fuelton%5C%22%2C%5C%22employed%5C%22%3Afalse%7D%5D%7D%3B%20oldVal%3A%20%7B%5C%22data%5C%22%3A%5B%7B%5C%22firstName%5C%22%3A%5C%22Cox%5C%22%2C%5C%22lastName%5C%22%3A%5C%22Carney%5C%22%2C%5C%22company%5C%22%3A%5C%22Enormo%5C%22%2C%5C%22employed%5C%22%3Atrue%7D%2C%7B%5C%22firstName%5C%22%3A%5C%22Lorraine%5C%22%2C%5C%22lastName%5C%22%3A%5C%22Wise%5C%22%2C%5C%22company%5C%22%3A%5C%22Comveyer%5C%22%2C%5C%22employed%5C%22%3Afalse%7D%2C%7B%5C%22firstName%5C%22%3A%5C%22Nancy%5C%22%2C%5C%22lastName%5C%22%3A%5C%22Waters%5C%22%2C%5C%22company%5C%22%3A%5C%22Fuelton%5C%22%2C%5C%22employed%5C%22%3Afalse%7D%5D%7D%22%5D%5D

**Comment by PaulL1** [comment]
AngularJS 1.2.10 or better is supported: http://ui-grid.info/docs/#/tutorial/100_preReqs

**Comment by PaulL1** [comment]
Solution provided that may resolve it, no comment for 3 weeks, closing, please re-raise or reopen if this is still occurring.
