### ISSUE TITLE
Performance degrade on certain types of Large data

### ISSUE THREAD

**Issue by onkami** [angular-ui/ng-grid#3393]
Hello, I am doing my project and base my work on several examples from tutorial.

Take a look: http://plnkr.co/edit/fy0FJXzXaBwPVPB7lTgU

There is a small piece of code in the data download part, that does some operation to data, and after that if you try to cell-navigate table, it becomes super-slow.
     
         $http.get('https://cdn.rawgit.com/angular-ui/ui-grid.info/gh-pages/data/10000_complex.json')
      .success(function(data) {
        ///ATTN HERE. IF NEXT "for" is present, cell-navigating is very slow
        for (var i = 0; i < 6; i++) {
          data = data.concat(data);
        }
        $scope.gridOptions.data = data;
      });

If you discard the data alteration, everything is operating at normal speed.

**Comment by PaulL1** [comment]
What this is doing is replicating the data retrieved from the server 2^6 times (i.e. 64 times or thereabouts).  I think I changed this recently to handle it differently, but fundamentally if this is slow it is probably because of the volume of data, not because of these lines of code as such.

**Comment by PaulL1** [comment]
Solution provided that may resolve it, no comment for 3 weeks, closing, please re-raise or reopen if this is still occurring.
