### ISSUE TITLE
when ui.grid.moveColumn and ui.grid.selection are used together, column header is flying too fast until end, same issue for pinning

### ISSUE THREAD

**Issue by moguzalp** [angular-ui/ng-grid#3395]
When column move and row selection are used together, when I try to move column, column header starts to flying from left to right too fast:
http://plnkr.co/edit/iU6weT394sSMVHO03tYT?p=preview

the same for pinning: 
http://plnkr.co/edit/LtMNx3zkOEgAJ9Oq3SD4?p=preview

**Comment by moguzalp** [comment]
It seems issue is resolved with the "ui-grid - v3.0.0-rc.21-2ad8f7f - 2015-06-03" version. Thanks

**Comment by moguzalp** [comment]
I closed issue. It works ok for colums however it has still problem when horizontal scrolling and after scroll right while moving those columns.

**Comment by AgDude** [comment]
@moguzalp I am closing this issue as I think the original problem of "flying to the right" has been resolved. There is currently a bug with moving a column after scrolling to the right #3631, but I am not able to reproduce the "flying to right".  Please re-open or comment if I am incorrect.

**Comment by bvsbharat** [comment]
hi is this issue is fixed with ui-grid.js file or we need any manual coding
