### ISSUE TITLE
Moving filtering feature into sorting menu

### ISSUE THREAD

**Issue by Ginwu** [angular-ui/ng-grid#3396]
Hello,

Thanks for your work on this project, I'm glad to use it in my own! 
I don't know if it's the right place to ask you that but is it possible to move filtering feature into sorting menu instead of below the headers with some sort of options or maybe in a a future version? I don't know if it's what you want. Maybe I missed something in the tutorial to just do it. 
Thanks again, GG with UI Grid.

Ginwu

**Comment by c0bra** [comment]
As it is, you would have to customize the column menu template to add stuff in. The column menus are set up to basically be buttons that perform actions, and they don't allow generic html. That would be a good thing to allow, though!  If you're up for a PR that would be swell, otherwise I can file this as an enhancement.

**Comment by PaulL1** [comment]
There's a PR out there that allows the menus to take a template, it had a rebasing issue or something else, I can't remember what, but it was pretty close.

**Comment by Ginwu** [comment]
Thanks for your answers. I'm trying to combine the custom column menu and the custom filters, but I can't put html in a custom column menu, so I'm blocked.

**Comment by PaulL1** [comment]
Yes, this PR allows templates on menu items: #3049

**Comment by Ginwu** [comment]
Yes, I'm trying with the custom menu.
But I can't do somenthing like this, isn't it? 

{
     field: 'id',
     width: '60',
     displayName: 'ID',
     type: 'number',
     menuItems: [
                    {
                        title: 'Filter',
                        template: '<div class="ui-grid-filter-container" ng-repeat="colFilter in col.filters"><div custom-modal-int-filter></div></div>'
				    }
				]
                   }

So is it possible to add templates to custom menu, and maybe a submenu to add multiple filters for example to a column? Or some defaults filters to column menu for each column type, like contains, begin with,etc for a string column. What do you think about that?
Thanks for your help!

**Comment by PaulL1** [comment]
It's not currently possible to custom templates for menu items, that PR adds the capability but it hasn't been merged yet because it needs some tidyup.

Submenus have been discussed, I think @AgDude was looking at it.  There's no implementation of that as yet.

**Comment by Ginwu** [comment]
Ok, thank you for your response. I'm waiting for that then.
