### ISSUE TITLE
Reset Row edit feature module when data set changed 

### ISSUE THREAD

**Issue by ncourtial** [angular-ui/ng-grid#3401]
Hi,
I'm using row edit feature in order to save manually all my dirty rows.
I want to cancel my local changes by resetting data set with initial values.
Here is my plunkr http://plnkr.co/edit/4dVrlsYPeq1QUF7PQ26M (plunk updated)
When I try the following scenario in my plunkr, I get an error (cf: console):
- Changing a value in a row.
- Clicking on reset button. (I want to reset to initial state before previous change)
- Re-changing a value in a row.
- Clicking on Save Button.
=> Two save events are fired which causes an error. It shouls only fire one event with my last change.
Like if it was keeping in dirty row cache my first change whereas I reset my data set and I would like to reset dirty row cache too.

Any idea about the problem.

Many thanks for your help.

Cheers,
Nathan

**Comment by ncourtial** [comment]
Sorry my plunk was bugged.
I has just corrected it.

**Comment by PaulL1** [comment]
Your init function replaces the data, but it doesn't clear or flush the dirty rows cache.  Unfortunately I haven't provided any way to do that.  I have added a new method `setRowsClean` that is similar to setRowsDirty, but in the reverse direction.  To use this you would:

```
  var gridRows = $scope.gridApi.rowEdit.getDirtyRows();
  var dataRows = gridRows.map( function( gridRow ) { return gridRow.entity; });
  $scope.gridApi.rowEdit.setRowsClean( dataRows );
```

http://ui-grid.info/docs/#/api/ui.grid.rowEdit.api:PublicApi will be updated once the merge comes through (a few hours probably).
