### ISSUE TITLE
exporterAllDataPromise doesn't accept a promise

### ISSUE THREAD

**Issue by AgDude** [angular-ui/ng-grid#3403]
It seems that this option is expecting a function which returns a promise. It should either be renamed to something link "exportAllDataFn", or be changed actually accept a promise object.

**Comment by PaulL1** [comment]
Yeah, it came in a pull request, it originally had some funny flags and polling going on so I asked for it to be changed to a promise.  The guy who did it wasn't 100% good with promises.  Renaming to exporterAllDataFunction and deprecating the old name (but allowing it to still be used).
