### ISSUE TITLE
rowSelectionChanged should trigger on batch also

### ISSUE THREAD

**Issue by AgDude** [angular-ui/ng-grid#3404]
Currently when the check in the header is clicked, only the ```rowSelectionChangedBatch``` event is triggered. intuitively it seems that using rowSelectionChanged, I should be able to capture any time a row is selected.  Would it be too much of a performance hit to trigger both events?

**Comment by PaulL1** [comment]
I think there's an option to turn off the batch event.

**Comment by AgDude** [comment]
Thanks @PaulL1. I read the docs too quickly.
