### ISSUE TITLE
ui-grid Grouping is broken

### ISSUE THREAD

**Issue by deepfriedbrain** [angular-ui/ng-grid#3409]
In the tutorial example for Grouping for ui-grid, I noticed that the grouping is broken. The +/- signs are placed one row above their correct position after expansion. See the 2 screenshots of original un-expanded state and expanded state.

![image](https://cloud.githubusercontent.com/assets/1531669/7444159/98005872-f1ab-11e4-8277-f8ec7f6d381c.png)

![image](https://cloud.githubusercontent.com/assets/1531669/7444161/a4dabd94-f1ab-11e4-8d47-4c75edc42766.png)

**Comment by AgDude** [comment]
This is the same problem described in #3394. Thanks for the details, on when it occurred.

**Comment by PaulL1** [comment]
Closing as duplicate.

**Comment by springzen** [comment]
Build used: ui-grid - v3.1.1 - 2016-02-09
I know this is now closed, but I am not sure if this is the same issue or a new one. When I group, I am seeing the same issue as described originally. In my case this is related to my css. I was trying to add word wrap and I took the tip from https://github.com/angular-ui/ui-grid/issues/317.
```
.ui-grid-viewport .ui-grid-cell-contents {
    word-wrap: break-word;
    white-space: normal !important;
}

.ui-grid-row, .ui-grid-cell {
    height: auto !important;
}

.ui-grid-row div[role=row] {
    display: flex;
    align-content: stretch;
}
```

If I use this css, only the headers wrap.
```
.ui-grid-header-cell .ui-grid-cell-contents {
    /*height: 48px;*/
    white-space: normal;
    -ms-text-overflow: clip;
    -o-text-overflow: clip;
    text-overflow: clip;
    overflow: visible;
    word-wrap: break-word;
}
```

![image](https://cloud.githubusercontent.com/assets/2808006/13235795/cae574e6-d974-11e5-8430-4fc15f6ff410.png)
