### ISSUE TITLE
IE 9  :  the grid is empty after a reload of gridOptions.data

### ISSUE THREAD

**Issue by aprieux** [angular-ui/ng-grid#3411]
Hello, 

Only under IE9, there is a bug that doesn't show the rows after refreshing the gridOptions.data

Here the fiddle  :  http://jsfiddle.net/bar247uk/4/

Steps to follow : 

Scroll to the bottom of the grid and then click on the button above the grid to reload data.
The elements are not visible, you have to move a bit the scrollbar and the rows appears.

This bug is present on the NG-Grid also.

If you could give me a quick fix waiting a fix in a next release, i will really appreciate it.

Thanks

**Comment by redlie** [comment]
Here a quick fix on RC19:
line 5072
container.adjustRows(null, container.prevScrolltopPercentage, true);
container.adjustColumns(null, container.prevScrollleftPercentage);
container.grid.element.find('.ui-grid-viewport').scroll(); // the fix

**Comment by aprieux** [comment]
Here a quick fix on RC19:
line 5072
container.adjustRows(null, container.prevScrolltopPercentage, true);
container.adjustColumns(null, container.prevScrollleftPercentage);
container.grid.element.find('.ui-grid-viewport').scroll(); // the fix

**Comment by PaulL1** [comment]
I wonder whether it's in the way you're defining your data.  I see a lot of people having problems when they replace the array in the way you're doing, as the grid is actually watching the array reference if you define in that way.

If you change the logic as attached: http://jsfiddle.net/5oseu2ys/ I think you may get a better result (I don't have IE to test on).

**Comment by PaulL1** [comment]
Solution provided that may resolve it, no comment for 3 weeks, closing, please re-raise or reopen if this is still occurring.
