### ISSUE TITLE
IE9: Selection column missing in RC21

### ISSUE THREAD

**Issue by melcor76** [angular-ui/ng-grid#3412]
I updated to RC21 and the Selection column is all white in IE9.
I was also able to emulate this with Dev-tools in IE11.

**Comment by c0bra** [comment]
This is because the selection columns are ending up at the top of the page:

![selection_row_weirdness](https://cloud.githubusercontent.com/assets/105007/7455714/25d98d38-f244-11e4-982e-1cc6ee3d52ff.png)

Probably due to us using incorrect absolute positioning.

**Comment by leekeal** [comment]
I have encountered this problem. How to fix it?

**Comment by anandvihar** [comment]
I am also having the same problem. How should it be fixed

**Comment by anandvihar** [comment]
IF i remove position absolute, then the border are not applied properly
![image](https://cloud.githubusercontent.com/assets/8238112/7747463/47aaf57c-ffd8-11e4-991a-3bb54ce293e8.png)

**Comment by anandvihar** [comment]
Can someone help me on this?
