### ISSUE TITLE
enableCellEditOnFocus vs enableCellEdit

### ISSUE THREAD

**Issue by OneMHz** [angular-ui/ng-grid#3415]
I have a grid that I want only one column to be editable.  If I just use enableCellEdit in the column defs, then I have to double click to start editing.  If I use enableCellEditOnFocus in the grid options, then I can single click, but have to manually disable editing on all of the other columns.

Is this intended?  Is there a workaround to make it so that enableCellEdit works like enableCellEditOnFocus?

**Comment by c0bra** [comment]
Sounds like a conflict in editing configuration defaults. I don't think there's a workaround but this would be an easy (if breaking) change.

**Comment by PaulL1** [comment]
If you include the edit feature, then implicitly you're defaulting `enableEdit: true`.  If you do nothing else then I believe that all your columns become editable.  Refer this plunker: http://plnkr.co/edit/FNoCJcTEGBx21ZlOBtGf?p=preview

If you set `editableOnFocus` at the gridOptions level, this remains the case, but by default they're now `editableOnFocus`.  

If you want just one column to be editable, then I think you need to set all the other columns `enableCellEdit: false`.

**Comment by PaulL1** [comment]
Solution provided that may resolve it, no comment for 3 weeks, closing, please re-raise or reopen if this is still occurring.
