### ISSUE TITLE
Nested UI Grid 

### ISSUE THREAD

**Issue by vinit2209** [angular-ui/ng-grid#3419]
I want to make nested UI grid but I am unable to make it using UI grid ,but It seems it is possible using ng-grid as mentioned in below question
http://stackoverflow.com/questions/27656340/nested-ui-grid-grid-inside-celltemplate.

by the way ,I want same thing as below link using ng-table ,but i want to make it using ui-grid

https://github.com/esvit/ng-table/blob/master/examples/demo30.html

Please help me

**Comment by PaulL1** [comment]
You would need to put another ui-grid into the cellTemplate for a specific column.  I would imagine the usability of doing that would be somewhat poor, in general I wouldn't recommend it.

**Comment by PaulL1** [comment]
Solution provided that may resolve it, no comment for 3 weeks, closing, please re-raise or reopen if this is still occurring.
