### ISSUE TITLE
Remove Sort - passes gridColumn instead of grid to sortChanged event

### ISSUE THREAD

**Issue by Zorkling** [angular-ui/ng-grid#3423]
When removing sort with External Sorting I noticed the sortChanged event through by using the column menu to remove a sort passes the current gridColumn instead of the grid.

It looks like this is cause by the following code in GridColumn.js line 725
```javascript
GridColumn.prototype.unsort = function () {
      this.sort = {};
      self.grid.api.core.raise.sortChanged( self, self.grid.getColumnSorting() );
    };
```

If i had to guess, it looks like it was copied from Grid.js line 1966, where self is the grid, however here self is the gridColumn.

It seems to be the code should read
```javascript
GridColumn.prototype.unsort = function () {
      this.sort = {};
      self.grid.api.core.raise.sortChanged( self.grid, self.grid.getColumnSorting() );
    };
```

Let me know if you'd like me to make a quick PR to fix

Thank for the excellent grid!

**Comment by PaulL1** [comment]
Ah. I just fixed today a bug that is no doubt caused by this (unsorting on a grouped grid, #3363.  Your suggestion probably would be a better way to fix that.  I'll apply it.

**Comment by Zorkling** [comment]
Awesome, thanks @PaulL1!
