### ISSUE TITLE
loaded children nodes for TreeView are in expanded state

### ISSUE THREAD

**Issue by funkydata** [angular-ui/ng-grid#3425]
http://ui-grid.info/docs/#/tutorial/215_treeView - The nodes under Guerrero Lopez, however, are loaded only when that row is expanded.

However, their state is set to uiGridTreeViewConstants.EXPANDED (minus sign) by default (I think after reading the source that they inherit the state from the parent nodes).

Since they are newly added rows shouldn't the state be uiGridTreeViewConstants.COLLAPSED instead?

**Comment by PaulL1** [comment]
I think you're right.  Modifying the code as you suggest, should come through soon.
