### ISSUE TITLE
ui-grid scrolls down to the latest row after clicking on any cell when  cell navigation feature is ON.

### ISSUE THREAD

**Issue by dimetrym** [angular-ui/ng-grid#3428]
This bug appears only on Internet Explorer(v.11) and Firefox(v.36), Platform is Window 7. 
Everything works fine on Chrome browser.
I'm trying to use CellNav feature. ui-grid scrolls down to the latest row after clicking on any cell.
To reproduce open link http://ui-grid.info/docs/#/tutorial/202_cellnav  in Internet Explorer.
Scroll to demo grid and just click on any cell . for example (0,0). See the picture below:
![image](https://cloud.githubusercontent.com/assets/7129551/7489885/137c92b0-f3e4-11e4-8df7-ee1938a634e0.png)

After that grid scrolls down to the latest row.See the picture below:
![image](https://cloud.githubusercontent.com/assets/7129551/7489890/1e51f1ee-f3e4-11e4-8f07-6c6720008d4b.png)

Thank you!

**Comment by swalters** [comment]
fixed in https://github.com/angular-ui/ng-grid/commit/aa56355469e0c2fe825f6c063bb2e2f7937817c7
