### ISSUE TITLE
Documentation for all possible events?

### ISSUE THREAD

**Issue by dereklin** [angular-ui/ng-grid#3438]
From I can tell, ui grid is heavily event driven.  I am upgrading from ng-grid to ui-grid.  In ng-grid, there is the afterSelectionChange event.  What is the equivalent of this and others in ui-grid?  Is there a documentation page listing all the possible events?

**Comment by PaulL1** [comment]
There is a set of API documentation: http://ui-grid.info/docs/#/api/ui.grid.core.api:PublicApi is a good place to start.  Each of the features has their own publicApi page, which should list all the events that feature supports.  You'd be looking for the selection api documentation: http://ui-grid.info/docs/#/api/ui.grid.selection.api:PublicApi

**Comment by PaulL1** [comment]
Solution provided that may resolve this issue, no comment for 3 weeks, closing, please re-raise or reopen if this is still occurring.
