### ISSUE TITLE
[BUG] height of grouping expand all and select all button

### ISSUE THREAD

**Issue by edenchen123** [angular-ui/ng-grid#3439]
The height of grouping expand all button changed after scrolling which cause expand button and it's row not in the same line. expand A open B....

see the official demo:
http://ui-grid.info/docs/#/tutorial/209_grouping

**Comment by mmautner** [comment]
Can you clarify what you're describing? Maybe with a screenshot?

I'm not experiencing what I understand you are describing. Is this occurring for you in multiple browsers?

**Comment by AgDude** [comment]
My guess it that this is another duplicate of #3394. If not, please provide some screenshots, as suggested earlier.

**Comment by edenchen123** [comment]
yes  it's duplicated of #3394 .

**Comment by mmautner** [comment]
then you should probably close this one then @edenchen123 :)
