### ISSUE TITLE
Data not shown properly when grid is resized

### ISSUE THREAD

**Issue by griessbreilp** [angular-ui/ng-grid#3441]
Hello everyone,
i encountered the problem, when the grid changes it's size (we generate our whole view through a json object, so this happens everytime), it doesn't shows the "new" visible entrys.

I created a little plunker:
http://plnkr.co/edit/01JK9r?p=preview

The case is, let the data load, press the button, so that the grid gets bigger and on the first time the table is half empty. After you scroll or resize the browser or something, the data is rendered properly.

After changing the size again, it works. (So you have to stop and start the plunker).

**Comment by PaulL1** [comment]
Try this: http://plnkr.co/edit/9wtuN5H5HwK1do72kGCV?p=preview

The grid doesn't really deal with dynamic size well, and it's something we continue to think about.  You could look at using the autoresize feature, which may give some options, but failing that usually some combination of intervals, handleWindowResize and queueRefresh will work.

**Comment by griessbreilp** [comment]
Sorry that it took so long to test your solution. 
Calling the queueGridRefresh-function actually solved my problem and the data is shown correctly. 
Thank you very much!

**Comment by PaulL1** [comment]
Excellent, closing then.
