### ISSUE TITLE
Aggregate columns footer not showing, unless ui-grid-tree-view attribute is specified, or loading in a callback

### ISSUE THREAD

**Issue by cyrilgandon** [angular-ui/ng-grid#3442]
Aggregate footer values are not robustly calculated:

Case working :
 - specify attribute ui-grid-tree-view : http://plnkr.co/edit/bRAj37pf8qJY4xyIeSmw
 - loading asynchronously :  http://plnkr.co/edit/0OLiB68R1srMrmae3EXU

Case not working :
 - Set data in constructor : http://plnkr.co/edit/B9uU0CNZxg8z6L2k5AhB
 - loading asynchronously after having set the data in constructor : http://plnkr.co/edit/jsjBtlKmBxKrW3yhFU1W

**Comment by PaulL1** [comment]
I think the problem with this is likely to be in the aggregation logic, and specifically in a debounce that exists in that logic.  You'll notice that if you sort a column the aggregations suddenly work, I think what's happening is the first aggregation isn't getting triggered.  I thought I did some work around this area a while back, and I may not have caught all the corner cases.
