### ISSUE TITLE
[Grouping] task: make a factory for generating header rows

### ISSUE THREAD

**Issue by AgDude** [angular-ui/ng-grid#3445]
Currently group header rows are generated in ```insertGroupHeader```, we use the GridRow factory, then set some defaults. It would be nicer to have a factory to set those defaults, and would also make testing a lot easier.

@PaulL1 would it be worth making this flexible enough to use for treeView also? The extent of my experience with treeView is a quick look at the tutorial page, but this seems like it could be a fairly generic ```GridHeaderRow``` factory.

**Comment by PaulL1** [comment]
Yes, this would make sense.  The main issue is that I didn't work out where I'd put common code like this - it's shared between treeView and grouping, but that doesn't mean it belongs in core.

**Comment by AgDude** [comment]
I was thinking a separate feature module, which would be services only. Maybe something like ```ui.grid.groupUtils```.

**Comment by PaulL1** [comment]
Yeah, I'd thought about that, but then people have to remember to include it.  Which they won't, so then we'll get constant bug reports.  I'd like something that automatically includes.  Perhaps each of treeView and grouping could include the module themselves?

**Comment by AgDude** [comment]
definitely.

**Comment by PaulL1** [comment]
Yeah, I have a feeling that it's harder than that.  :-)

**Comment by AgDude** [comment]
While we didn't actually create a factory for this, with the recent refactor of grouping this is only done in one place.
