### ISSUE TITLE
Column Header - Keeping the title/name of columns as uppercase

### ISSUE THREAD

**Issue by redapplewithleaves** [angular-ui/ng-grid#3447]
The column header is automatically formatted as title case. I need to keep all caps: 
http://plnkr.co/edit/5U9GAdj0KfQrv6GCESzG?p=preview

Is there a way to keep the title/name of the column all caps? There are some abbreviations that is preferably be all caps. 

Is there an option that I'm missing? Or is there a way to turn off this default feature?

**Comment by PaulL1** [comment]
Set the displayName property as well as the name.  Refer http://ui-grid.info/docs/#/api/ui.grid.class:GridOptions.columnDef

**Comment by redapplewithleaves** [comment]
Okay. Use displayName instead of name. Got it!

Thank you! I've been looking for this option.

**Comment by DaBlick** [comment]
Is there a way to do this once for ALL columns?   My columns are not a fixed set, but loaded dynamically

**Comment by SathishRamasamy83** [comment]
> Is there a way to do this once for ALL columns? My columns are not a fixed set, but loaded dynamically

If you apply below style to the component/screen in which you want to display the grid columns in capital letters, you would achieve what you wanted for grid data loaded dynamically.

Hope this helps :)

:host ::ng-deep .k-header {  
    text-transform: uppercase;
}
