### ISSUE TITLE
[Grouping] selecting grouped row should select children

### ISSUE THREAD

**Issue by AgDude** [angular-ui/ng-grid#3454]
When used in conjunction with selection, when the group header is selected it should select the children (if expanded). This should also be made consistent with treeView.

May this can be incorporated into #3445?

**Comment by AgDude** [comment]
Along with this, if a row within a group is selected, then the group is collapsed, that row should be unselected. Does this functionality belong in grouping, or selection? Should a selected row always become unselected if it becomes hidden?

**Comment by PaulL1** [comment]
I don't think it's necessarily true that hidden rows should always be selected.  I can imagine a use case where someone is selecting some items by navigating around a tree, and that they want those things to stay selected.  So if anything this would be switchable behaviour.

**Comment by AgDude** [comment]
@PaulL1, you make some good points. I was picturing a narrow use case.

Let's forget about selecting/unselecting rows, and just make sure there is an event that fires when the collapsed/expanded state changes (looks like this already exists on TreeView). We need a means to access the child rows in the callback. Selecting/unselecting will be the responsibility of the implementer.

I can think of three ways to implement access to the child rows:

1. A method on the ```headerGridRow``` class which returns an array of rows. 
2. A publicApi method something like ```getChildren(headerRow)``` which returns an array of rows.
3. Provide the array from from the event, like: ```gridApi.treeView.on.rowCollapsed(scope,function(row, childRows){})```

I am leaning towards 3, for simplicity. I am also going to propose a change to the events on ```treeView```. Instead of two events can they be combined into ```rowExpandedChanged```, similar to the ```rowSelectionChanged``` event?

**Comment by PaulL1** [comment]
I think I'd lean towards option 2, as that I think is a more general use case - it could be used for lots of things.  I can write that pretty quickly.

On the events, I originally split them out so that people could listen only for expanded or only for collapsed (and in particular, I think I built it so I could build the dynamic fetch when someone expanded a row that hadn't previously been expanded).  I think we lose something by combining them.  But yes, it'd be useful on grouping too.

**Comment by dheerajvats** [comment]
I was searching for a function/option that could get me the children for grouped row.
Maybe something similar to row.entity in cellTemplate.
I found some references for row.children but i guess it is not working.
I am using ui-grid v3.0+.....
