### ISSUE TITLE
$scope.gridApi.pinning.pinColumn not working as expected

### ISSUE THREAD

**Issue by MattOakley** [angular-ui/ng-grid#3457]
Setting pinning through code doesn't appear to have an effect.

http://plnkr.co/edit/WsQiaFhpEkkwnl1AR3VW?p=preview

Thanks

**Comment by PaulL1** [comment]
The pinning api takes a gridCol, not a colDef: http://ui-grid.info/docs/#/api/ui.grid.pinning.api:PublicApi

If you update to provide a gridCol it should work: http://plnkr.co/edit/De3rxwhVYC8WV0vzrh48?p=preview

**Comment by MattOakley** [comment]
Ok, thanks!

**Comment by Havock94** [comment]
I would like to report that if I try to pin a column and then set its pinning to 'none', the column just disappears and give me the error 
Cannot read property 'visibleColumnCache' of undefined
How can I fix this?
