### ISSUE TITLE
How to achieve filtering and sorting side by side in one row..?

### ISSUE THREAD

**Issue by mohitgupta2209** [angular-ui/ng-grid#3464]
![head](https://cloud.githubusercontent.com/assets/9722364/7559355/619575fa-f7d3-11e4-873a-ebc094370191.jpg)

Instead of doing it in 2 different lines I would like to have it as shown in the snip attached above.. Is it possible to achieve it?

**Comment by PaulL1** [comment]
I think you're trying to put the column name into the filter?  That's not something we currently do, you could potentially do it with a custom header cell template.

**Comment by PaulL1** [comment]
Solution provided that may resolve this issue, no comment for 3 weeks, closing, please re-raise or reopen if this is still occurring.
