### ISSUE TITLE
Autoexpand all rows.

### ISSUE THREAD

**Issue by billyaraujo** [angular-ui/ng-grid#3466]
Is there an auto expand per grouped item?

I know there is an expandAllRows but it doesn't work seem to work right after loading data to the grid.

**Comment by PaulL1** [comment]
Potentially this is because you're calling expandAllRows before the grid has ingested them.  Are you using a $timeout after the load before you call expandAllRows?

**Comment by billyaraujo** [comment]
Ideally there would be an autoexpand option at creation.

**Comment by klawson23** [comment]
I'm having this issue as well. 

If I try to call gridApi.grouping.expandAllRows() after setting the data nothing happens. 

I have also tried calling refresh and queueGridRefresh but neither seems to help, I have even tried placing expandAllRows plus refresh inside a timeout for a second after setting the data and it doesn't help.

I have also tried calling expandAllRows from inside a method on a button where I first change the grouping using gridApi.grouping.setGrouping() and then call gridApi.grouping.expandAllRows() and refreshing. That doesn't work the first time it is called, but interestingly if I hit the button a second time to change the grouping back to the first grouping or to clear the grouping it works and everything shows up expanded from then on.

**Comment by PaulL1** [comment]
Are you using a $timeout?  The selection tutorial gives an example of this - we load the data, do a $timeout or $interval, then we select the first row.  Expanding would be the same in terms of timing.

**Comment by klawson23** [comment]
I think calling gridApi.core.clearAllFilters() right beforehand may have
been causing an issue too. When I had a $timeout with both clearAllFilters
and expandAllRows, the expandAllRows didn't have an effect. However calling
clearAllFilters and then putting expandAllRows inside of a $timeout
resolves the issue.

This is an unrelated issue, but I am calling clearAllFilters first because
the drop down filters I have created on three columns all have an empty
option selected by default when the grid loads, preventing any data from
showing up in the grid.

**Comment by PaulL1** [comment]
OK, sure. so sounds like we can close?

**Comment by billyaraujo** [comment]
I have put timeout to expandAllRows but still would prefer an auto-expand option. Also when I use tabs with ng-show the grid looses its expanded state and have to call expandAllRows each time I show the grid.

**Comment by PaulL1** [comment]
You can use saveState to manage the expanded state of the grid.

**Comment by billyaraujo** [comment]
Thanks. I am still using RC21 but will check into that once I upgrade.

**Comment by fatifleu** [comment]
did you find solution because i have the same problem i want to expand all auto

**Comment by mportuga** [comment]
@fatifleu "I think calling gridApi.core.clearAllFilters() right beforehand may have
been causing an issue too. When I had a $timeout with both clearAllFilters
and expandAllRows, the expandAllRows didn't have an effect. However calling
clearAllFilters and then putting expandAllRows inside of a $timeout
resolves the issue."
