### ISSUE TITLE
External Filter throttling

### ISSUE THREAD

**Issue by csharpengineer** [angular-ui/ng-grid#3467]
Is there a way to set a delay for the filterChanged event?  I am using external pagination with external filtering and external sorting and I don't want to do a server-side request every time someone types a letter into the column filter fields.  I'd like to wait for a defined delay period to expire after each character is entered before I retrieve a new dataset from the server.

**Comment by PaulL1** [comment]
You need to debounce the callback, usually people use a $timeout to do the debounce.

**Comment by csharpengineer** [comment]
Thanks.  I was able to make this work by using a debounce on the callback registered for `gridApi.core.on.filterChanged`.  Just wanted to suggest this be implemented natively as part of ng-grid due to there already being debounce for aggregators and scrolling.

**Comment by PaulL1** [comment]
The debounce on aggregators and scrolling have both given troubles and been removed ultimately.  I think it's reasonable to have this implemented externally, as some people will want it and some people won't.  Closing.
