### ISSUE TITLE
Csv Export & CellTemplate

### ISSUE THREAD

**Issue by gunjanr17** [angular-ui/ng-grid#3468]
On UI-Grid, I have a cellTemplate on a field which add some addition information to that cell content.
If I export the data of this grid using csv export this does not considering cell template on that field.

Is there a way through which CSV export should export data displayed to user on grid using cellTemplate.

Example:
http://plnkr.co/edit/0IjYEdVsK7ryrcU8poYb?p=preview
In the above plunkr, ui-grid has a field as name having cellTemplate which prefix name with "Hello"  and I want to export the data with "Hello" name in the csv format.

**Comment by PaulL1** [comment]
Exporter cannot see the rendered data, it works against the data in the data array.  If you want custom formatting you'd need to use exporterFieldCallback: http://ui-grid.info/docs/#/api/ui.grid.exporter.api:GridOptions

**Comment by gunjanr17** [comment]
If I have 10 columns each having different cellTemplate than in exporterFieldCallback function I need to handle each column differently, am I correct?

**Comment by PaulL1** [comment]
Yes, correct.  I believe the callback provides the row and column so you could detect this in code.

**Comment by PaulL1** [comment]
Solution provided that should allow resolution, no further correspondence, assuming that solution resolved the problem.
