### ISSUE TITLE
How to set height of the table to be 100% of parent container?

### ISSUE THREAD

**Issue by iyel** [angular-ui/ng-grid#3469]
I see that height is set programmatically using element style

**Comment by PaulL1** [comment]
Take a look at the auto-resize feature: http://ui-grid.info/docs/#/tutorial/213_auto_resizing

**Comment by iyel** [comment]
@PaulL1 so I can do it only programmatically?

**Comment by PaulL1** [comment]
I believe if you set the parent container height, then the grid will automatically inherit that size.  You can set the parent container using css, but I believe the height must be explicit, it cannot just be a percentage.

**Comment by iyel** [comment]
Found solution, works in IE 9+
You can set height of 
```css 
height: 100vh - (other elements on page)px
```
