### ISSUE TITLE
Group header row is editable

### ISSUE THREAD

**Issue by cliren** [angular-ui/ng-grid#3470]
Group header rows shouldn't be editable as it is stated in the docs, Group header rows cannot be edited. 
But they are editable, here is the example. Am I missing some config option?

http://plnkr.co/edit/58nQjbirNzxFSHpEMgXD?p=preview

**Comment by AgDude** [comment]
Thanks for the bug report. This should be addressed as part of #3445.

**Comment by PaulL1** [comment]
Hmm.  `insertGroupHeader` in grouping.js has `headerRow.enableEditing = false;`

I presume that means that editing is not honouring that.  Looks like I never built that bit.  Thought I had.  `enableSelection` works, do I get points for that?

Nope, looks like it should be `enableCellEdit`, not `enableEditing`.
