### ISSUE TITLE
How to remove row selection highlighting

### ISSUE THREAD

**Issue by sirix42** [angular-ui/ng-grid#3471]
I am using ui-grid v3.0.0-RC.18. Instead of creating a column of checkmarks via a template, I decided to use the existing grid options to generate a column with 'Select All' enabled. The problem is I don't want to have the rows highlighted. How can I achieve this? Thanks.

	$scope.gridOptions = {
	    enableRowSelection: true,
	    enableSelectAll: true,
	    selectionRowHeaderWidth: 35,
	    rowHeight: 25,
	    showGridFooter:true,
	    modifierKeysToMultiSelect: false,
	    enableRowHeaderSelection: true,
	};

**Comment by dregan-gh** [comment]
This is a css property, so you can remove/modify it and the rows wont get highlighted.

**Comment by sirix42** [comment]
I see that it's the 'ui-grid-row-selected' class that does the highlighting. How do I remove it for just this grid?  I have another grid that I do want highlighting enabled on a row selection.  Thanks!

**Comment by PaulL1** [comment]
That's a bit trickier.  You'd need to use some less/css inheritance to target the ui-grid-row-selected to only that specific grid.

**Comment by PaulL1** [comment]
Solution provided that may resolve this issue, no comment for 3 weeks, closing, please re-raise or reopen if this is still occurring.

**Comment by Vinodang** [comment]
you can use enableHighlighting:true
