### ISSUE TITLE
Grouping issue with ui-grid

### ISSUE THREAD

**Issue by leelakrish** [angular-ui/ng-grid#3474]
Grouping the drop down column does not show the correct grouping header. please find the plunker for the same.

http://plnkr.co/edit/We2YFj9mMvoEU6kR5eQn

**Comment by PaulL1** [comment]
The issue is that you've inserted a cellTemplate that doesn't handle groupHeaders.  I'd suggest using the editable feature rather than overriding the cellTemplate with an editable dropdown.  Alternatively, your cellTemplate needs to check whether the row it's on is a groupHeader and render a different widget if it is.

**Comment by leelakrish** [comment]
http://plnkr.co/edit/1l1RH9DVr5wpMSC8NVlt

In the above plunker, I just added grouping with the dropdown provided in below ui-grid tutorial link,

http://ui-grid.info/docs/#/tutorial/315_editable_cascading_dropdown 

When I group the "gender" column which has dropdown values. There also grouping is not working as expected.

**Comment by PaulL1** [comment]
This is covered in the grouping tutorial.  You need to adjust the filter on gender to deal with the fact that grouping changes the cell value from `1` to `1 (10)`

**Comment by AgDude** [comment]
Closing, since no response for 3 weeks.

**Comment by ravivantaku** [comment]
http://plnkr.co/edit/Fd83R3gM8DZcF63x6WtI?p=preview 

I have modified the plunker which is given in grouping examples in ui-grid. 
 http://ui-grid.info/docs/#/tutorial/320_complex_grouping
In the above plunker i changed the gender field editableCellTemplate into cellTemplate with dropdown values then the gender field grouping header label is not visible. In columnDef's cellFilter is not working if we place cellTemplate in that column but works fine for editableCellTemplate property for the same column.

Give me any solution for this. Thanks in advance.
