### ISSUE TITLE
Editable cell support for ui-select

### ISSUE THREAD

**Issue by justin-romano** [angular-ui/ng-grid#3478]
I noticed someone did a branch for select2 support in ng-grid.
Are there any plans to support ui-select as a cell editor in the new ui-grid?

**Comment by salarmehr** [comment]
+1

**Comment by salarmehr** [comment]
+1

**Comment by trytocatchme** [comment]
It would be nice, +1

**Comment by PaulL1** [comment]
Not directly.  But ui-grid can support any editor that you choose to build a directive for.

**Comment by trytocatchme** [comment]
I tried to do this based on the [example](http://plnkr.co/edit/taPmlwLxZrF10jwwb1FX?p=preview) without the expected [results](http://plnkr.co/edit/dHIoizDE6p9UUoRTAmhg?p=preview).

btw select2 can work with that?
   gridApi.edit.on.afterCellEdit($scope,function(rowEntity, colDef, newValue, oldValue){
            $scope.msg.lastCellEdited = 'edited row id:' + rowEntity.id + ' Column:' + colDef.name + '   newValue:' + newValue + ' oldValue:' + oldValue ;
            $scope.$apply();
          });

**Comment by c0bra** [comment]
@justin-romano @trytocatchme Try using the method from this post: http://brianhann.com/ui-grid-and-dropdowns/  it shows how to use ui-select as an editor.
