### ISSUE TITLE
grunt build fails on ngdocs

### ISSUE THREAD

**Issue by fotofinder** [angular-ui/ng-grid#3484]
The Error is:
Warning: Unable to read "bower_components/csv-js/csv.js" 
after changing grunt/ngdocs.js to "src/bower_components/..." this task completed.

**Comment by PaulL1** [comment]
My bower_components is not under src - it is directly in the root of the directory.  I presume that's also what all the other devs get.

What led you to expect bower_components to be in src/bower_components?

**Comment by fotofinder** [comment]
Ah, that pulled a trigger.
I installed ng-grid as a sub modul to an existing project. And in this main project there is a `.bowerrc` file. 
Thanks for your reply!
