### ISSUE TITLE
grunt dev fails on task 'jscs:files'

### ISSUE THREAD

**Issue by fotofinder** [angular-ui/ng-grid#3486]
The Error is:
`Warning: Cannot read property 'loc' of undefined Use --force to continue.`

After once removing 'src/**/*.js' from the files array in grunt/jscs.js the task passes.

**Comment by PaulL1** [comment]
I wonder whether there is something wrong with your build environment.  I'd suggest re-cloning the ng-grid repository, and doing the install from scratch to see if that fixes your issues.

**Comment by PaulL1** [comment]
Solution provided that may resolve this issue, no comment for 3 weeks, closing, please re-raise or reopen if this is still occurring.
