### ISSUE TITLE
[filtering] Remove clear button when no filter

### ISSUE THREAD

**Issue by AgDude** [angular-ui/ng-grid#3487]
Previously when the filter text was deleted the "X" to clear the text was removed from the input. Between RC 20 and 21, this discontinued to be the case. Now if you enter a filter, then delete the text, the clickable X icon stays in the input.

**Comment by PaulL1** [comment]
I think I fixed this earlier today - do you want to check?  I just added an empty string check.

**Comment by AgDude** [comment]
Yes, this appears to be fixed.

**Comment by Shabbir-Saifee** [comment]
@PaulL1 Can you please mention the version in which this issue was fixed, we are currently using ui-grid 3.2.1
