### ISSUE TITLE
Can I have a custom aggregated function for the row?

### ISSUE THREAD

**Issue by cliren** [angular-ui/ng-grid#3490]
There are predefined aggregators like SUM, AVG etc, but I need more like RANGE, CONCAT (string concat) etc., is there a way to extend or do it through a cellTemplate?

**Comment by billyaraujo** [comment]
I was going to make a new post but I also would like custom aggregate function for each column when grouping. I have something more complex like an image and when grouped I want to show a custom image in the grouped row.

**Comment by AgDude** [comment]
This isn't currently supported, but it is planned. I am closing this as a duplicate of #3302.
