### ISSUE TITLE
[IE9] Broken syles if more than 27 grids

### ISSUE THREAD

**Issue by Matzz** [angular-ui/ng-grid#3491]
Hello,
I use a lot of grids on one page. On IE9 I noticed that  28'th and later grids has broken styles. Previous grids are fine. Bug can be reproduced on jsfiddle http://jsfiddle.net/rqzoyh6q/
Issue is present on all 3.x versions of ui-grid.  Broken styles are visible on image below. What is more if we add filters to headers, they also are broken.
![screen](https://cloud.githubusercontent.com/assets/1036919/7606926/9dab92e6-f95d-11e4-881f-986f524c761b.jpg)

Generated styles from valid grid

```
.grid1431505141783 {
      /* Styles for the grid */
    }

    .grid1431505141783 .ui-grid-row, .grid1431505141783 .ui-grid-cell, .grid1431505141783 .ui-grid-cell .ui-grid-vertical-bar {
      height: 30px;
    }

    .grid1431505141783 .ui-grid-row:last-child .ui-grid-cell {
      border-bottom-width: 0px;
    }

    
    

    /*
    .ui-grid[dir=rtl] .ui-grid-viewport {
      padding-left: px;
    }
    */

    
 .grid1431505141783 .ui-grid-coluiGrid-01P { min-width: 121px; max-width: 121px; } .grid1431505141783 .ui-grid-coluiGrid-01Q { min-width: 121px; max-width: 121px; } .grid1431505141783 .ui-grid-coluiGrid-01R { min-width: 121px; max-width: 121px; } .grid1431505141783 .ui-grid-coluiGrid-01S { min-width: 120px; max-width: 120px; }

 .grid1431505141783 .ui-grid-render-container-body .ui-grid-canvas { width: 483px; height: 30px; }
 .grid1431505141783 .ui-grid-render-container-body .ui-grid-header-canvas { width: 500px; }
 .grid1431505141783 .ui-grid-render-container-body .ui-grid-header-canvas { height: inherit; }
 .grid1431505141783 .ui-grid-render-container-body .ui-grid-viewport { width: 500px; height: 72px; }
 .grid1431505141783 .ui-grid-render-container-body .ui-grid-header-viewport { width: 500px; }
 .grid1431505141783 .ui-grid-render-container-body .ui-grid-footer-canvas { width: 500px; }
 .grid1431505141783 .ui-grid-render-container-body .ui-grid-footer-viewport { width: 500px; }
.grid1431505141783 .ui-grid-footer-aggregates-row { height: 30px; } .grid1431505141783 .ui-grid-footer-info { height: 30px; }
 .grid1431505141783 .ui-grid-coluiGrid-01P { min-width: 121px; max-width: 121px; } .grid1431505141783 .ui-grid-coluiGrid-01Q { min-width: 121px; max-width: 121px; } .grid1431505141783 .ui-grid-coluiGrid-01R { min-width: 121px; max-width: 121px; } .grid1431505141783 .ui-grid-coluiGrid-01S { min-width: 120px; max-width: 120px; }
```

Generated styles from invalid grid

```
.grid1431505141812 {
      /* Styles for the grid */
    }

    .grid1431505141812 .ui-grid-row, .grid1431505141812 .ui-grid-cell, .grid1431505141812 .ui-grid-cell .ui-grid-vertical-bar {
      height: 30px;
    }

    .grid1431505141812 .ui-grid-row:last-child .ui-grid-cell {
      border-bottom-width: 0px;
    }

    
    

    /*
    .ui-grid[dir=rtl] .ui-grid-viewport {
      padding-left: px;
    }
    */

    
 .grid1431505141812 .ui-grid-coluiGrid-04X { min-width: 121px; max-width: 121px; } .grid1431505141812 .ui-grid-coluiGrid-04Y { min-width: 121px; max-width: 121px; } .grid1431505141812 .ui-grid-coluiGrid-04Z { min-width: 121px; max-width: 121px; } .grid1431505141812 .ui-grid-coluiGrid-050 { min-width: 120px; max-width: 120px; }

 .grid1431505141812 .ui-grid-render-container-body .ui-grid-canvas { width: 483px; height: 30px; }
 .grid1431505141812 .ui-grid-render-container-body .ui-grid-header-canvas { width: 500px; }
 .grid1431505141812 .ui-grid-render-container-body .ui-grid-header-canvas { height: inherit; }
 .grid1431505141812 .ui-grid-render-container-body .ui-grid-viewport { width: 500px; height: 72px; }
 .grid1431505141812 .ui-grid-render-container-body .ui-grid-header-viewport { width: 500px; }
 .grid1431505141812 .ui-grid-render-container-body .ui-grid-footer-canvas { width: 500px; }
 .grid1431505141812 .ui-grid-render-container-body .ui-grid-footer-viewport { width: 500px; }
.grid1431505141812 .ui-grid-footer-aggregates-row { height: 30px; } .grid1431505141812 .ui-grid-footer-info { height: 30px; }
 .grid1431505141812 .ui-grid-coluiGrid-04X { min-width: 121px; max-width: 121px; } .grid1431505141812 .ui-grid-coluiGrid-04Y { min-width: 121px; max-width: 121px; } .grid1431505141812 .ui-grid-coluiGrid-04Z { min-width: 121px; max-width: 121px; } .grid1431505141812 .ui-grid-coluiGrid-050 { min-width: 120px; max-width: 120px; }
```

**Comment by c0bra** [comment]
IE9 only supports 31 stylesheets, max: http://blogs.msdn.com/b/ieinternals/archive/2011/05/14/10164546.aspx

There's no way around it that I'm aware of, sorry.

**Comment by Matzz** [comment]
I confirm style sheets limitation (example http://fiddle.jshell.net/qc5d6su9/).
Maybe you should add some method to combine styles? For example property style ContainerId to provide container id. If present library could append styles to this one container.
Other possibility is callback function which receive styles. Its responsibility would be to embed (or even transform) styles.

**Comment by PaulL1** [comment]
Two comments:

1.  IE9 is only marginally supported.  It works (so we're not desupporting it) but it doesn't work well.  We realise that some people are stuck with clients that still have IE9 in their corporate image or whatever, so we're trying to make sure it works OK for common scenarios.  But we don't have the ability to do unique code just for IE9.

2.  27 grids on a page doesn't sound like a good idea.  Are they all visible at the same time?  My suggestion is that you write the code to work out which grids are actually visible, and use an ng-if to hide the remainder.  That would avoid this problem, and have the side effect of making your application much more performant (27 grids on a page is a performance issue, IE9 performance is substantially worse than the other browsers we support).

**Comment by Matzz** [comment]
Grids are hidden using tabs. I think that ng-if wont fix this problem. Once grids are initialized they will remain in dom tree.

**Comment by PaulL1** [comment]
If you're using tabs then the best practice is to put an ng-if on the tab contents and only render the grid with the tab is active.  You can detect that the tab is active through setting a property on tab click.  There are a number of issues (and associated plunkers) that demonstrate use of the grid in tabs.

**Comment by PaulL1** [comment]
(in fact, there's one in the tutorials: http://ui-grid.info/docs/#/tutorial/108_hidden_grids)

**Comment by Matzz** [comment]
Thank you very much.  I will check it.
