### ISSUE TITLE
ui grid destroy data items while scroll bar dragging ?

### ISSUE THREAD

**Issue by HeavenGoGo** [angular-ui/ng-grid#3493]
I use ui grid to display data, I created a directive which used to add custom attributes to cell template to make sure it will display popover information when the mouse hover on the cell. In other words these custom attributes are directives indeed.  in order to make it to work normally , I need to compile them manually.  

Assume that there just can display 10 records, the 11-20 only be seen with dragging the scroll bar down. So the 1-10 records can work well, but the 11-20 records can't work. when 11-20 display, they will not execute the compile process, but when we drag scroll bar up to hide these data items, they will be compiled, but when drag down again they also can't work, just because when the data hide, they  are destroyed?

Here's the whole thing on plunker:http://plnkr.co/edit/y36frn9gYMGJEy1hJU7f, you can check the browser log result.

**Comment by PaulL1** [comment]
The virtualisation is likely to be causing you issues - the DOM elements are reused when we scroll, but they are pointed to different row/col.  Manually compiling the template is probably going to give you problems.

I'm looking through your code to see what it's doing and try to give some tips.  Unfortunately it's not clear to me what you're trying to achieve to be able to give you advice how to do it.  I'm never getting a pop-over when I hover - is that what you also get?

**Comment by HeavenGoGo** [comment]
I had resolve this issue, the example I gave you just print the manual compiled row information. because the rows are reused so the link function will not execute by default.   So I must watch the value and execute the compile function when the value changed. the plunker is  http://plnkr.co/edit/La1gQbwVLh0t3ObSZlxC?p=preview.

**Comment by PaulL1** [comment]
OK, sounds like you've resolved it.  Closing.
