### ISSUE TITLE
Row headers unaligned when there are filters in header

### ISSUE THREAD

**Issue by valepu** [angular-ui/ng-grid#3495]
Hi,
When you use row headers and filters together, row headers will go up by a row, resulting in an unaligned grid. See this Plunker http://plnkr.co/edit/TJGTS1?p=preview (if it doesn't happen right on load, try resizing the preview frame)

On this plunker I was trying (unsuccessfully) to reproduce another bug i'm having (but then realized it was fixed in the latest unstable), that explains all the features i have activated

**Comment by PaulL1** [comment]
Duplicate of #3394.
