### ISSUE TITLE
headerCellClass cellClass footerCellClass Center is not centered

### ISSUE THREAD

**Issue by dereklin** [angular-ui/ng-grid#3497]
Here is my plunker: http://plnkr.co/edit/dr8B3YGRt8dAoqtbr05m?p=preview

As one can see, the cell and footer behave the same.  The header is different.  I am guessing it's because the column menus.  But in my case, I have disabled column menus.

Issues:

1. The Secondary header is not centered
2. The Primary cells are not centered, but the Primary header is actually centered, this is so strange...
3. Like #2, the Primary footer is not centered.

How can I make things truly centered?

P.S.:

I have the column set up like this: headerCellClass: "center", cellClass: "center", footerCellClass: "center"

This is the class:

.center {
  text-align: center;
}

**Comment by alexspence** [comment]
I worked around this issue with this:

.ui-grid-invisible {
    display:none;
}

Your grid also appears to be using over 100%, probably due to the tree column.  I set your last column to 25% and it appears to behave the way you want it.

http://plnkr.co/edit/atldGpiIeOciOZ5qMqkg?p=preview

**Comment by icfantv** [comment]
I can confirm the problem is with the `.ui-grid-invisible` CSS class.  It should be using `display: none;` as @alexspence notes above.  The reason being is that `visibility: hidden;` still allocates space in the DOM whereas `display: none;` does not.

The result is that centering the header yields a header that is pushed to the left and the header does not appear centered when the sort icon is not present.

**Comment by dereklin** [comment]
Thanks @alexspence and @icfantv

**Comment by c0bra** [comment]
Sounds like you found a workaround. I don't think we want the column text to shift around based on whether there's a sort direction or not. You could also use a custom cell header if you didn't want to override an internal CSS class.

**Comment by icfantv** [comment]
I guess I'm ok with that solution @c0bra, but I believe this behavior should be documented in the API.
