### ISSUE TITLE
Cell Nav, Edit, Selection - touching grid cell in mobile device not opening keyboard

### ISSUE THREAD

**Issue by alexspence** [angular-ui/ng-grid#3498]
I'm at wits end with this issue.  I created a plunker to show that it doesn't work, but it works in the plunker.  Yet for some reason, when I have the same exact code hosted from my java app, the keyboard does not open unless I click the cell twice.  I get a cursor that flashes and no keyboard.

http://plnkr.co/edit/95AWv30FYeO8r2ZIUwmM?p=preview
This is the plunker with the same code I'm running that seems to work, even though running the same code in my app is not working.

I was using the latest RC, but in an attempt to resolve this issue I'm using the latest unstable.  The code In my web app is almost exactly the same as the plunker (Only minor differences in file names and paths).

**Comment by PaulL1** [comment]
There must be something that's not exactly the same.  Have you downloaded the code from both and run some form of compare tool to verify that it's line for line identical?  Are there timing differences in the order things load due to the different server?

**Comment by alexspence** [comment]
It has to do with the timeout.  Currently the default is 200, I changed that value to 50 and the behavior changes.  It works different on my android vs the ipad mini.  It even works different in full screen saved as a shortcut vs browsing to the app.  Changing the timeout to 50 ms seems to work ok, though trying to scroll selects columns.  

I'm also having weird scrolling issues with this. When I click on a cell to edit it seems to scroll for no reason.  Like it will bounce up and back down.  

Another issue I'm having is the selection.  When you try to touch to select, if you don't press for so long your selection is removed.

I'm trying to learn the codebase so I can suggest fixes for these issue.  The grid is awesome and in its state I'm expecting some work on my side to get everything working right.

**Comment by alexspence** [comment]
Another issue is the select on the ipad.  I'm testing using selectRange vs select() but so far I've only been able to get it to select and then deselect immediately.

**Comment by PaulL1** [comment]
Hanging out on the gitter channel can sometimes find people who can give immediate feedback and tips on the code base: https://gitter.im/angular-ui/ng-grid

I don't have lots of good ideas on your code - there's a lot going on in there and I'm not on a mobile device at the moment.  But some observations:

1.  You have some functions that calculate things like order totals.  You can bind columns to functions, you might find that a more efficient way to do what you're trying to do - then the function will automatically get called on any digest cycle.  It has some performance implications though

2.  If you were to play with rowEdit you could perhaps get a different way to handle your orderHasErrors construct.  That lets you validate a row at a time, and make the row red when it's in error

**Comment by PaulL1** [comment]
I think @alexspence may have visited gitter and received some advice, either way, I think this is no longer open.  Closing.
