### ISSUE TITLE
[RC21] Template files & loaders

### ISSUE THREAD

**Issue by Cayan** [angular-ui/ng-grid#3501]
In some features (like selection), there are directives using  $templateCache.get for templates and in my application they never load, probably cuz' the templateCache never got to it. I've read some core functions that work somehow alike and they are using the gridUtils.getTemplate function, so I updated some files to use gridUtils as well and everything went fine. 

I've updated theses files in my local, would it be okay to open a pull request?

**Comment by PaulL1** [comment]
Hmm.  It doesn't seem to do this in the tutorials.  Are you sure this isn't something unique to your environment?

**Comment by Cayan** [comment]
Tutorials uses built-in templates, open their js files and look for $templateCache.put, there will be a bunch of lines settings those up.

This leads to another problem: templates are requested without any extension and their folder's data are filled with .html files. I avoid editing files whenever possible, so I had to create and .htaccess file to redirect those requests, example: ui-grid -> ui-grid.html

**Comment by PaulL1** [comment]
I guess what I'm not understanding is why it's not working for you and is working for other people.

Are you using the distributed ui-grid.js file, or are you building your own version?  Usually all the templates are bundled inside the ui-grid.js file.

**Comment by c0bra** [comment]
No response in > 2 weeks. Closing.
