### ISSUE TITLE
resetting data binding doesn't clear selectedItems 

### ISSUE THREAD

**Issue by schengcrouchingtiger** [angular-ui/ng-grid#3503]
I have a ng-grid which has options:

$scope.callFlowGridOptions = {
                data: 'routes',
                enablePaging: false,
                showFooter: false,
                showSelectionCheckbox: true,
                selectedItems: [],
                enableCellEditOnFocus: true,
...

}

when I click a button and reload the data binding,

 LMC.getRoutes( criteria, filter )
                    .success( function(routes) {
                        $scope.routes = routes;
                    } );

the selectedItems remains and are not cleared.

It is expected that the data binding changes, the selectedItems should be reset to an empty array and should not carry over from previous data binding

**Comment by schengcrouchingtiger** [comment]
I have to manually clear the array items:

 LMC.getRoutes( criteria, filter )
                    .success( function(routes) {
                        $scope.routes = routes;
                        while ($scope.callFlowGridOptions.$gridScope.selectedItems.length) {
                            $scope.callFlowGridOptions.$gridScope.selectedItems.pop();
                        }
                    } );


if I do:

$scope.callFlowGridOptions.$gridScope.selectedItems = [];
it will not work

**Comment by PaulL1** [comment]
If you have replaced the items, how is it finding the selected items again?  Or are you saying they are still in the array even though they don't show selected on the grid?  Any chance of a plunker?

**Comment by PaulL1** [comment]
More information sought, not forthcoming after 3 weeks.  Closing, please reopen or reraise if this is still an issue for you.
