### ISSUE TITLE
JSON Date Format

### ISSUE THREAD

**Issue by ImranAhmed** [angular-ui/ng-grid#3504]
Hi,

Another date format question, I couldn't find an exact answer for this in forum.

My dates are in following format: /Date(1355097600000)/

I am trying to format as follows but it's not having any effect. Any ideas?

    {
                        name: 'From',
                        field: 'DateFrom',
                        cellTemplate: "<span> {{row.entity.DateFrom | date:'dd-MMM-yyyy'}}</span>"
                    },

**Comment by PaulL1** [comment]
Could you provide a plunker?  I'd expect that there's some flavour of angularJS filter that will format it for you, but really that's an angularJS thing rather than a ui-grid thing.

**Comment by ImranAhmed** [comment]
I was able to fix this. A percularity that exists in ASP.NET MVC when using the JavaScriptSerializer (Micorosft proprietary).

This was my ASP.NET MVC controller action and it returned dates in format:  /Date(1355097600000)/.

            var cr = new ContentResult
            {
                Content = new JavaScriptSerializer { MaxJsonLength = Int32.MaxValue }.Serialize(model),
                ContentType = "application/json"
            }

I switched the above to using JSON.NET serializer instead as follows:

            var cr = new ContentResult
            {
                Content = JsonConvert.SerializeObject(model, new IsoDateTimeConverter()),
                ContentType = "application/json"
            };

My dates are now output in the following format and can be succesfully manipulated by Angular:

           {"DateTo":"2012-12-02T00:00:00","DateFrom":"2012-12-01T00:00:00"}

**Comment by emsapplication** [comment]
thanks Imran its really resolve the problem.

I follow same as like.
**Import:::**
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

**MVC Code ::**
  public ActionResult GetAllResourceDetail()
        {
            List<ResourceDetailBO> resCol = _iResourceDetailBL.GetAllResourceDetail();
            var cr = new ContentResult
            {
                Content = JsonConvert.SerializeObject(resCol, new IsoDateTimeConverter()),
                ContentType = "application/json"
            };
            return cr;
        }

**JS Code Is** 
{
                field: 'CareerStartDate',displayName: 'Career Start Date', cellTemplate: '<span> {{row.entity.CareerStartDate | date:\'dd-MMM-yyyy\'}}</span>',
            }
