### ISSUE TITLE
guessSortFn - where to use?

### ISSUE THREAD

**Issue by juliusakula** [angular-ui/ng-grid#3509]
[doc with no example](http://ui-grid.info/docs/#/api/ui.grid.class:RowSorter)

Should this be set in columnDefinitions? Like so:

    {"name": "some_numbers", "sortingAlgorithm":  guessSortFn("number")}

I've got this issue (rc-21) where its sorting the numbers 10, 75, and 300. When sorting Descending, 75 is the 'top value', then 300, then 10. As if it thinks they are strings and doing alphabetical sort, I want to force a numerical sort.

**Comment by PaulL1** [comment]
If you set the type of the column to (IIRC) `numberStr` it should work.

**Comment by juliusakula** [comment]
Oh, so it automatically picks a sorting algorithm based off of the columns `type` attr. Thanks, that's worth documenting. That did work.

    {"name": "some_numbers", "type": "number"}

**Comment by juliusakula** [comment]
is there a `type: 'percentage'` ?

**Comment by PaulL1** [comment]
No, but I'd guess `type: 'numberStr'` might work - I think that treats a string as a number and attempts to parse it as such.  I'd guess that means we end up sorting the numeric characters as a number, and ignoring the percentage sign.

Of course, if I had a column that had percentages in it, I'd store it as a decimal number and use a cellFilter to display it as a percentage.  That'd make it much easier to work with.
