### ISSUE TITLE
How to show a grid in a Bootstrap modal

### ISSUE THREAD

**Issue by salarmehr** [angular-ui/ng-grid#3511]
I want to show an ui-grid in angular-bootstrap modal. However it seems the two directives are implemented using incompatible approach. Is it true? How can we use them together?

**Comment by PaulL1** [comment]
I use angular-bootstrap in my project, and I show ui-grid in a bootstrap modal without any major issues.

What exactly is it that gives you the problem?  There is a tutorial for grid in a modal (not with a bootstrap modal though unfortunately): http://ui-grid.info/docs/#/tutorial/110_grid_in_modal

**Comment by salarmehr** [comment]
@PaulL1  I will check it again. Thanks.
