### ISSUE TITLE
NaN instead of the current Page Number on the Firefox

### ISSUE THREAD

**Issue by salarmehr** [angular-ui/ng-grid#3512]
In demos and my code 'NaN' is shown instead of the number of current page on the pagination bar. 
http://ui-grid.info/docs/#/tutorial/318_external_pagination
http://ui-grid.info/docs/#/tutorial/314_external_pagination

Also, both section 314 and 318 on the tutorial are titled as: "external_pagination".

**Comment by PaulL1** [comment]
Hmm.  I don't get NaN.  What browser are you on?  I'm on Chrome/OSX.

On the tutorials, I never noticed that before.  No doubt it's because we had two competing features for a while (paging and pagination), probably the tutorial pages didn't get deleted but rather both got upgraded.

**Comment by salarmehr** [comment]
@PaulL1  It seems the issue is limited to FireFox (Opera/IE are OK.)

paging and pagination! What is differences? Which one should I use?

**Comment by PaulL1** [comment]
Hmm.  I don't have firefox on my machine here.  I'd be putting some breakpoints in the pagination code to see what calculation is returning that

**Comment by salarmehr** [comment]
I think it is a firefox bug. (it see same behavior other places as well.) 
closing for now
