### ISSUE TITLE
Fix module injection misnaming in ng-grid docs

### ISSUE THREAD

**Issue by skolsuper** [angular-ui/ng-grid#3514]
As far as I can tell, the docs at http://angular-ui.github.io/ng-grid/ are for 3.x? I'm not sure because there's no indication of that anywhere. Are there docs for 2.x? What is http://ui-grid.info/?

If those docs are supposed to be for 2.x then in line 3 where they say to inject `ui.grid` to your app they should say `ngGrid`, because in my version of ngGrid (from `bower install ng-grid`, version 2.0.14) the module is called `ngGrid` and `ui.grid` does not appear anywhere in the code.

**Comment by PaulL1** [comment]
The first docs are 2.x, the ui-grid.info docs are ui-grid/3.x.

**Comment by c0bra** [comment]
What? There's a message that says that ng-grid is being rewritten as UI-Grid, with a link.

@skolsuper Is the problem that that message makes it seem like the old docs (http://angular-ui.github.io/ng-grid/) are for v3 and not v2?

**Comment by PaulL1** [comment]
@c0bra: I had a quick look - there are a few examples on the 2.x page that show a module include of ui.grid.

**Comment by skolsuper** [comment]
Have fixed the title to a more precise description of the issue

**Comment by c0bra** [comment]
@PaulL1 looks like you were complicit :) https://github.com/angular-ui/ng-grid/commit/3e6bf0a6adda86c160a040084a29caa0bd4f5aa3

I will revert the commit.

**Comment by c0bra** [comment]
Done 2464ec321c2a4ae9410

**Comment by PaulL1** [comment]
Crap, you're kidding me.  It was a long time ago, I'm pleading ignorance.
