### ISSUE TITLE
Expand first row by default during the initial page load after the grid finishes rendering all rows.

### ISSUE THREAD

**Issue by AshwiniNaidu** [angular-ui/ng-grid#3520]
I have a requirement to display the first row of ui-grid as expanded during the initial page load after the grid finishes loading/rendering all rows. Subsquent selection of rows should toggle the row expansion. I tried using the  *renderingComplete* event to acheive the same but it didn't work. When I used *rowsRendered* event, it didnt appear expanded for the first time but each time when the rowSelectionChanged event fired, this got triggered too and the first row was expanded.

**Comment by PaulL1** [comment]
In general you can use onRegisterApi, then add a $interval or $timeout.

**Comment by AshwiniNaidu** [comment]
I tried but due to the difference in the server response time(for the data in the grid), I am facing an error saying undefined row entity.

**Comment by AshwiniNaidu** [comment]
I was able to fix it for now by adjusting the time delay, however I feel that may not be consistent for every response from the server.

 $scope.gridOptions.onRegisterApi = (gridApi: any) => {
        $scope.gridApi = gridApi;  
// check if already the rows are rendered and toggle the row expansion else give a time delay
          if (gridApi.grid.renderContainers.body.visibleRowCache.length !== 0) {
            $scope.gridApi.expandable.toggleRowExpansion($scope.gridApi.grid.rows[0].entity);
          } else {
            $timeout(() => {
              $scope.gridApi.expandable.toggleRowExpansion($scope.gridApi.grid.rows[0].entity);
            }, 30000);
          }

**Comment by PaulL1** [comment]
If the rows aren't there upon load, then you shouldn't really use the onRegisterApi/onRender events, because the grid will finish rendering well before data is available.  Your code controls when the data is given to the grid, normally if you're getting data via http then you would load the data into the grid, then $timeout, then toggle the row expansion.

You definitely shouldn't use timeout length to guess when the data is returned - you know exactly when the data is returned because your code receives it.

**Comment by AshwiniNaidu** [comment]
Yeah, I could figure a way around to watch the response and then toggle the row expansion with a $timeout. Here is the updated code. 

$scope.$watch('data', () =>  {
            $timeout(() => {
              var rows = $scope.gridApi.grid.rows;
              var entity: any = (rows.length && rows[0]) ? rows[0].entity : null;
              $scope.gridApi.expandable.toggleRowExpansion(entity);
            });
        });

Thanks for the response.

**Comment by c0bra** [comment]
Sounds like you got a workaround. If you still have questions or think this needs to be addressed again please file another issue.
