### ISSUE TITLE
Columns are misaligned if grid is hidden before data is loaded.

### ISSUE THREAD

**Issue by guznerge** [angular-ui/ng-grid#3526]
I am using version version 3.0.0.r21 of the UI grid and I have a simple scenario.
When page starts the grid is hidden. There is a call to get data which takes a some time.
When data received gridOptions.data is updated and grid is show. When I used version 3.0.0.r20 the grid showed correctly. After upgrading to r21 the columns are out of alignment.
A sample plunkr is here: http://plnkr.co/edit/yPApYPeRrLzOPzErT4bG?p=preview

If you change version to r20, or call getData() without timeout, or don't hide grid while loading the columns appear correctly.

**Comment by PaulL1** [comment]
Have you reviewed http://ui-grid.info/docs/#/tutorial/108_hidden_grids?

**Comment by c0bra** [comment]
No response in > 2 weeks. Closing.
