### ISSUE TITLE
CellNav: lose ability to move in obscure situations

### ISSUE THREAD

**Issue by PaulL1** [angular-ui/ng-grid#3528]
Some different scenarios:

1.  Go to the 202 tutorial: http://ui-grid.info/docs/#/tutorial/202_cellnav.  Click on the cell id: 0.  Shift+tab, which takes us off the grid.  Click on cell id: 0 again.  Up and down arrow keys no longer work, they scroll the grid.  Clicking again (on a different cell) seems to make them work.

2.  Same scenario as above, shift+tab off, tab to try to get back to grid, focus doesn't come into grid.

3.  Go to 309 tutorial http://ui-grid.info/docs/#/tutorial/309_editable_with_cellnav.  Click on cell id: 7.  Tab across until the address "vandiver" is selected.  Click in the input so that your cursor is in the edit cell.  Right arrow until you get to the end, and go off the end.  Focus is lost, and cannot be regained via keyboard.  I think the right answer here is that right arrow key shouldn't lose focus, but should stick at the rightmost edge of the cell (if you're scrolling through lots of text in the cell to get to the end, you don't want to run off the end).  But failing that, it shouldn't get into a non-keyboard navigable situation.

**Comment by willcodeforbeer** [comment]
I submitted a pull request for this : 
https://github.com/angular-ui/ng-grid/pull/3544

**Comment by swalters** [comment]
@PaulL1  https://github.com/angular-ui/ng-grid/commit/92477c7ad97f439582039b574baa2286f724d0ef should fix scenarios 1 and 2.

@willcodeforbeer can you check this commit against your PR?  I didn't see how your PR could address the bigger issue of grid not getting focus from other controls. thanks.

**Comment by PaulL1** [comment]
@swalters: it's better - scenario 2 is now fixed, with a small issue that it doesn't show the focus on the first cell, but shows it on the second once you use the arrow key.

Scenarios 1 and 3 still outstanding.

**Comment by swalters** [comment]
@willcodeforbeer's PR fixed issue #1.  A commit I just made fixed #3
