### ISSUE TITLE
Could you help add Japanese language support?

### ISSUE THREAD

**Issue by kevinsong1990** [angular-ui/ng-grid#3530]
Hi

I found in the ui-grid.js file, i18nService doesn't support Japanese language. From its code, I can see it support 'da', 'de', 'en', 'es' and so on, but no Japanese.

**Could you add Japanese support?**

Here is da language support code attached below,

```javascript

$delegate.add('da', {
        aggregate:{
          label: 'artikler'
        },
        groupPanel:{
          description: 'Grupér rækker udfra en kolonne ved at trække dens overskift hertil.'
        },
        search:{
          placeholder: 'Søg...',
          showingItems: 'Viste rækker:',
          selectedItems: 'Valgte rækker:',
          totalItems: 'Rækker totalt:',
          size: 'Side størrelse:',
          first: 'Første side',
          next: 'Næste side',
          previous: 'Forrige side',
          last: 'Sidste side'
        },
        menu:{
          text: 'Vælg kolonner:'
        },
        column: {
          hide: 'Skjul kolonne'
        },
        aggregation: {
          count: 'samlede rækker: ',
          sum: 'smalede: ',
          avg: 'gns: ',
          min: 'min: ',
          max: 'max: '
        },
        gridMenu: {
          columns: 'Columns:',
          importerTitle: 'Import file',
          exporterAllAsCsv: 'Export all data as csv',
          exporterVisibleAsCsv: 'Export visible data as csv',
          exporterSelectedAsCsv: 'Export selected data as csv',
          exporterAllAsPdf: 'Export all data as pdf',
          exporterVisibleAsPdf: 'Export visible data as pdf',
          exporterSelectedAsPdf: 'Export selected data as pdf'
        },
        importer: {
          noHeaders: 'Column names were unable to be derived, does the file have a header?',
          noObjects: 'Objects were not able to be derived, was there data in the file other than headers?',
          invalidCsv: 'File was unable to be processed, is it valid CSV?',
          invalidJson: 'File was unable to be processed, is it valid Json?',
          jsonNotArray: 'Imported json file must contain an array, aborting.'
        }
      });

```

**Comment by PaulL1** [comment]
We'd happily accept a pull request that provides japanese translations.  I'm not sure anyone on the team knows any japanese, but if you can provide the pull request, we'll review and merge it.

**Comment by kevinsong1990** [comment]
Okay, I'll give a pull request that provides japanese translation later:-)

Thanks for your reply.

**Comment by kevinsong1990** [comment]
Hi PaulL1

I found you already support ja in ng-grid/src/js/i18n/ja.js, so I think I don't need to support Japanese.

But I have a question,

I download the code from "https://github.com/angular-ui/ui-grid.info", its ui-grid.js(version 3.0) still doesn't support Japanese,

**Do you help plan to update ui-grid? or already moved to ng-grid?** Thanks very much

**Comment by kevinsong1990** [comment]
And btw, I have Japanese friends. They can help to do the translation in the future.

If you want help about Japanese, you can contact me:-）

**Comment by PaulL1** [comment]
It appears to be in unstable, if you view http://ui-grid.info/release/ui-grid-unstable.js and search for `'ja'` it is there.  So nothing to do I guess.  Thanks.
