### ISSUE TITLE
remove sorting icons

### ISSUE THREAD

**Issue by qitang** [angular-ui/ng-grid#3533]
Hi is there a way that I can remove the sorting icons and make it sort only when user click on the column header?

**Comment by PaulL1** [comment]
Yes, you would use a custom `headerCellTemplate`.

**Comment by qitang** [comment]
thank you for you response! But how can I create headerCellTemplate that still can take advantage of the built-in filter feature? Can u give me example?

**Comment by qitang** [comment]
I was able to figure that out with the cell template from the source. Thank you!
