### ISSUE TITLE
Grid footer with custom template not resolving scope value.

### ISSUE THREAD

**Issue by settysreekanth** [angular-ui/ng-grid#3534]
Here is the plunker for grid using custom footer template, however scope value within the template is not getting resolved. 

If you see this plunker, footer label "Footer Testing:" appears however value after that is not getting resolved.

http://plnkr.co/edit/XQdHkkBjPIGkxXhrnnem?p=preview

**Comment by settysreekanth** [comment]
@PaulL1 @c0bra Could you please help me as this is showstopper for some implementation.

**Comment by PaulL1** [comment]
This is another variant of the appScope question.  Resolution: http://plnkr.co/edit/4eHt5mmykX8sac297zJF?p=preview, documentation: http://ui-grid.info/docs/#/tutorial/305_appScope

**Comment by settysreekanth** [comment]
@PaulL1 Honestly - I just figured it out and logged into github to close this issue; same time I see your response - Thanks for your quick response.
