### ISSUE TITLE
Duplicate footerTemplate on ui-grid 3.0-RC21

### ISSUE THREAD

**Issue by Ginwu** [angular-ui/ng-grid#3535]
Hi,
I found this closed issue #1956, but it's still duplicate when selection functionality is activated. 
Here's a plunker with the bug:

http://plnkr.co/edit/AX7eKu4S54FqiJzCk00H?p=preview

**Comment by Ginwu** [comment]
Any news ?

**Comment by PaulL1** [comment]
It's showing once per render container, which is expected behaviour.  If you want the template to only show on the body render container, then you'd need to write some specific code to achieve that.

Something like: http://plnkr.co/edit/FPQonUnkpZgxsdsxXefl?p=preview

**Comment by Ginwu** [comment]
Okay, sorry for the misunderstanding of this behaviour.
Your hack is working fine for me, thanks!
