### ISSUE TITLE
columns do not honor minWidth during resize

### ISSUE THREAD

**Issue by meyerds** [angular-ui/ng-grid#3539]
Resize any column (for example the Age column on the ui-grid.info homepage) to a "negative width" - drag the right column border further left than the left column border. Observe rendering issues both on the resized column header and on the data rows. (visible in v3.0.0-rc21)

**Comment by PaulL1** [comment]
Looks like the issue is that it was checking col.colDef.minWidth, rather than col.minWidth.  So if you didn't set a minWidth it wasn't picking up the default, and therefore allowing negative col widths.  Fixed.
