### ISSUE TITLE
double curly braces not working in cellTemplate

### ISSUE THREAD

**Issue by avatarr** [angular-ui/ng-grid#3546]
Hello I'm newby in Angular and NgGrid ,

I would like to access data in {{}} is seem like not working cellTemplate 
I have a data like this 

var mockup = 
  [   {  
    'date':'28/02/2558',
    'name':'Test Object',
    'action':{  
      'edit':'active',
}
}
]

and set data to grid 
$scope.gridOptions.data = mockup;

in columnDefs I setup cellTemplate like this 

http://pastebin.com/sVmEDsvS

but {{gridOptions.data[0].action.edit}} not work ,

How can I Fix this issues   

Best regards.

Pratchaya

**Comment by PaulL1** [comment]
Normally you'd access things in cellTemplates through one of two ways:

1.  `row.entity.attribute` - use when the thing you want to access was set into your data.  I think this is what you want to do.
2.  `grid.appScope.method()` - use when you set a method or attribute on the $scope from which the grid is called.  Refer the tutorial on accessing scope in templates.

**Comment by avatarr** [comment]
Thank you, you save me :+1:
