### ISSUE TITLE
Not able to sort Date column in UIGRID

### ISSUE THREAD

**Issue by shrameec** [angular-ui/ng-grid#3547]
Please suggest:
This is the date format in our column:lastChangeTimestamp":"20-May-2015 15:27:26 and I am  not able to sort the same even after converting it to the date format.

 for(i = 0; i < data.length; i++){
				data[i].lastChangeTimestamp = Date(data[i].lastChangeTimestamp);
				 }
{ name: 'lastChangeTimestamp', enableCellEdit: false, enableColumnMenu: false,width: '20%', displayName: 'Date Modified' , type: 'date',cellFilter: 'date:"yyyy-MM-dd hh:mm:ss"', filter: {
			   condition: $scope.gridRSVModel.searchItem}
},

Receiving  error in console:

Error: a.getTime is not a function sortDate@file:///C:/DevTools/TestInteli/managementserver/resources/msGUI/app/bower_components/angular-ui-grid/ui-grid.js:9205:11 rowSorterSort/rowSortFn@file:///C:/DevTools/TestInteli/managementserver/resources/msGUI/app/bower_components/angular-ui-grid/ui-grid.js:9415:9 rowSorterSort@file:///C:/DevTools/TestInteli/managementserver/resources/msGUI/app/bower_components/angular-ui-grid/ui-grid.js:9436:9 sortByColumn@file:///C:/DevTools/TestInteli/managementserver/resources/msGUI/app/bower_components/angular-ui-grid/ui-grid.js:4833:5 startProcessor@file:///C:/DevTools/TestInteli/managementserver/resources/msGUI/app/bower_components/angular-ui-grid/ui-grid.js:4324:7 handleProcessedRows@file:///C:/DevTools/TestInteli/managementserver/resources/msGUI/app/bower_components/angular-ui-grid/ui-grid.js:4340:13 processQueue@file:///C:/DevTools/TestInteli/managementserver/resources/msGUI/app/bower_components/angular/angular.js:13248:11 scheduleProcessQueue/<@file:///C:/DevTools/TestInteli/managementserver/resources/msGUI/app/bower_components/angular/angular.js:13264:27 $RootScopeProvider/this.$get</Scope.prototype.$eval@file:///C:/DevTools/TestInteli/managementserver/resources/msGUI/app/bower_components/angular/angular.js:14466:9 $RootScopeProvider/this.$get</Scope.prototype.$digest@file:///C:/DevTools/TestInteli/managementserver/resources/msGUI/app/bower_components/angular/angular.js:14282:15 $RootScopeProvider/this.$get</Scope.prototype.$apply@file:///C:/DevTools/TestInteli/managementserver/resources/msGUI/app/bower_components/angular/angular.js:14571:13 timeout/timeoutId<@file:///C:/DevTools/TestInteli/managementserver/resources/msGUI/app/bower_components/angular/angular.js:16308:25 completeOutstandingRequest@file:///C:/DevTools/TestInteli/managementserver/resources/msGUI/app/bower_components/angular/angular.js:4924:7 Browser/self.defer/timeoutId<@file:///C:/DevTools/TestInteli/managementserver/resources/msGUI/app/bower_components/angular/angular.js:5312:7

**Comment by PaulL1** [comment]
The code looks right.  I suspect there's something else going on - any chance of a plunker?

**Comment by shrameec** [comment]
data[i].lastChangeTimestamp = Date(data[i].lastChangeTimestamp);
data[i].lastChangeTimestamp =Fri May 22 2015 09:50:51 GMT+0530 (India
Standard Time)

The Date is getting converted to this format,so probably that is why Grid
is unable to sort the same.
The UI-Grid can sort this format?

On Fri, May 22, 2015 at 12:27 AM, Paul <notifications@github.com> wrote:

> The code looks right. I suspect there's something else going on - any
> chance of a plunker?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular-ui/ng-grid/issues/3547#issuecomment-104388732>
> .
>



-- 
Thanks,
Shramee

Please don't print this e-mail unless you really need to.

**Comment by PaulL1** [comment]
No, when you console.log a timestamp it calls .toString() on the date object, and the format you show is the international format for timestamps.  That looks correct.  I think a plunker is necessary to debug this.

**Comment by shrameec** [comment]
I will send the plunker soon.

**Comment by shrameec** [comment]
http://plnkr.co/edit/eas5mPb7Yd9phHEazs0D?p=preview
I am unable to sort on the "lastChangeTimestamp" column of the Grid. How can we do the same?

**Comment by PaulL1** [comment]
http://plnkr.co/edit/sMUKEgFObc4mRuQrsPJu?p=preview

Your data was not dates, it was strings that could be converted into a date.  In order to sort dates your data needs to include a javascript date object.

**Comment by shrameec** [comment]
I just mentioned the way my data is and asked what all changes I need in this code to get my requirement implemented.

As mentioned in very beginning I had added below code  to my js

for(i = 0; i < data.length; i++){
data[i].lastChangeTimestamp = Date(data[i].lastChangeTimestamp);

and this was returning date of below format and then UI-Grid is unable to sort the data on the complete grid:

data[i].lastChangeTimestamp = Date(data[i].lastChangeTimestamp);
data[i].lastChangeTimestamp =Fri May 22 2015 09:50:51 GMT+0530 (India
Standard Time) 

I have updated the plunker also with the same.
http://plnkr.co/edit/eas5mPb7Yd9phHEazs0D?p=preview
Please check now.
