### ISSUE TITLE
Word wrap issue in UI-GRID column

### ISSUE THREAD

**Issue by shrameec** [angular-ui/ng-grid#3548]
Is there no relative way of wrapping the text of a column.
rowHeight: 70 gives a fixed height to row.
rowHeight: 100% doesn't work.
Please suggest!

**Comment by PaulL1** [comment]
You cannot have dynamic heights to the rows (refer the FAQ).  Either all rows are taller, or all rows are not.

**Comment by c0bra** [comment]
No response in > 2 weeks. Closing.
