### ISSUE TITLE
Sort stops responding

### ISSUE THREAD

**Issue by deepfriedbrain** [angular-ui/ng-grid#3549]
I'm using the UI Grid on a few different pages (partials) of my application, which get loaded using UI Router. I noticed that after a few mins of working with the application, the sort feature on all the grids on all the pages stops responding completely. Even after refreshing the browser, the sort doesn't work.   There's absolutely no error in the browser console. The only way to make it work is to launch a new tab. Then it goes back to normal for a while. This happens on the Chrome 42x.

The other features like menus, column pinning, column hiding work fine even when the sorting stops responding. 

Is it a known issue? Can I do something to prevent this behavior? Thanks.

**Comment by PaulL1** [comment]
What version?  There was a watchers problem on one of the bits of functionality - maybe sorting - in about rc18 or 19, I think fixed in 21.  Is that possibly the problem?

**Comment by deepfriedbrain** [comment]
I was using the latest unstable version.

**Comment by PaulL1** [comment]
There is a defect on column move where Chrome interprets the click as a column move instead of a sort if you move the mouse even slightly.  #3333

**Comment by deepfriedbrain** [comment]
Yes, it seems to be the same issue.
