### ISSUE TITLE
Can cellFilter pass the controller scope?

### ISSUE THREAD

**Issue by yaring** [angular-ui/ng-grid#3550]
Hi,

I've the definition of the grid on the controller scope:
```js
$scope.users = { 1: 'User1', 2: 'User2'};
$scope.gridOptions = {
    columnDefs: [
        { field: 'user_id', displayName: 'User Name', cellFilter: 'usersFilter:this' },
    ]
};
```
I also have some data store on the scope `$scope.users`.
Is it possible to pass the `$scope.users` variable to the filter?
The only thing I did is to pass `this` but that gave my the inner grid scope which is not the controller scope.

**Update:** 
I managed to get the `$scope.users` by doing
```js
{ field: 'user_id', displayName: 'User Name', cellFilter: 'usersFilter:$parent.$parent.$parent.$parent.$parent.$parent.$parent.users' }
```
**BUT** this looks ugly as hell, can someone suggest something better?

Thanks!

**Comment by therealtomas** [comment]
appScope is available at http://ui-grid.info/docs/#/tutorial/305_appScope , so grid.appScope.users if you $scope.$parent if you need another assign with gridOptions.appScopeProvider. Surely you can pass data to a filter if writing a custom filter.

**Comment by yaring** [comment]
Awesome! Thanks!

**Comment by PaulL1** [comment]
Looks resolved, closing.
