### ISSUE TITLE
CellTemplate ui-router links and pagination issue

### ISSUE THREAD

**Issue by esukf** [angular-ui/ng-grid#3551]
I'm using cellTemplate in order to create links on the grid. I am also using ui-router for the project so the link are generated using the ui-sref directive.

As per the Plunkr example below, the first page works fine but when you paginate to the second page the url remains the same as those on the first page. Inspecting the ui-sref value in the source, it is correct but it doesn't appear to update the href. Has anyone else come across this and know of a solution? This behaviour happens for infinite scoll.

http://plnkr.co/edit/MoOPiO8aevkMJU2OlMir?p=preview

**Comment by esukf** [comment]
As per https://github.com/angular-ui/ng-grid/issues/559 the workaround is to create the href directly and generate the url using a grid.appScope function.

http://plnkr.co/edit/F7XDdM6kBwcqkqO6Hh7N?p=preview

**Comment by PaulL1** [comment]
Looks resolved, closing.
