### ISSUE TITLE
multiselect and rowSelection

### ISSUE THREAD

**Issue by leonardorame** [angular-ui/ng-grid#3553]
Hi, I have a grid with multiselect enabled and enableRowHeaderSelection. That allows selecting rows by checking the checkbox on the right side. 

Now I want to let the user click on any row, then execute an action. But when I'm in multiselect mode I cannot select rows.

**Comment by PaulL1** [comment]
Is it that you want the user to be able to select the row by clicking on it (not just by clicking on the rowHeader), or is it that you want some action to happen when they click on the row?

**Comment by leonardorame** [comment]
Hi PauL1, I already can trigger an action when the user clicks on the checkmark. What I don't know how to is to display the selected row when in multiselect mode.

**Comment by PaulL1** [comment]
Sorry, still not clear.  It sounds like you want the row to be selected when you click on it?  I'm not clear what multi-select mode has to do with your problem?

Could you perhaps write a little more, describe the steps you expect the user to take (what they're clicking on), and what you expect your application to do when that happens, and finally what it does today when they do those actions?

**Comment by leonardorame** [comment]
Let me try to clarify it. On grids with multiselect=false, the user can click on any row and the row becomes highlighted, ok, then, if I add the multiselect and enableRowHeaderSelection, rows aren't highlighted anymore when the user clicks on them, but he can click on the checkboxes right hand.

**Comment by leonardorame** [comment]
BTW, the problem is related to enableRowHeaderSelection and not multiselect. When enableRowHeaderSelection is true, the only way I can select a row is by clicking on the checkbox, but I would like to be able to select it by clicking on any cell of the row.

**Comment by leonardorame** [comment]
For an example, please see the first grid of this page: http://ui-grid.info/docs/#/tutorial/210_selection

When you click on "Nieves Mack" the row is not selected (why?), but you can click on the check mark at the far right of the same row, an then the row is selected.

**Comment by PaulL1** [comment]
OK, so in that case this is a duplicate.  At present when you turn on row header selection it turns off being able to select anywhere on the row.  This can be changed, and is an open item #2254
