### ISSUE TITLE
Default text filtering should be case insensitive and "full-text"

### ISSUE THREAD

**Issue by njenia** [angular-ui/ng-grid#3559]
The default behavior for filtering is to find fields that has prefixes matching *exactly* the filter. I think it's not very intuitive, and should be changed to a more loose form of filtering, being case insensitive and looking for not only a prefix (basically, wrapping the filter term with two *).
What do you think?

**Comment by salarmehr** [comment]
+1

**Comment by JLLeitschuh** [comment]
I agree that this would make more sense. All existing angular filters are implemented in this way.

**Comment by pradapkumar** [comment]
The Single filter is case sensitive. I tried using this and its returning only if search as if in the data
Eg : Data has text as : Grid Data, the user has to search "Grid Data" if the user Search is "grid " it return null data. Please let me know If i need to add any specific thing I refered - 
http://ui-grid.info/docs/#/tutorial/321_singleFilter

**Comment by Hellmy** [comment]
You should propably also adapt the documentation and I'm currently not sure if there is also something in other ways than it should be because of the old STARTS_WITH and now CONTAINS.
 ```
   * Defaults to STARTS_WITH. Uses CONTAINS for strings beginning and ending with *s (*bob*).
   * Uses STARTS_WITH for strings ending with * (bo*). Uses ENDS_WITH for strings starting with * (*ob).
   * @param {object} filter object to use
   * @returns {uiGridConstants.filter<int>} Value representing the condition constant value
```
