### ISSUE TITLE
localization

### ISSUE THREAD

**Issue by wormen** [angular-ui/ng-grid#3561]
tell me how I can use the location, relative to your unit? eg I'm interested in the object
`
pagination: { sizes: 'items per page', totalItems: 'items'  }
`
How do I access it?

**Comment by PaulL1** [comment]
Take a look at http://ui-grid.info/docs/#/tutorial/104_i18n

**Comment by wormen** [comment]
localization in general is good, but my question you did not answer

**Comment by wormen** [comment]
how to change this value https://yadi.sk/i/f_tEhVxLgoiia
an example of an object above

**Comment by totszwai** [comment]
i am facing the same issue... the tutorial doesn't address the topic clearly.

**Comment by PaulL1** [comment]
I think you're referring to the 2.x grid?  If so, then I'm not familiar with that code base.

**Comment by wormen** [comment]
no 3.x

**Comment by PaulL1** [comment]
I think in 3.x the text is "page x of y", and there is an existing defect open on the fact that the "of" isn't being handled by i18n.
