### ISSUE TITLE
need to put the local scope in to a angular uigrid cell template

### ISSUE THREAD

**Issue by kirangsa** [angular-ui/ng-grid#3567]
Hi Guys,

i have a local scope $scope.edit="Edit btn";

i need to put the local scope in to a angular uigrid cell template. How could be it possible ?

cellTemplate: '<button id="editBtn" type="button" class="btn-small edit-btn" ng-click="grid.appScope.editeUser(row.entity)" >{{edit}}</button>

**Comment by PaulL1** [comment]
http://ui-grid.info/docs/#/tutorial/305_appScope

**Comment by kirangsa** [comment]
Thanks Paul.

You save my day :+1:
