### ISSUE TITLE
[Grouping] treeRowHeaderAlwaysVisible not working as expected

### ISSUE THREAD

**Issue by AgDude** [angular-ui/ng-grid#3572]
My expectation with this option is that when set to ```false```,  the "plus" column will be removed/added based on whether or not grouping is active. This does not appear to be working.

**Comment by AgDude** [comment]
@PaulL1  I have been working a bit on this. The core problem is solved by resetting ```grid.treeBase.numberLevels``` to 0 at the beginning of the ```createTree``` method. But then we run into the problem that we are considering a single grouping to have 0 ```numberLevels```, which is also the default without any grouping.

I am going to change this so ```numLevels``` becomes 1 if there is a single grouped column. Alternatively we could make it ```undefined``` if there are no grouped columns.

**Comment by PaulL1** [comment]
Sounds reasonable.  I don't think I did it deliberately, I recall noticing it had ended up zero based then just going with it.
