### ISSUE TITLE
Unicode BOM in exported CSV

### ISSUE THREAD

**Issue by iravanchi** [angular-ui/ng-grid#3575]
In `downloadFile` function in the CSV exported, BOM is being added in the "IE10+" case, but it is not added otherwise (specifically, the "html5 a[download]" case). This results in CSV files generated from Chrome or Firefox to show invalid Unicode characters (for example, in Excel).

I'm not sure this is right way to go, but I managed to fix it by adding the same character `\ufeff` in the `Blob` generated in this case too.

**Comment by PaulL1** [comment]
I'm trying to recall.  I seem to recall it gave spare characters on the front of the file when imported into Excel, and that's why it was removed.  I'll try to recreate and check.

**Comment by PaulL1** [comment]
OK, what version are you on?  The current master has:

```
          ieVersion = this.isIE();
          if (ieVersion && ieVersion < 10) {
            var frame = D.createElement('iframe');
            document.body.appendChild(frame);
        
            frame.contentWindow.document.open("text/html", "replace");
            frame.contentWindow.document.write('sep=,\r\n' + csvContent);
            frame.contentWindow.document.close();
            frame.contentWindow.focus();
            frame.contentWindow.document.execCommand('SaveAs', true, fileName);
        
            document.body.removeChild(frame);
            return true;
          }
        
          // IE10+
          if (navigator.msSaveBlob) {
            return navigator.msSaveBlob(
              new Blob(
                [exporterOlderExcelCompatibility ? "\uFEFF" : '', csvContent],
                { type: strMimeType } ),
              fileName
            );
          }
      
          //html5 A[download]
          if ('download' in a) {
            var blob = new Blob(
              [exporterOlderExcelCompatibility ? "\uFEFF" : '', csvContent], 
              { type: strMimeType }
            );
            rawFile = URL.createObjectURL(blob);
            a.setAttribute('download', fileName);
          } else {
            rawFile = 'data:' + strMimeType + ',' + encodeURIComponent(csvContent);
            a.setAttribute('target', '_blank');
          }
```

It looks like both options include the \ufeff, unless you've set the olderExcelCompatibility flag.  Perhaps you need to upgrade to get this code?

**Comment by iravanchi** [comment]
You're right. I'm on rc.20. I need to upgrade.
Sorry for the inaccurate reporting of the issue.

Althou, may I suggest iterating "RC" releases faster. The reason I didn't upgrade was that I saw the current in-development version is rc.21, and I wanted to keep using a "somewhat-stable" rc.20 release.  Now I realize that I was wrong, and rc.21, despite being in development, might be more stable.

**Comment by PaulL1** [comment]
Thanks, closing.

We typically iterate reasonably fast, but we keep thinking we're nearly at 3.0, and so we hold off the next one in the hopes that the next one will be the 3.0 final release.  But we're close to the point where we should think about a new RC, there are some major bug fixes that went in the last few days.  Perhaps after the next round of grouping changes comes in from @AgDude
