### ISSUE TITLE
Grouping Grid Row Content Layout Changed in Latest Version.

### ISSUE THREAD

**Issue by debayan31** [angular-ui/ng-grid#3577]
In previous version we got column value through "row.entity.<column Name>".

If I was trying to get out the headers, my code would be something like:

  var headers = [];
  $scope.gridApi.grid.renderContainers.body.visibleRowsCache.forEach( function( row, index ) {
    if( row.groupHeader ) {
      headers.push ( { label: row.entity.field1, value: row.entity.field2 } );
    }
  });
I'm assuming here that field1 is the field I am  grouping by, and field2 the field I am aggregating by.

But while debugging with latest version I found that within row.entity column name is not there. So how can I got rendered column value?  <Inside entity object structure is something like $$uiGrid-00G: Object, $$uiGrid-00D: Object>

 Find screenshot for reference.

![chart view](https://cloud.githubusercontent.com/assets/11749797/7796912/5b87a798-0302-11e5-930c-868c74281137.jpg)

**Comment by PaulL1** [comment]
This is described in the updated tutorial (there are now two tutorials - simple and complex, one of them includes an example of this) and the updated api documentation.

**Comment by debayan31** [comment]
PauL,

In Tutorial <http://ui-grid.info/docs/#/tutorial/209_grouping> I found that there is a function named "getAggregates" in not working correctly as because inside Line no --> 51 <app.js> is not exacuting.
