### ISSUE TITLE
Grid layout is completely broken when column is pinned to left and some columns have multiple filters

### ISSUE THREAD

**Issue by dimetrym** [angular-ui/ng-grid#3579]
* ui-grid - v3.0.0-rc.21-9a83f34 - 2015-05-23

Platform: Windows 7
Browsers: Chrome  43.0.2357.65, IE 11.0.9600.17801 

Notes:
1) Column "Order Id" is pinned to left.
2) The rest of the columns have enablePinning: false.

Open demo page and try to scroll grid horizontally by dragging scroll bar.

![image](https://cloud.githubusercontent.com/assets/7129551/7799725/6de217d8-0312-11e5-9c2c-7dd58c5d1427.png)
.
View demo: 
http://plnkr.co/edit/pcFZSYYAiDl1ldjJsl7U?p=preview

Thank you!

**Comment by dimetrym** [comment]
this bug appears after  * ui-grid - v3.0.0-rc.21 - 2015-04-28

**Comment by c0bra** [comment]
@dimetrym I'm not seeing the behavior in your plunker. Perhaps it was fixed recently?  Could you check again?

**Comment by dimetrym** [comment]
it is fixed now. Thanks!
