### ISSUE TITLE
group rowHeader unexpectedly disappears

### ISSUE THREAD

**Issue by AgDude** [angular-ui/ng-grid#3580]
This plunker is based on the complex grouping tutorial:
http://plnkr.co/edit/3lAuYzzGBwaQ3PJRSvh8?p=preview

I have disabled the custom columnsProcessor in the plunker. Now when I expand a group the expand button column is hidden. If I enable to columnsProcessor (event with all of the functionality disabled), the problem goes away.

**Comment by PaulL1** [comment]
If we change `treeRowHeaderAlwaysVisible` to true, then the problem goes away.  But that isn't really what we want.

If we take the simple tutorial, and set `treeRowHeaderAlwaysVisible` to false, then the problem arrives: http://plnkr.co/edit/FHKMyWSZC530QVRNgz2T?p=preview

**Comment by AgDude** [comment]
This is still a problem. On the 209 tutorial, remove grouping on both grouped columns, then group by "state".
