### ISSUE TITLE
Complex Tree Tutorial Example Broken?

### ISSUE THREAD

**Issue by dereklin** [angular-ui/ng-grid#3583]
I was checking the complex tree tutorial example: http://ui-grid.info/docs/#/tutorial/319_complex_trees
When I expand Mcclain Pope and then collapse it, Morse Mendoza becomes unexpandable.  There was some thing odd about expanding Mcclain Pope the first time.  I think there is some kind of positional/index issue.

**Comment by PaulL1** [comment]
Are you sure this isn't the same alignment issue we've had for a while: #3394.

**Comment by dereklin** [comment]
It's different.

**Comment by dereklin** [comment]
Actually, you might be right... Sorry...
