### ISSUE TITLE
SaveState Addition

### ISSUE THREAD

**Issue by johnstontrav** [angular-ui/ng-grid#3585]
suggest to add to saveState -> saveColumns

```
savedColumn.displayName = column.displayName;
```

This help to reconstruct grid.

**Comment by PaulL1** [comment]
In general the saveState feature aims to save state that the user can directly influence.  Can the user change the displayName in your grid?

**Comment by johnstontrav** [comment]
Hi Paul, whilst writing a detailed response to you, I have found another way.  thanks.

**Comment by c0bra** [comment]
Glad you found a solution!
