### ISSUE TITLE
http://ui-grid.info/ Site is down

### ISSUE THREAD

**Issue by talasila66** [angular-ui/ng-grid#3586]
http://ui-grid.info/ Site is down can you please look into it?

**Comment by talasila66** [comment]
http://ui-grid.info/ Site is down can you please look into it?

**Comment by talasila66** [comment]
Site is working currently

**Comment by msareen** [comment]
http://ui-grid.info/ is down again. Please look into it.

**Comment by ewahner** [comment]
Yes site is throwing a dns error.

**Comment by art-grig** [comment]
+1 site is down =(

**Comment by GravesDevelopment** [comment]
The site is down...

**Comment by rschoessler** [comment]
+1 site is down - ui-grid.info doesn't resolve DNS

**Comment by ashwin9977** [comment]
The site is down. DNS not resolved.

**Comment by tanvi-inttra** [comment]
+1 site is down - ui-grid.info doesn't resolve DNS

**Comment by Bodmoor** [comment]
+1 same here, site is down

**Comment by ganeshvelanki** [comment]
site is down from 24 hrs i think.

**Comment by asmrussel** [comment]
when the server will up again?

**Comment by subhayanbanerjee** [comment]
Any ETA when the server will be up? Please respond.

**Comment by mattbrunetti** [comment]
See #6162
