### ISSUE TITLE
How to achieve treegrid functionality in ui-grid?

### ISSUE THREAD

**Issue by talasila66** [angular-ui/ng-grid#3587]
How to achieve treegrid functionality in ui-grid?

I am having parent node with different no of children.

**Comment by PaulL1** [comment]
Try the tree tutorial?

**Comment by talasila66** [comment]
Thank you Tried the tree tutorial, but a small doubt, how to tell the a node as a leaf node at any level?

**Comment by talasila66** [comment]
Need to Use showTreeExpandNoChildren
