### ISSUE TITLE
EnableFiltering: false just for some columns messes up the cell

### ISSUE THREAD

**Issue by SalasSanchez** [angular-ui/ng-grid#3592]
I'm using  ui-grid - v3.0.0-rc.21 - 2015-04-28

I have made the background of the header dark, by adding the css:

```javascript
.ui-grid-header-cell .sortable {
    background:#3E3E3E;
}
```

I have enabled filtering in all columns but one (which also has a string of spaces for the name because I didn't want a name displayed, not ideal, but it works). The filtering capability disappears, but I get a white box on the cell, instead of being dark like the rest of the cell.

```javascript
$scope.gridOptions = {
        data: 'data',
        enableColResize: true,
        enableSorting: true,
        enableCellEdit: false,
        enableFiltering: true
    };

$scope.gridOptions.columnDefs= [ {
    field: "subject",
    name: "Subject",
}, {
    name: "   ",
    enableFiltering: false
}, {
    field: "id",
    name: "Id",
}];
```

A similar thing happens when I set enableSorting: false, the top portion of the cell goes white, ignoring the modifications i made to the css. 

Not sure if I am doing something wrong, or how to solve this issue. Any help would be much appreciated. Thanks!

**Comment by c0bra** [comment]
@SalasSanchez Just a note: properly formatting your code when filing an issue really makes it about 1000x easier to read and understand.

I went ahead and edited this one for you but you can check out how to set up syntax coloring and so on here: https://guides.github.com/features/mastering-markdown/

Hope that helps!

**Comment by c0bra** [comment]
Also, would you be able to set up a quick plunker demonstrating the issue? All that it would need is the column header styles set up as you describe.

**Comment by SalasSanchez** [comment]
Good point, sorry about that. 

I am trying to reproduce the issue on plunker. Will update when/if I manage.

**Comment by SalasSanchez** [comment]
Ok, here we go. (First time doing this, so let me know if this link does not work for you)

http://plnkr.co/edit/wSNgs0cZvjmEoAI8wvwi?p=preview

**Comment by SalasSanchez** [comment]
If you uncomment the "enableFiltering: false" on the column defs you will see what i mean. Similar thing if you uncomment "enableSorting: false".

Thanks a lot!

**Comment by c0bra** [comment]
@SalasSanchez So do you just want the header to be dark?  Will this not work?

```javascript
.ui-grid-header-cell {
    background:#3E3E3E;
}
```

**Comment by SalasSanchez** [comment]
Hah. I could wear I had tried this. Ok, great. Thanks!
