### ISSUE TITLE
Expandable grid options

### ISSUE THREAD

**Issue by Curioasa** [angular-ui/ng-grid#3608]
Is there any option for enabling expandable behavior only on certain rows in the grid, depending on some value that you have in the data?
E.g.:
[{'name':'Thomas', 'expandable':false}, {'name':'Anna', 'expandable':true}, {'name':'George', 'expandable':true}]

In this case, Thomas should not have a plus sign and, thus, not be expandable, but Anna and George should.

**Comment by yccteam** [comment]
One way to go is not to create a custom template with an ng-hide on the expandable "+" sign.

**Comment by Curioasa** [comment]
This is not a good practice. Take a look at the following plunker:
http://plnkr.co/edit/9WAjMwvG5qXmVcgqZ4Es?p=preview

Although the plus signs are hidden for certain rows, it gives the impression that the ones with the plus signs are expanded. What is more, is there a way to get rid of the plus sign in the header?

**Comment by yccteam** [comment]
Check this out - http://plnkr.co/edit/SNv5d2hssg71g9XhhIPh?p=preview
Just a matter of "i" to make it look better... (I've edited the main.css file)
Does this makes better sense now?

**Comment by Curioasa** [comment]
It makes perfect sense :). Thank you very much for your help!

**Comment by yccteam** [comment]
Glad I could help :)
