### ISSUE TITLE
buttons broken in grouping example

### ISSUE THREAD

**Issue by SoundLogic** [angular-ui/ng-grid#3636]
buttons seem broken for the [grouping example](http://ui-grid.info/docs/#/tutorial/209_grouping), but nothing serious as actual functionality seems to be working fine

**Comment by PaulL1** [comment]
They are currently there for me (if we're talking about the grouping buttons - the expand and collapse).  What browser and OS, and have you done a cache refresh on your browser, do you have any console error logs that are saying something about fonts being blocked or not retrieved?

**Comment by AgDude** [comment]
I think he is talking about the buttons above the grid. I can confirm that most of them don't work on chrome for windows. I probably broke them recent changes to grouping.

**Comment by PaulL1** [comment]
Ah. No, I broke them when I moved from grouping to treeBase for most expand/collapse functions.  I'll fix.
