### ISSUE TITLE
Using gridObject not working with dynamically loaded html

### ISSUE THREAD

**Issue by billmcknight1953** [angular-ui/ng-grid#3645]
I have an app where I am  loading different grids dynamically using ng-include.  In the controller if I create a gridOptions object, and attempt to display the grid on the dynamically loaded html like this

```html
<div ui-grid="gridOptions" class="grid" ></div>
```
no data displays at all.

However, if I change the grid markup to this

```html
<div ui-grid="{ data: myData }" class="grid"></div>
```
The grid data displays perfectly.  Nothing displays even if my gridOptions object is as simple as this:

```javascript
$scope.gridOptions = { data: myData };
```

Has anyone tried using ui-grid with dynamically loaded markup?

**Comment by PaulL1** [comment]
It sounds like some flavour perhaps of hidden grid (refer hidden grid tutorial).  Does the data show if you resize the page and/or click the headers or other things that would cause a refresh to run?  If you put a button on the page with a method that calls grid.refresh, does that fix things?  Can you create a plunker of it?

**Comment by billmcknight1953** [comment]
I would like to withdraw my issue.  The problem was completely self-caused by something other than either ui-grid or dyanmically loaded html.
