### ISSUE TITLE
Default sorting with external sorting does not work

### ISSUE THREAD

**Issue by moguzalp** [angular-ui/ng-grid#3650]
In given plnkr while default sorting is set for name column, it puts down triangle icon but does not sort column

http://plnkr.co/edit/zVKk0kSLFdGvDQK1oivc?p=preview

**Comment by c0bra** [comment]
Looks like this is the same behavior on the tutorial currently: http://ui-grid.info/docs/#/tutorial/307_external_sorting

**Comment by PaulL1** [comment]
Isn't that exactly what we'd expect?  It visually shows the sorting, but expects you to apply that sorting externally?

**Comment by c0bra** [comment]
@PaulL1 I think what he's saying is that the external sorting is not being triggered by the grid on setup, for columns with a default sort.

@moguzalp Is that right?

**Comment by moguzalp** [comment]
Yes @c0bra. if as @PaulL1  said :"Isn't that exactly what we'd expect", then in tutorial there should be code that triggers sorting externally.

**Comment by PaulL1** [comment]
That tutorial I think used to not have a default sort, therefore it wasn't a problem.  Now that it has a default sort, then the function that we trigger on sortChanged should probably be being called upon grid initialisation.

**Comment by PaulL1** [comment]
Looking into it closer, actually the sort on the gender column was there just to demonstrate that it does nothing, and the tutorial words say that.  I've removed it to make it clearer that's what's happening, and I've updated the sortChanged function to make it clearer how you should implement this.
