### ISSUE TITLE
Warning Message When Using ui-grid

### ISSUE THREAD

**Issue by talasila66** [angular-ui/ng-grid#3662]
I am getting the following warning message, when using ui-grid. with latest angular js version(v1.4.0-rc.2).

"angular.js:12204 Unable to assign type from data, so defaulting to string"

Can you please look into this?

**Comment by dabedur** [comment]
You can avoid getting the warning message by assigning the data `type` manually in the gridOptions -columnDef config if you know what the type is supposed to be...

**Comment by c0bra** [comment]
Yea the warning comes out of the grid itself. It's failing to correctly guess the type of column based on the first row value and defaults to "string".

I'm not sure that there needs to be a warning message for this; am looking into it.

**Comment by askanhan** [comment]
the same with me! And As a cosequence, the characters in the default selection column are in Chinese! Also the menu "icon" in the right upper corner. Characters for sorting are OK.
 ui-grid - v3.0.0-rc.21-4746790 - 2015-06-10
angular- 1.3.15

**Comment by c0bra** [comment]
@askanhan Check this out: http://localhost:9003/docs/#/tutorial/116_fonts_and_installation
