### ISSUE TITLE
showTreeExpandNoChildren is not working as expected.

### ISSUE THREAD

**Issue by talasila66** [angular-ui/ng-grid#3663]
showTreeExpandNoChildren: defaults to true. Shows the + even if there are no children, allows you to dynamically load children. If set to false there'll be no + if there are no children

I changed the value of showTreeExpandNoChildren to false in my grid options, still the + symbol is coming if there is no children also.

$scope.gridOptions = {
enableSorting: true,
enableFiltering: true,
showTreeExpandNoChildren: true,
columnDefs: [{
name: 'name',
width: '30%'
}],
onRegisterApi: function(gridApi) {
$scope.gridApi = gridApi;

}
};

Using 3.0.0-rc.21 build which didn't contain code for showTreeExpandNoChildren.

Tried with also http://ui-grid.info/release/ui-grid-unstable.js which contains showTreeExpandNoChildren changes.

Can you please look into it?

**Comment by PaulL1** [comment]
http://ui-grid.info/docs/#/tutorial/215_treeView shows this, if you click the toggleExpandNoChildren button.

Is it also working for you?

**Comment by talasila66** [comment]
will share my code today

**Comment by talasila66** [comment]
showTreeExpandNoChildren: false, should be set to false

**Comment by shwetapurushe** [comment]
Im having the same issue mentioned as talasila66. Has this been fixed?
