### ISSUE TITLE
grid data refresh not working in IE11

### ISSUE THREAD

**Issue by Volvohorst** [angular-ui/ng-grid#3664]
I do a simple refresh on my grid with data loaded from remote resource.
FF and Chrome render correctly, IE11 does not.

What I basically do:
I use the row edit feature to edit properties of my data in default cellEditor.
I can save the data successfully. When I reload the data from remote resource, the incoming data array contains the changes (and is the same size since I did not add any new objects) but does not get rendered in grid - instead the grid shows the old value again.
Doing '$scope.gridOptions.data = data;' leads to CORRECT grid refresh in FF/Chrome, in IE11 it does NOT.
Strange behavior: I can get IE11 to render the change correctly just by activating the debugger console (and not doing anything else beyond that).

My code:

   $scope.refreshData = function() {

    $scope.gridOptions.data.length = 0;
    $scope.gridOptions.data = [];

    $http.get(someURL')
	    .success(function(data) {
		   $scope.gridOptions.data = data;
	    }).
	    error(function(data) {
		 // something
	    });;
   };

Using angular 1.3.15 / ui-grid 3.0.0 rc21

Any ideas? Thanks alot!

**Comment by Volvohorst** [comment]
Never mind - switched IE to always reload on request and now it works... stupid me.

**Comment by c0bra** [comment]
Glad you found the solution! :)

**Comment by NeelaSundaram** [comment]
Hi,

Could you pls explain how did you fix this. I am facing the same issue now.  Thanks in advance.

**Comment by valekar** [comment]
Hi,

I had been facing this from past 3 months but finally resolved it!

I just disabled the caching for get request in IE. I did this just adding this below code in your app config method.

And of course, I am refreshing the grid by getting new data by a get request after a post request.

`angular.module('common', []).config(['$httpProvider', function ($httpProvider) {
    if (!$httpProvider.defaults.headers.get) {
        $httpProvider.defaults.headers.get = {};
    }
    // because previous version of code introduced browser-related errors
    //disable IE ajax request caching
    $httpProvider.defaults.headers.get['If-Modified-Since'] = 'Mon, 26 Jul 1997 05:00:00 GMT';
    // extra
    $httpProvider.defaults.headers.get['Cache-Control'] = 'no-cache';
    $httpProvider.defaults.headers.get['Pragma'] = 'no-cache';
}]);`

Hope this helps for those who stumble upon this issue.

I referred this solution from the below link.

http://stackoverflow.com/questions/16098430/angular-ie-caching-issue-for-http

If you guys are still facing this issue then feel free to email me at srinivas.valekar@gmail.com. I am glad to help you guys. :)

**Comment by amarnathnn** [comment]
i have an issue with grid reload in IE 11. its working fine in  chrome and Firefox. below is by code. 

$(document).ready(function () {
    gridNotes = $("#gridNotes").grid({
        dataKey: "NotesId",
        uiLibrary: "bootstrap",
        dataSource: RootUrl + "CounterParty/GetNotes",
        columns: [
            { field: "NotesId", title: "Notes ID", sortable: true, hidden: true },
            { field: "Description", title: "Notes", width: 500, sortable: true },
            { field: "NoteFlag", title: "Need Report", width: 100},
            { field: "LastModifiedBy", title: "Last Modified By", width: 250, sortable: true },
            { field: "LastModifiedDate", title: "Last Modified Date", width: 200, type: 'date', format: 'mm/dd/yyyy', sortable: true },
            { title: "", field: "Edit", width: 34, type: "icon", icon: "glyphicon-pencil", tooltip: "Edit", events: { "click": EditNotes } },
            { title: "", field: "Delete", width: 34, type: "icon", icon: "glyphicon-remove", tooltip: "Delete", events: { "click": RemoveNotes } }
        ],
        pager: { enable: true, limit: 5, sizes: [2, 5, 10, 20] }
    });
    $("#btnAddNotes").on("click", AddNotes);
    $("#btnSaveNotes").on("click", SaveNotes);
    $("#btnSearchNotes").on("click", SearchNotes);
});
**HTML Code**
<table id="gridNotes" data-source="@Url.Action("GetNotes")"></table>
**JavaScript Code**
  $("#Name").autocomplete({
                minLength: 3,
                source: function (request, response) {
                    $.ajax({
                        url: RootUrl + "CounterParty/NameIndex",
                        type: "POST",
                        dataType: "json",
                        data: { Prefix: request.term },
                        success: function (data) {
                            ClearAllAlert();
                            var ifrm = document.getElementById('ifrmid').contentWindow.document.getElementById('empChart');

                            if (ifrm != null) {
                                ifrm.style.display = "none";
                            }

                            response($.map(data, function (item) {

                                return { label: item.Name, value: item.Id };
                            }))
                        }
                    })
                },
                messages: {
                    noResults: "", results: ""
                },
                select: function (event, ui) {
                    var value = ui.item.value;
                    Loaddetails(value);
                    grid.reload();                   
                    gridNotes.reload();
                }
            });
