### ISSUE TITLE
[BUG] headerRowHeight isn't working

### ISSUE THREAD

**Issue by yccteam** [angular-ui/ng-grid#3665]
I've just tried playing with ```headerRowHeight ```, with no success - the height remains the same.
There's also no example for this in the tutorial, but it does appear in the documentation: http://ui-grid.info/docs/#/api/ui.grid.class:GridOptions
In addition, I'm checking ```showHeader``` - when checking ```headerRowHeight```, it stays 30 no matter what - even when I set ```showHeader``` to false (which is supposed to set ```headerRowHeight``` to 0...).
You can see the ```headerRowHeight ``` value in the console after clicking the toggle button. It's always 30.
Here's the plnkr:
http://plnkr.co/edit/CPzoOkEQ3VnK4oa6a5pA?p=preview

**Comment by c0bra** [comment]
@yccteam see #2822.  That section of the docs needs to be removed. Setting headerRowHeight in the grid options hasn't worked all the way back to RC.12.

You can set the header height by giving your header row cells a fixed height, as in this plunker: http://plnkr.co/edit/WqBAed2H4vELJwtdMlyM?p=preview  Does that make sense? I can add a tutorial for this, or update the custom header one with the needed info.

Also `showHeader` seems to work for me in your plunker. In the top grid it's `false` and the header does not show up.

**Comment by yccteam** [comment]
I see - 
Regarding ```showHeader``` - I was noting on the documentation error (it's also written in the code itself several times - https://github.com/angular-ui/ng-grid/search?utf8=%E2%9C%93&q=headerRowHeight&type=Code). 
In addition, in the docs it says that ```headerRowHeight``` would be set to 0 if ```showHeader``` is set to false (http://ui-grid.info/docs/#/api/ui.grid.class:GridOptions). 
Other than that it's working.

Regarding using css for the row height - fine by me :)

**Comment by c0bra** [comment]
With your plunker the header height is coming out as 0 when I click the "Toggle" button. Are you not seeing that?

**Comment by yccteam** [comment]
Strange...  It shows correctly now.
Must have looked at a different version when I did my test
Sorry about that.

**Comment by yccteam** [comment]
One more thing, if we're at it - when I set:
```#grid1 .ui-grid-header-cell {
  height: 0;
}```
It doesn't work. I'm trying to hide/show the header row dynamically using this method. Is there a different method for this?

**Comment by c0bra** [comment]
Hmm, the grid must resize the header to fit the contents somehow. Any value less than 30px gets reset to 30, looks like.

You could use `showHeader: false` for hiding the header and the CSS method for making it larger than normal, but that's kind of dissonant...

**Comment by yccteam** [comment]
Now I see where my problems stem from. I'm using an unstable version that's about a month old.  I see this method works fine: http://plnkr.co/edit/BDTschDHPCt88casKbHb?p=preview
