### ISSUE TITLE
try Date.Parse enhacement on edit cells.

### ISSUE THREAD

**Issue by raysuelzer** [angular-ui/ng-grid#3670]
I noticed another closed issue around editing cells with a "type" of date not working when the JSON of the date is encoded as a string.  Would it make sense to make an enhancement that would try to parse string representations of dates to javascript Date objects? 

Something like:

  { field: 'EventDate', displayName: 'Event Date', type: 'date', cellFilter: 'date:"MM/dd/yyyy"', stringToDate: true }?

Or is there a recommended way of getting JSON dates to be treated as Dates instead of strings?

Thanks
-Ray

**Comment by PaulL1** [comment]
The recommended way is the way we show in the tutorial - which is to explicitly parse your data in the way in.  We could write some code to attempt to detect that the string in a field is perhaps a date and might be able to be parsed as such, but it's quite a bit of code in the grid for something that is reasonably trivial for a user who knows their data is a date.

**Comment by PaulL1** [comment]
I think we merged this today - so closing.
