### ISSUE TITLE
Wiredep fails to inject ng-grid v3 into HTML file

### ISSUE THREAD

**Issue by joeskeen** [angular-ui/ng-grid#3673]
In order to inject script and CSS references into an HTML file, Wiredep needs to read the `main` property in the `bower.json` file which lists the files that should be injected.  Ng-grid v2.x did have a `main` property, so it works properly, but v3 has no `main` property.  
The workaround is that you have to manually add script/CSS references to your HTML file for ng-grid.  This should definitely be addressed before the v3.0 release.

_Sources
Wiredep: https://github.com/taptapship/wiredep#what-can-go-wrong
ng-grid v2: https://github.com/angular-ui/ng-grid/blob/v2.0.14/bower.json
ng-grid v3: https://github.com/angular-ui/ng-grid/blob/master/bower.json_

**Comment by PaulL1** [comment]
I've updated the bower file to conform.  I can't test it as I don't use wiredep. Looking at the link you provide my gut feel is that it's not going to work in the way that you hope, as wiredep doesn't appear to provide a way to include font files automatically, and those are also necessary.
