### ISSUE TITLE
enableCellEdit

### ISSUE THREAD

**Issue by liyatang** [angular-ui/ng-grid#3675]
see [here](http://ui-grid.info/docs/#/tutorial/205_row_editable)
In the souce, code like this "{name: 'gender'}"(app.js line:15)
whithout the config "enableCellEdit:true",but demo can edit ? 

This is not reasonable, the default value should be false?

**Comment by PaulL1** [comment]
I think it is reasonable, the default is that a cell isn't editable. If you include the ui.grid.edit feature, then we assume you want cells to be editable, and now the default is that all cells are editable.  If you don't want them editable then you can set editable as false on each individual column.

**Comment by liyatang** [comment]
3q.  
but, I don't think so.   I include ui.grid, just i will use it, doesn't mean I use it.
