### ISSUE TITLE
Mouse Wheel Scrolling does not work properly (the bug fix)

### ISSUE THREAD

**Issue by sergeyf12** [angular-ui/ng-grid#3676]
Hi,

I apologize in advance if the bug has been already reported and fixed.
Just in case here is the fix (line # 2394):

                          $elm.bind('wheel mousewheel DomMouseScroll MozMousePixelScroll', function (evt) {
                              // use wheelDeltaY

                              var newEvent = GridUtil.normalizeWheelEvent(evt);

                              var args = { target: $elm };
                              if (newEvent.deltaY !== 0) {
                                  var scrollYAmount = newEvent.deltaY * -120;

                                  // Get the scroll percentage
                                  var scrollYPercentage = (containerCtrl.viewport[0].scrollTop + scrollYAmount) / rowContainer.getVerticalScrollLength();

                                  // Keep scrollPercentage within the range 0-1.
                                  if (scrollYPercentage < 0) { scrollYPercentage = 0; }
                                  else if (scrollYPercentage > 1) { scrollYPercentage = 1; }

                                  args.y = { percentage: scrollYPercentage, pixels: scrollYAmount };

                                  // Let the parent container scroll if the grid is already at the top/bottom
                                  if (args.y.percentage !== 0 && args.y.percentage !== 1) {
                                      evt.preventDefault();
                                  }
                              }
                              if (newEvent.deltaX !== 0) {
                                  var scrollXAmount = newEvent.deltaX * -120;

                                  // Get the scroll percentage
                                  var scrollLeft = GridUtil.normalizeScrollLeft(containerCtrl.viewport);
                                  var scrollXPercentage = (scrollLeft + scrollXAmount) / (colContainer.getCanvasWidth() - colContainer.getViewportWidth());

                                  // Keep scrollPercentage within the range 0-1.
                                  if (scrollXPercentage < 0) { scrollXPercentage = 0; }
                                  else if (scrollXPercentage > 1) { scrollXPercentage = 1; }

                                  args.x = { percentage: scrollXPercentage, pixels: scrollXAmount };

                                  // Let the parent container scroll if the grid is already at the top/bottom
                                  if (args.x.percentage !== 0 && args.x.percentage !== 1) {
                                      evt.preventDefault();
                                  }
                              }

                              uiGridCtrl.fireScrollingEvent(args);
                          });

Thanks,
Sergey

**Comment by Jacquelin** [comment]
Hi,

Indeed the bug has been already reported #3340 
A pull request is open.

**Comment by sergeyf12** [comment]
Hi,

I use version v3.0.0-RC.18-d9b2314 - 2015-01-06

**Comment by PaulL1** [comment]
Closing as a duplicate.

**Comment by sergeyf12** [comment]
@PaulL1 : I think it's related to scrolling propagating to the parent. After I updated the version it's gone.

Thanks,
Sergey
