### ISSUE TITLE
[Grouping] Aggregation functions (Average, Sum....) not using locale for labels

### ISSUE THREAD

**Issue by valepu** [angular-ui/ng-grid#3688]
Since last release i have noticed that Aggregation functions use english labels on the rows where they are activated, this used to work in RC20. 
How to reproduce:
See this Plunker http://plnkr.co/edit/NPazbil7fCU39SgHviDf?p=preview locale is set to italian but i have tested portughese aswell, i can guess it happens for every language.
1. Open the menu for any column 
2. Click on "Raggruppa" (Italian for "Group")
3. Open the menu for another column
4. Click on "Agg: N. Elem." (Italian for "Agg: Count")
On each row it will show "total rows: XX" instead of "righe totali: XX"
This happens for all the aggregation functions

**Comment by PaulL1** [comment]
I think I've fixed this - I changed it so that the nativeAggregations weren't a static, but were recalculated every time they were used.  I think the labels were getting set before the i18n language had been specified.
