### ISSUE TITLE
ng-grid 2.x and angular 1.3.x - ueoe error when grouping is turned on

### ISSUE THREAD

**Issue by khaale** [angular-ui/ng-grid#3692]
Hi ng-grid maintainers!

Steps to reproduce (see http://plnkr.co/edit/nPdhno3nH82ttXuXhZDF?p=preview):
1. Use ng-grid 2.x and angular 1.3.x
2. Turn on grouping
Expected result: all should work fine
Actual result: `Error: [$parse:ueoe] http://errors.angularjs.org/1.3.14/$parse/ueoe?p0=row.entity.` on browser console.

Issue is caused by cell template formatting at: src/directives/ng-cell.js 
````javascript
var cellTemplate = $scope.col.cellTemplate.replace(COL_FIELD, 'row.entity.' + $scope.col.field);
````
Aggregation column has empty name, so we have `{{ row.entity. }}` in a final template. Looks like older version of angular were tolerate to such issues, but 1.3 has more strict validation and produces an error.

**Comment by PaulL1** [comment]
I don't believe ng-grid 2.x supports angular 1.3.  You may want to consider upgrading to ui-grid.

**Comment by JLLeitschuh** [comment]
Duplicate #3693
