### ISSUE TITLE
ng-grid Grouping throwing an error in console

### ISSUE THREAD

**Issue by harishr2222** [angular-ui/ng-grid#3693]
Hi Team,

I have used ng-grid 2.0.12, angularjs 1.3.8 and jquery 2.1.1, when i try to do ng-grid groupby , i am getting error like Error: [$parse:ueoe] Unexpected end of expression: row.entity., may i know ng-grid groupby supported verions of angularjs.

Regards,
harish

**Comment by PaulL1** [comment]
I don't believe that ng-grid supports angular 1.3.

**Comment by AmarJagtapDev** [comment]
hide this code in ng-grid.js - it add extra column when group is add.  
/moved out of above loops due to if no data initially, but has initial grouping, columns won't be added
        if(cols.length > 0) {
            for (var z = 0; z < groups.length; z++) {
                if (!cols[z].isAggCol && z <= maxDepth) {
                    cols.push(new ngColumn({
                        colDef: {
                            field: '',
                            width: 25,
                            sortable: false,
                            resizable: false,
                            headerCellTemplate: '<div class="ngAggHeader"></div>',
                            pinned: grid.config.pinSelectionCheckbox
                            
                        },
                        enablePinning: grid.config.enablePinning,
                        isAggCol: true,
                        headerRowHeight: grid.config.headerRowHeight
                        
                    }, $scope, grid, domUtilityService, $templateCache, $utils));
                }
            }
        }

**Comment by karolpyrek** [comment]
I know that this is quite old and actually only reference to ng-grid 2.x + angularJS 1.x and this repo is marked as obsolete but @AmarJagtapDev answer for me was useful.

Instead of removing this part of code

```
//moved out of above loops due to if no data initially, but has initial grouping, columns won't be added
if (cols.length > 0) {
    for (var z = 0; z < groups.length; z++) {
        if (!cols[z].isAggCol && z <= maxDepth) {
            cols.splice(0, 0, new ngColumn({
                colDef: {
                    field: '',
                    width: 25,
                    sortable: false,
                    resizable: false,
                    headerCellTemplate: '<div class="ngAggHeader"></div>',
                    pinned: grid.config.pinSelectionCheckbox

                },
                enablePinning: grid.config.enablePinning,
                isAggCol: true,
                headerRowHeight: grid.config.headerRowHeight

            }, $scope, grid, domUtilityService, $templateCache, $utils));
        }
    }
}
```

Lets provide easy with with just adding the name for the field


```
 //moved out of above loops due to if no data initially, but has initial grouping, columns won't be added
if (cols.length > 0) {
    for (var z = 0; z < groups.length; z++) {
        if (!cols[z].isAggCol && z <= maxDepth) {
            cols.splice(0, 0, new ngColumn({
                colDef: {
                    field: 'Empty', // FIX HERE
                    width: 25,
                    sortable: false,
                    resizable: false,
                    headerCellTemplate: '<div class="ngAggHeader"></div>',
                    pinned: grid.config.pinSelectionCheckbox

                },
                enablePinning: grid.config.enablePinning,
                isAggCol: true,
                headerRowHeight: grid.config.headerRowHeight

            }, $scope, grid, domUtilityService, $templateCache, $utils));
        }
    }
}
```
