### ISSUE TITLE
changing currentPage with a input delay or fired paginationChanged event by keyboard Enter

### ISSUE THREAD

**Issue by Awakening-j** [angular-ui/ng-grid#3715]
I'm using `ui-grid pagination`,  when I changing the **currentPage** by inputing a number, the `paginationChanged` event will be fired at once.  
Assuming that the currentPage is **2**, and I want to goto page **11**,  the steps are:   
* I first remove the input value **2**,  
* type **1**  
* type **1** again    

Finally the `paginationChanged` event will be fired three times, and if it is an ajax-pagination grid, I have to send three ajax requests to my server, that's not what I expect.  

So will ui-grid enhance this **currentPage** watching? To add an input delay check or fired by keyboard `Enter'  ?

![screen shot 2015-06-07 at 11 05 05 am](https://cloud.githubusercontent.com/assets/8085088/8022450/195b7d24-0d05-11e5-9eb7-5abf247b47ba.png)

**Comment by PaulL1** [comment]
No it is not our current plan to include a debounce within ui-grid for this purpose.  Some users would like to handle each individual event, some users would want to implement a debounce before calling their server.  That's up to the user to do.

If someone were to provide a PR with a switchable debounce implementation, we'd probably accept it, but the current dev team are not planning to implement it.

**Comment by Awakening-j** [comment]
@PaulL1 Thanks for your reply, I just realize it is a `debounce` issue, I add underscore `_.debounce` function, and the delay works, I think I am the one who 'provide a PR with a debounce implementation' :D, I paste the code below, hope it can be your team's reference.  
> var ajax = _.debounce(function(currentPage, pageSize){
                console.log('currentPage', currentPage, 'pageSize', pageSize)   
            }, 1000);
        var paginationChanged = function(currentPage, pageSize){
            //ajax
            ajax(currentPage, pageSize);
        };  

BTW, what is 'PR' mean ?

**Comment by PaulL1** [comment]
A PR is a pull request - so you fork the repository, add it to the code base, add unit tests, then submit a pull request.  JQuery isn't part of our code base, so using _.debounce won't work in the core solution (and is a good reason why doing debounce outside ui-grid is good - then you can choose to use external libraries if you wish).

**Comment by Awakening-j** [comment]
Thanks for explanation. I just use underscore as a solution reference, I know it should override in angular way if PR.  
So I won't submit a PR, just leaving this issue solution for other people

**Comment by Awakening-j** [comment]
@PaulL1 Hi PaulL1, I have a very strange issue on `angular-nvd3 directive`, I know it's not your field, but it seems it is not an issue only about nvd3, maybe some mechanism of angular. I wish you could help me find the issue reason, I've put it on plunker, http://plnkr.co/edit/BfosBI?p=preview, Thank you very much
