### ISSUE TITLE
Column sorting does not work after a while

### ISSUE THREAD

**Issue by moguzalp** [angular-ui/ng-grid#3717]
First of all, it is hard to reproduce issue. it  happens after playing long time with grid.

Column sorting stops working by clicking on column. Closing tab or window does not help, it requires all windows of browser get closed (in my case chrome and with no extentions).

However sorting still works by column menu.

Directives on ng-grid tags are: ui-grid-save-state, ui-grid-move-columns, ui-grid-resize-columns, ui-grid-pinning, ui-grid-pagination, ui-grid-exporter, ui-grid-auto-resize.

**Comment by AgDude** [comment]
@moguzalp When this occurs are you seeing the "shadow" for the move column feature?

**Comment by moguzalp** [comment]
I don't know what it means shadow, but I can say when I click to sort, it happens as I move column.

**Comment by AgDude** [comment]
By shadow, I mean the transparent copy of the column header that appears while you are moving it.

**Comment by AgDude** [comment]
@moguzalp I think this is the same issue as #3333. Could you please confirm that.

**Comment by moguzalp** [comment]
Correct, it seems it is the same issue.
