### ISSUE TITLE
Support of treeview in stable/RC

### ISSUE THREAD

**Issue by xforceco** [angular-ui/ng-grid#3735]
Currently trying following the 215 Tree View tutorial on official website, and find out tree view is not working in the tutorial for stable version of ui-grid.

Any fixing to this? Or tree view is supposed to be working only on unstable version?

**Comment by PaulL1** [comment]
TreeView, like grouping, was substantially changed recently, and the code for these changes is all in unstable (hasn't been pushed out as an RC yet, will go with 0.22).

**Comment by xforceco** [comment]
I see, hope it will be released soon. And thank you for the great effort :)
