### ISSUE TITLE
gridApi.core.scrollTo error

### ISSUE THREAD

**Issue by feralanPaladin** [angular-ui/ng-grid#3737]
Hi,

I use your core.scrollTo() function to scroll to the desired cell. But each time i call the function, i get the below error message.

This is the caller code =>
$scope.gridApi.core.scrollTo( $scope.model.gridData[valRet.rowIndx], $scope.columnDefs[valRet.colIndx] ). then(function(){ /*This part has not called by the promise yet*/ })

Error:
asked to listen on core.on.scrollEnd but scope wasn't passed in the input parameters, you probably forgot to provide it, not registering
(anonymous function) @ angular.js:265
module.service.s.logError @ ui-grid.js:10015
GridApi.registerEvent.feature.on.(anonymous function) @ ui-grid.js:5618
Grid.scrollToIfNecessary @ ui-grid.js:5297
Grid.scrollTo @ ui-grid.js:5329
(anonymous function) @ ui-grid.js:3245
module.service.s.createBoundedWrapper @ ui-grid.js:9473
(anonymous function) @ sfsGrid.js:69
(anonymous function) @ angular.js:265
it @ angular.js:265
(anonymous function) @ angular.js:265

**Comment by feralanPaladin** [comment]
gridApi.cellNav.scrollToFocus() function also produces the same error message

$scope.gridApi.cellNav.scrollToFocus( $scope.model.gridData[rowIndx], $scope.columnDefs[colIndx] );

**Comment by PaulL1** [comment]
What version are you on?  This was a defect in earlier versions, I thought it had been resolved.

**Comment by feralanPaladin** [comment]
My version is ui-grid - v3.0.0-rc.20-3cbe79f - 2015-04-17

I'll try with the latest version.

**Comment by feralanPaladin** [comment]
As you said, it had been resolved :)
