### ISSUE TITLE
Tab event propagates

### ISSUE THREAD

**Issue by feralanPaladin** [angular-ui/ng-grid#3742]
Hi,

At your previous versions, while using inline edit feature (with edit on focus) usually tab key is not propagates as an grid element event (I cannot catch the tab key event from the grid's DOM element)

But with your latest version, this situation has been changed and only default text edit fields prevents the propagation, but dropdown editors (ui-grid/dropdownEditor) propagates the tab event and this is an unexpected behaviour according to the previous versions.

**Comment by swalters** [comment]
should be fixed now in master
