### ISSUE TITLE
Custom template 317 and how to make it work with pinning

### ISSUE THREAD

**Issue by rkilarski** [angular-ui/ng-grid#3760]
The "merged cells" sample custom template in Tutorial 317 (http://ui-grid.info/docs/#/tutorial/317_custom_templates) is actually a real feature we have in our grids.  However, we are struggling with how to enable this feature along with pinning.  Currently, when we pin a column, the merged cell repeats in the new viewport.

You can see that in this example plunker:  http://plnkr.co/edit/rRNmh2XALvRLRaKejdkr?p=preview

where "A merged row" appears in each pinned viewport.

Question/bug/feature:  How would we keep the merged cell to take the entire horizontal width of the grid while keeping the pinned columns on the regular rows?

**Comment by PaulL1** [comment]
I provided an example of something similar for footer - I can't recall if it was in the tutorial or a plunker on an issue. The trick is an Ng-if that checks for renderContainer == body.

**Comment by rkilarski** [comment]
Hi Paul, thanks for the response.  I took a look at the tutorial for custom templates (that's where you mention renderContainer===body) and didn't see how to apply that example to any row in the middle of a grid.  That seemed to apply only to the grid's last row/footer?

**Comment by PaulL1** [comment]
No, the same logic should be able to be applied in any template to determine the renderContainer that you're in.

**Comment by rkilarski** [comment]
I think I know what you are suggesting...  you're proposing that the "merged rows" would ONLY be displayed in the body container, not the left or right container, is that right?

What I'm looking for is instead a row that spans the entire table, including the left container, while at the same time allowing a pinned column. Here's a mock-up:

![image](https://cloud.githubusercontent.com/assets/8093793/8219591/18ac08be-1519-11e5-82c7-de11338cfa00.png)

**Comment by PaulL1** [comment]
That won't be easy, since in the DOM the hierarchy includes the renderContainer - essentially columns are higher in the hierarchy than rows.  I think the best you can do is to have slightly different templates for the body and left containers, so it looks like a merged row, even though it actually isn't.

**Comment by rkilarski** [comment]
I ran the proposal through our designers and they are (mostly) OK with it.  So for now, I'll close this as an issue and see how our software does with this functionality.

**Comment by dashmaker** [comment]
@rkilarski Hi - I'm facing the same issue. Did you find a workaround that you are able to share?

**Comment by Krakownication** [comment]
The ng-if trick that checks for renderContainer == body:
http://plnkr.co/edit/XAg3225wZVave11419dT?p=preview
