### ISSUE TITLE
UI Grid refresh/reload issue

### ISSUE THREAD

**Issue by yiyzhang** [angular-ui/ng-grid#3770]
I am using UI Grid for a data grid display. All columnDefs and data are real-time and can change depending on user selection, but i cannot make the reset of UIGrid work. I tried to use $compile to recompile and append element on very refresh. 
    
var newRsGrid = $compile('<div class="gridStyle" ui-grid="gridOptions" ui-grid-auto-resize ui-grid-edit></div>')($scope)
rsGrid.empty();
rsGrid.append(newRsGrid);

It seems to work but is throwing lots of exceptions like: Error: [$compile:ctreq] Controller 'uiGrid', required by directive 'uiGridRow', can't be found!

I found a related issue at https://github.com/angular-ui/ng-grid/issues/3096, but don't know if he got the same error as i do. Can someone help with a solution? Will UI-Grid reset/reload be supported in 3.0?

**Comment by PaulL1** [comment]
3.0 will be the functionality we currently have, but with the remaining 3.0 milestone bugs fixed.  So no, this won't be in 3.0.

The usual way to reset the grid at the moment is to wrap your enclosing directive in an ng-if, so you can toggle the ng-if off, wait for one digest cycle, then toggle it on again.

**Comment by yiyzhang** [comment]
Thanks, Paul! Can you point to a URL where i can find some sample code with this "ng-if" technique?

**Comment by PaulL1** [comment]
No, not off the top of my head, although I've seen it somewhere in a plunker before.  But it's pretty simple.

**Comment by yiyzhang** [comment]
But "<div class="gridStyle" ui-grid="gridOptions"></div>" has to be wrapped in a directive, right? And then use the wrapper directive inside ng-if?

**Comment by yiyzhang** [comment]
Sorry i couldn't paste any code in here. It's swallowed.

**Comment by PaulL1** [comment]
You should be able to paste, I've edited.

The normal way is:

```
  <div ng-if="!refresh" class="gridStyle" ui-grid="gridOptions"></div>
```

And then in your controller, when something happens that would trigger a refresh:

```
  var refresh = function() {
    $scope.refresh = true;
    $timeout(function() {
      $scope.refresh = false;
    }, 0);
  };
```

**Comment by yiyzhang** [comment]
Yes, it's working! I simply set $scope.refresh to be true and then false, and reset gridOptions with new data and it works. The only minor thing noticed is that the timeout in "ui-grid-auto-resize" keeps changing the grid size. After i removed ui-grid-auto-resize attribute, it's working just fine. Thnaks!

**Comment by c0bra** [comment]
Glad you got it working.

**Comment by davidbarkhuizen** [comment]
@PaulL1 You sir, are a gentleman and a scholar - and I tip my hat to you. Many thanks.

**Comment by PaulL1** [comment]
Well thank you.  Nothing like getting nice thoughts for something I did months ago.  :-)

**Comment by shandianjiying** [comment]
I have resolved my problem ! Thanks a lot! That's working!@PaulL1

**Comment by blitterGitter** [comment]
Thank you c0bra and PaulL1, ng-if solves that issue. Had this for months, thank you very much!

**Comment by cauebiazin** [comment]
Hello.

I have the same problem.

I created a new function in my controller to refresh data after a search.

`$scope.atualizarComposicaoQuimica = function (resultado) {   
    $scope.grdComposicaoQuimica.data = $.parseJSON(resultado)
}`

In my div, I added ng-if:

`<div ng-if="!refresh" id="grd-ComposicaoQuimica" ui-grid="grdComposicaoQuimica" ui-grid-move-columns ui-grid-auto-resize ui-grid-resize-columns ui-grid-selection ui-grid-exporter></div>`

And in my controller I added tge code:

`var refresh = function () {
                $scope.refresh = true;
                $timeout(function () {
                    $scope.refresh = false;
                }, 0);
            };`

But i continue get the error "**Controller 'uiGrid', required by directive 'uiGridRow', can't be found!**"

Help-me please!

**Comment by shershen08** [comment]
running  ```gridApi.core.refresh()``` does not result in and changes;
```
gridApi.core.refresh().then((d)=>{
      console.log( d );
})
//outputs undefined
```

**Comment by cauebiazin** [comment]
This error occurs after I update my div with a PartialViewResul from controller:

`$("#divDadosAcoInterno").html(partialView);`

After this action, I execute the code follow to update my data:

`angular.element(document.getElementById('grd-ComposicaoQuimica')).scope().atualizarComposicaoQuimica(result)`

**Comment by rafasanchezcu** [comment]
Hola, soy de colombia.
hablo muy poco, espero me puedan ayudar.

Intento que se modifican automaticamente lo datos en las filas de mi tabla, 
estos datos van cambiando en tiempo real, pero no he logrado que se cambien en la interfaz de red, con ningun metodo. 

intento utilizar refresh Rows() pero tampoco lo logro.

Adjunto el codigo: 


var app = angular.module('app', ['ngAnimate', 'ngTouch', 'ui.grid', 'ui.grid.selection', 'ui.grid.exporter']);

app.controller('MainCtrl', ['$scope', '$http', 'i18nService', function ($scope, $http, i18nService) {


  
 $scope.deleteRow = function(row) {
    var index = $scope.gridOptions.data.indexOf(row.entity);  
    $scope.gridOptions.data.splice(index, 1);
  };
   
   $scope.addData = function(row) {
    
    $scope.gridOptions.data.push({
                
                
                field: 'Clave',
                field: 'Conductor',
                field: 'Placa',
                field: 'Ruta',
                field: 'HoraSalidaEstimada'
              });
  };


    $scope.gridOptions = {
    
    enableSorting: true,
    minimumColumnSize: 90,
    columnDefs: [
      
      {field: 'Eliminar', width: '7%', cellTemplate: '<button class="btn primary" ng-click="grid.appScope.deleteRow(row)">Eliminar</button>'},
      {field: 'Clave', width: '6%'},
      {field: 'Conductor', width: '8%'},
      {field: 'Placa', width: '7%'},
      {field: 'Ruta', width: '6%'},
      {field: 'HoraSalidaEstimada', name:'H.S.E', width: '7%'}
      

    ],
    
    exporterMenuCsv: false,
    enableGridMenu: true,
    enableSelectAll: true,
    //exporterCsvFilename: 'myFile.csv',
    exporterPdfDefaultStyle: {fontSize: 8},
    exporterPdfTableStyle: {margin: [10, 10, 10, 10]},
    exporterPdfTableHeaderStyle: {fontSize: 9, bold: true, italics: true, color: 'red'},
    exporterPdfHeader: { text: "Ruta:", style: 'headerStyle' },
    exporterPdfFooter: function ( currentPage, pageCount ) {
      return { text: currentPage.toString() + ' of ' + pageCount.toString(), style: 'footerStyle' };
    },
    exporterPdfCustomFormatter: function ( docDefinition ) {
      docDefinition.styles.headerStyle = { fontSize: 22, bold: true };
      docDefinition.styles.footerStyle = { fontSize: 10, bold: true };
      return docDefinition;
    },
    exporterPdfOrientation: 'landscape',
    exporterPdfPageSize: 'LETTER',
    exporterPdfMaxGridWidth: 450,
    //exporterCsvLinkElement: angular.element(document.querySelectorAll(".custom-csv-link-location")),
    onRegisterApi: function(gridApi){

      $scope.gridApi = gridApi;
     
    }

  };

  
  i18nService.setCurrentLang('es');


  $http.get('http://localhost:8080/docs/api/ULTIMAVERSION6/data/Tabla.json')
    .success(function(data) {
      $scope.gridOptions.data = data;

    var refresh = function() {
    $scope.refresh = true;
    $timeout(function() {
      $scope.refresh = false;
    }, 0);
  };





    });
}]);

**Comment by rafasanchezcu** [comment]
Hi, I am from Colombia.
I speak very little, I hope I can help.

I try to automatically modify the data in the rows of my table,
These data are changing in real time, but I have not been able to change them in the network interface, with any method.

I try to use refresh Rows () but I do not get it either.

I am enclosing the code:


$http.get('http://localhost:8080/docs/api/ULTIMAVERSION6/data/Tabla.json')
.success(function(data) {
$scope.gridOptions.data = data;

var refresh = function() {
$scope.refresh = true;
$timeout(function() {
  $scope.refresh = false;
}, 0);

**Comment by rafasanchezcu** [comment]
@PaulL1 @PaulL1 can you help me!! thanks
