### ISSUE TITLE
Mousewheel scrolling does not scroll completely in containers missing vertical scrollbar

### ISSUE THREAD

**Issue by swalters** [angular-ui/ng-grid#3772]
@c0bra if you could take a look at this, I'd appreciate it. I'm baffled.

In 203_pinning

1. Scroll to bottom using vertical scrollbar.  Last row is ID 499
2. Now use mouse wheel to scroll up and down in left container.  Last row Id is 496.
3. Do the same in Body container.  Last row Id is 496.
4. Do the same in right container. Last row Id is 499

**Comment by swalters** [comment]
You might want to merge https://github.com/angular-ui/ng-grid/pull/3769 before looking at this, but it gets the same results with or without it.

**Comment by c0bra** [comment]
Note: this happens in Chrome, Firefox, and IE10. Doesn't seem browser-related.

**Comment by c0bra** [comment]
Note: The margin-top that gets set from scrolling the right-most container (the one with the scrollbar) is 60px more than the others. 60px == two rows.

**Comment by c0bra** [comment]
Apparently `getVerticalScrollLength()` is measuring 100px longer for the container with the scrollbar.

**Comment by c0bra** [comment]
I thought maybe that the mousewheel handler was allowing an extra call to `fireThrottledScrollingEvent()` on the scrollbar container, but it isn't so.

It's just a normal scroll event I think...

**Comment by c0bra** [comment]
Note: It *may* be because the scrollbar-less container doesn't fire scroll events. So the one with scrollbars is able to fire an extra event to get to the bottom that the other ones can't.

We may need to somehow manually set the scrollTop to the max if we're at/past 100% and not at the max scroll distance (canvas height - viewport height)

**Comment by c0bra** [comment]
The problem is that containers that have overflow: scroll will scroll to the bottom
containers that have overflow: hidden won't
They will stop ~ 100px short

**Comment by c0bra** [comment]
Looks like we've been calculating scroll percentage wrong. The max scroll length should match the scroll height of the viewport but it's off by the height of the scrollbar, which causes the scroll percentage to go BEYOND 100%.

The mousewheel handler prevents firing this > 100% scroll event, and thus the container does not scroll.
