### ISSUE TITLE
exporting feature when using cellFilter

### ISSUE THREAD

**Issue by gizbo** [angular-ui/ng-grid#3774]
Hello guys,
   In my grid I have cell that are using cellFilter and when I export it looks like the filter is not called. Is there an easy way to get this working? So of my cells are objects {id:1,name:'test'}. 
Thanks so much,
Yves

**Comment by PaulL1** [comment]
Exporter explicitly doesn't call cellFilters - the way cellFilters are formatted means they can't be easily called synchronously.  Exporter provides some callbacks that you can use to massage the data on the way out, you can call your filters from those callbacks.

**Comment by gizbo** [comment]
Wow that was fast ! :) Thanks Paul
Would have, by any chance, an example of such callback?
Thanks so much.

**Comment by PaulL1** [comment]
http://ui-grid.info/docs/#/tutorial/312_exporting_data_complex.  ExporterFieldCallback.  It's a pretty simple example, but that framework should work.

**Comment by gizbo** [comment]
Thanks a lot man. 
Yves

**Comment by sachetgupta** [comment]
If you have applied a filter to columnDefs, then you just have to write a callback method which will execute that same filter while exporting the data (as PaulL1 suggested).

Below is my proposed solution. This method would work for multiple filter with multiple parameters.

Column defination:

```
var rptColumnDefs = [ {
        field: 'field1',
        cellFilter: "filter1:'param1' | filter2 | filter3 : 4 | filter4 : 4 : 'param2'",
        displayName: "Field 1"  
    }, field: 'field2',
        cellFilter: "filter1:'param1' | filter2 | filter3 : 4 | filter4 : 4 : 'param2'",
        displayName: "Field 2"  
    }]
```
Exporter Callback function:

```
$scope.reportGridOptions = {
    enableFiltering: true,
    enableHorizontalScrollbar: uiGridConstants.scrollbars.NEVER,
    enableVerticalScrollbar: uiGridConstants.scrollbars.WHEN_NEEDED,
    exporterCsvFilename: '',
    columnDefs: rptColumnDefs,    
    exporterFieldCallback: function (grid, row, col, input) {
            if (col.cellFilter) { // check if any filter is applied on the column
                var filters = col.cellFilter.split('|'); // get all the filters applied
                angular.forEach(filters, function (filter) {
                    var filterName = filter.split(':')[0]; // fetch filter name
                    var filterParams = filter.split(':').splice(1); //fetch all the filter parameters
                    filterParams.unshift(input); // insert the input element to the filter parameters list
                    var filterFn = $filter(filterName); // filter function
                    // call the filter, with multiple filter parameters. 
                    //'Apply' will call the function and pass the array elements as individual parameters to that function.
                    input = filterFn.apply(this, filterParams); 
                })
                return input;
            }
            else
                return input;
        }
```
This generic function will help export the data as it is displayed in UI Grid (after applying the filters.)
Hope this helps someone.

**Comment by piller187** [comment]
My cell filter is: cellFilter: 'date:\'MM/dd/yyyy\''

The above code doesn't work on this. It's not a function so $filter(filterName) fails.

**Comment by tonysepia** [comment]
@sachetgupta 
> This generic function will help export the data as it is displayed in UI Grid (after applying the filters.)
> Hope this helps someone.

Thank you for the great idea, but it appears that the app-level filter can't be accessed!
`Error: "[$injector:unpr] Unknown provider: numberFixedLen FilterProvider <- numberFixedLen Filter`

The numberFixedLen filter is defined like this:
app.filter('numberFixedLen', function () {
    return function(a,b){
        return(1e4+""+a).slice(-b);
    };
});

Why can't it be accessed?
