### ISSUE TITLE
How to remove Agg functions from string type column options menu 

### ISSUE THREAD

**Issue by kushalt** [angular-ui/ng-grid#3784]
I used angular-ui grid to show data with grouping but it shows Agg functions like (Agg;sum,Agg:Max) for all columns in grid. So i just want to show Agg functions only for numeric type columns and remove from string type column like Name,Status. Any help would be greatly appreciated.

**Comment by PaulL1** [comment]
There is a suppress aggregation option - is that at the column level?  If so, that will do it.

**Comment by kushalt** [comment]
Many thanks Paul , its working as expected.
