### ISSUE TITLE
How to filter by display value instead of actual value?

### ISSUE THREAD

**Issue by senpost** [angular-ui/ng-grid#3791]
I have a gender column in my grid and its actual value is a integer and it gets transformed into strings such as Male, Female etc... Filtering won't work if I try to filter it by the text, filtering by actual integer value works fine.

How can I filter it by the text that is displayed rather than the value behind the text?

Here is the Plunker http://plnkr.co/edit/JgjKWsVWCV7v4hA8mak3?p=preview

Thank you.

**Comment by PaulL1** [comment]
You can't filter without using a custom filter widget.  I'd recommend using the dropdown widget, which is shown in the http://ui-grid.info/docs/#/tutorial/306_custom_filters tutorial (for gender in fact).

**Comment by senpost** [comment]
Thanks @PaulL1

**Comment by mc0re** [comment]
Dropdowns are fine (although require some work if you want them translated and dynamic - pick only the values that exist in the data). But a full-text search on the values would also be really nice.

Could I suggest, that UI Grid adds the translated value to a helper column and uses it for standard text filtering, _instead_ of the actual value?
