### ISSUE TITLE
3.0 row data in cellFilter

### ISSUE THREAD

**Issue by mc0re** [angular-ui/ng-grid#3793]
In pure Angular I could write:

`<table> <tr ng-repeat="item in ..."> <td>{{'prefix.' + item.type + '.info' | translate item}}`

The idea is, that for each possible `item.type` (an enum - e.g. `Dog` and `Fish`) there is an entry in the translation table, looking like this:

`'prefix.Dog.info': 'This animal has {{nofExtremities}} paws'`
and
`'prefix.Fish.info': 'This fish has {{nofFins}} fins'`

So the `{{}}` elements in the translation results are replaced with properties of `item` object.

To repeat this in UI-Grid (3.0 rc 22), I thought I could use `cellFilter`, but giving it value `"translate row"` or `"translate row.entity"` yields a JS error:

`Error: [$parse:syntax] Syntax Error: Token 'row' is an unexpected token at column 85 of the expression ["prefix." + grid.getCellValue(row, col) + ".info" |translate row] starting at [row].`

What am I missing?

**Comment by c0bra** [comment]
Are you sure you can use a space in a filter spec in Angular? Do you mean to be doing `translate:row`?

**Comment by mc0re** [comment]
You're right, it must be a colon. Strangely, a space works in ordinary code - but a colon works in UI-Grid, that's what matters :-)

**Comment by ima-tech** [comment]
Can you post the complete solution, I'm having problems with that exactly.

**Comment by mc0re** [comment]
As @c0bra wrote, you need to write
`cellFilter: 'translate:row'`
