### ISSUE TITLE
[saveState | externalSorting] external sorting listener invoked without arguments on state restore

### ISSUE THREAD

**Issue by lpand** [angular-ui/ng-grid#3795]
Hi, external sorting and saveState plugin don't play nice together. I made a [demo](http://plnkr.co/edit/Ua02w1ltytbtWPoHo22v?p=preview) out of the saveState plugin tutorial.

1. change sorting of a column
2. save state
3. change sorting again
4. restore state

The sorting listener has been called without arguments while the column appears with the little triangle on it.

P.S. thanks for the great job

**Comment by lpand** [comment]
This seems to be the guilty line:

https://github.com/angular-ui/ng-grid/blob/master/src/features/saveState/js/saveState.js#L552

I'll create a pull request if you agree.

**Comment by PaulL1** [comment]
So the problem is that it didn't provide the sort column that changed in the call?  If that's what you're fixing then yeah, happily would accept a PR.
