### ISSUE TITLE
Export data in csv file with external download button

### ISSUE THREAD

**Issue by kushalt** [angular-ui/ng-grid#3801]
I want to export data in csv file on the click of Download button which is placed outside of the UI grid so is there any api available which i can call on button click event and data will be exported in csv file. Any help would be greatly appreciated.

**Comment by lpand** [comment]
Have you given a glance to the export tutorial? http://ui-grid.info/docs/#/tutorial/312_exporting_data_complex

**Comment by kushalt** [comment]
Thanks Ipand,  its exactly same as per my requirement.

**Comment by ashishpatel02** [comment]
@lpand , any help for exporting to excel?

**Comment by kenisteward** [comment]
@ashishpatel02 Do you really need to export to .xlsx?  Can your clients just load the csv into Excel?
