### ISSUE TITLE
rowTemplate messes up enableFullRowSelection/enableRowHeaderSelection

### ISSUE THREAD

**Issue by loykianos** [angular-ui/ng-grid#3802]
Hey there, 

I just noticed that adding a typical rowTemplate such as the one given in http://ui-grid.info/docs/#/tutorial/317_custom_templates messes up enableFullRowSelection  and/or enableRowHeaderSelection. 

Basically, I want to create a grid with selectable rows (without a checkbox) and an ng-dblclick action. 
I just switched from ngGrid to ui-grid, so I might be missing something. Maybe I should use a different rowTemplate or something.

**Comment by PaulL1** [comment]
You probably need to start with the base row template, and check that all the selection etc works.  Then modify from that base, and keep checking that it's all working.

**Comment by loykianos** [comment]
Indeed it, works as intended with the following rowTemplate content: 

<pre>ng-dblclick="grid.appScope.onDblClick(row)" ng-repeat="(colRenderIndex, col) in colContainer.renderedColumns track by col.colDef.name" class="ui-grid-cell" ng-class="{ \'ui-grid-row-header-cell\': col.isRowHeader }\" ui-grid-cell</pre>

It would be useful to add this base row template to the Custom Template section of the tutorial.

Thanks anyhow!

**Comment by c0bra** [comment]
@loykianos extracting the default templates and putting them up in the docs is on my plate. Thanks for confirming its usefulness! :)

**Comment by billyaraujo** [comment]
+1

**Comment by billyaraujo** [comment]
Please add tutorial on how to customize row template without loosing row selection.

http://plnkr.co/edit/4EpCvzRPXRxOoGvl1ktg?p=preview
