### ISSUE TITLE
set data to nggrid is not working 

### ISSUE THREAD

**Issue by avatarr** [angular-ui/ng-grid#3817]
Edit : I have use angular-ui-grid 3.0.0-rc.21
I have a some problem when I need to set data to nggrid again (actually I want to reset some of data) like below picture 

![screen shot 2558-06-19 at 11 28 49](https://cloud.githubusercontent.com/assets/1640817/8250903/eff1b0ce-16a1-11e5-9746-79957dd9d795.png)
In line 334 is work I have load data form my server , In line 336 to 341 I need to load some data again when user click on button (load data like ajax) then in line 339 , I have set my data to nggrid , seem to it not working , How can i do in this case 

Thank you

**Comment by c0bra** [comment]
Your console.log is running? Are you fetching your data with $http or a non-Angular ajax method? You could maybe try wrapping your `.data` assignment in a $timeout and see what happens, but I don't think it would do anything.

**Comment by avatarr** [comment]
I can solved it, Thank you very much 

best regards.
