### ISSUE TITLE
Call headerCellClass when sorting changes

### ISSUE THREAD

**Issue by mc0re** [angular-ui/ng-grid#3818]
It seems that when sorting is changed (by clicking on the column header), the `headerCellClass` (defined as a function) is not checked.

Here is the function I want get executed:
```javascript
function headerClassFunction(row, rowRenderIndex, col) {
	if (col.sort.direction && col.filters[0].term) {
		return 'header-sorted-filtered';
	} else if (col.sort.direction) {
		return 'header-sorted';
	} else if (col.filters[0].term) {
		return 'header-filtered';
	} else {
		return '';
	}
}
```

**Comment by c0bra** [comment]
Have you tried looking at this tutorial? http://ui-grid.info/docs/#/tutorial/115_headerCellClass  Looks like the header class is updating on sort there.

**Comment by mc0re** [comment]
Thanks, this is the part I was missing:
$scope.gridApi.core.on.sortChanged()
