### ISSUE TITLE
UI-Grid edit issue with custom template.

### ISSUE THREAD

**Issue by ashishjp** [angular-ui/ng-grid#3819]
I have one column with custom edit template with drop-down (select) html: 

When i am trying to edit the cell it works good, but when i am done with edit and clicks on other cell it should exit from edit mode and it should make cell non editable again.

However after scrolling edited cells exits edit mode. 

Grid should behave like default drop-down template

Here is the Plunker with issue on pet column:  http://plnkr.co/edit/IrUVRjv4XSp48V27LjsO?p=preview

**Comment by c0bra** [comment]
Why not use the `dropdownEditor` template for your own dropdown?  You need extra event bindings to make sure that the cell switches modes after the user selects a value and `dropdownEditor` adds that for you. Otherwise you'll have to write your own dropdown directive for that.

**Comment by ashishjp** [comment]
I tried to use dropdown editor but had few issues to bind dynamic values from $scope. and also I want to do some custom edit template those are different from default dropdown template. so I decided to go for custom template.  could you please help me to know how to do extra event binding or directive to solve my issue.

**Comment by ashishjp** [comment]
@c0bra @PaulL1 Please guide me with this issue.

**Comment by akgupta888** [comment]
@Ashish, I am facing similar issue. I had to use custom directive. Can u please let me know how did u solve the issue?
