### ISSUE TITLE
In a cell template, how to access the value from a different field/cell

### ISSUE THREAD

**Issue by rcholic** [angular-ui/ng-grid#3821]
**I have the following example data:**

```
var data = [
{"id" : 10, "name" : "Name 1", "city" : "San Francisco"},
{"id" : 12, "name" : "Name 2", "city" : "San Diego"},
{"id" : 20, "name" : "Name 3", "city" : "Santa Barbara"},
];
```

**below is the columnDefs for gridOptions, in the name field, I need to create a hyperlink using ui-sref**

```
var gridOptions.columnDefs = [
{field: 'id', displayName: 'ID'},
{field: 'name',
cellTemplate: '<div class="ui-grid-cell-contents tooltip-uigrid" title="{{COL_FIELD}}">' +
                       '<a ui-sref="main.placeDetail{{placeId: {{row.entity.id}} }}">{{COL_FIELD CUSTOM_FILTERS}}</a></div>'
},
{field: 'city', enableSorting: true}
];
```

The table is rendered fine except for the **row.entity.id** value. The values I get in the hyperlinks (inside the **name column**) are sequential: 1, 2, and 3, instead of 10, 12, and 20 as defined in the **data array**, however, the **id** values displayed in the **ID** column is what I am expecting: 10, 12, and 20. I wonder how you would access the **id** field value inside the **name** field, and why are the **id** in the **name** cell are sequential?

**Comment by c0bra** [comment]
If you change `id` to a different property name do you get the same behavior? `id` should not be a reserved word in ui-grid, *especially* not in entities, but I'm curious if maybe there's something going on there.

**Comment by rcholic** [comment]
@c0bra thanks for the reply.
When I change **id** to **name**, the **name** field value shows up correctly for the first 4 rows, but starting row #5, the **name** field value gets messed up, which means that the **name** in row #7 can take the **name** field value in row #9. This behavior is just too strange.

**Comment by c0bra** [comment]
That indeed is very strange. Can you reproduce this in a plunker?

**Comment by rcholic** [comment]
I am working on a plnkr. But I would like to bring this up to you. In the browser console, I see the following message when the page is loaded:

```
Unable to assign type from data, so defaulting to string
```

what does this error message mean? I saw a discussion on this at https://github.com/angular-ui/ng-grid/issues/3240

**Comment by PaulL1** [comment]
That is a warning not an error, it shouldn't be material to this issue.  You've embedded a binding in a binding, I'm not sure that's a good idea, if you change your cellTemplate to not do that do you get a better result?

**Comment by rcholic** [comment]
@PaulL1 
When I don't do the binding inside of binding, the **id** value shows up fine. Maybe binding of binding is to blame. Thanks
