### ISSUE TITLE
external sorting problem: sortColumns[0].name != gridOptions.columnDefs[0].name

### ISSUE THREAD

**Issue by rcholic** [angular-ui/ng-grid#3837]
I followed the external sorting guide on the official tutorial: http://ui-grid.info/docs/#/tutorial/307_external_sorting

I have the following data:
```
var data = [
{"id" : 10, "name" : "Name 1", "city" : "San Francisco"},
{"id" : 12, "name" : "Name 2", "city" : "San Diego"},
{"id" : 20, "name" : "Name 3", "city" : "Santa Barbara"},
];

$scope.gridOptions.columnDefs = [
{name: 'id', displayName: 'ID'},
{name: 'name'},
{field: 'city', enableSorting: true}
];

```

As used in the tutorial, I used the following **if statement:**

```
 if (sortColumns.length == 0 || sortColumns[0].name != $scope.gridOptions.columnDefs[0].name)
```
However, I found that  the value for **sortColumns[0].name**  is name when I sort the ID column, and the value for $scope.gridOptions.columnDefs[0].name is "id", which is correct. So I don't understand why these two values are not the same.

**Comment by PaulL1** [comment]
sortColumns is that subset of columns that have sorting. So if only one column has sorting, then sortColumns[0] will be that column.  Check sortColumns.length v's columnDefs.length.
