### ISSUE TITLE
Is there a way to format column header?

### ISSUE THREAD

**Issue by codesometech** [angular-ui/ng-grid#3844]
Is there a way to format column header? Some of my column headers are long and end with "..." and overlap with sort icon on column. It would be nice if I can add a line break.

**Comment by PaulL1** [comment]
On the columnDef, there should be a headerCellTemplate: http://ui-grid.info/docs/#/api/ui.grid.class:GridOptions.columnDef and http://ui-grid.info/docs/#/tutorial/317_custom_templates

**Comment by codesometech** [comment]
That worked. Thanks @PaulL1
