### ISSUE TITLE
ColumnDef: Unable to access grid.appScope

### ISSUE THREAD

**Issue by ImpactStudio** [angular-ui/ng-grid#3846]
I've searched high and low and have not been able to figure this one out and I have a maaaaajor feeling its going to be super simple.

Essentially I have a grid populating with nearly everything I need except a few of the column titles need to come from a configuration table in a database.  I have the following code in a controller:
```javascript
    orgService.getOrgLevel(1).then(function (results) {

        $scope.org1 = results.data;
    }, function (error) {
        //alert(error.data.message);
    });

$scope.resultGrid = {
        enableSorting: true,
        enableColumnResizing: true,
        columnDefs: [
            { field: "name", displayName: 'resultList.assetName', headerCellFilter: 'translate' },
            { field: "org1", displayName: 'grid.appScope.org1.label' },
            { field: "testDate", displayName: 'resultList.formTestDate', headerCellFilter: 'translate', cellFilter: 'date:\'longDate\'' },
            { field: "tester", displayName: 'resultList.tester', headerCellFilter: 'translate', cellFilter:'capitalize' },
        enableGridMenu: true,
}
```

I'm trying to get the display name of the column to evaluate a form of the expression to get the value that has been populated from the database.

I attempted to develop an 'orgFilter' that mimics the angular-translate directive however, that proved troublesome as I simply don't know enough to make it work.  After attempting to foray into that code, I came back and attempted to use headerCellTemplate.  However it requires me to provide the elements for that header and I would rather have the default elements there.  Especially since I am using a number of the grid sorting/filtering features.

That brings me back to my original question - is there a simple way to evaluate an angular expression for the display name?

**Comment by swalters** [comment]
Display Name is bound to columnDef.displayName.  Just update that somewhere else in your application after you get the data and the watch on columnDef.displayName should update it.

$scope.resultGrid.columnDefs[0].displayName = resultList.assetName

I do something similar in my application and it works.

**Comment by ImpactStudio** [comment]
I'm not sure if this is good code, as it seems a bit hacky but I was able to get it to finally work with the following.

```javascript
    orgService.getOrgLevel(1).then(function (results) {
        $scope.resultGrid.columnDefs[1].displayName = results.data.label;
    }, function (error) {
        //alert(error.data.message);
    });


    $scope.resultGrid = {
        enableSorting: true,
        enableColumnResizing: true,
        columnDefs: [
            { field: "relayName", displayName: 'resultList.assetName', headerCellFilter: 'translate' },
            { field: "org1", displayName: "orgLevel1" }
         ],
        enableGridMenu: true,
```

**Comment by ImpactStudio** [comment]
Good timing - yeah as I was thinking about how all the pieces came together, I realized that I was vastly overthinking it.  

I came to that conclusion right before you posted and was formatting my answer. :)  Thanks for the prompt reply!
