### ISSUE TITLE
gridApi.grouping is missing even ui.grid.grouping is included on app.module

### ISSUE THREAD

**Issue by val-samonte** [angular-ui/ng-grid#3852]
Am I missing something here? I checked the document section (http://ui-grid.info/docs/#/tutorial/209_grouping) and followed the exact example, but I still can't access the api for the grouping.

**Comment by val-samonte** [comment]
Sorry, ui-grid-grouping should be included on the html. This is undocumented though and kinda misleading a newbie like me.

**Comment by mikeyg123** [comment]
included in the html how?
