### ISSUE TITLE
Tree View  Data(Parent and Children) data's font is displaying in bold . 

### ISSUE THREAD

**Issue by talasila66** [angular-ui/ng-grid#3860]
Tree View  Data(Parent and Children) data's font is displaying in bold . How we can display normal, how we are displaying normal grid data? Any Code snippets please.

Actually data font is displaying same as like header font. I want data font to display in normal font.

**Comment by talasila66** [comment]
.ui-grid-tree-header-row {
  font-weight: normal;
}

Customizing the ui-grid.css,solved my problem

**Comment by onlinehood** [comment]
Thank you! @talasila66 

additionally, need !important in my case.

.ui-grid-tree-header-row {
font-weight: normal !important;
}
