### ISSUE TITLE
angular dependency for bower package

### ISSUE THREAD

**Issue by mkeremguc** [angular-ui/ng-grid#3865]
set `"angular": ">=1.2.16 <=1.3.x"` in bower package. however, even the ui-grid.info site uses angular 1.3 and seems it is compatible already. can you fix this so we can get rid of bower warnings etc ?

**Comment by c0bra** [comment]
I don't get it. Why wouldn't bower choose the latest 1.3.x based on that spec?  I made a tester for node-semver and it seems like that's what it should do: http://plnkr.co/edit/dHvHpgK53mtEcgI2goDQ?p=preview

**Comment by c0bra** [comment]
OK if I do `>=1.2.16 <=1.3.14` it will install 1.3.14. But if I do `>=1.2.16 <=1.3.x` (what it is now) it will do 1.2.28 (the latest 1.2.x). Anyone know what the heck that is?

**Comment by mkeremguc** [comment]
please update bower-ui-grid repo. also it might work as `>=1.2.16 <=1.3` not ?

**Comment by c0bra** [comment]
The repo gets updated automatically by Travis. I'll check the builds

**Comment by mkeremguc** [comment]
ok thanks but it won't allow 1.3.17 when comes out also. any incompatibility over 1.3.17 beta atm ?
