### ISSUE TITLE
UI-GRID not rendered properly

### ISSUE THREAD

**Issue by susharma-equinix** [angular-ui/ng-grid#3872]
Hi All,

When i populate the data inside the GRID the grid data is not shown properly.

![image](https://cloud.githubusercontent.com/assets/12180266/8373048/90112732-1c1b-11e5-9745-50880935624d.png)

Please check the image attached on how it looks.

Just to give a little bit on the placement, The grid is placed in col-md-8 division and another 4 columns are occupied by other elements.

so the html design looks something like this :

<div class="container-fluid" ng-controller="textController" ng-init="init()">
<div class="row">
<div class="col-md-4">
<form name="inputForm" class="form-group"></form>
<div>
<div align="left" ng-show="isGridVisible" class="col-md-8">
<div class="row">
<div class="col-sm-12">
<div class="gridStyle" ui-grid="gridOptions1" ui-grid-selection  ui-grid-grouping></div>
</div>
</div>
</div>
</div>

**Comment by c0bra** [comment]
Are you able to reproduce this in a plunker?

**Comment by susharma-equinix** [comment]
I identifed the problem Brain.

The problem is when the Grid is assigned in col-md-8 of the bootstrap you need to set the proper width for each column else the column width will be set automatically like above.

To conclude : Setting the column width solved the issue.

Thanks for prompt reply.

**Comment by c0bra** [comment]
Interesting. I wasn't able to reproduce in a plunker: http://plnkr.co/edit/awvzMZVVKbwqUdaIlnMF?p=preview

Can you show me how to set it up so it results in your issue above?

**Comment by susharma-equinix** [comment]
Hi,

The exact problem was related to alignment as well as rendering.

align="right" will it self render the data in a wrong way. 

http://plnkr.co/edit/Z20UpAc1iISPj2QcglsF?p=preview
Am not able to reproduce the exact problem.

Thanks,
Suraj

**Comment by c0bra** [comment]
Why would you use `align="right"`? Wasn't that mostly for tables pre-HTML5?

**Comment by susharma-equinix** [comment]
Yes it is.

I wanted something else out of it which was wrong. Closing the issue.
