### ISSUE TITLE
Problem Show Columns resizing

### ISSUE THREAD

**Issue by MaiconBG** [angular-ui/ng-grid#3878]
I have the grid on the tab, when I change the tabs misaligns columns:
GRID:
                enableRowSelection: true,
                enableSelectAll: true,
                selectionRowHeaderWidth: 30,
                rowHeight: 30,
                enablePaging: true,
                enableHorizontalScrollbar: 0,
                enableVerticalScrollbar: 0,
                enableColumnResizing :  false,
and use this:
$interval(function() {
                    $scope.gridApi.core.handleWindowResize();
 }, 10, 500);

![image](https://cloud.githubusercontent.com/assets/11874085/8385524/f71df740-1c1e-11e5-910d-b4f14a4dd778.png)

how to solve this problem?

**Comment by MaiconBG** [comment]
it happens in all browsers

**Comment by PaulL1** [comment]
Have you looked at http://ui-grid.info/docs/#/tutorial/108_hidden_grids

The general rule with tabs is that you should put an ng-if around the grid, and only render the grid if the tab is currently visible.  This will greatly improve your application performance - you won't be rendering grids that people can't see.

**Comment by MaiconBG** [comment]
thanks resolved!
