### ISSUE TITLE
column getting overlapped in ie when navigating between pages. please help.

### ISSUE THREAD

**Issue by sivaecekrr** [angular-ui/ng-grid#3882]
I have ng grid in two pages and column getting overlapped in IE9 when navigating between pages but its working fine in chrome and firefox. I have attached screenshot.
![capture](https://cloud.githubusercontent.com/assets/9946938/8393078/c2fae26c-1d1c-11e5-9be9-0bdbd9a0f7bf.PNG)

**Comment by c0bra** [comment]
Does it work as expected in IE10?

**Comment by sivaecekrr** [comment]
Issue occurs due to inner style given in some template file and it has been fixed. Thanks for response :-)
