### ISSUE TITLE
Inline adding new row

### ISSUE THREAD

**Issue by xforceco** [angular-ui/ng-grid#3883]
Would it be possible to add a new row which has empty content to the table by an external button?
It is attempted to allow user to add a new row and type the content he/she wants inline.

**Comment by c0bra** [comment]
Yes that is possible. Just splice in a row that has `null` for all your columns into your dataset wherever you want it.

**Comment by xforceco** [comment]
I see, it works. Thank you :D

**Comment by annoure** [comment]
hello,
Can you share your implementation for this inline editing. Thanks
