### ISSUE TITLE
Selected Items in the footer just keeps incrementing and never resets

### ISSUE THREAD

**Issue by susharma-equinix** [angular-ui/ng-grid#3891]
Hi All,

Am having this problem where the selected Items just keeps increasing the count even after removing the row from the data using splice.

Even after a new data is loaded the selectedI tems in the footer is not adjusted.

I tried to address this problem by adding the footerTemplate but thats not being displayed properly.

Can some one please help on this at the earliest.

**Comment by susharma-equinix** [comment]
I actually solved the issue by using custom footer i.e. by adding 
showGridFooter:true,
gridFooterTemplate: '<div class="gridStyle">Total Item(s) : {{grid.appScope.myGridData.length}}. Selected Item(s) : {{grid.appScope.gridApi.selection.getSelectedRows().length}}.</div>',

But the actual issue still exist.

**Comment by PaulL1** [comment]
Selected rows are stored in a cache.  When you delete a row it doesn't get removed from the cache. If you are selecting rows then deleting them, you should use the API to unselect the row before you delete it.

**Comment by susharma-equinix** [comment]
Paul,

Thanks alot for the early response.

$scope.gridApi.selection.clearSelectedRows(); worked for me.

Thanks
