### ISSUE TITLE
Multi select icon in "all features" example got messed up

### ISSUE THREAD

**Issue by manikawnth** [angular-ui/ng-grid#3908]
Multi select icon in "all features" example got messed up just an hour ago.
The side drop down menu that exports pdf, csv, the icon is also not working

**Comment by AgDude** [comment]
Looks like all of the font icons are broken.

**Comment by JLLeitschuh** [comment]
Its working fine for me. Try clearing your browser cache.
This can happen while developing sometimes. Normally I just do a `grunt clean build` and it fixes it. Perhaps travis didn't clean fully during the last merge?

**Comment by AgDude** [comment]
Fixed for me this morning. This was probably an issue with cache somewhere.
