### ISSUE TITLE
Extra column next to selection

### ISSUE THREAD

**Issue by susharma-equinix** [angular-ui/ng-grid#3910]
Hi All,

I have searched all the documentation but am unable to actually fix this problem.

What is this extra column next to selection i.e. when selectAll and enableRowSelection is set to true am getting this extra column next to selection column in ui-grid

![image](https://cloud.githubusercontent.com/assets/12180266/8469464/cd9ac68a-20ad-11e5-9cc6-0cff8b5fb496.png)

**Comment by JLLeitschuh** [comment]
Its the group by row. If you click the drop down menu on a column and group by it then the expand button will appear there.

**Comment by susharma-equinix** [comment]
Thanks alot for clarification

**Comment by PaulL1** [comment]
There is an option that will cause that column to only show if there is something grouped.  I can’t recall the name of it though.

Paul Lambert
paul@planar.id.au
+61 411 385 488
+64 21 385 488

**Comment by susharma-equinix** [comment]
Paul,

Please let me know if by any chance you remember the option.

Thanks,
Suraj

**Comment by PaulL1** [comment]
`treeRowHeaderAlwaysVisible`.  Refer http://ui-grid.info/docs/#/tutorial/209_grouping

**Comment by susharma-equinix** [comment]
Paul cant thank you enough...:)

Solved my problem.
