### ISSUE TITLE
ui-bootstrap top tooltip cannot be displayed on the first row

### ISSUE THREAD

**Issue by xforceco** [angular-ui/ng-grid#3936]
![or1](https://cloud.githubusercontent.com/assets/12808889/8518961/597678ba-2401-11e5-8e6d-fd54e80055a1.png)

For the first pic, I hover on second row and it works.
For the second pic, I hover on first row and it is hidden.

I have checked the code, and found that the rows have been wrapped in a div that uses 'overflow: scroll', when I change it to 'visible' it works but the other rows become out of position.

any hope to fix it to make it work with ui-bootstrap?

**Comment by c0bra** [comment]
You'll probably need to make the tooltip `append-to-body`. The grid has to prevent its contents from overflowing.

Read this for more info: http://brianhann.com/6-ways-to-take-control-of-how-your-ui-grid-data-is-displayed/#tooltips

**Comment by xforceco** [comment]
Thank you very much for the kind help! It works like a charm :D

**Comment by StevenDewey** [comment]
Thank You!
