### ISSUE TITLE
How to remove Columns option from grid menu

### ISSUE THREAD

**Issue by yiniesta** [angular-ui/ng-grid#3948]
I want to use grid menu in my ui-gird but I don't want the Columns option to set show/hide columns.I only want what I custom.How can I do? Thanks.
![image](https://cloud.githubusercontent.com/assets/6304413/8549264/7dbcc76e-24fc-11e5-8476-326700ba1097.png)

**Comment by PaulL1** [comment]
Check the gridOptions, there's an option to not show the show/hide columns.  Check also the grid menu tutorial.

**Comment by JLLeitschuh** [comment]
http://ui-grid.info/docs/#/api/ui.grid.class:GridOptions
Have a look at `gridMenuShowHideColumns`

**Comment by rahi-rajeev** [comment]
@ #5958
