### ISSUE TITLE
last column sort arrow wrong display

### ISSUE THREAD

**Issue by lvostinar** [angular-ui/ng-grid#3961]
This last commit from https://github.com/angular-ui/ng-grid/issues/1671 breaks the display of last column for us. We use no grid menu. See:
http://plnkr.co/edit/tM4e5Ng8dcJfKM6ZdKl7?p=preview The sort arrow of last column is displayed wrong.

I think:
`ng-class="{'ui-grid-column-menu-button-last-col': isLastCol}"`

should become:

`ng-class="{'ui-grid-column-menu-button-last-col': isLastCol && grid.options.enableGridMenu}"`

**Comment by JLLeitschuh** [comment]
I like this fix. If you want to make a PR to fix this we'd probably accept it.

**Comment by lvostinar** [comment]
Created pull request.
